### ISSUE TITLE
Kubernetes version wrong on Windows nodes

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1002]
Windows binary versions report the wrong version. These agents are v1.6.6

```
$ k get nodes
NAME                    STATUS    AGE       VERSION
40278acs9000            Ready     3h        v1.6.4-beta.0.147+2b3fc68910b4dd
40278acs9001            Ready     3h        v1.6.4-beta.0.147+2b3fc68910b4dd
k8s-master-40278883-0   Ready     3h        v1.6.6
```

**Comment by colemickens** [comment]
@seanknox how do we know know the agents really are built from 1.6.6 code?

**Comment by seanknox** [comment]
That's the good word from @JackQuincy and @JiangtianLi

**Comment by JiangtianLi** [comment]
@seanknox New zip uploaded. We can close this issue now.

**Comment by seanknox** [comment]
Awesome, thanks. We should add a test to confirm that API versions match on nodes and master, something needed for both Linux and Windows. Can you roll out a Windows cluster and post a screenshot showing versions and we'll close this one?

**Comment by JiangtianLi** [comment]
screenshot attached (sorry for the delay since there was some issue in CDN to propagate till now).
![k8s166](https://user-images.githubusercontent.com/25217557/28381690-97eb3dd8-6c70-11e7-9272-c786e8bfec8d.PNG)

**Comment by seanknox** [comment]
Great, thanks @JiangtianLi!
