### ISSUE TITLE
No DNS resolution and Internet access from Kubernetes POD on Windows

### ISSUE THREAD

**Issue by akava** [Azure/acs-engine#1007]
**Is this a request for help?**:
Yes, request for help.
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
---
Cannot tell. I'm using "az acs create --orchestrator-type=kubernetes" in Azure
Is able to run whatever command you suggest to identify that.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes. v1.6.6 (Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z")

**What happened**:
Newly deployed POD (based on "microsoft/aspnet" docker image) doesn't have Internet access nor DNS names are resolved.
Windows node itself has access to Internet

**What you expected to happen**:
the POD deployed have both Internet and DNS name resolution

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy Kubernetes cluster via "az acs create --orchestrator-type=kubernetes"
2. Deploy next pod to the kubernetes: https://gist.github.com/akava/226d7dadaa374d6f77cf1fdf36403dc4
3. Attach to the POD: "kubectl exec -it win-asp powershell"
4. Run: nslookup google.com:
Result:

>    PS C:\> nslookup google.com
>    Server:  UnKnown
>    Address:  172.20.32.1
> 
>    *** UnKnown can't find google.com: Server failed

5. Run: "Invoke-WebRequest -URI https://google.com"
Result:
>    Invoke-WebRequest : The remote name could not be resolved: 'google.by'

6. Add google's IP to hosts:
"74.125.232.231 google.com"  | Add-Content -PassThru "$env:windir\System
32\drivers\etc\hosts"
7. run the request again: Invoke-WebRequest -URI https://google.com
Result: 

>    Invoke-WebRequest : Unable to connect to the remote server

8. Attach to the windows node. Test that internet and DNS works (I attached via Remote Desktop)
   
**Anything else we need to know**:
No

**Comment by LukeDearden** [comment]
I had this same problem last week and found this Issue https://github.com/Azure/acs-engine/issues/959 which was fixed by this https://github.com/Azure/acs-engine/pull/967

If you build acs-engine from here and generate your own templates containers work as expected.

**Comment by akava** [comment]
@LukeDearden thanks. Will try that.
Acs Team, any idea on when the fix will be deployed to Azure?

**Comment by mfaizanse** [comment]
I deployed the k8s windows cluster using the acs-engine method and deployed my containers and it was working fine. But now the issue is that after some time the same container fails to connect to Azure SQL and Azure Table. I have tried nslookup www.google.com inside container and it is working. If I redeploy the pod then it again starts working but again after some time, the same issue occurs.

In error which I gets:
`The remote name could not be resolved: '<domain name>'`

**Comment by tiagorosendo** [comment]
Any update ?

**Comment by tiagorosendo** [comment]
any update? pods continue loosing connection with azure sql

**Comment by ajorkowski** [comment]
This issue seems related to #558 - disabling the DNS cache seems to be a solid workaround for me.
