### ISSUE TITLE
`acs-engine version` is unset after `make build`

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1015]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: v0.3.0 

---

`acs-engine version` returns `unset` for some users after running `make build`, see https://github.com/Azure/acs-engine/issues/1012 toward the bottom. I also saw this on @lachie83's MacOS system running go v1.8.3.

**Comment by wbuchwalter** [comment]
Also here: https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/issues/34#issuecomment-315839132 using go on Windows.

**Comment by lachie83** [comment]
I've dug into this a little and it appears that have CDPATH set is messing with the relative paths in the go build command. The removal of CDPATH from my env fixed this issue.
