### ISSUE TITLE
Can't list the acs created by commandline 

### ISSUE THREAD

**Issue by VincentLiu028** [Azure/acs-engine#102]
I use the xplatform cli 0.10.0, I followed the readme docuement and created acs cluster with docker swarm sucessfully with below command
$ azure group deployment create \
    --name="<DEPLOYMENT NAME>" \
    --resource-group="<RESOURCE_GROUP_NAME>" \
    --template-file="./_output/<INSTANCE>/azuredeploy.json" \
    --parameters-file="./_output/<INSTANCE>/azuredeploy.parameters.json
The problem is that when I run azure acs list -s {subscription id} -g {resource group name}, I get empty response. 
But when I use portal->new->containers->Azure Container Service to create a new docker swarm cluster with UI, I get response from command azure acs list -s {subscription id} -g {resource group name}.
Is there any differences between ACS cluster created with portal and command line?
![untitled1](https://cloud.githubusercontent.com/assets/17308665/20338519/8d1cf834-ac12-11e6-887a-ad36089cb846.png)

**Comment by colemickens** [comment]
Hi @VincentLiu028,

This is expected. "ACS-Engine" is a more IaaS-based solution. In this case, you are just creating raw Azure resources, so there's no actual "Container Service" object created.

**Comment by VincentLiu028** [comment]
Got it. Thanks for the information.
