### ISSUE TITLE
Support for Docker CE 17.06

### ISSUE THREAD

**Issue by NatashaHull** [Azure/acs-engine#1021]
**Is this a request for help?**:
No.

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Request

**What version of acs-engine?**:
Latest

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**:
Swarmmode aka Docker CE for ACS

We were deploying a Docker swarm using templates generated by a two month-ish old ACS engine that was not pinned to any version of Docker. Once we saw we were using 17.05, we switched to deploy using `docker stack`. 

We have since pulled master and regenerated the templates to find that we are now pinned at 17.03 which is incompatible with the way we deploy our containers. 

Now that 17.06 is stable we'd like to have the option to use it rather than roll back the way we do our deploys.

**Comment by seanknox** [comment]
Hi @NatashaHull, just to confirm, are you using Docker Swarm or Docker Swarm Mode?

**Comment by NatashaHull** [comment]
@seanknox We are using Docker Swarm Mode.

**Comment by atld** [comment]
Hi @seanknox. Do you have an estimation when 17.06.* will be supported? Should be a hopefully easy fix (just changing DOCKER_CE_VERSION in [configure-swarmmode-cluster.sh](https://github.com/Azure/acs-engine/blob/master/parts/configure-swarmmode-cluster.sh)) and some regression test efforts. Thanks.

**Comment by afomi** [comment]
Checking in on this issue. Any ETA or visibility on an updated release?

The [Release Notes](https://docs.docker.com/docker-for-azure/release-notes/) show 17.06 is now stable.

Thanks!

**Comment by afomi** [comment]
Any movement on this issue?

We're maintaining a fork to support 17.06 and would love to move back to a stable branch.

Thanks!

**Comment by fbuser1** [comment]
+1

**Comment by fbuser1** [comment]
+1

**Comment by fbuser1** [comment]
+1

**Comment by CecileRobertMichon** [comment]
Moby is now default as of https://github.com/Azure/acs-engine/releases/tag/v0.25.0
