### ISSUE TITLE
How to upgrade DC/OS master VM sizes?

### ISSUE THREAD

**Issue by rozele** [Azure/acs-engine#1028]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
v0.3.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DC/OS 1.9

**What happened**:
When I upgrade the VM size for the DC/OS master instances and do a PUT, all master instances in an availability set are simultaneously upgraded.

**What you expected to happen**:
This is what I expected to happen, but I'm wondering if there is any suggested approach for rolling out VM size upgrades to master instances to keep ZooKeeper healthy.

**How to reproduce it** (as minimally and precisely as possible):
1. Generate an ARM template for DC/OS from acs-engine
2. Deploy the template
3. Change the master VM size in the ARM template
4. Re-generate the ARM template with acs-engine
5. Re-deploy the template

**Anything else we need to know**:

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
