### ISSUE TITLE
High TCP timeout and retry values

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1032]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

Because the Kubelet does not perform application-layer heartbeating, the only way it knows the connection has been lost is when the kernel decides so. As mentioned above, Kubernetes does configure keepalives but these aren't at play here since they are only sent after 2 hours of inactivity by default (`net.ipv4.tcp_keepalive_time`).

Instead, TCP retransmissions account for the 15 minute delay. The default value for `net.ipv4.tcp_retries2` means that with exponential backoff, it takes ≈15m25s before the kernel kills the connection. Kubernetes places no timeout on its HTTP requests so the "update node status" request hangs for this time. When the 15 minutes expire, all the requests fail and Kubernetes reconnects. This situation is not entirely specific to the use of an ELB – if a directly-connected apiserver becomes partitioned or dies ungracefully, it will take 15 minutes before the Kubelet attempts to reconnect.

## AC
- Lower `net.ipv4.tcp_keepalive_time` and `net.ipv4.tcp_retries2` on agents to more aggressive values.
- Important: research what these should be

https://github.com/kubernetes/kubernetes/issues/41916#issuecomment-312428731

**Comment by narasi** [comment]
Hello,

Just a concerned soul who is facing the `NodeNotReady` issue intermittently on our Kubernetes cluster ( v1.5.3)

Since the upstream issue is fixed, do we have a fix for this yet? (apart from the partial mitigation)
