### ISSUE TITLE
Kubernetes v1.7.1

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1034]
## Acceptance Criteria
- Users can install Kubernetes v1.7.0 on Linux

**Comment by seanknox** [comment]
@JiangtianLi do you have bandwidth to build Kubernetes v1.7.1 for Windows? We have Linux v1.7.1 ready to go for release this week. If not we can queue Windows support for next release.

**Comment by JiangtianLi** [comment]
@seanknox I can make build for 1.7.1 this week. The major problem is to solve v1.7.0 Windows container issue. The delta between 1.7.0 and 1.7.1 should be small.

**Comment by seanknox** [comment]
Great, thanks!
