### ISSUE TITLE
How can I deploy kubeClusterCidr falling into custom vNet?

### ISSUE THREAD

**Issue by milla** [Azure/acs-engine#1037]
**Is this a request for help?**:
---
request

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
issue/feature request

**What version of acs-engine?**:
---
latest

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes

**What happened**:
I have an existing vnet, where I need to keep services calling backend-service per VPN configured in the same resource group. Here're some waysI tried and failed, Say I have a vnet whose cidr is 172.21.88.0/21, as figured out some counter parts, I have the table

![image](https://user-images.githubusercontent.com/297531/28365654-f991f39c-6cbb-11e7-9809-c29a231ef0de.png)

1. I changed firstConsecutiveStaticIP in input template, set vnetSubnetId properly;
2. generate json files, edited azuredeploy.json the following two IPs
"kubeServiceCidr"
"kubeDnsServiceIp"
3. changed kubeClusterCidr 
4. deploy to Azure, set subnet to routetable

The reason why I have to do 2,and 3 is that the backend-VPN configures only for 172.xx as configured in vnet. I.e, If skipped step 2 and 3, kubernetes runs well, yet cannot access the backend service.

Now, with all the above changes, all the certificates are generated for 10.xxx.xx.xx IPs, and failed in complaints that cert is not for 172.xx..xx.xx.

**What you expected to happen**:
Support custom vnet and kubernetes cluster cidr

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by anhowe** [comment]
Here is the PR that will help adjust the pod and service networks including the certificates: https://github.com/Azure/acs-engine/pull/546.  I'll ping the team to see if we can get this pushed through.

**Comment by CecileRobertMichon** [comment]
Closing as #546 was merged.
