### ISSUE TITLE
CI: remove "in progress" label check on acs-bot

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1040]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE/CHORE

---

Our backlog tool (waffle.io) uses "in progress" labels to items that are in flight. acs-bot won't build if this label is applied.

**Comment by colemickens** [comment]
It looks like the bot is still different than it was a couple weeks ago. Is it intentional that I have to manually trigger a build instead of it just being built when I open the PR?
