### ISSUE TITLE
k8s: windows: instance name differs from computer name, breaking things

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#105]
Let's consider a Windows node, as it were deployed by Anthony's Windows branch: https://github.com/Azure/acs-engine/tree/anhowe-wink8s.

## k8s-windowspool2-250945250

This node is identified in Azure by `k8s-windowspool2-250945250`.

This node has a hostname of `25094acs0901` (aka, the MachineName in Windows is `25094acs0901`)

The `kubelet` is overriding the hostname so that the apiserver identifies it as `k8s-windowspool2-250945250`.

However, the Kubernetes control plane expects to be able to resolve the registered hostname back to the actual machine (this is used for logs and remote pod connectivity). Unfortunately, since the hostname in Windows is `25094acs0901`, there is never an internal DNS record created for `k8s-windowspool2-250945250`, hence the errors we observed during KubeCon that look like this:

```
Get https://k8s-agentpool2-299742071:10250/containerLogs/default/wordpressapp-ext-h9t8c/wordpressapp-ext?timestamps=true: dial tcp: lookup k8s-agentpool2-299742071 on 168.63.129.16:53: no such host
```

The first fix that comes to mind is just not overriding the hostname, but then the Routes won't be created properly because the cloudprovider expects to be able to look up the VM instance via ARM using the hostname.

**Why is Azure so incredibly limiting when it comes to Windows hostnames?** The 15 character limit stems from NetBIOS which, afaik, hasn't been used in Windows for a very long time.

**Comment by colemickens** [comment]
cc: @anhowe this is why logs and remote exec into a container doesn't work in Windows. It's possible this affects other things (though very likely it does not affect kube-proxy or the Service network).

**Comment by colemickens** [comment]
Actually, looks like we might get lucky and avoid this problem on 1.5: https://github.com/kubernetes/kubernetes/pull/33718

`v1.5.0-alpha.1` is broken in a different way for Azure right now, but when there's a new alpha cut, we should consider moving the Windows branch over to it. I also have a `hyperkube-amd64` container on my docker hub that was cut from master if someone wants to test this and see if it at least gets remote container exec and logs works.

**Comment by anhowe** [comment]
fixed by https://github.com/Azure/acs-engine/pull/285/files
