### ISSUE TITLE
switch "in progress" auto-labeler to execute as acs-bot account

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#1053]
Meta nit bug report

The label management could be done by the @acs-bot account instead of @jackfrancis.

**Comment by seanknox** [comment]
I'm not sure why it shows up as Jack; I just reinstalled the webhook via the @acs-bot user. We'll see. Changes made on waffle.io will show up as coming from the person who made them.

**Comment by sgoings** [comment]
@seanknox I believe this is fixed now, yes?
