### ISSUE TITLE
"github.com/go-playground/pure/examples/middleware/logging-recovery" packaged moved

### ISSUE THREAD

**Issue by sylr** [Azure/acs-engine#1054]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: HEAD

---

I've got this message when installing acs-engine

```
sylvain@ubuntu-1604-dev:~$ mkdir $GOPATH
sylvain@ubuntu-1604-dev:~$ go get github.com/Azure/acs-engine
sylvain@ubuntu-1604-dev:~$ go get all
package github.com/go-playground/pure/examples/middleware/logging-recovery: cannot find package "github.com/go-playground/pure/examples/middleware/logging-recovery" in any of:
        /usr/lib/go-1.8/src/github.com/go-playground/pure/examples/middleware/logging-recovery (from $GOROOT)
        /home/sylvain/gopath/src/github.com/go-playground/pure/examples/middleware/logging-recovery (from $GOPATH)
```

It seems that package "github.com/go-playground/pure/**examples**/middleware/logging-recovery" moved to "github.com/go-playground/pure/**_examples**/middleware/logging-recovery"recovery/.

**Comment by hmarcelodn** [comment]
Same issue over here
