### ISSUE TITLE
enable mesos role definition during cluster generation

### ISSUE THREAD

**Issue by julienlau** [Azure/acs-engine#1055]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
version build from master of todat (commit Id 3ca208168ca284245adb776e00b88b7aa356ff29)
---

Recently attributes were added to DCOS cluster definition with acs-engine. This is really helpful for placement constraints during services deployments.
If I set in my json input definition :
"customNodeLabels" : {
          "agent" : "marathon1",
          "env" : "PROD"
        }
I can retrieve those two labels on DCOS nodes configurations.
Spark service on mesos uses the role attribute of mesos/DCOS.
It would be nice if I could define these roles during cluster definition like:
"customNodeRole" : "spark"
with a default value to 
"customNodeRole" : "*"

Thanks and regards,
Julien

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DCOS 1.9.0

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
