### ISSUE TITLE
additionnal disks of type MOUNT are not correctly enrolled during DCOS cluster creation

### ISSUE THREAD

**Issue by julienlau** [Azure/acs-engine#1056]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
last version from master ie commit id 3ca208168ca284245adb776e00b88b7aa356ff29
---

I want a DCOS cluster with agent providing additionnal DISKS of type MOUNT directly in MESOS offers.
As of today, if I define a DCOS 1.9.0 cluster with 4 additional disks per agent like this:
"agentPoolProfiles": [
      {
        "name": "marathon1",
        "count": 3,
        "vmSize": "Standard_D4_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "diskSizesGB": [1023, 1023, 1023, 1023],
      },

The disks are not subscribed in DCOS/MESOS offers and I cannot deploy services that use 1000GB.
In fact if in the DCOS UI, I go to nodes->10.x.x.x->Details I cannot see the additional disk space available.

However after doing some tweaking on source file dcoscustomdata190.t I manage to format and mount correctly the additionnal disks during cloud-init and MESOS see the resources for offers.
I hard coded it for 8 disks, but it deployment also works if no additionnal disks are present.
See code in https://github.com/julienlau/acs-engine/blob/geosys19/parts/dcoscustomdata190.t

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DCOS1.9.0

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
