### ISSUE TITLE
Hardcoded kubeServiceCidr

### ISSUE THREAD

**Issue by sylr** [Azure/acs-engine#1057]
**Is this a request for help?**: Maybe

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of acs-engine?**: HEAD

---

Unless I am mistaken it seems that kubeServiceCidr variable is harcoded to 10.0.0.0/16 in [parts/kubernetesmastervars.t](https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastervars.t#L113) and it can not be overwritten.

Is there a reason for the service subnet to be hardcoded ?

I am using custom VNet and my goal here is to be able to talk to the kubernetes services from outside kubernetes but still from within the VNet and use the private network.

Regards.

**Comment by lachie83** [comment]
@sylr Yes you are correct and I agree that this should probably be configurable. Would you like to work on the PR for making this possible?

**Comment by JackQuincy** [comment]
https://github.com/Azure/acs-engine/pull/546 PR exists. We just need someone to update it with latest and validate the issues we pulled it out in the first place have been fixed. Namely that the Azure networking plugin doesn't just stop working when it is used.
