### ISSUE TITLE
Add scaling command to acs-engine

### ISSUE THREAD

**Issue by JackQuincy** [Azure/acs-engine#1060]
**Is this a request for help?**:
NO
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Request
---

We should make a scale command that could either take an old api model and a new api model, or just point to the old api model then prompt for new agent count values. We should then make a new deployment template and use our transform code to get it ready for deployment. We have this code in the service and would just need to copy it into acs-engine. The hardest part would be the code to poll for the current state of the cluster has diverged between the service and acs-engine as they are being used for different scenarios currently (upgrade vs scale) and we would want to merge those two into a single way to get the current state of the cluster.

**Comment by seanknox** [comment]
@slack @kris-nova how does this feature line up with work your team is doing, if at all?

**Comment by slack** [comment]
We will need both upgrade and scale (up/down).

**Comment by JackQuincy** [comment]
upgrade exists. to use "export ACSENGINE_EXPERIMENTAL_FEATURES=1" and it will be available for use.

**Comment by kim0** [comment]
@JackQuincy .. Just to be clear, to scale and/or upgrade. After exporting that variable, we'd simply edit the json file, recreate the ARM templates and redeploy them .. correct ? Thanks

**Comment by JackQuincy** [comment]
They would be more along the lines of the deploy command and actually do the deployment as well. As scale down and upgrade can't be done in a partial arm template deployment as they require deleting resources.  Upgrade has it's own json file type to describe how to do an upgrade. Scale hasn't been designed yet, but we could definitely just change the json file and make adjustments to the cluster to reach the goal state, as this is what happens in the service.

**Comment by wbuchwalter** [comment]
I was also looking into adding this feature to the autoscaler, or as a standalone. See https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/issues/40.

> Scale hasn't been designed yet, but we could definitely just change the json file and make adjustments to the cluster to reach the goal state, as this is what happens in the service.

How would you handle clusters with custom VNet? See https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/issues/34.
If you redeploy using ARM, the VMs have a dependency on the NSG, but the NSG needs to be removed to avoid service interruptions. It seems like a catch 22, unless I'm missing something?

**Comment by JackQuincy** [comment]
See https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/transform.go . Post template generation we go in and remove resources/dependencies that don't make sense for the operation we are doing.

**Comment by wbuchwalter** [comment]
My bad, by dependency I didn't mean `dependsOn`. When you deploy with a customVNet, on the virtual machine resource there is:
```
"networkSecurityGroup": {
          "id": "[variables('nsgID')]"
        }
```
Can we also remove that without causing any issue?

**Comment by JackQuincy** [comment]
No we need it, but there is no reason we can't know it. It doesn't depend on the NSG resource being in the template. Since it is a reference by ID not by reference to another resource in the template we can just use it if it already exists.
