### ISSUE TITLE
Sovereign cloud support for AzureGermanCloud and AzureUSGovCloud

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1066]
Add sovereign cloud support for AzureGermanCloud and AzureUSGovCloud

**Comment by weinong** [comment]
To test it, you need different Azure subscriptions for respective sovereign cloud. the current CI won't be effective.

**Comment by seanknox** [comment]
Will re-prioritize this if/when the PR owner confirms he's tested it.
