### ISSUE TITLE
DNS configure from ARM template for DCOS

### ISSUE THREAD

**Issue by JuneZhao** [Azure/acs-engine#1067]
**Is this a request for help?**:

---Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---Feature request

**What version of acs-engine?**:

---N/A

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DC/OS

**What happened**:

the DC/OS server run on Ubuntu.  They have a resolv.conf file that is populated with the primary dns servers, however DC/OS has its own internal DNS services within the cluster which is defined with the set forwarders at the time the DC/OS package is loaded.  As part of DC/OS’s DNS setup, there is a process that constantly rewrites the resolv.conf file with the resolver ip’s that were set at the time DC/OS was installed.

Therefore setting the dns servers for the vnet has no impact on the environment.  If I set the resolv.conf file to contain my internal DNS servers, the entries are constantly overwritten by the DNS server settings that were set (of defaulted) at the time of install.

The DCOS install package is provided as part of the ARM template we are using and the desired DNS settings are normally defined as part of the creation of the installation package prior to installing DC/OS.  Therefore, I am looking for a way to define specific DNS servers as part of the initial install of DC/OS.

**What you expected to happen**:

Per the DC/OS installation documentation, the desired DNS resolvers must be defined in a config.yaml file.  The ARM template does not allow for this.  Do we plan to expose the DNS setting from ARM template  part

**Comment by JuneZhao** [comment]
@kind/feature

**Comment by JuneZhao** [comment]
@kind/feature
@orchestrator/dcos

**Comment by JuneZhao** [comment]
label:kind/feature

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
