### ISSUE TITLE
Documentation missing details for region(s) generated kubconfig folder

### ISSUE THREAD

**Issue by OJDUDE** [Azure/acs-engine#107]
I managed to deploy a Kubernetes cluster successfully from the first time. It was actually great. I just noticed that the acs-engine created a kubconfig folder with server configuration for each supported region. I did not see the files   anywhere referenced in your docs on how to use. Can you please point to the docs that provide more details what to use these files for?

**Comment by anhowe** [comment]
Each region will get a separate DNS URL.  ACS-Engine is not aware of which region you will deploy to and generates a kubeconfig for each region.  Once you have deployed to the region, you just use the appropriate kubeconfig for the region deployed to.

**Comment by anhowe** [comment]
@squillace can you help with documentation around this?

**Comment by ppanyukov** [comment]
@anhowe :

> you just use the appropriate kubeconfig for the region deployed to

not sure this clarified anything for me, use how? :)

**Comment by jackfrancis** [comment]
@ppanyukov @OJDUDE we have lots of color aroung `kubeconfig` regions in this doc:

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md

That is now linked to from the general purpose acsengine doc, so hopefully folks in the future will more easily find this info.
