### ISSUE TITLE
Documenation missing details on scale up\down scenarions

### ISSUE THREAD

**Issue by OJDUDE** [Azure/acs-engine#108]
In the documentation, there was a reference on how to use the API JSON file to scale up \ down the deployment. I did not see further details. How can I add \ remove nodes to an existing agents, master or add \ remove new agent pools?

**Comment by anhowe** [comment]
this is a duplicate of #108 and #108 has more info so closing this one.

**Comment by jauco** [comment]
@anhowe I think you meant to reference another issue than #108 (because this is issue #108) I can't find the other one though. Which issue contains more information?

**Comment by anhowe** [comment]
#109 provides more details.
