### ISSUE TITLE
Logging about duplicate proto type registration on using kubectl

### ISSUE THREAD

**Issue by yuvipanda** [Azure/acs-engine#1083]
**Is this a request for help?**: Sortof?

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: v0.4.0

---
**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.7.1, 50 node cluster across 2 agent pools of 25 each

**What happened**:

Running any kubectl command works, but produces the following output:

```
2017-07-22 21:16:16.761796 I | proto: duplicate proto type registered: google.protobuf.Any
2017-07-22 21:16:16.761847 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-07-22 21:16:16.761864 I | proto: duplicate proto type registered: google.protobuf.Timestamp
```

over and over again.

I can't repro this on a local kubectl that came off google's apt repository.

**What you expected to happen**:

No logging error messages?

**How to reproduce it** (as minimally and precisely as possible):

Creating a kubernetes cluster with 1.7.1 and running any kubectl commands from master seems enough.

**Comment by yuvipanda** [comment]
I'm using upstream kubectl (from https://kubernetes.io/docs/tasks/tools/install-kubectl/) and it works fine now.

**Comment by seanknox** [comment]
Hey @yuvipanda, are you getting this error with `kubectl` installed on the acs-engine provisioned Kubernetes master?

**Comment by yuvipanda** [comment]
Yup!

On Jul 26, 2017 10:00 AM, "Sean Knox" <notifications@github.com> wrote:

Hey @yuvipanda <https://github.com/yuvipanda>, are you getting this error
with kubectl installed on the acs-engine provisioned Kubernetes master?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/acs-engine/issues/1083#issuecomment-318117283>,
or mute the thread

**Comment by orkun1675** [comment]
Can confirm:
```
azureuser@k8s-master-40103400-0:~$ kubectl get nodes
2017-07-28 22:25:13.330017 I | proto: duplicate proto type registered: google.protobuf.Any
2017-07-28 22:25:13.330069 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-07-28 22:25:13.330233 I | proto: duplicate proto type registered: google.protobuf.Timestamp
NAME                        STATUS                     AGE       VERSION
k8s-agentpool1-40103400-0   Ready                      57s       v1.7.1
k8s-agentpool1-40103400-1   Ready                      57s       v1.7.1
k8s-agentpool1-40103400-2   Ready                      58s       v1.7.1
k8s-master-40103400-0       Ready,SchedulingDisabled   1m        v1.7.1
```

**Comment by ivanthelad** [comment]
using the latest acs-binary, https://github.com/Azure/acs-engine/releases/tag/v0.5.0,  to deploy kubernetes 1.7.2 results in the below output. 

`ivan@k8s-master-22238924-0:~$ kubectl  get node
2017-08-07 21:26:44.129565 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-07 21:26:44.129641 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-07 21:26:44.129656 I | proto: duplicate proto type registered: google.protobuf.Timestamp
NAME                        STATUS                        AGE       VERSION
k8s-agentpool1-22238924-0   NotReady                      34s       v1.7.2
k8s-agentpool1-22238924-1   NotReady                      39s       v1.7.2
k8s-agentpool1-22238924-2   NotReady                      40s       v1.7.2
k8s-agentpool2-22238924-0   Ready                         34s       v1.7.2
k8s-agentpool2-22238924-1   NotReady                      36s       v1.7.2
k8s-agentpool2-22238924-2   NotReady                      37s       v1.7.2
k8s-master-22238924-0       NotReady,SchedulingDisabled   37s       v1.7.2
ivan@k8s-master-22238924-0:~$ kubectl  get po`

**Comment by lachie83** [comment]
This is an issue with kubectl in hyperkube. https://github.com/kubernetes/kubernetes/issues/48924

Other than annoying, It appears to be benign

**Comment by lachie83** [comment]
We could pull kubectl from another source to remedy
