### ISSUE TITLE
Reboot nodes after security updates are installed

### ISSUE THREAD

**Issue by SaaldjorMike** [Azure/acs-engine#1087]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
OS security updates were installed on the nodes.

**What you expected to happen**:
Certain packages require nodes to be restarted, e.g. kernel updates, in this case I'd guess there should be some official/preferred way to gracefully reboot all nodes in the cluster. I know stuff like CoreOS Container Linux can make use of certain reboot strategies to make this happen. Is something similar is on the roadmap here as well?

I could manually (or scripted) do it, but seems like something that not only I would want.

Any feedback is much appreciated!

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jalberto** [comment]
my suggestion would expand this one, I would love to see ACS using coreos as default
