### ISSUE TITLE
Kubernetes vm scale up problem

### ISSUE THREAD

**Issue by canthefason** [Azure/acs-engine#109]
When I try to scale up the VM instances on Kubernetes via Container service,  it does not allow me to create a new node and returns the error below. Besides, it messes with my cluster, and it does not  allow me to reach to apiserver anymore.

```
Failed to save container service 'containerservice-[name]'. Error: Provisioning of resource(s) for container service 'containerservice-[name]' in resource group '[name]' failed with errors: Resource type: Microsoft.Compute/virtualMachines, name: k8s-agent-1F791599-2, id: /subscriptions/[subscriptionid]/resourceGroups/[name]/providers/Microsoft.Compute/virtualMachines/k8s-agent-1F791599-2, StatusCode: BadRequest, StatusMessage: \n {
  "error": {
    "code": "InvalidParameter",
    "target": "vmSize",
    "message": "The value of parameter vmSize is invalid."
  }
}
```

**Comment by canthefason** [comment]
I am still investigating this issue. To be more specific, after this scale up request, I can still reach the apiserver via the insecure port. It looks like a problem in network level. I will keep updating with my findings.

**Comment by canthefason** [comment]
yes, it is definitely related to the VM types. When I try to create my cluster from the UI, it sets the agent VM value as Standard_DS1. It works fine for initial creation, but it does not work at all when it comes to scaling up the agents. 

Then I tried to create my cluster with azure-cli. Initially, I set Standard_DS1 as the VM value, and it did not get validated. Later on, I picked the same VM value with example/kubernetes.json as Standard_D2_v2, and both cluster creation and scaling worked like a charm.

**Comment by colemickens** [comment]
Are you using ACS-Engine, or are you using the actual Container Service and trying to scale it via a PUT?

**Comment by canthefason** [comment]
In the beginning, I used UI. But now I am using ACS-Engine. 

There is one last thing I realized that might be helpful for you: I followed [these steps](https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md) to generate necessary templates. After that, I checked azuredeploy.json, and I even did not see Standard_DS1 under "agentpool1VMSize.allowedValues".

**Comment by colemickens** [comment]
cc: @anhowe for the question about the list of VM sizes.

Scaling in ACS itself is not yet supported, and in fact I believe we will soon be blocking updates until we implement scale up/scale down for Kubernetes.

With ACS-Engine, you can use the outputed "apimodel.json" file, change the desired values, and then re-deploy the template. There is an issue (#108) to document this process which we will do soon.

**Comment by kaubry** [comment]
Any estimation by when we can expect scaling functionality on Azure ?
In the meantime, is there any documentation on how to add nodes manually ?
Do you know if this will need to redeploy the cluster or if the already created cluster can be "upgraded" to support new functionalities ?

**Comment by colemickens** [comment]
@kaubry In the reply just above yours I described how acs-engine can be used to scale up/down.

>Do you know if this will need to redeploy the cluster or if the already created cluster can be "upgraded" to support new functionalities ?

You don't have to redeploy, but upgrading Kubernetes versions is currently a manual process. You can read a bit about that here. https://github.com/colemickens/azure-kubernetes-status/issues/15 We should document this in this acs-engine repo soon.

CC: @rgardler for timelines on scaling / upgrades. Not sure what sort of timeline specifics we're offering right now.

**Comment by kaubry** [comment]
@colemickens Thanks you for you quick reply. I manage to make everything work (upscale and upgrading Kubernetes version) but for scaling down, acs-engine doesn't seems to handle it. I need to manually remove the created VM and the corresponding network interface. Is it the right way to proceed or am I missing something ?

**Comment by colemickens** [comment]
@kaubry You are correct.

**Comment by timbrand** [comment]
> but for scaling down, acs-engine doesn't seems to handle it. I need to manually remove the created VM and the corresponding network interface. Is it the right way to proceed or am I missing something ?
Also, don't forget to download the OS disk of the agent. Otherwise you'll get a "TargetDiskBlobAlreadyExists" error when scaling up again.

**Comment by colemickens** [comment]
Thanks @timbrand , we need to document this process and that's a great point to include.

**Comment by anhowe** [comment]
To avoid the "TargetDiskBlobAlreadyExists", you will need to choose the option to delete the blob, when scaling down.

**Comment by anhowe** [comment]
@JackQuincy - this will be fixed when you submit https://github.com/Azure/acs-engine/pull/366/files.

**Comment by rocketraman** [comment]
The documentation added from pull #366 states that the NSG has to be removed, and the diff of `kubernetes_template.json` and `kubernetes_update_template.json` @ https://github.com/Azure/acs-engine/tree/master/examples/scale-up does show this removal.

However, I just tried a scale-up, and it worked with just changing the count and adding the offset parameters -- there was no need to remove the NSG.

**Comment by JackQuincy** [comment]
I should of been more specific if you don't remove the NSG any public services on the cluster will go unavailable for a period of between 2-10 mins is what I've seen reported.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rocketraman** [comment]
> if you don't remove the NSG any public services on the cluster will go unavailable for a period of between 2-10 mins is what I've seen reported.

Thanks for the clarification.

Would love to see a more permanent fix for the scaling up/down problem. This is certainly a key aspect of running a container orchestrator that should be seamless.

**Comment by anhowe** [comment]
Closing since main issue is solved.
