### ISSUE TITLE
Support localization in acs-engine

### ISSUE THREAD

**Issue by JiangtianLi** [Azure/acs-engine#1090]
ACS RP depends on ACS Engine API. However, currently ACS Engine is not localized and locale is en-us only. Therefore the error message returned by ACS Engine to ACS RP is not localized too. 

This issue tracks the support for localization in acs-engine, specifically the error message strings returned by acs-engine API.

**Comment by CecileRobertMichon** [comment]
@JiangtianLi can this issue be closed?

**Comment by JiangtianLi** [comment]
@CecileRobertMichon yes
