### ISSUE TITLE
Error starting/configuring docker swarm with docker 17.06

### ISSUE THREAD

**Issue by lonesomegeek** [Azure/acs-engine#1091]
While creating a swarm with the acs-template, it is using the old **/usr/bin/docker daemon** configuration while it seems to have changed in docker v17.06 to **dockerd**.

Here is more details:

Part of the log where the error occurs (/var/log/azure/cluster-bootstrap.log)

sudo bash -c 'echo "[Service]
    ExecStart=
    ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock
  " > /etc/systemd/system/docker.service.d/override.conf'
[...]
Docker is not healthy
+ ismaster
+ '[' swarmm-master-13957614- == swarmm-master-13957614- ']'
+ return 0
+ '[' 172.16.0.5 = 172.16.0.5 ']'
+ echo 'Creating a new Swarm on first master'
Creating a new Swarm on first master
++ hostname -i
++ hostname -i
+ docker swarm init --advertise-addr 172.16.0.5:2377 --listen-addr 172.16.0.5:2377
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Is this a request for help?**: I have manually updated the configurations on the master and agents and it is working well now.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: Latest, I think...

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: SWARM

**What happened**: See below

**What you expected to happen**: Docker agent to start accordingly to new setup with docker version 17.06

**How to reproduce it** (as minimally and precisely as possible): Create a new Swarm (1 master, 1 agent), the docker daemons will not start.

**Anything else we need to know**:

**Comment by SaaldjorMike** [comment]
There was a new build of acs-engine 4 days ago that changes in from running "docker daemon" to "dockerd". See more here: https://github.com/Azure/acs-engine/releases

I'd guess you're not running a build of acs-engine which contains that fix.

**Comment by lonesomegeek** [comment]
I'm using the template available here: https://github.com/Azure/azure-quickstart-templates/tree/master/101-acsengine-swarmmode

**Comment by amanohar** [comment]
@lonesomegeek, the template on Azure Quick Start templates is a couple of months ago so it's not using the latest change in ACS Engine of switch to dockerd. I recommend using Swarm Mode template from ACS Engine to create a cluster (and I will update quick start templates at some point).

**Comment by lonesomegeek** [comment]
Okay then! I'll mark this issue as closed. In the meantime, I'll test the images right from the ACS Engine.

Regards!
