### ISSUE TITLE
Add maxPods to Kubernetes configuration

### ISSUE THREAD

**Issue by ofiliz** [Azure/acs-engine#1102]
**Is this a request for help?**:

No.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature request.

---

**What version of acs-engine?**:

v0.4.0 / latest

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes, any version

**What happened**:

Kubelet accepts a "maxPods" argument that sets the maximum number of pods that can be scheduled on a node. It defaults to 110 pods. Acs-engine does not provide a mechanism to change maxPods.

**What you expected to happen**:

Adding maxPods to KubernetesConfig allows customers to specify a max limit appropriate for their scenarios and clusters.

Pods use actual IP addresses from Azure VNET space when CNI plugin is enabled. The number of IP addresses available per VNET is currently limited to 4096 by default. This limits the maximum size of clusters to 4096/110=37 nodes. The default maxPods value 110 is really for extreme cases, and allocating that many IP addresses by default is wasteful.

The proposed change changes the default value to 30 when CNI plugin is enabled. When CNI plugin is not enabled, the current default of 110 is preserved. Customers can set custom maxPods values appropriate for their scenarios.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

PR is coming.

**Comment by yuvipanda** [comment]
Does this mean right now an acs-engine made cluster can not have more than 4096 pods?

**Comment by ofiliz** [comment]
@yuvipanda No, there is no explicit limit on the number of pods by default.

**Comment by seanknox** [comment]
@yuvipanda While ACS doesn't have an explicit pod limit, Kubernetes does call this out. E.g. K8s v1.7 has a 100 pods/node limit: https://kubernetes.io/docs/admin/cluster-large/

**Comment by yuvipanda** [comment]
Thanks!
