### ISSUE TITLE
New K8 Cluster in existing vnet fails to provision

### ISSUE THREAD

**Issue by rajcheval** [Azure/acs-engine#1105]
**Is this a request for help?**:

yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

I just did a pull from the repo today.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.6.6
It used managed disk.
It was deploying to an existing cluster

**What happened**:
When executed the deployment it failed.
On VM extension failed with error:
Enable failed: failed to execute command: command terminated with exit Status=127

I tried to ssh into the master node using the public IP of the load balancer to get detailed extension logs.

ssh -i sshprivate_rsa azureuser@clusterdns.eastus2.cloudapp.azure.com
The authenticity of host 'clusterdns.eastus2.cloudapp.azure.com (52.177.207.219)' can't be established.
ECDSA key fingerprint is SHA256:/RTCq6IzX846Eb9x9V0GJgacllTRrAGDWwQ5eehihys.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'perft02k8.eastus2.cloudapp.azure.com' (ECDSA) to the list of known hosts.
Permission denied (publickey).

**What you expected to happen**:

Expected the cluster to provision successfully.

**How to reproduce it** (as minimally and precisely as possible):
create a vnet
configure a new K8 cluster in a subnet in the vnet. use manage disks.
I can share my templates if that will help

**Anything else we need to know**:
We provisioned a cluster successfully on an existing VNET 2 weeks ago.
Today I pulled the latest content from repo. customized the example for K8 and provisioned the cluster.

**Comment by rajcheval** [comment]
Existing VNET address space is: 10.241.0.0/22
lbsubnet: 10.241.0.0/24
KubernetesSubnet: 10.241.1.0/24

2 weeks ago we had provisioned K8 successfully. In that instance we only had 1 subnet and its address range was same as vnet address space.

**Comment by rajcheval** [comment]
I used PowerShell to execute the templates.

**Comment by dmitsh** [comment]
@rajcheval Can you successfully provision a new cluster with custom VNET and managed disk?

**Comment by rajcheval** [comment]
I did provision a cluster in existing vnet and managed disk 2 weeks ago.
