### ISSUE TITLE
Refactor Kubernetes upgrade code

### ISSUE THREAD

**Issue by rjtsdl** [Azure/acs-engine#1114]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
master/HEAD
---

1. After the change to user OrchestratorVersionHint as user input, upgrade code still treat OrchestratorVersion as user's input. Need to refactor that
2. Also upgrade is focus on 1.5.3 -> 1.6.2, we should work on the scenario to upgrade  1.5 -> 1.6 regardless of the patch part. 

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What you expected to happen**:
More aligned with OrchestratorVersionHint change. #921

**Comment by amanohar** [comment]
To help with the code here are the lines that need to be changed (there might be 1-2 more places). Upgrade uses the version specified in its API model to set the container service API model to generate the template.

Following lines need to be changed and tested:
1) https://github.com/Azure/acs-engine/blob/master/pkg/operations/kubernetesupgrade/v162upgrader.go#L42
2) https://github.com/Azure/acs-engine/blob/master/pkg/operations/kubernetesupgrade/v162upgrader.go#L27-L30
3) https://github.com/Azure/acs-engine/blob/master/pkg/operations/kubernetesupgrade/upgradecluster.go#L73-79
