### ISSUE TITLE
Cluster Key Vault

### ISSUE THREAD

**Issue by khenidak** [Azure/acs-engine#1116]
This is a documentation for K8S 1.8 Encryption Provider Feature

**Ref Docs**
- Doc: https://docs.google.com/document/d/1JAwPuZg47UhfRVlof-lMw08OJztunW8pvTNxDK3rCF8/edit
- Doc: https://docs.google.com/document/d/1T2y-9geg9EfHHtCDYTXptCa-F4kQ0RyiH-c_M1SyD0s/edit
- Code: https://github.com/kubernetes/kubernetes/pull/48574 

**Use Case**
Cloud providers will enable users to encrypt Kubernetes' secrets saved in etcd (for 1.8. 1.9++ is expected to add "secrets saved externally"). 

**How will that work on Azure**

1.  acs-engine will create clusters with a default Azure Key Vault provisioned by ARM. The key vault name is generated dynamically based on cluster FQDN and is saved in /etc/kubernetes/azure.json and will be used.

2. if the cluster is *not* using the newly introduced MSI, the user provided service principal will have create,encrypt and decrypt on vault/keys. if the cluster is using MSI, then VMs' service principals will be have the same permissions (added by the cloud provider as it starts). 

3. The cloud provider will be extended to
     -  Create a well named default key in the cluster key vault  used for encrypting/decrypt etcd secrets  
     -  Add permission as stated above. 
     -  implement encrypt/decrypt interfaces as needed by Kubernetes.

@jdumars @slack

**Comment by weinong** [comment]
regarding 2, do agent nodes have the same encrypt/decrypt privilege? Keyvault access policy can only have up to 16 principals added. If agents do need, the msi will not work when cluster size is > 16 (including master).
regarding 3, doesn't that mean cloud provider has "create" or "import' access to keyvault as well?

**Comment by khenidak** [comment]
re 2- (this is yet to be ironed out). VMs' spns has contributor access on the entire RG. they can add then remove themselves. Or try add, fail remove one, add.

re 3 - No create, encrypt and decrypt. I don't think we need import. am i missing something?
