### ISSUE TITLE
regression on 2017-07-01

### ISSUE THREAD

**Issue by weinong** [Azure/acs-engine#1117]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
05871f14ea21b33889db0d4a82f2464608ea96d3
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DockerCE

**What happened**:
StorageProfile used to be default to ManagedDisks. Now it's StorageAccounts

**What you expected to happen**:
StorageProfile should be ManagedDisks

**How to reproduce it** (as minimally and precisely as possible):
cannot say when the regression was introduced. but RP is using a fairly old version of acs-engine.

**Anything else we need to know**:

**Comment by weinong** [comment]
@anhowe

**Comment by weinong** [comment]
found it.
the regression was introduced at 84e8eafb3f6cd2473f84cfea0dcfe8bdcd96d0f3 [here](https://github.com/Azure/acs-engine/blob/master/pkg/api/v20170701/types.go#L154) and [here](https://github.com/Azure/acs-engine/blob/master/pkg/api/v20170701/types.go#L202).

@rjtsdl

**Comment by rjtsdl** [comment]
On it
