### ISSUE TITLE
Setup on Windows in Docker container fails on `make bootstrap`

### ISSUE THREAD

**Issue by dunnock** [Azure/acs-engine#1127]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
Master @ https://github.com/Azure/acs-engine/commit/f85026b10d9317979c6e1694d20060ecd16bab0c
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Setup of acs-engine fails on Windows within Linux Docker container

**What you expected to happen**:
Setup to complete, `make bootstrap` to succeed

**How to reproduce it** (as minimally and precisely as possible):
on Windows with Linux containers enabled:
```
$ .\scripts\devenv.ps1
# make bootstrap
```

make exit with 1 and error:
```
...
[INFO]  --> Exporting github.com/satori/uuid
[INFO]  --> Exporting github.com/prometheus/common
[INFO]  --> Exporting github.com/spf13/pflag
[INFO]  --> Exporting golang.org/x/sys
[INFO]  --> Exporting golang.org/x/crypto
[INFO]  --> Exporting gopkg.in/go-playground/validator.v9
[INFO]  --> Exporting gopkg.in/yaml.v2
[INFO]  Replacing existing vendor dependencies
[ERROR] Unable to export dependencies to vendor directory: remove /gopath/src/github.com/Azure/acs-engine/vendor/github.
com/go-playground/locales: directory not empty
Makefile:76: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 1
```

**Anything else we need to know**:
it is a clean setup on a new Windows box with git and docker preinstalled

**Comment by lonesomegeek** [comment]
Same issue here

**Comment by lonesomegeek** [comment]
As a workaround @dunnock I've deleted folder ./vendor/go-playground/locales prior to `make bootstrap` and it is passing through.

Give it a try and let me know it it worked!

**Comment by dunnock** [comment]
@lonesomegeek yes, worked, thanks! Though I think it needs to be fixed anyways. BTW, same folder present when creating on Mac, though on Windows it has got ~100 subitems, on Mac >500 and no error on Mac.
