### ISSUE TITLE
Remove out hard coded image url

### ISSUE THREAD

**Issue by resouer** [Azure/acs-engine#114]
Since `gcr.io` is not reachable from China mainland, I noticed all `acs-engine` guides in China are suggesting users to replace `gcr.io` in both code and configuration files to something else, and, what's worse, **re-compile** acs-engine to make this work.

This is very bad experience.

If we can not solve the URL problem, we can try to remove all image URLs in code at least, for example: https://github.com/Azure/acs-engine/blob/ef10fce6cb0b2bdd9a0745b6860ef494f9b50827/pkg/acsengine/const.go#L22

**Comment by colemickens** [comment]
That's just the default value. If you look at the output, you'll see that `kubernetesHyperkubeSpec` can easily be changed before you perform the deployment.

I actually use this regularly to test private builds of hyperkube that are pushed to a `docker.io` registry rather than a `gcr.io` registry, for example.

**Comment by resouer** [comment]
Good to know it's configurable. @colemickens can you make sure there're no `gcr.io` hard coded in the code? Then I can close this issue.

**Comment by colemickens** [comment]
Actually, no, that's not the only place it needs to be configured. It also needs to be replaced in any of the manifests where we are pulling containers for addons.

We don't have a great way of making this adjustable right now. For right now, it'd be very easy for you to maintain a fork that has the relevant mirrors you need. We can look at how we might support making this adjustable in the addon files as well.

**Comment by resouer** [comment]
Thanks! Closed.
