### ISSUE TITLE
Smaller Master VM size?

### ISSUE THREAD

**Issue by jamesbannan** [Azure/acs-engine#1141]
**Question**

I'm in the process of architecting a production Kubernetes clusters on ACS. The recommendation is to have multiple Masters, but the default size (D2) is kind of overkill for a K8s Master. My main concern is cost - given that the only options for multiple Masters are 1, 3 or 5, deploying a larger VM with at least 2 cores and 100GB of disk space blows out the cost quite quickly, and that's before we actually start deploying Agent VMs.

Where does the requirement to use larger VM sizes come from? I'd love to be able to use more, smaller VMs for the Masters, so this restriction is making things difficult.  Especially when I have to explain it to a customer :-)

Cheers,
James

**Comment by desdrury** [comment]
My guess about the 1, 3 or 5 Masters is because Etcd is co-lated with the Masters and Etcd needs an odd number to reach quorum.  I also think the size of the VM is overkill.  I look forward to hearing the answer to your questions @jamesbannan .

**Comment by JackQuincy** [comment]
We have added the option to set master vm size in vlabs, which all the exmpales use.  see example https://github.com/Azure/acs-engine/blob/master/examples/kubernetes.json and just set the master to a different size. We have had issues when the masters get to small so we have limited the masters to being sizes:
"Standard_A10",
        "Standard_A11",
        "Standard_A2",
        "Standard_A2_v2",
        "Standard_A2m_v2",
        "Standard_A3",
        "Standard_A4",
        "Standard_A4_v2",
        "Standard_A4m_v2",
        "Standard_A5",
        "Standard_A6",
        "Standard_A7",
        "Standard_A8",
        "Standard_A8_v2",
        "Standard_A8m_v2",
        "Standard_A9",
        "Standard_D11",
        "Standard_D11_v2",
        "Standard_D11_v2_Promo",
        "Standard_D12",
        "Standard_D12_v2",
        "Standard_D12_v2_Promo",
        "Standard_D13",
        "Standard_D13_v2",
        "Standard_D13_v2_Promo",
        "Standard_D14",
        "Standard_D14_v2",
        "Standard_D14_v2_Promo",
        "Standard_D15_v2",
        "Standard_D2",
        "Standard_D2_v2",
        "Standard_D2_v2_Promo",
        "Standard_D3",
        "Standard_D3_v2",
        "Standard_D3_v2_Promo",
        "Standard_D4",
        "Standard_D4_v2",
        "Standard_D4_v2_Promo",
        "Standard_D5_v2",
        "Standard_D5_v2_Promo",
        "Standard_DS11",
        "Standard_DS11_v2",
        "Standard_DS11_v2_Promo",
        "Standard_DS12",
        "Standard_DS12_v2",
        "Standard_DS12_v2_Promo",
        "Standard_DS13",
        "Standard_DS13_v2",
        "Standard_DS13_v2_Promo",
        "Standard_DS14",
        "Standard_DS14_v2",
        "Standard_DS14_v2_Promo",
        "Standard_DS15_v2",
        "Standard_DS2",
        "Standard_DS2_v2",
        "Standard_DS2_v2_Promo",
        "Standard_DS3",
        "Standard_DS3_v2",
        "Standard_DS3_v2_Promo",
        "Standard_DS4",
        "Standard_DS4_v2",
        "Standard_DS4_v2_Promo",
        "Standard_DS5_v2",
        "Standard_DS5_v2_Promo",
        "Standard_F16",
        "Standard_F16s",
        "Standard_F2",
        "Standard_F2s",
        "Standard_F4",
        "Standard_F4s",
        "Standard_F8",
        "Standard_F8s",
        "Standard_G1",
        "Standard_G2",
        "Standard_G3",
        "Standard_G4",
        "Standard_G5",
        "Standard_GS1",
        "Standard_GS2",
        "Standard_GS3",
        "Standard_GS4",
        "Standard_GS5",
        "Standard_H16",
        "Standard_H16m",
        "Standard_H16mr",
        "Standard_H16r",
        "Standard_H8",
        "Standard_H8m",
        "Standard_L16s",
        "Standard_L32s",
        "Standard_L4s",
        "Standard_L8s",
        "Standard_M128ms",
        "Standard_M128s",
        "Standard_M64ms",
        "Standard_NC12",
        "Standard_NC24",
        "Standard_NC24r",
        "Standard_NC6",
        "Standard_NV12",
        "Standard_NV24",
        "Standard_NV6"

**Comment by jamesbannan** [comment]
Thanks @JackQuincy - that's great information to have. Good to konw that we have a wide range of options :-) Out of interest, if we went with 3 x A2_v2 VMs for the Masters, they have a combined storage capacity of 3 x 20GB = 60GB. According to the vmsize property under masterProfile (https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md) the K8s Master needs 100GB. Is using a VM size with less than that going to be a problem?

**Comment by kallex** [comment]
Has anyone tested alike suitable master/agent combos with B-series (preview, low cost, low CPU load machines)?

They cost 1/4 (or are 75% cheaper) than A2-series with comparable memory/core count, but have lower CPU overall performance - boosted occasionally to match normap CPU.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#b-series-preview

Type	CORES	RAM	TEMP STORAGE	PRICE	
B1S  	1	        1.00 GiB	2 GiB	~€6.275/mo
B2S  	2	        4.00 GiB	8 GiB	~€22.59/mo
B1MS	1	        2.00 GiB	4 GiB	~€11.30/mo
B2MS	2	        8.00 GiB	16 GiB	~€42.67/mo
B4MS	4	        16.00 GiB	32 GiB	~€80.94/mo
B8MS	8	        32.00 GiB	64 GiB	~€154.98/mo

From the CPU/Memory limits the B2S and above seem to match A2.

Is the temp storage going to be an issue here... (although its only 20 GB for A2_v2 as well)?

**Comment by robsonpeixoto** [comment]
Any recommendation about the VM Size?
