### ISSUE TITLE
Scrub "--api-servers" from code for Kubernetes v1.8

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#1144]
**Is this a request for help?**: no

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: all

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

Kubernetes is removing "--api-servers" in https://github.com/kubernetes/kubernetes/pull/40050.  We need to scrub our code to remove this including Windows.

**Comment by kichristensen** [comment]
Should this not be closed? This is seems to be handled in https://github.com/Azure/acs-engine/blob/9c3a93698bbed804be860b4b57c27c703a3578af/parts/k8s/kuberneteswindowssetup.ps1#L318-L323
