### ISSUE TITLE
Improve documentation about Network Policies

### ISSUE THREAD

**Issue by sylr** [Azure/acs-engine#1149]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of acs-engine?**: HEAD

---

As a newcomer to Kubernetes and acs-engine the Network Policy area is a pretty dark place. Unless I missed some something I did not find a documentation which:

 - Explain each policy, the advantages and disadvantages they have compared to each other
 - Which one should be preferred in given use cases
 - How the given subnets are used by each policy (i.e.: with `none` the internal load balancer services IPs lie within the master subnet).

I think documentation should be improved about this topic.

Best regards.

**Comment by CecileRobertMichon** [comment]
See https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#network-policy-enforcement-with-calico and https://github.com/Azure/acs-engine/tree/master/examples/networkpolicy#microsoft-azure-container-service-engine---network-policy
