### ISSUE TITLE
Can't change default DCOS package download URL

### ISSUE THREAD

**Issue by kingliantop** [Azure/acs-engine#115]
Hi,

I used acs-engine  to generate dcos ARM json file, the default package download address as following:

https://dcosio.azureedge.net/dcos/testing/bootstrap/${BOOTSTRAP_ID}.bootstrap.tar.xz
https://az837203.vo.msecnd.net/dcos-deps/docker-engine_1.11.2-0~xenial_amd64.deb
https://az837203.vo.msecnd.net/dcos-deps/ipset_6.29-1_amd64.deb
https://az837203.vo.msecnd.net/dcos-deps/libltdl7_2.4.6-0.1_amd64.deb
https://az837203.vo.msecnd.net/dcos-deps/unzip_6.0-20ubuntu1_amd64.deb

While in China, I have to using China local address to download these packages, but even I updated urls in parts/dcosprovision.sh file, the generated dcos json file still keeps the original dcosio and az837203 address.

What is the proper way to automatically generate custom URL in DCOS json file? Currently I updated the json file manually.

**Comment by wangtt03** [comment]
Hi, kingliantop
after changing the dcosprovision.sh, you need to run `go-bindata` command to generate the template.go file under the pkg/acsengine folder. then you can re-compile the acsegine and generate new azuredeploy.json.

**Comment by kingliantop** [comment]
@wangtt03 
Yes, I used go-bindata with following steps:
1. Install go-bindata
2. update parts/dcosprovish.sh
3. delete pkg/acsengine/templates.go
4. generate new templates.go file:
~/gopath/bin/go-bindata -o templates.go ../../parts/.
5. then when I go back to acs-engine home to build new acs-engine with go build, I saw the following
errors:
~/gopath/src/github.com/Azure/acs-engine$ go build
acs-engine.go:11:2: found packages acsengine (azureconst.go) and main (templates.go) in /home/steven/gopath/src/github.com/Azure/acs-engine/pkg/acsengine

Did I miss anything? Thanska lot!

**Comment by wangtt03** [comment]
you need to run the go-bindata command like this:
go-bindata -o template.go -pkg acsengine -prefix ../../parts ../../parts

**Comment by wangtt03** [comment]
@kingliantop 
you need to run the go-bindata command like this:
go-bindata -o template.go -pkg acsengine -prefix ../../parts ../../parts

**Comment by kingliantop** [comment]
@wangtt03 It works! Thanks so much!
