### ISSUE TITLE
VNET - Add validation for Master-first-consecutive-static-ip 

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#1151]
**Is this a request for help?**: no

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What happened**:

Validation should exist for Master-first-consecutive-static-ip, to block incorrect values such as 254 in a 3 master scenario.

From Customer:
It needs to state again in the help that this should be high enough in the subnet range but have enough space based on the number of masters needed. I have had customers use 254 and when they try to deploy 3 masters it goes kaput. Especially now that we are giving the option to deploy to custom VNETs and being on our side of many a network conversation with our customers, this needs to be very well detailed in our documentation and help for the command.

**Comment by CecileRobertMichon** [comment]
@jackfrancis can we close this?

**Comment by jackfrancis** [comment]
This no longer relevant w/ recent changes to master host static IP assignments.
