### ISSUE TITLE
JSON file log driver memory leak

### ISSUE THREAD

**Issue by yangl900** [Azure/acs-engine#1153]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.3.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**: Very high memory consumption by JSON file log

**What you expected to happen**: Avoid using JSON file log driver, or, at least have options to switch to other log driver. The JSON file log driver looks like doesn't fit production usage.

**How to reproduce it** (as minimally and precisely as possible): Running a relative active cluster for long time. Here is what I captured from the `dockerd` process heap dump:

Running dockerd for 1 hours:
![image](https://user-images.githubusercontent.com/8466897/28838894-a6107474-76a6-11e7-95d6-f79ac247d743.png)

Running dockerd for 6 hours:
![image](https://user-images.githubusercontent.com/8466897/28838914-b8a47cc0-76a6-11e7-90a2-124e58e68807.png)

Running dockerd for 12 hours:
![image](https://user-images.githubusercontent.com/8466897/28838939-cfaa1ef2-76a6-11e7-8772-171628bc37cf.png)

Note that the memory consumption from jsonfilelog kept growing to 700MB. In production we have seen several times the dockerd process taking 12GB of memory and keep growing.

**Anything else we need to know**:
there are other issues opened on Docker regarding the bad performance of JSON file log driver: https://github.com/moby/moby/issues/34211

one more reason to avoid it.

**Comment by yangl900** [comment]
Just follow up on this issue. I have tried to restrict the json file log to a larger single file, but seems still leak 2gb per 24 hours.

After running 2 days we got:

2352.60MB of 2371.50MB total (99.20%)
Dropped 583 nodes (cum <= 11.86MB)
Showing top 10 nodes out of 32 (cum >= 63.69MB)
      flat  flat%   sum%        cum   cum%
 2140.84MB 90.27% 90.27%  2285.53MB 96.37%  github.com/docker/docker/daemon/logger/jsonfilelog.decodeLogLine
   79.50MB  3.35% 93.63%       81MB  3.42%  encoding/json.(*decodeState).literalStore
   68.05MB  2.87% 96.50%    68.05MB  2.87%  github.com/docker/docker/daemon/logger/jsonfilelog.(*JSONFileLogger).ReadLogs
   60.71MB  2.56% 99.06%    60.71MB  2.56%  bytes.makeSlice
    1.50MB 0.063% 99.12%    61.69MB  2.60%  github.com/docker/docker/pkg/ioutils.(*multiReadSeeker).Read
       1MB 0.042% 99.16%    62.69MB  2.64%  encoding/json.(*Decoder).refill
       1MB 0.042% 99.20%  2286.53MB 96.42%  github.com/docker/docker/daemon/logger/jsonfilelog.tailFile
         0     0% 99.20%    60.19MB  2.54%  bytes.(*Buffer).ReadFrom
         0     0% 99.20%   144.69MB  6.10%  encoding/json.(*Decoder).Decode
         0     0% 99.20%    63.69MB  2.69%  encoding/json.(*Decoder).readValue

**Comment by seanknox** [comment]
@yangl900 @jchauncey and I have some ideas on this. Will connect with you to discuss.

**Comment by cpuguy83** [comment]
These look like cumulative numbers. Reading logs allocates a new byte slice for each log line so I would expect these figures to be high.

**Comment by pawanks** [comment]
just incase someone need it , steps for go pprof  on CoreOS , can also be performed on other flavours 
- docker run --rm -v /opt/bin:/opt/bin xueshanf/install-socat
- nohup /opt/bin/socat -d -d TCP-LISTEN:8080,fork,bind=localhost UNIX:/var/run/docker.sock &
- docker run --rm --net host -v $PWD:/root/pprof/ golang go tool pprof --svg --inuse_space localhost:8080/debug/pprof/heap
- docker run --rm --net host -v $PWD:/root/pprof/ golang go tool pprof localhost:8080/debug/pprof/profile
