### ISSUE TITLE
[kubernetes] systemctl stop kubelet.service 

### ISSUE THREAD

**Issue by jpoon** [Azure/acs-engine#116]
Unable to stop kubelet.service via systemctl on k8s master node.

```
> systemctl stop kubelet.service
> systemctl status kubelet.service
Nov 22 01:29:19 k8s-master-1479775666-0 systemd[1]: Stopping Kubelet...
Nov 22 01:29:19 k8s-master-1479775666-0 docker[26894]: Error response from daemon: No such container: kubelet

```

Should be a fairly easy fix if you name the docker image when starting:
https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastercustomdata.yml#L323

**Comment by colemickens** [comment]
That sounds like the right fix to me as well. Patches welcome.

**Comment by colemickens** [comment]
Reopening since this change was reverted.
