### ISSUE TITLE
i18n.go - undefined: Asset

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#1160]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: master

---

running "go get github.com/Azure/acs-engine" yields the following error:

src/github.com/Azure/acs-engine/pkg/i18n/i18n.go:65: undefined: Asset

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:
Undefined: Asset

**What you expected to happen**:

No error

**How to reproduce it** (as minimally and precisely as possible):

go get github.com/Azure/acs-engine

**Anything else we need to know**:

**Comment by dcieslak19973** [comment]
This is with go version 1.8.3

**Comment by dcieslak19973** [comment]
Also, after running "go get all", getting:

package github.com/go-playground/pure/examples/middleware/logging-recovery: cannot find package "github.com/go-playground/pure/examples/middleware/logging-recovery" in any of:

With various GOROOT and GOPATH directories listed.

**Comment by seanknox** [comment]
This is the same problem mentioned https://github.com/Azure/acs-engine/issues/1068#issuecomment-318776434. We have text templates that need to be compiled before running, which `go get` doesn't do. It's an ugly error on cloning but harmless otherwise. If you don't need to develop on acs-engine, you're better off downloading the binary releases.

**Comment by dcieslak19973** [comment]
Got it. I used the docker method and it works

**Comment by uday31in** [comment]
Is there any ETA for the fix? Thanks.

**Comment by masroorhasan** [comment]
Getting the same error with `go get github.com/Azure/acs-engine` on windows.
