### ISSUE TITLE
Update UI and instructions in DCOS walkthrough

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#1163]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

**What happened**:
The docs don't match the DCOS UI.  Also, only docker containers can be deployed through marathon now.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
