### ISSUE TITLE
nameSuffix parameter missing from azuredeploy.parameters.json file 

### ISSUE THREAD

**Issue by josibake** [Azure/acs-engine#117]
The `nameSuffix` field is missing from the azuredeploy.parameters.json file following template generation. It is in the azuredeploy.json file and causes the following error when following the documentation:

```sh
info:    Executing command group deployment create
error:    Template and Deployment "parameters" objects lengths do not match 
	Deployment Parameter file does not have { nameSuffix } defined.
error:   Error information has been recorded to <path>/.azure/azure.err
error:   group deployment create command failed
```

The error is solved by manually adding the `nameSuffix` field to the azuredeploy.parameters.json file.

**Comment by colemickens** [comment]
It's not really required and that issue is fixed in newer versions of the
legacy CLI.

Unfortunately, new versions of the legacy CLI have a different issue. I
recommend you try the new Python based Azure CLI:
https://GitHub.com/Azure/azure-cli

**Comment by josibake** [comment]
Makes sense. I'll give the azure-cli a shot. If anything, having this noted in the issues will hopefully save somebody some headache.

**Comment by colemickens** [comment]
Closing this. Feel free to reopen if you're not unblocked.
