### ISSUE TITLE
IP address for k8s acs cluster should be static/New k8s service should not create new LoadBalancer but use existing LoadBalancer

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/acs-engine#1172]
**Is this a request for help?**:
---
Yes.

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**What version of acs-engine?**:
---
azure-cli (2.0.10)
acs (2.0.10)

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
I am using Kubernetes V1.6 on server (Linux/AMD64) and v1.7 on client (Windows/AMD64).

**What happened**:
When I try to create a new service with following code

```
apiVersion: v1
kind: Service
metadata:
  name: sqlservice
  labels:
    app: sqlservice
spec:
  type: LoadBalancer
  loadBalancerIP: <Existing Azure IP Address>
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlinux
```
I get an error that says can't use this IP address as it is being referenced in front-end configuration of Load Balancer <my azure load balancer name>. I can see that this IP address is being referred for load balancing(443) and NAT rules(22).

[Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer) has following note for Azure –

> Special notes for Azure: To use user-specified public type loadBalancerIP, a static type public IP address resource needs to be created first, and it should be in the same resource group of the cluster. Then you could specify the assigned IP address as loadBalancerIP.

However IP address resource that gets created in acs k8s cluster is dynamic and not static.

If I create a new static IP in resource group and use it as a LoadBalancerIP, k8s service gets created successfully. I see that it creates a new LoadBalancer as well.

**What you expected to happen**:
There are 3 things I expect -

1. When acs k8s cluster is provisioned, IP address that gets generated should be static and not dynamic to match k8s documentation (or k8s documentation should be corrected, whichever true!).
2. When a new acs k8s service is to be created, there should not be need to create a new static IP. It should use existing IP address. New service should not create a new LoadBalancer either. 
3. When a new service is getting created with type as LoadBalancer and pointing to an existing IP address, it should not fail owing to IP address being referenced in LoadBalancer configuration. LoadBalancer is expected to have multiple health probe, load balancing, NAT rules. It should simply add a new load balancing or NAT rule based on port no. specified in service creation yaml.

**How to reproduce it** (as minimally and precisely as possible):

1. Spin up a acs k8s cluster in azure.
2. Try to create a new service with type as LoadBalancer and use LoadBalancerIP as the the one created as part of cluster creation.

**Anything else we need to know**:
No.

**Comment by TaChao** [comment]
+1
