### ISSUE TITLE
e2e tests do not clean up after themselves

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1178]
e2e test teardown is coupled with running the actual tests in `test/acs-engine/acs-engine`, so if CI aborts a build—e.g. a new commit is push—the old infra is never destroyed. Cleanup needs to be handled by CI. This is rather urgent, as we end up with lots of old VM infra that has to be deleted manually and we hit quota.

@jchauncey @dmitsh

**Comment by jchauncey** [comment]
if circle aborts a build it sends a terminating signal which i think we can trap and make sure we clean up. 

```
clean_resource_groups() {
  az group list | jq -r '.[] | select(.properties.provisioningState != "Deleting" ).name' | grep "^$1" | while read -r name; do az group delete -n $name --yes --no-wait; done
}
```

that function will cleanup resource groups that match a prefix: `clean_resource_groups foo`

**Comment by seanknox** [comment]
Interesting idea, though that assumes the VM last longs enough to fire off the command.
