### ISSUE TITLE
k8s calico network policy has no effect

### ISSUE THREAD

**Issue by tejas0908** [Azure/acs-engine#1197]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: v0.4.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**: 
Installed a kubernetes cluster using ACS 0.4.0 (kubernetes v1.6.6)
Enabled calico network plugin using,
```json
"kubernetesConfig": {
   "networkPolicy": "calico"
}
```
Tried out the network policy example as mentioned in this link,
https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/

kubectl gave an error,
```
error: unable to recognize "test.yaml": no matches for networking.k8s.io/, Kind=NetworkPolicy
```

Changed "networking.k8s.io/v1" to "extensions/v1beta1" and tried again.

This time the network policy has no effect (busybox pod is able to communicate with nginx without issue)

**What you expected to happen**:

Expected the network policy to take effect and stop pod communication from busybox to nginx.

**How to reproduce it** (as minimally and precisely as possible):

Install k8s cluster with ACS v0.4.0 with network plugin calico enabled and try out the example mentioned at this link,
https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/

**Anything else we need to know**:

The k8s cluster has calico-node daemonset running.
But it does not have a calico policy controller as mentioned in these links,
https://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/hosted
https://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/calico.yaml

**Comment by dtzar** [comment]
I'm working to upgrade to 2.5.1 with policy controller.  See #1417 

That said, when I recently tested with 0.6.0 with a K8s 1.6.9 cluster the ingress network policies seemed to work fine although I didn't try the policy mentioned at the link you provided above.  Once we get 2.5.1 working it would be good for us to test the article to if it works. ;)
