### ISSUE TITLE
Allowed orchestratorVersions defined both in code and tests for pkg/api/vlabs/validate

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1204]
While adding Kubernetes v1.6.8 support, unit tests `pkg/api/vlabs/validate` for passed despite it missing the new Kubernetes version. This is because the tests themselves define the versions to check: https://github.com/Azure/acs-engine/pull/1201/files#r131750197

* As a fix, `pkg/api/vlabs/validate_test.go` should derive allowed Kubernetes versions directly from code and not override as we're doing.
* Let's apply whatever fix to the other API models as well:
./pkg/api/v20170131/validate.go
./pkg/api/v20170701/validate.go
./pkg/api/vlabs/validate.go

**Comment by jackfrancis** [comment]
updated version behavior obsolesces this particular issue
