### ISSUE TITLE
Kubernetes 1.7.2 managed disk UX is unclear

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#1205]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: v0.5.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

Installing the mariadb helm chart on a vanilla 1.7.2 cluster results in the following error message. 

```
  28m		8s		22	attachdetach					Warning		FailedMount		AttachVolume.Attach failed for volume "pvc-a9fbc8b2-7bbc-11e7-b7a9-000d3a73c386" : Attach volume "levo-cluster-5988e074-dynamic-pvc-a9fbc8b2-7bbc-11e7-b7a9-000d3a73c386" to instance "k8s-agent1-63681926-0" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Addition of a blob based disk to VM with managed disks is not supported."
  26m		2s		14	kubelet, k8s-agent1-63681926-0			Warning		FailedMount		Unable to mount volumes for pod "cantankerous-elephant-mariadb-531162889-57p0z_default(aa0950b2-7bbc-11e7-b7a9-000d3a73c386)": timeout expired waiting for volumes to attach/mount for pod "default"/"cantankerous-elephant-mariadb-531162889-57p0z". list of unattached/unmounted volumes=[data]
  26m		2s		14	kubelet, k8s-agent1-63681926-0			Warning		FailedSync		Error syncing pod
```

The agent has the following labels
```
k8s-agent1-63681926-0   Ready                      37m       v1.7.2    agentpool=agent1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=southcentralus,failure-domain.beta.kubernetes.io/zone=0,kubernetes.io/hostname=k8s-agent1-63681926-0,role=agent,storageprofile=managed,storagetier=Premium_LRS
```

**What you expected to happen**: I expect that a agent running with managed OS disks should be able to mount a storageaccount blog storage  volume using the default storageclass.

**How to reproduce it** (as minimally and precisely as possible):

* Build standard 1.7.2 cluster
* helm install stable/mariadb

**Anything else we need to know**:

**Comment by lachie83** [comment]
cc @khenidak

**Comment by jdumars** [comment]
https://github.com/kubernetes/kubernetes/issues/50150 for cross-reference

**Comment by seanknox** [comment]
This is a gap in our managed disk e2e tests, we'll need to expand them. cc @anhowe @dmitsh @jchauncey

**Comment by lachie83** [comment]
My apologies here. I've looked at the documentation and confirmed with @colemickens that VMs with managed disks should indeed not be able to mount non-managed disks. This behaviour is indeed correct.

**Comment by seanknox** [comment]
Yep. We need to install one storage class only, depending on the VM being used.

**Comment by lachie83** [comment]
All storage classes were placed there to support mixed-mode agent type clusters.

**Comment by khenidak** [comment]
Yes - mixed clusters will require labels and scheduler affinity either user driven (using labels and selector on spec) or we add a predicate on the scheduler

**Comment by jdumars** [comment]
My concern is the impact of this on Terraform/Tectonic-generated clusters that are currently working fine on 1.6.x and will break when upgraded to 1.7.2.

**Comment by andyzhangx** [comment]
Hi @lachie83 , as the error saying "Addition of a blob based disk to VM with managed disks is not supported."   It is NOT possible to use unmanaged data disks with a VM that has a managed OS disk, it's designed by azure.

**Comment by andyzhangx** [comment]
@lachie83 After further check, the default storage class(kubernetes.io/azure-disk) is wrong for managed disk VM, it's still using blob storage disk.  We will modify the acs-engine template code to set the right default storage class, while now you could use example below to work around this issue, thanks.
kubectl create -f https://raw.githubusercontent.com/andyzhangx/kubernetes/azure-disk-examples/examples/volumes/azure_disk/claim/managed-disk/managed-hdd/storageclass-managed-hdd.json
The correct scenarios are.
1. Managed VM can only attach managed disk
2. Unmanaged VM can only attach blob storage disk

**Comment by lachie83** [comment]
To further elaborate on @andyzhangx. Here is the correct usage

Agent pool types and storage capability.

- Premium Managed VM can only attach managed disk (both Premium and Standard LRS)
- Managed VM can only attach managed disk (only Standard LRS)
- Unmanaged VM can only attach blob storage disk
 
On clusters bootstrapped with acs-engine agent nodes are labelled so that you can influence the Kubernetes scheduler (see  storageprofile and storagetier)


```
k8s-agent1-63681926-0   Ready                      15h       v1.7.2    agentpool=agent1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=southcentralus,failure-domain.beta.kubernetes.io/zone=0,kubernetes.io/hostname=k8s-agent1-63681926-0,role=agent,storageprofile=managed,storagetier=Premium_LRS
```

The following storage classes are bootstrapped by default

```
kubectl get storageclass
NAME                TYPE
default (default)   kubernetes.io/azure-disk
managed-premium     kubernetes.io/azure-disk
managed-standard    kubernetes.io/azure-disk
``` 

See the following docs for how to pin a workload to a Kubernetes agent(s). https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#managed-disks-1

If a storageclass is not defined in a PVC then the default will be used using the admission controller (default is currently set to (default)) You can change the storage class in the PVC. See storageClassName https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims

**Comment by anschoewe** [comment]
Just to clarify, is it even possible to request managed disk today through a PVC?  Or is part of the bug that even if you specify 'managed-storage' as the storageClass is still creates blob storage in Azure?  

I'm also not seeing how I specify my Kubernetes cluster be created with Managed VMs.  Perhaps that's different topic, but would love to know how.  Does setting a specific 'agent-vm-size' when I create the Kubernetes cluster control this?

**Comment by andyzhangx** [comment]
@anschoewe of course it's possible to create managed disk through PVC, here is an example
kubectl create -f https://raw.githubusercontent.com/andyzhangx/kubernetes/azure-disk-examples/examples/volumes/azure_disk/claim/managed-disk/managed-hdd/storageclass-managed-hdd.yaml
kubectl get sc
kubectl create -f https://raw.githubusercontent.com/andyzhangx/kubernetes/azure-disk-examples/examples/volumes/azure_disk/claim/managed-disk/managed-hdd/pvc-on-managed-hdd.yaml
kubectl get pvc
watch kubectl describe pvc dd-managed-hdd-5g
kubectl create -f https://raw.githubusercontent.com/andyzhangx/kubernetes/azure-disk-examples/examples/volumes/azure_disk/claim/managed-disk/managed-hdd/pod-uses-managed-hdd.yaml
kubectl get po
watch kubectl describe po pod-uses-managed-hdd-5g

And you could refer to following PR, it has all details:
https://github.com/kubernetes/kubernetes/pull/49468

And about how to create a k8s cluster with managed VMs, here is the example, key point is specify storageProfile as ManagedDisks value:
https://github.com/Azure/acs-engine/blob/master/examples/disks-managed/swarm-vmas.json#L27

**Comment by antoineco** [comment]
I just ran into the same issue, but with managed disks on a VM with blob based disks.

```
Addition of a managed disk to a VM with blob based disks is not supported.
```

This started happening to me this week, with clusters provisioned from the `az` command-line tool. 
PVC suddenly became unusable on Azure.

#### Environment

```
azure-cli 2.0.22
kubernetes 1.8.2
Standard_A6 instances in uksouth
```

#### Storage class (default)

```yaml
❯ kubectl get sc default -o yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
  name: default
parameters:
  kind: Managed
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
```

#### Persistent volume claim

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  labels:
    app: zookeeper
    tier: data
  name: datadir-zookeeper-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
  volumeName: pvc-861e7371-e0c6-11e7-a779-00224801593f
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
```

#### Full error log

```
  Warning  FailedMount       1m (x20 over 26m)  attachdetach                        AttachVolume.Attach failed for volume "pvc-861e7371-e0c6-11e7-a779-00224801593f" : Attach volume "xxxxxxxxxx-dy-pvc-861e7371-e0c6-11e7-a779-00224801593f" to instance "k8s-agentpool0-34663692-2" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Addition of a managed disk to a VM with blob based disks is not supported."
  Warning  FailedMount       1m (x11 over 24m)  kubelet, k8s-agentpool0-34663692-2  Unable to mount volumes for pod "zookeeper-0_default(8620c239-e0c6-11e7-a779-00224801593f)": timeout expired waiting for volumes to attach/mount for pod "default"/"zookeeper-0". list of unattached/unmounted volumes=[datadir]
```

**Comment by andyzhangx** [comment]
From acs-engine v0.10.0, the defualt azure disk storage class would be consistent with agentpool VM, that is if VM is blob based disk VM, the default class will be blob based disk.
Back to your case, there are two options to workaround:
1) change default storage class, `kind: Managed` to `kind: Shared` by 
```
sudo vi /etc/kubernetes/addons/azure-storage-classes.yaml
```
After about 2 min, `kind` value in default storage class will be changed , you could check by 
```
watch kubectl get storageclass
```

2) create a new azure disk storage class, and use that storage class name in your PVC, below is an example:
https://github.com/andyzhangx/Demo/tree/master/linux/azuredisk

**Comment by antoineco** [comment]
@andyzhangx in that case the default Storage Class should be pre-configured accordingly, otherwise ACS is _broken by default_.

**Comment by andyzhangx** [comment]
@antoineco with multiple masters, option#2 is a better choice. acs-engine v0.10.0 has fixed this issue.

**Comment by antoineco** [comment]
What is the ACS version currently deployed on Azure?

**Comment by andyzhangx** [comment]
@antoineco you mean `az aks` right? 
This https://github.com/Azure/acs-engine/pull/1817 should be merge into **AKS** repo as well @jackfrancis

**Comment by antoineco** [comment]
No, I meant `az acs`.
