### ISSUE TITLE
Creating RBAC enabled cluster, but flags are not being created

### ISSUE THREAD

**Issue by chzbrgr71** [Azure/acs-engine#1210]
**Is this a request for help?**: Yes
**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE
**What version of acs-engine?**: v0.5.0 (2017-08-07T10:00:43-0700)

---
**Orchestrator and version: Kubernetes v1.7.1

**What happened**: Trying to test RBAC/AAD support with acs-engine v0.5.0. acs-engine runs, but it looks like the necessary flags for api-server are not being generated into my ARM template. Checked the manifest for the api-server and the flags are not there (eg - "--authorization-mode=RBAC"

**What you expected to happen**:  Expecting the deployed cluster to have RBAC enabled. 

**How to reproduce it**: Try acs-engine generate with the attached template. Could be an issue with my json template (below)

**Anything else we need to know**:  
[kube-rbac.txt](https://github.com/Azure/acs-engine/files/1208359/kube-rbac.txt)

**Comment by lachie83** [comment]
Hi @chzbrgr71. Did you build the acs-engine binary from source or download it from the release? Just wondering because I see the aad configuration in there and that wasn't a part of v0.5.0 and thought you may have been building off that PR which doesn't have RBAC.

**Comment by chzbrgr71** [comment]
In this case I downloaded the binary. Is there a better version I should use or build for RBAC?

**Comment by lachie83** [comment]
Just a friendly reminder to clean up those SPs that are present in the attached file

**Comment by lachie83** [comment]
I looks like the release binaries have not been build correctly. When I build from the release branch your file works with RBAC. cc @seanknox how can we confirm that the release binaries have been built from the right branch?

**Comment by lachie83** [comment]
@chzbrgr71 can you try building the binary from the release tag until we get this resolved?

**Comment by chzbrgr71** [comment]
I built acs-engine from code and re-tried my cluster. I now sww the "--authorization-mode=RBAC" flag set. I do not see the 3 other flags: --oidc-client-id, --oidc-issuer-,--oidc-username-claim. I'm not sure if these are set at runtime or something else was incorrect in my cluster definition?

**Comment by lachie83** [comment]
Okay great. The aad work isn't in that release or master at this point. You would have to build from that PR assuming it's been rebased on current master.
