### ISSUE TITLE
Kubernetes Large Cluster example doesn't work with 1.7.2

### ISSUE THREAD

**Issue by yuvipanda** [Azure/acs-engine#1214]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: v0.5.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

I tried to create a large Kubernetes cluster with 1.7.2.  Appropriate section of my cluster.json:

```
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.7.2",
      "kubernetesConfig": {
        "nodeStatusUpdateFrequency": "1m",
        "ctrlMgrNodeMonitorGracePeriod": "5m",
        "ctrlMgrPodEvictionTimeout": "1m",
        "ctrlMgrRouteReconciliationPeriod": "1m",
        "cloudProviderBackoff": true,
        "cloudProviderBackoffRetries": 6,
        "cloudProviderBackoffJitter": 1,
        "cloudProviderBackoffDuration": 6,
        "cloudProviderBackoffExponent": 1.5,
        "cloudProviderRateLimit": true,
        "cloudProviderRateLimitQPS": 3,
        "cloudProviderRateLimitBucket": 10
      }
    },
```

This was copied from the large clusters example.

**What you expected to happen**:

A cluster gets created! 

Instead, I got:

```
Retrying role assignment creation: 1/36
Retrying role assignment creation: 2/36
FATA[0000] error parsing the api model: cloudprovider backoff functionality not available in kubernetes version  
```

**How to reproduce it** (as minimally and precisely as possible):
Try the large clusters kubernetes example, but specify Kubernetes 1.7.2

**Anything else we need to know**:

We'd really like to test the managed disks support in 1.7.2 ;)

**Comment by lachie83** [comment]
Thanks @yuvipanda. This is actually a bug. I'll see if I can work on a fix

**Comment by yuvipanda** [comment]
@lachie83 it might be affected on master by a60cde297628e035754b162ef6258473b87c79d6 (maybe). After that commit, I can't specify '1.7.2' as OrchestrationVersion anymore.

**Comment by lachie83** [comment]
Actually. You're cluster.json is incorrect. It should be "orchestratorVersion" not "orchestratorRelease"

**Comment by yuvipanda** [comment]
Ah, interesting. I picked orchestratorRelease from https://github.com/Azure/acs-engine/blob/62051ed553c607ebcbd95333817e6092a935e9fd/examples/kubernetesversions/kubernetes1.7.json

**Comment by lachie83** [comment]
Yes that's a recent change. Are you deploying off master or v0.5.0?

**Comment by yuvipanda** [comment]
@lachie83 I just switched to master because I wanted https://github.com/Azure/acs-engine/pull/1216. When filing this bug I was on v0.5.0. Since I need https://github.com/Azure/acs-engine/pull/1216 anyway looks like I'll be on master now.

**Comment by lachie83** [comment]
Okay no worries. Can you confirm if you rebuilt your acs-engine binary?

**Comment by yuvipanda** [comment]
Yep, waiting on an older RG to delete, will confirm shortly.

**Comment by jackfrancis** [comment]
@yuvipanda Thanks for hanging in with us. Indeed, the `vlabs` api was changed post-`v0.5.0` to introduce a new `orchestratorRelease` property in the `orchestratorProfile`. This is a user-modifiable parameter that takes the form of "major.minor", e.g., `1.7` in your case. `orchestratorVersion` remains as a property, but is now (post-`v0.5.0`) read-only from the user's standpoint. After template generation the value in `orchestratorVersion` will reflect the latest supported patch version in the user-provided "major.minor" `orchestratorRelease`.

**Comment by yuvipanda** [comment]
I see. ok! I now am trying, based on master (+ #1216) with the following profile:

```
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.7",
      "kubernetesConfig": {
        "nodeStatusUpdateFrequency": "1m",
        "ctrlMgrNodeMonitorGracePeriod": "5m",
        "ctrlMgrPodEvictionTimeout": "1m",
        "ctrlMgrRouteReconciliationPeriod": "1m",
        "cloudProviderBackoff": true,
        "cloudProviderBackoffRetries": 6,
        "cloudProviderBackoffJitter": 1,
        "cloudProviderBackoffDuration": 6,
        "cloudProviderBackoffExponent": 1.5,
        "cloudProviderRateLimit": true,
        "cloudProviderRateLimitQPS": 3,
        "cloudProviderRateLimitBucket": 10
      }
    },
```

**Comment by jackfrancis** [comment]
Sounds good, looks like you're building a large cluster, 🍾 !

**Comment by jackfrancis** [comment]
Got it, was responding to the increased node status values. If those values aren't intentional high, let us know, they might not be what you want!

**Comment by yuvipanda** [comment]
I got 1.7.2 with master, so am going to close this! #1083 still happens tho!

Thank you very much, @jackfrancis and @lachie83!

**Comment by lachie83** [comment]
Great! Thanks @yuvipanda. I've commented on #1083
