### ISSUE TITLE
Azure Application Gateway support / SSL termination

### ISSUE THREAD

**Issue by erikrs** [Azure/acs-engine#122]
Hi,

I want to deploy Kubernetes on Azure and wanted SSL termination at load balancer level (typical as ingress object in Kubernetes).

As of now, only Azure Load Balancers (L4) are provisioned by acs. Is there a roadmap for supporting Application gateways ?

In the mean time, what is my best option to implement SSL offloading ? Eg. could I put an Application gateway in front of the loadbalancers ? or should I implement SSL termination myself by implementing an nginx container(s) specifically for this / or use something like 'dynamic SSL' plugin of Kong ?

Thx !

**Comment by kim0** [comment]
As a user, I'm hitting this exact need right now. I didn't try it yet, but my understanding is that I could/should be deploying nginx ingress-controller, with kube-lego to do the letsencrypt dance and get me certificates. The nginx ingress-controller would be exposed as a regular k8s service, through the Azure-LB. 

If someone has more insight/workaround, or working yaml files, it would be great to share them! That is all ofc, till App-Gateway gets natively supported

**Comment by colemickens** [comment]
\+ @JargoonPard to comment on the status of `azure-ingress-controller`.

**Comment by JargoonPard** [comment]
Sorry for the late response. I would suggest using the NGINX ingress controller at this point as @kim0 suggests.

**Comment by anhowe** [comment]
This is out of scope for ACS-Engine.  Let's reconsider if you are able to create a patch and submit, or if there is more customer demand.

**Comment by artisticcheese** [comment]
+1 as customer demand for have ALG as option for load balancing, mainly for SSL offloading and URL based routing.

**Comment by jolcese** [comment]
+1. I need SSL offloading

**Comment by cr4igo** [comment]
+1 , some customers are not allowed to use kube-lego due to internal policies

**Comment by razidare** [comment]
+1 for SSL offloading
