### ISSUE TITLE
Users should be able to opt in to Azure Accelerated Networking on Linux

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#1221]
> As an acs-engine user
> I want to use Azure Accelerated Networking with Linux VMs created by acs-engine
> so my VMs can take advantage of increased networking performance offered by AN

## Background
Accelerated Networking removes the virtual switch layer between VMs and the data center physical switch. Network policies are then applied by the VM NIC hardware. This leads to significantly better network performance.

More info: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-create-vm-accelerated-networking

## Acceptance Criteria
- Users can specify a feature flag in their cluster config to enable Accelerated Networking
- Documentation exists which explains that users must first have the Accelerated Networking feature enabled on their subscription and that A.N. on Linux is still in public preview, etc...everything listed under ["Limitations"](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-create-vm-accelerated-networking), basically.
- VM NICs in the deployment templates have `AcceleratedNetworking` enabled
- The accelerated networking driver for linux is automatically installed for Ubuntu (see the ["Configure Linux" section](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-create-vm-accelerated-networking). We (ACS) will need to host a mirror of the github script referenced in the doc and any software needed to be downloaded.
- Accelerated Networking on Linux uses the `bond0` iface to communicate, not `eth0`—ensure that nothing is hardcoded to use eth0 and/or breaks by using `bond0`

**Comment by seanknox** [comment]
@lachie83, FYI

**Comment by parsoFish** [comment]
Are there any updates on this feature

**Comment by CecileRobertMichon** [comment]
This was implemented in #3011
