### ISSUE TITLE
Make docker downloads resilient

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1239]
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: n/a

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** n/a

**What happened**: Currently we rely upon `get.docker.com` in scripts to download docker. This external reliance will cause outage-like symptoms whenever `docker.com` is offline.

**Comment by rjtsdl** [comment]
Add some context.

For docker swarm, yes we download from get.docker.com.
For kubernetes, we download it from https://aptdocker.azureedge.net/repo.

I will take this opportunity to remove docker.com dependency across acs-engine code.
