### ISSUE TITLE
Azure Kubernetes: no rolebindings exposed to user

### ISSUE THREAD

**Issue by forrestcoward** [Azure/acs-engine#1248]
*Is this a request for help?*:
Yes
---

*Is this an ISSUE or FEATURE REQUEST?* (choose one):
Issue
---

**What version of acs-engine?**:
Not sure. These are the API versions on my server:
```
>kubectl api-versions
apps/v1beta1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
batch/v1
certificates.k8s.io/v1beta1
extensions/v1beta1
istio.io/v1alpha1
policy/v1beta1
rbac.authorization.k8s.io/v1alpha1
rbac.authorization.k8s.io/v1beta1
settings.k8s.io/v1alpha1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```
---

Kubernetes on Azure (configured with a service principal) exposes no rolebindings to the user:

```
>kubectl get rolebindings
No resources found.
```

On other container services you may see something like this...

```
>kubectl get clusterroles
NAME AGE
admin 82d
cluster-admin 82d
edit 82d
kubelet-api-admin 82d
system:auth-delegator 82d
```

The reason this is important to me is I am trying to install [istio.io](https://istio.io/) in Kubernetes running in Azure, but hitting several permissions related issues. Details on the issue I am hitting can be found in [an issue I created against istio](https://github.com/istio/issues/issues/48). Please read.

They suggested I contact the cluster admin.

In the Google container service, the workaround for the issue I am hitting installing istio is to add yourself (the user) to the `cluster-admin` group. But in Azure Kubernetes, there appears to be no admin groups to add myself to.

I assume this is because of some security reason or decision that was made.

Any help appreciated!

Thanks,
Forrest

**Comment by rjtsdl** [comment]
@forrestcoward, I suspect the issue you faced, may already be solved by this. #1143. 
So try out the latest to confirm the issue still happen.

**Comment by forrestcoward** [comment]
Thanks. Yeah, it looks I need to update my ARM template to actually enable RBAC. I am running into an issue though the `apiVersion = vlabs`..

Which `apiVersion` am I supposed to use?

This one complains about no vlabs:
```
Deployment failed. {
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'westus' and API version 'vlabs' for type 'containerServices'. The supported api-versions are '2015-11-01-preview, 2016-03-30, 2016-09-30, 2017-01-31, 2017-07-01'. The support
ed locations are 'japaneast, centralus, eastus2, japanwest, eastasia, southcentralus, australiaeast, australiasoutheast, brazilsouth, southeastasia, westus, northcentralus, westeurope, northeurope, eastus, ukwest, uksouth, westcentralus, west
us2, southindia, centralindia, westindia, canadaeast, canadacentral'."
  }
}
```

This one tells me 2017-07-01 is not valid even though it is listed as valid right after...
```
Deployment failed. {
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'eastus' and API version '2017-07-01' for type 'containerServices'. The supported api-versions are '2015-11-01-preview, 2016-03-30, 2016-09-30, 2017-01-31, 2017-07-01'. The su
pported locations are 'japaneast, centralus, eastus2, japanwest, eastasia, southcentralus, australiaeast, australiasoutheast, brazilsouth, southeastasia, westus, northcentralus, westeurope, northeurope, eastus, ukwest, uksouth, westcentralus,
 westus2, southindia, centralindia, westindia, canadaeast, canadacentral'."
  }
}
```

Thanks,
Forrest

**Comment by jackfrancis** [comment]
@forrestcoward I assume you're using `acs-engine` to generate templates? What `--api-model` are you passing into `acs-engine generate`? (exclude credentials of course!)
