### ISSUE TITLE
20170701 schema change on KeyvaultSecretRef 

### ISSUE THREAD

**Issue by weinong** [Azure/acs-engine#1263]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: HEAD

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**: To prevent the privilege escalation, we should match the properties that acs-engine spit out to the 20170701 api model to ensure vault id is checked against vault id resource:
```
"reference": {
   "keyVault": {
     "id": "/subscriptions/5684bae7-6a09-47a6-bdf1-695d1fd8ac1f/resourceGroups/ww-ukwest/providers/Microsoft.KeyVault/vaults/ww-kv-ukwes2t"
   },
   "secretName": "spn"
}
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by weinong** [comment]
So instead of 
```go
type ServicePrincipalProfile struct {
	ClientID          string `json:"clientId,omitempty" validate:"required"`
	Secret            string `json:"secret,omitempty"`
	KeyvaultSecretRef string `json:"keyvaultSecretRef,omitempty"`
}
```

We need
```go
type ServicePrincipalProfile struct {
	ClientID          string            `json:"clientId,omitempty" validate:"required"`
	Secret            string            `json:"secret,omitempty"`
	KeyvaultSecretRef KeyvaultSecretRef `json:"keyvaultSecretRef,omitempty"`
}

type KeyvaultSecretRef struct {
	VaultID       string `json:"vaultID" validate:"required"`
	SecretName    string `json:"secret" validate:"required"`
	SecretVersion string `json:"version,omitempty"`
}
```

**Comment by weinong** [comment]
Btw, to re-iterate the privilege elevation problem:
- User has Microsoft.KeyVault/vaults/deploy/action assigned at a scope of “/subscriptions/${SUB_ID}/resourceGroups/${RG_NAME}/providers/Microsoft.KeyVault/vaults/${VAULT_NAME}/secrets/mysecret”
- It will pass ARM's linked access check against the secret resourceID (instead of vaultID)
- RP translates the api model to : 
```
"reference": {
   "keyVault": {
     "id": "/subscriptions/5684bae7-6a09-47a6-bdf1-695d1fd8ac1f/resourceGroups/ww-ukwest/providers/Microsoft.KeyVault/vaults/ww-kv-ukwes2t"
   },
   "secretName": "spn"
}
```
- Now, ACS RP will be able to deploy secrets at vault level where user does not have permission

**Comment by weinong** [comment]
@JackQuincy @amanohar @anhowe @rjtsdl please take a look at the proposed change.

**Comment by JackQuincy** [comment]
That seems fine to me. Do we need to do something similar for the other properties we allow users to pass in via key vault? I think we allow the admin user password for windows to be passed in the same way or should.

**Comment by jackfrancis** [comment]
@dmitsh @weinong @JackQuincy did PR #1321 address this issue?
