### ISSUE TITLE
Output directory should be named by dns-prefix rather than random numbers

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#127]
This has two benefits:

1. We would warn if the user is generating a template with a dnsPrefix that already exists. Means they're probably going to have a conflict at deploy-time, and/or they forgot to update the dns prefix in the model to be different for their next cluster.

2. It's a lot more intuitive. I still don't like the fact that we expose this randomly generated number to  users in the first place.

cc: @anhowe  what do you think?

**Comment by anhowe** [comment]
yes, this sounds good, let's do this.

**Comment by anhowe** [comment]
An important distinction here is that the directory name is based off of hash of the dns name.  We always want the DNS name to output to the same directory.  Then the customer can work with their model in that directory.

**Comment by anhowe** [comment]
Closing as not priority
