### ISSUE TITLE
Error on test.mk when creating dev environment

### ISSUE THREAD

**Issue by itowlson** [Azure/acs-engine#1271]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: Current master (commit 5fa24518)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** N/A

**What happened**: I checked out latest master onto Windows, and ran `.\scripts\devenv.ps1`.  The script terminated in Step 16/17 with the following message:

```
Step 16/17 : RUN make bootstrap
 ---> Running in 56c76f97c64c
make: glide: Command not found
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Makefile:128: test.mk: No such file or directory
make: *** No rule to make target 'test.mk'.  Stop.
The command '/bin/sh -c make bootstrap' returned a non-zero code: 2
```

**What you expected to happen**: Expected development container to be built with no errors.  I found that the development container was created successfully up to commit id dd31285e, and the error started occurring with commit id 97ab47bd (resolution for issue #1256).  In that commit I got only one "fatal: not a git repository" error but in current master I get 3 as shown above.  In both I get the makefile `test.mk` error.

**How to reproduce it** (as minimally and precisely as possible):

* Check out commit id 97ab47bd on Windows.
* Run .\scripts\devenv.ps1
* Note errors
* Check out commit id 5fa24518 (master at time of writing) on Windows
* Run .\scripts\devenv.ps1
* Note errors

**Anything else we need to know**:

**Comment by travisnielsen** [comment]
I can reproduce this issue on both Windows and a Mac. I was able to get past it by removing the include statement for test.mk from the makefile. Not sure if there might be side-effects when doing this (for regular deployment scenarios).
