### ISSUE TITLE
Kubernetes should have an HA mode with multiple masters

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#129]
Issue to track the addition of HA to Kubernetes in ACS-Engine.

Depending on where `kubeadm` is at whenever we get to this, we may want to adopt it to minimize our maintenance burden.

**Comment by anhowe** [comment]
this is now checked in with @raveeram changes

**Comment by aboyett** [comment]
Adding breadcrumbs in case anyone else is looking for code changes adding HA master support. They appear to be contained in https://github.com/Azure/acs-engine/pull/233 and https://github.com/Azure/acs-engine/pull/247

**Comment by DonMartin76** [comment]
How do I know whether this is in a specific release of `az`? With 0.1.2rc2, I only get one master even if specifying I want three, using `--master-count 3`.
