### ISSUE TITLE
What the heck is a servicePrincipalClientID?

### ISSUE THREAD

**Issue by bacongobbler** [Azure/acs-engine#1293]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): Question/support

---

**What version of acs-engine?**: 0.5.0

---

I'm trying to generate my first template, but I have no clue what any of the fields in examples/kubernetes.json are. It would be great if the [getting started doc](https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md) explained what each of the fields were and where to find them in my Azure portal, or perhaps through the `az` CLI.

**Comment by bacongobbler** [comment]
For anyone as clueless as I am:

```
export AZURE_GROUP_NAME="mygroupname"
export AZURE_SUBSCRIPTION_ID="mysubscriptionid" # look up your tenantId in ~/.azure/azureProfile.json
export AZURE_DNS_PREFIX=dnsprefix
az group create --name $AZURE_RG_NAME
az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_GROUP_NAME"
```

Grab the "appId" and "password" fields from that output and...

```
export AZURE_SERVICE_PRINCIPAL_CLIENT_ID=appId
export AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET=password
```

Manually make changes to examples/kubernetes.json...

```
$EDITOR examples/kubernetes.json # add in ~/.ssh/id_rsa.pub, $AZURE_DNS_PREFIX, $AZURE_PRINCIPAL_CLIENT_ID and $AZURE_PRINCIPAL_CLIENT_SECRET
acs-engine generate examples/kubernetes.json
az group deployment create \
    --name deploymentName \
    --resource-group $AZURE_GROUP_NAME \
    --template-file "./_output/$AZURE_DNS_PREFIX/azuredeploy.json" \
    --parameters "./_output/$AZURE_DNS_PREFIX/azuredeploy.parameters.json"
```

So my workflow was vastly more complicated than the docs explain. I would gently suggest that the docs should be geared more towards someone who is completely new to the Azure platform in general.

**Comment by JackQuincy** [comment]
These both explain it. Sorry if the other doc wasn't user friendly enough. Could you make a PR to improve the doc?
https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md
https://github.com/Azure/acs-engine/blob/master/docs/serviceprincipal.md 
Also please note you don't have to specify it if you use the deploy command, it will detect it is empty and create one for you and put the client id and secret in the proper places.

**Comment by jackfrancis** [comment]
@bacongobbler lemme know if you think the docs here have any misleading or confusing info:

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md#gather-information

**Comment by bacongobbler** [comment]
I think the problem was that I landed on the wrong page from the README. I should've landed on the link @jackfrancis and @JackQuincy noted above, which was also part of the README... Just ended up going down the wrong rabbit hole.

That documentation is *much* clearer on how to deploy a kubernetes cluster on ACS. Thank you for the links, and I sorry for being so unprofessional. I was getting frustrated after several hours to get an ACS cluster up and running, but now that I have a better grasp on acs-engine I hope to be a better contributor in the future. :)
