### ISSUE TITLE
make bootstrap fails if $GOPATH/bin is not in user path

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#1299]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: HEAD

---

"make bootstrap" fails:

go get -u github.com/Masterminds/glide
go get -u github.com/mitchellh/gox
go get github.com/jteeuwen/go-bindata/...
go get -u github.com/alecthomas/gometalinter
gometalinter --install
make: gometalinter: Command not found
Makefile:98: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 127

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

ALL

**What happened**:
 Cannot build

**What you expected to happen**:

Build to succeed

**How to reproduce it** (as minimally and precisely as possible):

Fresh install; try to build

**Anything else we need to know**:

**Comment by seanknox** [comment]
What OS are you running?

**Comment by dcieslak19973** [comment]
Running it on an Ubuntu 16.04.1 LTS provisioned in Azure. The VM itself may be several months old.

**Comment by jchauncey** [comment]
ok i think this is not the official way to install gometalinter anymore - `go get -u github.com/alecthomas/gometalinter`

**Comment by dcieslak19973** [comment]
When I make that change in the Makefile, I then get:

go get -u gopkg.in/alecthomas/gometalinter.v1
gometalinter --install
make: gometalinter: Command not found

**Comment by dcieslak19973** [comment]
My bad; looks like I didn't have $GOPATH/bin in my path...

**Comment by dcieslak19973** [comment]
I added $GOPATH/bin to my path and the original Makefile (getting gometalinter from github and not gopkg) worked. You can close this if you wish, or leave it open to address the github vs gopkg issue.

**Comment by jackfrancis** [comment]
@jchauncey Does @dcieslak19973 suggest any improvements we could introduce to `Makefile`, or is this good to close?

**Comment by jchauncey** [comment]
the only change we might do is have bootstrap check for the existence of `$GOPATH` and also for the go binary

**Comment by jackfrancis** [comment]
@dcieslak19973 if you don't mind I'm going to change the issue title to "make bootstrap fails if $GOPATH/bin is not in user path". `make bootstrap` should check and then fail with a clear message if this is detected.

**Comment by SeanTurner026** [comment]
I'm having an issue with gometalinter --install as well. I'm on mac High Sierra 10.13.2. Running **make bootstrap** gives me the following--

```
go get -u github.com/mitchellh/gox

go get github.com/jteeuwen/go-bindata/...

go get -u github.com/alecthomas/gometalinter

gometalinter --install

make: gometalinter: No such file or directory

make: *** [bootstrap] Error 1
```

Here's my path ```export PATH=$HOME/bin:/usr/local/bin:$GOPATH/bin:$PATH```

I also have:

```
export PATH=$PATH:/usr/local/go/bin

export GOPATH=$HOME/go

export GOBIN=$HOME/go/bin
```
I also tried editing the makefile to include ```go get -u gopkg.in/alecthomas/gometalinter.v1```, but that didn't help. Please advise. Thank you!

**Comment by jackfrancis** [comment]
Did you try vanilla `go get -u github.com/alecthomas/gometalinter`? (downloading the version'd one will have that version string in the binary filename)

**Comment by SeanTurner026** [comment]
I did, still was getting the same error.

**Comment by phaniapsr** [comment]
gometalinter: command not found 
I am getting this error always

**Comment by mboersma** [comment]
We're not using `gometalinter` in aks-engine now and `make bootstrap` appears only to require `go` to be in the $PATH. I'm closing this, but please re-open over at the [aks-engine](https://github.com/Azure/aks-engine) project if this problem persists.
