### ISSUE TITLE
Support minor-minor version for kubernetes Windows zip

### ISSUE THREAD

**Issue by JiangtianLi** [Azure/acs-engine#1315]
**Is this a request for help?**:
NA
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Kubernetes Windows zip is built out of private branch and needs to be strong versioned with patches. 

**What you expected to happen**:
There is an option to pick minor-minor version for Kubernetes Windows zip, e.g., v1.7.2.1

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Is this still relevant?

**Comment by JiangtianLi** [comment]
@CecileRobertMichon you can close it. We already support minor-minor version of zip.

**Comment by CecileRobertMichon** [comment]
Thanks @JiangtianLi
