### ISSUE TITLE
Validate CNI behavior in E2E tests

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1327]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**Anything else we need to know**: When we build out cluster feature validation in the new ginkgo e2e test runner, please add coverage for the new CNI behavior introduced in this PR:

https://github.com/Azure/acs-engine/pull/1259

**Comment by jchauncey** [comment]
@lachie83 Could you give me an example of how I could validate that CNI is working properly?

**Comment by lachie83** [comment]
Sure. Add this to the cluster model and make sure the pods go to running.
```
      "kubernetesConfig": {
        "networkPolicy": "azure"
      }
```

**Comment by jchauncey** [comment]
Ah k wasnt sure if i needed a more thorough example

**Comment by seanknox** [comment]
It's not intuitive, but just by virtue of the pods in a running state you're testing network connectivity, too.
