### ISSUE TITLE
Allow to parametrize ephemeral disk layout for dcos nodes.

### ISSUE THREAD

**Issue by janpavtel** [Azure/acs-engine#133]
Hi 
it would be helpfully if `acs-engine` would allow to parametrize ephemeral disk layout for `dcos`. Currently we can manually change values inside the file [dcoscustomdata184.t]( https://github.com/Azure/acs-engine/blob/master/parts/dcoscustomdata184.t) 
```
layout:
 -50
 -50
```
and next rebuild project and generate deploy templates. But we will end up with all nodes with the same layout. One of the disk (ephemeral0.1)  is used as mesos directory (`/var/lib/mesos`)  and  second (ephemeral0.2) is used as docker directory (`/var/lib/docker`). Some times there can be more optimal layouts. 
For example in our scenario (cassandra on dcos) we would like to have

- masters layout: -50/-50
- public agent layout: -30/-70
- private agent layout: -90/-10 (cassandra uses  `/var/lib/mesos` for storing data)

Currently workaround is manually edit generated deploy templates.

**Comment by julienlau** [comment]
+1
+1 handle mesos disks of type MOUNT

I was force to add something like this to use mesos disk of type MOUNT for statefull service

bootcmd:
- bash -c "if [ ! -f /var/lib/sdb-gpt ];then echo DCOS-5890;parted -s /dev/sdb mklabel
  gpt;touch /var/lib/sdb-gpt;fi"
- bash -c "if [ ! -f /var/lib/sdc-gpt ];then echo DCOS-5890;parted -s /dev/sdc mklabel
  gpt;touch /var/lib/sdc-gpt;fi"
- bash -c "if [ ! -f /var/lib/sdd-gpt ];then echo DCOS-5890;parted -s /dev/sdd mklabel
  gpt;touch /var/lib/sdd-gpt;fi"
- bash -c "mkdir -p /dcos/volume0"
disk_setup:
  ephemeral0:
    layout:
    - 50
    overwrite: true
    table_type: gpt
  /dev/sdc:
    layout: true
    overwrite: true
    table_type: gpt
  /dev/sdd:
    layout: true
    overwrite: true
    table_type: gpt
fs_setup:
- device: ephemeral0.1
  filesystem: ext4
  overwrite: true
- device: /dev/sdc1
  filesystem: ext4
  overwrite: true
- device: /dev/sdd1
  filesystem: ext4
  overwrite: true
mounts:
- - ephemeral0.1
  - /var/lib/docker
- - /dev/sdc1
  - /var/lib/mesos
- - /dev/sdd1
  - /dcos/volume0

**Comment by anhowe** [comment]
Thanks for this issue.  We have marked as P2 since this is currently not on the roadmap, but is valuable to continue to learn from and collect feedback.  If you submit a PR we can review.  Ultimately this would be good to model in the Agent pools.

**Comment by itaysk** [comment]
Reusing this thread to ask something that's been bothering me:
mesos-resources reports the size of free space in /var/lib/mesos but what actually takes space are the docker images that land in /var/lib/docker. Isn't this a problem? (mesos doesn't reflect it nodes true capacity)

**Comment by anhowe** [comment]
Closing this, since it is a p2 not on our roadmap.  Please re-open if you think we need this, and also if any new scenarios highlight the need of this.
