### ISSUE TITLE
K8s - Internal Load Balancer cannot be provisioned when VNET is outside the Resource Group

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#1333]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE (possibly upstream)

---

**What version of acs-engine?**: LATEST

---

I attempted to expose an NGINX container on a Kubernetes 1.7.4 cluster, where the VNET of the K8s cluster is not contained in the same Resource Group as the one that ACS-Engine used to create the cluster.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

No internal load balancer was created; I left it for 12 hours to try to provision one.

**What you expected to happen**:

The creation of an internal load balancer

**How to reproduce it** (as minimally and precisely as possible):

Install a k8s 1.7.4 cluster
Create an nginx pod
Expose the nginx pod via an internal load balancer by setting the annotation on the service to "service.beta.kubernetes.io/azure-load-balancer-internal: 
true"

**Anything else we need to know**:

This may be an upstream issue with kubernetes itself and not acs-engine

**Comment by dcieslak19973** [comment]
Per: https://github.com/kubernetes/kubernetes/pull/49725

The file /etc/kubernetes/azure.json on the masters needs to have the property vnetResourceGroup added with the appropriate value.

I manually added this post-install and rebooted the master node and it worked.

**Comment by sylr** [comment]
There are already PR for this :

https://github.com/Azure/acs-engine/pull/1150
https://github.com/Azure/acs-engine/pull/1142

**Comment by bigmyx** [comment]
Having the same issue.. Any update on a fix?

**Comment by karataliu** [comment]
Verified this works with v1.8, addressed by https://github.com/Azure/acs-engine/pull/1150
