### ISSUE TITLE
Kubernetes agents don't always attach to master - missing 1 minute grace period

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#1334]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: all

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**: Kubernetes agents need to wait 1 minute to reboot, so that the CSE can properly signal completion.  Otherwise, deployments will fail, or agents will fail to attach.

**Comment by jackfrancis** [comment]
fixed by https://github.com/Azure/acs-engine/pull/1335
