### ISSUE TITLE
Question about `firstConsecutiveStaticIP` param

### ISSUE THREAD

**Issue by bigmyx** [Azure/acs-engine#1337]
**Is this a request for help?**:
---
I have a question about `firstConsecutiveStaticIP` parameter.
Due to the fact we re-use a subnet from another Resource Group, we do not control the IP addresses allocation.
Can the parameter above be dynamic according to the subnet?

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
no

**What version of acs-engine?**:
---
v0.5.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
---
Kubernetes

**Comment by keatz55** [comment]
I too would be interested in some additional documentation around the `firstConsecutiveStaticIP`. Either way, great job on this project!
