### ISSUE TITLE
DNS Configuration is not correct on Kubernetes Nodes

### ISSUE THREAD

**Issue by bigmyx** [Azure/acs-engine#1354]
**Is this a request for help?**:
---
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Issue

**What version of acs-engine?**:
---
v0.5.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
---
Kubernetes

**What happened**:
---
After deploying a Kubernetes cluster, the DNS settings on the nodes dont seem to be correct:

```
cat /etc/resolv.conf

nameserver 192.168.48.11
nameserver 192.168.48.14
search reddog.microsoft.com
```

When I deploy Kubernetes using Azure portal as a container service, I got this:

```
ameserver 168.63.129.16
search yz3ohtvxc4tutkrevfbn5xgm3e.xx.internal.cloudapp.net
```

moreover: `hostname -f` gives a correct value on the host deployed by acs-engine:

```
hostname -f
k8s-master-92129213-0.yz3ohtvxc4tutkrevfbn5xgm3e.xx.internal.cloudapp.net
```

when trying on the acs-deployed one:

```
hostname -f
hostname: Name or service not known
```

Here is my current deployment code (I use it on combination with Terraform): https://gist.github.com/bigmyx/5f9e2812c2bc8dec7fcbeda03a790898

As a result Kubernetes cluster is not functional:
For instance:
```
kubectl logs mic-test2-1124265738-7zsqc
Error from server: Get https://k8s-agentpool1-74729379-0:10250/containerLogs/default/mic-test2-1124265738-7zsqc/mic-test2: dial tcp: lookup k8s-agentpool1-74729379-0 on 192.168.48.11:53: no such host
```

**How to reproduce it** (as minimally and precisely as possible):
---
Generate and run deployment using `k8s.json` from the Gist above.
Please note: As you can see from the configuration above, I am connecting this cluster to a shared Subnet from another Resource Group.

**Comment by bigmyx** [comment]
Seems like this specific issue is not directly related to `ecs-engine`, since the DNS VM configuration is done by Azure service.. 
Closing it now.

**Comment by gitnik** [comment]
Any more hints as to how you got this solved @bigmyx ? I'm running into the same problem

**Comment by yfried** [comment]
@bigmyx Any update or workaround here? I'm stuck as well
