### ISSUE TITLE
Please create a new release 0.5.1 to fix vlabs template generation

### ISSUE THREAD

**Issue by ivanfioravanti** [Azure/acs-engine#1359]
Current 0.5.0 release is not working with vlabs apiversion, because examples in source code are not compatible. This issue has been already fixed by @dmitsh in  #1332 

Problem is that examples have been updated replacing `servicePrincipalClientID` with `clientId` but release 0.5.0 is expecting old values so generation fails with error: 
`FATA[0000] error parsing the api model: the service principal client ID must be specified with Orchestrator Kubernetes`

**Comment by PoisonousJohn** [comment]
Sure the same goes with servicePrincipalClientSecret

**Comment by oivindoh** [comment]
+1, this caused a lot of head scratching and finally hair pulling on my end

**Comment by ivanfioravanti** [comment]
Is anyone from ACS Engine team reviewing open issues? This is really an easy one. Thx

**Comment by shahiddev** [comment]
0.6.0 doesn't work with the new template names either see #1427
