### ISSUE TITLE
k8s integration with existing private network 

### ISSUE THREAD

**Issue by bathizte** [Azure/acs-engine#1360]
**Is this a request for help?**:
---
No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Feature Request

**What version of acs-engine?**:
---
0.5.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.6

**What happened**:

We want to integrate a k8s cluster into our private network linked to Azure using a VPN. 
We made a successful deployment using and existing VNET which address space is 10.A.B.0/26
However we ran into some issues with the masquerading exclusion of the traffic which is by default set on 10.0.0.0/8. 
Network traffic coming from the pods could not be routed back because their sources address where not known outside of the cluster. 

**What you expected to happen**:

We want to have the network traffic properly routed from the pods to the outside of the cluster and back. 

There is a configuration option at the kubelet level (--non-masquerade-cidr option).

So we want to submit a fix for the ACS Engine, and will listen to any advice on it or any related subject in order to have a robust existing subnet integration in a private network context.

**How to reproduce it** (as minimally and precisely as possible):

Set up a k8s deployment using an existing VNET integrated in a private network overlapping with the 10.0.0.0/8 space. 

**Anything else we need to know**:

...

**Comment by bathizte** [comment]
Hello,

Do you have any comments on this feature and the way we implemented it ?
Any chance that you could review the PR ? 

Thanks !

**Comment by SaaldjorMike** [comment]
Linking this with #425
