### ISSUE TITLE
Dynamic disk in PersistentVolumeClaim mounted twice

### ISSUE THREAD

**Issue by krish7919** [Azure/acs-engine#1364]
**Is this a request for help?**: Yes.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: No idea. I use Kubernetes on ACS.

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Issue with mounting persistent volume claims (2 disks) for MongoDB Statefulset.
We use 2 persistent volume claims to mount 2 dynamic disks at runtime.
The `data` disk from MongoDB were never mounted.
The `configdb` disk from MongoDB was mounted in the mountpoint reserved for the `data` disk.

Output of `lsblk`:
```
root@mdb-instance-1-ss-0:/# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk
sda      8:0    0   30G  0 disk
`-sda1   8:1    0   30G  0 part /etc/mongod/ca
sdb      8:16   0  100G  0 disk
`-sdb1   8:17   0  100G  0 part
sdc      8:32   0   20G  0 disk
sdd      8:48   0    1G  0 disk /data/configdb
sr0     11:0    1 1024M  0 rom
```
Output of `mount`. Notice the `/dev/sdd` repeated:
```
root@mdb-instance-1-ss-0:/# mount | grep data
/dev/sdd on /data/db type ext4 (rw,relatime,data=ordered)
/dev/sdd on /data/configdb type ext4 (rw,relatime,data=ordered)
/dev/sda1 on /dev/termination-log type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /etc/resolv.conf type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /etc/hostname type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /etc/hosts type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /etc/mongod/ca type ext4 (rw,relatime,discard,data=ordered)
```

**What you expected to happen**:
Usually, when MongoDB restarts, the PVCs ensure that the disks are re-mounted correctly automatically.
Expected output of `lsblk` (taken from another cluster):
```
root@mdb-instance-1-ss-0:/# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk
sda      8:0    0   30G  0 disk
`-sda1   8:1    0   30G  0 part /etc/mongod/ca
sdb      8:16   0  100G  0 disk
`-sdb1   8:17   0  100G  0 part
sdc      8:32   0    1G  0 disk /data/configdb
sdd      8:48   0   20G  0 disk /data/db
sr0     11:0    1  668K  0 rom
```

Expected output of `mount` (taken from another cluster):
```
root@mdb-instance-1-ss-0:/# mount | grep data
/dev/sdd on /data/db type ext4 (rw,relatime,data=ordered)
/dev/sdc on /data/configdb type ext4 (rw,relatime,data=ordered)
/dev/sda1 on /dev/termination-log type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /etc/resolv.conf type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /etc/hostname type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /etc/hosts type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /etc/mongod/ca type ext4 (rw,relatime,discard,data=ordered)
```

**How to reproduce it** (as minimally and precisely as possible):
I have no idea.

**Anything else we need to know**:
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by krish7919** [comment]
Might be related to #793

**Comment by jackfrancis** [comment]
#793 suggests this is fixed in kubernetes version `1.7.2`. `acs-engine` currently supports generating a template that you can submit to build a `1.7.2` cluster. Let me know if you'd be interested in, and need some help, building a `1.7.2` cluster as a test to see if this symptom is fixed with that version.

**Comment by krish7919** [comment]
Hi @jackfrancis !
Information to set up a k8s v1.7 cluster is surely welcome, although, I have no idea how to reproduce this issue. Any suggestions on repre steps?

**Comment by jackfrancis** [comment]
If this is not a reproducible problem, and only occurs through the Azure portal-guided ACS flow, it's likely this shouldn't be an open issue in the acs-engine project. I'm happy to keep it open for a little while as a placeholder if it would help to triage this issue, assuming you expect it to re-occur.

Here's a link to a doc describing how to get and build acs-engine for local use:

https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md

And here's a doc that describes some of the Kubernetes scenarios that acs-engine supports above and beyond what the ACS will build you via the portal or az CLI tool:

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md

**Comment by jalberto** [comment]
I have similar problem using acs-engine master with k8s 1.8 and 1.7.7

```
viz@k8s-pool01-11577755-0:~$ sudo mount | grep sdc
/dev/sdc on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b960592259 type ext4 (rw,relatime,data=ordered)
/dev/sdc on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b960592259 type ext4 (rw,relatime,data=ordered)
/dev/sdc on /var/lib/kubelet/pods/19c5b607-b5ae-11e7-924b-000c3a2c338b/volumes/kubernetes.io~azure-disk/pvc-60e500d8-b5ad-11e7-924b-000c3a2c338b type ext4 (rw,relatime,data=ordered)
/dev/sdc on /var/lib/kubelet/pods/19c5b607-b5ae-11e7-924b-000c3a2c338b/volumes/kubernetes.io~azure-disk/pvc-60e500d8-b5ad-11e7-924b-000c3a2c338b type ext4 (rw,relatime,data=ordered)
```

**Comment by andyzhangx** [comment]
Hi @jalberto  your issue is expected, `/dev/sdc` will first mount to `/var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b960592259` and then k8s would "bind mount" to `/var/lib/kubelet/pods/19c5b607-b5ae-11e7-924b-000c3a2c338b/volumes/kubernetes.io~azure-disk/pvc-60e500d8-b5ad-11e7-924b-000c3a2c338b`, it's not a issue.
