### ISSUE TITLE
Managed disks should mount to /dcos/volumn[0-3]

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#137]
On agents created with one or more Managed Disks.

Also, the agent should be able to see these disks and offer them as resources to Mesos

**Comment by xtophs** [comment]
My PR (https://github.com/Azure/acs-engine/pull/80) mount the disks. Waiting for approval

**Comment by anhowe** [comment]
Thanks Christoph, we will take a look at your PR!

**Comment by jackfrancis** [comment]
@xtophs I see that #80 was closed without being merged. Was this issue ever addressed?

**Comment by xtophs** [comment]
I don't believe so. I can reissue this weekend.

**Comment by jackfrancis** [comment]
Super, thanks!

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
