### ISSUE TITLE
Change nodes size for existing cluster

### ISSUE THREAD

**Issue by oryagel** [Azure/acs-engine#1370]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.5.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.3

Hi,
I want to change the vm size of the nodes in an existing cluster.
Is that supported?
How can I do that?

Thanks

**Comment by nalthoff** [comment]
Can you resize in the portal? I successfully resized a agent VM in the portal. Not sure how automated you need it to be.

**Comment by oryagel** [comment]
Thanks! Even if it works, I think it will break `acs-engine-autoscaler`. It seems that the autoscaler fetches the ARM deployment in order to determine the instance size. I guess that changing the instance size from the Azure Portal won't change the ARM deployment. I can try that tomorrow.

**Comment by nalthoff** [comment]
I wonder what happens if you update the apimodel and redeploy? that should
recreate the deploy.json files and maybe change all of the VM's Sizes...


----------------------------------------------------------------
Nicholas D. Althoff

**Comment by mdpradeep** [comment]
We have the same issue. We started off the cluster with `Standard DS4` but we want to move to `Standard DS14`. The issues are:

1.  You have to manually move each of the nodes to the new type.
2. The new nodes that get created still have the old VM type.

Tried the `redeploy` option from the azure portal and that failed with no meaningful error. Having the above features is critical for any production deployment.

**Comment by nalthoff** [comment]
I was able to successfully scale my VM's using the asc-engine deploy option. I had the apimodel.json file that was created during the initial deploy. I changed the VM size on the agent pool and did the asc-engine deploy... and it worked! You are restricted to changing sizes based on your initial choice though. 
For example. I initially tried to change from Standard_A2 to Standard_D2_V2 and got this error:

{
  "error": {
    "code": "OperationNotAllowed",
    "target": "vmSize",
    "message": "Unable to perform Operation 'Update VM' on the VM because the requested size Standard_D2_v2 is not available in the cluster where the availability set is currently allocated. The available sizes are: Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A4,Standard_A5,Standard_A6,Standard_A7. Read more on VM resizing strategy at https://aka.ms/azure-resizevm."
  }
}
When I changed to Standard_A3 it worked perfectly.

**Comment by oryagel** [comment]
Thanks @nalthoff 
I don't remember using the `apimodel.json` in the cluster creation process. I used the following to create the cluster: https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md#deploy-templates
I used the `azuredeploy.json` and `azuredeploy.parameters.json` to create the cluster. How should I use the `apimodel.json` to alter the cluster?

Thanks

**Comment by nalthoff** [comment]
With acs-engine you can either use the "deploy" command or the "generate" command. With either of those, you will get files that are put into an "_output/[DNSNAME]" folder. Details at this link(https://github.com/Azure/acs-engine/blob/d9b7711f966acb9a7bcf7dc3278e38770459b3c3/docs/acsengine.md) See the "usage" section.
Example using the acs-engine deploy approach here: 
https://github.com/Azure/acs-engine/blob/d9b7711f966acb9a7bcf7dc3278e38770459b3c3/docs/kubernetes/deploy.md

Ping me on slack too and I can help you out.

**Comment by SaaldjorMike** [comment]
I guess another approach to it could be to deploy a new agentpool (using the agentpool-only approach) with whatever desired VM size you want and then delete the old agentpool.

**Comment by nalthoff** [comment]
I haven't heard of that approach. Do you have a link / docs?

**Comment by SaaldjorMike** [comment]
PR #1290 merged in support for this, but I dont believe we have any docs for it yet. 

Essentially what you'd need to do is to use a JSON file like this: https://github.com/Azure/acs-engine/blob/master/examples/agents-only.json

All the values should be populated based on the JSON files generated for the original deployment, except of course for `agentPoolProfiles` as this is where you specify the new pools.

Briefly tested it out yesterday, and worked fine for me. In my case I deployed the new agentpool using the same `vnetSubnetId` as the existing cluster so I used the IP of the internal load balancer for the master nodes in the `fqdn` field.

As there is still no docs for it, I guess the agentpool-only is still very much experimental.

**Comment by blacksails** [comment]
When i try to do the redeploy approach I get some errors: 
```
ERRO[0040] {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"error\": {\r\n    \"code\": \"PropertyChangeNotAllowed\",\r\n    \"target\": \"customData\",\r\n    \"message\": \"Changing property 'customData' is not allowed.\"\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"error\": {\r\n    \"code\": \"PropertyChangeNotAllowed\",\r\n    \"target\": \"dataDisk.createOption\",\r\n    \"message\": \"Changing property 'dataDisk.createOption' is not allowed.\"\r\n  }\r\n}"}]}}
FATA[0040] resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
```

**Comment by jwalker343** [comment]
@SaaldjorMike When you deployed the agent-only profile, for the certificate profile:
`    "certificateProfile": {
      "caCertificate": "cert_Ca",
      "caPrivateKey": "cert_Cakey",
      "apiServerCertificate": "cert_Api",
      "apiServerPrivateKey": "cert_apikey",
      "clientCertificate": "cert_client_pem",
      "clientPrivateKey": "cert_client_key",
      "kubeConfigCertificate": "cert_kube_pem",
      "kubeConfigPrivateKey": "cert_kube_key"
    }`

Are those references to the files, Base64 encoded, or passed in as some other format?

**Comment by SaaldjorMike** [comment]
@jwalker343 As far as I recall, they were not base64 encoded last time I tested it. I do remember that all I did was to copy the values directly from the ARM templates that generated and used for my initial deployment.

**Comment by CecileRobertMichon** [comment]
@jwalker343 @SaaldjorMike @blacksails @nalthoff the correct way of adding agent nodes is to use the `scale` command. See https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/scale.md for details.

**Comment by nalthoff** [comment]
Nice! I didn't know that existed. I think the question is more about size of the nodes, not the number of them, but thanks for the info

**Comment by CecileRobertMichon** [comment]
I was referring to 

> I guess another approach to it could be to deploy a new agentpool (using the agentpool-only approach)

, the agenpool-only model is not meant to add agent pools, the scale command is. In terms of changing the size of a node, your approach @nalthoff 

> I was able to successfully scale my VM's using the asc-engine deploy option. I had the apimodel.json file that was created during the initial deploy. I changed the VM size on the agent pool and did the asc-engine deploy

 seems to be the right one.

**Comment by SaaldjorMike** [comment]
@CecileRobertMichon It is worth noting that my previous comment about adding a new agentpool and deleting the old one was posted on 26 Sep 2017, whereas the scale command was first merged in 24 Oct 2017 (see https://github.com/Azure/acs-engine/pull/1636). Personally I haven't tried the scale command yet.

>  the agenpool-only model is not meant to add agent pools, the scale command is

I was under the impression that scale command was meant for scaling already-existing agentpools as you have to specify which pool you want to scale. Also
https://github.com/Azure/acs-engine/blob/master/cmd/scale.go#L161
prints a fatal log error if does not find the specified agentpool. Am I missing something here?

**Comment by jwalker343** [comment]
@SaaldjorMike I don't think so, there are 3 distinct methods in this thread:

- Modifying existing agents to a different VM class (i.e. D2_v2 to D3_v2) which should probably be done via the re-deploy method. (this is vertical scaling)

- Adding new agents to an existing agent pool (Horizontal scaling) and should be done via the scale command

- Adding a new agent pool with new set of agents (i.e. for a different workload or different node features like GPUs, etc..) which should be done using the agentpool-only method.

I'm am still experimenting with agentpool only as It looks like i'll need that feature relatively soon.

**Comment by CecileRobertMichon** [comment]
@SaaldjorMike I had a typo in my comment, I meant "add agent nodes", not "add agent pools" I edited it to reflect that, sorry for the confusion.

**Comment by jackfrancis** [comment]
Just to add some thoughts: we always encourage acs-engine experimentation; but caveat emptor w/ respect to agent pool-only re-use patterns. Those libraries are consumed by AKS (managed kubernetes) and then rationalized by higher order code. They were not intended to be used natively w/ existing acs-engine clusters (nor to be used to build novel clusters).

Hope that makes sense. All that being said, we're definitely curious if anyone has managed to wrange anything functional in Azure using those libraries.
