### ISSUE TITLE
Error when creating Cluster Role [Windows] [Kubernetes]

### ISSUE THREAD

**Issue by mfaizanse** [Azure/acs-engine#1376]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
(Deployed using Azure Portal)
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes with windows worker nodes
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
`Error from server (Forbidden): error when creating "promethius-clusterrole.yaml": clusterroles.rbac.authorization.k8s.io "prometheus-operator" is forbidden: attempt to grant extra privileges: [{[*] [extensions] [thirdpartyresources] [] []} {[*] [apiextensions.k8s.io] [customresourcedefinitions] [] []} {[*] [monitoring.coreos.com] [alertmanagers] [] []} {[*] [monitoring.coreos.com] [prometheuses] [] []} {[*] [monitoring.coreos.com] [servicemonitors] [] []} {[*] [apps] [statefulsets] [] []} {[*] [] [configmaps] [] []} {[*] [] [secrets] [] []} {[list] [] [pods] [] []} {[delete] [] [pods] [] []} {[get] [] [services] [] []} {[create] [] [services] [] []} {[update] [] [services] [] []} {[get] [] [endpoints] [] []} {[create] [] [endpoints] [] []} {[update] [] [endpoints] [] []} {[list] [] [nodes] [] []} {[watch] [] [nodes] [] []} {[list] [] [namespaces] [] []}] user=&{kubeconfig  [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]`

**What you expected to happen**:
It should create the clusterrole.

**How to reproduce it** (as minimally and precisely as possible):
1. Clone [Prometheus-operator](https://github.com/coreos/prometheus-operator)
2. Run "kubectl apply -f bundle.yaml"

**Anything else we need to know**:
I have tried binding cluster-admin role to kubernetes user but still the same issue.
Related Link: [https://coreos.com/operators/prometheus/docs/latest/troubleshooting.html](https://coreos.com/operators/prometheus/docs/latest/troubleshooting.html)

Note:
I am using windows containers.
My main goal is to get Horizontal Pod Autoscaling working with windows containers.

**Comment by oivindoh** [comment]
This is ACS, not acs-engine. ACS does not currently support RBAC. It has made it into [acs-engine](https://github.com/Azure/acs-engine/pull/1143) recently, however.

**Comment by mfaizanse** [comment]
@oivindoh Can you tell me when acs-engine new changes are pushed to ACS? And where I can find the list of supported kubernetes features in ACS and acs-engine?
