### ISSUE TITLE
Specify the Windows version in API Model

### ISSUE THREAD

**Issue by robbiezhang** [Azure/acs-engine#1383]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature request
---

**What version of acs-engine?**:
Any version
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
The ARM template generated by the acs-engine always uses the "latest" as the agentWindowsVersion

**What you expected to happen**:
It's better that we can specify the agentWindowsVersion in the API model

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by itowlson** [comment]
If we were to add this, should we set it globally for the cluster level (as part of the `windowsProfile` section of the apimodel) or separately for each agent pool (in the `agentPoolProfile` section)?  Other Windows settings, such as admin username, are in the cluster `windowsProfile`; is there any need for per-pool Windows OS images?
