### ISSUE TITLE
Error deploying extensions on DC/OS

### ISSUE THREAD

**Issue by stuartleeks** [Azure/acs-engine#1385]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: Current master at time of opening issue (https://github.com/Azure/acs-engine/commit/99802def22fd76c7b74d681076ec8b3a6755d260)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** DC/OS 

**What happened**: When deploying the a DC/OS cluster with either the hello-world-dcos or vamp-dcos extensions the following error 

```
Deployment failed. {
  "error": {
    "code": "InvalidTemplate",
    "message": "Deployment template validation failed: 'The template parameters 'masterVMNamePrefix' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'artifactsLocation, apiVersionDefault, targetVMName, extensionParameters'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'."
  }
}
```

**What you expected to happen**: The cluster and extensions should be successfully deployed

**How to reproduce it** (as minimally and precisely as possible): 

* Fill out the required fields in `examples/extensions/dcos.json`
* Remove the `rootUrl` property for the extension: https://github.com/Azure/acs-engine/blob/master/examples/extensions/dcos.json#L50
* generate the template and deploy

**Anything else we need to know**:
The error seems to be because the template expansion ends up pulling in the `masterOffset` variable which is defined for the k8s templates but not for DC/OS.

By default, the content for the scripts etc are pulled from the raw links on github. The `rootUrl` allows this to be overridden which simplifies development.

Since the examples have the `rootUrl` specified to point to the storage account that @robbagby created for the original PR, the examples will use those versions of the templates and scripts rather than the ones in the repo.

It might be worth removing the `rootUrl` from the examples to avoid this confusion.

**Comment by stuartleeks** [comment]
@JackQuincy - I am just finishing up testing a PR for this. Let me know your thoughts on removing the `rootUrl` property from the examples and I can include that in the PR

**Comment by jackfrancis** [comment]
@stuartleeks I wonder if @JackQuincy's PR #1392 addressed this? That PR went out last week, so if you get current w/ master you could try a fresh dcos deploy w/ extensions.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
