### ISSUE TITLE
Cluster not functioning when created using latest / HEAD

### ISSUE THREAD

**Issue by nalthoff** [Azure/acs-engine#1386]
**Is this a request for help?**: 

Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE
---

**What version of acs-engine?**:
Latest / HEAD

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.1

**What happened**:
I pulled latest acs-engine. generated the model and deployed via "az group create ...'

**What you expected to happen**:
Cluster was stood up and I could connect via KubeCtl

**How to reproduce it** (as minimally and precisely as possible):
1. Pull latest code
2. Use Attached json file to generate assets
3. Run az group create to generate cluster
4. Attempt to connect to cluster to pull nodes (kubectl get nodes --kubeconfig=./kubeconfig/kubeconfig.southcentralus.json)

**Anything else we need to know**:
Here is the .json file i used to generate the arm templates:
```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
	"orchestratorRelease": "1.7",
      "orchestratorVersion": "1.7.1"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "k8s171-gc",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "REDACTED"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "REDACTED",
      "secret": "REDACTED"
    }
  }
}
```

I ssh'ed into the master and it looks like the Kubelet is having trouble getting started. Here are the errors I see when I run journalctl -u kubelet -f
```
Sep 01 15:47:53 k8s-master-42072372-0 docker[2509]: E0901 15:47:53.444437    2534 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://10.240.255.5:443/api/v1/services?resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused
Sep 01 15:47:53 k8s-master-42072372-0 docker[2509]: E0901 15:47:53.445827    2534 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://10.240.255.5:443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8s-master-42072372-0&resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused
Sep 01 15:47:53 k8s-master-42072372-0 docker[2509]: E0901 15:47:53.446924    2534 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://10.240.255.5:443/api/v1/nodes?fieldSelector=metadata.name%3Dk8s-master-42072372-0&resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused
```

**Comment by lachie83** [comment]
Those errors are because kubelet cannot connect to the api-server. Can you confirm if the API server is running?

**Comment by nalthoff** [comment]
It was not running. the docker-ps just showed the kubelet. Is there a trick to get it started if it doesn't start automatically?

**Comment by lachie83** [comment]
Kubelet should try to restart it automatically. You can take a look at the logs using journalctl

**Comment by lachie83** [comment]
I will try to repo next week. I would suggest using the 0.5.0 release given that it's working for you

**Comment by nalthoff** [comment]
Was an issue w/ Service principle. Cluster up and running correctly using the right info... Closing
