### ISSUE TITLE
label k8s nodes with agent pool and custom labels

### ISSUE THREAD

**Issue by slack** [Azure/acs-engine#139]
It would be great if nodes were labeled with the agent pool (and any other metadata that makes sense).

**Comment by yangl900** [comment]
+1. I would like labels e.g. VM SKU, and if possible, custom labels specified from apimodel.

**Comment by colemickens** [comment]
This is a similar change being done for DCOS: https://github.com/Azure/acs-engine/pull/138

**Comment by bnookala** [comment]
Hi👋 @dmitsh, @anhowe,

@wbuchwalter, @ritazh and I are working with a customer right now and they're in need of this. Is this something that is actively being worked on? We're thinking of rolling out a fix for it ourselves. 

Thanks!

**Comment by seanknox** [comment]
@bnookala As you discovered we did not have this work in the hopper, thanks for grabbing it!
