### ISSUE TITLE
k8s clusters missing requestheader-client-ca-file

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1390]
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of acs-engine?**: n/a

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes v1.7

**What happened**: aggregated API servers need both `client-ca-file` and `requestheader-client-ca-file` keys, current acs-engine-built kubernetes 1.7 clusters are missing `requestheader-client-ca-file`

Ref:

https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/auth.md#requestheader-authentication

Starting up the API server with `--requestheader-client-ca-file <string>` option engaged should fix this.

**Comment by sabbour** [comment]
Was this fixed? I'm getting hit by this in https://github.com/Azure/helm-charts/issues/102 using acs-engine 0.11.0.

**Comment by sabbour** [comment]
I was trying to provision the Service Catalog API with rbacEnabled=false
When using rbacEnabled=true (the default), it worked.

**Comment by jackfrancis** [comment]
Thanks for providing this color, @sabbour. Yes, we expect service catalog to be fully functional w/ an orchestratorProfile that looks like the one you pasted. Let us know if you run into any further trouble.
