### ISSUE TITLE
Logs exhaust available disk space

### ISSUE THREAD

**Issue by anisimovsergey** [Azure/acs-engine#1394]
**Is this an ISSUE or FEATURE REQUEST?**: ISSUE

---

**What version of acs-engine?**: v0.5.0

---

**Orchestrator and version**
Kubernetes

**What happened**:

The policy for the log files rotation was changed recently in [this commit](https://github.com/Azure/acs-engine/commit/0b43f5c2d0f541d585dcb60db298be747759c452) 
Previously logs for any container could occupy  50 Mb x 5 = 250 Mb now it's 200 Mb x 25 = 5000 Mb = 5 Gb  it's 20 times more! 

If you run a Kubernetes cluster based on standard DS3_V2 nodes with 28 Gb disk attached to each, you can exhaust disk space after spinning up 5 containers on every VM theoretically. In reality, you usually end up having little bit less than 25 Gb free space and therefore you can run up to 4 containers per VM max. 

**What you expected to happen**:

I would expect that it would be possible to run at least 10 micro-services on a single VM (DS3_V2) without filling its disk with log files. I would also expect from people who use ACS in production to use logs aggregation stacks (e.g. Fluentd/Elasticsearch/Kibana) avoiding huge log files completely. 

**How to reproduce it**:

Create a Kubernetes cluster and spin up several containers which log a lot, wait a bit and check the available disk space.

**Anything else we need to know**:

It would be nice to have such breaking changes mentioned in the release notes.

**Comment by rjtsdl** [comment]
@anhowe
