### ISSUE TITLE
Kubernetes: Unable to alter system deployments

### ISSUE THREAD

**Issue by DavidRouyer** [Azure/acs-engine#1397]
**Is this a request for help?**:
---
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**What version of acs-engine?**:
---
0.5.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I've created a cluster using the ACS engine and I'm trying to update the kubernetes-dashboard by doing a deployment update or by setting the image (v1.6.1 to v1.6.3). The deployment is updated, a new Replica Set is created with the new version, but another update occur and a new Replica Set is created with the old version (v1.6.1). I'm also trying to move my dashboard to another node with the nodeSelector, but same result.

**What you expected to happen**:
My deployment shouldn't be overrided and my dashboard should be updated correctly.

**How to reproduce it** (as minimally and precisely as possible):
Just do a `kubectl apply -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/ku
bernetes-dashboard.yaml`. The deployment will be updated, but another update will be applied to rollback the dashboard to its initial state.

**Anything else we need to know**:
Is there any mecanism which prevent to update deployments in kube-system?

**Comment by sanguinius69** [comment]
Hey ! 
Same issuer here as I am trying to update tiller version from v2.5.1 (original deploy) to the new version v2.6.0 but unsure why the new deploy is killed and rolled back to v2.5.1.
If anybody could enlighten us ??
cheers !

**Comment by mcwienczek** [comment]
I think the reason is the same as in acs clusters - components declared at cluster creation are forced and re-created in case someone tried to change them. If you want to change thos components you would need to ssh into master machine and change file manifests manually.

For example: https://github.com/Azure/ACS/issues/55
