### ISSUE TITLE
Where could I specify k8s version in acs config file

### ISSUE THREAD

**Issue by andyzhangx** [Azure/acs-engine#1401]
I see there is code change for deploy k8s by acs-engine, the orchestratorVersion field is removed, so where could I specify k8s version in acs config file? The default example of k8s does not give the details.

**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by sozercan** [comment]
It's called`orchestratorRelease` now
https://github.com/Azure/acs-engine/blob/master/examples/kubernetes-releases/kubernetes1.7.json

**Comment by andyzhangx** [comment]
@sozercan I have checked the json file, it says `"orchestratorRelease": "1.7"`, then how should I specify the minor version, e.g. 1.7.2

**Comment by sozercan** [comment]
You don't specify minor version anymore, version is whatever is latest on the repo.

https://github.com/Azure/acs-engine/blob/343774d0c874caadbc51e909c329a025e7359670/pkg/acsengine/const.go#L102-L103

**Comment by andyzhangx** [comment]
Thanks for your guide, I have tried, it works well.
