### ISSUE TITLE
Terraform integration

### ISSUE THREAD

**Issue by koalalorenzo** [Azure/acs-engine#1402]
---
FEATURE REQUEST
---

**What version of acs-engine?**:
Any version
---
Hey Guys,
I am trying to use `ACS-engine` to generate a Terraform ❤️ configuration instead of ARM templates
 🤢 
Something like `--terraform` as an option would be highly appreciated 👍 
Any idea/plan for this?

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.5

**What you expected to happen**:
Use Terraform instead of ARM templates

**Comment by snpdev** [comment]
See https://github.com/Azure/terraform-provider-acsengine. (There is also https://github.com/daniel-rhoades/acs-engine-terraform, but last updated on  Jul 7, 2017).
