### ISSUE TITLE
Support for Cluster Destroy Operation 

### ISSUE THREAD

**Issue by bigmyx** [Azure/acs-engine#1411]
**Is this a request for help?**:
---
No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Yes

**What version of acs-engine?**:
---
```
Version: canary
GitCommit: bde8e414
```

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.
---
Support for an automatic resource destruction, for example, if I want to constantly build/destroy a Kubernetes clusters in my dev environment on Azure, yet keeping all those clusters in one Resource Group, which I don't want to delete..   Thanks in advance!

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
---
Kubernetes

**Comment by luhkevin** [comment]
Any updates on this? I would like this as well.
