### ISSUE TITLE
Calico should be updated to v2.5

### ISSUE THREAD

**Issue by tmjd** [Azure/acs-engine#1417]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature request

**What version of acs-engine?**:

latest

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**Request**:

Calico should be updated to v2.5
​
With Kubernetes deprecation of ThirdPartyResources (TPR) in favor of  Custom Resource Definitions (CRD) Calico has to switch over to CRDs. The v2.5 release makes that switch and requires a migration step for deployments using the Kubernetes Datastore. A migration guide can be found https://github.com/projectcalico/calico/tree/master/upgrade/v2.5

Another thing to be aware of is that CRDs are first available in Kubernetes v1.7. This means that if Calico v2.5 is using the Kubernetes Datastore it must be used with Kubernetes 1.7+, it cannot be used 
with Kubernets 1.6.x or lower.
​
Feel free to reach out to me (@tmjd or erik.stidham on slack) or @ozdanborne on github, Kubernetes slack, or Calico slack to collaborate.

**Comment by dtzar** [comment]
I've already started to work on this in the [calico branch](https://github.com/Azure/acs-engine/tree/calico) with not only the goal to migrate to 2.5.1, but to migrate to the etcd backed (full) policy version "Standard Hosted Install".  I got acs-engine + K8s 1.6.9 to work with a vanilla non-calico template and then manually applying the calico templates and switching kubelet on the nodes to use cni (from kubenet).  However, when I deploy a new template  from that branch a number of addons fail to start.  I'm planning to troubleshoot with @lachie83 tomorrow and see where we get.
