### ISSUE TITLE
Ability to specify RP versions as an input

### ISSUE THREAD

**Issue by radhikagupta5** [Azure/acs-engine#1424]
Feature Request:
The default template that is generated by ACS Engine is created with following API versions. We should have ability to add these as input so if someone wants to change these they can. For example Azure Stack is still on few older API versions and we would like to pass these as input to the template generator.

    "apiVersionDefault": "2016-03-30",
    "apiVersionLinkDefault": "2015-01-01",
    "apiVersionStorage": "2015-06-15",
    "apiVersionStorageManagedDisks": "2016-04-30-preview",
---
**Is this an ISSUE or FEATURE REQUEST?** (choose one): This is a feature request.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes, Swarm or DC/OS

**Comment by itowlson** [comment]
If acs-engine just naively allowed a user to customise the RP version string, without changing the template properties body accordingly, we might end up with a template that doesn't conform to its declared API version.  So it seems like this would require the engine to have schemas for all the different possible RP versions, which could be very complex and time-consuming.

If there are API versions that would work for Azure Stack and are schema-compatible with the Azure Cloud template API versions, then I guess that might work, though it could be brittle as the Azure Cloud templates move forward to consume new API versions...
