### ISSUE TITLE
Helm chart incubator/ElasticSearch cannot handle minimal loads

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#1454]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: latest

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kuberenets 1.7.4

**What happened**: When I interact with ElasticSearch (or Kibana) at any sort of pace above one-offs, the elasticsearch-data-[0-2] pods get into a bad state. Once I stop the activity, the pods eventually recover.

**What you expected to happen**:  I would expect ES to be able to keep up with moderate loads; it can't even keep up with light load.

**How to reproduce it** (as minimally and precisely as possible): Provision a kubernetes cluster. Install the Helm Chart for incubator/ElasticSearch. Finally, install the fluentd for Kubernetes daemonset: https://github.com/fluent/fluentd-kubernetes-daemonset

**Anything else we need to know**:  Cross-linked to https://github.com/kubernetes/charts/issues/2195

**Comment by jackfrancis** [comment]
@dcieslak19973 can you describe the specification of your cluster? how many masters/nodes, size of vms, etc

**Comment by dcieslak19973** [comment]
Single node master (D2), 3 Linux VMs (D3v2), 3 Windows VMs (D3v2). I changed the ElasticSearch chart to ensure placement of everything goes to the 3 Linux VMs.

Under "Persistent Volumes", I see 3 resources, each of size 30Gbi. They have the following annotations:
pv.kubernetes.io/bound-by-controller: yes
pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner

Under the Persistent Volume Claims, the one odd thing is "Access Modes: ReadWriteOnce" (the Capacity is set to {"storage":"30Gi"})

Since you are a Microsoft employee, my company has an NDA in place; if it would help, I could set up a Skype session to demonstrate.

Thanks
Dan

**Comment by dcieslak19973** [comment]
Bump

**Comment by dcieslak19973** [comment]
The helm chart was recently updated and seems more stable. Closing this.
