### ISSUE TITLE
Creates translations file next to _output

### ISSUE THREAD

**Issue by rocketraman** [Azure/acs-engine#1459]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: e86076153ce40dfdbd13ff05f0ddc6aca6280727

---

When running `generate` the `_output` directory is created as expected, but so is a `translations` directory containing some translation files.

**Comment by jackfrancis** [comment]
This has been fixed in PR #1426! (merged a couple weeks ago), sorry for the inconvenience!
