### ISSUE TITLE
Proposal for adding 'defaultStorageClass' option for Kubernetes cluster

### ISSUE THREAD

**Issue by karataliu** [Azure/acs-engine#1472]
This is a follow up of #1205, and proposes a fix by adding a 'defaultStorageClass' option in apimodel.

The [doc](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#managed-disks-1) has talked about how to use managed disk on a cluster.

This proposal here is for enabling the usage of `default storage class` with managed disks.

Reference: https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

As per that issue, a worst case is when user created a managed disk only cluster, and then request a PersistentVolumeClaims using default storage class. The PVC request will fail since the default storage class is for unmanaged disks.

For now, every new acs-engine created kubernetes cluster has 'default'(unmanaged disk) as default storage class.
```
$ kubectl get storageclasses
NAME                         TYPE
default (default)            kubernetes.io/azure-disk   
managed-premium              kubernetes.io/azure-disk   
managed-standard              kubernetes.io/azure-disk 
```

A user can manually update default storage class via `kubectl edit storageclasses`, but the result is not persistent. If the master node reboots, the hard-coded value will restore, resulting a invalid situation:
```
$ kubectl get storageclasses
NAME                         TYPE
default (default)            kubernetes.io/azure-disk   
managed-premium              kubernetes.io/azure-disk   
managed-standard (default)   kubernetes.io/azure-disk
```

One workable way is to manually edit `/etc/kubernetes/addons/azure-storage-classes.yaml`, and then we can get a stable result for default storage class.
```
$ kubectl get storageclasses
NAME                         TYPE
default                      kubernetes.io/azure-disk   
managed-premium              kubernetes.io/azure-disk   
managed-standard (default)   kubernetes.io/azure-disk 
```

But this would require manual steps, and if there're several nodes in a master cluster, user has to update all of them, which is painful.

The proposal is as following:
1. Rename 'default' to 'unmanaged'

It does make sense now to name a configuration as 'default', since we've multiple configurations and 'default' is an applicable tag.

https://github.com/Azure/acs-engine/blob/ce0f5f1aa265e619757b406a4a2a28241dafb38a/parts/kubernetesmasteraddons-azure-storage-classes.yaml#L4

2. Add a new option named 'defaultStorageClass' in apimodel (`properties/orchestratorProfile/kubernetesConfig`).
The option's value could be 'a storage class name' defined in previous yaml or empty (default).
  - If a storage class name is specified, we will alter 'azure-storage-classes.yaml' to set the default correspondingly.
  - If empty value is specified, we could infer the default storage class. One approach is to select managed/unmanaged storage class based on first agent pool's configuration 

This *does not* address all issues, especially for cases of using mixed disk types. But it would help on some common scenarios(a managed-disk only cluster, having managed-disk as default storage class).

**Comment by karataliu** [comment]
This is important for AKS, where master node is not directly accessible by user.

**Comment by IvanovOleg** [comment]
@karataliu 
I've got the same error even with modified /etc/kubernetes/addons/azure-storage-classes.yaml
