### ISSUE TITLE
The yaml for format for kubernetesagentcustomdata.yml is incorrect.

### ISSUE THREAD

**Issue by radhikagupta5** [Azure/acs-engine#1476]
Pick the file and run it thru http://www.yamllint.com/ and it gives three errors. I am new to yaml so not sure what the issue is but this should probably be fixed.

https://raw.githubusercontent.com/Azure/acs-engine/master/parts/kubernetesagentcustomdata.yml

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE.

**What version of acs-engine?**:
master
---

**Comment by jackfrancis** [comment]
Thanks for reporting @radhikagupta5. The linting errors are because we have a layer of go templating on top of the .yaml (by design). The raw `.yaml` file is not meant to be literally interpreted as `yaml` until is passes through go templating!
