### ISSUE TITLE
Docker Swarm deployment in an existing VNET with a DNS server fails

### ISSUE THREAD

**Issue by jcorioland** [Azure/acs-engine#148]
When using ACS Engine to deploy a Docker Swarm cluster in an existing VNET that also contains a DNS server, the deployment fails.

The error occurs when executing the configure-swarm-cluster.sh. The master hostname could not be resolved:

```+ for i in '{1..120}'
+ host swarm-master-13212455-0
Host swarm-master-13212455-0 not found: 2(SERVFAIL)
+ '[' 1 -eq 0 ']'
+ sleep 1
+ for i in '{1..120}'
+ host swarm-master-13212455-0
Host swarm-master-13212455-0 not found: 2(SERVFAIL)
```
Thanks

**Comment by colemickens** [comment]
Hi @jcorioland.

It looks like that check was for a platform issue that has since been resolved. Would you be willing to remove this line so that the deployment skips the likely-unneeded network validation? https://github.com/Azure/acs-engine/blob/master/parts/configure-swarm-cluster.sh#L99

**Comment by anhowe** [comment]
This validation is needed since we need a stable network to proceed with the script.  However, the hostname resolution can be removed, since we use IP Addresses for discovery.

**Comment by anhowe** [comment]
These are the lines to remove: https://github.com/Azure/acs-engine/blob/master/parts/configure-swarm-cluster.sh#L39-L56.
