### ISSUE TITLE
Autoscaling Not working on Azure ACS Kubernetes

### ISSUE THREAD

**Issue by hamid2013** [Azure/acs-engine#1497]
**Request For help**:
I have created the ACS kubernetes using the terraform, and then use this repo for the autoscaler. After that i created the load on the agent but due to some reason the agent is not getting scale out.
How to check or troubleshoot for this.
---

**Comment by jackfrancis** [comment]
@lachie83 @sauryadas is there a doc that could help identify if the supported process is being followed, or whether or not something is not working as expected and needs to be tagged as a bug?
