### ISSUE TITLE
Using "long way" deployment doesn't create ACS resource

### ISSUE THREAD

**Issue by jalberto** [Azure/acs-engine#1500]
**Is this a request for help?**:

yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

0.7.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes 1.7.2

**What happened**:
Using "long way" descibred here https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md
The command result is "succeed" but when I run `az acs ls` I got an empty list.
In azure portal I can see the resource group with all expected elements

**What you expected to happen**:
`az acs ls` must show created cluster

**How to reproduce it** (as minimally and precisely as possible):
just follow the link in previous secion

**Anything else we need to know**:

**Comment by SaaldjorMike** [comment]
Pretty sure you need to use `az acs` (and not acs-engine itself) to create the cluster if you need to interact with the cluster using `az acs` afterwards.

**Comment by jalberto** [comment]
it does makes sense, but is quite misleading as mostly documentation mixes both concepts.

It also will make sense if acs-engine is seens as a custom ACS in azure, so some acs commands can be used
