### ISSUE TITLE
Enable ability to provision ipv6 ALB

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#1501]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of acs-engine?**: All

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes 1.7.x

**What happened**:

Enable the ability to provision an IPv6 frontend IP on an ALB via service annotation. 

**What you expected to happen**:

Supply a service annotation to have an IPv6 front-end IP attached to the ALB

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

Not sure if the IP address field support ipv6 an an input so you may have to annotate the service resource with the IP address.

**Comment by itowlson** [comment]
It looks like Azure load balancers support at most one IPv6 address.  So you couldn't actually ask for a specific IPv6 address for a service - you'd have to take what the LB gave you.  (Well, the _first_ service in an availability set could request a specific IPv6 address, but then all other services would have to specify the same IPv6 address or fail.)
