### ISSUE TITLE
Enable Setting Fault & Update Domains for ACS

### ISSUE THREAD

**Issue by ianalderman** [Azure/acs-engine#1509]
FEATURE REQUEST

Forked ACS-Engine (I believe from Current will update when confirmed)

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s 1.7.2

**What happened**:
North Europe had a storage issue, this inevitably took out the Fault Domain with 2 out of the 3 masters.  The single remaining master did not pick up management as it could not form a quorum

**What you expected to happen**:
There should be an option to set the number of Fault Domains, or provide warnings when a chosen FD count would present operational risks. E.g. with 2 FDs I assume you need 5 or 7 masters (if you can't have a quorum with 2 I am not a etcd expert so don't know!).  This also needs to be in place for agents (as in min number of agents to provide capacity).

**How to reproduce it** (as minimally and precisely as possible):
Ideally by taking out a FD in an Azure Region, probably best not though please? :)

**Anything else we need to know**:
Need to think about Update Domains too.

**Comment by aku105** [comment]
Note, this seems to be applicable if we use ManagedDisks on master (hardcoded that way): https://github.com/Azure/acs-engine/blob/1036878f5ea36785410ef8f1f789c6f2d21dd1b5/parts/kubernetesmasterresources.t#L7-L10

**Comment by JoseAntonioRodriguez** [comment]
This is not only related to Kubernetes masters. We are also facing this issue when using systems such as Zookeeper or Consul where 3 fault domains would be more convenient to guarantee HA and quorum. Could that setting be configurable instead of hardcoded?

**Comment by palmerabollo** [comment]
Agree. With acs-engine it's not possible to deploy any quorum-based with high-availability guarantees. They require more than 2 fault domains. It's a big issue IMO.

**Comment by jackfrancis** [comment]
The way we want to do this is to expose a manual override, and then to document to users which regions will support 3 FDs w/ managed disk.
