### ISSUE TITLE
docker hub with Kubernetes

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/acs-engine#1518]
**Is this a request for help?**:
Help
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Seeking help on deployment to ACS
---

**What version of acs-engine?**:
What ever is hosted in Azure
---

Hi,
I have pushed a couple  of images to docker hub. From there I want to pull the image and user it in ACS without using Azure container registry. So is it possible to do that are should I mandatorily push my images to Azure container registry.

**Comment by DonMartin76** [comment]
If you don't specify a registry on your image, e.g. just say `venkateshsrini/yourimage:tag` (or whatever name and tag you gave your image), the cluster should automatically pull from Docker Hub.

Only if you specify a registry, you will also need a `imagePullSecret` in your Kubernetes Pod specificiation (e.g. in your `deployment.yaml`), or, if you're using an ACR inside the same resource group, you don't even need that.

**Comment by VenkateshSrini** [comment]
@DonMartin76 ,
Thanks for your reply. But how will it know my docker credential. I guess I should do a docker login before this step. I'm I right

**Comment by jackfrancis** [comment]
@VenkateshSrini to pull the image you don't need credentials. I'm going to close because I don't see anything actionable for acs-engine, please re-open with a note of what additional feature you'd like to see if I'm wrong!
