### ISSUE TITLE
Add v1.8 kubectl to circleci container

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1528]
I wonder if the kubernetes 1.8 tests are failing because they are using the v1.7 client to connect to the v1.8 cluster. In any event, it would be nice to upgrade to 1.8 and see if they still work for 1.6 and 1.7 tests (in which case I'd say we just want to upgrade to the 1.8 kubectl client generally)

**Comment by jackfrancis** [comment]
@jchauncey a low priority TODO item for the next couple weeks

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
