### ISSUE TITLE
Kubernetes dnsmasq vulnerability patch, e.g. 1.7.7

### ISSUE THREAD

**Issue by DonMartin76** [Azure/acs-engine#1531]
**Is this a request for help?**:

Yes.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue.

---

**What version of acs-engine?**:

Latest.

---

See https://groups.google.com/forum/#!topic/kubernetes-dev/QWIzhD3JhhE

There is a vulnerability in the dnsmasq component used in Kubernetes. I suppose this is an issue with cluster created with `acs-engine` in versions prior to the ones announced above as well.

Will there be a 0.7.1 version with the new and fixed Kubernetes versions?

**Comment by jackfrancis** [comment]
Fix is in master as of yesterday:

https://github.com/Azure/acs-engine/commit/7961efabf7513e68852205f61f5ecbf2704390b8

As we're getting close to the next interval in our two week target cadence, we're planning on folding these into the `v0.8.0` release.

Thanks!
