### ISSUE TITLE
Single master kubernetes cluster fails to upgrade if tries to drain agents.

### ISSUE THREAD

**Issue by JackQuincy** [Azure/acs-engine#1547]
Mostly for tracking future work
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
head, v0.8.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
On upgrade the api server was down when the agent pool was starting to be upgraded. This caused the first node in the agent pool to fail to drain. This happened in a single master cluster.

**What you expected to happen**:
upgrader to wait for the api server to be available before moving on to upgrading the agents

**How to reproduce it** (as minimally and precisely as possible):
uncomment code about draining in upgrading agents and run any upgrade command with 1 master

**Comment by jackfrancis** [comment]
@JackQuincy could you confirm that the merge of #1541 fixes this?
