### ISSUE TITLE
kubernetes throws an error: certificate signed by unknown authority from the latest acs-engine (0.80) for self signed certificate

### ISSUE THREAD

**Issue by humblesticker** [Azure/acs-engine#1554]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
0.80
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
after cluster install I issued "kubectl get nodes". It gives you "Unknown Authority" error

**What you expected to happen**:
Previous version I believe I was able to communicate without this issue

**How to reproduce it** (as minimally and precisely as possible):
Install cluster using 0.80 acs-engine with self-signed certificate and issue any kubectl command 

**Anything else we need to know**:
I didn't try properly signed certificate so I am not 100% sure "self signed" certificate is an issue here.

**Comment by jackfrancis** [comment]
We will look into this, thank you!

**Comment by jackfrancis** [comment]
@lachie83 When you get a chance this week could you build a 1.8.0 cluster using acs-engine (either master or v0.8.0 should repro), and try to verify that the user-provided self-signed cert flow is broken?
