### ISSUE TITLE
Feature Request: Mesos Support

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/acs-engine#156]
:wave: Hello

Are there any plans to add support for Mesos to Azure Container Service (ACS)? Whilst DCOS builds upon the same foundation - we find that Mesos fits our needs better over DCOS.

I'm not 100% sure where I should be requesting this - but here seems to be the most sensible place?

Presumably this would also make it possible to create ACS instances paid for via Azure Credits too? Right now a Credit Card is required - which makes testing this hard - whereas Amazon for instance offer Amazon Container Service under their free tier?

Thanks!

**Comment by colemickens** [comment]
cc: @rgardler

**Comment by rgardler** [comment]
We do not currently plan to offer Apache Mesos without the DC/OS bits. However, if you want to edit the scripts so they only install Mesos then we would consider adding it as an option within ACS Engine.

I don't follow your point about Azure Credits. ACS is not a charged for service beyond the underlying resources (VMs, Storage etc.) which are charged in exactly the same way as any other. You should be able to deploy ACS into any subscription in good standing. If this is not your experience then it's a bug.

**Comment by anhowe** [comment]
This is out of scope for ACS-Engine, closing as won't fix.
