### ISSUE TITLE
Mixed up error messages when validating DNSServiceIP and ServiceCidr

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [Azure/acs-engine#1571]
I think the error messages in those checks are mixed up:

https://github.com/Azure/acs-engine/blob/4df8a77c90c87264d93c1e285310af7d8fd287c3/pkg/api/vlabs/validate.go#L466-L471

When `DNSServiceIP` is empty it should complain about that and not about `ServiceCidr` being empty. And vice versa.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
