### ISSUE TITLE
Unable to create pvc in AzureGermanCloud

### ISSUE THREAD

**Issue by ramkumar1989** [Azure/acs-engine#1594]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**:
0.8.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.7.7

**What happened**:
Unable to create a persistent volume claim in the kubernetes cluster created in Azure Germany.

**What you expected to happen**:
The Claim should have created a Persistent Volume and map that the storage account.

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster in AzureGermanCloud and then create a persistent volume claim from the default storage class.

**Anything else we need to know**:
Event Message: 
Warning         ProvisioningFailed      Failed to provision volume with StorageClass "default": Put https://<storageaccount_name>.blob.core.windows.net/2838460267?restype=container: dial tcp: lookup <storageaccount_name>.blob.core.windows.net on 168.63.129.16:53: no such host

**Comment by vidrascup** [comment]
I have the same issue are there any updates ?

**Comment by andyzhangx** [comment]
v1.7.9 should solve this issue, just ping me if it does not work.

**Comment by andyzhangx** [comment]
I have checked v1.8.3 has fixed this issue, cherry-pick fix for this issue is https://github.com/kubernetes/kubernetes/pull/54615

@pengzhisun FYI

**Comment by vidrascup** [comment]
I've checked on v1.8.2 deployed on azure germany and is not working , still same issue.
On azure portal the volume is created but , when kube is connecting to the volume we receive this error.

Warning  ProvisioningFailed  14s (x9 over 2m)  persistentvolume-controller  Failed to provision volume with StorageClass "default": Put https://p1339261175.blob.core.windows.net/36338085?restype=container: dial tcp: lookup p1339261175.blob.core.windows.net on 168.63.129.16:53: no such host

**Comment by andyzhangx** [comment]
@vidrascup yes, v1.8.2 does not work since cherry-pick https://github.com/kubernetes/kubernetes/pull/54615 is not in 1.8.2, **v1.8.3** should work

**Comment by andyzhangx** [comment]
@amkumar1989 since v1.8.3 has fixed this issue, could you close it?
