### ISSUE TITLE
Dns problems using custom VNET

### ISSUE THREAD

**Issue by tesharp** [Azure/acs-engine#1603]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: v0.8.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:
I've tried deploying several clusters with v0.8.0, all using custom VNET and different options for networkPolicy (currently using "azure"). They all have dns problems after deployment though. I can see pods running with "kubectl get pods", and nodes show up, but if I try to attach, run og log a pod I only get error message

Error from server: Get https://k8s-master-xxxx:10250/containerLogs/kube-system/kube-apiserver-k8s-master-xxxx/kube-apiserver: dial tcp: lookup k8s-master-xxxx on 10.0.0.5:53: server misbehaving

My custom VNET is running Active Directory with its own dns servers (10.0.0.5), and the vnet has custom dns servers set. This seems to cause problems for dns lookups on linux nodes. On our other linux machines we have followed the guidelines at https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-network/virtual-networks-name-resolution-ddns.md and created a boot script that register the dns on linux nodes. (After allowing non-secure dns updates in AD DNS). 

Was considering just making this an extension to acs-engine to fix, but maybe there is a better option. Would be nice if it could be set as kubernetesConfig or something. For now I'm just adding this manually to continue testing.

**How to reproduce it** (as minimally and precisely as possible):

Deploy cluster to custom VNET with custom dns servers.

**Anything else we need to know**:

**Comment by JackQuincy** [comment]
This shouldn't be needed. What you should need to do is follow the steps [here ](https://github.com/Azure/ACS/tree/master/docs/VNET )to add the routetable in the custom vnet's subnets so that the internal kubernetes routing functions. This isn't in our custom vnet Documentation though.  I'm not sure why

**Comment by tesharp** [comment]
Using networkPolicy "azure" there is no routetable created, and not sure how that would help. I've tested this by deploying same cluster to another vnet that does not have any dns servers set on vnet. Then the /etc/resolv.conf on master has this content:

nameserver 168.63.129.16
search qddxx3nbbwnebgeeerdhuajxnf.ax.internal.cloudapp.net

In this setup everything works. Its using the internal Azure dns servers and searching correct domain. However with custom dns servers resolv.conf has these values:

nameserver 10.0.0.4
namespace 10.0.0.5
search reddog.microsoft.com

My dns servers are set to forward lookups to 168.63.129.16, but its not searching correct domain. So only way I can manage to get it to work is registering the master and nodes in my dns server. Would work if it searched the correct domain, but thats not something that can control as it is now with vnet dhcp settings.

**Comment by travisnielsen** [comment]
You can safely add DNS search suffixes on Ubuntu by setting `/etc/resolvconf/resolv.conf.d/base`. This setting survives reboots and will allow master and agent nodes to resolve each other via your internal DNS zone.

That being said, you may want to consider leaving your VNets on Azure DNS with no OS customization. If you need Pods to be able to resolve internal services, use the [DNS ConfigMap settings](http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html) instead. The reason why this is important is due to the fact that cluster upgrades work by deleting VMs and re-provisioning them with the new bits. If your deployment relies on customized OS settings, you will need to account for it as part of your upgrade process, which isn't ideal.

**Comment by tesharp** [comment]
I added the DNS search suffix, and registered it on my custom DNS server with an extension I made (https://github.com/tesharp/acs-engine/blob/master/extensions/register-dns/v1/register-dns.sh). Registering that as a pre provision extension the cluster works after deployment without any changes needed. But maybe the extension wont run again re-provisioning the machines?

Thanks for the link on DNS ConfigMap, I'll look into that. Will solve problem of pods resolving internal services at least. If extension won't work on re-provisioning I will have to reconsidering deploying to custom VNet. That would really limit usage of custom VNet in my opinion though..

**Comment by mortenlerudjordet** [comment]
I'm kind of struggling with the same problem. I'm also deploying with the azure networkPolicy and this does not create a route (and seem to not be needed).
I have a vNet connected to our onprem environment and as such has DNS to our DC added to the Azure vNet. Though when I try to deploy to this vNet it seems like both DNS and the dashboard is stuck in  ContainerCreating. On the master I can see both my onprem DC DNS server added as nameservers and a 
search reddog.microsoft.com in the /etc/resolv.conf

I've looked high and low to find some hints to how I can do anything with this. I've read about the DNS ConfigMap but unsure how I can use it with the acs-engine generation configs.
So out of desperation I'm posting here, as this seems as close to my issue as I have come.

**Comment by nakahparis** [comment]
I'm facing the same issue using "azure" network policy. Cluster is deployed but kube-dns & dashboard containers are stuck in ContainerCreating state...

**Comment by mortenlerudjordet** [comment]
I have only gotten this to work with this profile on a custom vNet with the default DNS (if setting a custom DNS, none of the system pods (DNS,Tiller and Dashboard) works as expected).
This seems to be related to what IP range the PODs are handed.

If I have a custom vNet (10.242.0.0/16). With one subnet for master (10.242.4.0/24) and one for agents (10.242.5.0/24). Using the following config gets the system pods created with an IP in the 192.168.x.x range. I'm probably not understanding how to integrate the azure vNet with the cluster. I also want to be able to reach the PODs I spinn up from inside the Azure vNet without having to expose them through the loadbalancer (on the Internet). Though not sure how to get that working.
`{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "kubernetesConfig": {        
        "networkPolicy": "calico",
		"clusterSubnet": "192.168.0.0/18",
		"serviceCidr": "192.168.64.0/18",
		"dnsServiceIP": "192.168.64.2",
		"nonMasqueradeCidr": "192.168.0.0/16"
      }
    },

    "masterProfile": {
      "count": 1,
      "dnsPrefix": "satestk8s",
      "vmSize": "Standard_D2_v2",
      "storageProfile": "ManagedDisks",
      "OSDiskSizeGB": 80,
      "ipAddressCount": 100,      
      "vnetSubnetId": "/subscriptions/<ID>/resourceGroups/satestsharedresourcesrg/providers/Microsoft.Network/virtualNetworks/SATestVnet/subnets/SATestK8sMastersSubnet",
      "firstConsecutiveStaticIP": "10.243.4.5"  
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "OSDiskSizeGB": 80,
        "storageProfile": "ManagedDisks",
        "vnetSubnetId": "/subscriptions/<ID>/resourceGroups/satestsharedresourcesrg/providers/Microsoft.Network/virtualNetworks/SATestVnet/subnets/SATestK8sAgentsSubnet",
        "availabilityProfile": "AvailabilitySet"        
      }
    ],`

**Comment by serbrech** [comment]
Hello, We met this issue today.
Deploying a cluster with version of acs-engine (0.12.1) into an existing Vnet/Subnet : 

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "kubernetesConfig": {
        "networkPolicy": "none",
        "clusterSubnet": "10.193.0.0/16"
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "DNSPREFIX",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Network/virtualNetworks/XXX/subnets/default",
      "firstConsecutiveStaticIP": "10.192.10.40",
      "vnetCidr": "10.192.10.0/25"
    },
    "agentPoolProfiles": [
      {
        "name": "defaultpool",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/XXX/resourceGroups/XXXX/providers/Microsoft.Network/virtualNetworks/XXX/subnets/default"
      },
      {
        "name": "otherpool",
        "count": 3,
        "vmSize": "Standard_F2s_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Network/virtualNetworks/XXXX/subnets/default"
      }
    ],
    "linuxProfile": {
      "adminUsername": "",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "...."
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "xxxx",
      "secret": "xxxx"
    }
  }
}
```

Resolution was to _manually_ assign the route table created on the vnet to the default subnet.
Should that happen automatically? What is the status on this issue?

Stephane

**Comment by sylus** [comment]
@tesharp I think I am having the exact same problem as you as when I ssh to my master node and check my resolv.conf I get a similar output.

Are you still having this issue on v0.12.4? If so is the register-dns.sh what you are currently leveraging to resolve? Thanks a bunch!

## Resolv.conf

```sh
cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.20.48.4
nameserver 172.20.48.5
search reddog.microsoft.com
```

## Kubectl

kubectl works for nodes + pods, but when I try to attach / port-forward I will get:  lookup on ... 172.20.48.5:53: server misbehaving

```sh
❯ kubectl get nodes                                                                                                  130 ↵
NAME                        STATUS    ROLES     AGE       VERSION
k8s-linuxpool1-30561499-0   Ready     agent     5h        v1.8.6
k8s-linuxpool1-30561499-1   Ready     agent     5h        v1.8.6
k8s-master-30561499-0       Ready     master    5h        v1.8.6
```

## Helm

```sh
❯ helm ls                                                                                                              1 ↵
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp: lookup k8s-linuxpool1-30561499-1 on 172.20.48.5:53: server misbehaving
```

**Comment by sylus** [comment]
Is there anything else I can do to help move this issue along? I have a step by step guide deploying on a custom vnet that doesn't have any problems. The moment I have a vnet with custom dns servers though the problem then arises. Will happily assist anyone with debugging this.

**Comment by tesharp** [comment]
@sylus Im still using this workaround. Tried deploying a 0.12 cluster without and it failed. Using registerdns.sh as an extension on both master and agent nodes it works fine. Havent found any other solution so far...

**Comment by eynet** [comment]
@tesharp unable to access https://github.com/tesharp/acs-engine/blob/master/extensions/register-dns/v1/register-dns.sh , Do you have another link ?

**Comment by tesharp** [comment]
@eynet Sorry, I just moved it from master to a separate branch a while ago. Forgot about that.. new link is https://github.com/tesharp/acs-engine/blob/register-dns-extension/extensions/register-dns/v1/register-dns.sh

**Comment by eynet** [comment]
@tesharp Thank you!

**Comment by yfried** [comment]
Hi,
I think kubernetes has a way to solve this:
http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html

**Comment by tesharp** [comment]
@yfried That works from inside the pods, but not from the master / nodes themselves. Problem here is that the nodes cannot resolve the master dns names, and opposite. So when nodes are trying to do a dns lookup on k8s-master-xxxx it just fails. Inside the containers / pods this would work, just not on the vm machines.

**Comment by bramvdklinkenberg** [comment]
Have the same issue with kubernetes cluster with a custom vnet created by acs-engine.

Created a cluster with the following:
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
         "networkPolicy": "azure"
      },
      "orchestratorVersion": "1.7.7"
    },
    "masterProfile": {
      "count": 3,
      "vnetCidr":"10.40.16.0/23",
      "dnsPrefix": "k8sinfoplus",
      "vnetSubnetId": "$SUBNETID",
      
      "vmSize": "Standard_D2_v2",
      "storageProfile" : "ManagedDisks",
      "firstConsecutiveStaticIP": "10.40.17.1"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "storageProfile" : "ManagedDisks",
        "vnetSubnetId": "$SUBNETID",
        
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "kubadmin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "$KEY"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "$ID",
      "secret": "$SECRET"
    }
  }
}

kubectl get nodes and get pod works fine but when using exec or helm install I get the same error "..... server misbehaving".

Is the only option to manually add the masters and agents to dns servers?

**Comment by bramvdklinkenberg** [comment]
I got it to work by adding al cluster nodes to our own (on premise) dns servers

**Comment by serbrech** [comment]
@bramvdklinkenberg this is what the register-dns extension from @tesharp does :)

**Comment by bramvdklinkenberg** [comment]
that script didn't work for me. I don't know if the script is ment for a specific distro?
next to adding the nodes to the dns servers I also had to add a configmap with a stubdomain for our domain name. only adding the nodes to the dns server wasn't enough for me to get it to work.

**Comment by serbrech** [comment]
That's right, you have 2 pieces to the puzzle. Someone correct me if I'm wrong 😄 : 
The DNS for the nodes, and the DNS used from within the pods/containers. 
- The nodes DNS lookups are fixed by the extension (registering the nodes in your private dns)
- The pods DNS lookups are handled by the configmap for kube-dns (tell k8s dns, used by your containers, to forward to your private dns)

**Comment by jackfrancis** [comment]
@tesharp We could add some post-deployment enforcement: "if user brought his/her own dnsServiceIP value then run `nsupdate` to register the nodes w/ resolver(s)".

I'd be happy to start experimenting along those lines with something resembling the script you shared.

**Comment by tesharp** [comment]
@jackfrancis Correct me if I'm wrong, but isn't the dnsServiceIP (kubernetesConfig.DNSServiceIP) the internal IP address of dns service in cluster? In this case it is more a master / node configuration and not kubernetes configuration, so maybe shouldn't be in kubernetesConfig at all?

Having it as a port-deployment step would be very nice. I could have created a PR as well, but didn't like this way (extension) of doing it and didn't know what would be best way. If it could be a setting on master / agent config maybe, like vnetDomainName.

**Comment by serbrech** [comment]
@tesharp That makes a cascading priority between cluster-wide config and pool specific config... it complicates and already busy api.
What about creating a VM profile separately, and provide a way to reference it in each pool to reuse the configuration?

**Comment by tesharp** [comment]
@serbrech So if I understand you correct it could be something like this:
```
{
  properties: {
    ...
    vmProfile: {
      "name": "vm-common",
      "domainName": "domain.local",
      "http_proxy": "http://proxy",
      "https_proxy": "http://proxy",
      "no_proxy": "local",
      "distro": "coreos"
    },
    "masterProfile": {
      "vmProfile": "vm-common"
      ...
    },
    "agentPoolProfiles": [
      {
        "vmProfile": "vm-common",
        ...
      }
    ]
    ...
  }
}
```

Just included http proxy and distro as example of what configuration could be useful for a vmProfile setting. This kind of setup would be good to me. Just don't want to have to repeat all these settings for every agent pool / master pool as they should be cluster wide.

**Comment by noose** [comment]
@tesharp I can't use your extensions:
```
Unable to GET extension resource for extension: register-dns with version v1 with filename template-link.json at URL: https://raw.githubusercontent.com/tesharp/acs-engine/register-dns-extension/extensions/register-dns/v1/template-link.json StatusCode: 404: Status: 404 Not Found
```

```
    "extensionProfiles": [
      {
        "name": "prometheus-grafana-k8s",
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
      },
      {
        "name": "register-dns",
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/tesharp/acs-engine/register-dns-extension/",
        "version": "v1",
        "script": "register-dns.sh"
      }
    ]
```

```
        "extensions": [
          { "name": "prometheus-grafana-k8s" },
          { "name": "register-dns" }
        ]
```

**Comment by sylus** [comment]
Hey sorry been following this issue and was curious if there is consensus on how to solve this.

a) The nodes DNS lookups are fixed by the extension (registering the nodes in your private dns)
b) The pods DNS lookups are handled by the configmap for kube-dns (tell k8s dns, used by your containers, to forward to your private dns)

I understand a) but am confused about what I need to do for b). Could anyone provide clear and concise steps for what they have done to solve this?

Thanks so much, greatly appreciated.

**Comment by serbrech** [comment]
@sylus Adjusting kube-dns is to allow the pods to resolve services that live outside the cluster.
pods run dns resolution through kube-dns (to allow for local resolution via service names).
If you want the kubernetes services to talk to your on-prem services, the kube-dns config map needs to be updated to forward dns resolution queries when they don't match local k8s services.

**Comment by sylus** [comment]
Ah thanks @serbrech makes sense :) was curious as everything was working for you, glad to know just outside services.

**Comment by serbrech** [comment]
@sylus about what you wrote above, I believe that's the right approach, until PR #2590 from @axier lands :)

**Comment by sylus** [comment]
This also summates my issue:

https://github.com/openshift/origin/issues/17316
