### ISSUE TITLE
scale-up instructions missing information

### ISSUE THREAD

**Issue by jalberto** [Azure/acs-engine#1615]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
0.8.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes

**What happened**:
I have a running cluster (created with acs-engine 0.7.0) with an agentpool with 3 nodes, I will like to scaleup creating a new agentpool (different VM size and attached disks).

I found this https://github.com/Azure/acs-engine/tree/master/examples/scale-up and a couple of closed issues but I cannot find which commands need to be run.

**What you expected to happen**:
a list of commands describing how to proceed

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jalberto** [comment]
Things I tried:

- `acs-engine upgrade` : as for description this is to upgrade k8s not scaleup
- `acs-engine generate` : trying to run generate in any of the files provided in `scale-up` dir throw a validation error

**Comment by jalberto** [comment]
So previous described error is related to https://github.com/Azure/acs-engine/issues/1159 but there is not a workaround

**Comment by jalberto** [comment]
using current master solves previous error with deploy, but now I get this error:

using `az group deployment create`

```
Deployment failed. Correlation ID: a10febc8-024b-4c2c-cc24-cdfe147c0355. {
  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "imageReference",
    "message": "Changing property 'imageReference' is not allowed."
  }
}
```

**Comment by CecileRobertMichon** [comment]
Hi @jalberto, is https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/scale.md this what you are looking for? You can use the following command:
`acs-engine scale --subscription-id 51ac25de-afdg-9201-d923-8d8e8e8e8e8e \
    --resource-group mycluster  --location westus2 \
    --deployment-dir _output/mycluster --new-node-count 5 \
    --node-pool agentpool1 --master-FQDN mycluster.westus2.cloudapp.azure.com
`

**Comment by jalberto** [comment]
Yes! thanks
