### ISSUE TITLE
Kubernetes Service creates NSG destination set to ANY

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#1619]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: ALL

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

When you create a service of type loadbalancer the associated nsg that's applied to the loadbalancer enables access to all destinations on that port. If that nsg is used for the VMs as well and they have public IPs they also will be accessible via the service ports

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
https://github.com/kubernetes/kubernetes/pull/54177

**Comment by anhowe** [comment]
Please confirm these test cases:

1. LB->NodeWithPod
2. LB->NodeWithoutPod->NodeWithPod
3. Internal Node->LB->NodeWithPod
4. Internal Node->LB->NodeWithoutPod->NodeWithPod
