### ISSUE TITLE
Kubernetes Service Loadbalancer not supporting sessionAffinity key

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#1622]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**:ALL 

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

When provisioning a service type loadbalancer with sessionAffinity set to Client IP the corresponding Loadbalancer doesn't have session persistent set.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
@itowlson

**Comment by itowlson** [comment]
This appears to be already working.  @colemickens added it in https://github.com/kubernetes/kubernetes/commit/8b50b83067468b6ee75fdef8194ca76b00c326ec.  I will add unit tests for it (since I already wrote them!).
