### ISSUE TITLE
Kubernetes service loadbalancer only creates loadBalancerSourceRanges

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#1623]
**Is this a request for help?**: YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: ALL

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

If you list multiple loadBalancerSourceRanges in the array the corresponding NSG rule only is created for the first.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
@itowlson

**Comment by itowlson** [comment]
This also seems to be working now.  Testing interactively I see that if I specify three loadBalancerSourceRanges in the YAML then I see three rules in the NSG, and the Source values in the rules match what I entered.  The commit implementing this feature is https://github.com/kubernetes/kubernetes/commit/610f38cb4a9e030332e23ed9ea981e9c97279678.
