### ISSUE TITLE
Doc update (Kubernetes):  Step 6: Key Management and Agent Forwarding with Windows Pageant

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/acs-engine#163]
The documentation for ssh keygen shows a screenshot of putty with port 2200, but the templates generated use port 22.  Request that step 6 documentation and screenshot be updated to reflect what template is using.

https://github.com/Azure/acs-engine/blob/master/docs/ssh.md#ssh-key-generation

**Comment by AlexGrs** [comment]
I would also add that in the deployment output of azure container service, the output says you must connect to master using 2200 port instead of 22 port.

**Comment by colemickens** [comment]
Can you show me an example @AlexGrs ? I can't see where we'd be outputting that for ACS or ACS-Engine.
