### ISSUE TITLE
Vendor path has colon which stops clone repo on windows machines

### ISSUE THREAD

**Issue by yolo3301** [Azure/acs-engine#1633]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Issue. [Path](https://github.com/Azure/acs-engine/tree/master/vendor/github.com/docker/distribution/contrib/docker-integration/generated_certs.d) has colon which stops clone the repo on windows machines.

**What version of acs-engine?**:
---
In the current source code.

**Comment by yolo3301** [comment]
@jackfrancis

**Comment by jackfrancis** [comment]
@JackQuincy How do we plan to fix this? This PR introduced the `generated_certs.d/` directories that include the `:` character.
