### ISSUE TITLE
acs-engine 0.8.0 is not working, it cannot deploy a cluster

### ISSUE THREAD

**Issue by jalberto** [Azure/acs-engine#1637]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.8.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes 1.7 & 1.8

**What happened**:
Trying to deploy a cluster definition that was working in 0.7.0 fails in 0.8.0

**What you expected to happen**:
Deploy a cluster

**How to reproduce it** (as minimally and precisely as possible):
Try to deploy a cluster with some custom options (calico & vnet)

**Anything else we need to know**:
This is the error:

```
INFO[0014] Starting ARM Deployment (k8svl-340956271). This will take some time... 
FATA[0015] resources.DeploymentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The template resource 'k8s-master-11577755-0' at line '1' and column '31828' is not valid: The language expression length limit exceeded. Limit: '24576' and actual: '24914'.. Please see https://aka.ms/arm-template-expressions for usage details.'."
```

This is a blocker

**Comment by jalberto** [comment]
probably duplicated of https://github.com/Azure/acs-engine/issues/1159 but this is a really blocker bug, I suggest a 0.8.1 release to fix this soon as possible

**Comment by justindavies** [comment]
I've also seen this issue, it looks like the customData definition within the Master node is too long.  Specifically the Calico amendment customData is pushing the variable over the ARM template length.  I'm currently testing a fix locally and will issue a PR if it works.

**Comment by jalberto** [comment]
@justindavies seems to be fixed in master, so maybe a backport to 0.8.1 is enough

**Comment by justindavies** [comment]
@jalberto , thanks for the heads up

**Comment by jackfrancis** [comment]
@jalberto Are you able to re-try using acs-engine at HEAD? We made some improvements with #1579, which landed after the 0.8.0 release.

Thanks!

**Comment by jalberto** [comment]
@jackfrancis yes, it works with current master, but current master have other issues not resolved, so not usable for now. For that reason I suggest a fix release 0.8.1

**Comment by jackfrancis** [comment]
@jalberto what other issues are in current master? We're thinking about working towards a 0.9.0 release this week

**Comment by jalberto** [comment]
I opened several issues related to current master @jackfrancis

**Comment by kahoona77** [comment]
Hi just had the same issue with 0.9.1. while trying to upgrade to k8s 1.8.2
This is the error: 

Deployment template validation failed: 'The template resource 'k8s-master-52482811-0' at line '1' and column '68547' is not valid: The language expression length limit exceeded. Limit: '24576' and actual: '24698'.. Please see https://aka.ms/arm-template-expressions for usage details.'.

**Comment by jackfrancis** [comment]
@jalberto This symptom has been addressed in Azure Resource Manager (ARM), the API that acs-engine depends upon. Could you kindly verify that you're no longer seeing errors that look like "The language expression length limit exceeded..."?

If this is still an issue, please re-open!

**Comment by jalberto** [comment]
thanks! I will check when I have th eopportunity
