### ISSUE TITLE
network options being ignored

### ISSUE THREAD

**Issue by jalberto** [Azure/acs-engine#1639]
**Is this a request for help?**:
no
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
master
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s 1.7

**What happened**:
Using this options:

KubernetesConfig:
```
        "networkPolicy": "calico"
        "clusterSubnet": "10.25.0.0/17"
        "serviceCidr": "10.25.128.0/18"
        "dnsServiceIP": "10.25.191.254"
        "nonMasqueradeCidr": "10.25.0.0/16"
```

MasterProfile:
```
      "firstConsecutiveStaticIP": "10.25.127.5",
      "vnetCidr": "10.25.0.0/16"
```

using `acs-engine generate` get this in `_output`:

azuredeploy.parameters.json
```
    "firstConsecutiveStaticIP": {
      "value": "10.240.255.5"
    },

    "masterSubnet": {
      "value": "10.240.0.0/16"
    },

    "pool01Subnet": {
      "value": "10.240.0.0/16"
    },
``` 

_output/apimodel.json
```
      "vnetCidr": "10.25.0.0/16",
      "firstConsecutiveStaticIP": "10.240.255.5",

```

**What you expected to happen**:
Every network and IP must be based on params passed

**How to reproduce it** (as minimally and precisely as possible):
use sample k8s.json and add network options to it

**Anything else we need to know**:
Notice I am not trying to use a existing VNET but configuring how the VNET created by acs-engine must be configured

**Comment by jackfrancis** [comment]
@jalberto When was this last working?

**Comment by jalberto** [comment]
first time I try this kind of configuration

**Comment by CecileRobertMichon** [comment]
Hi @jalberto, what template are you using for this deployment? Are you defining a vnetSubnetId in the masterProfile?
