### ISSUE TITLE
kubernetes-dashboard static resources are missing

### ISSUE THREAD

**Issue by ziXet** [Azure/acs-engine#1641]
**Is this an ISSUE or FEATURE REQUEST?**
ISSUE

**What version of acs-engine?**
Not sure (Azure acs stock version)

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7

**What happened**:
kubernetes-dashboard pod is running but all static resources are missing.

**What you expected to happen**:
Load kubernetes dashboard on http://localhost:8001/ui/

**How to reproduce it** (as minimally and precisely as possible):

1. Fire up a kubernetes cluster using Azure ACS (portal).
2. Run "kubectl proxy"
3. open http://localhost:8001/ui

**Anything else we need to know**:
https://s.nimbus.everhelper.me/share/1194440/neyb91k8eli19mzav641

**Comment by nakahparis** [comment]
Had the same issue. The workaround is to add a "/" into the URL after the redirection.

**Comment by ziXet** [comment]
Problem solved! thanks

**Comment by richardjortega** [comment]
For other people, adding this information as it's a K8s version and not an acs-engine issue: https://github.com/kubernetes/dashboard/wiki/FAQ#i-am-seeing-404-errors-when-trying-to-access-dashbord-dashboard-resources-can-not-be-loaded

**Comment by jackfrancis** [comment]
Thanks @richardjortega for hunting that down!
