### ISSUE TITLE
Use cloud init to mound etcd disks instead of using bash script

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/acs-engine#1643]
**Is this a request for help?**:
NO
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
0.8.0
---

PR #661 added a temporary fix for mounting disks until issue https://bugs.launchpad.net/cloud-init/+bug/1692093 was resolved. The issue has now been resolved in the latest Ubuntu image. PR #1521 updated the Ubuntu image in acs-engine. PR #661 should be reverted to switch back to using cloud-init.

Here are the steps to make sure the issue is still fixed after reverting the changes introduced in PR #661:

1.	Setup a simple service in Kubernetes
2.	Reboot the master
3.	Verify you still have the service

Repeat with 1 and 3 master solutions.  If etcd does not get reformatted and you still see the service, then this is working.

**Comment by jchauncey** [comment]
@CecileRobertMichon can we close this?

**Comment by CecileRobertMichon** [comment]
@jchauncey not sure. I think this still need to be done eventually.

**Comment by aheumaier** [comment]
https://github.com/Azure/acs-engine/pull/2774 fixes this issue
