### ISSUE TITLE
Windows agent nodes on Windows-only or Hybrid cluster do not work

### ISSUE THREAD

**Issue by pdeligia** [Azure/acs-engine#1647]
**Is this a request for help?**:
YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
1.8.0 (but have also tried 1.7.0 and earlier)
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes (1.8 and also tried 1.7)

**What happened**:
Windows agent nodes are not working on a Windows-only or Hybrid cluster. I followed the instructions (e.g. from [here](https://hackernoon.com/kubernetes-adventures-on-azure-part-3-acs-engine-hybrid-cluster-bc453c13b451) and [here](https://thorsten-hans.com/hybrid-kubernetes-cluster-on-azure-container-services-ed6f11bf3cb2)) to setup an example Hybrid cluster that runs an IIS service, but it fails.

When I get the description of a Windows node, I am getting the following:
```
  Type     Reason                   Age                 From                   Message
  ----     ------                   ----                ----                   -------
  Normal   NodeHasSufficientMemory  30m (x30 over 33m)  kubelet, 36331acs9010  Node 36331acs9010 status is now: NodeHasSufficientDisk
  Normal   Starting                 26m                 kubelet, 36331acs9010  Starting kubelet.
  Normal   NodeHasSufficientDisk    26m                 kubelet, 36331acs9010  Node 36331acs9010 status is now: NodeHasSufficientDisk
  Warning  InvalidDiskCapacity      1m (x6 over 26m)    kubelet, 36331acs9010  invalid capacity 0 on device "" at mount point ""
  Warning  ImageGCFailed            1m (x5 over 21m)    kubelet, 36331acs9010  invalid capacity 0 on device "" at mount point ""
```
And after creating a new pod I am getting the following (via `kubectl logs POD_NAME`):
```
ERROR ( message:Cannot find requested collection element. )
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
ERROR ( message:Cannot find requested collection element. )
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
ERROR ( message:Cannot find requested collection element. )
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
ERROR ( message:Cannot find requested collection element. )
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
ERROR ( message:Cannot find requested collection element. )
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
ERROR ( message:Cannot find requested collection element. )
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
ERROR ( message:Cannot find requested collection element. )
```

and the IIS service (from the examples in the links above) fails to deploy.

I have managed to successfully deploy a Linux only GPU Kubernetes cluster, which works perfectly fine, but we need to deploy a Hybrid cluster (Windows + Linux), so this issue is a blocker for us.

**What you expected to happen**:
I would expect the Windows agent nodes to work normally, and to be able to successfully deploy jobs/pods/services.

**How to reproduce it** (as minimally and precisely as possible):
I am using the following cluster configuration:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.7"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool1",
        "count": 2,
        "vmSize": "Standard_NC6",
        "availabilityProfile": "AvailabilitySet"
      },
      {
        "name": "windowspool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      }
    ],
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": ""
    },
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

and deploy via acs-engine.

**Anything else we need to know**:

**Comment by jchauncey** [comment]
@pdeligia can you try deploying the template `examples/windows/kubernetes-hybrid.json`?

**Comment by fengli858** [comment]
Kubernetes 1.7.10
Windows and Linux Hybrid cluster.
The  Windows agent does not work. it can start windows images.
Error message: Error syncing pod
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile":  {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.7"
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "Fengk8stest2",
            "vmSize": "Standard_D3_v2",
            "OSDiskSizeGB": 200
         },
        "agentPoolProfiles": [
            {
                "name": "agentpool1",
                "count": 2,
                "vmSize": "Standard_D3_v2", 
                "OSDiskSizeGB": 300,
                "storageProfile" : "ManagedDisks",
                "diskSizesGB": [1020],
                "availabilityProfile": "AvailabilitySet",       
                "osType": "Windows"
            },
            {
                "name": "agentpool2",
                "count": 2,
                "vmSize": "Standard_D3_v2",
                "OSDiskSizeGB": 200,
                "storageProfile" : "ManagedDisks",
                "diskSizesGB": [640],
                "availabilityProfile": "AvailabilitySet"
            }
        ],
        "windowsProfile": { 
            "adminUsername": "azureuser", 
            "adminPassword": "xxxxxxxxx" 
        }, 
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": { "publicKeys": [ { "keyData": "" } ] }
        },
        "servicePrincipalProfile": { 
            "clientId": "", 
            "secret": "" 
        } 
    }
}

**Comment by pdeligia** [comment]
@jchauncey apologies for the delayed response. I am able to run pods on Windows nodes now.

**Comment by fengli858** [comment]
Great! How did you fix your issue? Could you share your template? thanks!

**Comment by fengli858** [comment]
I may have the same issue with 0.9.3
node description:
Type     Reason               Age               From                   Message
  ----     ------               ----              ----                   -------
  Warning  InvalidDiskCapacity  2m (x23 over 1h)  kubelet, 13242k8s9001  invalid capacity 0 on device "" at mount point ""
  Warning  ImageGCFailed        2m (x22 over 1h)  kubelet, 13242k8s9001  invalid capacity 0 on device "" at mount point ""

**Comment by jchauncey** [comment]
how much disk space is on the node that is producing that error?

**Comment by fengli858** [comment]
acs-engine 0.9.3
I got the same error for Kubernetes 1.8.2 and 1.7.10.
(I have another Kubernetes cluster (using 0.8.0), Hybrid, works fine!)
On Windows-Pool
OS DiskSizeGB = 300
diskSizeGB = 1020.
Thanks!
(I am about to try the example you point out a few days ago, examples/windows/kubernetes-hybrid.json)

"agentPoolProfiles": [
 {
 "name": "agentpool1",
 "count": 2,
 "vmSize": "Standard_D3_v2",
 "OSDiskSizeGB": 300,
 "storageProfile" : "ManagedDisks",
 "diskSizesGB": [1020],
 "availabilityProfile": "AvailabilitySet",
 "osType": "Windows"
 },

**Comment by fengli858** [comment]
acs-engine 0.9.3
tested the examples/windows/kubernetes-hybrid.json.
It does not work. No Data Disk for windows node.

**Comment by andyzhangx** [comment]
@fengli858 what's your error info? The warning info of windows node is a potential issue, but would not lead to pod running error. One possible issue is that from acs-engine v0.9.2, it's using a new Windows OS called 1709, you should use conatiner image tag with 1709 keyword, otherwise the container could not run on OS, below is an example:
https://github.com/andyzhangx/Demo/tree/master/windows/basic/rs3

Below are about the 1709 breaking change notes:
https://github.com/andyzhangx/Demo/tree/master/windows#note
