### ISSUE TITLE
could not init cloud provider "azure": error unmarshaling JSON: json: cannot u              nmarshal number into Go struct field Config.cloudProviderBackoff of type bool

### ISSUE THREAD

**Issue by JuneZhao** [Azure/acs-engine#1658]
**Is this a request for help?**:

---Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---Issue

**What version of acs-engine?**:

---latest

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8S

**What happened**:
When deployed using ACS-Engine with 3 master and 4 agents with custom vnet we got below error when trying to start kubelet service

Oct 21 05:39:12 k8s-master-37491860-0 docker[1678]: Error: failed to run Kubelet              : could not init cloud provider "azure": error unmarshaling JSON: json: cannot u              nmarshal number into Go struct field Config.cloudProviderBackoff of type bool

From deploy.json:
    "cloudProviderBackoff": {
      "defaultValue": "",
      "metadata": {
        "description": "Enable cloudprovider backoff?"
      },
      "type": "string"
    },

From:parameters.json:
    "cloudProviderBackoff": {
      "value": "false"
    },

After furthering reading the source code from ACS-engine:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure.go

It is defined as below:
CloudProviderBackoff bool `json:"cloudProviderBackoff" yaml:"cloudProviderBackoff"`

Not sure related or not found below
https://stackoverflow.com/questions/24480835/go-decoding-json-int-into-string
https://ethereum.stackexchange.com/questions/955/uncaught-error-could-not-decode-json-cannot-unmarshal-array-into-go-value-of

I found below template
https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/transformtestfiles/k8s_master_upgrade_template.json

Is this working?

**Comment by jchauncey** [comment]
cc @jackfrancis
