### ISSUE TITLE
godeb: no downloads available

### ISSUE THREAD

**Issue by UncleTawnos** [Azure/acs-engine#1669]
What version of acs-engine?
master at commit d11ad5b98af7041a55a11e83fbb320ae471fd017

godeb from s3 looks like having problem fetching go version. 
`
acs-engine$ ./scripts/devenv.sh
+ docker build --pull -t acs-engine .
Sending build context to Docker daemon  227.2MB
Step 1/18 : FROM buildpack-deps:xenial
xenial: Pulling from library/buildpack-deps
Digest: sha256:07d3330a162edc027a589df0ec6ac4cce91ae426f6dc490f49b3b119e9e6e8d8
Status: Image is up to date for buildpack-deps:xenial
 ---> c063789e4027
Step 2/18 : RUN apt-get update     && apt-get -y upgrade     && apt-get -y install python-pip make build-essential curl openssl vim jq gettext     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 7ef442837204
Step 3/18 : ENV GO_VERSION 1.8
 ---> Using cache
 ---> 0468e8c7c54b
Step 4/18 : RUN mkdir /tmp/godeb     && curl "https://godeb.s3.amazonaws.com/godeb-amd64.tar.gz" > /tmp/godeb/godeb.tar.gz     && (cd /tmp/godeb; tar zvxf godeb.tar.gz; ./godeb install "${GO_VERSION}")     && rm -rf /tmp/godeb
 ---> Running in 55c152feca2c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2002k  100 2002k    0     0   422k      0  0:00:04  0:00:04 --:--:--  422k
godeb
error: no downloads available at http://golang.org/dl/
`

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:
go download crashed

**What you expected to happen**:
docker running

**How to reproduce it** (as minimally and precisely as possible):
run `./scripts/devenv.sh`

**Anything else we need to know**:

looks like godeb.s3 tarball is bad

**Comment by xtophs** [comment]
same happens with v0.8.0 on Ubuntu 16.04 server

Downloading the godeb tarball manually works:
```
curl "https://godeb.s3.amazonaws.com/godeb-amd64.tar.gz" > /tmp/godeb/godeb.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2002k  100 2002k    0     0  7251k      0 --:--:-- --:--:-- --:--:-- 7254k
```

running godeb fails:
```
./godeb install 1.8
error: no downloads available at http://golang.org/dl/
```

**Comment by xtophs** [comment]
known issue with godeb: https://github.com/niemeyer/godeb/issues/31

**Comment by jchauncey** [comment]
Can you guys try this again? I think we might have fixed this issue last week.

**Comment by UncleTawnos** [comment]
yup, it's working for me now, thank you
