### ISSUE TITLE
Kubernetes 1.7.7 in ACS-Engine release v0.8.0 not worked on Azure China Cloud

### ISSUE THREAD

**Issue by pengzhisun** [Azure/acs-engine#1677]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

---

**What version of acs-engine?**:
v0.8.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.7

**What happened**:
azure-disk provider not worked on AzureChinaCloud, while provisioning a pvc resource in k8s got the following error message:

Warning  ProvisioningFailed  10s (x62 over 15m)  persistentvolume-controller  Failed to provision volume with StorageClass "default": Put https://p3345881817.blob.core.windows.net/2840965416?restype=container: dial tcp: lookup p3345881817.blob.core.windows.net on 168.63.129.16:53: no such host.

The blob storage endpoint should use the Azure China endpoints.

**What you expected to happen**:

The blob storage endpoint should use the Azure China endpoints and the pvc provision should be succeed on Azure China Cloud.

**How to reproduce it** (as minimally and precisely as possible):
1. deploy a k8s cluster via acs-engine with this guide: https://github.com/Azure/devops-sample-solution-for-azure-china/blob/master-dev/acs-engine/README.md
2. deploy pvc resource via yaml file with following setting: volume.beta.kubernetes.io/storage-class: default

**Anything else we need to know**:

It's a known issue in Kubernetes 1.7.7 and has been fixed in Kubernetes 1.7.9.

**Comment by andyzhangx** [comment]
it's not related to acs-engine, would you close it?

**Comment by pengzhisun** [comment]
Close this issue due to the latest v0.9.1 version has resolved it, the default version for k8s 1.7.* in acs-engine is 1.7.9 now.
