### ISSUE TITLE
Cannot update Kubernetes Dashboard in k8s 1.8

### ISSUE THREAD

**Issue by pradyuman** [Azure/acs-engine#1683]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.8.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

**What happened**: I deployed a cluster using acs-engine with kubernetes 1.8 and RBAC and tried to edit the image for kubernetes dashboard to 1.7.1 (gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1). I tried:
- Editing the yaml on the dashboard to use `gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1` as the image
- Setting the image via: `kubectl set image deployment/kubernetes-dashboard --namespace=kube-system kubernetes-dashboard=gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1`
- Updating the deployment via: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

The deployment would briefly update to use the new image and then roll back due to an error that I cannot find (kubectl logs --previous on the old pod returns NotFound). I know the cluster was able to pull the image because that event is successful in the logs.

**What you expected to happen**: Kubernetes Dashboard would update to 1.7.1 without any issues.

**How to reproduce it** (as minimally and precisely as possible):
I used the following config:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.8",
        "kubernetesConfig": {
          "enableRbac": true
        }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": [dnsPrefix],
      "vmSize": "Standard_D2s_v3",
      "vnetSubnetId": [id],
      "firstConsecutiveStaticIP": "10.0.10.4"
    },
    "agentPoolProfiles": [
      {
        "name": "apoold8sv3",
        "count": 3,
        "vmSize": "Standard_D8s_v3",
        "vnetSubnetId": [id],
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": [public key]
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": [appId],
      "secret": [password]
    }
  }
}
```

And then tried to run the commands above.

**Anything else we need to know**: This was a brand new cluster with no other services, deployments, or namespaces.

**Comment by feiskyer** [comment]
Also upgraded the dashboard, but it works properly. I'm simply running

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```

Could you provide related kubelet logs ( that is when upgrading dashboard ) ?

**Comment by jackfrancis** [comment]
acs-engine doesn't support these types of update to existing cluster operations, however, I hope this helps:

We recently merged to master an addition that enables more specific dashboard customization:

https://github.com/Azure/acs-engine/pull/1765

When building *new* clusters, if you want to pass in a custom dashboard image reference (e.g., `gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1`, you could decorate your `kubernetesConfig` api model config object with an `addons` array entry that looks something like this:

```
"kubernetesConfig": {
    "addons": [
        {
            "name": "kubernetes-dashboard",
            "containers": [
                {
                    "name": "kubernetes-dashboard",
                    "image": "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1"
                }
            ]
        }
    ]
}
```

Also, we're always keen to be reminded when we're not shipping the latest component version, so please continue to bug us to update our manifests to include the latest stable versions!
