### ISSUE TITLE
Cannot deploy Kubernetes cluster in AzureChinaCloud

### ISSUE THREAD

**Issue by ajhewett** [Azure/acs-engine#1701]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: v0.7.0 and v0.8.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7

**What happened**:
Using the "deploy" option of acs-engine into the AzureChinaCloud asks for reauthentication, i.e.

`time="2017-11-02T16:03:42+01:00" level=warning msg="To sign in, use a web browser to open the page https://aka.ms/deviceloginchina and enter the code XXXXXXXXX to authenticate."`

but the code cannot be recognized, i.e.
`We don't recognize this code, please enter the code again`

**What you expected to happen**:
The Kubernetes cluster is created without asking for authentication since  the user is already authenticated to the AzureChinaCloud.

**How to reproduce it** (as minimally and precisely as possible):

The acs-engine cmdline looks like (redacted):
`acs-engine.exe  deploy --api-model priv-ajh-cn-east-es5-kube.apimodel.json --azure-env AzureChinaCloud --ca-certificate-path rootCertificate --ca-private-key-path rootPrivateKey --location chinaeast --output-directory priv-ajh-cn-east-es5-kube --resource-group priv-ajh-cn-east-es5-kube --subscription-id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

The api-model looks like (redacted)
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.7"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "priv-ajh-cn-east-es5-kube",
      "vmSize": "Standard_D2_v2",
      "osDiskSizeGB": 128,
      "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "agent",
        "count": 3,
        "vmSize": "Standard_DS12_v2",
        "osDiskSizeGB": 128,
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa ..."
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "secret": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    }
  }
}
```

**Anything else we need to know**:

The user is already authenticated to azure.  Other Azure Powershell and CLI commands succeed. e.g. creating a resource group, accessing a keyvault.

The same script (with different parameters) works fine in the AzurePublicCloud and does not ask for reauthentication.

**Comment by ajhewett** [comment]
A workaround is to first use `acs-engine.exe generate` to generate the ARM templates and then deploy them using either Azure CLI or Powershell Cmdlets.

**Comment by andyzhangx** [comment]
@ajhewett you could following below guide to deploy k8s on azure china cloud:
https://github.com/Azure/devops-sample-solution-for-azure-china/blob/master-dev/acs-engine/README.md

**Comment by ajhewett** [comment]
@andyzhangx yes, that approach does work.  This issue is that the ``acs-engine deploy`` command does not  work with the AzureChinaCloud environment but does work elsewhere.

**Comment by wenboyang214** [comment]
` ./acs-engine scale --subscription-id ** \
    --resource-group wb-sa-k8s-cluster  --location chinaeast2 \
    --deployment-dir _output/wb-kubernetes --new-node-count 3 \
    --node-pool agentpool1 --master-FQDN ***.chinaeast2.cloudapp.chinacloudapi.cn \
    --azure-env AZURECHINACLOUD`` `

`WARN[0000] To sign in, use a web browser to open the page https://microsoft.com/deviceloginchina and enter the code F8TDAPQWG to authenticate.`
`We don't recognize this code, please enter the code again.`

same issue when using acs-engine scale
is there any available way to achieve scale k8s cluster in azure cloud china ?

much thanks.

**Comment by andyzhangx** [comment]
@jackfrancis @CecileRobertMichon any thoughts?

**Comment by andyzhangx** [comment]
@wenboyang214 you may run following cli command again before run "./acs-engine scale"
```
az cloud set --name AzureChinaCloud
az login -u ACCOUNT_NAME
```
Original session may be expired.

**Comment by wenboyang214** [comment]
@andyzhangx 
I have tried the way you referred but when run **./acs-engine scale**  still force to login ignoring the above two commands.

there seems 3 methods to get access:
**1.device(default: promote to login with a short code) [alway not recognize even the endpoint is deviceloginchina] (i wanna to know anyone success using device login method in Mooncake?)
2.client_secret
3.client_certificate**

i finally figure out it can be access via **client-id and client-secret** instead of promote login.

./acs-engine scale --subscription-id 57a67c5e-a*** 
--azure-env azureChinaCloud 
--client-id 54dec1cc-59b2-****************** 
--client-secret L54wgGowRMttE*********************** 
--auth-method client_secret 
--resource-group wb-sa-k8s-cluster --location chinaeast2 
--deployment-dir _output/wb-kubernetes --new-node-count 3 
--node-pool agentpool1 --master-FQDN ******.chinaeast2.cloudapp.chinacloudapi.cn

I describe my solution: https://github.com/Azure/acs-engine/issues/3789
