### ISSUE TITLE
Clarify how to scale-up master nodes.

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#1710]
I have my cluster running only 1 master node and I would like to add another.

How can I proceed to solve this ?

**Comment by jackfrancis** [comment]
Hi @hmarcelodn how did you build your cluster?

**Comment by hmarcelodn** [comment]
Hi @jackfrancis 

I used the following cluster definition file and ran acs-engine:
```

{

  "apiVersion": "vlabs",

  "properties": {

    "orchestratorProfile": {

      "orchestratorType": "Kubernetes"

    },

    "masterProfile": {

      "count": 1,

      "dnsPrefix": "",

      "vmSize": "Standard_D2_v2",

      "vnetSubnetId": "/subscriptions/SUBS_ID/resourceGroups/edge-cluster-westus/providers/Microsoft.Network/virtualNetworks/vnet-westus/subnets/k8s-masters-subnet",

      "firstConsecutiveStaticIP": "10.0.118.5"     

    },

    "agentPoolProfiles": [

      {

        "name": "agentpool1",

        "count": 3,

        "vmSize": "Standard_D2_v2",

        "availabilityProfile": "AvailabilitySet",

        "vnetSubnetId": "/subscriptions/SUBS_ID/resourceGroups/edge-cluster-westus/providers/Microsoft.Network/virtualNetworks/vnet-westus/subnets/k8s-nodes-subnet"             

      }

    ],

    "linuxProfile": {

      "adminUsername": "azureuser",

      "ssh": {

        "publicKeys": [

          {

            "keyData": ""

          }

        ]

      }

    },

    "servicePrincipalProfile": {

      "servicePrincipalClientID": "",

      "servicePrincipalClientSecret": ""

    }

  }

}

```


Can I scale this up like with agent nodes? I already scaled up several times agent nodes with acs-engine using the offset parameter. 

Thanks a lot.

**Comment by jackfrancis** [comment]
@JackQuincy suggested trying an upgrade, and passing in an api model with an increased master count. This is not really a designed user flow, but it might work.

The short story is that we don't have a supported flow for this yet!

**Comment by hmarcelodn** [comment]
I tried modifying the mastercount number. I see now 5 master nodes.

Should I add those new members manually using etcdctl so I can see then joined in the cluster?

Thanks you very much   @jackfrancis   !

**Comment by jackfrancis** [comment]
@hmarcelodn were you able to wrangle this into working status? As this is not a supported flow at the moment, I'll close this issue, we'd prefer to tackle this scenario as a first class feature when appropriate, and not formally encourage a brittle solution, if that makes sense. :)
