### ISSUE TITLE
Scaling-Master / Unable to perform initial IP allocation check

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#1716]
Hello,

I started from 3 master nodes and I increased it to 5. I am trying to add the new members to the existing cluster. My apiserver container stops working with the following error:

> 
> E1106 20:44:18.977854       1 cacher.go:274] unexpected ListAndWatch error: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: Failed to list *storage.StorageClass: client: etcd cluster is unavailable or misconfigured
> I1106 20:44:19.043807       1 logs.go:41] http: TLS handshake error from 10.0.118.9:52142: EOF
> I1106 20:44:19.072129       1 logs.go:41] http: TLS handshake error from 10.0.118.9:52148: EOF
> I1106 20:44:19.084461       1 logs.go:41] http: TLS handshake error from 10.0.118.9:52150: EOF
> F1106 20:44:19.103677       1 controller.go:128] Unable to perform initial IP allocation check: unable to refresh the service IP block: client: etcd cluster is unavailable or misconfigured

From the already working master nodes I can see the new member:

> 
> azureuser@k8s-master-50639053-0:~$ etcdctl member list
> 99673c60d6c07e0e: name=k8s-master-50639053-2 peerURLs=http://10.0.118.7:2380 clientURLs=
> b130aa7583380f88: name=k8s-master-50639053-3 peerURLs=http://10.0.118.8:2380 clientURLs=
> b4b196cc0c9fca4a: name=k8s-master-50639053-1 peerURLs=http://10.0.118.6:2380 clientURLs=
> c264b3b67880db3f: name=k8s-master-50639053-0 peerURLs=http://10.0.118.5:2380 clientURLs=
> e6e511de7d665829: name=k8s-master-50639053-4 peerURLs=http://10.0.118.9:2380 clientURLs=

 If I check the cluster health I got:

> azureuser@k8s-master-50639053-0:~$ etcdctl cluster-health
> member 99673c60d6c07e0e is healthy: got healthy result from http://10.0.118.7:2379
> member b4b196cc0c9fca4a is healthy: got healthy result from http://10.0.118.6:2379
> member c264b3b67880db3f is healthy: got healthy result from http://10.0.118.5:2379
> member fd36b7acc85d92b8 is unhealthy: got unhealthy result from http://10.0.118.9:2379
> cluster is healthy
> 

It works if I run in the new master node and stop the etcd service:

> sudo etcd --listen-client-urls http://10.0.118.9:2379 --advertise-client-urls http://10.0.118.9:2379 --listen-peer-urls http://10.0.118.9:2380

Could someone help me? 

Thanks.

**Comment by JackQuincy** [comment]
Scaling masters isn't supported. If you want to go from 3 to 5 masters, the current suggestion is to build a new cluster and move your workloads.

The issue you are hitting currently is caused because of the certs Kubernetes needs to run are provisioned at the creation of the cluster and some of them have the ip addresses of all the masters in a list in allowed endpoints/ips. To get this working you'd need to create new certs and roll all the certs for the api server/etcd clusters. I'm guessing just making a new cluster and moving your work loads would be easier. @jackfrancis do you know of any documentation to help with migrating workloads?

**Comment by hmarcelodn** [comment]
@JackQuincy thanks for your quick support on this. I understood we are out of support right now.

Let me ask you something. If I have 2 acs-engine based clusters running in different AZ. Do you believe it is possible to Federate these clusters? Or would it be insane at this momment in Azure? 

I would like to have some recommendation on this.

Thanks a lot.

**Comment by JackQuincy** [comment]
I'm not a expert about federation. @anhowe @jackfrancis any idea on the state of using acs-engine clusters in federation?

**Comment by jackfrancis** [comment]
@sauryadas Do we have any concrete answer to the federation question beyond "federation is not a recommended story at this time."?
