### ISSUE TITLE
ACS engine deploy only master kubernetes node 

### ISSUE THREAD

**Issue by ipolyzos** [Azure/acs-engine#1730]
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

Version: v0.8.0
GitCommit: 79572455
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.8

**What happened**:

Deployed the template attached below (censored). Even through successfully completed and I can see the right amount of VMs etc. When I run the `kubectl get nodes`  I can see only the master node i.e.
```
$kubectl get nodes
NAME                    STATUS    ROLES     AGE       VERSION
k8s-master-???-0   Ready     master    44m       v1.8.0
```

--------- Template ---------

> {
>   "apiVersion": "vlabs",
>   "properties": {
>     "orchestratorProfile": {
>       "orchestratorType": "Kubernetes",
>       "orchestratorRelease": "1.8",
>       "kubernetesConfig": {
>         "enableRbac": true,
>         "clusterSubnet": "10.0.0.0/22",
>         "nodeStatusUpdateFrequency": "1m",
>         "ctrlMgrNodeMonitorGracePeriod": "5m",
>         "ctrlMgrPodEvictionTimeout": "1m",
>         "ctrlMgrRouteReconciliationPeriod": "1m",
>         "cloudProviderBackoff": true,
>         "cloudProviderBackoffRetries": 6,
>         "cloudProviderBackoffJitter": 1,
>         "cloudProviderBackoffDuration": 6,
>         "cloudProviderBackoffExponent": 1.5,
>         "cloudProviderRateLimit": true,
>         "cloudProviderRateLimitQPS": 3,
>         "cloudProviderRateLimitBucket": 10
>       }
>     },
>     "masterProfile": {
>       "count": 1,
>       "dnsPrefix": "_???_",
>       "vmSize": "Standard_D2_v2",
>       "firstConsecutiveStaticIP": "10.0.0.1",
>       "storageProfile" : "ManagedDisks"
>     },
>     "agentPoolProfiles": [
>       {
>         "name": "agentpool",
>         "count": 3,
>         "vmSize": "Standard_A2_v2",
>         "storageProfile" : "ManagedDisks",
>         "availabilityProfile": "AvailabilitySet",
>         "customNodeLabels": { ... }
>       }
>     ],
>     "linuxProfile": {
>       "adminUsername": "_???_",
>       "ssh": {
>         "publicKeys": [
>           {
>             "keyData": "_ssh-rsa ...???_
>           }
>         ]
>       }
>     },
>     "servicePrincipalProfile": {
>       "clientId": "_???_",
>       "secret": "_???_"
>     }
>   }
> }

**What you expected to happen**:

When  run the `kubectl get nodes`  expected to see all master and agent nodes.

**How to reproduce it** (as minimally and precisely as possible):

Redeploy the template.

**Anything else we need to know**:

**Comment by DonMartin76** [comment]
Sounds like it might be a variant of my issue #1699? Also acs-engine 0.8.0.

**Comment by ipolyzos** [comment]
I can confirm the same behaviour with the 0.9.0 and 0.9.1 versions as well.

I would like also to note that he deployments attempted in regions: _ukwest_, _uksouth_, _eastus_, _eastus2_, _westus_, _westus2_, _canadacentral_ and _canadaeast_

**Comment by DonMartin76** [comment]
It always fails, or sometimes?

**Comment by ipolyzos** [comment]
It does not fail, it completes succesfully. I am able to connect with `kubectl` also. However when I run `kubectl get nodes` i can see only the master one and not the agents.

**Comment by DonMartin76** [comment]
Yes, sorry, I stated it wrong. What I meant was: Does it *always* behave like this, or do you get proper clusters once in a while as well? Which type of agents do you use?

**Comment by ipolyzos** [comment]
I would like to also mention that in order to make sure that is not packages version or other env related issue deployments took place using the local setup but also tried within `azuresdk/azure-cli-python:2.0.20` and `microsoft/acs-engine:latest`  docker images with no difference so far.

**Comment by ipolyzos** [comment]
unfortunately, every time has the same behaviour have not managed since the day before to get any proper cluster

**Comment by ipolyzos** [comment]
Continuing to experiment with this issue I can report that worked fine since I have completely removed the agentpool custom labels. Not sure what may trigger this, since labels were very simple but I believe worths further investigation.

**Comment by jackfrancis** [comment]
@ipolyzos Can you paste the exact customLabels object you were using?

**Comment by ipolyzos** [comment]
Seems that now is fixed, was occurring for a couple of days in **ukwest**, **uksouth** and **canadacentral**. Not able to reproduce anymore.

**Comment by jackfrancis** [comment]
Thanks for your patience, @ipolyzos please re-open if this issue reoccurs!
