### ISSUE TITLE
The default storage class is unmanaged even create a managed disk k8s cluster

### ISSUE THREAD

**Issue by pengzhisun** [Azure/acs-engine#1736]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.9.1
---

kubernetes.json settings:

"masterProfile": {                           
    "count": 1,                              
    "dnsPrefix": "k8s-master",        
    "vmSize": "Standard_D2_v2",              
    "storageProfile" : "ManagedDisks"        
},                                           
"agentPoolProfiles": [{                      
    "name": "agentpool1",                    
    "count": 3,                              
    "vmSize": "Standard_D2_v2",              
    "availabilityProfile": "AvailabilitySet",
    "storageProfile" : "ManagedDisks"        
}],                                          

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.7.9

**What happened**:

I provisioned a kubernetes cluster via acs-engine with managed disks storage profile, while trying to install a wordpress helm chart via helm install command, found the pods start failed with following error:

AttachVolume.Attach failed for volume "pvc-e0606d76-c445-11e7-a3a0-0017fa00247a" : Attach volume "spz-k8s-t3-master-dynamic-pvc-e0606d76-c445-11e7-a3a0-0017fa00247a" to instance "k8s-agentpool1-20711447-2" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Addition of a blob based disk to VM with managed disks is not supported."

It seems the root cause is the acs-engine didn't set the default storage class to managed disk, so while the helm chart installing, it will create a unmanaged storage account, then the mount pvc volume will failed.

**What you expected to happen**:

In most of cases, the helm charts should be developed by 3rd party and they commonly use the default storage class to provision pv, the acs-engine should automatically set the default storage class to managed disk if the k8s cluster is managed disk.

**How to reproduce it** (as minimally and precisely as possible):

1. Add storageProfile" : "ManagedDisks" field in the masterProfile and agentPoolProfiles sections in kubernetes.json file.
2. acs-engine generate kubernetes.json to generate the ARM template and parameter files.
3. create an ARM deployment based on generated files
4. install helm in k8s master node 
5. use helm install stable/wordpress
6. use kubectl get events to see the volume mount failed message

**Anything else we need to know**:

Some helm chart developers allow to receive the storage class settings from input configuration file, but the helm charts end user shouldn't have to solve this issue by themselves, they are deserved to avoid the differences between acs-engine provisioned k8s cluster and the "standard" k8s cluster (since the managed disk issue is Azure specific)

**Comment by andyzhangx** [comment]
@JiangtianLi acs-engine should set correct default storage class according the `storageProfile` in `agentPoolProfiles`

**Comment by sidcarter** [comment]
@pengzhisun what is the apiVersion you're using? I had this problem which went away when I used "vlabs" as the version.

**Comment by jackfrancis** [comment]
@anhowe @JackQuincy My understanding of this concern is that this won't really be possible in acs-engine. I think that the helm chart author/maintainer will always have to explicitly express desired storage in the chart, and not assume that the acs-engine built cluster will do that on helm's behalf.

**Comment by pengzhisun** [comment]
Hi @jackfrancis

Thanks for your response.

I'm not sure why helm chart developer need to explicitly set an azure storage class, from my understanding the helm charts are designed for k8s and the default storage class is designed to adapt the underlying cloud infrastructure like azure, aws and gce etc in k8s, the acs-engine provisioned k8s cluster should follow the same principle to make the cloud infrastructure transparently to helm charts.

Helm charts is a good way to embrace the k8s ecosystems and save lots of efforts for our customer, we want to figure out a best practice to leverage these assets in Azure, please feel free to correct me.

**Comment by andyzhangx** [comment]
@jackfrancis This issue is not specific to helm chart, default storage class should be set correctly, e.g.
`kind`=`managed` for managed disk cluster, 
`kind`=`Shared` for unmanaged disk cluster,
There should be logic check in acs-engine code.

**Comment by c0dingarchit3ct** [comment]
I am facing the same issue when using ACS and using helm to deploy Prometheus/Graffana, struggling with both.
Any idea how we can at least do a workaround?

**Comment by andyzhangx** [comment]
@c0dingarchit3ct here is the workaround:
For setting default storage class, you should first edit following file:
```
sudo vi /etc/kubernetes/addons/azure-storage-classes.yaml
```
Move the following config to the storage class where you want:
```
storageclass.beta.kubernetes.io/is-default-class: "true"
```
After about 2 min, the default storage class will be changed automatically.

**Comment by andyzhangx** [comment]
BTW, with acs-engine v0.10.0 or above, the default storage class will be consistent with what your k8s cluster type, e.g. the default will be managed storage class if you create a managed k8s cluster.
