### ISSUE TITLE
Add ability to specify addons

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#1748]
**Is this a request for help?**: Add ability to specify addons

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature Request

---

In some clusters we want to disable addons such as the dashboard for security purposes.  We should add an option under KubeConfig that will specify the addons that the customer wants.  If the customer doesn't choose anything, they will get the default behavior of all addons.

**Comment by dmitsh** [comment]
addressed in PR#1754

**Comment by jackfrancis** [comment]
I'd like to take a crack at this.
