### ISSUE TITLE
Kubernetes - Cluster do not start

### ISSUE THREAD

**Issue by AlexGrs** [Azure/acs-engine#175]
After deploying a cluster using acs-engine (following fix for kubernetes dashboard), the cluster do not start anymore after deploy. I'm on commit `c67286684e9cfa78d189afb392d9d2479eb92724`.

```
user@k8s-master:~$ kubectl get services --namespace=kube-system
Unable to connect to the server: dial tcp 104.40.73.116:443: i/o timeout
user@k8s-master:~$ kubectl cluster-info
Unable to connect to the server: dial tcp 104.40.73.116:443: i/o timeout
```

**Comment by colemickens** [comment]
Your service principal is likely wrong. Please check the troubleshooting steps: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md#misconfigured-service-principal

**Comment by AlexGrs** [comment]
It's strange. I tried again using the procedure https://github.com/Azure/acs-engine/blob/master/docs/serviceprincipal.md and used the client_id and secret generated. Still my new cluster still have issue.

`Jan 10 23:35:11 k8s-master-40256100-0 docker[5299]: E0110 23:35:11.849237    5750 kubelet_node_status.go:70] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/XXXXXXXX/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401`

I will try again tomorrow.

**Comment by colemickens** [comment]
Please also ensure you're in the correct subscription in the CLI and also that your azure-cli is up-to-date. Early versions had bugs that would cause the credentials to not activate for hours depending on your timezone or might not have assigned permissions to the SP by default.

**Comment by AlexGrs** [comment]
@colemickens : it was probably an outdated version of azure cli. i tried it again this morning and it works flawlessly.

**Comment by colemickens** [comment]
Great to hear!
