### ISSUE TITLE
Azure AD and rbac enabled kubernetes cluster should also create the cluster role binding

### ISSUE THREAD

**Issue by arodus** [Azure/acs-engine#1761]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
1.9.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Cluster with rbac and azure ad authentication is enabled.
Any kubectl command results in:
```
Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: {UUID} Resource value from request: {UUID}. Resource app ID: {UUID}. List of valid resources from app registration: {UUID}.
```
**What you expected to happen**:
The comand executes succesfull

**How to reproduce it** (as minimally and precisely as possible):
Deploy cluster with rbac and azure ad authentication.

**Anything else we need to know**:

The aad extension should support a parameter `adminUser`. After the cluster is created a clusterrolebinding according to https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/aad.md  should be created for the specified user.

**Comment by jackfrancis** [comment]
Hi @arodus, could you paste in (with creds scrubbed) the api model you used to deploy a new cluster? Thanks!

**Comment by arodus** [comment]
Hi @jackfrancis, sure:

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.8.2",
      "kubernetesConfig": {
        "enableRbac": true
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "ffg-acstest",
      "vmSize": "Standard_DS2_v2",
      "OSDiskSizeGB": 250
    },
    "agentPoolProfiles": [
      {
        "name": "agent",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "OSDiskSizeGB": 250,
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "clusteradmin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "keyvaultSecretRef": {
        "vaultID": "",
        "secretName": ""
      }
    },
    "aadProfile": {
      "serverAppID": "",
      "clientAppID": ""
    }
  }
}
```

**Comment by pidah** [comment]
As a wider comment, is it possible to have an option to pass custom RBAC role-binding config to acs-engine which would be placed on the master nodes in /etc/kubernetes/addons to be managed by the addon manager ?
