### ISSUE TITLE
HOWTO: Update CNI plugin

### ISSUE THREAD

**Issue by rocketraman** [Azure/acs-engine#1774]
**Is this a request for help?**: YES

---

**What version of acs-engine?**: 

```
Version: canary
GitCommit: 5b5e8bf
GitTreeState: clean
```

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.7.5

How can I update the Azure CNI plugin version in my cluster?

**Comment by jackfrancis** [comment]
We don't currently expose it as a configuration parameter. See:

https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/defaults.go#L32

Are you looking to use a newer version than `v0.91`?

**Comment by rocketraman** [comment]
@jackfrancis  No, I'm trying to upgrade the CNI plugin in a cluster that was created with an older version of acs-engine (and therefore uses an older version of the CNI plugin).

Trying to get the fix for https://github.com/Azure/azure-container-networking/issues/76.

**Comment by jackfrancis** [comment]
There is no supported way to do this. You could manually perform the steps here, using the desired CNI artifacts:

https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastercustomscript.sh#L168

@JackQuincy Just in case, I'll ask: would a scale/upgrade operation do this for @rocketraman on an existing cluster using a newer version of acs-engine. I think not, but perhaps adding more nodes to an existing cluster w/ a fresher config would give the desired azure CNI presence, after which the old nodes could be deprecated.

Either way it's rather manual!

**Comment by rocketraman** [comment]
@jackfrancis Replacing the cni binaries with the newer version seems easy enough. Do I need a reboot of each node after doing that?

**Comment by sharmasushant** [comment]
@rocketraman replacing binaries would work. Reboot should not be required. However, to reclaim the lost ip-addresses, you will need to fix the CNI state. It is easy to clean up the state completely and start from fresh. However, if there are some existing pods on the node, then the state clean up will need to accommodate for those. I think its better to create new cluster/nodes.

**Comment by rocketraman** [comment]
@sharmasushant :  If I create new nodes, migrate all workload to them, and then remove the old nodes, will the necessary CNI state cleanup happen?

@jackfrancis Is the best way to clean this up with acs-engine to create a new node pool, migrate workload to it, then scale down the old node pool to 0 nodes?

**Comment by jackfrancis** [comment]
@JackQuincy The scaling documents here suggest there is no scale-down. And @rocketraman's mention of creating a new node pool suggests there's an idiomatic workflow to do that w/ acs-engine. Is a `az group deployment create` against the same resource group with a modified api model (w/ the new agent pool) the way to do that?
