### ISSUE TITLE
Changing Master VM size in Portal does not update Master Labels

### ISSUE THREAD

**Issue by AlexZeitler** [Azure/acs-engine#1788]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
Where to get this from when running in ACS?
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.7

**What happened**:
Change Master size in Azure portal to `D1_v2 Standard`
Run `kubectl describe node k8s-master-id` returns:

```
Labels:             beta.kubernetes.io/arch=amd64
                         beta.kubernetes.io/instance-type=Standard_D2_v2
```

**What you expected to happen**:
```
Labels:             beta.kubernetes.io/arch=amd64
                         beta.kubernetes.io/instance-type=Standard_D1_v2
```

**How to reproduce it** (as minimally and precisely as possible):
Go to the Azure portal, select the k8s master VM, click Size, change size to D1_v2 Standard, click select and wait for the changes to be applied.

**Anything else we need to know**:

**Comment by amrmahdi** [comment]
I just tried resizing the master from the portal. The labels were updated. Cluster created using acs-engine 0.22 using kubernetes 1.10.8.
