### ISSUE TITLE
az acs create --master-vm-size=Standard_D1_v2 creates Standard_D2_v2 master

### ISSUE THREAD

**Issue by AlexZeitler** [Azure/acs-engine#1789]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
Unknown, where to get this in ACS?
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s

**What happened**:
Run

```
az acs create --resource-group iw --orchestrator-type=kubernetes  --name=iw-k8s --agent-count=2 --agent-vm-size=Standard_D1_v2 --master-vm-size=Standard_D1_v2  --generate-ssh-keys
```

Resulting Master VM size according to Portal: Standard D2 v2 (2 vcpus, 7 GB memory)

**What you expected to happen**:
Standard D1 v2 (1 vcpus, 3.5 GB memory)

**How to reproduce it** (as minimally and precisely as possible):
Run the command shown above, validate in Azure Portal.

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
this is an ACS issue, not acs-engine. Please open a support request if this is still relevant.
