### ISSUE TITLE
Turn on azure CNI by default

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1791]
**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

We'd like to work towards having azure CNI be the default networking implementation. Let's turn it on for a bunch of cluster scenarios IN CI and see what happens.

**Comment by jackfrancis** [comment]
So far I've only identified one breaking behavior, which is to customers who 

See this api model, which I had to enforce a`"networkPolicy": "none"` configuration onto in order to pass our E2E

https://github.com/jackfrancis/acs-engine/commit/b212e342fd04aff67b2b8411a2a7b0d8f5862673

Does it make sense that the following provisioning foo would not scaffold a working cluster when applied to a cluster with customer-specified VNETs?:

https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastercustomscript.sh#L168

@dtzar @brendandburns FYI

**Comment by edevil** [comment]
Does azure CNI support the NetworkPolicy functionality (controlling ingress and egress to containers via k8s configuration) ?

I have setup an ACS cluster with the azure CNI but NetworkPolicy objects seem to have no effect. Are we supposed to use Calico for this? Do they work well together?

**Comment by dtzar** [comment]
@edevil Azure CNI does not support NetworkPolicy today, but does help make routing easier.  Unfortunately you can't use more than one CNI network plugin: https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/#cni 
If you need the K8s NetworkPolicy, then you should use the Calico CNI plugin.

**Comment by edevil** [comment]
@dtzar thank you for the explanation!
