### ISSUE TITLE
osType: Windows for masterProfile

### ISSUE THREAD

**Issue by radu-matei** [Azure/acs-engine#1797]
**Is this a request for help?**:
Yes.
---

**What happened**:
I am trying to create a Docker Swarm Mode cluster only with Windows VMs - 1 master and 3 agents. The problem is that, [according to the docs](https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md#masterprofile), you cannot assign `osType` to `Windows` in the `masterProfile` section.

So, when trying to generate the deployment files with `acs-engine`:
```
Version: v0.9.4
GitCommit: 50709347
GitTreeState: clean
```

The result I get:

```
INFO[0000] Error returned by LoadContainerService: Unknown JSON tag osType
FATA[0000] error validating generateCmd: error parsing the api model: Unknown JSON tag osType
```
This means I cannot create a Windows-only cluster.

**How to reproduce it** (as minimally and precisely as possible):
Here's the cluster definition I'm trying to deploy:

```
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "SwarmMode"
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "",
            "vmSize": "Standard_D2_v3",
            "osType": "Windows"
        },
        "agentPoolProfiles": [
            {
                "name": "agentpublic",
                "count": 3,
                "vmSize": "Standard_D2_v3",
                "dnsPrefix": "",
                "osType": "Windows",
                "ports": [
                    80,
                    443,
                    8080
                    ]
            }
        ],
        "windowsProfile": {
            "adminUsername": "",
            "adminPassword": "",
            "imageVersion": "1709.0.20171012"
        }
    }
}
```

On top of that, apparently I cannot use the 1709 image version:

`"message": "The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:1709.0.20171012' is not available. Verify that all fields in the storage profile are correct."`

Since I can have a Docker Swarm Mode only made of Windows nodes, I expect to be able to deploy one to Azure using `acs-engine`.
Is there anything I am missing?

Thanks,
Radu M

**Comment by CecileRobertMichon** [comment]
Windows is only supported for agents at this time
