### ISSUE TITLE
Windows Agent Sometimes Lost Connection

### ISSUE THREAD

**Issue by robbiezhang** [Azure/acs-engine#1799]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
private fork from 0.3.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
We deploy clusters with 246 Windows agents. After running for some time, some Windows agents lost connection. The running period varies from several hours to several weeks. The symptoms are:
1. Node is shown as "NotReady" from the API Server
2. Unable to run CustomScriptExtension or other extensions (reset username/password, etc.), because of timeout.
3. On the Azure portal, the Extensions tab of the VM shows an warning:
Some details about the installed extensions are unavailable. This can occur when the virtual machine is stopped or the agent is unresponsive.
![image](https://user-images.githubusercontent.com/9003737/33035794-3eeb09ac-cde1-11e7-8e01-c354ceb763d5.png)
4. "Redeploy" the VM timeout.
5. In the "Boot Diagnostics" of the VM, it shows a warning icon on the network.
6. Unable to RDP

We found that replacing the Network Interface (NIC) of the VM can mitigate the issue. We just create a new NIC with dynamic IP in the VNET, and replace the current one. The node becomes Ready in a few seconds.

**What you expected to happen**:
The Windows agents should be responsive.

**How to reproduce it** (as minimally and precisely as possible):
There is no clear reproduce step. ACI team observes such issue in a few clusters.

**Anything else we need to know**:
It seems the issue repos more often recently (after 11/8/2017) - when we deploy a new cluster, 20~60 Windows agents are NotReady (out of 246). Since the nodes appear in the API server, it might means that the Windows agent setup script runs successfully and register the node to API server, but lost connection after several hours.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
