### ISSUE TITLE
acstgen: consider: replace base64/gzip trick with proper inlining in ARM template

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#18]
I'm not a huge fan of the b64+gzip trick we're using to shove the addons and customscript into the cloudconfig file.

Unfortunately, the alternative is raising the string expression limit in ARM again (not sure if they're willing). Also requires then figuring out how to do the indentation correctly into the YAML file, since the contents of the file would need to be inserted, with each line having the proper indentation.

Might not be worth the effort, if the only benefit is increasing the readability of the template outputs ever so slightly, but worth consideration.

**Comment by JonathanFraser** [comment]
I was playing around doing something similar in cloud-formation and very quickly hit the 64K userdata limit.

**Comment by colemickens** [comment]
There's three different issues I see here:

1. We shouldn't  have so many helper functions that purely serve to do string munging, base64 and gzip. We should have helper funtions injected into the template context so that someone can do `{{ .SomeField | b64 | gzip }}`. A large amount of boiler plate template functions could be purged.

2. There is an upper-bound of 64K on userdata. I don't think acs-engine is in any risk of hitting this anytime soon.

3. There is an upper-bound of 16K for string expressions in the template. I was just told that we could potentially get this bumped up higher if needed.

**Comment by JackQuincy** [comment]
doesn't look like we are actually going to do this. Closing it. Reopen if you have objections
