### ISSUE TITLE
k8s: Make kubeClusterCidr, kubeServiceCidr, kubeDnsServiceIp configurable for custom VNet

### ISSUE THREAD

**Issue by alxlchnr** [Azure/acs-engine#180]
In case you want to deploy a kubernetes cluster in an existing VNet which has a different address space than the default (10.0.0.0/8) you also want to adjust the hardcoded values for kubeClusterCidr, kubeServiceCidr, kubeDnsServiceIp. Currently the only way to achieve this is to deploy the templates and change the relevant files on the created master and agent vms. But you may still face problems.
It would be better to specify the values before template creation and get templates which fit the predefined VNet.

https://github.com/Azure/acs-engine/blob/2c4f3168751be5d3b2add8327eef8818c88daceb/parts/kubernetesmasteraddons-kube-dns-service.yaml#L11

https://github.com/Azure/acs-engine/blob/2c4f3168751be5d3b2add8327eef8818c88daceb/parts/kubernetesmastercustomdata.yml#L147

https://github.com/Azure/acs-engine/blob/2c4f3168751be5d3b2add8327eef8818c88daceb/parts/kubernetesmastervars.t#L58-L59

https://github.com/Azure/acs-engine/blob/2c4f3168751be5d3b2add8327eef8818c88daceb/pkg/acsengine/pki.go#L113

**Comment by anhowe** [comment]
Thanks for filing this.  Marking this as P2 and we will continue to watch for customer interest.  Also, please consider submitting a PR on this item.

**Comment by dcieslak19973** [comment]
I'm interested in this functionality

**Comment by siamak-haschemi** [comment]
We also need to do that, since the 10.0.0.0/16 network is already blocked by our productive environment. I also did not understand the workaround above. Maybe @alxlchnr could comment that further. I am happy with a manual solution for now ...

**Comment by siamak-haschemi** [comment]
In #303 I wrote the detailed steps to run a cluster within a custom VNET and with a different IP-subnet. Just in case someone needs that.

**Comment by alxlchnr** [comment]
#191

**Comment by alxlchnr** [comment]
Sorry for the late answer @siamak-haschemi . It seems that you already found my pull request #191 in order to find a manual solution for your problem. The Pull Request may have saved a lot of time if it was merged to master. 
With the PR it is possible to konfigure kubeClusterCidr, kubeServiceCidr, kubeDnsServiceIp in the template and all changes you have done manually will be done by acs-engine.
