### ISSUE TITLE
kubernetes version enforcement

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1800]
acs-engine needs to enforce version requirements for a variety of usage patterns:

- ACS
- AKS (managed Kubernetes)
- acs-engine CLI (vlabs)

Acceptance criteria:

- ACS & AKS
  - RP template generation should defer to acs-engine for authoritative list of supported versions
- acs-engine CLI
  - acs-engine users should have access to a separate, more fresh list of versions so that they can be on the cutting edge of the Kubernetes release cycle

**Comment by CecileRobertMichon** [comment]
Can we close this or are we not there yet?

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
