### ISSUE TITLE
acs-engine "upgrade" usage help

### ISSUE THREAD

**Issue by bq1756** [Azure/acs-engine#1809]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.8.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.7

**What happened**:

The following command results in **"FATA[0002] error loading ContainerService: OrchestratorType has unknown orchestrator:"**.  What is causing this error?  Is a file improperly formatted?
acs-engine upgrade --subscription-id "*******************" --deployment-dir "C:\src\acs-engine\_output\testkube" --resource-group "test-kube" --upgrademodel-file "C:\src\acs-engine\_output\testkube\UpgradeModel.json" --debug

C:\src\acs-engine\_output\testkube\UpgradeModel.json:
{
  "apiVersion": "vlabs",
  "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.8.4"
    }
}

C:\src\acs-engine\_output\testkube\* contains several files that were automatically generated during the "acs-engine deploy" phase.  The file apimodel.json contains "orchestratorType": "Kubernetes".

**What you expected to happen**:
Kubernetes upgraded to 1.8.4

**How to reproduce it** (as minimally and precisely as possible):
Get latest acs-engine project from github
Create kubernetes cluster by:
- acs-engine.exe generate $PathToACSEngineTemplateJson
- az account set -s "Microsoft Azure Enterprise"
- az group create --name test-kube --location eastus2
- az group deployment create --name test-kube --resource-group test-kube --template-file "C:/src/acs-engine/_output/testkube/azuredeploy.json" --parameters "C:/src/acs-engine/_output/testkube/azuredeploy.parameters.json"

Attempt kubernetes upgrade by:
- Alter \examples\k8s-upgrade.sh; change ENV_FILE to "C:\src\acs-engine\examples\k8s-upgrade\v1.7.7.json.env"
- execute acs-engine upgrade --subscription-id "*************" --deployment-dir "C:\src\acs-engine\_output\testkube" --resource-group "test-kube" --upgrademodel-file "C:\src\acs-engine\_output\testkube\UpgradeModel.json" --debug

**Anything else we need to know**:
"networkPolicy": "calico"

**Comment by jackfrancis** [comment]
@bq1756 could you try to repro w/ acs-engine v0.9.4?

**Comment by bq1756** [comment]
acs-engine v0.9.4 got me past this specific issue.  My cluster in now in the process of upgrading.

Note v0.9.4 has different, required input parameters.  The new parameters are simpler.
