### ISSUE TITLE
[dcos] zookeeper error jna missing on master nodes

### ISSUE THREAD

**Issue by julienlau** [Azure/acs-engine#182]
HI,
The jna library seems to be missing from the ubuntu image used for the master nodes.
Zookeeper seems to work, but always show the error messages below.
Would it be please possible to include jna in the ubuntu image used for DCOS ?
Thanks and regards,
JL

Fri Jan 13 12:42:33 UTC 2017 ERROR Cleanup Task: at java.lang.ClassLoader.defineClass1(Native Method) 
Fri Jan 13 12:42:33 UTC 2017 ERROR Cleanup Task: java.lang.NoClassDefFoundError: com/sun/jna/Library 
Fri Jan 13 12:42:33 UTC 2017 ERROR Cleanup Task: log4j:WARN Error during default initialization 
Fri Jan 13 12:38:04 UTC 2017 INFO ZooKeeper Server: Starting zookeeper ... STARTED 
Fri Jan 13 12:38:03 UTC 2017 ERROR ZooKeeper Server: Using config: /var/lib/dcos/exhibitor/conf/zoo.cfg 
Fri Jan 13 12:38:03 UTC 2017 ERROR ZooKeeper Server: ZooKeeper JMX enabled by default 
Fri Jan 13 12:38:03 UTC 2017 INFO Process started via: /opt/mesosphere/active/exhibitor/usr/zookeeper/bin/zkServer.sh

**Comment by colemickens** [comment]
You're saying DCOS's ZK requires side-loading other Java classes into the environment?

What Ubuntu package provides those classes? Why does this change need to be made in ACS rather than in how DCOS packages/ships ZK?

**Comment by anhowe** [comment]
Currently marking as P2 as scenario is unclear.  Please answer Cole's questions to get better clarification on this request.

**Comment by julienlau** [comment]
Good questions. I don't know what is the limit between the DCOS and ACS-ENGINE project.
However, this JNA library seems to be required by DCOS default configuration of zookeeper (at least when using more than one master).

If I go to the exhibitor API, i got every 10 miinutes the following error:
Thu Mar 02 09:50:49 UTC 2017 INFO Cleanup task completed 
Thu Mar 02 09:50:49 UTC 2017 ERROR Cleanup Task: ... 31 more 
Thu Mar 02 09:50:49 UTC 2017 ERROR Cleanup Task: at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
Thu Mar 02 09:50:49 UTC 2017 ERROR Cleanup Task: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 
Thu Mar 02 09:50:49 UTC 2017 ERROR Cleanup Task: at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
Thu Mar 02 09:50:49 UTC 2017 ERROR Cleanup Task: at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 
Thu Mar 02 09:50:49 UTC 2017 ERROR Cleanup Task: Caused by: java.lang.ClassNotFoundException: com.sun.jna.Library

If I check the zookeeper config, it seems to be linked to : 
Miscelanous/Cleanup period ms = 300000

I did try to install jna lib on master nodes by running:
sudo apt-get install -y openjdk-8-jdk libjna-java libjna-jni libjnr-unixsocket-java
and rebooting, but it did not solve my problem.

I think it may be due to the fact that DCOS is using its own non-linux-standard and is looking for libs in /opt/mesosphere and not in /usr/lib ?

It may be necessary to add the needed jna.jar and libjna.so to cloud-init scripts ?

**Comment by julienlau** [comment]
Same issue here I think:
https://dcosjira.atlassian.net/browse/DCOS-310

**Comment by anhowe** [comment]
closing since this is tracked on DCOS

**Comment by ayashjorden** [comment]
Hi all,
As I can't comment in DC/OS Jira, is there someone with permissions that can ping them?
