### ISSUE TITLE
Generated DCOS bootstrap url is invalid for 1.10

### ISSUE THREAD

**Issue by fifitrixabelle** [Azure/acs-engine#1823]
The recently added 1.10 support for dcos cluster generates a url that does not exist:

https://dcosio.azureedge.net/dcos/stable/bootstrap/e38ab2aa282077c8eb7bf103c6fff7b0f08db1a4.bootstrap.tar.xz
Returns: "The specified blob does not exist."

All other versions return a valid file so running using the 1.10 example does not install dcos
https://github.com/Azure/acs-engine/blob/master/examples/dcos-releases/dcos1.10.json

https://github.com/Azure/acs-engine/commit/8420ce6214086188c46386e5f27a059894728cc3#diff-8edb2653431a5da9ad1f4286097702a7R30

This effects master and any other branch that contains this url key - can this be updated to a valid blob url

**Comment by jackfrancis** [comment]
@julienstroheker Are you the caretaker of DC/OS images @ `https://dcosio.azureedge.net/dcos/stable/bootstrap/`? Or do you know who is?

Looks like we need to update a working tarball for `1.10`. (Assuming the artifact name is different, we'll also need to update the references in acs-engine.

Thanks!

**Comment by julienstroheker** [comment]
I am not unfortunately and I don't know who is.
It is weird this was working when we merged.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
