### ISSUE TITLE
Increase resiliency of DNS pods

### ISSUE THREAD

**Issue by aku105** [Azure/acs-engine#1827]
**Is this a request for help?**:
No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE

---

**What version of acs-engine?**:
Latest

---

DNS pod should be made more resilient since it's one of the important services in cluster on which any pod depends, if they need to communicate with other services inside or outside of cluster. Some possible improvements:
1. ~~Run DNS pods as Deployment and have a Kubernetes service on top of the pods.~~ Exists in master.
2. Configure an autoscaler on DNS pods, so that deployment can scale up under load.
3. ~~Use `addonmanager.kubernetes.io/mode: Reconcile` to allow addon manager to keep the service up.~~ Exists in master.
4. Make the DNS pods' QOS guaranteed.
5. ~~Increase verbosity of `dnsmasq` and ship the logs to stderr for analysis.~~ Exists in master.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
N/A

**What you expected to happen**:
N/A

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
N/A

**Comment by jackfrancis** [comment]
DNS is run as a deployment:

```
$ kubectl get deployments -n kube-system | grep kube-dns
kube-dns-v20           2         2         2            2           1h
```

Additionally, the `addonmanager.kubernetes.io/mode: Reconcile` label does exist.

What version of acs-engine did you use to build your cluster?

Agreed that DNS is a critical service, we'd be happy to explore ways to add resiliency.

**Comment by aku105** [comment]
Hi @jackfrancis, we have an older fork on which we had done above mentioned changes for DNS service resilience. I didn't consult the latest in acs-engine before raising the issue, so some of the points in my original ticket were incorrect/outdated.

I haven't yet created a new cluster from acs-engine master (or latest release), but, I just checked https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmasteraddons-kube-dns-deployment.yaml and the points being covered by acs-engine now are:
- DNS pods are now in a Kubernetes deployment.
- `Reconcile` label exists to allow addon manager to keep the services up.
- Increase verbosity of `dnsmasq` container

I've updated the initial description in light of above information.

**Comment by jackfrancis** [comment]
Thanks for updating! Do you have a working implementation of the following in your clusters?

- Configure an autoscaler on DNS pods, so that deployment can scale up under load.
- Make the DNS pods' QOS guaranteed.

**Comment by aku105** [comment]
Yes, we are working on creating a pull request, but might be delayed as we had not created any tests on the fork, so we'll have to write and validate the tests first. (I'm guessing a PR without tests isn't acceptable).

**Comment by jackfrancis** [comment]
We ask for unit tests for any additive functions (or changes to existing functions), but we're more permissive about higher order testing validations (i.e., E2E). I would definitely encourage a work-in-progress PR if you have something working, and we can figure things out in that thread.

Thanks again!
