### ISSUE TITLE
acs-engine "upgrade" causes service outage when master VMs are being deleted

### ISSUE THREAD

**Issue by bq1756** [Azure/acs-engine#1834]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue for now
---

**What version of acs-engine?**:
0.9.4
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.2, during upgrade to 1.8.1

**What happened**:
"acs-engine upgrade" caused a service outage each time acs-engine log output showed "Starting ARM Deployment (master...)".  The outage ends a variable amount of time afterwards... 1 - 8 minutes.
The outage happened 3 times, one time for each master node in my test cluster.
During agent upgrades/delete/create, the test service remained online, no outages.

**What you expected to happen**:
No application outages.  I anticipated a rolling, non-disruptive upgrade.

**How to reproduce it** (as minimally and precisely as possible):
Create a simple http service with 3 pods (distributed across 3 agent nodes) behind a kube service.
Hit the service public IP address every 5 seconds, recording the returned status code.
Execute acs-engien.exe upgrade with correct parameters
Record when statuscode != 200

**Anything else we need to know**:
I am using the 'calico' network provider

**Comment by bq1756** [comment]
As an experiment, I moved the kube-controller-manager to master-2 before running "acs-engine upgrade".  This action does not prevent the outages during the upgrade of each master node.

Does anybody have an opinion about why deleting and/or creating 1 of 3 master nodes would cause an outage on all pods across all agent nodes?

**Comment by dtzar** [comment]
Looks like this could be due to a bug fixed in Calico.  See "A new node controller for Kubernetes deployments clears data associated with deleted nodes from the Calico datastore, preventing conflicts that can lead to crash loops." Fixed in this release: https://github.com/projectcalico/calico/releases/tag/v2.6.3

**Comment by dtzar** [comment]
@bq1756 Can you create a cluster with an updated binary from code I have up in the calico263 branch and see if this fixes your problem?
