### ISSUE TITLE
Unable ssh into an agent node

### ISSUE THREAD

**Issue by avaranovich** [Azure/acs-engine#184]
After I ssh into a master node using FQDN, I am trying to ssh into the agent node from the master node

None of the users work
`azureuser@k8s-master-36439165-0:~$ ssh azureuser@k8s-agent-36439165-0
Permission denied (publickey).
`

`azureuser@k8s-master-36439165-0:~$ ssh root@k8s-agent-36439165-0
Permission denied (publickey).`

**Comment by khenidak** [comment]
You need to copy your private key into the master before you can ssh from the master to any of the agents. Once copied use 
ssh -i {PATH-TO-YOUR-PRIVATE-KEY} {USER}@{AGENT-NODE-NAME}

**Comment by avaranovich** [comment]
thanks that did the trick!

**Comment by AlexGrs** [comment]
Usually copying your private_key on the server is not a so great idea. Just enable Agent Forwarding and when you connect to your master with ssh, you will be able to ssh to agent without copying your keys explicitely.

`ssh -A user@master` and then on master: `ssh user@agent1`

Hope it helps !

**Comment by avaranovich** [comment]
thanks guys, in fact it still did not allow to ssh as root on agent, there seems to be check saying I should be using my user, and not root.

**Comment by colemickens** [comment]
Please post full error messages.

It may well be telling you not to SSH as root. I'm sure that's disabled.

Anyhow, this works, I've been using it all evening:

```
# on my dev machine
scp ~/.ssh/id_rsa azureuser@cluster.westus.cloudapp.azure.com:/home/azureuser
ssh azureuser@cluster.westus.cloudapp.azure.com

# on the master VM
ssh -i id_rsa 10.240.0.5

# now I'm on the node!
```

You can also use SSH Agent Forwarding, but I don't run that setup and can't advise on it right no.

**Comment by anhowe** [comment]
Agent forwarding is the recommended approach to connect to agents and is described in the docs here: https://github.com/Azure/acs-engine/blob/master/docs/ssh.md#key-management-and-agent-forwarding-with-windows-pageant.

Closing this incident.
