### ISSUE TITLE
Kubernetes v1.8.4 support

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1840]
https://github.com/kubernetes/kubernetes/releases/tag/v1.8.4

**Comment by CecileRobertMichon** [comment]
@jackfrancis looks like we missed 1.8.3, should I add it too while I'm at it?

**Comment by CecileRobertMichon** [comment]
Also 1.7.11 just got released

**Comment by jackfrancis** [comment]
Since we missed the window when v1.8.3 was latest 1.8, we don't have to retroactively add it in acs-engine.
