### ISSUE TITLE
Kubernetes/Agents: Create /etc/kubernetes/manifests directory

### ISSUE THREAD

**Issue by khenidak** [Azure/acs-engine#185]
There are too many logs like this one:

Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring

can be solved if /etc/kubernetes/manifests was created by default on all agents.

**Comment by anhowe** [comment]
Thanks @khenidak for this bug report.  I have marked it as a P0.

**Comment by anhowe** [comment]
This has now been fixed.  Closing issue.  Thanks again for the report.
