### ISSUE TITLE
Document k8s extensions vs k8s addons

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1850]
Add some clarifying documentation to distinguish between addons and extensions so we can better empower best future re-use of both of these interfaces.

**Comment by elizabethhalper** [comment]
Helpful documentation:
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md
https://kubernetes.io/docs/concepts/overview/extending/#extensions
https://kubernetes.io/docs/concepts/cluster-administration/addons/
