### ISSUE TITLE
docker daemon version out of date

### ISSUE THREAD

**Issue by amanohar** [Azure/acs-engine#1865]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
All
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
All

**What happened**:
Docker engine version in ACS Engine is pinned to:
    "dockerEngineVersion": "1.12.*"

**What you expected to happen**:
ACS Engine should be updated to newer docker engine version e.g.: 17.09.0-ce

Originally reported by @bacongobbler here: https://github.com/Azure/AKS/issues/63

**Comment by rasquill** [comment]
+1, as they say. This really torques things out of whack to have one this old.
