### ISSUE TITLE
ubuntu 16.04 agent node fails to mount NFS volume with Kubernetes v1.9.0-beta.1

### ISSUE THREAD

**Issue by karataliu** [Azure/acs-engine#1882]
Since Kubernetes v1.9.0 is pre-release now, this is to track the potential issue here.

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When testing NFS volume support, just found it would fail with k8s v1.9.0-beta.1. It could run well in v1.8.0 and v1.9.0-beta.0.

Run examples in https://github.com/kubernetes-incubator/nfs-provisioner, use 'demo/nfs-busybox-rc.yaml' as testing pod.

The final pod would succeed with mounted NFS volumes, but the mounted path are not writable in container, and also on agent node.

If call mount directly on agent node, the mounted path is writable, the key difference is 'vers=' parameter . It works with value '4.0', but fails with value '4.2' .
```
10.0.212.234:/export/pvc-36a12f4c-d989-11e7-babe-000d3a1c64c3 on /var/lib/kubelet/pods/6b5195db-d98b-11e7-babe-000d3a1c64c3/volumes/kubernetes.io~nfs/pvc-36a12f4c-d989-11e7-babe-000d3a1c64c3 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.240.0.5,local_lock=none,addr=10.0.212.234)
10.0.212.234:/export/pvc-36a12f4c-d989-11e7-babe-000d3a1c64c3 on /home/quick type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.240.0.5,local_lock=none,addr=10.0.212.234)
```

This works in v1.8.0 and v1.9.0-beta.0, but fails in v1.9.0-beta1. The most related change is hyperkube image upgraded from debian jessie to stretch.

The root cause is in acs-engine generated template, kubelet is run inside a container, thus it will call 'mount' binary in container instead of agent node. The 'nfs-common' package in the hyperkube container is newer in this case:
On agent node
```
# mount.nfs --version
mount.nfs: (linux nfs-utils 1.2.8)
```
In container
```
# mount.nfs --version
mount.nfs: (linux nfs-utils 1.3.3)
```

If copying v1.2.8 version mount.nfs to the container, and do mount manually, the resulting 'ver' would be '4.0', thus also writable.

**What you expected to happen**:
nfs mount should be supported.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a v1.9.0-beta.1 cluster, 
Follow steps in https://github.com/kubernetes-incubator/nfs-provisioner to setup a new storage class. Run demo in 'demo/nfs-busybox-rc.yaml'

**Anything else we need to know?**:

**Environment**:

**Comment by jackfrancis** [comment]
Hi @karataliu, could you help shape this PR into a workable form for building v1.9.0-beta.1 clusters?

https://github.com/Azure/acs-engine/pull/1893

Especially, check out the image references in the new version struct, does that correlate to the component versions of everything you're using to produce a working cluster?

Thanks!

**Comment by jackfrancis** [comment]
obsolete
