### ISSUE TITLE
Default ACS Kubernetes setup has broken Helm due to missing role

### ISSUE THREAD

**Issue by carlpett** [Azure/acs-engine#1892]
**Is this a request for help?**:
No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

**What version of acs-engine?**:
Whatever Azure uses internally?

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.7

**What happened**:
The pre-installed Helm cannot perform deployments which for example creates new namespaces.

To see why, create new cluster. Run `kubectl get clusterrolebindings/tiller -o yaml`. See that the binding references a `cluster-admin` role. Check `kubectl get clusterrole`, this role does not exist.

**What you expected to happen**:
The role should exist.

**How to reproduce it** (as minimally and precisely as possible):
Create new cluster with Azure portal or `az acs create`.

**Anything else we need to know**:
Let me know :)

**Comment by jackfrancis** [comment]
Just built a new cluster w/ acs-engine (wanna see if this is an issue in acs-engine):

```
$ kubectl get nodes
NAME                    STATUS         AGE       VERSION
k8s-master-37170530-0   Ready,master   8m        v1.7.9
k8s-pool1-37170530-0    Ready,agent    8m        v1.7.9
k8s-pool1-37170530-1    Ready,agent    8m        v1.7.9
k8s-pool1-37170530-2    Ready,agent    8m        v1.7.9
$ helm version
Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
$ kubectl get clusterrolebindings/tiller -o yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: 2017-12-06T21:01:24Z
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: tiller
  resourceVersion: "278"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/tiller
  uid: 9e64f9e6-dac8-11e7-bb84-000d3a146ac2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
$ kubectl get clusterrole cluster-admin
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "cluster-admin" not found
```

Does that match your experience as well?

**Comment by carlpett** [comment]
@jackfrancis Yep, that's the same!
Maybe I should also note that it is not possible to create the missing role with the client cert that is returned with `az acs kubernetes get-credentials`, because it lacks some permissions. I have to ssh to the master and `sudo kubectl create -f cluster-admin.yaml`.

**Comment by sabbour** [comment]
Any updates on this issue? Same behavior observed here.

**Comment by jackfrancis** [comment]
@slack is this something we want to slot in for AKS GA?

**Comment by cloudify** [comment]
Just has the same exact issue described here.

@sabbour I tried to provision the role as you describe but got this error:

`cluster-admin.yml`:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cluster-admin
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

```
$ kubectl --namespace kube-system apply -f cluster-admin.yml
error: error validating "cluster-admin.yml": error validating data: unknown object type schema.GroupVersionKind{Group:"rbac.authorization.k8s.io", Version:"v1", Kind:"ClusterRole"}; if you choose to ignore these errors, turn validation off with --validate=false
```

Here's my Kubernetes version:

```
$  kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jalberto** [comment]
Still an Issue in GA

```
kubectl get clusterroles --all-namespaces                                    
NAME              AGE
omsagent-reader   5d
```

**Comment by viroos** [comment]
workaround tested on AKS 1.10.3 in westeurope:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

but lack of this role is a little bit confusing at least. Especially when official Helm doc assumes it exists (https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm)

**Comment by jalberto** [comment]
AKS installed via Portal has snot RBAC enabled, the only way to have RBAC enabled is by using azure cli

This information is a bit confusing in documentation.

**Comment by plc402** [comment]
You saved my week. :-p
I was struggling to install gitlab on aks 1.10.3, thanks to your trick.
I  discovered also that it was impossible to create a rbac enabled cluster on aks by using terraform, 
it's a shame to be obliged to use az client :p

**Comment by jalberto** [comment]
you welcome, I wasted one week on it too...

**Comment by DeadZen** [comment]
3 days...

**Comment by chrissound** [comment]
Many thanks @viroos your solution solves my possible unrelated issue as well. Have a great weekend!

**Comment by sabbour** [comment]
One thing to note, it is a recommended best-practice **NOT** to grant `cluster-admin` role to Tiller. 

The better thing to do would be to create a Role/RoleBinding per namespace and initialize Tiller to use that, as per documentation here: https://github.com/helm/helm/blob/master/docs/rbac.md#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace
