### ISSUE TITLE
Prevent Creation of Public IP for Master VM when connected to Custom VNET

### ISSUE THREAD

**Issue by bigmyx** [Azure/acs-engine#1895]
---

FEATURE REQUEST

---
The Master VM is connected to a custom VNET, thus does not need to be exposed to Internet. 
According to [Slack channel conversation](https://kubernetes.slack.com/archives/C5HJXTT9Q/p1512628098000240), need to introduce a new variable that stops it from creating `Microsoft.Network/publicIPAddresses/`

**Orchestrator and version**
Kubernetes 1.8

**Comment by martell** [comment]
My suggested fix.

Add a variable to "masterProfile" in config for disabling the public ip address that stops `parts/k8s/kubernetesmastervars.t` from creating
```
    {
      "apiVersion": "[variables('apiVersionDefault')]",
      "location": "[variables('location')]",
      "name": "[variables('masterPublicIPAddressName')]",
      "properties": {
        "dnsSettings": {
          "domainNameLabel": "[variables('masterFqdnPrefix')]"
        },
        "publicIPAllocationMethod": "Dynamic"
      },
      "type": "Microsoft.Network/publicIPAddresses"
    },
```

And relevant
```
"dependsOn": [
        "[concat('Microsoft.Network/publicIPAddresses/', variables('masterPublicIPAddressName'))]"
      ]
```

**Comment by karataliu** [comment]
Related:
https://github.com/Azure/acs-engine/issues/221
https://github.com/Azure/acs-engine/pull/674

**Comment by bigmyx** [comment]
Those seem to be opened since a year ago..

**Comment by martell** [comment]
Then `enablePrivateCluster` flag was added in https://github.com/Azure/acs-engine/pull/2326 thanks to @CecileRobertMichon.
Can someone close this :)
