### ISSUE TITLE
extension to install software on k8s cluster

### ISSUE THREAD

**Issue by andyzhangx** [Azure/acs-engine#1896]
**Is this a request for help?**:
I would like to use acs-engine to set up a k8s cluster, after set up, every node should have installed specified packages, is that possible to use acs-engine extension now? 
More over, does it also support Windows node now?

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE
---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by andyzhangx** [comment]
@jackfrancis

**Comment by jackfrancis** [comment]
This is an example of a recent addition using the "extensions" acs-engine plugin vector:

https://github.com/Azure/acs-engine/pull/1837
