### ISSUE TITLE
acstgen: kubernetes: consider switching to `kubeadm`

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#19]
Filing this for ongoing and future discussion/consideration.

This could dramatically reduce the amount of code we maintain to deploy Kubernetes.

Advantages:
- removing 90+% of the yaml we have in the repo for Kubernetes (cloud-config, certs, etc)
- not having to worry about drift between upstream addons and our addon yamls

Disadvantages:
- no HA option in kubeadm (if it even matters)
- no easy way to get a `kubeconfig` out (yet)
- unclear which addons are deployed

**Comment by colemickens** [comment]
Something else we should consider, probably should still just follow `kubeadm` but they may adopt this: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-rootfs-distribution.md

also, removing myself since I'm clearly not looking at `kubeadm` right now.

**Comment by anhowe** [comment]
closing old issue

**Comment by colemickens** [comment]
Hm... could we maybe have a "backlog" tag and keep these sorts of things open? This is really something we should do eventually. Or else is there somewhere else we're keeping track of these sorts of things?
