### ISSUE TITLE
Documentation: how to enable custom firewall rules for Kubernetes PODs.

### ISSUE THREAD

**Issue by avaranovich** [Azure/acs-engine#190]
I am running a POD, from which I need to make a connection to FTP server.

Simple test from the running container

```
curl -v ftp://ftp.host.com --user xxx:yyy
*   Trying 81.xxx.yyy.zz...
* connect to  81.xxx.yyy.zz port 21 failed: Connection timed out
* Failed to connect to ftp.host.com port 21: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to ftp.host.com port 21: Connection timed out
```

I don't need to expose this POD as a public service, but I need to be able to access **Internet** resources. 

If I look at the consolidated security rule table, I see only a number of IP ranges are authorized for outbound

![grafik](https://cloud.githubusercontent.com/assets/963035/22059351/b86b118e-dd6c-11e6-93fc-892a9b27d821.png)

Where my 81.*.*.* is not there.

**Comment by colemickens** [comment]
I just executed the following with a cluster I have up:

```
kubectl run -i -t --restart=Never xenial-$RANDOM --image=ubuntu:xenial
```

```
root@xenial-21050:/# ftp test.talia.net
Connected to test.talia.net.
220 ProFTPD 1.3.5rc3 Server (test.talia.net) [::ffff:80.251.0.59]
Name (test.talia.net:root):
```

Seems to be working for me. Not sure about the screenshot, but I'm guessing that Azure just exposes the blocks of the IP space that are actually "the Internet" for that outbound rule. It shouldn't block any normal Internet traffic.

**Comment by avaranovich** [comment]
Once I explicitely enabled an FTP to any destination as an outbound rule in the NSG, it worked.

![grafik](https://cloud.githubusercontent.com/assets/963035/22072267/14f470aa-dda2-11e6-8e2a-258d740b5594.png)

somehow my destination was blocked by Azure default set up. Not sure how this is related to ACS, but from the regular VM it worked w/o any issues.

**Comment by colemickens** [comment]
Does the destination IP really not fall in one of the ranges already supplied by the default Outgoing Internet traffic rule?

**Comment by colemickens** [comment]
If you're willing, can you email me the IP/hostname of the target server (colemick@microsoft.com) and I can ask around to see if this is expected or not?

**Comment by colemickens** [comment]
I'm going to close this since I can't repro and no one else has ever reported related issues. Please provide additional details requested if you think there's still an issue.
