### ISSUE TITLE
Provisioned Kubernetes agent nodes don't load FlexVolume plugins (and potentially others)

### ISSUE THREAD

**Issue by technicianted** [Azure/acs-engine#1907]
**Is this a request for help?**:
No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

---

**What version of acs-engine?**:
0.10.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.2. 

**What happened**:
When deploying a [FlexVolume](https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md) plugin either manually or using a DaemonSet, agent nodes do not detect or load it.

**What you expected to happen**:
Plugin [automatically loaded](https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md#dynamic-plugin-discovery), registered and usable by pods.

**How to reproduce it** (as minimally and precisely as possible):
Try to install a FlexVolume in a cluster then use it in a pod. Mount will fail and logs will indicate:

```
Dec 10 04:52:07 k8s-agentpool0-81655688-0 docker[6976]: E1210 04:52:07.957395    7534 desired_state_of_world_populator.go:288] Failed to add volume "test" (specName: "test") for pod "dffbe49a-dd65-11e7-a11f-000d3af90848" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "test" err=no volume plugin matched
```

**Anything else we need to know**:
The problem happens because plugins path `/usr/libexec/kubernetes/kubelet-plugins/` on the agent node is not mounted inside the `kubelet` container, so `kubelet` is unaware of the plugin installation. 

I managed to fix it by adding the volume mount to the `kubelet` container as follows:

```patch
--- /etc/systemd/system/kubelet.service.org	2017-12-11 02:45:15.278764549 +0000
+++ /etc/systemd/system/kubelet.service	2017-12-10 16:04:44.170267737 +0000
@@ -30,6 +30,7 @@ ExecStart=/usr/bin/docker run \
   --volume=/etc/kubernetes/:/etc/kubernetes:ro \
   --volume=/srv/kubernetes/:/srv/kubernetes:ro $DOCKER_OPTS \
   --volume=/var/lib/waagent/ManagedIdentity-Settings:/var/lib/waagent/ManagedIdentity-Settings:ro \
+  --volume=/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins \
     ${KUBELET_IMAGE} \
       /hyperkube kubelet \
         --kubeconfig=/var/lib/kubelet/kubeconfig \
```

**Comment by andyzhangx** [comment]
Thanks for the info, I also got same issue, provide a fix for this.

**Comment by andyzhangx** [comment]
Also provide flexvolume examples here:
https://github.com/andyzhangx/Demo/blob/master/linux/flexvolume
https://github.com/andyzhangx/Demo/blob/master/windows/flexvolume
