### ISSUE TITLE
Documentation of Azure storage encryption option

### ISSUE THREAD

**Issue by weinong** [Azure/acs-engine#1910]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Documentation request

---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: all

**What happened**:
Please document the encryption options available in acs-engine. Particularly, be orchestrator specific and probably be k8s version specific as 1.7 and 1.8 may have different upstream support in PV.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
This is a representative resource declaration for ManagedDisk:

```
    {
      "apiVersion": "2016-04-30-preview",
      "location": "[variables('location')]",
      "name": "[variables('agentAvailabilitySet')]",
      "properties": {
        "managed": "true",
        "platformFaultDomainCount": "2",
        "platformUpdateDomainCount": "3"
      },
      "type": "Microsoft.Compute/availabilitySets"
    },
```

**Comment by andyzhangx** [comment]
is there any upstream work for azure disk?

**Comment by weinong** [comment]
@khenidak would be able to comment on upstream related work.

**Comment by weinong** [comment]
I did some investigation, here is my findings:

1. acs-engine k8s supports encrypted OS disks through Managed Disk
1. acs-engine k8s does not support encryption on pre-attached data disk
1. k8s PV and PVC do not support encryption

@jackfrancis @anhowe I suggest to add work item to enable 2.

**Comment by weinong** [comment]
I can create a PR to document my findings tomorrow.

**Comment by andyzhangx** [comment]
@weinong do you have the working template for # 1?

**Comment by andyzhangx** [comment]
There are two kinds of encryption on azure:
1) [Storage Service Encryption(SSE)](https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption) 
Managed disk has enabled SSE by default, there is nothing we need to do either in acs-engine or k8s upstream.
2) [Azure Disk Encryption for Windows and Linux IaaS VMs](https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption) 
User needs to set secretKeyVault and keyEncryptionKey keyVault in advance, there should be some work to do in acs-engine to enable disk encryption.
I am now doing k8s upstream work [Add PV support for Azure Disk Encryption](https://github.com/kubernetes/kubernetes/issues/57070) now for # 2

**Comment by andyzhangx** [comment]
After my investigation, I don't think there is k8s upstream work for this feature.
If you have already enabled azure disk encryption on VM, the attached empty disk would be encrypted using the same key vault by default, here are the detailed steps:
https://github.com/andyzhangx/Demo/blob/master/windows/azuredisk/disk-encryption
There should be work in acs-engine to create a k8s cluster with azure disk encryption enabled by default.
