### ISSUE TITLE
Option to disable cloud provider on kubelet

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#1917]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature Request

---

Summary: When creating large clusters that do not use PV's, it can be beneficial to reduce ARM QoS load from the Agent kubelets.  The option here would disable the cloud provider on the agent kubelets.

**Comment by jackfrancis** [comment]
We have some anecdotal success with running clusters that have cloudprovider disabled on agent kubelets only. Let's prove that out and then add the appropriate knobs.
