### ISSUE TITLE
Multizone support?

### ISSUE THREAD

**Issue by omerlh** [Azure/acs-engine#1919]
**Is this a request for help?**:

No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature Request

**What version of acs-engine?**:

```
Version: v0.10.0
GitCommit: 7f3e25c2
GitTreeState: clean
```

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes, 1.7

Kubernetes already have support for [multizone](https://kubernetes.io/docs/admin/multiple-zones/) - e.g. deploying cluster over multiple regions in Azure, for high availability. How can that be done using ACS engine?
Currently, I create 2 different clusters (in eastus and westus region), with traffic manager to spread the traffic between the clusters. This is not ideal, but working. Ideally, this would be managed by kubernetes multizone feature - which will also be more efficient on resources.

**Comment by hmarcelodn** [comment]
I experienced same issue and I did exactly the same than you @omerlh

**Comment by dstrebel** [comment]
Kubernetes multizone feature is for single region zones and not multiregion. Azure currently is in preview for Availability Zones, which also utilize VM Scale Sets. Azure VM Scale Set support is slated for [1.10](https://github.com/kubernetes/features/issues/513) . So support for K8 multizone will come sometime after that release. If you want cross region you would be looking at utilizing K8 Federation.

**Comment by xukai286** [comment]
we need this feature. thank you

**Comment by feiskyer** [comment]
We are working on upstream kubernetes for this feature. See https://github.com/kubernetes/features/issues/586.

**Comment by aheumaier** [comment]
@feiskyer Is this still valid ? or merged now ?

**Comment by feiskyer** [comment]
@aheumaier yep, k8s part has been merge now. #3453 is working on acs-engine part.

**Comment by ritazh** [comment]
Note: https://github.com/Azure/acs-engine/pull/3453 adds zones support for agents. We will add zones support for masters in a different PR.

**Comment by aluncoppack** [comment]
>We will add zones support for masters in a different PR.

@ritazh, this is fantastic to hear. Do you have a link to the master PR?

**Comment by ritazh** [comment]
@aluncoppack AZ for master PR: #3864
