### ISSUE TITLE
ACS pods not able to reach network/DNS/Internet

### ISSUE THREAD

**Issue by HorizonXP** [Azure/acs-engine#193]
I've been trying to resolve this issue all day today to no avail.

I've had a Kubernetes ACS cluster running fine for the last few days, when I ran into errors today after performing host system updates. I destroyed and recreated the cluster at least 5 times today, using the Azure CLI, acs-engine, and the portal, and all of them have the same issue. It manifests with kube-dns not coming up, and this is its log:

`kubectl logs -f --namespace=kube-system kube-dns-v19-1xsgn kubedns
I0119 07:37:48.670370       1 server.go:94] Using https://10.0.0.1:443 for kubernetes master, kubernetes API: <nil>
I0119 07:37:48.670885       1 server.go:99] v1.4.0-alpha.2.1652+c69e3d32a29cfa-dirty
I0119 07:37:48.670905       1 server.go:101] FLAG: --alsologtostderr="false"
I0119 07:37:48.670913       1 server.go:101] FLAG: --dns-port="10053"
I0119 07:37:48.670919       1 server.go:101] FLAG: --domain="cluster.local."
I0119 07:37:48.670923       1 server.go:101] FLAG: --federations=""
I0119 07:37:48.670926       1 server.go:101] FLAG: --healthz-port="8081"
I0119 07:37:48.670930       1 server.go:101] FLAG: --kube-master-url=""
I0119 07:37:48.670933       1 server.go:101] FLAG: --kubecfg-file=""
I0119 07:37:48.670939       1 server.go:101] FLAG: --log-backtrace-at=":0"
I0119 07:37:48.670948       1 server.go:101] FLAG: --log-dir=""
I0119 07:37:48.670952       1 server.go:101] FLAG: --log-flush-frequency="5s"
I0119 07:37:48.670960       1 server.go:101] FLAG: --logtostderr="true"
I0119 07:37:48.670964       1 server.go:101] FLAG: --stderrthreshold="2"
I0119 07:37:48.670967       1 server.go:101] FLAG: --v="0"
I0119 07:37:48.670974       1 server.go:101] FLAG: --version="false"
I0119 07:37:48.670979       1 server.go:101] FLAG: --vmodule=""
I0119 07:37:48.671085       1 server.go:138] Starting SkyDNS server. Listening on port:10053
I0119 07:37:48.671139       1 server.go:145] skydns: metrics enabled on : /metrics:
I0119 07:37:48.671153       1 dns.go:167] Waiting for service: default/kubernetes
I0119 07:37:48.671290       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0119 07:37:48.671305       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0119 07:37:53.803931       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:55331->168.63.129.16:53: i/o timeout"
I0119 07:37:55.804089       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:55802->168.63.129.16:53: i/o timeout"
I0119 07:37:57.804431       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:41432->168.63.129.16:53: i/o timeout"
I0119 07:38:01.810270       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:48597->168.63.129.16:53: i/o timeout"
I0119 07:38:03.810646       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:55119->168.63.129.16:53: i/o timeout"
I0119 07:38:05.810900       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:59869->168.63.129.16:53: i/o timeout"
I0119 07:38:07.811192       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:52698->168.63.129.16:53: i/o timeout"
I0119 07:38:11.821343       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:47281->168.63.129.16:53: i/o timeout"
I0119 07:38:13.821563       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:38586->168.63.129.16:53: i/o timeout"
I0119 07:38:15.821795       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:58303->168.63.129.16:53: i/o timeout"
I0119 07:38:17.822143       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:37997->168.63.129.16:53: i/o timeout"
I0119 07:38:18.671529       1 dns.go:173] Ignoring error while waiting for service default/kubernetes: Get https://10.0.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.0.0.1:443: i/o timeout. Sleeping 1s before retrying.
E0119 07:38:18.671743       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0119 07:38:18.671885       1 reflector.go:214] pkg/dns/dns.go:156: Failed to list *api.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
I0119 07:38:21.831934       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:51223->168.63.129.16:53: i/o timeout"
I0119 07:38:23.832345       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:44299->168.63.129.16:53: i/o timeout"
I0119 07:38:25.832604       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:45042->168.63.129.16:53: i/o timeout"
I0119 07:38:27.833026       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:40623->168.63.129.16:53: i/o timeout"
I0119 07:38:31.843862       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:40243->168.63.129.16:53: i/o timeout"
I0119 07:38:33.844205       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:50088->168.63.129.16:53: i/o timeout"
I0119 07:38:35.844583       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:41751->168.63.129.16:53: i/o timeout"
I0119 07:38:37.845050       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:35591->168.63.129.16:53: i/o timeout"
I0119 07:38:41.850011       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:38869->168.63.129.16:53: i/o timeout"
I0119 07:38:43.850389       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:45791->168.63.129.16:53: i/o timeout"
I0119 07:38:45.850751       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:33188->168.63.129.16:53: i/o timeout"
I0119 07:38:47.851157       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:37498->168.63.129.16:53: i/o timeout"
I0119 07:38:49.672112       1 dns.go:173] Ignoring error while waiting for service default/kubernetes: Get https://10.0.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.0.0.1:443: i/o timeout. Sleeping 1s before retrying.
E0119 07:38:49.672219       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0119 07:38:49.672309       1 reflector.go:214] pkg/dns/dns.go:156: Failed to list *api.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
I0119 07:38:51.861000       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:49297->168.63.129.16:53: i/o timeout"
I0119 07:38:53.861397       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:56355->168.63.129.16:53: i/o timeout"
I0119 07:38:55.861782       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:53945->168.63.129.16:53: i/o timeout"
I0119 07:38:57.862194       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:44628->168.63.129.16:53: i/o timeout"
I0119 07:39:01.866792       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:36977->168.63.129.16:53: i/o timeout"
`

What actually seems to be happening is that IP traffic is not being forwarding from within the pods. So the nodes can ping each other and external IPs, but the running pods cannot. Each running pod can only reach itself, or its host node. That's why in the above logs, only requests from one IP are being shown by kube-dns; those are requests coming from itself. I don't know if pods can reach/ping each other on the same host.

I'm not sure what has changed in the last day to cause this issue. I've opened a support ticket with Azure, because this is too bizarre to not be due to some configuration issue on my end. But the fact that I've been able to reproduce it consistently, despite changing methods of deployment and even using different regions, tells me that there's either something really wrong with my account, or something changed without my knowledge.

Help appreciated!

**Comment by Rurouni** [comment]
Same started happening to me today, all clusters created with `az acs create` are not working with kube-dns pods constantly crashing. Yesterday same scripts were working

**Comment by phimar** [comment]
Same for me here as well. Created a fresh ACS via the portal and the kube-dns container are crashing constantly.

**Comment by HorizonXP** [comment]
Yikes. I've pointed Azure support to this thread. Hope it can be resolved soon since it's affecting our production workload.

**Comment by AlexGrs** [comment]
Same thing here. Something is broken. All my new clusters are failing with DNS crash.

**Comment by HorizonXP** [comment]
Excerpt from Azure support:

"It was nice talking to you on the phone today.  As per our conversation, we have confirmed that our build deployment is causing the issue.  We have a fix, but the new deployment has not been pushed out yet.  We are forecasting to have the new build pushed out late this evening.  Because of the deployment process, we are not able to give you an exact time that you will be able to access the new build for your VMs located in North Central US."

**Comment by RossWilliams** [comment]
I can confirm replicating this prior to PR #196 being merged. This no longer replicates on master.

**Comment by HorizonXP** [comment]
So is the solution to redeploy using acs-engine from master?

**Comment by RossWilliams** [comment]
Sorry, you would need to wait for #196 to be merged. It has a WIP note on it though, not ready.

**Comment by colemickens** [comment]
Please see this issue for details about an ongoing issue with the Azure Container Service: [Azure/ACS #3 - Kubernetes Clusters Broken after Deployment or Unattended Upgrades](https://github.com/Azure/ACS/issues/3).

Additionally, we plan to use that repo (https://github.com/Azure/ACS) to handle these sorts of events in the future. Please consider subscribing so that you are notified in the future.

For now, I am going to close this out. If there are follow up questions, please put them on that issue so everyone can benefit from the answer in a single place.

Thanks.
