### ISSUE TITLE
ARN template for os disk encryption.

### ISSUE THREAD

**Issue by LaneEnglot** [Azure/acs-engine#1931]
**Is this a request for help?**:
Yes!!! Definitely! 
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Request
---

**What version of acs-engine?**:
v. 0.9.3 and v.0.1.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I attempted to use a power-shell script to run a deployment inside another deployment and it failed. I also tried setting up a vault with secrets and modifying the ARN template to enable disk encryption, specifying the vault is and secret... I couldn't get it to work. I reached out the MS tech team and they directed me here... 

**What you expected to happen**:

I expected the disks to encrypt themselves during the creation of the cluster and I expected that the auto scaled nodes would spin up with encrypted disks enabled.... 

**How to reproduce it** (as minimally and precisely as possible):
1. use acs engine to make the ARN template with the template above.
2. and that is as far as I have gotten... I haven't been able to successfully encrypt the disks on cluster creation...
3. and the rest is history!

**Anything else we need to know**:
k8s is not as easy as it looks...! :)

**Comment by LaneEnglot** [comment]
the acs engine template I am using...
[ac-eng-k8s.txt](https://github.com/Azure/acs-engine/files/1558834/ac-eng-k8s.txt)

**Comment by jackfrancis** [comment]
Hi @LaneEnglot, please track #747 which we're currently working through. Sorry we don't have a working solution just yet!
