### ISSUE TITLE
Kubernetes Horizontal Pod Autoscaler does not work for v1.8+ cluster

### ISSUE THREAD

**Issue by karataliu** [Azure/acs-engine#1936]
**Is this a request for help?**:
N/A

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
v0.10.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:

Follow the steps to using HPA(Horizontal Pod Autoscaler):
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

It does not work for acs-engine generated v1.8 cluster due to missing metric data. It works well with v1.7 

Error is:
```
  26m		1m		51	horizontal-pod-autoscaler	Warning		FailedGetResourceMetric		unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

Detailed log from controller-manager log:
```
E1215 05:27:31.069343       1 request.go:629] TESTINGLOG GET, https://10.255.255.5:443/apis/metrics.k8s.io/v1beta1/namespaces/e2e-tests-horizontal-pod-autoscaling-khm9m/pods?labelSelector=name%3Drc-light
E1215 05:27:31.070269       1 podmetrics.go:79] TESTINGLOG error is :"the server could not find the requested resource (get pods.metrics.k8s.io)"
```

This is due to 'metrics' changed to 'metrics.k8s.io' in v1.8:
https://github.com/kubernetes/kubernetes/pull/51653

In v1.7, the cluster depends on heapster to provide such metric information, but it is no longer supported in v1.8:
https://github.com/kubernetes/heapster/issues/1840

**What you expected to happen**:
HPA functions correctly

**How to reproduce it** (as minimally and precisely as possible):
Try
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Anything else we need to know**:

- Consider [metrics-server](https://github.com/kubernetes-incubator/metrics-server).
- Refer to [v1.8 changelog](https://github.com/kubernetes/kubernetes/blob/v1.8.5/CHANGELOG-1.8.md)
```
metrics-server is now the recommended way to provide the resource metrics API. 
```

**Comment by AceHack** [comment]
Any update?

**Comment by karataliu** [comment]
Follow-up issue: https://github.com/Azure/acs-engine/issues/2114
Fix PR: https://github.com/Azure/acs-engine/pull/2339

Verified from my side, with acs-engine v0.16.0 and k8s v1.10.1, it works well.
