### ISSUE TITLE
Accelerated Networking

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1938]
Tracking ticket for enabling accelerated networking for master/agent hosts. Official docs here:

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-create-vm-accelerated-networking

**Comment by jcdoba** [comment]
It might work but is unreliable.
I have set it up and works for a while then drops.

**Comment by kosta709** [comment]
yes, it works much slower and unstable with "acceleratedNetworkingEnabled": true than with false
I see it on launching Ceph using https://github.com/rook/rook

also looks like requests to ClusterIP service including dns and kubernetes api have a big latencies

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/pull/3011
