### ISSUE TITLE
`--master-vm-size` seems not working properly.

### ISSUE THREAD

**Issue by DanielTimLee** [Azure/acs-engine#1944]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
acs (2.0.22)
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
`--master-vm-size` seems not working properly.
It keeps uses `Standard_D2_V2`, even if options are suggested.

Azure/acs-engine#1141
As suggested here, I used 'Standard_A2_v2', but It just ignores and uses 'Standard_D2_V2'.

But the funny part is, `--agent-vm-size` works really properly.
Any idea why this works like this?

(+ I'm not sure but `ManagedDisks` are not working well too.)
(Also, Do I really must use 128GB of etcd disk for master? Is there any way to lessen this etcd disk size when I create?)

**What you expected to happen**:
Create Master VM with `Standard_A2_V2`

**How to reproduce it** (as minimally and precisely as possible):
```sh
az group create -n $GRP;
az acs create --debug --verbose \
--orchestrator-type kubernetes \
--master-vm-size Standard_A2_v2 \
-g $GRP -n $GRP --dns-prefix $GRP
```

**Anything else we need to know**:
I'm using Azure CLI v2.0

**Comment by philipedwards** [comment]
@DanielTimLee I cant help you with the bug but I can offer you the workaround that I used to modify the virtual machine type of our cluster members.

After creating the cluster using a `az acs create` command:

1. Log into the Azure Portal and navigate to Virtual Machines
2. Select one of your master nodes to navigate to the VM dashboard
3. Use the Size blade menu item on the left

From there you should be able to modify the VM type accordingly. From the Disks menu item you should be able to adjust your disk allocation, although I have not tried this.

**Comment by DanielTimLee** [comment]
Thanks for the tip!

Yeah, Actually right now I'm using it just like this.
Thanks.

**Comment by CecileRobertMichon** [comment]
Closing as this is an ACS RP issue.
