### ISSUE TITLE
acs-engine scale down returns error about a problem with certificates

### ISSUE THREAD

**Issue by arwkmd** [Azure/acs-engine#1948]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**:

* 0.10.0
* 0.11.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

* Kubernetes: 1.7
* Kubernetes: 1.8

**What happened**:

After executing in bash

```sh
acs-engine scale \
	--subscription-id $subscriptionId \
	--resource-group $resourceGroupName \
	--location $location \
	--auth-method 'client_secret' \
	--client-id $username \
	--client-secret $password \
	--deployment-dir "$armTemplateDirectory" \
	--new-node-count $agentPoolProfileCount \
	--node-pool $agentPoolProfileName \
	--master-FQDN "$dnsPrefix.$location.cloudapp.azure.com"	
```

where:

* $agentPoolProfileCount is less than current node count (it was 3 and now 2);
* client-id and client-secret are a service principal.

I get the error:

```
time="2017-12-19T11:39:57Z" level=info msg=validating...
time="2017-12-19T11:40:01Z" level=info msg="Name suffix: 87791856"
time="2017-12-19T11:40:02Z" level=error msg="Failed to drain node k8s-agentpool1-87791856-3, got error Get https://XXX.YYY.cloudapp.azure.com/api/v1/nodes/k8s-agentpool1-87791856-3: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"ca\")"
time="2017-12-19T11:40:02Z" level=error msg="Got error Node 'k8s-agentpool1-87791856-3' failed to drain with error: 'Get https://XXX.YYY.cloudapp.azure.com/api/v1/nodes/k8s-agentpool1-87791856-3: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"ca\")', while draining the nodes to be deleted"
Error: Node 'k8s-agentpool1-87791856-3' failed to drain with error: 'Get https://XXX.YYY.cloudapp.azure.com/api/v1/nodes/k8s-agentpool1-87791856-3: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")'
Usage:
  acs-engine scale [flags]
.
.
.

time="2017-12-19T11:40:02Z" level=fatal msg="Node 'k8s-agentpool1-87791856-3' failed to drain with error: 'Get https://XXX.YYY.cloudapp.azure.com/api/v1/nodes/k8s-agentpool1-87791856-3: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"ca\")'"
```

**What you expected to happen**:

Some agent virtual machines will be deleted.

**How to reproduce it** (as minimally and precisely as possible):

1. Create resource group;
1. Create virtual network and subnet;
1. Download and install Azure Container Service Engine
1. Create cluster definition file
1. Generate templates `acs-engine generate`
1. Deploy Kubernetes `az group deployment create`

Next decrement number of agent nodes and execute:

1. Generate templates `acs-engine generate`
1. Scale down `acs-engine scale`

**Anything else we need to know**:

* All code is executed in **azuresdk/azure-cli-python** docker container;
* Scaling up works perfect;
* `kubectl cluster-info` works;
* `scp -o 'StrictHostKeyChecking no'` works.

SSH key pair are generated by:

```sh
ssh-keygen \
	-t rsa \
	-b 2048 \
	-C "${adminUsername}@${dnsPrefix}" \
	-f "~/.ssh/id_rsa"
```

and read `publicSshKey=$(cat ~/.ssh/id_rsa.pub)`

It does not matter if after creating Kubernetes in Azure I scaling down or first scaling up and later scaling down.

**Comment by tamilmani1989** [comment]
Even I'm facing the same issue when I did scale down.. @jackfrancis Can you please check whether it happens in latest acs-engine?

**Comment by UncleTawnos** [comment]
@jackfrancis @JackQuincy any updates on this issue. It's stil happening with master-latest and 1.8. I will confirm tomorrow it it happens with 1.9

**Comment by arwkmd** [comment]
acs-engine in version 0.14.4 works
