### ISSUE TITLE
1.8.5 k8s Upgrade Feature

### ISSUE THREAD

**Issue by mcops** [Azure/acs-engine#1950]
**FEATURE REQUEST for acs-engine 0.12.0**

Kubernetes Release 1.8.5 support, because we do need finally the mountOption (file_mode/dir_mode) fix for azurefile volumes!

Thx
Gerald

**Comment by jackfrancis** [comment]
Thanks for the nudge, we're working on it!

**Comment by jalberto** [comment]
1.8.10 is already in 0.14.5

**Comment by jackfrancis** [comment]
@mcops please re-open if you have trouble upgrading your cluster to >= v1.8.5 in a more recent version of acs-engine.

**Comment by jalberto** [comment]
@jackfrancis can you help me with #2567 ?
