### ISSUE TITLE
Kubernetes CoreOS failed to start kubelet

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/acs-engine#1957]
**Is this a request for help?**:
YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.11.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.4

**What happened**:
Unable to connect to the kubernetes cluster with CoreOS as a distro after deployment. Kubelet can't be started because of the file system permission issue:

Dec 20 14:32:24 k8s-master-XXXXXX-0 docker[2794]: /run/torcx/bin/docker: Error response from daemon: error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins': mkdir /usr/libexec/kubernetes: read-only file system.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
``{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.8.4",
      "kubernetesConfig": {
        "networkPolicy": "azure",
        "enableRbac": true
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "yourdnsprefix",
      "vmSize": "Standard_D2_v2",
      "storageProfile" : "ManagedDisks",
      "distro": "coreos"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile" : "ManagedDisks",
        "distro": "coreos"
      }
    ],
    "linuxProfile": {
      "adminUsername": "admin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}``

**Anything else we need to know**:
Tried several times

**Comment by IvanovOleg** [comment]
I've removed the plugins volume line from the kubelet.service and it works.

**Comment by IvanovOleg** [comment]
`Dec 20 15:45:19 k8s-agentpool1-39482401-3 docker[1124]: `docker daemon` is not supported on Linux. Please run `dockerd` directly
Dec 20 15:45:19 k8s-agentpool1-39482401-3 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 20 15:45:19 k8s-agentpool1-39482401-3 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Dec 20 15:45:19 k8s-agentpool1-39482401-3 systemd[1]: docker.service: Unit entered failed state.
Dec 20 15:45:19 k8s-agentpool1-39482401-3 systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 20 15:45:20 k8s-agentpool1-39482401-3 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Dec 20 15:45:20 k8s-agentpool1-39482401-3 systemd[1]: Stopped Docker Application Container Engine.`

On agent node docker deamon doesn't start(((

**Comment by andyzhangx** [comment]
@jackfrancis does our acs-engine support coreos too? I have checked, `In CoreOS the /usr partition is read-only by design`

**Comment by mwieczorek** [comment]
@andyzhangx It was supported before #1909 :)
There's some examples: https://github.com/Azure/acs-engine/tree/master/examples/coreos
Can we change the folder from:
```
--volume=/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins
```
to
```
--volume=/etc/kubernetes/plugins:/etc/kubernetes/plugins
```
and pass it to kubelet as parameter:
```
--volume-plugin-dir=/etc/kubernetes/plugins
```
instead of using the default?

**Comment by andyzhangx** [comment]
@mwieczorek Thanks for the suggestion. Sounds like there is a trade-off if we also want to support coreos, we need to use `/etc/kubernetes/plugins` instead of standard plugin dir `/usr/libexec/kubernetes/kubelet-plugins` for all linux distros, because we use only one 
https://github.com/Azure/acs-engine/blob/master/parts/k8s/artifacts/kuberneteskubelet.service for all linux distros.
@jackfrancis @JiangtianLi  what's your opinion?

**Comment by andyzhangx** [comment]
I would like to change the default flexvolume plugin dir in Linux to `/etc/kubernetes/volumeplugins` and in Windows, the plugin dir would be `c:\k\volumeplugins`

**Comment by richardjortega** [comment]
I will try and look into this soon, I integrated CoreOS a while back but think it needs updates after Azure CNI was introduced. You can put stuff in /opt, which is what the CoreOS implementation does (puts kubelet in /opt) — I believe unless it was changed recently.

**Comment by andyzhangx** [comment]
@richardjortega, I made a PR#1991 to set flexvolume plugin dir as `/etc/kubernetes/volumeplugins` in Linux.
BTW, have anyone tried coreos examples under https://github.com/Azure/acs-engine/tree/master/examples/coreos, it never succeeded, last error was due to docker could not start up in coreos, is there any fix to acs-engine?

**Comment by richardjortega** [comment]
@andyzhangx I wrote those CoreOS examples. I haven’t tried them in about a month or two so things could’ve changed that sideaffected it.

**Comment by IvanovOleg** [comment]
@andyzhangx If you get 'docker daemon' is not supported on Linux. Please run 'dockerd' directly on the agent nodes, just copy exec_start.conf from master.
