### ISSUE TITLE
cannot get stats and metrics from kubelet on Windows in k8s v1.7 & v1.8

### ISSUE THREAD

**Issue by andyzhangx** [Azure/acs-engine#1968]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE 
---

**What version of acs-engine?**:
all
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** 
Kubernetes

**What happened**:
I have checked the code in https://github.com/Azure/kubernetes/tree/acs-v1.8.4-1/pkg/kubelet/winstats, found  that in k8s v1.7 & v1.8, we cannot get stats and metrics from kubelet on Windows, due to PR [Implement CRI stats in Docker Shim](https://github.com/kubernetes/kubernetes/pull/51152) not patched to azure/kubernetes. From k8s v1.9, it would work.
So my question is shall we patch [Implement CRI stats in Docker Shim](https://github.com/kubernetes/kubernetes/pull/51152) to azure/kubernetes to support v1.7 & v1.8? I could do this work and also testing, but I would like to know whether it's necessary to do this work.

Update:
Some other features like HPA(Horizontal Pod Autoscaling) depends on this metrics collecting feature, so if we want to enable metrics depending features on Windows in v1.7 & v1.8, we should do this patching work first.

If you want to check this feature, you could follow below guide:
https://github.com/andyzhangx/Demo/blob/master/linux/cadvisor/
https://github.com/andyzhangx/Demo/blob/master/windows/cadvisor/ (it works on Windows only from v1.9.0)

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

@JiangtianLi @jackfrancis

**Comment by JiangtianLi** [comment]
@andyzhangx Thanks for checking that. It would be good to backport to 1.7 and 1.8 at Azure/Kubernetes. Then we can bump the windows zip version up in acs-engine.

**Comment by andyzhangx** [comment]
For 1.8:
https://github.com/Azure/kubernetes/pull/29
https://github.com/Azure/kubernetes/pull/30

I will work on 1.7 next.

BTW, do you know what's https://github.com/Azure/kubernetes/tree/release-1.8/pkg/kubelet/winstats/win directory for? Is there any relationship with winstats? @JiangtianLi

**Comment by JiangtianLi** [comment]
@andyzhangx Thanks, merged. https://github.com/Azure/kubernetes/tree/release-1.8/pkg/kubelet/winstats/win is a workaround for vendoring https://github.com/lxn/win when we backported the metrics work from upstream.

**Comment by andyzhangx** [comment]
close this issue since following PRs have been merged:
Azure/kubernetes#29
Azure/kubernetes#30
1.7 will not support this feature.
