### ISSUE TITLE
Cannot scale Windows agent pool (Kubernetes Cluster)

### ISSUE THREAD

**Issue by bhope** [Azure/acs-engine#1972]
**Is this a request for help?**:
Yes

**Is this an ISSUE or FEATURE REQUEST?**
 Issue

**What version of acs-engine?**:
v0.11.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.7

**What happened**

After I deployed a Hybrid Kubernetes cluster with Windows and Linux agent pool, 
I tried to scale out the Windows agents pool using the acs-engine scale command.
After executing the command, I get the following error:

```
INFO[0000] validating...
INFO[0003] Name suffix: 25663911
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Azure/acs-engine/cmd.(*scaleCmd).run(0xc42078a000, 0xc42058cb40, 0xc420164540, 0x0, 0xc, 0x0, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:209 +0x219f
github.com/Azure/acs-engine/cmd.newScaleCmd.func1(0xc42058cb40, 0xc420164540, 0x0, 0xc, 0x0, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:64 +0x52
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc42058cb40, 0xc420164480, 0xc, 0xc, 0xc42058cb40, 0xc420164480)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4206aa6c0, 0xc42058c480, 0xc42058c240, 0xc42058c000)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4206aa6c0, 0xc420000448, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/main.go:9 +0x2f
```
This happens only when I try to scale up windows pool. If I do it for Linux, everything works perfectly fine.

**What you expected to happen**:

-- I'd expect the acs-engine to scale up windows pool perfectly as it does for Linux.

**How to reproduce it** (as minimally and precisely as possible):
There are very few steps that I really followed:
1. Use acs-engine to deploy a hybrid cluster in Azure. (Please find the .json file attached)
2. Use acs-engine scale command to scale up windows pool. Following is my command:

```acs-engine scale --subscription-id <sub_id> --resource-group <rg_name> --location eastus2 --deployment-dir <my_dir>/acs-engine/examples/windows/_output/<rg_name> --new-node-count 3 --node-pool windowspool2```

**Anything else we need to know**:
The same scale command works perfectly fine for scaling up and down Linux agent pool.
[kubernetes-hybrid.json.txt](https://github.com/Azure/acs-engine/files/1591877/kubernetes-hybrid.json.txt)

**Comment by zqingqing1** [comment]
Hi Prathamesh, currently, the scalability for windows haven't implemented yet. So that's the reason why it works well for Linux agent pool. Team are working on supporting this feature. Thanks for pointing the issue out.

**Comment by campbelldgunn** [comment]
@zqingqing1 Does scaling out a windows pool work for `acs` and or `aks`then? Or this is a problem across all 3 CLIs?

**Comment by JiangtianLi** [comment]
@campbelldgunn acs leverages acs-engine package code as library therefore scaling windows pool should have the same issue in acs. aks doesn't support windows node yet.

**Comment by campbelldgunn** [comment]
@JiangtianLi Great, thanks.

**Comment by qmalexander** [comment]
Hi, @zqingqing1. Is it possible to get this fixed asap?

**Comment by JiangtianLi** [comment]
@jackfrancis @CecileRobertMichon on the plan to fix scaling for windows pool.

**Comment by jackfrancis** [comment]
@qmalexander Current Windows priorities are validating RS3 hotfix patches that affect network behaviors during deployment. This PR brings some of that:

https://github.com/Azure/acs-engine/pull/2230

We aim to further test and validate that known bad behaviors have been addressed.

After that, I'm fine to queue up Windows scaling if @JiangtianLi has cycles.

For emphasis: thank you so much for your patience using Windows clusters before this feature is ready!

**Comment by qmalexander** [comment]
Sounds awesome!, @jackfrancis what is the deadline on completing #2230? 
Do any one has a suggestion on how to scale in the mean time?
Then the question is. @JiangtianLi  do you have cycles? 😊

**Comment by jackfrancis** [comment]
@qmalexander #2230 is in master, look for it in the next release of acs-engine this week.

**Comment by qmalexander** [comment]
@jackfrancis nice! So is it possible for you to start with this one now?  @JiangtianLi

**Comment by jackfrancis** [comment]
@qmalexander The RS3 hotfix patches that are in the v0.13.0 release still need testing, and overall our current priority is stability over features (Windows scaling). I know that's a squishy answer, but want to set your expectations according to our near term focus.

Thanks for continuing to inquire!

**Comment by MirzaSikander** [comment]
`Version: v0.13.1` still has this issue.

**Comment by BuairtRi** [comment]
Just adding my upvote that this is important. My project is about to launch depending on running microservices in a windows kubernetes environment, and I need to be able to scale machines easily. 

Is there a work around to add a few machines to the node without the command line?
