### ISSUE TITLE
Trying to upgrade Kubernetes cluster version 1.6.6 created from ACS engine version 0.5.0

### ISSUE THREAD

**Issue by vannovv** [Azure/acs-engine#1974]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.11.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Trying use the upgrade command to upgrade a Kubernetes cluster from 1.6.6 to 1.7.10.  The cluster was created using acs-engine 0.5.0 and I am now running version 0.11.0.  When I run the following command with all the information filled out:

acs-engine upgrade --subscription-id  --deployment-dir  --location centralus --resource-group  --upgrade-version 1.7.10 --auth-method client_secret --client-id  --client-secret 

I get the following output:

INFO[0000] validating...
INFO[0002] Error returned by LoadContainerService: Unknown JSON tag servicePrincipalClientID
FATA[0002] error parsing the api model: Unknown JSON tag servicePrincipalClientID

**What you expected to happen**:
The cluster to be upgraded to version 1.7.10

**How to reproduce it** (as minimally and precisely as possible):
Create cluster from older acs-engine version and try to upgrade?

**Anything else we need to know**:
It appears to referring to the servicePrincipalClientID line in the apimodel.json file in the output directory and it appears to have the correct SP info.

**Comment by dstrebel** [comment]
Does the servicePrincipalProfile look like this? I believe the clientId and secret JSON changed versions back.

"servicePrincipalProfile": {
      "clientId": "XXXXXXXXXXXXXXXXXXXX",
      "secret": "XXXX-XXXXX-XXXX_XXXXXXX"
