### ISSUE TITLE
Remove kubernetes useInstanceMetadata parameters

### ISSUE THREAD

**Issue by feiskyer** [Azure/acs-engine#1976]
**Is this a request for help?**:

Request.

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

FEATURE REQUEST.

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes v1.10+

**What happened**:

`useInstanceMetadata` parameter has been removed by https://github.com/kubernetes/kubernetes/pull/57647. 

**What you expected to happen**:

We should remove `useInstanceMetadata` parameters from kubernetes azure cloud provider configure file for v1.10+.

And set `useInstanceMetadata=false` by default for all older releases.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by karataliu** [comment]
Related https://github.com/Azure/acs-engine/pull/1763

**Comment by feiskyer** [comment]
Update: 

Note that instance's providerID/externalID are in different formats with useInstanceMetadata enabled or not:

- useInstanceMetadata=true: providerID/externalID are instance's VMID (in UUID format), e.g. `azure://abcdef11-1111-1111-1111-9fd3bafde18a`
- useInstanceMetadata=false or not set: providerID/externalID are instance's ID, e.g. `azure:///subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.Compute/virtualMachines/<vm-name>`

This could cause upgrading problems from old clusters (with useInstanceMetadata=true) to v1.10+. 

Could we disable metadata for v1.9? So we could support upgrading v1.9 to v1.10+ in the future.

/cc @jackfrancis  @brendandburns @jdumars

**Comment by feiskyer** [comment]
This is not required. We will add instance back and change its format to azure instance ID format.
