### ISSUE TITLE
Liveness and Readiness probes fail after restarting kubelet , causing containers to crash in a loop

### ISSUE THREAD

**Issue by lirkog86** [Azure/acs-engine#1977]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
0.9.3 , 0.12
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.2

**What happened**:
Liveness and Readiness probes get connection refused after restarting kubelet service by running "systemctl restart kubelet" and starting a new pod on the node.

this only happen when using kubenet network plugin.  CNI and calico doesn't have this issue.

due to the failure of the Liveness probe some of k8s system containers (kube-dns, dashboard and tiller) started to crash in a loop- 

kube-system   tiller-deploy-76775db66-2vgcg                   0/1       CrashLoopBackOff   6          27m       10.244.2.3     k8s-agentpool0-29177002-1

**What you expected to happen**:
Liveness and Readiness probe shouldn't fail after restarting kubelet service and running a new pod on the host

**How to reproduce it** (as minimally and precisely as possible):
run a new alpine deployment on a node running kube-dns/tiller-deploy pods.
restart kubelet on that node using "systemctl restart kubelet"
run a new deployment on the same node.

journalctl will show the following errors-
```
Jan 02 14:50:16 k8s-agentpool0-29177002-1 docker[30982]: I0102 14:50:16.564647   31028 prober.go:106] Liveness probe for "tiller-deploy-76775db66-2vgcg_kube-system(d4bdf1e8-efc6-11e7-997a-000d3af913ad):tiller" failed (failure): Get http://10.244.2.3:44135/liveness: dial tcp 10.244.2.3:44135: getsockopt: connection refused
Jan 02 14:50:22 k8s-agentpool0-29177002-1 docker[30982]: I0102 14:50:22.469114   31028 prober.go:106] Readiness probe for "tiller-deploy-76775db66-2vgcg_kube-system(d4bdf1e8-efc6-11e7-997a-000d3af913ad):tiller" failed (failure): Get http://10.244.2.3:44135/readiness: dial tcp 10.244.2.3:44135: getsockopt: connection refused
Jan 02 14:50:26 k8s-agentpool0-29177002-1 docker[30982]: I0102 14:50:26.564519   31028 prober.go:106] Liveness probe for "tiller-deploy-76775db66-2vgcg_kube-system(d4bdf1e8-efc6-11e7-997a-000d3af913ad):tiller" failed (failure): Get http://10.244.2.3:44135/liveness: dial tcp 10.244.2.3:44135: getsockopt: connection refused
```

tiller-deploy events-

```
Events:
  Type     Reason                 Age                From                                Message
  ----     ------                 ----               ----                                -------
  Warning  FailedScheduling       37m (x5 over 37m)  default-scheduler                   No nodes are available that match all of the predicates: NodeNotReady (4), PodToleratesNodeTaints (1).
  Normal   SuccessfulMountVolume  37m                kubelet, k8s-agentpool0-29177002-1  MountVolume.SetUp succeeded for volume "tiller-token-dxsqs"
  Normal   Pulling                37m                kubelet, k8s-agentpool0-29177002-1  pulling image "gcrio.azureedge.net/kubernetes-helm/tiller:v2.6.2"
  Normal   Scheduled              37m                default-scheduler                   Successfully assigned tiller-deploy-76775db66-2vgcg to k8s-agentpool0-29177002-1
  Normal   Started                37m                kubelet, k8s-agentpool0-29177002-1  Started container
  Normal   Pulled                 37m                kubelet, k8s-agentpool0-29177002-1  Successfully pulled image "gcrio.azureedge.net/kubernetes-helm/tiller:v2.6.2"
  Normal   Created                37m                kubelet, k8s-agentpool0-29177002-1  Created container
  Normal   SuccessfulMountVolume  19m                kubelet, k8s-agentpool0-29177002-1  MountVolume.SetUp succeeded for volume "tiller-token-dxsqs"
  Normal   Killing                16m (x3 over 16m)  kubelet, k8s-agentpool0-29177002-1  Killing container with id docker://tiller:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Started                16m (x3 over 16m)  kubelet, k8s-agentpool0-29177002-1  Started container
  Normal   Created                16m (x3 over 16m)  kubelet, k8s-agentpool0-29177002-1  Created container
  Warning  Unhealthy              16m (x5 over 16m)  kubelet, k8s-agentpool0-29177002-1  Readiness probe failed: Get http://10.244.2.3:44135/readiness: dial tcp 10.244.2.3:44135: getsockopt: connection refused
  Warning  Unhealthy              16m (x5 over 16m)  kubelet, k8s-agentpool0-29177002-1  Liveness probe failed: Get http://10.244.2.3:44135/liveness: dial tcp 10.244.2.3:44135: getsockopt: connection refused
  Normal   Pulled                 9m (x7 over 16m)   kubelet, k8s-agentpool0-29177002-1  Container image "gcrio.azureedge.net/kubernetes-helm/tiller:v2.6.2" already present on machine
  Warning  FailedSync             4m (x52 over 20m)  kubelet, k8s-agentpool0-29177002-1  Error syncing pod
```

**Anything else we need to know**:
the issue happens only when running new pods after restarting kubelet service

**Comment by jackfrancis** [comment]
Are these clusters long-running or short-lived? Is they are short-lived, would you consider using a more recent version of acs-engine (with a more recent version of k8s)?

Seeing as how this is kubenet-only symptom, is there a reason you're not using Azure CNI for IPAM?

Thanks!

**Comment by lirkog86** [comment]
so you don't recommend using kubelet when deploying clusters with acs-engine?

**Comment by jackfrancis** [comment]
You should use kubenet if you want control (at the expense of maintenance overhead) of your cluster network concerns. Azure CNI is meant to handle basic functional network concerns on behalf of the user, which is why it makes sense for most folks (most folks don't want/need to be concerned about enforcing their own cluster networking).

@sharmasushant can provide more details if you feel like your requirements are squishy in terms of my simplified description of Azure CNI vs kubenet. There are good reasons to use one or the other. What are your needs?

**Comment by lirkog86** [comment]
same issue occurs in acs-engine v0.12.
i don't see it happening in gcloud k8s deployment with kubenet

**Comment by slack** [comment]
Should be fixed by #2165. Kubelet restart was overwriting the IPAM database, causing duplicate ip addresses to be assigned to Pods on the host.

Can you provision a new cluster (with master) and validate that you no longer see the failing health/liveness probes?

**Comment by hmarcelodn** [comment]
The same issue happened to our clusters in production suddenly.

Whats the timeline?

**Comment by jackfrancis** [comment]
FYI I have a PR that I'm using to add environmental DNS sanity checks for our E2E cluster deployments:

https://github.com/Azure/acs-engine/pull/2921

Please add any high level wishlist items or concrete coverage requests there to get ahead of these issues going forward. Thanks!
