### ISSUE TITLE
kube-dns and kubernetes-dashboard fail to come up

### ISSUE THREAD

**Issue by JonathanFraser** [Azure/acs-engine#200]
These may be seperate issues but its difficult to tell. I spin up a vanilla cluster in westus2 with [file](https://gist.github.com/JonathanFraser/e367a485b81deab0084e3e40a31ca1e5).

cluster comes up and api is accessible, however both the dashboard and kube-dns pods are in a crashloopbackoff. the kube-dns pod is listing some [errors](https://gist.github.com/JonathanFraser/ee7863e734e51d72f211f3c7aa8d2b14).

the dashboard logs are simpler but perhaps more perplexing as the api is accessible but it says it cannot [connect](https://gist.github.com/JonathanFraser/9b4171e5c6cba25579f8fa5aa1fcab0a).

as both of these are addons it could be a fault with the addon manager whose log is [here](https://gist.github.com/JonathanFraser/ad8b08276d5d84a71e7146beaada5878).

**Comment by JonathanFraser** [comment]
Some further debugging seems to point to the same issue, that neither the dashboard or the dns can access the kubernetes service. The kubedns container seems to start, however it lists the api as nil and then fails to forward the dns requests. 
```
I0120 20:34:05.916909       1 server.go:94] Using https://10.0.0.1:443 for kubernetes master, kubernetes API: <nil>
I0120 20:34:05.917532       1 server.go:99] v1.4.0-alpha.2.1652+c69e3d32a29cfa-dirty
I0120 20:34:05.917564       1 server.go:101] FLAG: --alsologtostderr="false"
I0120 20:34:05.917572       1 server.go:101] FLAG: --dns-port="10053"
I0120 20:34:05.917578       1 server.go:101] FLAG: --domain="cluster.local."
I0120 20:34:05.917582       1 server.go:101] FLAG: --federations=""
I0120 20:34:05.917586       1 server.go:101] FLAG: --healthz-port="8081"
I0120 20:34:05.917595       1 server.go:101] FLAG: --kube-master-url=""
I0120 20:34:05.917598       1 server.go:101] FLAG: --kubecfg-file=""
I0120 20:34:05.917602       1 server.go:101] FLAG: --log-backtrace-at=":0"
I0120 20:34:05.917606       1 server.go:101] FLAG: --log-dir=""
I0120 20:34:05.917610       1 server.go:101] FLAG: --log-flush-frequency="5s"
I0120 20:34:05.917618       1 server.go:101] FLAG: --logtostderr="true"
I0120 20:34:05.917622       1 server.go:101] FLAG: --stderrthreshold="2"
I0120 20:34:05.917625       1 server.go:101] FLAG: --v="0"
I0120 20:34:05.917629       1 server.go:101] FLAG: --version="false"
I0120 20:34:05.917636       1 server.go:101] FLAG: --vmodule=""
I0120 20:34:05.917752       1 server.go:138] Starting SkyDNS server. Listening on port:10053
I0120 20:34:05.917815       1 server.go:145] skydns: metrics enabled on : /metrics:
I0120 20:34:05.917830       1 dns.go:167] Waiting for service: default/kubernetes
I0120 20:34:05.917921       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0120 20:34:05.917941       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0120 20:34:12.204164       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:54960->168.63.129.16:53: i/o timeout"
I0120 20:34:12.204256       1 logs.go:41] skydns: failure to forward request "read udp 10.244.5.3:54960->168.63.129.16:53: i/o timeout"
```

**Comment by colemickens** [comment]
Please pull the latest ACS-Engine. It includes a fix for this issue. See more details here: https://github.com/Azure/ACS/issues/3

**Comment by JonathanFraser** [comment]
I have pulled and rebuilt with the latest version. However, both the master and agent nodes are brought up with docker 1.13.0

**Comment by JonathanFraser** [comment]
looking into the template on the azure portal itself I can see that the variable for both the master and agent has a variable:
   `"dockerEngineVersion": "1.12.*"`
so it appears that the installation script is for some reason ignoring the version

**Comment by colemickens** [comment]
I'm afraid I can't reproduce this. On HEAD of `master` with git commit: 7cd3e7f7d17c59e6fe4b014e61688bba3df92cfa

```
NAMESPACE     NAME                                            READY     STATUS    RESTARTS   AGE
kube-system   heapster-v1.2.0-194960081-hpsl3                 2/2       Running   0          10m
kube-system   kube-addon-manager-k8s-master-33416968-0        1/1       Running   0          10m
kube-system   kube-apiserver-k8s-master-33416968-0            1/1       Running   0          10m
kube-system   kube-controller-manager-k8s-master-33416968-0   1/1       Running   0          10m
kube-system   kube-dns-v19-2j9v0                              3/3       Running   0          10m
kube-system   kube-dns-v19-b1n4z                              3/3       Running   0          10m
kube-system   kube-proxy-cpxsm                                1/1       Running   0          10m
kube-system   kube-proxy-qc30g                                1/1       Running   0          10m
kube-system   kube-proxy-w0z7j                                1/1       Running   0          10m
kube-system   kube-scheduler-k8s-master-33416968-0            1/1       Running   0          10m
kube-system   kubernetes-dashboard-1872455951-b1nts           1/1       Running   0          10m
```

**Comment by colemickens** [comment]
To help any further, I'd need you to send me these files from the master and at least one node:

* `/var/log/cloud-init.log`
* `/var/log/cloud-init-output.log`
* `/var/lib/cloud/instance/user-data.txt`
* `/var/lib/cloud/instance/cloud-config.txt`

**Comment by JonathanFraser** [comment]
I think the following are probably relavent:
cloud-init-output.log (on master)
```
The following additional packages will be installed:
  aufs-tools cgroupfs-mount libltdl7
Suggested packages:
  mountall
The following NEW packages will be installed:
  aufs-tools cgroupfs-mount docker-engine libltdl7
0 upgraded, 4 newly installed, 0 to remove and 146 not upgraded.
Need to get 19.3 MB/19.4 MB of archives.
After this operation, 89.2 MB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu xenial/universe amd64 cgroupfs-mount all 1.2 [4970 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 libltdl7 amd64 2.4.6-0.1 [38.3 kB]
Get:3 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 docker-engine amd64 1.13.0-0~ubuntu-xenial [19.2 MB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 19.3 MB in 0s (29.0 MB/s)
Selecting previously unselected package aufs-tools.
(Reading database ... 61253 files and directories currently installed.)
Preparing to unpack .../aufs-tools_1%3a3.2+20130722-1.1ubuntu1_amd64.deb ...
Unpacking aufs-tools (1:3.2+20130722-1.1ubuntu1) ...
Selecting previously unselected package cgroupfs-mount.
Preparing to unpack .../cgroupfs-mount_1.2_all.deb ...
Unpacking cgroupfs-mount (1.2) ...
Selecting previously unselected package libltdl7:amd64.
Preparing to unpack .../libltdl7_2.4.6-0.1_amd64.deb ...
Unpacking libltdl7:amd64 (2.4.6-0.1) ...
Selecting previously unselected package docker-engine.
Preparing to unpack .../docker-engine_1.13.0-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-engine (1.13.0-0~ubuntu-xenial) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu6) ...
Setting up aufs-tools (1:3.2+20130722-1.1ubuntu1) ...
Setting up cgroupfs-mount (1.2) ...
Setting up libltdl7:amd64 (2.4.6-0.1) ...
Setting up docker-engine (1.13.0-0~ubuntu-xenial) ...
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(group) request, exiting
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for systemd (229-4ubuntu6) ...
Processing triggers for ureadahead (0.100.0-19) ...
Cloud-init v. 0.7.7 running 'modules:final' at Fri, 20 Jan 2017 23:40:44 +0000. Up 40.69 seconds.
Cloud-init v. 0.7.7 finished at Fri, 20 Jan 2017 23:41:44 +0000. Datasource DataSourceAzureNet [seed=/dev/sr0].  Up 102.00 seconds
```

while the file: /etc/apt/preferences.d/docker.pref
```
Package: docker-engine Pin: version 1.12.* Pin-Priority: 550
```

so it appears the pin line is correctly written to apt preferences but the docker-engine install jumps to 1.13.0 anyway

**Comment by JonathanFraser** [comment]
there appears to be a discrepency between the hold lines in cloud-config and user-data.txt
cloud-config.txt:
```
- echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
- 'echo "Package: docker-engine Pin: version 1.12.* Pin-Priority: 550 " > /etc/apt/preferences.d/docker.pref'
```

while user-data.txt
```
- "echo \"Package: docker-engine
Pin: version 1.12.*
Pin-Priority: 550
\" > /etc/apt/preferences.d/docker.pref"
```

checking the ubuntu reference it looks like the individual entries should be on seperate lines but the actual pin file is all on one line. I suspect there is a new line escaping issue here.

**Comment by colemickens** [comment]
I really need all of the files mentioned, please. Like I said, we're not
seeing this anywhere else so I need to figure out why yours is different.

**Comment by colemickens** [comment]
Also, how exactly are you deploying the template afterward?

**Comment by JonathanFraser** [comment]
`azure group deployement create`

**Comment by colemickens** [comment]
What version? `azure --version`? 

I'm pretty sure you're being bitten by a bug in the CLI actually. The docs should have instructed you to either downgrade it to a working version, or use the new `az` cli. I strongly recommend the latter.

**Comment by JonathanFraser** [comment]
the version is 0.10.7, though how would a this be a cli bug?

**Comment by colemickens** [comment]
The CLI doesn't escape the JSON payload correctly. The newlines are rendered as literals and so when they're placed on box, they're incorrect. -- The apt preference file is supposed to be three lines, not one.

Please downgrade `azure` or switch to `az`.

**Comment by colemickens** [comment]
(For whatever reason the CLI parses the JSON to ensure it's correctly formatted, but they submit the output of that process, rather than the original body. There's a bug in that process that causes escape literals in javascript to be processed incorrectly. Basically, the file on disk and the file submitted to the Azure API have more differences than just whitespace -- which is the bug).

I'm trying to get confirmation of whether this is fixed in `0.10.8`, but like I said, `az` is better for a lot of reasons anyway.

**Comment by JonathanFraser** [comment]
that would explain the behaviour, I'll make the appropriate script changes and redeploy

**Comment by colemickens** [comment]
It does appear the parser shipped in `0.10.8` is changed, so you might be able to do a minor (not really a bugfix release the way they're doing versioning). Might be less disruptive than changing to `az`. (But please note, I haven't personally tested `0.10.8`.)

**Comment by JonathanFraser** [comment]
although one could argue that those echos should be a write_file instead of a run command as file write happen first anyway. moreover cloud init supports version pinning a file directly as well as install addition repos so most of those commands could be handled in native cloud init.

**Comment by colemickens** [comment]
Good points. If you wanted to file issues for that, or better yet, send PRs, we would take them under consideration.

Let me know if you were unblocked and we can close this one out at least. Thanks!

**Comment by JonathanFraser** [comment]
Looks like that was it, cutting over the the python client fixed the problem.

**Comment by colemickens** [comment]
Glad to hear it. Thanks for the patience and quick back and forth while troubleshooting. Cheers.

**Comment by homotopycolimit** [comment]
I am having the same issues.
Deployed a brand new cluster using kubernetes-anywhere and the kube-dns and dashboard pods are stuck in a Crash Loop.
This issue is marked as "Closed" but I don't understand what I should do to fix the problem.

(using azure v0.10.8, tried kubernetes 1.4.8 and 1.5.2, kubernetes-anywhere master branch)

**Comment by anhowe** [comment]
Hi Aron,

Sounds like you are hitting the following issue: https://github.com/Azure/ACS/issues/3.

You can fix your existing cluster with the workaround script or upgrade to the latest ACS-Engine.

Thanks,

Anthony

**Comment by homotopycolimit** [comment]
thank you.
indeed downgrading docker to 1.12.* solved that issue for me.
...
Now I'm stuck on the next issue https://github.com/kubernetes/kubernetes/issues/40332 
:)

**Comment by anhowe** [comment]
Are you using the latest ACS-Engine?  This is not a problem in the latest ACS-Engine since it uses kubernetes 1.5.1: https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/const.go.

Thanks,

Anthony

**Comment by homotopycolimit** [comment]
Unfortunately I used kubernetes-anywhere ( https://github.com/kubernetes/kubernetes-anywhere ) to deploy and I chose to use the latest release ( 1.5.2 - https://github.com/kubernetes/kubernetes/releases ).
