### ISSUE TITLE
Improve StorageAccountClassic validation

### ISSUE THREAD

**Issue by amanohar** [Azure/acs-engine#201]
Validation should block StorageAccountClassic in one or more agent pools if the master doesn’t have  "storageProfile": "StorageAccountClassic".

I specified: "storageProfile": "StorageAccountClassic" only in agent pool profile and not master profile. 

This resulted in a template where a var: "_storageAccountBaseName_" is generated but never used. Although I do see “_storageAccountBase**Classic**Name_” being used but is not declared.

**Comment by anhowe** [comment]
The mode to dynamically generate the "classic" templates on the fly was experimental, and has been reverted.  Closing this.
