### ISSUE TITLE
Kubernetes pods cant see each other via external ip address / external dns in acs-engine 0.8

### ISSUE THREAD

**Issue by douglaswaights** [Azure/acs-engine#2013]
**Is this a request for help?**:
yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE
---

**What version of acs-engine?**:

0.8.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

I have a mixed cluster windows and linux and im running a web app against identity server. To log into the web app a hybrid flow is used which goes through the browser so its not sufficient to use internal kubernetes services. Unfortunately it appears pods cannot see each other via the external load balancer ip address or external dns address and so this fails. The solution is to spin up another cluster to host identity server. I've just tried this in AKS to see if the behaviour is the same but it appears that it works as expected in AKS so this appears to be an acs-engine bug. Once this mixed cluster is created it doesnt seem to matter if its windows external ip adress pod to linux external ip address pod or linux to linux...neither work.

**What you expected to happen**:
Two pods in the same mixed windows and linux cluster can reference each other via external load balancer ip / external dns address.

**How to reproduce it** (as minimally and precisely as possible):

As described above

**Comment by 4c74356b41** [comment]
how did you créate hybrid AKS cluster? i dont think its posible yet?

**Comment by douglaswaights** [comment]
@4c74356b41 no in AKS its just a linux cluster...but the pods can communicate via external load balancer ip in addition to k8s services, unlike in ACS engine 0.8.0.

**Comment by 4c74356b41** [comment]
@douglaswaights because they are not windows :)
