### ISSUE TITLE
Kubernetes dashboard not deployed in AzureGermanCloud

### ISSUE THREAD

**Issue by MarkTiedemann** [Azure/acs-engine#2014]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): `ISSUE`

---

**What version of acs-engine?**:

```sh
$ acs-engine version
Version: v0.11.0
GitCommit: cda96312
GitTreeState: clean
```

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: `Kubernetes, v1.8.4`

**What happened**:

<details><summary><code>apimodel.json</code></summary><p>

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "orchestratorVersion": "1.8.4"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "<redactedDnsPrefix>",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

</p></details>

<details><summary><code>deploy.ps1</code></summary><p>

```powershell
az cloud set `
  --name 'AzureGermanCloud'

acs-engine deploy `
  --resource-group '<redactedResourceGroup>' `
  --subscription-id '<redactedSubscriptionId>' `
  --location 'germanynortheast' `
  --azure-env 'AzureGermanCloud' `
  --api-model 'apimodel.json'
```

</p></details>

<br>

`az login && powershell -f deploy.ps1` creates the following:

<details><summary><code>_output/azuredeploy.parameters.json</code></summary><p>

```json
{
  "$schema":
    "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "_moreStuffHere": {},
    "kubernetesDashboardCPULimit": {
      "value": "300m"
    },
    "kubernetesDashboardCPURequests": {
      "value": "300m"
    },
    "kubernetesDashboardMemoryLimit": {
      "value": "150Mi"
    },
    "kubernetesDashboardMemoryRequests": {
      "value": "150Mi"
    },
    "kubernetesDashboardSpec": {
      "value":
        "gcrio.azureedge.net/google_containers/kubernetes-dashboard-amd64:v1.8.0"
    },
    "_moreStuffHere": {},
    "location": {
      "value": ""
    },
    "_moreStuffHere": {},
    "targetEnvironment": {
      "value": "AzurePublicCloud"
    }
  }
}
```

</p></details>

<br>

**What you expected to happen**:

* I expected the `"parameters"."location"."value"` in `_output/azuredeploy.parameters.json` to be `"germanynortheast"`. It is `""`, however.
* I expected the `"parameters"."targetEnvironment"."value"` in `_output/azuredeploy.parameters.json` to be `"AzureGermanCloud"`. It is `"AzurePublicCloud"`, however.

* Based on the `_output/azuredeploy.parameters.json`, I expected the Kubernetes dashboard to be deployed in the cluster. It is not, however:

```sh
$ kubectl get svc -n kube-system
No resources found.
```

**How to reproduce it** (as minimally and precisely as possible):

See above.

**Anything else we need to know**:

Feel free to ask. :)

**Comment by MarkTiedemann** [comment]
If I go through the same steps but change the location to `westeurope` and the cloud to `AzurePublicCloud`, it works:

```sh
# In German Cloud
$ kubectl cluster-info
Kubernetes master is running at https://<redacted>.germanynortheast.cloudapp.microsoftazure.de
```

```sh
# In Public Cloud
$ kubectl cluster-info
Kubernetes master is running at https://<redacted>.westeurope.cloudapp.azure.com
Heapster is running at https://<redacted>.westeurope.cloudapp.azure.com/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://<redacted>.westeurope.cloudapp.azure.com/api/v1/namespaces/kube-system/services/kube-dns/proxy
kubernetes-dashboard is running at https://<redacted>.westeurope.cloudapp.azure.com/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
tiller-deploy is running at https://<redacted>.westeurope.cloudapp.azure.com/api/v1/namespaces/kube-system/services/tiller-deploy/proxy
```

**Comment by CecileRobertMichon** [comment]
@htuomola what does your apimodel look like?

**Comment by htuomola** [comment]
@CecileRobertMichon Hi, should've came back to this earlier. In my case the issue was with trying to provide service principal credentials via KeyVault and the KV secret was missing some permissions. As a result, the deployment was "successful" but without dashboard etc. I actually never got the keyvault-based service principal working but that doesn't relate to this..
