### ISSUE TITLE
[Windows Nodes] "There is no enough space on the disk"

### ISSUE THREAD

**Issue by Stygy** [Azure/acs-engine#2015]
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

v0.11.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.9

**What happened**:
Cannot pull images because of a "There is not enough space on the disk" error:
![image](https://user-images.githubusercontent.com/6739343/34728649-769b5672-f528-11e7-822a-9595e4acaa9a.png)
 
K8s shows that there is no disk space issue: 
![image](https://user-images.githubusercontent.com/6739343/34728535-235de56a-f528-11e7-910d-ff370d7427be.png)

**What you expected to happen**:
Pod created with no issue

**How to reproduce it** (as minimally and precisely as possible):
1) Create a Hybrid Cluster with this json: https://goo.gl/9zA9wF
2) Create 6 deployments with microsoft/iis (version 1709) as base image. These will work
3) Create an additional deployment with the same image, the error will start to appear. 

**Anything else we need to know**:
I've upgraded the master machine to D12_V2 but that didn't fix the error. https://goo.gl/g7FjuQ

**Comment by andyzhangx** [comment]
you need to assign a bigger OS disk size, see example:
https://github.com/Azure/acs-engine/blob/master/examples/windows/kubernetes-manageddisks.json#L20

**Comment by Stygy** [comment]
I've setup a 200GB disk (https://goo.gl/9zA9wF). What would be a recommended size for the OS disk? Can I resize the disk without rebuilding the cluster?

**Comment by andyzhangx** [comment]
One possible solution is use the resource disk which has 100GB to download image, need to find a way to change docker settings?

**Comment by robinsondotnet** [comment]
I've got the same error. Have anyone solved? 
I am using a image based on microsoft/dotnet-framework:4.7 . This image is around 12GB. I think that it  shouldn't be a problem.

**Comment by andyzhangx** [comment]
@JiangtianLi do you know anyway to let docker use resource disk in Windows, I only know how to do it in Linux. Resource disk has 100GB size, it would good place for temp dir.

**Comment by Stygy** [comment]
I've seen that by default the windows VM's are being created with a 30GB C drive where Docker is. I've tried to setup docker with the daemon.json file (adding this line:  **{"graph": "H:\\Images"}**). BTW I had to Initialize/Partition/Format the attached disks because by default I only had the C and D drives. Looks like the OSDiskSizeGB is not working. 

After I did this I tried to start a couple of containers and got constantly the "**Failed create pod sandbox**" error. 

Plus, I see that I'm missing the kubletwin/Pause images after I changed the docker configuration. Is there anyway I can get that? Couldn't pull that from docker hub.

**Comment by Stygy** [comment]
I should also include that I setup a custom VNET for my cluster, that's the only way I found to get into the windows nodes and check what was happening. And I must mention that I went through a big issue with the Dashboard and DNS deployments because the acs-engine deployment was not setting up the Route Table.

**Comment by Stygy** [comment]
Ok, I've solved the disk space issue. I connected to the machine and expanded the C Volume with Diskpart app.
list disk
list volume
select volume 1
extend

Now I only have the Pod sandbox issue. That might be because the VNET setup

![image](https://user-images.githubusercontent.com/6739343/34892557-b495e38a-f7a7-11e7-9115-0b610033f1a0.png)

**Comment by Stygy** [comment]
In https://github.com/Azure/acs-engine/blob/master/docs/custom-vnet.md
There must say that if you want to use that in windows nodes is necessary to add the subnet variable in the azuredeploy.json that is expected but not there.

My Linux pods have no issues... only windows ones

**Comment by PatrickLang** [comment]
Another solution is to move the container storage to D:, but that's not resilient. That shouldn't be a problem because you can just pull the image again if they're missing.

This requires:

1. Change `data-root` docker daemon config to a path on d:
2. Change `DOCKER_TMPDIR` to a path on d: (needs a fix that's not in Docker EE 17.06 yet https://github.com/moby/moby/pull/35077)
3. Re-pull any images you need

**Comment by andyzhangx** [comment]
I set Windows OSDisk size as 300GB, while after creating some windows containers like aspnet, it has only 3GB disk space left even I have removed all containers. What I could workaround is clean Temp dir to release 13GB space.
```
rm -Recurse -Force C:\Windows\Temp\*
```

Is there any way to release the cache data in Windows?
