### ISSUE TITLE
LoadBalancer Service does not receive public IP in AzureGermanCloud

### ISSUE THREAD

**Issue by sebastianroesch** [Azure/acs-engine#2016]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): `ISSUE`

---

**What version of acs-engine?**:

```sh
$ acs-engine version
Version: v0.11.0
GitCommit: cda96312
GitTreeState: clean
```

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: `Kubernetes, v1.8.4`

**What happened**:

<details><summary><code>apimodel.json</code></summary><p>

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "orchestratorVersion": "1.8.4"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "<redactedDnsPrefix>",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

</p></details>

<details><summary><code>deploy.ps1</code></summary><p>

```powershell
az cloud set `
  --name 'AzureGermanCloud'

acs-engine deploy `
  --resource-group '<redactedResourceGroup>' `
  --subscription-id '<redactedSubscriptionId>' `
  --location 'germanynortheast' `
  --azure-env 'AzureGermanCloud' `
  --api-model 'apimodel.json'
```

</p></details>

<details><summary><code>service.yaml</code></summary><p>

```apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name:proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name:proxy-ssl
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: proxy
```

</p></details>

<br>

`az login && powershell -f deploy.ps1` deploys the cluster.
`kubectl apply -f service.yaml` deploys the Kubernetes service, but does not apply a public IP address. The assigned external IP address of the service ports stay in `pending` forever.

I already checked the IP address limit of my Azure subscription and that seems to be no issue since I can create public IPs in other ways.

```
NAMESPACE   NAME         CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
default     kubernetes     10.0.0.1          <none>     443/TCP                      2h
default     proxy      10.0.213.161       <pending>     80:31373/TCP,443:30825/TCP   3m
```

<br>

**What you expected to happen**:

* I expected the service to receive a public IP address.
* I expected the same behavior as when I deploy the cluster and service in another Azure region, like this:
```
NAMESPACE     NAME        CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
default       kubernetes    10.0.0.1          <none>     443/TCP                      11m
default       proxy      10.0.122.22      52.178.X.X     80:31099/TCP,443:30692/TCP   3m
```
**How to reproduce it** (as minimally and precisely as possible):

See above.

**Anything else we need to know**:

Feel free to ask. :)

**Comment by sebastianroesch** [comment]
Probably related to #2014

**Comment by ralbon** [comment]
I have the same issue. Did you find any solution ?

I can see the Public IP created in azure interface, associated to the load balancer created.
However, it stays in pending ..

ACS Engine: 0.13.0
Kubernetes : 1.9.3
Azure : Northeurope

Thank you

**Comment by ryanlovett** [comment]
I'm having the same problem while deploying [JupyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/index.html).

ACS Engine: 0.20.6
Kubernetes: 1.10.6
Azure: westus2

**Comment by joelsjolly** [comment]
I"m having same problem (external IP is pending), deploying the BookInfo sample (Istio)
ACS Engine v0.18.8
Kubernetes 1.10.3
Azure eastus

**Comment by ryanlovett** [comment]
After some MS folks pointed me at a [virtual-kubelet/LoadBalancer issue](https://github.com/virtual-kubelet/virtual-kubelet/issues/41), I tried modifying our azuredeploy.parameters.json, changing kubernetesACIConnectorSpec from "microsoft/virtual-kubelet" to "microsoft/". After deploying the agents and installing our helm chart, our LoadBalancer was able to get a public IP.

Theoretically this shouldn't matter since kubernetesACIConnectorEnabled == false in the same file.
