### ISSUE TITLE
Add support for kubernetes --feature-gates in template

### ISSUE THREAD

**Issue by stuartleeks** [Azure/acs-engine#2021]
**Is this a request for help?**: No 

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of acs-engine?**: latest master (8fd4ac4)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes - all versions

**What you expected to happen**: Various behaviours (and preview features) in Kubernetes are controlled by `--feature-gates`. As per the [docs](https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md#kubeletconfig), specifying `--feature-gates` is currently not permitted.

Proposal:

1. Allow `--feature-gates` to be specified in the `kubeletConfig`. 
Looking at the code, the agents currently include `Accelerators=true` in `--feature-gates` for kubernetes version 1.6.0 and above, so this behaviour should be preserved. 
2. Add an `apiserverConfig` section to `kubernetesConfig` as per the `kubeletConfig` to allow apiserver specific configuration (including `--feature-gates`). This was discussed in a comment [here](https://github.com/Azure/acs-engine/pull/1854#issuecomment-348030399)

Sample config:

```json

"kubernetesConfig": {
    "kubeletConfig": {
        "--cluster-dns": "172.17.1.11",
        "--max-pods": "30",
        "--feature-gates": {
            "MountPropagation": "true",
            "TaintNodesByCondition": "true"
        },
        <etc...>
    },
    "apiserverConfig": {
        "--storage-backend": "etcd3",
        "--feature-gates": {
            "MountPropagation": "true"
        },
        <etc...>
    }
}
```

**Update**: 
As per the [comments](https://github.com/Azure/acs-engine/pull/2032#issuecomment-357813879) from @paulbouwer we should ensure that this covers settings `--feature-gates` for:

- [x] kubelet
- [x] api-server
- [x] kube-controller-manager
- [ ] kube-proxy
- [ ] kube-scheduler

**Comment by stuartleeks** [comment]
@jackfrancis, @CecileRobertMichon, @JackQuincy  - would love your thoughts on the approach :-)

**Comment by stuartleeks** [comment]
@croomes - does this look like it would fit your requirements?

**Comment by stuartleeks** [comment]
Thinking about this a bit more, how would this work for the config:

```json
"kubernetesConfig": {
    "kubeletConfig": {
        "--cluster-dns": "172.17.1.11",
        "--max-pods": "30",
        "--feature-gates": [ "MountPropagation=true", "TaintNodesByCondition=true"],
        <etc...>
    },
    "apiserverConfig": {
        "--storage-backend": "etcd3",
        "--feature-gates": ["MountPropagation=true"],
        <etc...>
    }
}
```

It still feels fairly simple in terms of the config, but should make the implementation quite a bit simpler (I think!)

**Comment by CecileRobertMichon** [comment]
@jackfrancis implemented the apiServerConfig interface in #2012 which was merged yesterday

**Comment by jackfrancis** [comment]
I think we can re-use the existing (since yesterday!) `apiServerConfig` implementation like this:

```
"apiserverConfig": {
    "--storage-backend": "etcd3",
    "--feature-gates": "['key1'='val','key2'='val']",
    <etc...>
}
```

In other words, `--feature-gates` would be a special property that we'd deserialize and expand as k8s runtime config separately.

My representation of JSON inside of a JSON string is crude, someone has probably solved that problem before. We should do something like that, in my view.

**Comment by stuartleeks** [comment]
Thanks @CecileRobertMichon  and @jackfrancis! I have started implementing this with the comma-separated format for now, and spotted the apiServerConfig as I was going through making the changes :-)

Once I have a version working I'll submit a PR for review and we can refine the config format along with any other changes from the review - does that sound ok?

**Comment by stuartleeks** [comment]
I was just thinking about the handling for `--feature-gates` in the `kubeletConfig` with master and agent profiles and want to get your opinions. 

As I understand the behaviour there, any value that is specified in the `masterProfile` (as an example) will be used, but if a value is absent from `masterProfile` and present in the `kubernetesConfig/kubeletConfig` then the `kubernetesConfig/kubeletConfig` value is used for the master. I.e. values are inherited unless overridden.

So in the case of the following (pseudo config)
```json

"kubernetesConfig": {
    "kubeletConfig": {
        "--dummysetting1": "shared1",
        "--dummysetting2": "shared2",
        <etc...>
    }
}
"masterProfile" : {
    "kubernetesConfig" : {
        "kubeletConfig" : {
            "--dummysetting1": "master1",
        }
}
```

the `masterProfile` that would be applied is 

```json
"masterProfile" : {
    "kubernetesConfig" : {
        "kubeletConfig" : {
            "--dummysetting1": "master1",
            "--dummysetting2": "shared2",
        }
}
```

So... for feature gates, what level should we merge at?

I.e. if our input is as below, what should the output be?

```json
"kubernetesConfig": {
    "kubeletConfig": {
        "--feature-gates": "gate1=true"
        <etc...>
    }
}
"masterProfile" : {
    "kubernetesConfig" : {
        "kubeletConfig" : {
            "--feature-gates": "gate2=true"
        }
}
```

One option is to simply override to give this effective master config:

```json
"masterProfile" : {
    "kubernetesConfig" : {
        "kubeletConfig" : {
            "--feature-gates": "gate2=true"
        }
}
```

Another option is to treat the feature gates as another level that should be merged, like the `kubeletConfig` giving this effective master config:

```json
"masterProfile" : {
    "kubernetesConfig" : {
        "kubeletConfig" : {
            "--feature-gates": "gate1=true,gate2=true"
        }
}
```

I already have the code for merging (to support adding in `Accelerators=true` for the agents), so either can easily be achieved - the question is which do you feel is right :-)

**Comment by jackfrancis** [comment]
- your description of how agent and master override config delivery is implemented is correct
- in terms of where to implement feature-gates, I think from a high level the answer is that we want the following
  - both cluster-wide and master-override use the same implementation (look for `--feature-gates` property inside `kubeletConfig` and do special deserialization)
  - cluster-wide and master-override are able to have distinct `--feature-gates` config values
  - we don't try to tackle merging/interleaving between the two
    - i.e., if cluster-wide `--feature-gates` is "A,B,C,D" and master-override is "A,B,C,D,E" then those distinct, respective values are declared comprehensively in their appropriate config interfaces
    - i.e., we don't get to say "just add 'E' to the preëxisting 'A,B,C,D' vals present in the cluster-wide config

I hope that makes sense and answers your questions!

**Comment by stuartleeks** [comment]
@jackfrancis - as the [PR](#2032 ) stands:

*  it uses the same format for kubelet, agent/master-override and apiserver. Currently I've opted for the `key1=value1,key2=value2` format that works with the `--feature-gates` switch.
* it preserves the behaviour of specifying the `Accelerators=true` feature gate on the agent nodes
* it allows feature gates to be overridden by master or agent profile, without performing any merging

**Comment by stuartleeks** [comment]
@jackfrancis can you re-open to track changes to kubernetes components (I forgot to update the PR comment to prevent the issue being auto-closed)!

**Comment by jackfrancis** [comment]
Done.

**Comment by campbelldgunn** [comment]
@jackfrancis Please when considering `--feature-gates` to include `CoreDNS=true` as I am fighting with addon manager cannot get rid of `Kube-DNS`.

**Comment by jackfrancis** [comment]
@campbelldgunn the `--feature-gates` option is wide open (with a few exceptions): you should be able to specify that key/val pair in your api model when building a cluster.
