### ISSUE TITLE
acs-engine deploy not validating orchestrator version properly

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/acs-engine#2025]
**Is this a request for help?**:  yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):  ISSUE
---

**What version of acs-engine?**:
 0.11.0, 0.10.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
1.9

**What happened**:
There might be two separate issues; however, they manifest themselves together:
* If I attempt to generate a 1.9 cluster, JSON validation fails
* If I attempt to deploy a 1.9 K8S Cluster, I get a 1.7 cluster

If I attempt to generate an 1.9 K8S cluster, I get:

```
•100% ➜ acs-engine generate --api-model kubernetes1.9-issue.json
INFO[0000] Error returned by LoadContainerService: OrchestratorProfile is not able to be rationalized, check supported Release or Version
FATA[0000] error validating generateCmd: error parsing the api model: OrchestratorProfile is not able to be rationalized, check supported Release or Version


•100% ➜ cat kubernetes1.9-issue.json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.9"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "sandbox-acs-engine-19",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

```

If I try to deploy this cluster, it will allow it; however, it will create a Kubernetes 1.7 cluster.

**What you expected to happen**:

I would expect the generate run to pass with a simple 1.9 cluster
I would expect the deploy run to deploy a K8S 1.9 cluster (instead of a 1.7 cluster)

**How to reproduce it** (as minimally and precisely as possible):

Use this as a base:
https://github.com/Azure/acs-engine/blob/master/examples/kubernetes-releases/kubernetes1.9.json

Run:
```
acs-engine deploy --api-model kubernetes1.9-issue.json --location southcentralus --subscription-id <your sub here> --resource-group sandbox-acs-engine
INFO[0017] Starting ARM Deployment (sandbox-acs-engine-1341619957). This will take some time...
INFO[0467] Finished ARM Deployment (sandbox-acs-engine-1341619957).
ssh <ip>
thfalgou@k8s-master-18220585-0:~$ kubectl version
2018-01-10 18:08:51.762208 I | proto: duplicate proto type registered: google.protobuf.Any
2018-01-10 18:08:51.762268 I | proto: duplicate proto type registered: google.protobuf.Duration
2018-01-10 18:08:51.762419 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
And 
**Anything else we need to know**:

**Comment by jackfrancis** [comment]
`v0.11.0` doesn't support `v1.9.n` of Kubernetes. We expect to release `v0.12.0` this week which (as of this writing) supports `v1.9.1`.

I'm going to quickly investiagte the `acs-engine deploy` behavior, which doesn't make sense as you stated (it should fail an api model that declares an unsupported version).

**Comment by jackfrancis** [comment]
I can reproduce this error. Succinctly:

`acs-engine deploy` should fail in the same way as `acs-engine generate` when an unsupported version is included in the api model. It's possible this is a symptom of a larger bug that permits validation failures (or skips validation entirely) during the `deploy` execution flow.

Thanks for reporting @lastcoolnameleft !

**Comment by lastcoolnameleft** [comment]
Phew.  Glad it's not just me and I'm not going crazy.  I "thought" I deployed a 1.9 cluster cluster, and when newer primitives didn't work as expected, I got really confused until I checked the version of the nodes.  Reproduced the error 2x more times, just to make sure.

**Comment by 4c74356b41** [comment]
You just need to compile latest code, i deployed 1.9 just today with acs engine.
