### ISSUE TITLE
K8s cluster upgrade from 1.8.2 to 1.8.6 fails

### ISSUE THREAD

**Issue by dtzar** [Azure/acs-engine#2029]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
git [commit 8fd4ac4](https://github.com/Azure/acs-engine/commit/8fd4ac4267c29370091d98d80c3046bed517dd8c)

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Run the K8s upgrade steps per [the bottom example here](https://github.com/Azure/acs-engine/tree/master/examples/k8s-upgrade). Going from an ACS-Engine provisioned cluster on 1.8.2 desiring to migrate to a 1.8.6 cluster.  It spits out this error:
```
INFO[0000] validating...
INFO[0002] Error returned by LoadContainerService: Unknown JSON tag nodeStatusUpdateFrequency
FATA[0002] error parsing the api model: Unknown JSON tag nodeStatusUpdateFrequency
```

If I revert to the [0.11.0 binary release](https://github.com/Azure/acs-engine/tree/v0.11.0
) and try to do the same upgrade to the supported 1.8.4, I get this error trying to upgrade:
```
INFO[0000] validating...
INFO[0002] Error returned by LoadContainerService: Unknown JSON tag tillerMemoryRequests
FATA[0002] error parsing the api model: Unknown JSON tag tillerMemoryRequests
```

**What you expected to happen**:
acs-engine upgrades the cluster to 1.8.6

**How to reproduce it** (as minimally and precisely as possible):
Pretty sure this should be very easy to reproduce for any cluster provisioned prior to PR 1854 using an acs-engine binary after that PR.  I think that the upgrades broke once you merged this PR https://github.com/Azure/acs-engine/pull/1854 which removed the nodeStatusUpdateFrequency and two other properties.

**Comment by jackfrancis** [comment]
Hi @dtzar! We merged changes this week that moved some properties into a more generic interface.

If you paste the api model that produced those errors I'll try to give you the newer, more generic version. (Btw this breakage was expected and there will be thorough notes in the next release :))

**Comment by dtzar** [comment]
Thanks for the quick response @jackfrancis! Here is my API model:
Would appreciate giving me the newer more generic version which will allow me to upgrade the cluster. :)

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "orchestratorVersion": "1.8.2",
      "kubernetesConfig": {
        "kubernetesImageBase": "gcrio.azureedge.net/google_containers/",
        "clusterSubnet": "10.244.0.0/16",
        "dnsServiceIP": "10.0.0.10",
        "serviceCidr": "10.0.0.0/16",
        "networkPolicy": "none",
        "nonMasqueradeCidr": "10.0.0.0/8",
        "maxPods": 110,
        "dockerBridgeSubnet": "172.17.0.1/16",
        "nodeStatusUpdateFrequency": "10s",
        "ctrlMgrNodeMonitorGracePeriod": "40s",
        "ctrlMgrPodEvictionTimeout": "5m0s",
        "ctrlMgrRouteReconciliationPeriod": "10s",
        "enableRbac": true,
        "gchighthreshold": 85,
        "gclowthreshold": 80,
        "etcdVersion": "2.5.2",
        "tillerCPURequests": "50m",
        "tillerCPULimit": "50m",
        "tillerMemoryRequests": "150Mi",
        "tillerMemoryLimit": "150Mi"
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "REDACTED",
      "vmSize": "Standard_DS2_v2",
      "firstConsecutiveStaticIP": "10.240.255.5",
      "storageProfile": "ManagedDisks",
      "oauthEnabled": false,
      "preProvisionExtension": null,
      "extensions": [],
      "distro": "ubuntu"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "osType": "Linux",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "distro": "ubuntu",
        "fqdn": "",
        "preProvisionExtension": null,
        "extensions": []
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "REDACTED"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
REDACTED    },
    "certificateProfile": {
 REDACTED   }
  }
}
```

**Comment by dtzar** [comment]
Looks like this is covered in #2062.  Although this isn't resolved, I'm going to close it out due to the known problem and workarounds presented there.
