### ISSUE TITLE
No internet on agents\pods, kubernetes 1.9.1

### ISSUE THREAD

**Issue by 4c74356b41** [Azure/acs-engine#2045]
---
ISSUE
---
**What version of acs-engine?**:
```
Version: canary
GitCommit: 1b48407
GitTreeState: clean
```
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.1, used this template to generate deployment:
```
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.9"
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "k8s-19",
            "vmSize": "Standard_DS2_v2"
        },
        "agentPoolProfiles": [
            {
                "name": "winpul",
                "count": 2,
                "vmSize": "Standard_DS2_v2",
                "availabilityProfile": "AvailabilitySet",
                "osType": "Windows"
            }
        ],
        "windowsProfile": {
            "adminUsername": "username",
            "adminPassword": "password"
        },
        "linuxProfile": {
            "adminUsername": "username",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": "ssh-rsa data"
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "xxx",
            "secret": "yyy"
        }
    }
}
```
**What happened**:
No internet on agent nodes, no internet on pods

**What you expected to happen**:
Internet on agent nodes, internet on pods

**How to reproduce it** (as minimally and precisely as possible):
build acs engine from the same commit, run `./acs-engine generate` pointing to my template.

**Anything else we need to know**:
I've observed similar behavior on 1.7.9 and 1.8.1 (both **created by ACS, not ACS engine**). I didnt edit\configure the deployment files before deploying them nor did I change anything that got deployed. The load balancer looks to be configured properly (i can get to my service from outsire), but there is no outbound connectivity on the nodes. Firewall is off on both nodes. If I attach public IP to the nodes internet starts to work on the nodes, doesnt work on containers though. Internet on docker containers works (after attaching public ip).

**Comment by ermontgo** [comment]
I'm seeing the same issue with both 1.9 and 1.7 kubernetes versions, ACS-Engine version Version: v0.12.1
GitCommit: 93589b42
GitTreeState: clean

**Comment by ermontgo** [comment]
I also see this issue with ACS-Engine version 0.12.5

**Comment by msorby** [comment]
Been trying to figure this out, but getting no where.

So I went back tp acs-enging 0.6.0 and Kubernetes 1.6.9, using the same source json and now my windows container have internet access.
So either something happened with acs-enging/kuberentes between then and now, or it's a Windows issu, since kubernetes 1.9.x is using 1709 windows image.

Would love to have this sorted our for Kubernetes 1.9.x

> {
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorVersion": "1.6.9"
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "some-name",
        "vmSize": "Standard_D3_v2",
        "storageProfile": "StorageAccount"
      },
      "agentPoolProfiles": [
        {
          "name": "windowspool2",
          "count": 1,
          "vmSize": "Standard_D3_v2",
          "availabilityProfile": "AvailabilitySet",
          "osType": "Windows"          
        }
      ],
      "windowsProfile": {
        "adminUsername": "",
        "adminPassword": ""
      },
      "linuxProfile": {
        "adminUsername": "",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "ssh-rsa..."
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId": "",
        "secret": ""
      }
    }
  }

Regards,
Morten

**Comment by 4c74356b41** [comment]
@msorby https://github.com/Azure/acs-engine/issues/2027#issuecomment-365154472

**Comment by 4c74356b41** [comment]
@ermontgo forgot to add you
