### ISSUE TITLE
DNS problems from within container on AzureGermanCloud with multi-agent-k8s

### ISSUE THREAD

**Issue by ITler** [Azure/acs-engine#2046]
**Is this a request for help?**:
no, bug
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
0.10.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8s Server 1.7.9, 1.8.4 kubectl: 1.8.5, 1.9.1

**What happened**:
Deploying a fresh K8s cluster on **AzureGermanCloud** shows DNS issues from within containers. Seems independent to pod's/container's internal Linux (issue seen with Debian, Ubuntu, Alpine). Should be reproducible with any kind of app image, I can with my own image and public nginx image.
Issue occurrence is dependent from k8s cluster setup, like this:

1 master, 1 agent: no problem
3 masters, 1 agent: no problem
3 masters, **3 agents**: problem occurs
1 master, **3 agents**: problem occurs

I always tear down whole cluster deployment and set up a fresh one, so should be isolated test environment and no interference.

**What you expected to happen**:
No DNS issues when using more than 1 k8s agent node:)

**How to reproduce it** (as minimally and precisely as possible):
```
{
  "apiVersion": "vlabs",
  "location": "germanycentral",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "orchestratorVersion": "1.8.4"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "test",
      "vmSize": "${vm_size_master}",
      "vnetSubnetId": "${subnet_id}", #172.29.2.0/23 same range as vnet
      "firstConsecutiveStaticIP": "172.29.3.240"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "${vm_size}",
        "vnetSubnetId": "${subnet_id}", #172.29.2.0/23 same range as vnet
		"storageProfile" : "ManagedDisks",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "${admin_user}",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "${ssh_pkey}"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientID": "${service_principle_client_id}",
      "secret": "${service_principle_client_secret}"
    }
  }
}

```

**Anything else we need to know**:
Please pay attention to my **network** (vnet and subnet) **range limitation**. Maybe this causes issues somehow.
I started investigating logs on master, seeing, that `kube-scheduler.log` says, that etcd cluster have no leader. When directly checking with `etcd-cluster cluster-health` (or so), it reports healthy.
We use same K8s version on AWS with multi-agent-cluster, we don't have issues, so I strongly assume, that this problem relates to AzureGermanCloud

**Comment by ITler** [comment]
I close this, as, at the moment, I'm pretty sure that this has something to do with K8s itself, rather than with acs-engine. I would reopen this, if I feel it is appropriate.

Bug reported at kubernetes GitHub repo https://github.com/kubernetes/kubernetes/issues/58290

**Comment by ITler** [comment]
I need to reopen that issue, as I finally could figure out a difference with deployed resources by `acs-engine`. 

v0.9.3 works with **`AzureGermanCloud`** and **`AzureCloud`**
v0.10.0 works only with **`AzureCloud`**
v0.12.0 works with none of them

So `acs-engine` deployment does not create master `route table` resource anymore.
It looks like that (created with `v0.10.0`@ public `AzureCloud`):

```
{
            "comments": "Generalized from resource: '/subscriptions/8dbf8c14-a8cb-4bc6-af5d-911a11a1b302/resourceGroups/k8s-westeurope_cross/providers/Microsoft.Network/routeTables/k8s-master-11974821-routetable'.",
            "type": "Microsoft.Network/routeTables",
            "name": "[parameters('routeTables_k8s_master_11974821_routetable_name')]",
            "apiVersion": "2017-06-01",
            "location": "westeurope",
            "scale": null,
            "properties": {
                "provisioningState": "Succeeded",
                "routes": [
                    {
                        "name": "k8s-master-11974821-0",
                        "etag": "W/\"6f819301-b396-4e19-9a49-1076a3303dac\"",
                        "properties": {
                            "provisioningState": "Succeeded",
                            "addressPrefix": "10.244.0.0/24",
                            "nextHopType": "VirtualAppliance",
                            "nextHopIpAddress": "172.29.3.240"
                        }
                    },
                    {
                        "name": "k8s-agentpool1-11974821-0",
                        "etag": "W/\"6f819301-b396-4e19-9a49-1076a3303dac\"",
                        "properties": {
                            "provisioningState": "Succeeded",
                            "addressPrefix": "10.244.1.0/24",
                            "nextHopType": "VirtualAppliance",
                            "nextHopIpAddress": "172.29.2.4"
                        }
                    },
                    {
                        "name": "k8s-agentpool1-11974821-1",
                        "etag": "W/\"6f819301-b396-4e19-9a49-1076a3303dac\"",
                        "properties": {
                            "provisioningState": "Succeeded",
                            "addressPrefix": "10.244.2.0/24",
                            "nextHopType": "VirtualAppliance",
                            "nextHopIpAddress": "172.29.2.5"
                        }
                    }
                ]
            },
            "dependsOn": []
        }
```

**Comment by okke-formsma** [comment]
The default provisioning system has changed from 'none' to 'cni'. Also see https://github.com/Azure/acs-engine/tree/master/examples/networkpolicy

Setting your properties.orchestratorProfile.kubernetesConfig.networkPolicy to 'none' will yield a route table resource again.

**Comment by ITler** [comment]
Cheers, seem to work ... didn't see that doc.
Thank you
