### ISSUE TITLE
Master internal load balancer does not utilise health probe - Azure

### ISSUE THREAD

**Issue by marty2bell** [Azure/acs-engine#2051]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: 0.10.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
The internal master load balancer has a health probe defined but it is not used on the internal load balancer rule.  If you are querying kubernetes from an agent pod and a master node goes down then you can still get re-directed to the missing node. 

**What you expected to happen**:

Bringing a master node down does not cause any exceptions when there are multiple nodes.

**How to reproduce it** (as minimally and precisely as possible):

create a cluster with multiple master nodes and setup the agents so that they can query the masters, for example https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

Create a pod that queries the master nodes for sat pod status and then stop a master node.  You should eventually get a failed response.

**Anything else we need to know**:

**Comment by SuperMarioo** [comment]
I'm having the same problem , is there a way to manual fix it ?

**Comment by dennis-benzinger-hybris** [comment]
I don't have a cluster at hand to test with so take the following with a grain of salt :-).

1. Open the load balancer in the azure portal
2. Go to "Load balancing rules"
3. See that the rule has no information in the "Health Probe" column.
4. Open the rule
5. Choose the already existing health probe in field "Health probe".
6. Save and wait a minute for the change to apply.

You could also script this with the `az` command line client.

**Comment by SuperMarioo** [comment]
Thanks , I have fixed ARM Template to include health probe in the rule . 

The need to fix it in Acs-engine .
