### ISSUE TITLE
acs-engine 0.12.x release date?

### ISSUE THREAD

**Issue by mcops** [Azure/acs-engine#2053]
When will be the next release candidate of ACS-engine, because we highly depend on k8s 1.8.6 on azure to be able to use properly the azurefile storage driver and correct parsing of mount options.

Thanks!

**Comment by CecileRobertMichon** [comment]
Hi @mcops, we expect to release v0.12.0 in the next couple of days, hopefully tomorrow.

**Comment by CecileRobertMichon** [comment]
v0.12.0 was released earlier today, closing this issue.
