### ISSUE TITLE
Unable to deploy Kubernetes cluster to existing VNet

### ISSUE THREAD

**Issue by dmorgan-github** [Azure/acs-engine#2057]
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

HEAD

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

Deployment failed. Correlation ID: a35dedad-094c-4897-a311-2857581c00c8. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse1'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=5\n[stdout]\n\n[stderr]\nstat: cannot stat '/opt/azure/containers/provision.complete': No such file or directory\n\"."
      }
    ]
  }
}

**What you expected to happen**:
Cluster deployed in existing VNet

**How to reproduce it** (as minimally and precisely as possible):

1) Create VNet

2) Create subnets

2) build acs-engine according to instructions found here:
https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md

3) Generate ARM templates:
./bin/acs-engine generate config.json
see config.json below.

4) create cluster
az group deployment create -g RES_GROUP --name "ClusterDeployment" --template-file azuredeploy.json --parameters "@azuredeploy.parameters.json"

config.json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "test123",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/SUB_ID/resourceGroups/RES_GROUP_ID/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME",
      "firstConsecutiveStaticIP": "10.1.3.5" 
    },
    "agentPoolProfiles": [
      {
        "name": "agentprivate",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/SUB_ID/resourceGroups/RES_GROUP_ID/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa ... your_email@example.com"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "CLIENT_ID",
      "secret": "PASSWORD"
    }
  }
}

**Anything else we need to know**:

**Comment by ducas** [comment]
I’m having the same issue. Pretty much exact json input and using “the long way” too. I tried specifying orchestratorRelease as “1.9” based on #1806, but no luck.

**Comment by dougmacqueen** [comment]
Try adding vnetCidr into the masterProfile section with your master subnet cidr. From memory i had a similar issue and found that the subnet was used in the provisioning scripts and was required.

**Comment by dmorgan-github** [comment]
Never resolved. We decided to abandon the unmanaged container service. Eventually we abandoned azure itself. Went with AWS.

**Comment by ashvindeodhar** [comment]
@CecileRobertMichon Is there any workaround / solution for this? I am hitting this issue:


        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=4\n[stdout]\n\n[stderr]\n\"."

**Comment by CecileRobertMichon** [comment]
@ashvindeodhar a lot has changed since this issue was opened. Could please follow the steps in https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/troubleshooting.md#vmextensionprovisioningerror-or-vmextensionprovisioningtimeout and open a new issue? I'll close this one.

**Comment by ashvindeodhar** [comment]
@CecileRobertMichon - opened a new issue: https://github.com/Azure/acs-engine/issues/3730
