### ISSUE TITLE
K8s upgrade error when using RBAC and AAD

### ISSUE THREAD

**Issue by emondek** [Azure/acs-engine#2061]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

0.11.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.8.2

**What happened**:

1. Used acs-engine v0.11.0 to deploy a K8s v1.8.2 cluster with RBAC enabled
2. The cluster has 3 masters and 3 agents
3. Run the following command to upgrade the cluster to 1.8.4:

acs-engine upgrade --deployment-dir _output/edsk8s02/ --location northcentralus --resource-group K8s03 --subscription-id <sub-id> --upgrade-version 1.8.4 --auth-method client_secret --client-id <client-id> --client-secret <client-secret>

After completing the upgrade of the first master, the following error is thrown and the upgrade stops:

INFO[0527] Error validating upgraded master VM: k8s-master-16424874-0 
FATA[0527] Error upgrading cluster: No Auth Provider found for name "azure" 

Running 'kubectl get nodes' shows:

NAME                        STATUS    ROLES     AGE       VERSION
k8s-agentpri01-16424874-0   Ready     agent     26m       v1.8.2
k8s-agentpri01-16424874-1   Ready     agent     26m       v1.8.2
k8s-agentpri01-16424874-2   Ready     agent     26m       v1.8.2
k8s-master-16424874-0       Ready     master    15m       v1.8.4
k8s-master-16424874-1       Ready     master    26m       v1.8.2
k8s-master-16424874-2       Ready     master    26m       v1.8.2

So, the first master does get upgraded and looks healthy but the upgrade stops.

**What you expected to happen**:
Expect all of the masters and agents to get upgraded.

**How to reproduce it** (as minimally and precisely as possible):
Steps listed above.

**Anything else we need to know**:
The same error gets thrown when using 'acs-engine upgrade --auth-method device'

**Comment by rahulbasmanghi** [comment]
Same issue while trying to work with Acs-engine v1.8.9->1.8.10 upgrade

**Comment by syeditron** [comment]
I am trying to upgrade from orchestration version 1.8.2 to 1.9.4 with RBAC enabled and it seems to fail with the same error message No Auth Provider found for name "azure"

**Comment by jackfrancis** [comment]
@EPinci would you be able to recreate your test against this PR:

https://github.com/Azure/acs-engine/pull/2650

If the "check for all nodes ready" CSE test is flaky in upgrade/scale situations, we should rethink this. The above prototype PR effectively removes that check (the longer term idea is that we would make that check configurable, say, for testing/debugging).

**Comment by pontusarfwedson** [comment]
Just for input, the upgrade func will add "extra" nodes so the total number of nodes a lot of the time differ from the actual desired number of nodes. Do not have any more specifics but I noticed that behaviour running the upgrade (or upgrades) yesterday.

**Comment by pontusarfwedson** [comment]
@EPinci What log-file would that output end up in? Looking in `var/log/azure/cluster-provision.log` doesn't give me any of that output.

**Comment by EPinci** [comment]
@pontusarfwedson Actually, that was the log file. Probably you're not in case like mine where the node count of the agents changed after the initial deployment and not due to ACS-Engine scaling.

I was able, however, to run your changes and your workaround for the azure provider actually works while waiting for the official one - it complains about reregistration after the first node, but, hey, I can live with that… :).
That check wouldn't run on agent nodes but upgrades start with masters and the overall node count is still different so I immediately bump into this and I'm trying to leverage #2650 to fix this as well.

**Comment by pontusarfwedson** [comment]
Yeah, I feel we can live with that as well ;) But did you get the long timeouts when running my stuff? Since the agent nodes don't even run `ensureK8s` that cannot be the case for those :)

**Comment by pontusarfwedson** [comment]
And another FYI, tried to use the `scale` functionality on an existing cluster which caused the master nodes to change their IP addresses which messes up a bunch of stuff including etcd .. Currently trying to resolve.

**Comment by EPinci** [comment]
@pontusarfwedson I'm seeing strange things as well, even during upgrades the number of IP addresses allocated per node jumped from 30 to 111 (and then breaking up things).

**Comment by pontusarfwedson** [comment]
@EPinci You were not able to perform an upgrade successfully? Have to look into that, just saw that one of our major pods were in `CrashLoopBackoff`.
