### ISSUE TITLE
Scale up deletes subnets

### ISSUE THREAD

**Issue by itowlson** [Azure/acs-engine#2063]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: Whatever is currently used by the Azure CLI (2.0.23) / REST API

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**:  Kubernetes, default version

**What happened**: When I scaled up the agent pool, it deleted a subnet I had added to the cluster vnet.  (Scaling _down_ the agent pool did _not_ affect the subnet,)  If it can't delete the subnet, the scale operation fails.

**What you expected to happen**: That my subnet would not be affected by agent pool scaling

**How to reproduce it** (as minimally and precisely as possible):

1. Create an ACS Kubernetes cluster using Azure CLI 2.0.23.
2. View the resource group in the Azure portal.
3. Select the vnet created for the cluster (k8s-vnet-xxxxxxxx).
4. Add a subnet named `test-subnet` to this vnet.
5. Return to the resource group and select the container service.
6. Select `Agents` and increase the agent pool size from 3 to 4.
7. Wait for the resize to complete.
8. Select the vnet again and view its subnets.
9. Note that `test-subnet` no longer exists.

**Anything else we need to know**: You can also try adding a public IP to the custom subnet.  Your scale up operation will then fail because it can't delete the subnet while it's in use.

**Comment by itowlson** [comment]
Verified that this happens when I provision and scale a cluster at the `acs-engine` level too.

**Comment by itowlson** [comment]
Looks like scaling down just deletes agent VMs, but scaling up redeploys the entire ARM template, including the VNET.  Could `transformer.NormalizeForK8sVMASScaling` remove the VNET declaration?  We would need to remove both the declaration itself and any depends-on statements that referred to it.

Do we see any safety issues with this?

**Comment by jackfrancis** [comment]
@JackQuincy can you confirm that this behavior should not occur? (Also, if you suspect/have an opinion that this behavior is a side-effect of the current scale implementation, that would be awesome too!)
