### ISSUE TITLE
acs-engine 0.12 - issues with upgrade

### ISSUE THREAD

**Issue by mcops** [Azure/acs-engine#2069]
**currrent deployed azure acs kubernetes release: 1.8.4

**seems  upgrade command is kind of broken, or something changed in the api model, concerning my previous json file (besides several parameters which are not anymore supported) - I do get this error:
(already tried upgrade version 1.8.6, same error)

acs-engine-v0.12.0-windows-amd64>acs-engine.exe upgrade --subscription-id XXXXXX --resource-group RG-XXX-EU-XXX --upgrade-version 1.9.1 --location westeurope --deployment-dir _output\xxx-prod --auth-method client_secret --client-id XXXXXX --client-secret XXXXX
[36mINFO[0m[0000] validating...
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/Azure/acs-engine/cmd.(*upgradeCmd).validate(0xc04206db80, 0xc042540480, 0xc04237a600, 0x0, 0x10)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/upgrade.go:173 +0xd68
github.com/Azure/acs-engine/cmd.(*upgradeCmd).run(0xc04206db80, 0xc042540480, 0xc04237a600, 0x0, 0x10, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/upgrade.go:188 +0x7e
github.com/Azure/acs-engine/cmd.newUpgradeCmd.func1(0xc042540480, 0xc04237a600, 0x0, 0x10, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/upgrade.go:57 +0x59
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc042540480, 0xc04237a400, 0x10, 0x10, 0xc042540480, 0xc04237a400)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:647 +0x3ff
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042549440, 0xc042549d40, 0xc042549b00, 0xc042549680)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:726 +0x340
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042549440, 0xc0425c5f68, 0x148238c)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:685 +0x32
main.main()
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/main.go:9 +0x36

**Comment by CecileRobertMichon** [comment]
Hi @mcops, are you trying to upgrade a pre-existing cluster? If so, please see #2062

**Comment by CecileRobertMichon** [comment]
@mcops what version of acs-engine did you build your cluster with? Did you manually change anything in the apimodel before running the upgrade command? I am trying to reproduce your error but I am not able to get the same error.

**Comment by mcops** [comment]
coming from 0.10 release.

**Comment by CecileRobertMichon** [comment]
I am still unable to reproduce, how many masters are there in your cluster? Did you change anything in the apimodel.json file before running upgrade?

**Comment by mcops** [comment]
yes, I'd to adjust apimodel, because several parameters aren't supported. So I'll have a look that I don't have any typo in the json.

**Comment by gsacavdm** [comment]
I'm having the same problem (with the same exact error message) when trying to upgrade a 1.7.9 cluster that was created with acs-engine v12.0.4.

I haven't tinkered with apimodel.json at all. it's the same one that was used to create the cluster 3 days ago.

**Comment by CecileRobertMichon** [comment]
@mcops was this issue resolved?
