### ISSUE TITLE
acs-engine 'upgrade' did not grab new Ubuntu OS image

### ISSUE THREAD

**Issue by bq1756** [Azure/acs-engine#2075]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
v0.11
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.2 - 1.8.4

**What happened**:
Deployed a brand new test cluster on k8s 1.7.2.  The node OS images are vulnerable to Meltdown-Spectre.
Manually altered /_output/*.json to "osImageVersion" = "16.04.201801120".
Upgraded the cluster to 1.8.4 with acs-engine.exe 'upgrade' command.
After 'upgrade' command completed, the nodes are still vulnerable to Meltdown-Spectre (kernel 4.13 deployed).

**What you expected to happen**:
I was hoping acs-engine would request newer osImageVersions.

**How to reproduce it** (as minimally and precisely as possible):
  acs-engine.exe generate acs-engine-template.json
  az group deployment create -plus more parameters- 
  Manually replace osImageVersion values in master and agent sections of _output/azuredeploy.json and _output/azuredeploy.parameters.json.
 acs-engine.exe upgrade -plus more parameters-

**Anything else we need to know**:
Bottom line.  I want to secure production k8s nodes against Meltdown-Spectre.  It would be great if I can upgrade to k8s 1.8.4 at the same time.

**Comment by gsacavdm** [comment]
+1, I ran acs-engine generate, then modified the _output folder's azuredeploy.parameters.json and ran acs-engine deploy / upgrade / scale and my parameters were ignored.
