### ISSUE TITLE
How to change VM sizes of agents in Azure

### ISSUE THREAD

**Issue by bq1756** [Azure/acs-engine#2076]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
v0.11
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.2

**What happened**:
Nothing yet.  I want to replace the Azure VM sizes of my k8s agent nodes from basic D-series to larger Dv3-series on a k8s cluster running production workloads.  How can I accomplish this task without completely rebuilding the cluster?

**What you expected to happen**:
I want to change the Azure VM size of my k8s agent nodes with a simple command and perhaps some manual config file changes.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by bq1756** [comment]
I plan to test the following procedure:
Create an additional node pool, using desired VM size
Migrate workload to new node pool
Figure out a way to delete a node pool in a way that keeps acs-engine working for future scale/upgrade activities

**Comment by yuedai** [comment]
I think you can kubectl drain a node, change its sku and kubectl uncordon the node back.

**Comment by giorgited** [comment]
I think this is a duplicate of #1370

**Comment by bq1756** [comment]
This ticket is a partial duplicate of #1370.  The workaround described in #1370 is limited.  With this approach, I cannot use my desired VM size.  I am limited to which VM sizes I can use based on the VM size that is currently running in the agent pool.
The approach described here in #2076 should enables me to create an entirely new agent pool so I can use any size VM I desire.  The problem with this approach is that I cannot decommission the original (now containing undesirable VM size) agent pool.  I opened #2278 to address this problem.

**Comment by bq1756** [comment]
This issue is covered by #1370 and #2278.
