### ISSUE TITLE
etcd certs deployed as Root user preventing etcd from starting.

### ISSUE THREAD

**Issue by twittyc** [Azure/acs-engine#2077]
**Is this a request for help?**: YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: v0.12

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.9

**What happened**: etcd certs are being deployed to the masters as user root. etcd is configured to run as user etcd. This prevents etcd from reading the certs and starting.

**What you expected to happen**: etcd certs should be owned by user etcd. This would allow etcd to start.

**Comment by CecileRobertMichon** [comment]
Hi @twittyc. Thanks for reporting! I am trying to reproduce what you are describing but etcd is starting correctly for me. What template are you using? What does `systemclt status etcd` show?

**Comment by twittyc** [comment]
Hi @CecileRobertMichon thanks for the reply. It seems it was a botched deployment I haven't been able to reproduce the issue again.
