### ISSUE TITLE
kubectl should be extracted from the hyperkube image

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#208]
Say you're working with or testing managed disks. It's vital the kubectl is at the exact same revision as the running apiserver.

If we would extract `hyperkube` (and thus `kubectl)` from the container, we could place that on host. We'd also get to eliminate the extra `kubectlVersion` parameter/variable we have now.

**Comment by colemickens** [comment]
Should be possible to do this with something roughly like: `docker run <hyperkube_spec> -v /usr/local/bin:/host cp /hyperkube /host/hyperkube && hyperkube --symlinks`

**Comment by khenidak** [comment]
Thinking out loud: 

We need to stream line the entire process. This will happen not only during testing beta feature (similar to md) but also when people upgrade cluster to versions that will break existing kubectl. maybe we can create a script toolkit as docker image that has bunch of scripts, one of them can extract kubectl from hyperkube spec. Also consider the reverse, upgrade something opps, now i want my old kubectl back.

**Comment by anhowe** [comment]
Closing this P2 as it is nice to have, but can be currently solved in alternate ways.  We can consider re-opening if we get requests for this.
