### ISSUE TITLE
0.12; container nameservers not using dnsServiceIP

### ISSUE THREAD

**Issue by okke-formsma** [Azure/acs-engine#2082]
ISSUE
---
**What version of acs-engine?**:
Version: v0.12.0
GitCommit: 1d332296
GitTreeState: clean
---
**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
My pods are unable to reach DNS. It seems the wrong nameserver is specified in /etc/resolv.conf.

```
/ # more /etc/resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local <snip>
options ndots:5
```

I set the api-model configuration dnsServiceIp to 10.48.0.10, but this is not applied to resolv.conf.

**What you expected to happen**:
I would expect the correct /etc/resolv.conf setting for my pods.

**How to reproduce it** (as minimally and precisely as possible):
Deployed a kubernetes cluster using acs-engine 0.12 on a specified subnet using an internal clusterSubnet.

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.9",
      "kubernetesConfig": {
        "networkPolicy": "none",
        "clusterSubnet": "10.50.0.0/16",
        "dnsServiceIP": "10.48.0.10",
        "serviceCidr": "10.48.0.0/16"
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_A2_v2",
      "vnetSubnetId": "/subscriptions/xxx/resourceGroups/main/providers/Microsoft.Network/virtualNetworks/main-vnet/subnets/K8S-MASTER",
      "firstConsecutiveStaticIP": "10.1.16.240",
      "vnetCidr": "10.1.16.0/24"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_A4_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/xxx/resourceGroups/main/providers/Microsoft.Network/virtualNetworks/main-vnet/subnets/K8S-AGENTS"
      }
    ]
```

Set up routing between the subnets using the route-table tricks similar to

```
    $ RT=$(az network route-table list -g k8s | jq -r '.[].id')
    $ az network vnet subnet update -n K8S-AGENTS -g main --vnet-name main-vnet --route-table $RT
    $ az network vnet subnet update -n K8S-MASTER -g main --vnet-name main-vnet --route-table $RT   
```

Set up `ip-masq-agent` to enable nonMasqueradeCIDR 10.48.0.0/12.

**Comment by tesharp** [comment]
I submitted a pull request to fix this issue yesterday: https://github.com/Azure/acs-engine/pull/2078

**Comment by okke-formsma** [comment]
Fixed by https://github.com/Azure/acs-engine/pull/2078
