### ISSUE TITLE
`hyperkubeSpec` should be adjustable from the apimodel

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#209]
We probably don't want this is Azure Container Service proper (unless we want to offer "unsupported" deployments inside ACS...), but it would be really great to have for development scenarios.

We could also document the e2e process for building custom builds of kubernetes and deploying them with ACS-Engine. It makes a nice workflow.

**Comment by anhowe** [comment]
This can be done in parameters.

However, I really like the idea of documenting how to use this for kubernetes development, especially for how to build your own cluster, created from your own kubernetes.

**Comment by jackfrancis** [comment]
yay done in #1005
