### ISSUE TITLE
Unable to delete statefulset in Kubernetes 1.9.1

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/acs-engine#2110]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.12.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.1

**What happened**:
Unable to delete statefulset. Error: **no kind "GetOptions" is registered for version "apps/v1"**

**What you expected to happen**:
Delete statefulset using kubectl delete -f statefulset.yml

**How to reproduce it** (as minimally and precisely as possible):
Create a statefulset using the template from the [kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/). Change the storage class to managed-premium. Try to delete it using kubectl delete -f statefulset.yml

**Anything else we need to know**:

**Comment by feiskyer** [comment]
@IvanovOleg have you also upgraded kubectl?

**Comment by IvanovOleg** [comment]
@feiskyer no, I forgot. Sorry
