### ISSUE TITLE
Enable OIDC options as user-configurable

### ISSUE THREAD

**Issue by mwieczorek** [Azure/acs-engine#2112]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
0.12.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

According to https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md 
OIDC options (--oidc-username-claim, --oidc-groups-claim, --oidc-client-id, --oidc-issuer-url) for apiserver config 

> are not currently user-configurable, either because a higher order configuration vector is available that enforces kubelet configuration, or because a static configuration is required to build a functional cluster

Is it possible to change that and make them user-configurable?
Possible use case is if I don't want to use AAD but f.e. [dex](https://github.com/coreos/dex) instead.
I know that it's related to AADProfile, and of course in case AADProfile is set it could take precedence.

**Comment by mwieczorek** [comment]
Hi, any thoughts about this? I'm just asking if you would consider such change and eventually PR?

**Comment by mwieczorek** [comment]
@CecileRobertMichon @jackfrancis sorry to bother you directly, but could you please take a look and write what do you think?

**Comment by mwieczorek** [comment]
Trying to gain attention once again :)
@jackfrancis @CecileRobertMichon

**Comment by jackfrancis** [comment]
Thanks for your patience, @mwieczorek, this PR (merged) actually addressed some of the above properties:

https://github.com/Azure/acs-engine/commit/975170552e5442b8702831d0d7fedbd3078f3a02

I'd be happy to move over the remaining. What are your thoughts on the current state of these properties in master?

**Comment by mwieczorek** [comment]
@jackfrancis 
I haven't seen #2528 yet. Great, so I need just two more: --oidc-client-id, --oidc-issuer-url.

**Comment by mwieczorek** [comment]
@jackfrancis 
I've seen #2528 is released (https://github.com/Azure/acs-engine/releases/tag/v0.15.0).
I'll be happy if the second part (--oidc-client-id, --oidc-issuer-url) ships in v0.16.0 :)
