### ISSUE TITLE
HPA Autoscaling in v1.9.n clusters

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#2114]
Auto-scaling isn't working in our v1.9 clusters using the vanilla demo here:

http://blog.kubernetes.io/2016/07/autoscaling-in-kubernetes.html

At a minimum, it looks like we need metrics service component to make this work in 1.9.

**Comment by feiskyer** [comment]
@jackfrancis Which components are we missing?

**Comment by jackfrancis** [comment]
What I've been told anecdotally is that 1.9 requires the metrics server.

https://github.com/kubernetes/metrics

Haven't had time to look into it beyond that yet! Thanks for any time you can put into this!

**Comment by dtzar** [comment]
I'm guessing it has to do with upstream: https://github.com/kubernetes/kubernetes/issues/47511

**Comment by feiskyer** [comment]
I believe @jackfrancis is referring Horizontal Pod Autoscaler (HPA) while Cluster Autoscaler is aiming to scale the number of nodes (which is under evolving at https://github.com/kubernetes/autoscaler repo and won't need metrics server).

**Comment by jackfrancis** [comment]
@feiskyer is right (issue title changed accordingly)

**Comment by pidah** [comment]
@jackfrancis HPA is failing because k8s 1.8+ require metrics server. Metrics server in turn requires enabling Aggregated API's. I suggest Aggregated API's and metrics server be enabled for k8s 1.8+
I am happy to raise a PR for these if this is ok ?

**Comment by dtzar** [comment]
Yes please

**Comment by jackfrancis** [comment]
@pidah change that to 1.9+ and we're good to go :)

**Comment by djsly** [comment]
FYI: I don't think the metrics server is a hard requirement, we just finished the integration of HPA with custom metric support. While the metric server will become the defacto server, I think that the support for the new metric API was back ported to heapster.  

You can configure `heapster` with the `--api-server` configuration, enable api aggregation on the api-server and finally for custom metrics, run the prometheus-adapter (assuming you have a prometheus) backend.
