### ISSUE TITLE
nginx-ingress-controller deployment fails in Kubernetes 1.91 / acs-engine v0.12.2 

### ISSUE THREAD

**Issue by fengli858** [Azure/acs-engine#2119]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
0.12.2

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.1

**What happened**:
nginx-ingress-controller deployment fails in Kubernetes 1.91 / acs-engine v0.12.2
It works in my another k8s cluster created by acs-engine v.0.11.0

**What you expected to happen**:
the k8s 1.9.1 will create ReplicationController by gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.15

**How to reproduce it** (as minimally and precisely as possible):
Happens every time when using kubectl create -f to deploy rc.

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx-ingress-lb
spec:
  replicas: 2
  selector:
    app: nginx-ingress-lb
  template:
    metadata:
      labels:
        app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      nodeSelector:
          beta.kubernetes.io/os: linux
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.15
        name: nginx-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend

**Anything else we need to know**:

**Comment by dtzar** [comment]
Have you tried using the publicly available helm chart? 
Please see this technical article I wrote which works: http://ow.ly/Fqge30i1O0U

**Comment by fengli858** [comment]
@dtzar David, Thank you for your advice! I will learn the Helm and try these publicly available helm chart to deploy the google ingress replication controller again. I will also visit your blog.

**Comment by dtzar** [comment]
I trust this will solve your problem, so closing the issue out for now. If it does not, please go ahead and respond back here and I can reopen if need be.
