### ISSUE TITLE
kubectl get nodes error connection :443 timeout

### ISSUE THREAD

**Issue by rakidu** [Azure/acs-engine#2122]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**:
C:\Ravi>acs-engine version
Version: canary
GitCommit: unset
GitTreeState: unset

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:
Not able to reach the nodes in the cluster

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by rakidu** [comment]
I deployed acs cluster in azure using ACS-Engine
I logged in to Master and tried to execute "kubectl get nodes" command
error : Unable to connect to the server: dial tcp 52.178.90.205:443: i/o timeout

I downloaded the .kube/config file on to local machine and tried to execute the same command from Azure CLI
Error : Unable to connect to the server: dial tcp 52.178.90.205:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by serbrech** [comment]
Most likely the kubernetes system containers are unable to start for some reason.


try to run `sudo journalctl -u kubelet | grep --text autorest` on a master node to see if it's not your service principal missing the necessary rights.

This is described in the [Troubleshooting](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/troubleshooting.md) doc.

I wish acs-engine could verify this before launching the deployment...

**Comment by rakidu** [comment]
sudo journalctl -u kubelet | grep --text autorest
for above command no output
i executed below command
sudo journalctl -u kubelet 

-- Logs begin at Tue 2018-01-16 14:54:47 UTC, end at Wed 2018-01-24 12:05:19 UTC. --
Jan 16 14:53:56 k8s-master-10483458-0 systemd[1]: Stopped Kubelet.
Jan 16 14:53:59 k8s-master-10483458-0 systemd[1]: Starting Kubelet...
Jan 16 14:53:59 k8s-master-10483458-0 bash[6865]: Bad argument `MASQUERADE'
Jan 16 14:53:59 k8s-master-10483458-0 bash[6865]: Try `iptables -h' or 'iptables --help' for more information.
Jan 16 14:53:59 k8s-master-10483458-0 systemd[1]: kubelet.service: Control process exited, code=exited status=2
Jan 16 14:53:59 k8s-master-10483458-0 systemd[1]: Failed to start Kubelet.

**Comment by rakidu** [comment]
kubelet.service is down 
root@k8s-master-10483458-0:/home/duraki# systemctl status kubelet
● kubelet.service - Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Wed 2018-01-24 11:33:59 UTC; 32min ago
  Process: 1966 ExecStartPre=/bin/bash /opt/azure/containers/kubelet.sh (code=exited, status=2)

Jan 24 11:33:59 k8s-master-10483458-0 systemd[1]: kubelet.service: Unit entered failed state.
Jan 24 11:33:59 k8s-master-10483458-0 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jan 24 11:33:59 k8s-master-10483458-0 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jan 24 11:33:59 k8s-master-10483458-0 systemd[1]: Stopped Kubelet.
Jan 24 11:34:00 k8s-master-10483458-0 systemd[1]: kubelet.service: Start request repeated too quickly.
Jan 24 11:34:00 k8s-master-10483458-0 systemd[1]: Failed to start Kubelet.

**Comment by mcwienczek** [comment]
I am having exactly the same problem with iptables MASQUERADE when deploying acs-engine onto custom VNET. Kubelet won't start:

```
Feb 07 11:46:45 k8s-master-62187370-0 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Feb 07 11:46:45 k8s-master-62187370-0 systemd[1]: Stopped Kubelet.
Feb 07 11:46:45 k8s-master-62187370-0 systemd[1]: Starting Kubelet...
Feb 07 11:46:45 k8s-master-62187370-0 systemd[1]: Started ACPI event daemon.
Feb 07 11:46:45 k8s-master-62187370-0 bash[6938]: Bad argument `MASQUERADE'
Feb 07 11:46:45 k8s-master-62187370-0 bash[6938]: Try `iptables -h' or 'iptables --help' for more information.
Feb 07 11:46:45 k8s-master-62187370-0 systemd[1]: kubelet.service: Control process exited, code=exited status=2
Feb 07 11:46:45 k8s-master-62187370-0 systemd[1]: Failed to start Kubelet.
Feb 07 11:46:45 k8s-master-62187370-0 systemd[1]: kubelet.service: Unit entered failed state.
Feb 07 11:46:45 k8s-master-62187370-0 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

**Comment by mcwienczek** [comment]
Fixed it by adding `"vnetCidr"` parameter to `masterProfile`. Apparently `firstConsecutiveStaticIP` is not enough to setup custom VNET. You also need to specify master CIDR.

**Comment by serbrech** [comment]
@mcwienczek are you using `azure` networkPolicy? or are you using `none` (kubenet)?

**Comment by mcwienczek** [comment]
`azure` network policy

**Comment by jt55401** [comment]
> Fixed it by adding "vnetCidr" parameter to masterProfile. Apparently firstConsecutiveStaticIP is not enough to setup custom VNET. You also need to specify master CIDR.

Thank you. Saved my night. I was going crazy trying to figure that one out.
