### ISSUE TITLE
Latest acs-engine deployed k8s cluster not working

### ISSUE THREAD

**Issue by mcops** [Azure/acs-engine#2124]
**acs-egine release**: 0.12.4
**k8s release:** 1.9.1 (exactly same effect with 1.8.7)

- empty resource group
- deploy k8s cluster with custom vnet and managed disks
  (route table is also not created as in previous release. Not sure if this is not anymore needed with the new cni integrations?)
- k8s: 3x agents (DS4v2), 1x master (DS3v2)
-master, agents and all relevant resources are created properly, besides route table (already
tried to added manually and map it to proper subnet - same effec)

**Troubleshooting performed so far:**
Master: Linux k8s-master-40493200-0 4.13.0-1006-azure (patches from 22nd Jan

kubelet/api not running correctly:
kubectl cluster-info
Kubernetes master is running at https://XXXX.westeurope.cloudapp.azure.com
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp 52.XX.XXX.XXX:443: i/o timeout

sudo journalctl -u kubelet | grep --text autorest
>no output

docker running kube-system containers:
sudo docker ps -f status=running |awk '{print $2}'
sudo: unable to resolve host k8s-master-40493200-0
ID
k8s-gcrio.azureedge.net/hyperkube-amd64@sha256:69cd6e29c8bd7658e6597cba6aa0110e91c8ef9a993844717e7819cf91d77563
k8s-gcrio.azureedge.net/pause-amd64:3.0
k8s-gcrio.azureedge.net/hyperkube-amd64@sha256:69cd6e29c8bd7658e6597cba6aa0110e91c8ef9a993844717e7819cf91d77563
k8s-gcrio.azureedge.net/kube-addon-manager-amd64@sha256:90d80609f044c121b0110d71ac02432cf4c0415e8204f25025666179cbb72387
k8s-gcrio.azureedge.net/pause-amd64:3.0
k8s-gcrio.azureedge.net/pause-amd64:3.0
k8s-gcrio.azureedge.net/pause-amd64:3.0
k8s-gcrio.azureedge.net/hyperkube-amd64:v1.9.1

-Couldn't find anything abnormal in logs

**Support is greatly appreciated, because we have deleted previous cluster, because acs-engine 0.12 was not able to perform clean upgrade and now (yes, I know, 0.12.4 supports it now - too late for us!) usual ARM deployment not working at all :(**

**Comment by ashishkulk** [comment]
Same issue :/

**Comment by jujaga** [comment]
I am also encountering the exact same issue.

**Comment by jt55401** [comment]
same here.

**Comment by imranq2** [comment]
not sure if it applies here but you can issue "systemctl restart etcd" on the master.  This works around a known bug: https://github.com/Azure/acs-engine/issues/2282

**Comment by CecileRobertMichon** [comment]
If anyone is still running into this issue or a similar issue, please share `/var/log/cloud-init-output.log` and `/var/log/azure/cluster-provision.log` with me so I can help you debug the issue. There were a number of deployment transient errors that were fixed with v0.13.0 so if possible you can also try to deploy a new cluster.
