### ISSUE TITLE
Unable to scale the kubernetes cluster after upgrading the kubernetes version from 1.7.9 to 1.8.2

### ISSUE THREAD

**Issue by nagarjunac** [Azure/acs-engine#2127]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
canary
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.2

**What happened**:
I have upgraded my kubernetes cluster from version 1.7.9 to 1.8.2 using the "acs-engine upgrade" command. Then I tried to scale my cluster using the command "acs-engine scale". Scaling the cluster is failing with the below error.
{
  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "customData",
    "message": "Changing property 'customData' is not allowed." }
{"code":"PropertyChangeNotAllowed","target":"osDisk.createOption","message":"Changing property 'osDisk.createOption' is not allowed."}  

**What you expected to happen**:
Scaling of the cluster should have been successful.

**How to reproduce it** (as minimally and precisely as possible):

1. Create a ARM template for kubernetes cluster using acs-engine with custom Vnet specs. Use Kubernetes version 1.7.9

2. Deploy the ARM template using the command  "az group deployment create"

3. Update the route table settings as specified in the acs engine docs for custom vnets.

4.Upgrade the cluster to version 1.8.2 with the help of acs-engine. 

acs-engine upgrade --subscription-id 51ac25de-afdg-9201-d923-8d8e8e8e8e8e \
--resource-group mycluster  --location westus2 \ 
--deployment-dir _output/mycluster  --upgrade-version 1.8.2 \
--auth-method client_secret --client-id 790c8dfc-d8f5-4zx6-b2b0-cxew1cbsf87d --client-secret 8d2972c8-zz71-2xc3-8e1e-18357e92cd8d

5. Try scaling up or down the number of nodes in the cluster. 

acs-engine scale --subscription-id 51ac25de-afdg-9201-d923-8d8e8e8e8e8e \
    --resource-group mycluster  --location westus2 \
    --deployment-dir _output/mycluster --new-node-count 5 \
    --node-pool agentpool1 --master-FQDN mycluster.westus2.cloudapp.azure.com --auth-method client_secret --client-id 790c8dfc-d8f5-4zx6-b2b0-cxew1cbsf87d --client-secret 8d2972c8-zz71-2xc3-8e1e-18357e92cd8d

**Anything else we need to know**:

**Comment by Novitoll** [comment]
+1 What is the resolution for this?
