### ISSUE TITLE
CIS 1.1.24 Ensure that the admission control policy is set to PodSecurityPolicy

### ISSUE THREAD

**Issue by JunSun17** [Azure/acs-engine#2132]
Is this a request for help?: No

Is this an ISSUE or FEATURE REQUEST? (choose one): Feature

Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm): Kubernetes

What you expected to happen: Adopt CIS 1.1.24 Ensure that the admission control policy is set to PodSecurityPolicy.

Extra work needed to create pod security policy:
https://kubernetes.io/docs/admin/admission-controllers/#podsecuritypolicy

**Comment by ewok2030** [comment]
Is this not already implemented by setting the `EnablePodSecurityPolicy` as completed in #2048 ?
