### ISSUE TITLE
Pods are not able to list services

### ISSUE THREAD

**Issue by ducas** [Azure/acs-engine#2137]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

0.12.3

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

I have a Kubernetes v1.8 cluster provisioned to a custom VNet. When trying to run external-dns, logs are displaying the following errors:

time="2018-01-23T23:43:42Z" level=error msg="services is forbidden: User "system:serviceaccount:default:default" cannot list services at the cluster scope" 

I have also tried setting the namespace on the external-dns arguments to default, but no luck - 

time="2018-01-24T00:03:13Z" level=error msg="services is forbidden: User "system:serviceaccount:default:default" cannot list services in the namespace "default""

This works on ACS clusters.

**What you expected to happen**:

The external-dns plugin should be able to list services

**How to reproduce it** (as minimally and precisely as possible):

Follow the instructions for deploying external-dns here: https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/azure.md

**Anything else we need to know**:

Here is the full log output:

    time="2018-01-23T23:43:39Z" level=info msg="config: &{Master: KubeConfig: Sources:[service] Namespace: AnnotationFilter: FQDNTemplate: Compatibility: PublishInternal:false Provider:azure GoogleProject: DomainFilter:[removed] AWSZoneType: AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup:[removed] CloudflareProxied:false InfobloxGridHost: InfobloxWapiPort:443 InfobloxWapiUsername:admin InfobloxWapiPassword: InfobloxWapiVersion:2.3.1 InfobloxSSLVerify:true InMemoryZones:[] Policy:sync Registry:txt TXTOwnerID:default TXTPrefix: Interval:1m0s Once:false DryRun:false LogFormat:text MetricsAddress::7979 LogLevel:info}" 
    time="2018-01-23T23:43:39Z" level=info msg="Connected to cluster at https://10.0.0.1:443" 
    time="2018-01-23T23:43:42Z" level=error msg="services is forbidden: User "system:serviceaccount:default:default" cannot list services at the cluster scope" 
    time="2018-01-23T23:44:43Z" level=error msg="services is forbidden: User "system:serviceaccount:default:default" cannot list services at the cluster scope"

Here is my api model:

    {
      "apiVersion": "vlabs",
      "properties": {
        "orchestratorProfile": {
          "orchestratorType": "Kubernetes",
          "orchestratorRelease": "1.8"
        },
        "masterProfile": {
          "count": 1,
          "dnsPrefix": "[removed]",
          "vmSize": "Standard_D2s_v3",
          "vnetSubnetId": "/subscriptions/[removed]/resourceGroups/[removed]/providers/Microsoft.Network/virtualNetworks/[removed]/subnets/[removed]",
          "firstConsecutiveStaticIP": "10.12.143.250",
          "vnetCidr": "10.12.143.0/24"
        },
        "agentPoolProfiles": [
          {
            "name": "agentpool1",
            "count": 2,
            "vmSize": "Standard_D4s_v3",
            "vnetSubnetId": "/subscriptions/[removed]/resourceGroups/[removed]/providers/Microsoft.Network/virtualNetworks/[removed]/subnets/[removed]",
            "availabilityProfile": "AvailabilitySet"
          }
        ],
        "linuxProfile": {
          "adminUsername": "azureuser",
          "ssh": {
            "publicKeys": [
              {
                "keyData": "[removed]"
              }
            ]
          }
        },
        "servicePrincipalProfile": {
          "clientId": "[removed]",
          "secret": "[removed]"
        }
      }
    }

**Comment by ducas** [comment]
FYI - I ended up getting around this by creating a service account and giving it view access to the cluster.

    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: external-dns
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: external-dns-view-binding
      namespace: default
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view
    subjects:
    - kind: ServiceAccount
      name: external-dns
      namespace: default

This was not required in ACS, so I'm not sure why it has changed for ACS-Engine...

**Comment by jackfrancis** [comment]
@ducas The majority of users wanted an RBAC story by default, which informed the decision to turn it on by default. You can turn it off by declaring this in your api model under the `kubernetesConfig` object:

`"enableRbac": false`

**Comment by ducas** [comment]
@jackfrancis yep - I thought that was the case... I just wanted to confirm it was intentional. I'm happy with having RBAC. Thanks!
