### ISSUE TITLE
Kubernetes custom vnet deployment struck at adding route table

### ISSUE THREAD

**Issue by rakidu** [Azure/acs-engine#2146]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**:
C:\Users\infyadmin\Downloads>acs-engine version
Version: canary
GitCommit: unset
GitTreeState: unset
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:
The kubelet service down

**What you expected to happen**:
The route table should be created so that master will communicate with nodes
Without route tables i am getting "IP:443 timeout" error

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
networkpolicy set as Azure while deploying the cluster

**Comment by nakahparis** [comment]
There is no Route Table created when using Network Policy "Azure". Pods are obtaining IP's directly from the VNET. If you want a Route Table, you should use Network Policy "none"

**Comment by JunSun17** [comment]
@rakidu can you post a detailed log on the issue you saw? It seems something else went wrong on your deployment.
