### ISSUE TITLE
Unable to get AAD groups to work with RBAC

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#2150]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: master

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

Following the documentation added in this commit. I'm unable to get AAD groups to be used as a k8s role binding group. @mirthy would you be able to assist?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
I see that apiserver has the following flag `--oidc-groups-claim=groups`. Should I see the groups key present in my JWT access token?

**Comment by lachie83** [comment]
@pidah I see you've also done some work on this area and may be able to help

**Comment by duga3** [comment]
When I configured that first time, I missed this line in the [AAD walkthrough](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/aad.md)
> For groups to work properly, you'll need to edit the Server Application Manifest and set groupMembershipClaims to either All or SecurityGroup.

**Comment by lachie83** [comment]
Thanks for your response @duga3 

I have confirmed that the manifest for the server application has the following configured `"groupMembershipClaims": "All",` and that I do have the tenant ID present as an argument to the following flag on the api server `--oidc-issuer-url`

One thing that I do notice in the apiserver logs is the following message right before  the RBAC DENY. `I0125 05:50:38.703095       1 jwt.go:158] Signature error (key 0): crypto/rsa: verification error`

From the looks of it in the JWT. Group membership needs an additional call to the graph API. Will that additional API call happen because this seems different to most other implementations where the groups array is present in the access JWT

**Comment by lachie83** [comment]
Even turning the logging on the apiserver to v=10 I don't get any more insight as to what call is generating this and even if it's something to worry about `I0125 05:50:38.703095 1 jwt.go:158] Signature error (key 0): crypto/rsa: verification error`

**Comment by lachie83** [comment]
@cosmincojocar. Wondering if you can weigh in here as you wrote Azure plugin

**Comment by duga3** [comment]
@lachie83 I get this JWT error as well, but everything works as expected.
> jwt.go:158] Signature error (key 0): crypto/rsa: verification error
When I first setup AAD manually, I followed the example [there](https://github.com/colemickens/azure-ad-k8s-oidc-example#unknowns). @colemickens experienced the same error JWT, but it still works. Didn't trace it down in the code so far.
Right before the RBAC deny error, there should be a list which groups the user is part of, there is at least one system group that the user is always member of.
If kubernetes manages to fetch the groups from the token, you should see a list of the respective objectIDs.
Could you paste the relevant parts from the apiserver log?

**Comment by lachie83** [comment]
I do not see any logs like that in the apiserver. Can you post a snippet so I can confirm?

Also I have the following flags on the apiserver

```
--oidc-client-id=spn:<client_id> --oidc-username-claim=oid --oidc-groups-claim=groups --oidc-issuer-url=https://sts.windows.net/<tenant_id>/
```

I would also like to the confirm that you only need to set the groupMembershipClaims on the server app (Web App/API)

**Comment by colemickens** [comment]
@duga3 AFAIK those messages are totally unrelated, and I was seeing them sporadically even without any OIDC stuff turned on.

**Comment by pidah** [comment]
@lachie83 I tried it again today successfully against k8s 1.9.*  The only other thing I did was follow the steps in the troubleshooting section – https://github.com/DigitalInnovation/acs-engine/blob/AADGroupAdminId/docs/kubernetes/aad.md#loginpageerror

**Comment by lachie83** [comment]
Thanks for the response @pidah. Can you confirm if this also works for k8s 1.8 and 1.7? My tests are currently running on k8s 1.8.

Are you building from master? Can you confirm your AAD profile under the properties session in your model?

Are you specifying all of the following?
```
"aadProfile": {
    "serverAppID": "<serverAppID",
    "clientAppID": "<clientAppID>",
    "tenantID": "<tenantID>",
    "adminGroupID": "<adminGroupID>"
}
```

I would also like to confirm my expectations here. I would only like to have a group based cluster role binding and not a user specific CRB.

**Comment by pidah** [comment]
@lachie83 I confirm specifying all 4 flags; we also only need group based CRB; I built from latest master today. I will test 1.7/1.8 tomorrow.

**Comment by lachie83** [comment]
@pidah would you be willing to jump on a video chat to eyeball my setup? I'm lachie83 on k8s slack.

**Comment by lachie83** [comment]
When I take a look at the JWT from the access-token section of kubeconfig I only see the following referencing groups. Can you confirm if you see the following using jwt.io:

```
  "_claim_names": {
    "groups": "src1"
  },
  "_claim_sources": {
    "src1": {
      "endpoint": "https://graph.windows.net/<tenantID>/users/<user_oid>/getMemberObjects"
    }
```

**Comment by cosmincojocar** [comment]
@lachie83 I remember that AAD will in-line the groups in the JWT only if the user is member of a very few groups, otherwise it will send a URI to a Graph API object.  I guess you have in addition to configure the api server application by adding the **"groupsMembershipClaims": "All"** in the manifest. See the **Groups** section of the [Modern Authentication with Azure Active Directory for Web Applications](https://books.google.com/books?id=5-U3CwAAQBAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q=group&f=false) book.

A better alternative to the OpenID Connect plugin used by api server, is this [Webhook](https://github.com/Nike-Inc/harbormaster), which is able to validate a token issued by AAD and upon authentication it will fetch the groups from Graph API. You have also to configure the api server to delegate the token review to this webhook. It can be deployed on the same node as the api server. I just tested briefly a while ago.

**Comment by pidah** [comment]
Hi @lachie83, yes I am happy to jump on a video chat UK time. The following is my access token <redacted> 
```
{
  "aud": "spn:33d205gg-0296-11e8-ba34-0ed5f89f718b",
  "iss": "https://sts.windows.net/33d205cc-0296-11e8-ba89-0ed5f89f718b/",
  "iat": 1516969591,
  "nbf": 1516969591,
  "exp": 1516973491,
  "acr": "1",
  "aio": "Y2NgYKh8ervmRNOcVR68upuSuTjmCljNFZvdrcT8gMnAqrWC4zAA",
  "amr": [
    "pwd"
  ],
  "appid": "901075f7-f08d-4fac-9196-e2ce33947614",
  "appidacr": "0",
  "family_name": "Idah",
  "given_name": "Peter",
  "groups": [
    "33d1d7d2-0296-11e8-ba89-0ed5f89f718b",
    "33d1daf2-0296-11e8-ba89-0ed5f89f718b",
    "33d1dd68-0296-11e8-ba89-0ed5f89f718b",
    "33d1df66-0296-11e8-ba89-0ed5f89f718b",
    "33d1e3a8-0296-11e8-ba89-0ed5f89f718b",
    "33d1e59c-0296-11e8-ba89-0ed5f89f718b",
    "33d1e77c-0296-11e8-ba89-0ed5f89f718b",
    "33d1e95c-0296-11e8-ba89-0ed5f89f718b",
    "33d1eb3c-0296-11e8-ba89-0ed5f89f718b",
    "33d1ed1c-0296-11e8-ba89-0ed5f89f718b",
    "33d1ef06-0296-11e8-ba89-0ed5f89f718b",
    "33d1f4b0-0296-11e8-ba89-0ed5f89f718b",
    "33d1f6e0-0296-11e8-ba89-0ed5f89f718b",
    "33d1f8de-0296-11e8-ba89-0ed5f89f718b",
    "33d1fad2-0296-11e8-ba89-0ed5f89f718b",
    "33d1fcc6-0296-11e8-ba89-0ed5f89f718b",
    "33d1fea6-0296-11e8-ba89-0ed5f89f718b"
],
  "ipaddr": "183.0.154.18",
  "name": "Idah, Peter",
  "oid": "33d205cc-0296-11e8-ba89-0ed5f89f718b",
  "onprem_sid": "S-1-5-21-961111111-1923232342-1823234326-123232",
  "scp": "user_impersonation",
  "sub": "Zj_9jG39_o07TkRcZySBGbTsu$Ag6fs_kUGuS7T3Ytxk",
  "tid": "33d205cc-0296-11e8-ba89-0ed5f89f718b",
  "unique_name": "Peter.Idah@xxxx.net",
  "upn": "Peter.Idah@xxxx.net",
  "uti": "tcsd3t0Ct0mQf20u1QsjFF",
  "ver": "1.0"
}
```

I confirmed it working on k8s 1.8.3 . On k8s 1.7.12 the rbac binding was not applied because of the RBAC version ` rbac.authorization.k8s.io/v1`. Once I changed it to ` rbac.authorization.k8s.io/v1beta1` and applied it, kubectl authentication/authorization worked fine.

**Comment by sylr** [comment]
FYI I set `groupMembershipClaims` from `null` to `7` in the server application manifest and now I have groups in my token (124 of them actually, I don't know if they are all here).

**Comment by jamoham** [comment]
Even after setting `groupMembershipClaims` to `"All"` or `"SecurityGroup"`,
my token does not list the groups:

```
  "_claim_names": {
    "groups": "src1"
  },
  "_claim_sources": {
    "src1": {
      "endpoint": "https://graph.windows.net/<tenantID>/users/<user_oid>/getMemberObjects"
    }
```

What am I missing here?

**Comment by idanlevin** [comment]
any updates on this?

**Comment by mo-saeed** [comment]
> Even after setting `groupMembershipClaims` to `"All"` or `"SecurityGroup"`,
> my token does not list the groups:
> 
> ```
>   "_claim_names": {
>     "groups": "src1"
>   },
>   "_claim_sources": {
>     "src1": {
>       "endpoint": "https://graph.windows.net/<tenantID>/users/<user_oid>/getMemberObjects"
>     }
> ```
> 
> What am I missing here?

Hi @jamoham did you find out how to fix this ?
