### ISSUE TITLE
DS2_v2 should be used in the examples

### ISSUE THREAD

**Issue by blacksails** [Azure/acs-engine#2158]
**Is this a request for help?**:

No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**What version of acs-engine?**:

v0.12.4

I think that the examples should use a vm size that supports the managed-premium storage class. The D2_v2 size used in the examples does not. I had to recreate our cluster after finding out that i couldn't attach premium storage.

**Comment by dtzar** [comment]
There are TONS of examples.  Which ones specifically do you think should be changed?

**Comment by blacksails** [comment]
At least the k8s ones. I don't know much about swarm and dcos' use of premium storage. But k8s comes preconfigured with a premium storage class, which can only be used if the vm supports it.
