### ISSUE TITLE
The template deployment is not valid according to the validation procedure

### ISSUE THREAD

**Issue by bailantaotao** [Azure/acs-engine#2161]
**Is this a request for help?**:

yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

issue

---

**What version of acs-engine?**:

Version: canary
GitCommit: e251320a
GitTreeState: clean

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernates

**What happened**:

``` 
The template deployment 'dev-acs' is not valid according to the validation procedure. The tracking id is 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
```

**What you expected to happen**:

It should print the fully error message.
How do i to use tracking id?

**How to reproduce it** (as minimally and precisely as possible):

```
$ acs-engine generate template.json
$ az group deployment create --name dev-acs --resource-group rg-dev-acs --template-file _output/dev-acs/azuredeploy.json --parameters _output/dev-acs/azuredeploy.parameters.json
```

**Anything else we need to know**:

template.json
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.7.9",
      "kubernetesConfig": {
        "enableRbac": true,
        "networkPolicy": "calico",
        "clusterSubnet": "172.16.0.0/20"
      }
    },
    "masterProfile": {
      "dnsPrefix": "dev-acs",
      "count": 1,
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": "/subscriptions/xxxxxxx/resourceGroups/vpc-dev-acs/providers/Microsoft.Network/virtualNetworks/vnet-dev-acs/subnets/subnet-dev-acs",
      "vnetCidr": "10.1.48.0/20",
      "firstConsecutiveStaticIP": "10.1.63.254",
      "OSDiskSizeGB": 512,
      "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "memory",
        "count": 4,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/xxxxxxx/resourceGroups/vpc-dev-acs/providers/Microsoft.Network/virtualNetworks/vnet-dev-acs/subnets/subnet-dev-acs",
        "OSDiskSizeGB": 512,
        "storageProfile": "ManagedDisks"
      },
      {
        "name": "memoryplus",
        "count": 1,
        "vmSize": "Standard_D8s_v3",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/xxxxxxx/resourceGroups/vpc-dev-acs/providers/Microsoft.Network/virtualNetworks/vnet-dev-acs/subnets/subnet-dev-acs",
        "OSDiskSizeGB": 512,
        "storageProfile": "ManagedDisks"
      },
      {
        "name": "compute",
        "count": 1,
        "vmSize": "Standard_F4s_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/xxxxxxx/resourceGroups/vpc-dev-acs/providers/Microsoft.Network/virtualNetworks/vnet-dev-acs/subnets/subnet-dev-acs",
        "OSDiskSizeGB": 512,
        "storageProfile": "ManagedDisks"
      },
      {
        "name": "storage",
        "count": 1,
        "vmSize": "Standard_L4s",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/xxxxxxx/resourceGroups/vpc-dev-acs/providers/Microsoft.Network/virtualNetworks/vnet-dev-acs/subnets/subnet-dev-acs",
        "OSDiskSizeGB": 512,
        "storageProfile": "ManagedDisks",
        "diskSizesGB": [1023]
      }
    ],
    "linuxProfile": {
      "adminUsername": "amis",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "xxxxxxxxxxx"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "xxxxxxxxxxx",
      "secret": "xxxxxxxxxxx"
    }
  }
}

```

**Comment by andscho-msft** [comment]
I ran into this also yesterday, and I was able to find my actual error by using the powershell commandlets.

```Powershell
Get-AzureRMLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DetailedOutput
```

**Comment by bailantaotao** [comment]
Thanks for @andscho-msft

I cannot to use the command `Get-AzureRMLog` on macOS environment.

But i can get the information from `Azure Cloud Shell`  :)

**Comment by dazinator** [comment]
I hit this area following the getting  started guide for acs and swarm.
when doing `azs create` it looks like it uses a default --agent-vm-size of `Standard_D2_v2` which isn't available for my region `uksouth`. This leads to this error being output with no clue as to what went wrong. Using the azure cloud shell to get the error details helped narrow down the problem. Now I am left with the problem of how to figure out what vm size to use that is in my region and closest to the default. I have no idea how to figure that out.

It would be better if it could default to an available size for the region, or provide a better error message explaining what went wrong and how to fix it.

**Comment by iamgini** [comment]
> I ran into this also yesterday, and I was able to find my actual error by using the powershell commandlets.
> 
> ```powershell
> Get-AzureRMLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DetailedOutput
> ```

Wonderful  :)

**Comment by ahelwer** [comment]
With the new Azure PowerShell commandlets, you're actually looking for:

```
Get-AzLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DetailedOutput
```

**Comment by danielibanez** [comment]
Thanks @dazinator Changing the deploy settings fixed this issue.

I ran into this problem with Umbraco CMS.

**Comment by aadamsx** [comment]
When running 

Get-AzLog -CorrelationId c6d2da54-813a-40e3-84bd-163438c81574 -DetailedOutput

Where c6d2da54-813a-40e3-84bd-163438c81574 is the tracking id in the error, I get the following:

WARNING: 5:35:15 PM - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 5:35:15 PM - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.
WARNING: [Get-AzLog] Parameter deprecation: The DetailedOutput parameter will be deprecated in a future breaking change release.

**Comment by elpablete** [comment]
> With the new Azure PowerShell commandlets, you're actually looking for:
> 
> ```
> Get-AzLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DetailedOutput
> ```

Cloud shell returns empty result using this command with my trakcing Id.

**Comment by ahelwer** [comment]
@elpablete try:
```
$result = Get-AzLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DetailedOutput
```
Then examine `$result`.

**Comment by eisber** [comment]
Azure CLI: az monitor activity-log list --correlation-id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by rdtechie** [comment]
`((Get-AzLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).Properties.Content.statusMessage | ConvertFrom-Json -AsHashtable).error.details.message`

**Comment by ghost** [comment]
> Azure CLI: az monitor activity-log list --correlation-id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

One thing here, just make sure you supply the subscription ot set the default subscription, the command won't error with not found it will just return an empty list

**Comment by anushas-dev** [comment]
> ```powershell
> Get-AzureRMLog
> ```

Newer command, for az power shell from 7.x.x,
Get-AzLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DetailedOutput
