### ISSUE TITLE
K8s upgrade leads to temporary unreachable services

### ISSUE THREAD

**Issue by ITler** [Azure/acs-engine#2175]
**Is this a request for help?**:
---
maybe yes, as I can't believe, that upgrading K8s using acs-engine leads to temporary unavailability (connectivity loss) of deployed applications

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
in worst case an issue

**What version of acs-engine?**:
---
v0.12.0, but also seen in v0.10.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
server 1.8.4 client 1.9.2

**What happened**:

On **AzureGermanCloud** I've set up a basic cluster with 3 masters and 3 agents. I run 3 instances of nginx each on every agent and having a load-balanced service to have nginx reachable from outside via public ip. I'm continuously `curl`ing to check, if nginx is reachable and it is.
Now I start to upgrade k8s from 1.8.4 to 1.9.1
When upgrade process comes to first upgrade of k8s master:

    INFO[0252] Master offset: 0
    INFO[0252] Master pool set count to: 1 temporarily during upgrade...
    INFO[0252] Starting ARM Deployment (master-18-01-31T12.25.12-930474091). This will take some time...
    [...here...]
    INFO[1171] Finished ARM Deployment (master-18-01-31T12.25.12-930474091). 

...nginx is not reachable anymore for at least 10 minutes ... curl reports connection timed out.
About 2 minutes before ARM Deployment will be finished, nginx is reachable again and keeps reachable until next k8s master gets upgraded. Then, again, nginx is not reachable, temporarily... same for 3rd master upgrade. 

If I would have to guess, the ARM Deployment "touches" (maybe re-creates) Azure's Public IP resource, which leads to the outage.

**What you expected to happen**:
I would expect that running applications, which have replicas on multiple k8s agent nodes and a load balanced service, are reachable during upgrade of k8s without interruption (as on AWS).

**How to reproduce it** (as minimally and precisely as possible):
Bootstrap at least 1 master, 2 agents, deploy nginx (or any application) with at least 2 replicas and pod affinity to be distributed to at least 2 k8s agents, setup load-balanced service and monitor app's availability via public ip connection.

**Anything else we need to know**:

    "kubernetesConfig": {
        "networkPolicy": "none"
    },

full config: https://gist.github.com/ITler/840c96544416b1ecee3add2e171f1e2b

**Comment by ITler** [comment]
Am I the only one with that issue? Does upgrading Kubernetes with that approach usually work?

**Comment by yastij** [comment]
cc @jackfrancis -  I can confirm this behavior in `northeurope`.

**Comment by jackfrancis** [comment]
So this is not a failure of the cordon and drain implementation, but rather in the network plumbing for the newly created VMs? (upgrade works by deleting/creating vms)

**Comment by yastij** [comment]
Yes

**Comment by jackfrancis** [comment]
@JackQuincy @amanohar Does the above description match current expectations for acs-engine upgrade implementation? Is this a known gap or a novel bug?

**Comment by JackQuincy** [comment]
my guess is this is an nsg issue. For scale we remove the nsg from the deployments we send to arm. I'm guessing on recreating masters we aren't doing that and that is blocking all traffic from the internet to the load balancer services until k8s recreates them. This is the original [pr](https://github.com/Azure/acs-engine/pull/366) where I fixed it for scale, Seems we might need to pull this out some and let upgrade use it as well

**Comment by yastij** [comment]
@JackQuincy @CecileRobertMichon - I can confirm, this is related to NSGs not being removed before having the deployment being sent to ARM.

**Comment by khaldoune** [comment]
@JackQuincy 
Why do we need to remove the NSG before upgrade?
Cc @yastij @CecileRobertMichon

**Comment by yastij** [comment]
Yes, wee need to add a call to `transformer.NormalizeForK8sVMASScalingUp(sc.logger, templateJSON)` It'll remove the NSG. I'll try to send a PR this weekend
