### ISSUE TITLE
K8S require credentials after scaling and resizing vms

### ISSUE THREAD

**Issue by AlexandreRzc** [Azure/acs-engine#2176]
**Is this a request for help?**:
Yes, I'm beginner on ACS and Kubernetes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
Version: v0.5.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Client 1.8.0 and Server 1.8.1

**What happened**:
This morning I scaled the agentpool from 2 VMs  to 5 with the screen "Agent Pool" on the Azure Portal 
and changed the size of the VMs one by one witht the portal too.
After the scaling and resizing, I noticed that I couldn't access to the pods I deploy on the cluster since this morning but I still can access to the old ones deployed before this morning.

I can use kubectl to create, list, describe and delete pods , service etc
But I can't use logs and exec 

I can access to the web UI too, but the web UI can't access to the logs and exec too.

The pods are not reachable from kubectl but are still running : for example my elasticsearch is still up and reachable from curl 

I scaled down to 2 VMs and it works agains

**What you expected to happen**:
After scaling, it should be transparent and ready to serve.

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster , scale VMs then change the size of VMs 

**Anything else we need to know**:

**Comment by JunSun17** [comment]
Not sure we have the corresponding scaling tests in place to test pod activity. Add the missing_test label for further repo and investigation.

**Comment by AlexandreRzc** [comment]
Hi 
I found out that the kubelet file in /etc/default/  and kubelet.service file in /etc/systemd/system/
were not the same as my previous nodes. I did a manual copy and restarted kubelet and it worked.

If i want those files to be replicated on any new nodes, what should I do ?
And more generally if i want to launch and replicated some actions/scripts on any nodes what should I do ?
