### ISSUE TITLE
Duplicate names for storage accounts

### ISSUE THREAD

**Issue by UncleTawnos** [Azure/acs-engine#2177]
**Is this a request for help?**:
NO
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
master at commit 65d2ed3ad076256a2dc33e3d4f067e3470d21d15 
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
KUBERNETES

**What happened**:
validation / deployments fails due to storage account names being already taken
```
msrest.http_logger : b'{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment \'deployment_dry_run\' is not valid according to the validation procedure. The tracking id is \'c1d8c42e-abfa-433b-a40a-9d1e31ad621e\'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.","details":[{"code":"PreflightValidationCheckFailed","message":"Preflight validation failed. Please refer to the details for the specific errors.","details":[{"code":"StorageAccountAlreadyTaken","target":"00xrc2zephck2y2agnt0","message":"The storage account named 00xrc2zephck2y2agnt0 is already taken."},{"code":"StorageAccountAlreadyTaken","target":"u0xrc2zephck2y2agnt1","message":"The storage account named u0xrc2zephck2y2agnt1 is already taken."}]}]}}'
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f3ea9688ea0>, <function _x509_from_base64_to_hex_transform at 0x7f3ea9688f28>]
Event: CommandInvoker.OnFilterResult []
```

**What you expected to happen**:
deployment validates

**How to reproduce it** (as minimally and precisely as possible):
create a cluster with common master fqdn prefix - like k8s-prod, kubernetes-test, etc, use StorageAccount for nodes' PersistentVolumeClaims, try to deploy second cluster with the same name and region within another unrelated subscription

**Anything else we need to know**:
The faulty part is this template line:
`"storageAccountBaseName": "[uniqueString(concat(variables('masterFqdnPrefix'),variables('location')))]",`

this generates non-unique string. Adding some random string:
` "storageAccountBaseName": "[uniqueString(concat(variables('masterFqdnPrefix'),variables('location'),'fds43'))]",`
resolves the problem

**Comment by JunSun17** [comment]
Checked the uniqueString reference here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-string#uniquestring . It seems making sense that we should not allow two different deployments which use the same masterFqdnPrefix + location since master FQDN is in the form of masterFqdnPrefix.location.cloudapp.azure.com (as the entry point for your master nodes).

I do agree we probably should fail at an earlier point.

**Comment by UncleTawnos** [comment]
yeah, quick fail would be cool, as large cluster tends to deploy very long time and still you can end with storage name someone else in Azure uses (as they're unique worldwide)
