### ISSUE TITLE
Unable to mount secret volumes for kube-proxy and calico with acs 0.12.5 and k8s 1.9.1 and 1.8

### ISSUE THREAD

**Issue by khaldoune** [Azure/acs-engine#2185]
**Is this a request for help?**:
ISSUE
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.12.5
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.1

**What happened**:
Try to install k8s using this template:
`{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.9",
      "kubernetesConfig": {
         "enableRbac": true,
         "enableAggregatedAPIs": true,
         "enableDataEncryptionAtRest": true,
         "networkPolicy": "calico",
         "clusterSubnet": "10.90.0.0/23",
         "dnsServiceIP": "10.90.2.10",
         "serviceCidr": "10.90.2.0/24",
         "maxPods": 64,
         "kubeletConfig": {
            "--anonymous-auth": "false",
            "--read-only-port": "0",
            "--event-qps": "0"
         },
         "controllerManagerConfig": {
            "--profiling": "false",
            "--terminated-pod-gc-threshold": "100",
            "--node-cidr-mask-size": "26"
         },
         "cloudControllerManagerConfig": {
            "--profiling": "false"
         },
         "apiServerConfig": {
            "--profiling": "false",
            "--repair-malformed-updates": "false"
         }
      }
    },
    "masterProfile": {
      "count": 5,
      "dnsPrefix": "k8sdev19-v3",
      "vmSize": "Standard_D2",
      "vnetSubnetId": "/subscriptions/00000000000000000000000000000000000/resourceGroups/k8sdev19-v3/providers/Microsoft.Network/virtualNetworks/vnet193/subnets/masters",
      "firstConsecutiveStaticIP": "10.90.3.4"
    },
    "agentPoolProfiles": [
      {
        "name": "worker",
        "count": 4,
        "vmSize": "Standard_DS2",
        "availabilityProfile": "AvailabilitySet",
        "dnsPrefix": "",
        "vnetSubnetId": "/subscriptions/00000000000000000000000000000000000/resourceGroups/k8sdev19-v3/providers/Microsoft.Network/virtualNetworks/vnet193/subnets/workers"
      }
    ],
    "linuxProfile": {
      "adminUsername": "k8s",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "secret": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    }
  }
}
`

You will get the calico and kube-proxy crashing.

When you see the dump file, you see these errors:

`"Message": "MountVolume.SetUp failed for volume \"calico-node-token-vc8d5\" : Internal error occurred: invalid padding on input",
"Message": "Unable to mount volumes for pod \"kube-proxy-2kmds_kube-system(6f1efee0-0784-11e8-bc9d-000d3ab0f58e)\": timeout expired waiting for volumes to attach/mount for pod \"kube-system\"/\"kube-proxy-2kmds\". list of unattached/unmounted volumes=[default-token-x7kvh]",`

Or even:

`Line 148290: logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12\x82\x01\n\x06\n\x00\x12\x00\x1a\x00\x12\aFailure\x1a1Internal error occurred: invalid padding on input\"\rInternalError**\n\x00\x12\x00\x1a\x00\"\x1e\n\x00\x12\x18invalid padding on input\x1a\x00(\x002\x000\xf4\x03\x1a\x00\"\x00"`

**What you expected to happen**:
A functional k8s cluster

**How to reproduce it** (as minimally and precisely as possible):
Use the cluster definition below

**Anything else we need to know**:
Thanks

**Comment by khaldoune** [comment]
I can also see these errors:

`Line 72931: E0202 00:52:58.056017       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get https://10.110.3.8:443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp 10.110.3.8:443: getsockopt: connection refused`

AND

`Line 72982: time="2018-02-02T00:54:59Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.11.0-1016-azure/modules.dep.bin'\nmodprobe: WARNING: Module ip_vs not found in directory /lib/modules/4.11.0-1016-azure`, error: exit status 1"`

My routetable seems to be OK

k8s-master-41950892-0 | 10.110.0.192/27 | 10.110.3.4 | …
-- | -- | -- | --
k8s-master-41950892-1 | 10.110.0.160/27 | 10.110.3.5 | …
k8s-master-41950892-2 | 10.110.0.224/27 | 10.110.3.6 | …
k8s-master-41950892-3 | 10.110.0.96/27 | 10.110.3.7 | …
k8s-master-41950892-4 | 10.110.0.128/27 | 10.110.3.8 | …
k8s-worker-41950892-0 | 10.110.0.0/27 | 10.110.3.132 | …
k8s-worker-41950892-1 | 10.110.0.64/27 | 10.110.3.134 | …
k8s-worker-41950892-2 | 10.110.0.32/27 | 10.110.3.135 | …
k8s-worker-41950892-3 | 10.110.1.0/27 | 10.110.3.133

Thanks.

**Comment by khaldoune** [comment]
And some logs from kube-proxy:

time="2018-02-02T01:24:56Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: **ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.11.0-1016-azure/modules.dep.bin'\nmodprobe: WARNING: Module ip_vs not found in directory /lib/modules/4.11.0-1016-azure`, error: exit status 1"**
time="2018-02-02T01:24:56Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."
W0202 01:24:56.174575       1 server_others.go:289] Flag proxy-mode="" unknown, assuming iptables proxy
I0202 01:24:56.175812       1 server_others.go:138] Using iptables Proxier.
I0202 01:24:56.248550       1 server_others.go:171] Tearing down inactive rules.
E0202 01:24:56.276935       1 proxier.go:792] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed

I get this error even if I force proxy-mode=iptables

**Comment by khaldoune** [comment]
I have just found that if I remove enableDataEncryptionAtRest from the API Server params, it works. Still need to understand why...

**Comment by pidah** [comment]
@khaldoune there was a bug fixed for enableDataEncryptionAtRest in master. Can you build from master and try ?

**Comment by khaldoune** [comment]
@pidah 
Deployment from master fails:
`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'cse0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=3\\n[stdout]\\n\\n[stderr]\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'cse2'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=3\\n[stdout]\\n\\n[stderr]\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'cse1'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=3\\n[stdout]\\n\\n[stderr]\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'cse3'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=3\\n[stdout]\\n\\n[stderr]\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'cse4'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=3\\n[stdout]\\n\\n[stderr]\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}`

**Comment by khaldoune** [comment]
@pidah: I will retry in the next release. Do you have an approximative release date?
