### ISSUE TITLE
Mixed cluster with windows & linux pools

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/acs-engine#2188]
**Is this a request for help?**: Yes, I need an example how can I deploy a cluster with linux and windows pools in the same cluster for both DCOS and K8s. I did not see any ARM templates where the agent pool template contains OS version. I also did not find any examples how can you spin up a cluster with multiple pools that are different.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
This is a FEATURE REQUEST.
---

**What version of acs-engine?**:
Any version supported.
---

**Comment by olilanz** [comment]
A k8s linux/win hybrid example can be found here: https://github.com/Azure/acs-engine/blob/master/examples/windows/kubernetes-hybrid.json

An example for spcifying the OS version is here: https://github.com/Azure/acs-engine/blob/master/examples/windows/kubernetes-windows-version.json

My experience with hybrid clusters only covers k8s. But I suppose it works the same way for DC/OS.

**Comment by lmiroslaw** [comment]
Thanks! Will give it a try.
