### ISSUE TITLE
VMs with Accelerated Networking 

### ISSUE THREAD

**Issue by olilanz** [Azure/acs-engine#2199]
**Is this a request for help?**:
No.
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature 
---

**What version of acs-engine?**:
Any. Currently 0.12.5
---

**Description**
Accelerated Networking is now generally available for free on Azure for most VMs. It brings better network performance, reduces jitter, and uses less CPU. For it to work, the NICs need to be created with the EnableAcceleratedNetworking option. 

More info: https://azure.microsoft.com/en-us/blog/maximize-your-vm-s-performance-with-accelerated-networking-now-generally-available-for-both-windows-and-linux/

Not all VMs have that support. Ideally, Azure would provide an API through which the supported VM types could be identified. acs-engine could then automatically configure the best NIC option. I didn’t find any such. So, it might be more practical to make the option available in the cluster definition, e.g. master/agent profiles like this:

...
    "agentPoolProfiles": [
      {
        "name": "linuxpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
        “enableAcceleratedNetworking”: “true”
      },
...

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
All

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/pull/3011
