### ISSUE TITLE
Cannot use gluster-kubernetes with ACS

### ISSUE THREAD

**Issue by zrahui** [Azure/acs-engine#2222]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: 0.12.5

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.1

**What happened**:
Deploying [gluster-kubernetes](https://github.com/gluster/gluster-kubernetes) into an Azure CNI enabled cluster results in non-functioning DNS. 
kube-dns logs show i/o timeouts as it is unable to reach the apiservers as below:
```
E0207 02:00:53.044120       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://192.168.25.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 192.168.25.1:443: i/o timeout
```

**What you expected to happen**:
DNS continue to work after deployment

**How to reproduce it** (as minimally and precisely as possible):
As above, use the gluster-kubernetes deployment tool to provision into an ACS Engine cluster. nslookup /tracing continues to function from busybox pods until the GlusterFS pods come online. 
```
PS C:\azure> kubectl exec -ti busybox-std-2mkgx sh
/ # nslookup kubernetes
Server:    192.168.25.10
Address 1: 192.168.25.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes
Address 1: 192.168.25.1 kubernetes.default.svc.cluster.local
/ # traceroute kubernetes
traceroute to kubernetes (192.168.25.1), 30 hops max, 46 byte packets
 1  *^C <----- Pods come online around here.
/ # traceroute kubernetes
traceroute: bad address 'kubernetes'
/ # nslookup kubernetes
Server:    192.168.25.10
^C
/ #
```
Removing the pods, clearing /var/lib/glusterd on each node and rebooting brings DNS (and connections to apiserver) back online.

**Anything else we need to know**:
I've tried to resolve this but not sure where the issue lies, it seems to be either a port conflict or something that glusterd is doing to the cluster. This worked in an older ACS Engine cluster without Azure CNI. Any help or direction for debugging is much appreciated.

**Comment by jarrpa** [comment]
I'll note that the only things I can think of that might affect this are that the GlusterFS pods:

1. are privileged
2. use hostNetwork

Here's a direct link to the DaemonSet: https://github.com/gluster/gluster-kubernetes/blob/master/deploy/kube-templates/glusterfs-daemonset.yaml

And here's a list of the ports it uses: https://github.com/gluster/gluster-kubernetes/blob/master/deploy/gk-deploy#L539-L545
