### ISSUE TITLE
nit: etcd diskSize is string

### ISSUE THREAD

**Issue by khenidak** [Azure/acs-engine#2231]
Just a little nit - 
https://github.com/Azure/acs-engine/blob/master/pkg/api/types.go#L245 

size should be an int not a string

**Comment by jackfrancis** [comment]
While there are some advantages to not having to do type conversion for integer comparison (and other math operations), the ARM spec accepts this value as a string:

https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesmasterresources.t#L510

Additionally, there is overhead to changing this type spec w/ respect to upgrade/scale.
