### ISSUE TITLE
Multi-Master Fails to setup etcd correctly on 3rd master

### ISSUE THREAD

**Issue by dstrebel** [Azure/acs-engine#2232]
**Is this a request for help?**:

---No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---Issue

**What version of acs-engine?**:

---0.12.5

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9

**What happened**:
One master failed with etcd error

**What you expected to happen**:
three working masters

**How to reproduce it** (as minimally and precisely as possible):
run multi-master deployment like the one below

{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.9",
            "kubernetesConfig": {
                "networkPolicy": "calico"
            }
        },
        "masterProfile": {
            "count": 3,
            "dnsPrefix": "k8-tugboatlabs",
            "vmSize": "Standard_DS2_v2_Promo"
        },

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Hi @dstrebel, could you please share what `ls -l /etc/kubernetes/certs` looks like on your cluster? There were several fixes pushed to master to improve the resilience of deployments and specifically to protect against errors like yours. In the meantime, you might want to try deploying again as this is a transient error.

**Comment by CecileRobertMichon** [comment]
This should be fixed in v0.13.0 , please feel free to reopen if you encounter the same problem again.
