### ISSUE TITLE
go-bindata repo has new owner

### ISSUE THREAD

**Issue by pidah** [Azure/acs-engine#2234]
**ISSUE** 

---

**What version of acs-engine?**: all

---

The go-bindata creator deleted their @github account and someone else created a new account with the same name. More details reported by @francesc yesterday on twitter –
https://twitter.com/francesc/status/961249107020001280 
Some more discussions here: https://github.com/jteeuwen/go-bindata/issues/3
@jackfrancis

**Comment by palmerabollo** [comment]
We forked acs-engine to use `containous/go-bindata`. The new `jteeuwen/go-bindata` is not trustworthy IMO.

**Comment by jackfrancis** [comment]
@JiangtianLi Do you have any thoughts here? Thanks @pidah for filing this!

**Comment by JiangtianLi** [comment]
@jackfrancis Look like we didn't vendor that. Let's find a reliable fork and vendor it. What do you think?

**Comment by jackfrancis** [comment]
Yes, we can investigate "reliable" after we cut the next release.

**Comment by CecileRobertMichon** [comment]
What's the status of this?
