### ISSUE TITLE
Add master nodes

### ISSUE THREAD

**Issue by starkilla2003** [Azure/acs-engine#2247]
**Is this a request for help?**:

yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

maybe FEATURE REQUEST

**What version of acs-engine?**:

all

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
all

**What happened**:
I wanted to ask if there is a way to add master nodes to an existing kubernetes cluster. We have a customer environment we cannot breakt down and redeploy that easily at the moment. Does anyone know a way to add worker nodes. If there is no actual way with acsengine at the moment i would request that feature for a future release.

**What you expected to happen**:
More worker nodes for HA cluster

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mwieczorek** [comment]
hi @starkilla2003 
have you tried the [scale command](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/scale.md) ?

**Comment by starkilla2003** [comment]
@mwieczorek As far as I see the scale command only works for agents and not for masters. Or am I missing something?

**Comment by mwieczorek** [comment]
@starkilla2003 yes. By 'worker nodes' I understand 'agents'. So sorry for misunderstanding

**Comment by CecileRobertMichon** [comment]
@starkilla2003 scale only works for agent nodes. As of today, the only way to add master nodes is to deploy a new cluster.

**Comment by starkilla2003** [comment]
@CecileRobertMichon Will this feature be implemented in the future? We are trying a manual scale up right now. But along the way there are alot of things that can go wrong. Certificates and etcd are the main issue there.

**Comment by CecileRobertMichon** [comment]
@starkilla2003 there is no current plan to implement it in the near future. Doing a manual scale up can be tricky, #1710 has some information on things that have been tried previously if that helps. I think the main issue with a manual scale up is that etcd communications are encrypted with TLS so new master nodes would need certs signed by the same ca as the existing ones and would need to be added to the etcd cluster (`etcdctl member add`).

**Comment by starkilla2003** [comment]
@CecileRobertMichon thank you for making it clearer to me.
