### ISSUE TITLE
Is it possible to deploy ACS locally on windows 1o

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/acs-engine#2248]
Is it possible to install AKS locally on my machine and deploy the ACS locally

**Comment by asubmani** [comment]
@VenkateshSrini . No. AKS  is a managed Kubernetes service in Azure. You won't be able to install it on a PC.  The same applies to ACS as well. However both of these will be available in Azure Stack (The Operating System for Azure, available for on-prem use). Either way AKS instances will exist in Azure/Azure stack; not on Windows 10.   You can however install the "Kubectl" tools on Windows 10 and manage your AKS instance :).

**Comment by JunSun17** [comment]
@asubmani thanks for the detailed explanation.
@VenkateshSrini will close this issue for now, please re-open if you still have further questions.
