### ISSUE TITLE
acs-engine admits location format that causes failure much later

### ISSUE THREAD

**Issue by itowlson** [Azure/acs-engine#2258]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: Current master at 12 Feb 2018

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**  Kubernetes

**What happened**:

I created a cluster using `acs-engine deploy --location "Australia Southeast"`.  This worked fine and the cluster was created in the Australia Southeast region.

Then I upgraded the cluster using `acs-engine upgrade --location "Australia Southeast" ...other parameters...`.  This command was accepted and the upgrade process was kicked off.  After many minutes the upgrade command attempted an ARM deployment which appeared to succeed, but then failed validation because it used the region name in the URL:

```
INFO[0279] Starting ARM Deployment (master-18-02-12T21.42.04-813459685). This will take some time...
INFO[0741] Finished ARM Deployment (master-18-02-12T21.42.04-813459685). Error: <nil>
INFO[0741] Error validating upgraded master VM: k8s-master-23389264-0
FATA[0741] Error upgrading cluster: host must be a URL or a host:port pair:
"https://itowlsonacsupgradetest.Australia Southeast.cloudapp.azure.com"
                                ^^^^^^^^^^^^^^^^^^^
```

**What you expected to happen**:  Either acs-engine should accept only the URL forms of region names (e.g. `australiasoutheast`), so that it fails quickly rather than during an upgrade, or it should map the friendly names when required.

**How to reproduce it** (as minimally and precisely as possible):

Upgrade a cluster using a friendly region name that contains spaces (e.g. "Australia Southeast").

**Anything else we need to know**:

**Comment by itowlson** [comment]
It looks like the result of not detecting the error until this point was that the cluster was left in a half-upgraded state, with one master upgraded but the others not upgraded.  I'm not sure what the impact of this would be in a production cluster...

**Comment by shubheksha** [comment]
For this one, I believe a check needs to be added here to ensure that the location name has no spaces: https://github.com/Azure/acs-engine/blob/master/cmd/scale.go#L99?
@CecileRobertMichon

**Comment by shubheksha** [comment]
@CecileRobertMichon, I believe we can pass in the `location` in the expected format (all lowercase, no spaces) here: https://github.com/Azure/acs-engine/blob/master/cmd/upgrade.go#L199?

**Comment by CecileRobertMichon** [comment]
@shubheksha I think this is the function we want https://github.com/Azure/acs-engine/blob/ec456b1637e1bd94bde0255e881f336a81bbc4ac/pkg/api/convertertoapi.go#L23 
Somehow it's being applied for deployments but not upgrade (and I suspect not scale either) so you can probably re-use it.

**Comment by shubheksha** [comment]
I didn't see `NormalizeAzureRegion` being called in any of those files. However, all three of them use [this](https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/engine.go#L289) method, so can we apply it here instead?
