### ISSUE TITLE
Scale command fails for AzureGermanCloud with 404 error

### ISSUE THREAD

**Issue by starkilla2003** [Azure/acs-engine#2262]
**Is this a request for help?**:
YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
Version: v0.12.5
GitCommit: 9fa6a690
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I tried to scale my agent pool from 2 to 3 with the following command:
`acs-engine scale --subscription-id <ID> --resource-group k8test  --location germanycentral --deployment-dir _output/k8stest --new-node-count 3`

I am currently working in the AzureCloudGermany.  My cluster was created with the following config:

{
  "apiVersion": "vlabs",
  "location": "germanycentral",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
        "networkPolicy": "calico",
        "maxPods": 16,
        "gcHighThreshold": 70,
        "gcLowThreshold": 40
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "k8stest",
      "vmSize": "Standard_D2_v2",
      "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "yesnodes",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "admin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

The scale command threw the following exception:
```
[36mINFO[0m[0000] validating...
[37mDEBU[0m[0000] Resolving tenantID for subscriptionID: 
[31mERRO[0m[0000] Unexpected response from Get Subscription: 404
[31mERRO[0m[0000] Failed to get client:Unexpected response from Get Subscription: 404
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x14068c3]

goroutine 1 [running]:
github.com/Azure/acs-engine/pkg/armhelpers.(*AzureClient).EnsureResourceGroup(0x0, 0xc04204c0e8, 0x6, 0xc04204c130, 0xe, 0x0, 0x410a51, 0xc04232c500, 0xa0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/pkg/armhelpers/groupsclient.go:11 +0xf3
github.com/Azure/acs-engine/cmd.(*scaleCmd).validate(0xc042439200, 0xc042262240, 0xc04218c6e0, 0x0, 0xb)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:118 +0x37c
github.com/Azure/acs-engine/cmd.(*scaleCmd).run(0xc042439200, 0xc042262240, 0xc04218c6e0, 0x0, 0xb, 0x1424c65, 0x5)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:180 +0x7e
github.com/Azure/acs-engine/cmd.newScaleCmd.func1(0xc042262240, 0xc04218c6e0, 0x0, 0xb, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:66 +0x59
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc042262240, 0xc04218c630, 0xb, 0xb, 0xc042262240, 0xc04218c630)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04226c480, 0xc042262240, 0xc04226db00, 0xc04226d440)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:726 +0x305
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04226c480, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:685 +0x32
main.main()
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/main.go:9 +0x2e
```

**What you expected to happen**:
Agent pool with 3 nodes

**How to reproduce it** (as minimally and precisely as possible):
Just run the scale command.

**Anything else we need to know**:
Please let me know if you need further information.

**Comment by starkilla2003** [comment]
Same happens if i use the upgrade parameter.

**Comment by starkilla2003** [comment]
Ok, i found the flag --azure-env "AZUREGERMANCLOUD" for acs-engine and with this it is working.

**Comment by digyou** [comment]
> Ok, i found the flag --azure-env "AZUREGERMANCLOUD" for acs-engine and with this it is working.

working for me, thanks~~
