### ISSUE TITLE
OSProvisioningTimedOut acs-engine Upgrade

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#2272]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

Version: v0.12.5
GitCommit: 9fa6a690
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Upgrading from 1.6.6 to 1.7.9

**What happened**:

I tried to upgrade my cluster from 1.6.6 to 1.7.9 but the upgrade process always failed in the same way.

"The resource operation completed with terminal provisioning state 'Failed'.

- OS Provisioning for VM 'k8s-agentpool1-34379092' did not finish in the alloted time.
The VM may still finish provisioning successfully.
Please check provisioning state later.

(Code: OSProvisioningTimedOut)"

**What you expected to happen**:

Complete the upgrade.

**How to reproduce it** (as minimally and precisely as possible):

Create a dummy cluster with 1 master and 3 slave nodes.

**Anything else we need to know**:

My cluster was created with the acs-engine v0.5.0. The apimodel.json was not compatible with the expected template with the latest version. I am in production and I need to upgrade this.

**Comment by CecileRobertMichon** [comment]
Hi @hmarcelodn, we are aware of this issue (see #2265) and are working on a solution. In the meantime, you can try re-running the upgrade operation and it should succeed after 1 or 2 retries. Could you please share your apimodel to help us debug the issue?

**Comment by hmarcelodn** [comment]
Hi @CecileRobertMichon ,

I tried yesterday re-running and it worked.

I am going to share next my apimodel.json sample.

Thanks a lot.

**Comment by hmarcelodn** [comment]
Closed due to #2265
