### ISSUE TITLE
Add capability to acs-engine to provision and destroy agent pools

### ISSUE THREAD

**Issue by bq1756** [Azure/acs-engine#2278]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
v0.12.5
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8+ in my case

**Request**:
As an automation engineer, I want to automatically provision and destroy Kubernetes agent pools using native acs-engine commands.

**Use cases**:
1 - Add performance testing to an automated CI pipeline....
Several development teams share a k8s cluster for general build/test/deploy activities.  A team wants to periodically load test their application without interferring with other teams' work.

Desire:  Add a step to the CI pipeline where development teams can deploy an isolated performance testing environment, run tests, then destroy the environment to save compute expenses.

Ask:  Add capability to acs-engine to provision a new (temporary) agent pool.  Add capability to acs-engine to remove an agent pool.

2 - Underlying VM sizing changes.....
I want to provision a new agent pool with the latest, greatest or most deeply discounted VMs, move my workload to the new agent pools/VMs, then destroy to old agent pool.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by todoesverso** [comment]
Is there any update on this? Planned?
I would really use such a feature in my production cluster.
