### ISSUE TITLE
v.0.13.0 - Custom VNET not yet supported with Windows-enabled clusters

### ISSUE THREAD

**Issue by idanshahar** [Azure/acs-engine#2283]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

v.0.13.0

If this is a ISSUE, please:
The previous version supported a Custom Vnet for Windows-enabled cluster, now somehow the latest version does not support this feature. Is this planned? 

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.1

**What happened**:
Failed to generate Windows-enabled Kubernetes Cluster inside custom Vnet.

**How to reproduce it** (as minimally and precisely as possible):
Generate a hybrid cluster inside Custom Vnet with acs-engine v.0.13.0

**Comment by hmarcelodn** [comment]
I dont think its working in Linux either. #2284 I am experiencing that issue. Possible related to limited functionality with the latest versions. I was using v0.12.5 just in case.

**Comment by patrick-motard** [comment]
What version supported custom Vnets? I deployed a hybrid 1.7 cluster a few months back and found that the cluster would provision completely with the exception of the windows nodes. I participated in a few Issues regarding this and requested that the documentation be updated to state this known limitation. It was updated and can be found here. 1.8 and 1.9 were out when that happened. So maybe you succeeded with a version prior to 1.7? 

I wish i could remember what version of the acs-engine i was using.

[Documentation](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md) stating the limitation. 
[Open Issue.](https://github.com/Azure/acs-engine/issues/1767)

**Comment by idanshahar** [comment]
@patrick-motard 
seems that v0.12.5 support Custom Vnet + Hybrid Cluster (Without CNI)

**Comment by patrick-motard** [comment]
@idanshahar oooh awesome! I will try that out.

**Comment by CecileRobertMichon** [comment]
validation was intentionally added in https://github.com/Azure/acs-engine/pull/2168 since support for custom vnets + windows was broken. The check has now been removed but note that custom vnet support for Windows is experimental and there are some known issues.
