### ISSUE TITLE
Acs-Engine Scale is not working (Vm Disk not created)

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#2285]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

0.12.5

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

I updated my 1.6.6 cluster into 1.9.1 using acs-engine upgrade command line successfully. After that I tried the acs-engine scale command line and it was failing. The error was no specified in the stdout but I was able to check at the deployments section in my cluster resource group seeing the following message:

> Changing property 'dataDisk.createOption' is not allowed. (Code: PropertyChangeNotAllowed, Target: dataDisk.createOption)

**What you expected to happen**:

Scale up properly.

**How to reproduce it** (as minimally and precisely as possible):

I did it moving from 1.6.6 to 1.9.1 and then running scale command against the upgraded cluster.

**Anything else we need to know**:

N/A

**Comment by hmarcelodn** [comment]
It just failed once. It worked. Closing.

**Comment by valer-cara** [comment]
Just hit it too. A re-run doesn't help. Still investigating..

**Comment by todoesverso** [comment]
I hit it too :(

**Comment by hmarcelodn** [comment]
Try re-launching the CLI
