### ISSUE TITLE
Upgrade 1.7.4 -> 1.8.7 failed. Etcd on master-0 has switched to HTTPS and can't communicate with the older 2 etcd nodes.

### ISSUE THREAD

**Issue by valer-cara** [Azure/acs-engine#2290]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
Version: v0.12.4
GitCommit: 069d9e4

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:

*TL;DR* - etcd switched to using HTTPS and it can't connect to the other 2 older nodes.

Upgrade 1.7.4 to 1.8.7 fails on the first master machine. Here's my path through the cascade of failures:

- FIrst sign is kubelet outputting: `network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR`

- Seems that the controller manager is responsible to set the podcidr in this setup, since it's ran with `--allocate-node-cidrs=true`. In the logs of the CM it's failing to contact the apiserver: `error retrieving resource lock kube-system/kube-controller-manager: Get https://10.240.255.5:443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp 10.240.255.5:443: getsockopt: connection refused `

- The apiserver is not responsive since it exits pretty soon after kubelet starts it initially, due to numerous timeout errors on many of it's endpoints and finally
```
E0215 20:43:37.021444       1 client_ca_hook.go:78] Timeout: request did not complete within allowed duration
F0215 20:43:37.021871       1 hooks.go:133] PostStartHook "ca-registration" failed: unable to initialize client CA configmap: timed out waiting for the condition
```

- Seems that etcd has died on this new node. Digging through i found that etcd's args have switched from http to https on the new node and it can't communicate with the other 2 etcd nodes.

**What you expected to happen**:
Upgrade would complete.

**How to reproduce it** (as minimally and precisely as possible):
I guess upgrading from 1.7.4 to 1.8.7? Didn't attempt to reproduce yet.

**Anything else we need to know**:

~~I'm thinking of switching all etcds sequentially to http to allow the upgrade to complete, then switch them all back to https? Would you suggest otherwise?~~

**Comment by CecileRobertMichon** [comment]
@valer-cara what version of acs-engine was your cluster built with?

**Comment by valer-cara** [comment]
@CecileRobertMichon - quite an old one - the machines were created on `28 Aug 2017`, and I believe it was 0.5.0 (maybe this e2643431594bb908cb9ee1019c75389957787a94)

**Comment by valer-cara** [comment]
Ultimately I've restored the data dir, but it seems etcd is also updated `remote version is too low: remote[91d25258d70ad868]=2.2.5, local=3.2.11`.

**Comment by valer-cara** [comment]
So I managed to downgrade etcd on master-0, recreate the etcd cluster from a backup, set apiserver on master-0 to use the `etcd2` storage backend - the components booted and the cluster's alive once again.

Now I'll neet to upgrade etcd 2.2.5 -> 3, re-enable TLS.

**Comment by CecileRobertMichon** [comment]
Did you manually edit your apimodel before running the upgrade (the answer should be yes since some of the json properties have changed names since v0.5.0)? Could you please share what your apimodel looked like (how many masters/agents, any optional features turned on, etc.)? I'm trying to repro to see what went wrong. Upgrade to tls should be backward compatible and was tested with v0.11.0 but it's very possible that there are other things to account for that differ in v0.5.0.

**Comment by valer-cara** [comment]
I dug through the git history in my repo of the output/* files, hope I didn't miss anything, but these should be the edits and the initial .json (I've noticed that `kubeletConfig` change):

```diff
--- a/apimodel.json
+++ b/apimodel.json
@@ -10,11 +10,13 @@
         "clusterSubnet": "10.244.0.0/16",
         "networkPolicy": "none",
         "maxPods": 110,
-        "DockerBridgeSubnet": "172.17.0.1/16",
-        "nodeStatusUpdateFrequency": "10s",
-        "ctrlMgrNodeMonitorGracePeriod": "40s",
-        "ctrlMgrPodEvictionTimeout": "5m0s",
-        "ctrlMgrRouteReconciliationPeriod": "10s"
+        "dockerBridgeSubnet": "172.17.0.1/16",
+        "kubeletConfig": {
+          "--node-status-update-frequency": "10s"
+        },
+        "controllerManagerConfig": {
+          "--node-monitor-grace-period": "40s",
+          "--pod-eviction-timeout": "5m0s",
+          "--route-reconciliation-period": "10s"
         }

       }
     },
```

The initial one was:

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.7",
      "orchestratorVersion": "1.7.4",
      "kubernetesConfig": {
        "kubernetesImageBase": "gcrio.azureedge.net/google_containers/",
        "clusterSubnet": "10.244.0.0/16",
        "networkPolicy": "none",
        "maxPods": 110,
        "DockerBridgeSubnet": "172.17.0.1/16",
        "nodeStatusUpdateFrequency": "10s",
        "ctrlMgrNodeMonitorGracePeriod": "40s",
        "ctrlMgrPodEvictionTimeout": "5m0s",
        "ctrlMgrRouteReconciliationPeriod": "10s"
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "...",
      "vmSize": "Standard_D2_v2",
      "osDiskSizeGB": 200,
      "firstConsecutiveStaticIP": "10.240.255.5",
      "storageProfile": "ManagedDisks",
      "oauthEnabled": false
    },
    "agentPoolProfiles": [
      {
        "name": "agent",
        "count": 3,
        "vmSize": "Standard_DS4_v2",
        "osDiskSizeGB": 200,
        "osType": "Linux",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "fqdn": ""
      }
    ],
    "linuxProfile": {
      "adminUsername": "...",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "..."
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "...",
      "secret": "..."
    },
    "certificateProfile": {
      "caCertificate": "...",
      "caPrivateKey": "...",
      "apiServerCertificate": "...",
      "apiServerPrivateKey": "...",
      "clientCertificate": "...",
      "clientPrivateKey": "...",
      "kubeConfigCertificate": "...",
      "kubeConfigPrivateKey": "..."
    }
  }
}
```

The current one is:

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.7",
      "orchestratorVersion": "1.7.4",
      "kubernetesConfig": {
        "kubernetesImageBase": "gcrio.azureedge.net/google_containers/",
        "clusterSubnet": "10.244.0.0/16",
        "networkPolicy": "none",
        "maxPods": 110,
        "dockerBridgeSubnet": "172.17.0.1/16",
        "kubeletConfig": {
          "--node-status-update-frequency": "10s"
        },
        "controllerManagerConfig": {
          "--node-monitor-grace-period": "40s",
          "--pod-eviction-timeout": "5m0s",
          "--route-reconciliation-period": "10s"
        }
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "...",
      "vmSize": "Standard_D2_v2",
      "osDiskSizeGB": 200,
      "firstConsecutiveStaticIP": "10.240.255.5",
      "storageProfile": "ManagedDisks",
      "oauthEnabled": false,
      "preProvisionExtension": null,
      "extensions": []
    },
    "agentPoolProfiles": [
      {
        "name": "agent",
        "count": 3,
        "vmSize": "Standard_DS4_v2",
        "osDiskSizeGB": 200,
        "osType": "Linux",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "fqdn": "",
        "preProvisionExtension": null,
        "extensions": []
      },
      {
        "name": "highio",
        "count": 6,
        "vmSize": "Standard_L4s",
        "osDiskSizeGB": 32,
        "osType": "Linux",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "fqdn": "",
        "preProvisionExtension": null,
        "extensions": []
      }
    ],
    "linuxProfile": {
      "adminUsername": "...",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "..."
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "...",
      "secret": "..."
    },
    "certificateProfile": {
      "caCertificate": "...",
      "caPrivateKey": "...",
      "apiServerCertificate": "...",
      "apiServerPrivateKey": "...",
      "clientCertificate": "...",
      "clientPrivateKey": "...",
      "kubeConfigCertificate": "...",
      "kubeConfigPrivateKey": "..."
    }
  }
}
```

**Comment by valer-cara** [comment]
ATM my masters config is:

- master-0: 1.8.7 manually adjusted to run etcd 2.2, no TLS for compat with the rest
- master-1: 1.7.4 default config, etcd 2.2
- master-2: 1.7.4 default config, etcd 2.2 

I'll manually upgrade etcd on all machines to 3.2.11 (the one provisioned by the upgrade), set them to use TLS and then just re-run the upgrade. Not sure if i'm missing anything, but I'll jump to it, hope not to crash anything :boom:
