### ISSUE TITLE
Enabling PodSecurityPolicy does not enable apparmor on nodes

### ISSUE THREAD

**Issue by Chewie** [Azure/acs-engine#2296]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.13.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.3

**What happened**:

Enabling the (not yet documented) flag `KubernetesConfig.EnablePodSecurityPolicy`, along with its required flag `KubernetesConfig.EnableRbac`, effectively adds the PodSecurityPolicy admission controller to the ApiServer, but this is not enough according to the [Kubernetes documentation](https://kubernetes.io/docs/tutorials/clusters/apparmor/). In particular, this feature requires apparmor to be enabled on all nodes, along with an additionnal flag to the ApiServer, `--runtime-config=extensions/v1beta1/podsecuritypolicy[,others...]`.

Currently, running a pod puts it in a `Blocked` state, with the following description:

~~~
Annotations:    container.apparmor.security.beta.kubernetes.io/nginx=runtime/default
                kubernetes.io/psp=restricted
                seccomp.security.alpha.kubernetes.io/pod=docker/default
Status:         Pending
Reason:         AppArmor
Message:        Cannot enforce AppArmor: AppArmor is not enabled on the host
~~~

**What you expected to happen**:

Enabling the `KubernetesConfig.EnablePodSecurityPolicy` flag should, in addition to the admission controller, do the following:

* Add the `--runtime-config=extensions/v1beta1/podsecuritypolicy[,others...]` flag
* Configure apparmor on the nodes

**How to reproduce it** (as minimally and precisely as possible):

Start from the example `kubernetes.json` provided and add  "EnablePodSecurityPolicy" and "EnableRbac" to the `kubernetesConfig` field.

**Anything else we need to know**:

**Comment by khaldoune** [comment]
+1

**Comment by yastij** [comment]
Cc @jackfrancis @pidah PTAL

**Comment by jackfrancis** [comment]
@pidah This looks like something we can add pretty easily. Let me know if you don't have cycles to do this. Also, once we have this working, it'd be great to build some functional E2E test behaviors on top of these clusters. Open to suggestions on how to simply, functionally prove out basic symptoms of "working".

**Comment by pidah** [comment]
@jackfrancis I am pretty busy atm, so happy for someone else to take this... +1 for tests 👍

**Comment by Chewie** [comment]
Analysis of the problem with @yastij showed that the problem wasn't the enabling of apparmor, but the missing mount of apparmor_parser in the kubelet that triggered this message.

Closing this issue in favor of #2319
