### ISSUE TITLE
Failed upgrade from kubernetes 1.9.1 to 1.9.3

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/acs-engine#2301]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
 v0.13.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

1.9.1 -> 1.9.3
**What happened**:
FATA[0098] Error upgrading cluster: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."

**What you expected to happen**:
Upgrade is completed

**How to reproduce it** (as minimally and precisely as possible):
"networkPolicy": "azure"

**Anything else we need to know**:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"PrivateIPAddressIsAllocated\",\r\n \"message\": \"IP configuration /subscriptions/xx-x-x-x-x-x-x-x-x-/resourceGroups/xx-xxx-xx/providers/Microsoft.Network/networkInterfaces/k8s-master-30347309-nic-0/ipConfigurations/ipconfig1 is using the private IP address 10.240.0.4 which is already allocated to resource /subscriptions/xxx-xx-x-x-x-x-x-x-xx/resourceGroups/xx-xxx-xx/providers/Microsoft.Network/networkInterfaces/k8s-agentpool1-30347309-nic-0.\",\r\n \"details\": []\r\n }\r\n}"}]}

**Comment by IvanovOleg** [comment]
I've destroyed my cluster because of this issue. It looks like acs-engine is unable to check if ip address is allocated or not and fails each time.

**Comment by JunSun17** [comment]
@IvanovOleg there is a known issue that the second upgrade will introduce problems like this. Just curious, has your cluster already been upgraded before this upgrade?

**Comment by IvanovOleg** [comment]
@JunSun17 It's the first upgrade since I've started using Azure network

**Comment by JunSun17** [comment]
@IvanovOleg can you attach your cluster definition here so we can investigate this issue further? Thanks!

**Comment by IvanovOleg** [comment]
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.9.1",
      "kubernetesConfig": {
        "networkPolicy": "azure",
        "enableRbac": true,
        "apiServerConfig": {
          "--admission-control": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,DenyEscalatingExec,AlwaysPullImages"
        }
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "xx-xxx-xxx",
      "vmSize": "Standard_D2_v2",
      "storageProfile" : "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile" : "ManagedDisks"
      }
    ],
    "linuxProfile": {
      "adminUsername": "xxxxx",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

**Comment by IvanovOleg** [comment]
@JunSun17 As far as I remember I used v0.12.2 for the original deployment. I think you should create ~ 30-40 dummy containers before upgrade to allocate a lot of ips.

**Comment by mtgerb** [comment]
I run into the same issue, when upgrading kubernetes from 1.8.7 to 1.8.8. Have also used acs-engine v.0.12.2 and upgraded to version v0.13.0 before trying to upgrade the cluster.

**Comment by JunSun17** [comment]
@IvanovOleg @mtgerb Thanks for reporting this issue. I suspect upgrade with v0.13.0 may introduce this issue if the original deployment is not using v0.13.0. I will do some further testing and update on this issue.

**Comment by JunSun17** [comment]
Yes, there is an issue if the original deployment is not using v0.13.0. v0.13.0 reserves static IPs for master nodes but these IPs might have been taken already by other nodes deployed with an early version. I am investigating on a solution for this.

**Comment by IvanovOleg** [comment]
@JunSun17 Thanks! Maybe it's a good idea to have some kind of command line parameter that handles the range of ips as a backup plan for situations like this.
