### ISSUE TITLE
Inter pod communication

### ISSUE THREAD

**Issue by narindergoyal** [Azure/acs-engine#2311]
**Is this a request for help?**:Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):Issue

---

**What version of acs-engine?**:latest

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
We have setup the acs-engine environment and we were working on setting up nginx-ingress-controller on that environment. What is happening that here inter pod communication is not working. 
If our nginx-ingress-controller is on agent-0 and other pods are also on same agent, we are able hit the services. 
However If our nginx-ingress-controller is on agent-1 and other pods are on different agent say agent-2, we are not able hit the services. 

**What you expected to happen**:
Inter pod communication should be working

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by mwieczorek** [comment]
@narindergoyal in case you used custom vnets nad networkPolicy=none/calico  - did you update the subnets with route table? (https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#feat-custom-vnet)
