### ISSUE TITLE
Have a single microservice (2 pods on different nodes) that is not communicating

### ISSUE THREAD

**Issue by vannovv** [Azure/acs-engine#2317]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.12.5
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.6

**What happened**:
I have a single microservice among 6 other microservices that are Internet facing that is not responding.  The other Internet exposed microservices appear to be working fine.  All are on the same subnet and spread out across 3 different nodes for that namespace.  I have Calico enabled and policies applied to all of the microservices pods (but it is my understanding that Calico can't restrict inbound or outbound traffic from outside of the cluster, just pod to pod).  If I get on the node that is hosting the pod I can telnet over to the internal K8S ip for the pod on port 80 but if I go over to one of the other nodes in the namespace and in the same subnet and try it times out.  The microservice appears to be happy from what I am seeing in the pod console and the pod logs, K8S seems to think the pods are happy.  The k8s service for this microservice registered the "external IP" (the azure IP) in the internal azure load balancer that is managed by K8S.  Everything I have looked at seems to be correct and consistent with other services that are working.  I have removed the replication group and the K8S service and re-deployed the microservice so that K8S can recreate everything but got the same result. Not sure what to look at from here.  

**What you expected to happen**:
To be able to access this microservice from the Internet

**How to reproduce it** (as minimally and precisely as possible):
Can provide the scripted install of the cluster and policies applied if needed.

**Anything else we need to know**:
The only thing I have found and I dont know if it could be related is an error on the nodes when I describe the nodes via kubectl: 

Warning  FailedNodeAllocatableEnforcement  4m (x11666 over 8d)  kubelet, k8s-fe-19053462-2  Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to wr
ite 33718095872 to memory.limit_in_bytes: write /var/lib/docker/overlay2/c7f1dfb1194f009975dff70eeb618fa46f50a189858f2c255dd820b7184e62d5/merged/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument

Also worth noting, we have this up and running using acs-engine v0.5.0 and K8S 1.6.6 and have built multiple clusters with no problems.

**Comment by jackfrancis** [comment]
@dtzar Can you validate the calico assumptions above, just to rule that out?

> I have Calico enabled and policies applied to all of the microservices pods (but it is my understanding that Calico can't restrict inbound or outbound traffic from outside of the cluster, just pod to pod).

**Comment by vannovv** [comment]
Just to make sure I was clear. We are applying this same Calico policy file across 5 different clusters that are all built from the same scripts, so pretty close to identical,and they are all working fine.  For this cluster we updated the ACS Engine and K8S versions and I pulled the vnet out of the K8S resource group and put it into its own resource group to give us more flexibility.

**Comment by dtzar** [comment]
Calico does natively have the capabilities to restrict in or outbound connections to the pods.  This is highlighted in this tutorial: https://docs.projectcalico.org/v3.0/getting-started/kubernetes/tutorials/advanced-policy  which is also linked to from [our readme](https://github.com/Azure/acs-engine/tree/master/examples/networkpolicy#post-installation).  

There are a number of different ways to troubleshoot calico policies, but looks like you got it figured out.

**Comment by sheigel** [comment]
@dtzar would you point some resource for troubleshooting network policies?

**Comment by dtzar** [comment]
These two calico troubleshooting links are helpful along with general ubunutu networking skills like `iptables` ;)
https://docs.projectcalico.org/v3.0/usage/troubleshooting/
https://docs.projectcalico.org/v3.0/getting-started/kubernetes/troubleshooting
