### ISSUE TITLE
Name labe missing when creating cluster wiuth acs-engine

### ISSUE THREAD

**Issue by andrehe001** [Azure/acs-engine#2333]
hi all, I've created a hybrid cluster with 1 linux and 1 windows node with the acs template in the samples/windows folder. What I do not see is a name for the cluster which I need to run az acs kubernetes get-credentials --name clustername --resource-group hybrid-xxx --ssh-key-file C:\path\myPrivateKey_rsa.

Anyone know, if I can add a cluster name after the installation or what I have to change in the json template to add a cluster name?

**Comment by imranq2** [comment]
you usually pass the cluster name with the -n parameters to az group deployment.  e.g.,
az group deployment create `
    --template-file "$acsoutputfolder\azuredeploy.json" `
    --resource-group $AKS_PERS_RESOURCE_GROUP -n $AKS_CLUSTER_NAME `
    --parameters "$acsoutputfolder\azuredeploy.parameters.json" `
    --verbose

**Comment by CecileRobertMichon** [comment]
If you used the deploy command to create your cluster (`bin/acs-engine deploy`) your cluster name is the dns-prefix string you used.
