### ISSUE TITLE
expose kube-schedulerConfig

### ISSUE THREAD

**Issue by yastij** [Azure/acs-engine#2336]
We are currently facing an acs-engine limition. Kube-scheduler is not user-configurable, we can't configure it in our kubernetes.json

the use case would be tipically configure --address, scheduler-policy etc..

cc @jackfrancis @pidah

**Comment by JunSun17** [comment]
this looks to be similar to work you have done for api-server, etc. @jackfrancis 

I think another temporary solution is you can modify the deployed file /etc/kubernetes/manifests/kube-scheduler.yaml, and restart kube-scheduler pods.

**Comment by yastij** [comment]
that is what we are doing right now with ansible. However, we are trying to close these gaps.

**Comment by jackfrancis** [comment]
@yastij I'll aim to get to this this week, please bug me next week if you don't hear any status. :)

**Comment by yastij** [comment]
Sure, thanks !!

**Comment by yastij** [comment]
cc @jackfrancis
