### ISSUE TITLE
acs-engine scale: Unknown JSON tag nonMasqueradeCidr

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/acs-engine#2345]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**:  Version: v0.13.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

**What happened**: I tried to scale up|down a k8s cluster but I get the error:
INFO[0000] validating...                                
INFO[0002] Error returned by LoadContainerService: Unknown JSON tag nonMasqueradeCidr 
FATA[0002] error parsing the api model: Unknown JSON tag nonMasqueradeCidr 

**What you expected to happen**: My cluster to scale up|down

**How to reproduce it** (as minimally and precisely as possible): 
acs-engine scale --subscription-id ${ID} --resource-group ${RG} --location westeurope --deployment-dir /home/builduser/acsengine/_output/${CLUSTER} --new-node-count 2 --node-pool ${AGENTPOOL} --master-FQDN ${CLUSTER}.westeurope.cloudapp.azure.com

**Comment by CecileRobertMichon** [comment]
Hi @bramvdklinkenberg, please see issue #2060 which explains how to workaround this issue.
