### ISSUE TITLE
Error while Scaling down Agent Nodes in Kubernetes

### ISSUE THREAD

**Issue by nikparmar** [Azure/acs-engine#2355]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:

We have an ACS cluster with 3 agent Nodes and from the portal I scaled it upto 10 Nodes it worked but when I did a scale down to 1 Again.
Got this error:
Failed to save container service 'dp-acs-monitoring3'. Error: Scaling down agents for container service 'dp-acs-monitoring3' in resource group 'dp_acs_dev3' failed with errors: Resource type: 'Microsoft.Compute/virtualMachines', name: 'k8s-agent-706AC3A8-1', error code: 'ScaleDownInternalError', message: Resource type: 'Microsoft.Compute/virtualMachines', name: 'k8s-agent-706AC3A8-3', error code: 'ScaleDownInternalError', message: Resource type: 'Microsoft.Compute/virtualMachines', name: 'k8s-agent-706AC3A8-4', error code: 'ScaleDownInternalError', message: Resource type: 'Microsoft.Compute/virtualMachines', name: 'k8s-agent-706AC3A8-5', error code: 'ScaleDownInternalError', message: Resource type: 'Microsoft.Compute/virtualMachines', name: 'k8s-agent-706AC3A8-6', error code: 'ScaleDownInternalError', message: Resource type: 'Microsoft.Compute/virtualMachines', name: 'k8s-agent-706AC3A8-7', error code: 'ScaleDownInternalError', message: Resource type: 'Microsoft.Compute/virtualMachines', name: 'k8s-agent-706AC3A8-8', error code: 'ScaleDownInternalError', message: Resource type: 'Microsoft.Compute/virtualMachines', name: 'k8s-agent-706AC3A8-9', error code: 'ScaleDownInternalError', message:

And the ACS cluster went into failes state
**What you expected to happen**:
to scale down normally

**How to reproduce it** (as minimally and precisely as possible):
Scale upto 10 nodes and then scale down to 1

**Anything else we need to know**:
We have tried using API's also and from portal facing same issue when Kubernetes is in GA

**Comment by JunSun17** [comment]
@nikparmar Which version of acs-engine are you using?
