### ISSUE TITLE
Evaluate how we configure docker (and nodes in general) for Kubernetes

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#236]
This is regarding the scramble we had two weeks ago for the docker upgrade breaking clusters.

See the upstream issue: https://github.com/kubernetes/kubernetes/issues/40182 which features suggestions beyond pinning to `1.12.x`. Additionally, it's [suggested that we simply tell `docker` to not configure iptables at all](https://twitter.com/thockin/status/826999681800630272).

This partially serves as a reminder to see if sig-node has a list of published guidelines. If not, pinging thockin after he's back from vacation to see if he's aware of a list.

Also, as a reminder to watch upstream to see how they handle it (a patch in Kube, a recommendation to change docker's config json, etc).

**Comment by colemickens** [comment]
We should look at the doc that @brendandburns sent around from Deis when we do this.

**Comment by colemickens** [comment]
Also, we need to keep this under consideration for 1.6 and newer addon manager, etc:

* [Supports 'ensure exist' class addon in Addon-manager #40108](https://github.com/kubernetes/kubernetes/pull/40108) - changes how addon manager treats annotations
* [Create a default StorageClass for Azure](https://github.com/kubernetes/kubernetes/issues/40071) - StorageClass addon with addon-manager will replace the existing admission controller.

**Comment by colemickens** [comment]
Also:
`kubelet.go:1145] Image garbage collection failed: unable to find data for container /`.

**Comment by anhowe** [comment]
closing as not specific enough.
