### ISSUE TITLE
Scaling does not work on upgraded clusters with multiple agent nodes

### ISSUE THREAD

**Issue by JunSun17** [Azure/acs-engine#2362]
**Is this a request for help?**:

No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

v0.12.0, the earlier version might have the same problem

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

First upgrade a cluster with 3 agent nodes. When scale up or down, got the following errors:

```
./bin-v0.12.0/acs-engine scale --subscription-id xyz --deployment-dir ./_output/xyz  --location westus2 --resource-group xyz  --master-FQDN "xyz.westus2.cloudapp.azure.com"--node-pool "agentpool1" --new-node-count 1 --auth-method client_secret --client-id xyz  --client-secret xyz
INFO[0000] validating...
INFO[0003] Name suffix: 34851071
ERRO[0004] Failed to drain node , got error resource name may not be empty
ERRO[0004] Got error Node '' failed to drain with error: 'resource name may not be empty', while draining the nodes to be deleted
Error: Node '' failed to drain with error: 'resource name may not be empty'
Usage:
  acs-engine scale [flags]
Flags:
      --auth-method device        auth method (default:device, `client_secret`, `client_certificate`) (default "device")
      --azure-env string          the target Azure cloud (default "AzurePublicCloud")
      --certificate-path string   path to client certificate (used with --auth-method=client_certificate)
      --classic-mode              enable classic parameters and outputs
      --client-id string          client id (used with --auth-method=[client_secret|client_certificate])
      --client-secret string      client secret (used with --auth-mode=client_secret)
      --deployment-dir generate   the location of the output from generate
  -h, --help                      help for scale
      --language string           language to return error messages in (default "en-us")
      --location string           location the cluster is deployed in
      --master-FQDN string        FQDN for the master load balancer, Needed to scale down Kubernetes agent pools
      --new-node-count int        desired number of nodes
      --node-pool string          node pool to scale
      --private-key-path string   path to private key (used with --auth-method=client_certificate)
      --resource-group string     the resource group where the cluster is deployed
      --subscription-id string    azure subscription id
Global Flags:
      --debug   enable verbose debug logs
FATA[0004] Node '' failed to drain with error: 'resource name may not be empty'
```

```
./bin-v0.12.0/acs-engine scale --subscription-id xyz --deployment-dir ./_output/xyz  --location westus2 --resource-group xyz  --master-FQDN "xyz.westus2.cloudapp.azure.com"--node-pool "agentpool1" --new-node-count 5 --auth-method client_secret --client-id xyz  --client-secret xyz
INFO[0000] validating...
INFO[0004] Name suffix: 34851071
INFO[0004] Found no resources with type Microsoft.Network/routeTables in the template.  source="scaling command line"
INFO[0004] Starting ARM Deployment (xyz). This will take some time...
INFO[0164] Finished ARM Deployment (xyz).
FATA[0164] resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
```

**What you expected to happen**:

Scaling should work.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

For the case with 3 agent nodes, notice the numbering of agent nodes is changed from 0, 1, 2 to 0, 1, 3 after upgrading. this might be related to the scaling issue.

**Comment by ITler** [comment]
interesting... with `0.12.0` I am able to scale. I run on AzureGermanCloud facing many issues I can't explain. 
However when *upgrading* the cluster, I've seen the numbering issue as well...
After a debug session with Microsoft, they found an issue on their side as the numbering issue causes me to not be able to remove the resource group which contained the cluster. I needed to manually delete the faulty ARM deployment to finally get rid of the resource group in my particular case. However, I **guess** there is something f**ked up on Azure side, I think, as long as you didn't change anything on the files produced by acs-engine. Too, it would be (always) interesting to see your (cleaned) acs-engine config and know which cloud you are running.

**Comment by khaldoune** [comment]
@jackfrancis @@jcorioland

**Comment by jackfrancis** [comment]
This is a known functionality gap.

**Comment by khaldoune** [comment]
@jackfrancis This is a very important feature for production ready clusters. As you can guess, not all workloads that will be deployed on kubernetes will have the same requirements.
Is it possible to provide more details about this issue? This is something that happens only on upgraded clusters? Is it planned to fix this issue?
Thanks
Cc @jcorioland

**Comment by yastij** [comment]
@jackfrancis - I can reproduce with 1 agentpool.

```
 "agentPoolProfiles": [
      {
        "name": "workers0",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "osDiskSizeGB": 80,
        "osType": "Linux",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "diskSizesGB": [
          50
        ],
```
as you can see here, we try to update nodes using client-go

https://github.com/Azure/acs-engine/blob/244055e309cbf2732e370260e1340ab147b36325/pkg/operations/cordondrainvm.go#L54-L63

resulting in the following error `resource name may not be empty`.

the error gets to the calling function:

https://github.com/Azure/acs-engine/blob/244055e309cbf2732e370260e1340ab147b36325/pkg/operations/cordondrainvm.go#L34-L41


the root cause seems to be around here:

https://github.com/Azure/acs-engine/blob/244055e309cbf2732e370260e1340ab147b36325/cmd/scale.go#L231-L234


we might need to add a check here on vm names

https://github.com/Azure/acs-engine/blob/244055e309cbf2732e370260e1340ab147b36325/cmd/scale.go#L205-L211

**Comment by khaldoune** [comment]
@jackfrancis @CecileRobertMichon 
@yastij and I are working on the same project. Thanks for your assistance.
@yastij Is it feasable to work on a forked version and push a pull request?

**Comment by yastij** [comment]
I'm at kubeCon, but I can manage to find some time and send a PR. I the mean time I'm fine with backporting the patch in our current version until the release.

**Comment by yastij** [comment]
@jackfrancis @CecileRobertMichon - the only difference between `az vm list -g` and the api call done here: `vms, err := sc.client.ListVirtualMachines(sc.resourceGroupName)` is api version. 

We are currently using in acs-engine `2016-04-30-preview`. az CLI uses `2017-12-01`. We might need to bump azure-sdk-go version.

**Comment by jackfrancis** [comment]
@JackQuincy Would you have cycles to look into this anytime soon? Essentially:

1) upgrade + scale
2) inspect possible stale Azure API versions for certain resources
3) consider upgrading azure-sdk-for-go

To be clear, as far as I know, upgrade +scale against the same cluster has always been flaky, so this is adding additional resilience around these acs-engine features.

**Comment by oivindoh** [comment]
We've also seen this, unfortunately not until after upgrading our production cluster recently.

This makes me somewhat concerned, as we're approaching the need to scale up our node count a bit, and I'm wondering if this will put us in an entirely failed state.

Here's the full acs-engine upgrade log (acs-engine 0.18.3) from our 1.9.7 to 1.10.4 upgrade in case it's useful:

[log_upgrade_1_9_7_to_1_10_4.log](https://github.com/Azure/acs-engine/files/2101619/log_upgrade_1_9_7_to_1_10_4.log)
