### ISSUE TITLE
enablePrivateCluster flag failing

### ISSUE THREAD

**Issue by SilvioPilato** [Azure/acs-engine#2383]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.13.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.7.7

**What happened**:
We tried to deploy the following json template on a custom vnet with acs-engine, but running acs-engine deploy on it returned the following error:

INFO[0000] Error returned by LoadContainerService: Unknown JSON tag enablePrivateCluster
FATA[0000] error validating generateCmd: error parsing the api model: Unknown JSON tag enablePrivateCluster

`{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.7.7",
      "kubernetesConfig": {
        "networkPolicy": "calico",
        "enablePrivateCluster": true
      }
    },
    "masterProfile": {
      "count": 3,
      "vmSize": "Standard_DS3_v2",
      "dnsPrefix":"xxx",
      "vnetSubnetId":"xxx",
      "firstConsecutiveStaticIp":"xxx",
      "vnetCidr": "10.12.195.16/28"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_DS3_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId":"xxx"
      }
    ],
    "linuxProfile": {
      "adminUsername": "xxx",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "xxx"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "xxx",
      "secret": "xxx"
    }
  }
}`

**What you expected to happen**:
To have a private kubernetes cluster deployed on target vnet

**How to reproduce it** (as minimally and precisely as possible):
Run acs-engine deploy on given api-model

**Comment by CecileRobertMichon** [comment]
Hi @SilvioPilato, the `"enablePrivateCluster"` tag was recently merged into acs-engine master and has not been included in a release yet. If you want to play with the feature before the next release you can [build from the master branch.](https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md#build-acs-engine-from-source)

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/releases/tag/v0.14.0 was just released with this feature
