### ISSUE TITLE
nslookup can't resolve 'kubernetes.default' 

### ISSUE THREAD

**Issue by Satya-26** [Azure/acs-engine#2386]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 13.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**: nslookup can't resolve 'kubernetes.default' 

**What you expected to happen**:  Able to resolve kubernetes.default. below is the expected output:
$ kubectl exec -ti busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes.default
Address 1: 10.0.0.1

**How to reproduce it** (as minimally and precisely as possible): Deploy the Kubernetes cluster in Custom VNet in Micrososft Azure

**Anything else we need to know**: Nothing

**Comment by ITler** [comment]
As a kind hint, I would suggest to provide more information here, as it is very hard for the people to help without knowing what you really bootstrapped.
Which Azure cloud do you work with? How does the acs-config JSON look like (remove sensitive data before posting)?

**Comment by jackfrancis** [comment]
Are you doing this from within a running pod (e.g., busybox)? I'm not able to repro on a 1.9 cluster:

```
$ kubectl run -i -t busybox --image=busybox --restart=Never
If you don't see a command prompt, try pressing enter.
/ # nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.0.0.1 kubernetes.default.svc.cluster.local
```
