### ISSUE TITLE
acs-engine deploy command adds auto-sufix even if it is not specified

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/acs-engine#2387]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.13.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.3

**What happened**:
I've deployed a brand new kubernetes cluster without --auto-suffix argument, but suffix has been added to the resource names.

**What you expected to happen**:
Resource names don't contain suffix

**How to reproduce it** (as minimally and precisely as possible):
`acs-engine deploy`

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
I don't see this PR introducing the behavior you describe, can you look over:

https://github.com/Azure/acs-engine/pull/2239

To be clear about your bug, is the suffix you're seeing in the form of `4af9f070`? E.g.:

https://play.golang.org/p/WdOLWpaOClO

**Comment by IvanovOleg** [comment]
k8s-agentpool1-**30347309**-0
I was talking about this random number. Can I get rid of it?

**Comment by jackfrancis** [comment]
There is no way to get rid of that at the moment, it's there to ensure uniqueness across multiple deployments. This is not the `--auto-suffix`, which is an additional element of (optional) uniqueness.
