### ISSUE TITLE
enablePrivateCluster not recognized

### ISSUE THREAD

**Issue by MassimoSporchia** [Azure/acs-engine#2389]
**Is this a request for help?**:

NO

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

Version: v0.13.1
GitCommit: 797dd91
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Not important

**What happened**:

While trying to generate a Kubernetes Cluster, I tried adding the "ensurePrivateCluster" as explained here: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#feat-custom-vnet

```
"orchestratorProfile": {
      "orchestratorType": "Kubernetes",
	  "orchestratorRelease": "1.8",
	  "kubernetesConfig": {
        "enablePrivateCluster": true
}
```
While calling the acs-engine generate "template.json" the following error occurs:
```
[36mINFO[0m[0000] Error returned by LoadContainerService: Unknown JSON tag enablePrivateCluster
[31mFATA[0m[0000] error validating generateCmd: error parsing the api model: Unknown JSON tag enablePrivateCluster
```
  
**What you expected to happen**:

The template generates without any errors

**How to reproduce it** (as minimally and precisely as possible):

1. Create a custom VNET template using Kubernetes as orchestrator
1. Ensure the acs-engine generate command works
1. Add the ensurePrivateCluster attribute
1. The acs-engine generate command should throw the forementioned error

**Anything else we need to know**:

This is strange, the types are there: https://github.com/Azure/acs-engine/blob/master/pkg/api/types.go

**Comment by CecileRobertMichon** [comment]
Hi @MassimoSporchia, the "enablePrivateCluster" tag was recently merged into acs-engine master and has not been included in a release yet. If you want to play with the feature before the next release you can [build from the master branch](https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md#build-acs-engine-from-source).

**Comment by MassimoSporchia** [comment]
@CecileRobertMichon Oouch, thanks, must have missed that!

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/releases/tag/v0.14.0 was just released with this feature

**Comment by todoesverso** [comment]
@CecileRobertMichon 
I am still seen this in 0.14.0 :( 

```
todoesverso@todoesdebian:~/repos/acs-engine-test$ acs-engine version
Version: v0.14.0
GitCommit: 6ba4622b
GitTreeState: clean
todoesverso@todoesdebian:~/repos/acs-engine-test$ acs-engine deploy --subscription-id XXXXX --dns-prefix victor-acs-test --location westeurope --auto-suffix --api-model kubernetes.json --resource-group victor-acs-engine
INFO[0000] Error returned by LoadContainerService: Unknown JSON tag enablePrivateCluster 
FATA[0000] error validating deployCmd: error parsing the api model: Unknown JSON tag enablePrivateCluster
```

**Comment by CecileRobertMichon** [comment]
Note that the apimodel definition slightly changed to 
``` "kubernetesConfig": {
        "privateCluster": {
          "enabled": true
      }
```
see [docs](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#private-cluster) for more details.
