### ISSUE TITLE
Template Variable Limit Exceeded

### ISSUE THREAD

**Issue by samkreter** [Azure/acs-engine#2393]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: v1.9.4.3

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

**What happened**: Trying to deploy a cluster but we are hitting the max parameter limit found by the error 
` {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The number of template variables limit exceeded. Limit: '256' and actual: '272'. Please see https://aka.ms/arm-template/#variables for usage details.'."}} `

**What you expected to happen**: Be able to use more variables in the template. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Hi @samkreter! What does your apimodel look like? Which version of acs-engine are your using? ` v1.9.4.3` doesn't exist the latest release is [v0.13.1](https://github.com/Azure/acs-engine/releases/tag/v0.13.1)

**Comment by samkreter** [comment]
Hey! Sorry wrong versioning. The ACS-engine version is 0.9.4. Below is the api model. 
[apimodel.txt](https://github.com/Azure/acs-engine/files/1783197/apimodel.txt)

**Comment by CecileRobertMichon** [comment]
Ok so ARM has template limits and the size of  your cluster (number of agent pools) is making it go over. A few questions: any reason you're using v0.9.4 and not the most recent (v0.13.1)? Do you need to have the agent nodes separated into 11 pools? Looks like several of them have the same properties.

**Comment by CecileRobertMichon** [comment]
You might be able to get around this by changing your template a bit to condense things like this: [apimodel (1).txt](https://github.com/Azure/acs-engine/files/1786093/apimodel.1.txt). Note that I removed the firstConsecutiveIP since it's being ignored because you're not using a custom VNET and the windows profile because you don't have any windows pools.

**Comment by jackfrancis** [comment]
Fixed with #3649
