### ISSUE TITLE
agentpublicosImageSKU isn't used

### ISSUE THREAD

**Issue by plasne** [Azure/acs-engine#2399]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.13.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DC/OS

**What happened**:
I specified the following after the azuredeploy.parameters.json was generated:
"agentprivateosImageSKU": "17.10"
"agentprivateosImageVersion":  "17.10.201802220"

**What you expected to happen**:
I expected the agents to be 17.10, but they were 16.04 because "osImageSKU" was "16.04-LTS" and that is the only variable used.

**How to reproduce it** (as minimally and precisely as possible):
As above.

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
Hi @plasne, we don't currently support that OS image SKU. If you are experimenting by modifying the acs-engine generate values, make sure you replace all 16.04 references with the appropriate 17.10 replacements, and that the region/account you're building in has access to those SKUs.

I'm going to close this as there is no support at this time for 17.10

**Comment by plasne** [comment]
I probably could have stated this better, but I realize that 17.10 doesn't work, the issue is that the parameters show 3 variables for SKU and 3 variables for version, but they aren't used, only 1 is, which is confusing.
