### ISSUE TITLE
k8s 1.10 support note: Use kube-addon-manager-amd64:8.5+ image for addonmanager

### ISSUE THREAD

**Issue by karataliu** [Azure/acs-engine#2404]
To keep a note here for k8s 1.10 support.

Current addonmanager image used by k8s 1.9 does not suit k8s 1.10
```
"addonmanager":              "kube-addon-manager-amd64:v6.5",
```
The behavior is addon-manager won't start.
For example, with single mater note, the master won't treat it self as leader, thus does not start working:
```
INFO: Not elected leader, going back to sleep.
INFO: Leader is k8s-master-40459714-0_e8338f59-0802-11e8-9439-000d3a107392
INFO: Not elected leader, going back to sleep.
INFO: Leader is k8s-master-40459714-0_e8338f59-0802-11e8-9439-000d3a107392
INFO: Not elected leader, going back to sleep.
INFO: Leader is k8s-master-40459714-0_e8338f59-0802-11e8-9439-000d3a107392
```

Root cause is identity naming rule change introduced by:
https://github.com/kubernetes/kubernetes/pull/58302
https://github.com/kubernetes/kubernetes/pull/58386

Updating to `kube-addon-manager-amd64:v8.5` image will do the fix.

**Comment by jackfrancis** [comment]
Thanks for tracking this requirement @karataliu !
