### ISSUE TITLE
Not able to connect with kubectl X509 unknown authority

### ISSUE THREAD

**Issue by Jarlotee** [Azure/acs-engine#2418]
**Is this a request for help?**: Yes
---
**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue
---
**What version of acs-engine?**: 0.13.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Following the [kubernetes guide](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md#deploy), after adding the `kubeconfig,centralus.json` file to `KubeConfig` environment variable, when i run `kubectl cluster-info` I get the following message:

```
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
```

**What you expected to happen**:

To successfully connect to the cluster

**How to reproduce it** (as minimally and precisely as possible):

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md#acs-engine-the-long-way

**Anything else we need to know**:

```json
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorVersion": "1.9.1",
        "kubernetesConfig": {
            "dockerEngineVersion": "17.05.*"
        }
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "some-cool-prefix",
        "vmSize": "Standard_D2_v2"
      },
      "agentPoolProfiles": [
        {
          "name": "agentpool1",
          "count": 2,
          "vmSize": "Standard_D2_v2",
          "availabilityProfile": "AvailabilitySet"
        }
      ],
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "secret!"
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId": "some-id",
        "secret": "secret!"
      }
    }
  }
```

**Comment by ewok2030** [comment]
FWIW - I had similar trouble from behind a non-transparent proxy on a corporate network. The proxy intercepts traffic and modifies the responses, invalidating the certificate trust between kubectl and apiserver.

Using the ‘—insecure-skip-tls-verify’ flag with kubectl was the workaround.

**Comment by ahsannaseem** [comment]
havin g same issue but getting this

`kubectl --insecure-skip-tls-verify="true" get pods
error: the server doesn't have a resource type "pods"`

**Comment by Luis-Angel-Ramher** [comment]
Hi, i have a similar problem when writing
```
kubectl version --short
```
It show the following
```
Client Version: v1.11.0
Unable to connect to the server: x509: certificate signed by unknown authority
```
Then i execute
```
kubectl config set-cluster gke_my-project --insecure-skip-tls-verify=true
```
But when performing 
```
kubectl version --short
```
I get this
```
Client Version: v1.11.0
error: got '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<!--//////////////////////////////////////////////////////////////////////////
//
//    Copyright (c) 1996 - 2011, Websense, Inc.    All Rights Reserved
//    See WebsenseCopyright.txt for copyright information
//
///////////////////////////////////////////////////////////////////////////-->

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Blocked by Websense</title>
<!--<link rel="stylesheet" href="/en/Default/master.css" type="text/css">-->
<script type="text/javascript" language="javascript" src="/en/Default/master.js"></script>
<script type="text/javascript" language="javascript" src="/en/Default/base64.js"></script>
<script type="text/javascript" language="javascript" src="/en/Default/security.js"></script>
</head>

<body>
<form>
        <iframe src="http://10.50.226.90:15871/cgi-bin/block_message.cgi?ws-session=-1902541711" id="test" title="test"
name="ws_block" frameborder="0" scrolling="no"  style="width:100%;" height="600">

        </iframe>
<iframe src="http://10.50.226.90:15871/cgi-bin/blockOptions.cgi?ws-session=-1902541711" id="option" name="ws_blockoption
" frameborder="0" scrolling="no" style="width:100%;" height="600">

</iframe>
</form>
</body>
</html>
': invalid character '<' looking for beginning of value
```
Can someone help me, I do it from the windows cmd.

Thank you

**Comment by kaplanke** [comment]
> Hi, i have a similar problem when writing
> 
> ```
> kubectl version --short
> ```
> It show the following
> 
> ```
> Client Version: v1.11.0
> Unable to connect to the server: x509: certificate signed by unknown authority
> ```
> Then i execute
> 
> ```
> kubectl config set-cluster gke_my-project --insecure-skip-tls-verify=true
> ```
> But when performing
> 
> ```
> kubectl version --short
> ```
> I get this
> 
> ```
> Client Version: v1.11.0
> error: got '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
> 
> 
> 
> <html>
> <head>
> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
> <title>Blocked by Websense</title>
> 
> <script type="text/javascript" language="javascript" src="/en/Default/master.js"></script>
> <script type="text/javascript" language="javascript" src="/en/Default/base64.js"></script>
> <script type="text/javascript" language="javascript" src="/en/Default/security.js"></script>
> </head>
> 
> <body>
> <form>
>         <iframe src="http://<ip address>:<port>/cgi-bin/block_message.cgi?ws-session=xxxxxxx" id="test" title="test"
> name="ws_block" frameborder="0" scrolling="no"  style="width:100%;" height="600">
> 
>         </iframe>
> <iframe src="http://<ip address>:<port>/cgi-bin/blockOptions.cgi?ws-session=xxxxxxxxx" id="option" name="ws_blockoption
> " frameborder="0" scrolling="no" style="width:100%;" height="600">
> 
> </iframe>
> </form>
> </body>
> </html>
> ': invalid character '<' looking for beginning of value
> ```
> Can someone help me, I do it from the windows cmd.
> 
> Thank you

This is websense response, which possibly says you cannot access your cluster via your company fw. You may want to try from an other network (mobile hotspot maybe?)...

**Comment by eugen-nw** [comment]
I used the command below to get myself out of this pickle:
az aks get-credentials -g <resource group name> -n <cluster name> --overwrite-existing

I watched the ~/.kube/config file and a whole new entry got added in the "users:" section.  The kubectl commands work now.

**Comment by mpandav** [comment]
> I used the command below to get myself out of this pickle:
> az aks get-credentials -g <resource group name> -n <cluster name> --overwrite-existing
> 
> I checked the ~/.kube/config file and a whole new entry got added in the "users:" section. The kubectl commands work now.

Can you please mentioned the correct command so I can use the same

**Comment by eugen-nw** [comment]
Certainly:

az aks get-credentials  -g <your Azure resource group> -n <your Azure Kubernetes instance name>  --overwrite-existing

**Comment by eugen-nw** [comment]
Certainly, whatever is enclosed within \< \> you need to supply with your own values:

az aks get-credentials  -g \<Azure resource group name\>  -n \<Azure Kubernetes service instance name\>  --overwrite-existing

For more info: az aks get-credentials  -help

**Comment by eugen-nw** [comment]
In case your browse does not render my message correctly, this is the image that I'm seeing:

![image](https://user-images.githubusercontent.com/15199814/58303108-77872e80-7da3-11e9-850f-842c115e0fce.png)

**Comment by Raiyan444** [comment]
**Fixed:** 
Just Copy kube config again

cp /etc/kubernetes/admin.conf $home/.kube/config
