### ISSUE TITLE
metrics-server failing on 1.10

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#2421]
Current support for 1.10 clusters (delivered w/ PR #2413) does not deliver a working metrics-server:

metrics-server pod is failing with the following error:

`F0309 04:15:59.001244 1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file`

FYI @pidah @feiskyer if either of you have cycles to play around w/ 1.10 beta clusters :)

**Comment by jackfrancis** [comment]
Ah, of course, I should be able to fix that today, thanks!

**Comment by feiskyer** [comment]
@pidah is right, metrics-server requires following configs:

```
--requestheader-client-ca-file=<path to aggregator CA cert>
--requestheader-allowed-names=aggregator
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User
--proxy-client-cert-file=<path to aggregator proxy cert>
--proxy-client-key-file=<path to aggregator proxy key>
```

**Comment by adelina-t** [comment]
I can confirm I see this issue with acs-engine v0.16.1 and k8s 1.10.2 and k8s 1.9.7 . Also happens with v0.16.0 and k8s 1.9.7.

**Comment by jackfrancis** [comment]
This is fixed. #2857 aims to fix this for Windows
