### ISSUE TITLE
kuberneteswindowssetup.ps1 does not wait for Docker service to be up, and hence fails

### ISSUE THREAD

**Issue by ufminhas** [Azure/acs-engine#2446]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.13.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
acs-engine/parts/k8s/kuberneteswindowssetup.ps1 does not wait for Docker service to be up and hence fails to finish the setup (e.g., kubletwin/pause is not built)

**What you expected to happen**:

Find file 
Copy path 
acs-engine/parts/k8s/kuberneteswindowssetup.ps1 should wait for the Docker service to be up before executing.

**How to reproduce it** (as minimally and precisely as possible):
Deploy K8s for Windows using acs-engine binary for 0.13.1

**Anything else we need to know**:
No

**Comment by j03wang** [comment]
I can confirm this has happened to me in the last two clean deployments.
