### ISSUE TITLE
prometheus-grafana extension doesn't get executed

### ISSUE THREAD

**Issue by ams0** [Azure/acs-engine#2459]
**Is this a request for help?**:

YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

---

**What version of acs-engine?**:

Version: canary
GitCommit: bfc6b0ed
GitTreeState: clean

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

Deployed acs-engine cluster with prometheus-grafana extension

**What you expected to happen**:

Script to be executed.

**How to reproduce it** (as minimally and precisely as possible):

Deploy this template: https://gist.github.com/ams0/00a57ad5195bc2a802ebcdb257a22982

**Anything else we need to know**:

The script doesn't get executed automatically, but running:

```
git clone https://github.com/azure/acs-engine.git
cd acs-engine/extensions/prometheus-grafana-k8s/v1/
sudo bash ./prometheus-grafana-k8s.sh monitoring
```
correctly installs Prometheus 2.0, Grafana and cAdvisor in every node.

**Comment by CecileRobertMichon** [comment]
@trstringer @ritazh might be able to help here

**Comment by trstringer** [comment]
@ams0 it looks like in your api model you are missing `name`, `version`, and `rootURL` in your extension profile. From my understanding of the way extensions work for acs-engine, the root url is a hard requirement. From the gist, your extension profile has no identifying information for the actual extension to use.

I'll let @ritazh comment further on the requirements for an extension profile.

**Comment by ams0** [comment]
My bad indeed. But now that I add the extensionProfile, template generation fails with:

```
$> acse generate monitoring.yaml
INFO[0000] Generating assets into _output/monitorme...
Extension not supported for orchestrator. Error: Unable to GET extension resource for extension: prometheus-grafana-k8s with version v1 with filename supported-orchestrators.json at URL: https://raw.githubusercontent.com/Azure/acs-engine/master/extensions/prometheus-grafana-k8s/v1/supported-orchestrators.json Error: Get https://raw.githubusercontent.com/Azure/acs-engine/master/extensions/prometheus-grafana-k8s/v1/supported-orchestrators.json: x509: failed to load system roots and no roots provided
```

Looks like it can't access the CA store and can't verify Github identity.

**Comment by ams0** [comment]
My bad, using the extensionProfiles section fixed it. Thanks all

**Comment by trstringer** [comment]
@ams0 awesome!! Glad it fixed it.
