### ISSUE TITLE
Grafana dashboards empty

### ISSUE THREAD

**Issue by ams0** [Azure/acs-engine#2460]
**Is this a request for help?**:

YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

---

**What version of acs-engine?**:

Version: canary
GitCommit: bfc6b0ed
GitTreeState: clean

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.9

**What happened**:

Deploying (manually, see #2459 ) the prometheus-grafana extension deploys a dashboard (https://grafana.com/api/dashboards/3119) but all graphs are empty; however, data is coming in. 

**What you expected to happen**:

To deploy a dashboard 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by trstringer** [comment]
Let's get https://github.com/Azure/acs-engine/issues/2459 figured out, and then if this is still a problem we can troubleshoot further. I'd be surprised if these issues (and solutions) aren't related.

For what it's worth, we recently moved to a decoupled cAdvisor from kubelet. A quick check would be to see if the cAdvisor daemon set has been deployed. You should be able to curl metrics from it. The Prometheus config is what controls where to find those metrics. Again, my recommendation would be for us to hold off on troubleshooting this until the aforementioned issue is resolved.

cc // @ritazh

**Comment by ams0** [comment]
Indeed, running the script properly through the extension profile loaded the dashboard correctly. Thanks!
