### ISSUE TITLE
availabilityProfile: what to use?

### ISSUE THREAD

**Issue by olilanz** [Azure/acs-engine#2462]
**Is this a request for help?**:

Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

---

**What version of acs-engine?**:

0.13.1 (or any)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes (or any)

**What happened**:

When deploying a Kubernetes cluster, I use availabilityProfile:AvailabilitySet. That works well. But the documentation puzzles me. 

Why is there a rule of thumb stating that this is the only option when Kubernetes is required? Is availabilityProfile:VirtualMachineScaleSets not supported with Kubernetes? According to docs it still seems to be the default, even when Kubernetes is used.

I can’t seem to make sense of this. Can anyone enlighten me?

** What you expected to happen**:

availabilityProfile:AvailabilitySet should be default for Kubernetes orchestrator type, if it indeed is the only option. Otherwise, clearer guidance in the docs.

**How to reproduce it** (as minimally and precisely as possible):

Not applicable 

**Anything else we need to know**:

No

**Comment by CecileRobertMichon** [comment]
@olilanz from what I know, this isn't relevant for k8s 1.10+. Before k8s 1.10, you can use VMSS if you are not planning to use PVC/PV based on azure disks (see https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv). If you are, it is better to use AvailabilitySet. @khenidak might have a better explanation.

**Comment by ams0** [comment]
It doesn't work currently (built acs-engine from master branch):

template:
```
{
     "apiVersion": "vlabs",
     "properties": {
         "orchestratorProfile": {
             "orchestratorType": "Kubernetes",
             "orchestratorRelease": "1.10"
         },
         "masterProfile": {
             "count": 1,
             "dnsPrefix": "vmssk8s",
             "vmSize": "Standard_D2_v2"
         },
         "agentPoolProfiles": [
             {
                 "name": "linuxpool1",
                 "count": 1,
                 "vmSize": "Standard_D2_v2",
                 "storageProfile" : "ManagedDisks",
                 "availabilityProfile": "VirtualMachineScaleSets"
             }
         ],
         "linuxProfile": {
             "adminUsername": "azureuser",
             "ssh": {
<snip>
```
error:
```
INFO[0000] Error returned by LoadContainerService: VirtualMachineScaleSets are not supported with Kubernetes since Kubernetes requires the ability to attach/detach disks.  To fix specify "AvailabilityProfile":"AvailabilitySet"
FATA[0000] error validating generateCmd: error parsing the api model: VirtualMachineScaleSets are not supported with Kubernetes since Kubernetes requires the ability to attach/detach disks.  To fix specify "AvailabilityProfile":"AvailabilitySet"
```

But I think that's not the case anymore for 1.10+. How to remove the check?

**Comment by sozercan** [comment]
For vmss on k8s, you'll need to wait until #2620 is merged

**Comment by olilanz** [comment]
Closed as duplicate
