### ISSUE TITLE
Can't deploy K8s 1.9.x on AzureGermanCloud

### ISSUE THREAD

**Issue by ITler** [Azure/acs-engine#2464]
**Is this a request for help?**:
somehow yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
0.13.1, 0.14.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8s 1.9.3, 1.9.4, 1.9.6

**What happened**:
Can't bootstrap a new cluster at all on **AzureGermanCloud** with newest K8s and acs-engine release. Error during ARM deployment:

	Deployment failed. {
	  "status": "Failed",
	  "error": {
		"code": "ResourceDeploymentFailure",
		"message": "The resource operation completed with terminal provisioning state 'Failed'.",
		"details": [
		  {
			"code": "VMExtensionProvisioningError",
			"message": "VM has reported a failure when processing extension 'cse2'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=3\"."
		  }
		]
	  }
	}

**What you expected to happen**:
...

**How to reproduce it** (as minimally and precisely as possible):

	{
		"apiVersion": "vlabs",
		"location": "germanycentral",
		"properties": {
			"orchestratorProfile": {
				"orchestratorType": "Kubernetes",
				"orchestratorRelease": "1.9",
				"orchestratorVersion": "1.9.6"
			},
			"masterProfile": {
				"count": 3,
          			"vnetCidr": "10.128.0.0/23",
         			"ipAddressCount": 1,
				"dnsPrefix": "itltest",
				"vmSize": "Standard_A2_v2",
				"vnetSubnetId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/itltest_germanycentral/providers/Microsoft.Network/virtualNetworks/itltest_germanycentral-vnet/subnets/itltest_germanycentral-vnet-subnet",
				"firstConsecutiveStaticIP": "10.128.0.239"
			},
			"agentPoolProfiles": [
			{
				"name": "pool1",
				"availabilityProfile": "AvailabilitySet",
				"count": 3,
        			"ipAddressCount": 117,
				"storageProfile": "ManagedDisks",
				"vmSize": "Standard_A2_v2",
				"vnetSubnetId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/itltest_germanycentral/providers/Microsoft.Network/virtualNetworks/itltest_germanycentral-vnet/subnets/itltest_germanycentral-vnet-subnet"
			}
			],
			"linuxProfile": {
				"adminUsername": "testuser",
				"SSH": {
					"publicKeys": [
					{
						"keyData": ""
					}
					]
				}
			},
			"servicePrincipalProfile": {
				"clientID": "00000000-0000-0000-0000-000000000000",
				"secret": "00000000-0000-0000-0000-000000000000"
			}
		}
	}

Running:

    acs-engine generate <rendered-config-above>.json
    az group deployment create --template-file azuredeploy.json --parameters azuredeploy.parameters.json [... whatever else is necessary to create an ARM deployment]

**Anything else we need to know**:
- **AzureGermanCloud**
- this time try to use AzureCNI
- one vnet and subnet for all k8s nodes created before using acs-engine

**Comment by ITler** [comment]
I've learned from a MS technican, that this message does not necessarily mean, that the kubernetes wasn't deployed correctly and this could be seen more as a cosmetical problem.. I couldn't verify that, as I couldn't have a look at it.
However as the ARM deployment itself ends with failed state, there are not *Outputs* generated, which we need for documentation reasons and further automation purposes in our tool chain. So this is more than just a cosmetical topic at least for us.

**Comment by ITler** [comment]
Nevertheless, a bootstrapped 1.9.3 cluster@AzureGermanCloud is unhealthy (reproducable), but as I've seen, I'm not the only one having problems. I hopefully can provide more details next week.

**Comment by vpatelsj** [comment]
Are you ok with sharing VM logs? I'll be happy to take a look at the failure and diagnose.

**Comment by ITler** [comment]
Generally yes, but I don't care anymore, as I can bootstrap 1.9.6 using acs-engine 0.14.4

**Comment by AnirbanKundu** [comment]
I was trying to create a K8 cluster using the following command: 
`az aks create --name myAKSCluster --resource-group myResourceGroup  --node-count 1 \
    --generate-ssh-keys \
    --service-principal <appId> \
    --client-secret <password>
`
And I keep on getting the  error: 
```
Deployment failed. Correlation ID: e9e40841-6500-4508-af4a-f7218b2dbdbb. VM has reported a failure when processing extension 'cse-agent-0'. Error message: "Enable failed: failed to execute command: command terminated with exit status=31
[stdout]

[stderr]
".
```
My app details are as follows:
```
{
  "appId": "c41d4e40-9800-4128-addc-36d877e9ab58",
  "displayName": "azure-cli-2018-07-24-17-15-19",
  "name": "http://azure-cli-2018-07-24-17-15-19",
  "password": "7f8f10b1-74f9-4469-8eb8-ece3f79380c1",
  "tenant": "15ccb6d1-d335-4996-b6f9-7b6925f08121"
}
```

Can anyone help ? 

Thanks,
Anirban
