### ISSUE TITLE
Kubelet 1.8.8 not starting after cluster deployment in AzureGermanCloud

### ISSUE THREAD

**Issue by ITler** [Azure/acs-engine#2465]
**Is this a request for help?**:
somehow yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
0.13.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8s 1.8.8

**What happened**:
ARM Deployment of new cluster on **AzureGermanCloud** works, however `kubelet` service on master refuses to start

    $ service kubelet status
    [...]
    Mar 14 14:04:10 k8s-master-20992919-0 bash[2304]: Bad argument `MASQUERADE'
    Mar 14 14:04:10 k8s-master-20992919-0 bash[2304]: Try `iptables -h' or 'iptables --help' for more information.
    Mar 14 14:04:10 k8s-master-20992919-0 systemd[1]: kubelet.service: Control process exited, code=exited status=2
    Mar 14 14:04:10 k8s-master-20992919-0 systemd[1]: Failed to start Kubelet.

A reboot does not help, however I didn't expect it.

As the output states problem with iptables, the version is:
    
    $ iptables --version
    iptables v1.6.0

**What you expected to happen**:
...

**How to reproduce it** (as minimally and precisely as possible):

	{
		"apiVersion": "vlabs",
		"location": "germanycentral",
		"properties": {
			"orchestratorProfile": {
				"orchestratorType": "Kubernetes",
				"orchestratorRelease": "1.8",
				"orchestratorVersion": "1.8.8"
			},
			"masterProfile": {
				"count": 1,
				"dnsPrefix": "itltest",
				"vmSize": "Standard_A2_v2",
				"vnetSubnetId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/itltest_germanycentral/providers/Microsoft.Network/virtualNetworks/itltest_germanycentral-vnet/subnets/itltest_germanycentral-vnet-subnet",
				"firstConsecutiveStaticIP": "172.29.3.240"
			},
			"agentPoolProfiles": [
			{
				"name": "pool1",
				"availabilityProfile": "AvailabilitySet",
				"count": 2,
				"storageProfile": "ManagedDisks",
				"vmSize": "Standard_A2_v2",
				"vnetSubnetId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/itltest_germanycentral/providers/Microsoft.Network/virtualNetworks/itltest_germanycentral-vnet/subnets/itltest_germanycentral-vnet-subnet"
			}
			],
			"linuxProfile": {
				"adminUsername": "testuser",
				"SSH": {
					"publicKeys": [
					{
						"keyData": ""
					}
					]
				}
			},
			"servicePrincipalProfile": {
				"clientID": "00000000-0000-0000-0000-000000000000",
				"secret": "00000000-0000-0000-0000-000000000000"
			}
		}
	}

Running:

    acs-engine generate <rendered-config-above>.json
    az group deployment create --template-file azuredeploy.json --parameters azuredeploy.parameters.json [... whatever else is necessary to create an ARM deployment]

**Anything else we need to know**:
- **AzureGermanCloud**
- this time tried to use AzureCNI
- one vnet and subnet for all k8s nodes created before using acs-engine

**Comment by ITler** [comment]
This is caused by using AzureCNI.
When changing back to Kubenet, kubelet starts. (tested once)

**Comment by jackfrancis** [comment]
Hi @ITler,

A quick scan of your api model suggests there is a missing `vnetCidr` property in the `masterProfile` object. See the example provided here:

https://github.com/Azure/acs-engine/blob/master/examples/vnet/kubernetesvnet-azure-cni.json

This applies if you wish to use Azure CNI.

**Comment by ITler** [comment]
Hello @jackfrancis,

thanks for replying... will give it a try

**Comment by ITler** [comment]
Well, it seems to work. I obviously didn't see the wood for the trees. Thank you very much. I close the issue, nevertheless will do some more testing, before relying on the setup. Currently it looks like we need to use K8s 1.9.x having the feature to set dns label to public ip addresses. You recently stated, that you wouldn't use 1.9.x, yet. Hope this will change soon. Again thank you for effort.
