### ISSUE TITLE
ACS-engine private cluster jumpbox fails to install

### ISSUE THREAD

**Issue by stefanstranger** [Azure/acs-engine#2474]
Request for help
---

ISSUE
---

**What version of acs-engine?**:
Version: v0.14.0
---

I'm trying to deploy an ACS with Kubernetes private Cluster but when I configure to also deploy a jumpbox the ARM Template Test Deployment fails with errors around missing variables:

- vnetID
- vmSizesMap

I've the following Cluster Definition regarding internal ip addresses and jumpbox configuration:

"kubernetesConfig": {
        "privateCluster": {
          "enabled": true,
          "jumpboxProfile": {
            "name": "my-jb",
            "vmSize": "Standard_D4s_v3",
            "osDiskSizeGB": 30,
            "storageProfile": "ManagedDisks",
            "username": "azureuser",
            "publicKey": "ssh-rsa xxx"
          }
        },
          "clusterSubnet": "10.232.21.0/24",
          "dnsServiceIP": "172.19.0.10",
          "serviceCidr": "172.19.0.0/16"
        }
 
After the creation of the ARM Templates the Azure Test deployment fails because of missing variables in the ARM Templates. See above.

I'm able to deploy the internal only ACS with Kubernetes cluster when I remove the jumpbox settings.

My Azure Environment consists of two Resource Groups:
1. Resource Group with:
    - Domain Controller and DNS
    -Virtual Network
2. Resource Group with:
    - Kubernetes Cluster nodes etc.

The Kubernetes Cluster nodes are using the VNet from Resource Group 1.

I'm able to deploy and connect to the Kubernetes Cluster when I deploy the cluster without the jumpbox configuration.  

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.0

**What happened**:
Deployed failed when trying to include jumpbox vm for ACS with Kubernetes internal deployment.

**What you expected to happen**:
- Deployment of ACS with private Kubernetes cluster including the jumpbox VM.

**How to reproduce it** (as minimally and precisely as possible):
- Create 2 Resource Groups in Azure
- Create a VNet in one Resource Group
- Create a Cluster Definition file for private clusterin including jumpbox configuration
- Run ACS Engine
- Verify ARM Templates for missing variables.

**Comment by CecileRobertMichon** [comment]
@stefanstranger thank you for reporting! That is indeed a bug in the implementation which makes the jumpbox incompatible with a custom vnet. I will have a PR to fix it soon, I'll report back here when it's out.

**Comment by CecileRobertMichon** [comment]
The fix was just released in [v0.14.1](https://github.com/Azure/acs-engine/releases/tag/v0.14.1), please let me know if you run into any other issues!
