### ISSUE TITLE
Internal LoadBalancer not working with multiple subnets

### ISSUE THREAD

**Issue by todoesverso** [Azure/acs-engine#2476]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
master
```
$ acs-engine version
Version: canary
GitCommit: 832842ef
GitTreeState: clean
```
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
```
$ kubectl get nodes -o wide
NAME                          STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION      CONTAINER-RUNTIME
k8s-deliverypool-16621075-0   Ready     agent     2h        v1.9.4    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1011-azure   docker://1.13.1
k8s-master-16621075-0         Ready     master    2h        v1.9.4    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1011-azure   docker://1.13.1
k8s-telluricpool-16621075-0   Ready     agent     2h        v1.9.4    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1011-azure   docker://1.13.1

```

**What happened**:
```
$ cat nginx.yml 
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-load-balancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    run: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

$ kubectl  create -f nginx.yml 
deployment "nginx-deployment" created
service "nginx-internal-load-balancer" created
$ kubectl get svc
NAME                           TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
kubernetes                     ClusterIP      10.0.0.1     <none>        443/TCP        1h
nginx-internal-load-balancer   LoadBalancer   10.0.95.71   <pending>     80:30521/TCP   2m
$ kubectl get svc
NAME                           TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
kubernetes                     ClusterIP      10.0.0.1     <none>        443/TCP        1h
nginx-internal-load-balancer   LoadBalancer   10.0.95.71   10.2.0.34     80:30521/TCP   2m
$ curl -vvv 10.2.0.34
* Rebuilt URL to: 10.2.0.34/
*   Trying 10.2.0.34...
* TCP_NODELAY set
* connect to 10.2.0.34 port 80 failed: Connection timed out
* Failed to connect to 10.2.0.34 port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to 10.2.0.34 port 80: Connection timed out
```

**What you expected to happen**:
Curl returning the nginx welcome page.

**How to reproduce it** (as minimally and precisely as possible):
With the steps above should be reproducible.

**Anything else we need to know**:
My SKU is Basic.

The pod  _kube-controller-manager_ shows me this errors.
```
I0315 17:57:45.954800       1 azure_backoff.go:193] LoadBalancerClient.List(victor-acs-engine) - backoff: success
E0315 17:57:45.955029       1 service_controller.go:776] Failed to process service default/kubernetes. Retrying in 5m0s: error getting LB for service default/kubernetes: Service(default/kubernetes) - Loadbalancer not found
I0315 17:57:45.955316       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"kubernetes", UID:"c5d0865d-285c-11e8-9ece-000d3a2880d1", APIVersion:"v1", ResourceVersion:"35", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service default/kubernetes: Service(default/kubernetes) - Loadbalancer not found
I0315 17:57:45.985602       1 azure_backoff.go:193] LoadBalancerClient.List(victor-acs-engine) - backoff: success
E0315 17:57:45.985703       1 service_controller.go:776] Failed to process service kube-system/metrics-server. Retrying in 5m0s: error getting LB for service kube-system/metrics-server: Service(kube-system/metrics-server) - Loadbalancer not found
I0315 17:57:45.986256       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"kube-system", Name:"metrics-server", UID:"cd602992-285c-11e8-9ece-000d3a2880d1", APIVersion:"v1", ResourceVersion:"358", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service kube-system/metrics-server: Service(kube-system/metrics-server) - Loadbalancer not found
I0315 17:57:46.026600       1 azure_backoff.go:193] LoadBalancerClient.List(victor-acs-engine) - backoff: success
E0315 17:57:46.026629       1 service_controller.go:776] Failed to process service kube-system/tiller-deploy. Retrying in 5m0s: error getting LB for service kube-system/tiller-deploy: Service(kube-system/tiller-deploy) - Loadbalancer not found
I0315 17:57:46.027023       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"kube-system", Name:"tiller-deploy", UID:"cd6eb6cb-285c-11e8-9ece-000d3a2880d1", APIVersion:"v1", ResourceVersion:"380", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service kube-system/tiller-deploy: Service(kube-system/tiller-deploy) - Loadbalancer not found
I0315 17:57:46.077681       1 azure_backoff.go:193] LoadBalancerClient.List(victor-acs-engine) - backoff: success
E0315 17:57:46.077932       1 service_controller.go:776] Failed to process service kube-system/kube-dns. Retrying in 5m0s: error getting LB for service kube-system/kube-dns: Service(kube-system/kube-dns) - Loadbalancer not found
I0315 17:57:46.078403       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"kube-system", Name:"kube-dns", UID:"cdda31b9-285c-11e8-9ece-000d3a2880d1", APIVersion:"v1", ResourceVersion:"414", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service kube-system/kube-dns: Service(kube-system/kube-dns) - Loadbalancer not found
I0315 17:57:46.113397       1 azure_backoff.go:193] LoadBalancerClient.List(victor-acs-engine) - backoff: success
E0315 17:57:46.113440       1 service_controller.go:776] Failed to process service kube-system/heapster. Retrying in 5m0s: error getting LB for service kube-system/heapster: Service(kube-system/heapster) - Loadbalancer not found
I0315 17:57:46.113568       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"kube-system", Name:"heapster", UID:"ce177ca3-285c-11e8-9ece-000d3a2880d1", APIVersion:"v1", ResourceVersion:"442", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service kube-system/heapster: Service(kube-system/heapster) - Loadbalancer not found
I0315 17:57:46.156898       1 azure_backoff.go:193] LoadBalancerClient.List(victor-acs-engine) - backoff: success
E0315 17:57:46.157423       1 service_controller.go:776] Failed to process service kube-system/kubernetes-dashboard. Retrying in 5m0s: error getting LB for service kube-system/kubernetes-dashboard: Service(kube-system/kubernetes-dashboard) - Loadbalancer not found
I0315 17:57:46.157599       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"kube-system", Name:"kubernetes-dashboard", UID:"ce476b8a-285c-11e8-9ece-000d3a2880d1", APIVersion:"v1", ResourceVersion:"478", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service kube-system/kubernetes-dashboard: Service(kube-system/kubernetes-dashboard) - Loadbalancer not found

```

**Comment by jackfrancis** [comment]
Hi @todoesverso,

We have test coverage on ILB that passing for `v1.9.4` clusters. See here:

https://github.com/Azure/acs-engine/blob/master/test/e2e/kubernetes/kubernetes_test.go#L262

using this resource definition:

https://github.com/Azure/acs-engine/blob/master/test/e2e/kubernetes/workloads/ingress-nginx-ilb.yaml

What's different between the above test implementation and what you're encountering? If ILB is still broken in `v1.9.4` we want to improve our test case so that we are appropriately failing.

**Comment by todoesverso** [comment]
I am using a private cluster with this config, not sure if that is where it is coming:

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.9.4",
      "kubernetesConfig": {
         "privateCluster": {
	    "enabled" : true
	 }
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/XXXX/resourceGroups/victor-acs-engine/providers/Microsoft.Network/virtualNetworks/vnet-k8s/subnets/vnet-k8s-master-subnet",
      "firstConsecutiveStaticIP": "10.2.0.239",
      "vnetCidr": "10.2.0.0/16"
    },
    "agentPoolProfiles": [
      {
        "name": "deliverypool",
        "count": 1,
        "vnetSubnetId": "/subscriptions/XXXX/resourceGroups/victor-acs-engine/providers/Microsoft.Network/virtualNetworks/vnet-k8s/subnets/vnet-k8s-deliverypool-subnet",
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      },
      {
        "name": "telluricpool",
        "count": 1,
        "vnetSubnetId": "/subscriptions/XXXX/resourceGroups/victor-acs-engine/providers/Microsoft.Network/virtualNetworks/vnet-k8s/subnets/vnet-k8s-telluricpool-subnet",
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }

    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

```

**Comment by todoesverso** [comment]
The same test fails to me:

`
$ kubectl run --image library/nginx:latest default --labels=app=ingress-nginx
deployment "default" created
$ cat a.yml 
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx
$ kubectl create -f a.yml 
service "ingress-nginx" created
$ kubectl get svc
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx   LoadBalancer   10.0.126.218   10.2.0.34     80:30444/TCP,443:31867/TCP   5m
kubernetes      ClusterIP      10.0.0.1       <none>        443/TCP                      3h
$ curl -vv 10.2.0.34
* Rebuilt URL to: 10.2.0.34/
*   Trying 10.2.0.34...
* TCP_NODELAY set
^C

`

**Comment by khaldoune** [comment]
@CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
I'll try to repro this today and get back to you

**Comment by todoesverso** [comment]
I was able to workaround the issue by having a single subnet in my vnet instead a subnet for each agent pool.

**Comment by CecileRobertMichon** [comment]
@todoesverso can I close this issue? Or is the multiple subnet scenario something you would expect to work? If so has it worked in the past? Is this a private cluster specific issue or does the same apply to clusters with public IPs?

**Comment by todoesverso** [comment]
I would expect multiple subnets to work, just because ace-engine allows you to build one, I mean, any combination of supported features should work right? Otherwise if there are any restrictions it would be helpful they are documented. I just tried it with a private cluster.
I guess with the proper documentation the issue can be closed.

**Comment by khaldoune** [comment]
@jackfrancis @@jcorioland

**Comment by jackfrancis** [comment]
@todoesverso Our notion of "supported features" is squishy right now (it more or less correlates to regular E2E test coverage, which will tell us when scenarios that we expect to work stop working).

The current state of acs-engine encourages folks to experiment, and not always by building 1st class features with strict test coverage; which means that it is possible to produce a cluster configuration that may not work out of the box, owing to combinatoric particulars that have not yet been vetted.

Not trying to be evasive, just to emphasize what @CecileRobertMichon said earlier: has this scenario ever worked in the past? If so, we can identify this as a regression and work toward a fix w/ tests.

**Comment by todoesverso** [comment]
@jackfrancis I understand completly. Unfortunatly I cannot say this is a regression. I am unsing a single subnet now and things are working. I guess this can be closed and in the case I really need multiple subnets I can re open it. Regards, Victor

**Comment by jackfrancis** [comment]
Thanks @todoesverso

**Comment by hmarcelodn** [comment]
@jackfrancis I am facing the same issue right now and it was working on 1.6.6 with multiple subnets.

Is there any workaround on this? Do you know why it just stop working?

Thanks.

**Comment by CecileRobertMichon** [comment]
@hmarcelodn are you using private clusters as well? or is this a regular cluster with public IPs?

**Comment by hmarcelodn** [comment]
I am using a regular cluster this time, it was working before with 1.6.6.

**Comment by jackfrancis** [comment]
Has anyone tried a multiple subnet scenario + ILB workloads + v1.9.6 of k8s? (you'll need acs-engine `v0.14.4` to deploy `v1.9.6`)

**Comment by robsonpeixoto** [comment]
Is not working here.

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.9.6",
      "kubernetesConfig": {
        "privateCluster": {
          "enabled": true
        }
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "homolog",
      "vmSize": "Standard_B1ms",
      "vnetSubnetId": "???",
      "firstConsecutiveStaticIP": "172.31.3.150",
      "vnetCidr": "172.31.0.0/22",
      "distro": "ubuntu"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool",
        "count": 2,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "???",
        "distro": "ubuntu"
      }
    ],
    "linuxProfile": {
      "adminUsername": "???",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "???"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "???",
      "secret": "???"
    }
  }
}

```

My service and deployment definition:
```yaml
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: robsonpeixoto/echo-server
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: echo
  labels:
    app: echo
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: echo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
```

**Comment by amitshowry** [comment]
I'm using single custom vnet["172.29.0.0/16"], subnet ["172.29.0.0/16"], Deployed ACS Kubernetes cluster  below versions 
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.9",
      "orchestratorVersion": "1.9.4",

Default Namespace : Events
Error creating load balancer (will retry): failed to ensure load balancer for service default/ingress-nginx: network.LoadBalancersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '1f84df17-2e76-4c46-add7-7ccc256204b2' with object id '1f84df17-2e76-4c46-add7-7ccc256204b2' does not have authorization to perform action 'Microsoft.Network/loadBalancers/read' over scope '/subscriptions/4b9a0c7a-e8b2-4377-8d96-a75cbfe766c8/resourceGroups/EDSP-ACS-EastUS/providers/Microsoft.Network'."

Tried to deploy below template 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx
```
Events : 
  Normal   EnsuringLoadBalancer        1m (x7 over 6m)  service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  1m (x7 over 6m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/ingress-nginx: network.LoadBalancersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '1f84df17-2e76-4c46-add7-7ccc256204b2' with object id '1f84df17-2e76-4c46-add7-7ccc256204b2' does not have authorization to perform action 'Microsoft.Network/loadBalancers/read' over scope '/subscriptions/4b9a0c7a-e8b2-4377-8d96-a75cbfe766c8/resourceGroups/EDSP-ACS-EastUS/providers/Microsoft.Network'."

```bash
azureuser@k8s-master-39781074-0:~$ kubectl get svc --all-namespaces
NAMESPACE     NAME                   TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
default       ingress-nginx          LoadBalancer   10.0.73.245   <pending>     80:30345/TCP,443:32315/TCP   11m
default       kubernetes             ClusterIP      10.0.0.1      <none>        443/TCP                      4h
kube-system   heapster               ClusterIP      10.0.24.23    <none>        80/TCP                       4h
kube-system   kube-dns               ClusterIP      10.0.0.10     <none>        53/UDP,53/TCP                4h
kube-system   kubernetes-dashboard   NodePort       10.0.35.73    <none>        443:31415/TCP                4h
kube-system   metrics-server         ClusterIP      10.0.1.235    <none>        443/TCP                      4h
kube-system   tiller-deploy          ClusterIP      10.0.234.0    <none>        44134/TCP                    4h


NAME                      STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION      CONTAINER-RUNTIME
k8s-edspnode-39781074-0   Ready     agent     4h        v1.9.4    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1012-azure   docker://1.13.1
k8s-master-39781074-0     Ready     master    4h        v1.9.4    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1012-azure   docker://1.13.1


azureuser@k8s-master-39781074-0:~$ kubectl get pods --all-namespaces  -o wide
NAMESPACE     NAME                                            READY     STATUS    RESTARTS   AGE       IP               NODE
kube-system   heapster-6599f48877-wrds6                       2/2       Running   0          4h        172.29.0.21      k8s-edspnode-39781074-0
kube-system   kube-addon-manager-k8s-master-39781074-0        1/1       Running   0          4h        172.29.255.239   k8s-master-39781074-0
kube-system   kube-apiserver-k8s-master-39781074-0            1/1       Running   2          4h        172.29.255.239   k8s-master-39781074-0
kube-system   kube-controller-manager-k8s-master-39781074-0   1/1       Running   0          4h        172.29.255.239   k8s-master-39781074-0
kube-system   kube-dns-v20-597689868c-26ncb                   3/3       Running   0          4h        172.29.0.9       k8s-edspnode-39781074-0
kube-system   kube-dns-v20-597689868c-xj52z                   3/3       Running   0          4h        172.29.0.12      k8s-edspnode-39781074-0
kube-system   kube-proxy-94wvn                                1/1       Running   0          4h        172.29.0.4       k8s-edspnode-39781074-0
kube-system   kube-proxy-jjp5z                                1/1       Running   0          4h        172.29.255.239   k8s-master-39781074-0
kube-system   kube-scheduler-k8s-master-39781074-0            1/1       Running   0          4h        172.29.255.239   k8s-master-39781074-0
kube-system   kubernetes-dashboard-697d9d4f78-4h5nm           1/1       Running   0          4h        172.29.0.13      k8s-edspnode-39781074-0
kube-system   metrics-server-99b948fd5-8hcc6                  1/1       Running   0          4h        172.29.0.29      k8s-edspnode-39781074-0
kube-system   monitoring-grafana-76848b566c-86h6q             1/1       Running   0          1h        172.29.0.20      k8s-edspnode-39781074-0
kube-system   monitoring-influxdb-6c4b84d695-2k7lq            1/1       Running   0          1h        172.29.0.23      k8s-edspnode-39781074-0
kube-system   tiller-deploy-7779ffcf89-tdkx7                  1/1       Running   0          4h        172.29.0.18      k8s-edspnode-39781074-0

```

**Comment by feiskyer** [comment]
Kubernetes azure cloud provider doesn't handle multiple subnets well. Let me open an issue to track and fix this issue.

**Comment by amitshowry** [comment]
@feiskyer - Thanks, I'm not using multiple subnets here, its one vnet["172.29.0.0/16" Address space], subnet ["172.29.0.0/16"], i'm checking service principle with Cloud team.

**Comment by lehtiton** [comment]
Anyone got this working?

I have been trying to create a cluster with acs-engine that is deployed to my private vnet (need a data center l2l vpn access) for a long time now and would really appreciate if someone could give me some hints how to get that done. I have just faced an issue after issue. I have tried several versions of acs-engine with several different orchestrator releases and version. I think the latest trial with the following configs is the best result so far even tough it's not working (see the issues I am facing on the bottom) :-(

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "orchestratorVersion": "1.8.8",
      "kubernetesConfig": {
        "networkPolicy": "none",
        "privateCluster": {
          "enabled": true,
          "jumpboxProfile": {
            "name": "k8s-jb",
            "vmSize": "Standard_D4s_v3",
            "username": "***",
            "publicKey": "***"
          }
        }
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "acsengine01",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "***",
      "firstConsecutiveStaticIP": "*.*.69.239",
      "vnetCidr": "*.*.69.128/25"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        "ipAddressCount" : 10,
        "vnetSubnetId": "***"
      }
    ],
    "linuxProfile": {
      "adminUsername": "***",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "***"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "***",
      "secret": "***"
    }
  }
}


So, what I have done is that I have first used acs engine to create the azure templates, then run post-deployment commands advised in https://github.com/Azure/acs-engine/blob/master/docs/custom-vnet.md#post-deployment-attach-cluster-route-table-to-vnet and finally logged in to master (via jump server) and executed kubectl create for above mentioned deployment. The pods get up according to kubectl, but the following lists the issues I have recognized so far. 


Problem 1: cannot connect my pods
***@k8s-jb:~$ kubectl logs cmsapi-beta-deployment-85644b49c5-dbft4
Error from server: Get https://k8s-agentpool1-31111984-0:10250/containerLogs/default/xxx-deployment-85644b49c5-dbft
4/xxx-container: dial tcp: lookup k8s-agentpool1-31111984-0 on 192.168.252.139:53: server misbehaving

Problem 2: cannot see service loadbalancer IP (expecting to see private subnet ip *.*.69.x)
***@k8s-jb:~$ kubectl get services
NAME                  TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
xxx-service           LoadBalancer   10.0.180.211   <pending>     3001:30227/TCP   31m
kubernetes            ClusterIP      10.0.0.1       <none>        443/TCP          43m

Problem 3: kubectl describe services shows errors with access
Warning  CreatingLoadBalancerFailed  2m (x6 over 4m)     service-controller  Error creating load balancer (will retry): E
rror getting LB for service default/kubernetes: network.LoadBalancersClient#Get: Failure responding to request: StatusCode=
403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client
 '***' with object id '***' does not have authorization to 
perform action 'Microsoft.Network/loadBalancers/read' over scope '/subscriptions/***/resourceGroups/***/
providers/Microsoft.Network/loadBalancers/acsengine01'."

**Comment by lehtiton** [comment]
Updating previous post above so that after creating the service principal again (az ad sp create-for-rbac --role="Contributor"  --scopes="/subscriptions/***") I got rid of the issues 2 and 3. However the  issue 1 with connecting to my pod (from master) still remained. 

Here is what I get when calling e.g. "kubectl logs <pod>":
Error from server: Get https://k8s-agentpool1-31111984-0:10250/containerLogs/default/xxx-deployment-85644b49c5-spksm/xxx-container: dial tcp: lookup k8s-agentpool1-31111984-0 on 192.168.252.139:53: server misbehaving

**Comment by amitshowry** [comment]
@lehtiton - After creating sp, you have to Add "SPN object ID" in IAM role as "Contributor" of target ResourceGroup where Cluster will be deployed 

az role assignment create --assignee "Object_ID" --role "Contributor" --scope "/subscriptions/Subscription_ID/resourceGroups/RG_NAME"

**Comment by feiskyer** [comment]
Kubernetes v1.11 adds standard load balancer support. Have someone tried it with multiple subnets?
