### ISSUE TITLE
K8s cluster deployment with more than one master fails on AzureGermanCloud

### ISSUE THREAD

**Issue by ITler** [Azure/acs-engine#2480]
**Is this a request for help?**:
no
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
0.13.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8s 1.8.8

**What happened**:
Almost there.
However, deployment of K8s cluster with **more than one master node** (count: 3) on AzureGermanCloud fails. No problem with single master cluster! 

	Deployment failed. {
		"status": "Failed",
		"error": {
			"code": "ResourceDeploymentFailure",
			"message": "The resource operation completed with terminal provisioning state 'Failed'.",
			"details": [
			{
				"code": "VMExtensionProvisioningTimeout",
				"message": "Provisioning of VM extension 'cse2' has timed out. Extension installation may be taking too long, or extension status could not be obtained."
			}
			]
		}
	}

Even if the cluster would have been bootstrapped, correctly, as I see all resources and this error was explained to me as a cosmetical issue, I nevertheless can't work with failed ARM deployments as they lack the *.property.outputs* JSON data, which I want to process further in our deployment automation chain.    

**What you expected to happen**:
...

**How to reproduce it** (as minimally and precisely as possible):

	{
		"apiVersion": "vlabs",
		"location": "germanycentral",
		"properties": {
			"orchestratorProfile": {
				"orchestratorType": "Kubernetes",
				"orchestratorRelease": "1.8",
				"orchestratorVersion": "1.8.8"
			},
			"masterProfile": {
				"count": 3,
				"dnsPrefix": "itltest",
				"vmSize": "Standard_A2_v2",
				"vnetSubnetId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/itltest_germanycentral/providers/Microsoft.Network/virtualNetworks/itltest_germanycentral-vnet/subnets/itltest_germanycentral-vnet-subnet",
				"firstConsecutiveStaticIP": "172.29.3.240",
                                "vnetCidr": "172.29.2.0/23"
			},
			"agentPoolProfiles": [
			{
				"name": "pool1",
				"availabilityProfile": "AvailabilitySet",
				"count": 2,
				"storageProfile": "ManagedDisks",
				"vmSize": "Standard_A2_v2",
				"vnetSubnetId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/itltest_germanycentral/providers/Microsoft.Network/virtualNetworks/itltest_germanycentral-vnet/subnets/itltest_germanycentral-vnet-subnet"
			}
			],
			"linuxProfile": {
				"adminUsername": "testuser",
				"SSH": {
					"publicKeys": [
					{
						"keyData": ""
					}
					]
				}
			},
			"servicePrincipalProfile": {
				"clientID": "00000000-0000-0000-0000-000000000000",
				"secret": "00000000-0000-0000-0000-000000000000"
			}
		}
	}

Running:

    acs-engine generate <rendered-config-above>.json
    az group deployment create --template-file azuredeploy.json --parameters azuredeploy.parameters.json [... whatever else is necessary to create an ARM deployment]

**Anything else we need to know**:
- **AzureGermanCloud**
- AzureCNI setup

**Comment by ITler** [comment]
I will give it a try with 0.14.0, as I've seen, that there is a merge request that seems to address this. Will report back

**Comment by vpatelsj** [comment]
Regarding the cse2 extension failure, we can check the logs of your custom script extension execution from the master/agent nodes vm? they should be located at /var/log/azure/blah blah folder.

**Comment by ITler** [comment]
@vpatelsj This not relevant for me anymore, as I now use 0.14.4 to deploy k8s 1.9.6

That's why I close this
