### ISSUE TITLE
Add retry for downloading external resources in kuberneteswindowssetup.ps1 

### ISSUE THREAD

**Issue by JiangtianLi** [Azure/acs-engine#2481]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:

**What you expected to happen**:
Add retry for downloading external resources in kuberneteswindowssetup.ps1 to make it resilient to failure.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
Here are some examples how we do this for Linux clusters:

https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesmastercustomdata.yml#L364
https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesmastercustomscript.sh#L512
