### ISSUE TITLE
Unable to access on-prem resources over Express Route

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#2504]
**Is this a request for help?**:
Help
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**:
0.13
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.7

**What happened**:
Containers running on the cluster via Pods are unable to access on-prem services (e.g. a database). The agent nodes ARE able to reach these on-prem services (e.g. they can route to the internal IPs over our Express Route properly).  The kubernetes cluster was created with a "networkPolicy=none". Hitting external (e.g. Internet) IPs works fine.

**What you expected to happen**:
Containers running on the cluster should be able to route just like the host can.

**How to reproduce it** (as minimally and precisely as possible):
I deployed the tutum/curl container using:

  kubectl run -it --image=tutum/curl client --restart=Never

And can route to things like http://www.google.com but not to http://some.on-prem.resource/

**Anything else we need to know**:

**Comment by vpatelsj** [comment]
With little info about your setup I am wondering if you checked your nsg rules to see if the appropriate ports are opened for accessing the database services etc.

**Comment by dcieslak19973** [comment]
Thanks. I should have mentioned that I set up an ANY/ANY rule on the affected NSG.

I’m not great with networking, but my gut feeling is that the Route Table may be the problem

My company does have an NDA in place with Microsoft and I could make arrangements for a Microsoft employee to screen share

**Comment by sharmasushant** [comment]
@dcieslak19973 Please use networkpolicy as azure. This will give your PODs ip addresses from vnet address space, and pods should be able to reach on-prem.

**Comment by dcieslak19973** [comment]
#2529 closes this.
