### ISSUE TITLE
Modifying toleration on Kube-Proxy Daemonset reverts back to default

### ISSUE THREAD

**Issue by davidchua** [Azure/acs-engine#2509]
**Is this a request for help?** : Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**:

➜  acs git:(master) ✗ acs-engine version
Version: v0.11.0
GitCommit: cda96312
GitTreeState: clean
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
When editing `kube-proxy` daemonset with a new Toleration or modifying existing toleration via `kubectl edit ds kube-proxy -n kube-system`, changes was applied momentary but within 1-2 minutes, the changes were reverted back to the default.

Background is I have a node that's tainted with a `dedicated=something:NoSchedule` and it is causing both `kube-proxy` and `calico-node` `DaemonSets` to not schedule on it.

Modifying `calico-node`'s toleration was successful, changes was applied and persisted. Calico runs on the tainted node.

Doing the same for `kube-proxy` caused `kube-proxy` to momentary spawn on the node, but after 1-2 minutes, `kube-proxy` shutsdown. Doing another `kubectl edit ds kube-proxy -n kube-system`. Shows that the previously made changes was reverted, although `metadata.generation` at this point increased by `2`.

I've tested another scenario by adding a new `annotations` for `kube-proxy` and the changes persisted unlike `tolerations`.

**What you expected to happen**:
The tolerations to be persistently applied.

**How to reproduce it** (as minimally and precisely as possible):

1. `kubectl taint node <node> somekey:value:NoSchedule`
2. `kubectl edit ds kube-proxy -n kube-system` and add a new Toleration like:

```
- effect: NoSchedule
   operator: Exists
```

3. `kubectl get po -n kube-system | grep kube-proxy` should now show an additional `kube-proxy` spawn up
4. After 1-2 minutes, you should notice that newly created `kube-proxy` spinning down/terminated.
5. `kubectl edit ds kube-proxy -n kube-system` will now show the Toleration revert back to the original:

```
   72       - effect: NoSchedule
   73         key: node-role.kubernetes.io/master
   74         operator: Equal
   75         value: "true"
```

**Anything else we need to know**:

Describing `ds/kube-proxy`

Shows the events:

```
  Normal  SuccessfulCreate  22m   daemon-set  Created pod: kube-proxy-np7wl
  Normal  SuccessfulDelete  22m   daemon-set  Deleted pod: kube-proxy-mk85h
```

**Comment by carlpett** [comment]
`kube-proxy` is run as an "addon" in the cluster, this means (to the best of my understanding) that the `kube-addon-manager` will reconcile the running definition with it's on-disk definition in `/etc/kubernetes/addons/kube-proxy-daemonset.yaml` every few minutes. 
So, if you need to modify it, you have to change it on disk on all your master nodes.
