### ISSUE TITLE
High etcd 2.2.5 IO writes and CPU IOwait on really small Kubernetes cluster (3 nodes)

### ISSUE THREAD

**Issue by zwindler** [Azure/acs-engine#2510]
**ISSUE/HELP**

**Orchestrator Kubernetes 1.7.10 and etcd 2.2.5**

**What happened**:
We have a few really small Kubernetes clusters hosted on azure virtual machines (IaaS) and deployed with acs-engine.
The SSD storage hosting etcdDisk is providing 500 IOPS and a throughput limit of 100 MB/sec which seemed to be more than enough for this really small cluster.

On all clusters, we are recording a really high amount of CPU IOwait on all master nodes (~40%) and a constant 300 IOPS (100% writes) and 1MB/s writen. All of this comes from the etcd process and is located on etcd own disk.

As far as we can tell, the azure SSD disk hosting etcd working directory is not up to its limit (we made some tests and got to the advertised 500 with both big and small writes). The performance throughput doesn't seem to be the issue also as we are very far from the 100 MB/s limit.

**What you expected to happen**:
I'm really skeptical about this intensive write use of the SSD provided to etcd and I feel that this is not a normal behaviour, especially for such a small cluster (3 workers only !).

Can you provide me with some input regarding whether or not this is a normal behaviour ?

**Comment by jackfrancis** [comment]
Hi @zwindler, we have an open PR that aims to address why this may happen:

https://github.com/Azure/acs-engine/pull/2435

Also, a more recent version of acs-engine will build you a cluster with newer versions of both Kubernetes and etcd. Are you able to migrate to a fresh cluster? If not, if you provide your initial api-model, and the version of acs-engine you used to deploy your existing cluster, I can investigate if `acs-engine upgrade` is likely to work for you.

**Comment by zwindler** [comment]
Thanks for the answer.

I have seen the PR which will give more IOPS to the disk but as the SSD are not at the maximum IOPS limit, I'm not 100% sure this is the issue here. I'll give it a try nonetheless because if this is just it, this would be convenient.

I'm not sure what you mean by "initial api-model" because I'm not the one who deployed the cluster in the first place. Those clusters are in use so I can't migrate easily, but updating is a valuable option that we are considering.

Thanks again.
