### ISSUE TITLE
ILB is not working after deploying K8S 1.9.3

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#2517]
**Is this a request for help?**:
YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.13.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
1.9.3

**What happened**:

We regenerated the cluster in order to upgrade our acs-engine + Kubernetes versions and deployed the NGINX with a ILB service and we loose connection from a paired VNET.

**What you expected to happen**:

ILB needs to be working.

**How to reproduce it** (as minimally and precisely as possible):

Using two vnets (one for the cluster and one for the api management) and deploy the cluster on 1 of the vnets.

**Anything else we need to know**:

No

**Comment by jackfrancis** [comment]
There are known ILB issues with v1.9.3, this has been fixed in v1.9.6 (acs-engine v0.14.4)
