### ISSUE TITLE
networkPolicy=Azure and Existing VNET outside of Resource Group failing

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#2529]
**Is this a request for help?**: HELP

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.14.4

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes 1.9.6

**What happened**: Provisioning a Kubernetes 1.9.6 cluster with "bring-your-own-VNET" using Azure Networking fails; the Custom Script extension running on Master (CSE0) fails with an exit code of 3

**What you expected to happen**: Provisioning to work

**How to reproduce it** (as minimally and precisely as possible): Create a 1.9 cluster with networkPolicy= true (and enableRbac=false) as well as 2 different VNETS (one for masterProfile the other for agentProfile) where the VNETS are in a different Resource Group than the one that ACS-Engine will deploy to

**Anything else we need to know**:
Previously, I had used prior versions (0.12.5 and 0.13.0) to create clusters of k8s v 1.8.x and the process created a RouteTable object. I do not see any RouteTable objects being created. Not sure if that is expected or not. That said, routing seems to be working in the cluster; I can ping agent nodes from the master node

**Comment by sylr** [comment]
You should look in one of those file: https://github.com/Azure/acs-engine/blob/4649c8d41bd37d350b0842cd76f2e7db21d05e43/test/e2e/runner/cli_provisioner.go#L222-L223

**Comment by dcieslak19973** [comment]
So far it looks like it thinks the k8s cluster isn't working after 600 seconds and fails. It appears to me to be because the k8s master node cannot get any kubectl commands to work. This appears to me to be because it can't seem to get a route to the public IP address of the kubernetes cluster.

I'm going to try setting the privateCluster option to see if that helps. I seem to remember that being my starting point today without luck, but maybe another attempt will clarify.

**Comment by dcieslak19973** [comment]
When I run `kubectl cluster-info dump` I get `The connection to the server x.y.z.10:443 was refused - did you specify the right host or port?` The IP address is the correct IP address of the (single) master node. Any ideas?

**Comment by sylr** [comment]
Thhe kubernetes master does not seem to have started up correctly, you should look into the kubernetes log files.

**Comment by dcieslak19973** [comment]
`● kubelet.service - Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2018-03-26 21:57:53 UTC; 4s ago
  Process: 7521 ExecStartPre=/bin/bash /opt/azure/containers/kubelet.sh (code=exited, status=2)

Mar 26 21:57:53 k8s-master-17778578-0 systemd[1]: kubelet.service: Unit entered failed state.
Mar 26 21:57:53 k8s-master-17778578-0 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Mar 26 21:57:53 k8s-master-17778578-0 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Mar 26 21:57:53 k8s-master-17778578-0 systemd[1]: Stopped Kubelet.
Mar 26 21:57:53 k8s-master-17778578-0 systemd[1]: kubelet.service: Start request repeated too quickly.
Mar 26 21:57:53 k8s-master-17778578-0 systemd[1]: Failed to start Kubelet.
`

When I run:

`sudo /opt/azure/containers/kubelet.sh`

I get:

`Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.`

Which seems to come from this line in the script:

`iptables -t nat -A POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d  -j MASQUERADE`

I am not very familiar with iptables....

**Comment by sharmasushant** [comment]
@dcieslak19973  
You can follow the example here: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#feat-custom-vnet 

You have to specify the vnetCidr which is missing in your config it seems like.

**Comment by dcieslak19973** [comment]
Thanks @sharmasushant. I was missing the vnetCidr in my acs-engine file.
