### ISSUE TITLE
Nvidia GPU support broken in master

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#2538]
Placeholder ticket for now, // TODO: investigation

Our E2E tests are showing us that building a cluster w/ `Standard_NC6` agent nodes are not able to schedule a pod for `nvidia-smi`.

@wbuchwalter FYI. If you're able to build from master and deploy a new cluster, it'd be awesome if you could try to repro!

**Comment by wbuchwalter** [comment]
@jackfrancis Not exactly sure what is happening here...
On the agent, journalctl reports:
```
+ retrycmd_if_failure 5 10 curl -fLS https://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run -o nvidia-drivers-390.30
+ timeout curl -fLS https://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run -o nvidia-drivers-390.30
+ timeout curl -fLS https://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run -o nvidia-drivers-390.30
+ timeout curl -fLS https://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run -o nvidia-drivers-390.30
+ timeout curl -fLS https://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run -o nvidia-drivers-390.30
+ timeout curl -fLS https://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run -o nvidia-drivers-390.30
Executed "-fLS https://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run -o nvidia-drivers-390.30" 5 times
```

But if I manually do `curl -fLS https://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run` from the node, it works fine.
Have you ever seen a similar issue?

**Comment by jackfrancis** [comment]
Thanks for doing that R&D, I'll look into that! (possibly something flaky about that `retry_if_failure` convenience func)
