### ISSUE TITLE
acs-engine should print template outputs at exit

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2554]
Moving from https://github.com/kargakis/acs-engine/issues/34

> It'd be great if, instead of just printing "Finished ARM Deployment" at the end of a run, it printed the template outputs (like where to https / ssh to...)

@jim-minter

**Comment by kwoodson** [comment]
@kargakis,

This is the pattern we have setup for this but will require an updated client or at least more information returned from the `DeployTemplate` call.

https://github.com/Azure/acs-engine/pull/3193
