### ISSUE TITLE
[Azure] VirtualMachineScaleSets and Kubernetes 1.10

### ISSUE THREAD

**Issue by Drupi** [Azure/acs-engine#2564]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.14.5
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes (v 1.10)

**What happened**:
During the generate of api-model from Kubernetes.json  I get following message:

INFO[0000] Error returned by LoadContainerService: VirtualMachineScaleSets are not supported with Kubernetes since Kubernetes requires the ability to attach/detach disks.  To fix specify "AvailabilityProfile":"AvailabilitySet"
FATA[0000] error validating generateCmd: error parsing the api model: VirtualMachineScaleSets are not supported with Kubernetes since Kubernetes requires the ability to attach/detach disks.  To fix specify "AvailabilityProfile":"AvailabilitySet"

**What you expected to happen**:
Should build without any issues. 

**How to reproduce it** (as minimally and precisely as possible):
allow the acs-engine to build scale sets template with Kubernetes. 

**Anything else we need to know**:
According to the change list of K8s 1.10 the scale sets are now supported. 

Here is a link to : https://kubernetes.io/docs/imported/release/notes/#azure

**Comment by feiskyer** [comment]
#2403 is aiming to add this.

cc @JiangtianLi
