### ISSUE TITLE
Request for documentation: Redeployment of nodes without upgrading Kubernetes

### ISSUE THREAD

**Issue by neurot1cal** [Azure/acs-engine#2568]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Request
---

**What version of acs-engine?**:
v0.9.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.2

**What happened**:
Nothing (Yet)

**What you expected to happen**:
I expect that when running `./acs-engine deploy` with the same data from the _output folder the cluster was built from, the deployment process will recognize that only objects that dont exist in Azure will be created.

For example, we have 2 Windows nodes that we would like to drain/delete/rebuild, instead of patching in place (For monthly security patches). I'm looking for documentation somewhere on how this process is recommended to be done through acs-engine.

Based on what I've found from `./acs-engine scale`, it appears that you can deploy again and only have the new nodes deployed. Any guidance here would be appreciated.

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@neurot1cal is https://github.com/Azure/acs-engine/blob/master/docs/kubernetes-day2-operations.md what you're looking for?

**Comment by neurot1cal** [comment]
This talks about how to reduce the number of nodes, either up or down, but doesn’t talk about how to redeploy a node if it ever becomes unhealthy or unresponsive. Seems strange to me that we have such a good set of patterns for auto healing primitives within the cluster, but node scaling, repair and reprovisioning are very manual. 

Short of writing my own control loop outside of the cluster, or hopefully using VM Scake Sets, is there any plans on doing something like this with either acs-engine or AKS?
