### ISSUE TITLE
Could not connect to Windows pod by port 10250

### ISSUE THREAD

**Issue by andyzhangx** [Azure/acs-engine#2573]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE 
---

**What version of acs-engine?**:
latest master(commit 05ebc78b57ce2ef92a83bcf6b81b3a9b46ce7f0b)
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Could not connect to Windows pod by port 10250 or query pod stats/summary by port 10255, it's a regression on v1.10.0 Windows cluster, it works well for Linux pod.
```
azureuser@k8s-master-20941235-0:~kubectl exec -it aspnet -- cmd
Error from server: error dialing backend: dial tcp 10.240.0.34:10250: getsockopt: connection timed out
azureuser@k8s-master-20941235-0:~$ curl http://20941k8s9010:10255/stats/summary
curl: (7) Failed to connect to 20941k8s9010 port 10255: Connection timed out
```

While if I connect to that Windows node, and run following command by localhost, it works well, so I guess there is some network configuration not correct for Windows:
```
PS C:\> $response = wget http://localhost:10255/stats/summary -UseBasicParsing
PS C:\> echo $response
StatusCode        : 200
StatusDescription : OK
Content           : {
                      "node": {
                       "nodeName": "20941k8s9010",
                       "startTime": "2018-04-02T06:52:31Z",
                       "cpu": {
                        "time": "2018-04-02T07:17:35Z",
                        "usageCoreNanoSeconds": 54780000000
                       },
                       "memory": {
                        "t...
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Content-Type: application/json
                    Date: Mon, 02 Apr 2018 07:17:40 GMT

                    {
                      "node": {
                       "nodeName": "20941k8s9010",
                       "startTime": "2018-04-02T06:52:31Z",...
Forms             :
Headers           : {[Transfer-Encoding, chunked], [Content-Type, application/json], [Date, Mon, 02 Apr 2018 07:17:40
                    GMT]}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        :
RawContentLength  : 2370
```
**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
1. use laest master branch(commit 05ebc78b57ce2ef92a83bcf6b81b3a9b46ce7f0b) to deploy windows cluster
2. create a simple pod on windows
```kubectl create -f https://raw.githubusercontent.com/andyzhangx/Demo/master/windows/basic/aspnet-pod.yaml```

#### watch the status of pod until its `Status` changed from `Pending` to `Running`
```watch kubectl describe po aspnet```

3. enter the pod container to do validation
```kubectl exec -it aspnet -- cmd```

**Anything else we need to know**:

@JiangtianLi @feiskyer

**Comment by feiskyer** [comment]
Seems kubelet is not listening at 10250? are there any errors in kubelet logs?

**Comment by andyzhangx** [comment]
@feiskyer 10250 & 10255 are all being listened on that windows node
```
I0402 03:26:30.748044    2928 csi_plugin.go:61] kubernetes.io/csi: plugin initializing...
I0402 03:26:30.748044    2928 plugins.go:454] Loaded volume plugin "kubernetes.io/csi"
I0402 03:26:30.749044    2928 server.go:149] Starting to listen read-only on 0.0.0.0:10255
I0402 03:26:30.749044    2928 healthz.go:74] Installing healthz checkers:"ping", "syncloop"
I0402 03:26:30.750044    2928 server.go:428] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"20941k8s9010", UID:"20941k8s9010", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Starting' Starting kubelet.
I0402 03:26:30.750044    2928 config.go:99] Looking for [api], have seen map[]
I0402 03:26:30.750044    2928 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
I0402 03:26:30.750044    2928 status_manager.go:140] Starting to sync pod status with apiserver
I0402 03:26:30.750044    2928 kubelet.go:1777] Starting kubelet main sync loop.
I0402 03:26:30.750044    2928 kubelet.go:1794] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
I0402 03:26:30.750044    2928 generic.go:183] GenericPLEG: Relisting
I0402 03:26:30.750044    2928 server.go:129] Starting to listen on 0.0.0.0:10250
I0402 03:26:30.751044    2928 healthz.go:74] Installing healthz checkers:"ping", "syncloop"
```

**Comment by andyzhangx** [comment]
I found I even could not ping windows node, windows version is 
```
>ver
Microsoft Windows [Version 10.0.16299.248]
```

**Comment by JiangtianLi** [comment]
@andyzhangx Can you curl the aspnet POD?

**Comment by andyzhangx** [comment]
@JiangtianLi  I could ping aspnet pod from master, while I could not ping windows node

**Comment by JiangtianLi** [comment]
@andyzhangx ping may be blocked on Azure. Can you use telnet or netcat to test connection to node on a specific port?

**Comment by caseywatson** [comment]
Was this ever resolved? I am facing the same issue.

**Comment by JiangtianLi** [comment]
@caseywatson what k8s version and acs-engine you are using? Do you have windows only cluster or hybrid cluster?

**Comment by jakubmalin** [comment]
Any new update on this? I am experiencing the same issue with:
acs-engine version Version: v0.16.2

Has anyone went through this issue and finally connected to the pod?

**Comment by sam-cogan** [comment]
I deployed from the master branch a few days ago and it seemed to work, do looks like a fix is in

**Comment by andyzhangx** [comment]
@jakubmalin v0.17.1 should have fixed this issue. all firewall should be turned off for Azure CNI which is the default. You may also fix this issue by `netsh advf set allprofiles state off` on windows node.
