### ISSUE TITLE
Add docs for ACI connector clientKey val as keyvault

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#2574]
Once we mature the use-case of using clientKey as keyvault reference, let's update this doc to clarify that option:

https://github.com/Azure/acs-engine/tree/master/examples/addons/aci-connector

**Comment by jackfrancis** [comment]
@vglafirov if you could do this extra credit work, great, otherwise this issue as a reminder

**Comment by CecileRobertMichon** [comment]
Also need to append `kubernetesACIConnectorClientKey` to the following list: https://github.com/Azure/acs-engine/blob/80c0c83b426caafa644ad0d115c52b6d37209b64/pkg/acsengine/engine.go#L110
