### ISSUE TITLE
 server misbehaving

### ISSUE THREAD

**Issue by kapopken** [Azure/acs-engine#2597]
**Is this a request for help?**:
YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.15.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10

**What happened**:
When trying to communicate to pods inside the cluster, I get an error server misbehaving. Simply doing a ping or a curl to validate returns this errors going from pod to  service. I am able to provision external load balancers and deploy pods/deployments.
kubectl : Error from server: error dialing backend: dial tcp: lookup k8s-linuxpool-28650259-0 on 172.XX.XX.X:53: server misbehaving

**What you expected to happen**:
I expected a valid response

**How to reproduce it** (as minimally and precisely as possible):
Deploy a kubernetes cluster using the acs-engine to a custom vnet, and then try to communicate to any pod. In my case I ran this command: 
 kubectl exec -it employeeapi-79d7fd5498-xq7ld     -- curl http://employeeapi 
I tried NGINX and the controller output the same issue as well

**Anything else we need to know
![acs](https://user-images.githubusercontent.com/739819/38347016-35974248-385e-11e8-8469-da1e7231b1d1.PNG)

w**:

**Comment by lehtiton** [comment]
Does anyone know any workaround for this? I am facing this same issue with acs-engine 0.15.1 and orchestration version 1.8.8.

**Comment by jackfrancis** [comment]
@kapopken @lehtiton This looks like environmental symptoms we've seen intermittently in our test runs over the past couple weeks due to Azure DNS latency. Essentially, a now-patched bug in the DNS implementation caused a delay in VM DNS registrations.

Can you confirm that this follow-up deployments are not subject to this errata?

**Comment by kapopken** [comment]
Sorry everyone for late response. I determined this was due to using a custom DNS server. Once I switched to Azure DNS it worked fine. Closing this.
