### ISSUE TITLE
grafana not working with new fs changes.

### ISSUE THREAD

**Issue by martell** [Azure/acs-engine#2598]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**What version of acs-engine?**:
---
HEAD at time of posting

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

kubernetes 1.10.0

**What happened**:

The grafana pod has the following error

```
kubectl logs dashboard-grafana-123456789-12345
chown: changing ownership of '/var/lib/grafana/dashboards/..2018_04_05_08_37_14.684228320': Read-only file system
chown: changing ownership of '/var/lib/grafana/dashboards/..data': Read-only file system
chown: changing ownership of '/var/lib/grafana/dashboards': Read-only file system
```

**Comment by martell** [comment]
seems related https://github.com/runconduit/conduit/pull/646
need to bump grafana version

**Comment by martell** [comment]
https://github.com/kubernetes/charts/commit/5bb9765d496044b0e65581e8aa7489835b5e07ca#diff-2afd63ebacfc1dc10cf0ac0ac5a97d63

suggestions welcome, possibly bump the chart to a newer version?

**Comment by mwieczorek** [comment]
maybe it's related to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#changelog-since-v193 ?
> Changes secret, configMap, downwardAPI and projected volumes to mount read-only, instead of allowing applications to write data and then reverting it automatically. Until version 1.11, setting the feature gate ReadOnlyAPIDataVolumes=false will preserve the old behavior. (#58720, @joelsmith)

**Comment by oivindoh** [comment]
See https://github.com/grafana/grafana-docker/issues/140
