### ISSUE TITLE
Can acs-engine modify an already deployed cluster?

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#2599]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): QUESTION

---

**What version of acs-engine?**: 0.14.0+

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**: I've used acs-engine to deploy a simple 5-node (1-master) cluster; can I use acs-engine to modify that cluster (say, to add in the Virtual Kube to talk to an Azure Container Instance)? Or do I need to destroy the cluster and redeploy it?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by dcieslak19973** [comment]
Thanks; if it is better to redeploy a new cluster whenever one can, is there any guidance about how to handle data elements that have been persisted? For a trivial example, suppose I have an Elastic Search instance running in my ACS-Engine k8s cluster and would like to keep a rolling 30 day history. If I drop and recreate the cluster, how do I retain previously saved entries?

**Comment by mwieczorek** [comment]
@dcieslak19973 maybe you can use [Ark](https://github.com/heptio/ark/blob/master/docs/use-cases.md#cluster-migration) to migrate workloads (with PVs) to new cluster?

**Comment by dcieslak19973** [comment]
Thanks; I'll take a look at Ark - it sounds promising
