### ISSUE TITLE
Allowing https://github.com/Microsoft/Docker.DotNet to connect to a swarm cluster

### ISSUE THREAD

**Issue by pksorensen** [Azure/acs-engine#261]
Hi guys

I am experience abit with using https://github.com/Microsoft/Docker.DotNet to run some workloads in my ACS swarm cluster.  

I discovered that by default this is not possible: http://stackoverflow.com/questions/42170378/what-is-the-proper-endpoint-for-connecting-to-azure-container-service-swarm-clus/42170719#42170719

Just to see that i could connect, i edited `sudo vim /etc/init/docker.conf` and forwarded the ports in the load balancer.   Added `DOCKER_OPTS='-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock'`

Now this works, but of cause is not secured. Also, this exposes the docker master for which swarm is running on, and not the swarm master. What would be needed to expose the remote api for the actually swarm cluster instead?

Since I am out of my core domain here, i was wondering if someone here has the expertise to verify that this would be a good starting point: http://tech.paulcz.net/2016/01/secure-docker-with-tls/

Are any of the certificates that was used to SSL setup somewhere on the machine and can be reused in some of the steps?

Lets say we figure out how to set it up properly, would there be some files from the acs-engine deployment that could be updated on the master to allow it to call the modified swarm-manager command that is needed with tlsverify when the machiens reboot, such one do not have to log in and do this every time.

```
docker run -d --name swarm-manager \
    -v /etc/docker/ssl:/etc/docker/ssl \
    --net=host swarm:latest manage \
    --tlsverify \
    --tlscacert=/etc/docker/ssl/ca.pem \
    --tlscert=/etc/docker/ssl/cert.pem \
    --tlskey=/etc/docker/ssl/key.pem \
    etcd://127.0.0.1:2379
```

**Comment by colemickens** [comment]
Is this in regards to Swarm or Swarm Mode?

Would you be able to get by with unix or TCP socket forwarding over SSH? You could avoid all of this complexity if so?

Today, we don't generate PKI assets for Swarm or Swarm Mode clusters... so, this will likely be a fairly large modification as you'll need to add PKI assets to the apimodel, and support generating them the same way  we do with Kubernetes, and then get them into the VM via CustomScriptExtension.

>Now this works, but of cause is not secured. Also, this exposes the docker master for which swarm is running on, and not the swarm master. What would be needed to expose the remote api for the actually swarm cluster instead?

I don't really follow. It should be the same as issuing the docker swarm commands locally when you attach to the remote socket. I don't understand the distinction being made here or what you are blocked from doing that you expect to be able to do.

**Comment by colemickens** [comment]
cc: @amanohar

**Comment by anhowe** [comment]
Closing since the workaround is to get by with unix or TCP socket forwarding over SSH
