### ISSUE TITLE
Using custom images errors

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#2629]
**Is this a request for help?**:

---
yes
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---
ISSUE
**What version of acs-engine?**:

---
master
```
commit d574b1020d751c102dc075410e8e91909ca1c04d (HEAD -> master, origin/master, origin/HEAD)
Author: Jack Francis <jackfrancis@gmail.com>
Date:   Fri Apr 6 16:34:28 2018 -0700

    retry apt-mark hold and apt-mark unhold (#2625)
```

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Specified a custom VHD image in the API model for agents and one master. The master provisioned but the agents failed to deploy and got this error:

```json
{
  "error": {
    "code": "BadRequest",
    "target": "vm.properties.storageProfile.imageReference.id",
    "message": "Could not find member 'id' on object of type 'PlatformImageReference'. Path 'properties.storageProfile.imageReference.id', line 1, position 26006."
  }
}
```

**What you expected to happen**:
agents and masters would boot from custom image

**How to reproduce it** (as minimally and precisely as possible):
I used this apimodel:

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "imageReference": {
        "name": "acstack-ubuntu-17.10-1523069601",
        "resourceGroup": "ACStackImages"
      },
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "imageReference": {
          "name": "acstack-ubuntu-17.10-1523069601",
          "resourceGroup": "ACStackImages"
        },
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

The resource group for the image the image itself are both owned by my subscription.

cc @kargakis 

**Anything else we need to know**:

**Comment by kargakis** [comment]
First, make sure you are including https://github.com/Azure/acs-engine/commit/49e262a2777af473335b51aca1da72fb11f2aafe in your acs-engine build. Second, the issue you are seeing is because the api version of the VM used is old.

**Comment by seanknox** [comment]
> The api version of the VM used is old.

I don't follow—what does this mean, exactly?

**Comment by kargakis** [comment]
The VM is using an old [schema](https://schema.management.azure.com/schemas/2015-08-01/Microsoft.Compute.json#/resourceDefinitions/virtualMachines) that does not support [id in imageReference which is what the template uses to specify a custom image](https://github.com/Azure/acs-engine/blob/d574b1020d751c102dc075410e8e91909ca1c04d/parts/k8s/kubernetesagentresourcesvmas.t#L186). I think your agent VM is defaulting to an old version because it is using a storage account in its storage profile. Can you retry your deployment by adding `"storageProfile": "ManagedDisks",` in your agentPoolProfile? We should probably add some validation about it.

**Comment by kargakis** [comment]
@seanknox did you validate my suggestion? I have opened https://github.com/Azure/acs-engine/pull/2696 to update the example.
