### ISSUE TITLE
Initial SSH key no longer works after upgrade.

### ISSUE THREAD

**Issue by phillipgibson** [Azure/acs-engine#2632]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.9

**What happened**:
Using acs-engine to upgrade the k8 1.8.9 to 1.9.6 version, the azureuser_rsa SSH key no longer works to access the nodes after the upgrade.

**What you expected to happen**:
I could still utilize the same azureuser_rsa SSH key to access the k8 nodes.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a k8 cluster with acs-engine, then upgrade the clusters minor version using the acs-engine upgrade param.

**Anything else we need to know**:
There doesn't seem to be a acs-engine param to instruct the process to use the same SSH key. The "--private-key-path" param looks to be only associated with CA certs

**Comment by CecileRobertMichon** [comment]
Hi @phillipgibson, when you first deployed your cluster, was the ssh key part of your apimodel?

**Comment by phillipgibson** [comment]
Sorry for the delay :). It was not, I had it autogen.
