### ISSUE TITLE
How to replace a service principal?

### ISSUE THREAD

**Issue by robsonpeixoto** [Azure/acs-engine#2636]
I'd like to invalidate the current Service Principal and create another to use in a running cluster. How to replace this SP?

**Comment by rrudduck** [comment]
Unless it's changed since the last cluster we deployed, you can just update the /etc/kubenetes/azure.json file with the updated credentials.

**Comment by robsonpeixoto** [comment]
But the scale-up will use the older SP, right  @rrudduck ?

**Comment by rrudduck** [comment]
Before you scale the cluster, modify the apimodel.json file that was created as the output from the initial cluster creation. The new nodes will use the updated values.

**Comment by heltondd** [comment]
Does it work for VirtualMachinescaleSet with cluster-auto-scaler?
