### ISSUE TITLE
Deploy using client-id and client-secret command line switches throws an error

### ISSUE THREAD

**Issue by jobanputra** [Azure/acs-engine#2657]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**:  v0.15.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

**What happened**:
We generate service principle on the fly and are not available to put in the api-model json file. I used the following command:
 `acs-engine deploy --subscription-id (redacted)  --resource-group (redacted) --dns-prefix (redacted) --location westus2 --auto-suffix --api-model clusterDefinition.json --client-id (redacted) --client-secret (redacted) --auth-method client_secret`.
However I go the following error message:
`FATA[0000] --client-id and --client-secret must be specified when --auth-method="client_secret"`

**What you expected to happen**:
I expected a new cluster to be created.

**How to reproduce it** (as minimally and precisely as possible):
Replace the redacted values and execute the following command:
 `acs-engine deploy --subscription-id (redacted)  --resource-group (redacted) --dns-prefix (redacted) --location westus2 --auto-suffix --api-model clusterDefinition.json --client-id (redacted) --client-secret (redacted) --auth-method client_secret`

**Anything else we need to know**:
I tried to run the same command but escaped the client-id and client-secret using quotes but I still get the same error.

**Comment by CecileRobertMichon** [comment]
@jobanputra I tried to repro but the same command works for me (without quotes, using version `0.15.1`)... Here is the relevant code: https://github.com/Azure/acs-engine/blob/c7f5a61618e60f6adea94c9283da456ed38c834c/cmd/root.go#L79 

Can you double check that you are passing in valid values for `--client-id` and `--client-secret`?

**Comment by jobanputra** [comment]
You were right. I was using the wrong credentials. However once I get past that I get the following error:
`INFO[0004] Error returned by LoadContainerService: ServicePrincipalProfile must be specified with Orchestrator Kubernetes`

`FATA[0004] error validating deployCmd: Failed to validate the apimodel after populating values: ServicePrincipalProfile must be specified with Orchestrator Kubernetes`

This is my cluster definition JSON file:
`
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes"
      },
      "masterProfile": {
        "count": 1,
        "vmSize": "Standard_D2_v2"
      },
      "agentPoolProfiles": [
        {
          "name": "agentpool1",
          "count": 3,
          "vmSize": "Standard_D2_v2",
          "availabilityProfile": "AvailabilitySet"
        }
      ],
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "(redacted)"
            }
          ]
        }
      }
    }
  }
`

**Comment by CecileRobertMichon** [comment]
@jobanputra this looks like a bug. I added it to the backlog. In the meantime, you can get around the issue by pasting your client id and secret in your apimodel as follows: ``` {
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "(redacted)"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "redacted",
      "secret": "redacted"
    }
  }
}```

**Comment by jobanputra** [comment]
Unfortunately we generate the service principal at runtime and so this work around does not work for us. But thank you for looking at the issue and helping.

**Comment by damaggio** [comment]
@jobanputra while the bug gets solved, you could script everything and use jq to change the values in the json template file with appropriate client id and secret.

In linux you would do, for example:
jq ".properties.servicePrincipalProfile.clientId = \"${servicePrincipalClientId}\"" template.json > tmp.json && mv tmp.json template.json
and the same for servicePrincipalProfile.secret

Let me know if this works for you

**Comment by jobanputra** [comment]
Yes. This is what I ended up doing.
