### ISSUE TITLE
Fail to pull down images on windows node

### ISSUE THREAD

**Issue by mingw2358** [Azure/acs-engine#2659]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: v.0.15.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** 1.10.0

**What happened**: Failed to pull images with error:
rpc error: code = Unknown desc = failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\docker\windowsfilter\4368385d64161943864fe935406b94967bacb3492bf7f9de2584a2251dda2687\UtilityVM\Files\Windows\WinSxS\amd64_microsoft-windows-lsa-minwin_31bf3856ad364e35_10.0.16299.15_none_6057cd900372da49\lsass.exe: Access is denied.
Looks like some other containers are locking the file. If I stop all running containers on the vm, then manually pull down this image, it works. This image is based on microsoft/windowsservercore:1709

**What you expected to happen**: 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by PatrickLang** [comment]
This is fixed in Docker 17.06.2-ee-9. Install & upgrade instructions here:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server#1-install-docker

ACS-Engine will get it automatically the next time the Windows Server image is updated
