### ISSUE TITLE
[k8s] Allow customizing flags for kubelet

### ISSUE THREAD

**Issue by wbuchwalter** [Azure/acs-engine#266]
There are a number of scenarios where someone would want to customize the flags passed to kubelet on the agents (i.e. enabling alpha features).

Any idea on how that could be done?

@colemickens initial input:
>We would need to come to agreement on what this would look like in the apimodel - do we support a number of specific toggles and support checking for invalid combinations? Do we just allow the user to wholesale override all of the attributes passed to the various components, etc?

**Comment by jackfrancis** [comment]
@wbuchwalter I think the most practical step forward is to continue to add configuration of kubelet (and other k8s core components) flags on an as-needed basis. You can see in the current kubelet service definition that we ship to clusters there's a fair amount of ad hoc customization going on:

https://github.com/Azure/acs-engine/blob/master/parts/kuberneteskubelet.service

Generalizing this would be a decent amount of work, and not entirely practical given that the set of kubelet key/vals from one version of kubernetes to the next is subject to change (and would have to be managed appropriately at template generation time to ensure we produce a usable kubelet spec).

I would welcome any improvement to this surface area as a PR, up to and including a tasteful general model! But I'd prefer to keep this out of the backlog as it's not likely something we'd tackle anytime soon in a comprehensive way.
