### ISSUE TITLE
Upgrade results in node with 111 IPs

### ISSUE THREAD

**Issue by EPinci** [Azure/acs-engine#2668]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** ISSUE

---

**What version of acs-engine?**: v15.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** from v1.9.3 to v1.9.6

**What happened**:

I configured the cluster with AzureCNI and ipAddressCount set to 20.
During an upgrade run node get thorn down and rebuilt.
Original node had 20 IPs as expected, new node has 111 IPs resulting in quick subnet exhaustion.

**What you expected to happen**:

Original node having 20 IP, new node having the same number.

**How to reproduce it** (as minimally and precisely as possible):

Deploy a cluster with with AzureCNI and ipAddressCount set to 20.
Mine had 3 masters (with 20 IPs as well) and 3 node (with standard 30 IPs).

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
Running a deployment, then a series of upgrades against this api model:

```
{   "apiVersion": "vlabs",   "properties": {     "orchestratorProfile": {       "orchestratorType": "Kubernetes",       "orchestratorVersion": "1.7.0"     },     "masterProfile": {       "count": 1,       "dnsPrefix": "",       "vmSize": "Standard_D2_v2"     },     "agentPoolProfiles": [       {         "name": "agentpool1",         "count": 2,         "vmSize": "Standard_D2_v2",         "availabilityProfile": "AvailabilitySet",         "storageProfile" : "ManagedDisks"       }     ],     "linuxProfile": {       "adminUsername": "azureuser",       "ssh": {         "publicKeys": [           {             "keyData": ""           }         ]       }     },     "servicePrincipalProfile": {       "clientId": "",       "secret": ""     }   } }```

After initial deployment:

```
$ az network vnet show -n k8s-vnet-24809053 -g kubernetes-ukwest-78035 | grep 'networkInterfaces' | wc -l
      94
```

**Comment by jackfrancis** [comment]
Holding steady after the 1st upgrade (from 1.7.0 to 1.7.12):

```
$ az network vnet show -n k8s-vnet-24809053 -g kubernetes-ukwest-78035 | grep 'networkInterfaces' | wc -l
      94
```

**Comment by EPinci** [comment]
Weird I tried this multiple times and always with the same result (even the IP count!).
In my case had 3 masters and 3 nodes and then manually deleted two nodes VM form the portal.

Can you try just deleting one of the two nodes to see if this has an impact: this is exactly my scenario where the original node count get changed outside ACS-Engine (e.g.: autoscaler)?

Do you want me to send you my api model?

**Comment by jackfrancis** [comment]
Let's let my test keep running (there are 12 more upgrades to go). I'm not saying for sure that we can't repro yet. :)

**Comment by jackfrancis** [comment]
I take it back, I've been unable to repro. Yeah, please paste in the api model you're seeing this behavior on post-upgrade, and we'll repro using it as exactly as possible. Thanks!

**Comment by EPinci** [comment]
@jackfrancis Any chance you can give this a go? What do you think about it?
