### ISSUE TITLE
Restarting Windows Nodes 

### ISSUE THREAD

**Issue by beaudryj** [Azure/acs-engine#2670]
Is this a request for help?:
Yes

Is this an ISSUE or FEATURE REQUEST? (choose one):
ISSUE

What version of acs-engine?:
Latest

Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)
Kubernetes 1.9.3

What happened:
I Shutdown my worker node in the portal to help cut down on daily costs as I am running this for a Dev/test Environment and would like to shutdown workers in evening and start up again in morning. I noticed that when I turn the node back on the Docker Service fails to start, and the node never changes to a ready state in the cluster. Am I doing something incorrectly to shutdown, or is there an issue with the nodes or scripts on the nodes?

**Comment by CecileRobertMichon** [comment]
@JiangtianLi any idea?

**Comment by esheris** [comment]
I had experienced this same issue multiple times while doing the same thing. I did find that if I use the "redeploy" option from the azure portal they come back up. I was running 2 windows nodes on the test cluster and at least 1 would need this done each morning.

**Comment by JiangtianLi** [comment]
@beaudryj Is there any workload running on the node? Can you get docker service log? When reboot, k8s setup will need to clean up containers and hns network. But if docker daemon fails before that, then the log probably will have some clue.

**Comment by beaudryj** [comment]
No, I did not do any of that as the "Serial Connection (Preview)" has been the only way I have been able to get into the nodes. I wasnt even able to spin up a win10 node on the network and WinRM into the node.
