### ISSUE TITLE
Kubernetes on custom VNET

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#268]
I seem to be having the same problem as described by ticket 120, namely, that when deploying a Kubernetes cluster in a custom VNET (where the VNET is in a different Resource Group from the cluster), I see "RouteController failed to create a route" errors and am unable to see a simple nginx pod move from PENDING status.

kubectl describe nodes | grep -i network
 NetworkUnavailable    True    Mon, 13 Feb 2017 22:21:36 +0000         Mon, 13 Feb 2017 22:21:36 +0000         NoRouteCreated                  RouteController failed to create a route
NetworkUnavailable    True    Mon, 13 Feb 2017 22:21:36 +0000         Mon, 13 Feb 2017 22:21:36 +0000         NoRouteCreated                  RouteController failed to create a route
NetworkUnavailable    True    Mon, 13 Feb 2017 22:21:36 +0000         Mon, 13 Feb 2017 22:21:36 +0000         NoRouteCreated                  RouteController failed to create a route
NetworkUnavailable    True    Mon, 13 Feb 2017 22:21:36 +0000         Mon, 13 Feb 2017 22:21:36 +0000         NoRouteCreated                  RouteController failed to create a route

**Comment by colemickens** [comment]
As noted in [that issue](https://github.com/Azure/acs-engine/issues/120#issuecomment-277336309), support for this scenario was recently added. You need to update, rebuild, regenerate and deploy a new cluster.

I'm going to go ahead and close this, but please reopen it if there's an issue after you update, etc.

**Comment by dcieslak19973** [comment]
I redeployed the cluster from scratch today, using ACS Engine that was also pulled from today. The log was sent from that fresh cluster.

I attempted to deploy a K8s cluster after that with the Vnet in the same resource group but ran into a deployment failure. I'll redo both processes tomorrow and reopen another ticket if the problem recurs.

Sent from my iPhone

On Feb 13, 2017, at 4:57 PM, Cole Mickens <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #268<https://github.com/Azure/acs-engine/issues/268>.

**Comment by colemickens** [comment]
Okay. Note that deploying into a vnet in a different resource group is explicitly NOT supported. If you need that, please file a tracking issue for it (though we will probably not get to it very soon, as it requires work in upstream Kubernetes as well).

**Comment by karthik-ir** [comment]
I'm facing the same issue. What is the work around this ?

**Comment by rrajadevops** [comment]
@colemickens @dcieslak19973 I created the custom acs cluster today. I am looking for how to connect my cluster using kubectl, could you please share the steps how to connect my k8s cluster using kubectl.
Regards,
Raja
