### ISSUE TITLE
openshift: consider prebaking relevant docker images into golden images

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2681]
Or use the azure container registry

Moved from https://github.com/kargakis/acs-engine/issues/29

@jim-minter @kwoodson

**Comment by kwoodson** [comment]
@jim-minter @pweil-,

Do we know where we stand on this issue?  Are we still planning on this?

**Comment by pweil-** [comment]
> Do we know where we stand on this issue? Are we still planning on this?

Not in the plans right now.  Can be a low priority card if we want to clean up the number of issues here.

**Comment by jim-minter** [comment]
trello'd
