### ISSUE TITLE
openshift: start to implement unit tests against certgen

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2682]
Moved from https://github.com/kargakis/acs-engine/issues/31

@jim-minter

**Comment by jim-minter** [comment]
@kwoodson - worth taking a look at?

**Comment by kwoodson** [comment]
I think this might cover this issue:
https://github.com/Azure/acs-engine/pull/2780

Specifically:
https://github.com/Azure/acs-engine/pull/2780/files#diff-4c66ee984882825b6bd7db3c729a37f7

**Comment by kwoodson** [comment]
@kargakis @jim-minter,   The tests mentioned in #2780 were specifically around permissions and ownership.   If we could come up with a list of specific tests for the certgen pkg that might help.

**Comment by jim-minter** [comment]
this probably goes away with HCP and the testing should become clearer
