### ISSUE TITLE
openshift: verify tar file ownerships and permissions and add test coverage

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2683]
Moved from https://github.com/kargakis/acs-engine/issues/35

@jim-minter

**Comment by jim-minter** [comment]
@kwoodson - worth taking a look at?

**Comment by jim-minter** [comment]
aim is to remove https://github.com/jim-minter/acs-engine/blob/4330d210ec31f2a29812d04c223cf168413f73f0/parts/k8s/openshiftmasterscript.sh#L38-L40

**Comment by jim-minter** [comment]
also confirm all key permissions are not group/world read/writable
