### ISSUE TITLE
openshift: revisit clusterUsername and clusterPassword in openshiftConfig

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2687]
Moved from https://github.com/kargakis/acs-engine/issues/75

@jim-minter

**Comment by kwoodson** [comment]
@kargakis @jim-minter,

Original Issue:
> Either, these should go away when AAD integration is enabled, or username(s)/password(s) should be specifiable and laid down using an API we're prepared to stand behind.

The original card mentioned that AAD integration would satisfy the intentions of this card.  Can we close this now that Jim's work has completed?

**Comment by jim-minter** [comment]
ok, trello'd
