### ISSUE TITLE
openshift: review OpenShift Orchestrator for validation requirements

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2688]
Moved from https://github.com/kargakis/acs-engine/issues/76

@pweil- @jim-minter

**Comment by kargakis** [comment]
managed disks validation: https://github.com/Azure/acs-engine/pull/2737

**Comment by kwoodson** [comment]
vnet validation: #3268

**Comment by kwoodson** [comment]
@kargakis @jim-minter, are these sufficient or are we looking at adding more validations?  If we could be specific then we can come up with requirements.

**Comment by jim-minter** [comment]
happy to close
