### ISSUE TITLE
documentation for the openshift orchestrator

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2692]
@jackfrancis can be assigned to me

**Comment by dcieslak19973** [comment]
Is the idea here to add "OpenShift" as another Orchestrator Type like DCOS, Kubernetes, and Swarm?

**Comment by jackfrancis** [comment]
@dcieslak19973 Red Hat is currently in the process of implementing OpenShift on Azure via acs-engine, yes.
