### ISSUE TITLE
openshift: PR gating

### ISSUE THREAD

**Issue by jim-minter** [Azure/acs-engine#2700]
I'd like to try to guarantee that openshift-related PRs to acs-engine are reviewed and signed off by an openshift team owner in addition to whatever other review/sign-off requirements acs-engine may have.  In the case that one openshift team owner submits a PR, a separate one should review and sign off.

Because of the structure of acs-engine it's difficult to neatly define "openshift-related".  Perhaps "touches code under /pkg/openshift or PR submitted by a RHer" is an adequate starting proxy?

Suggest "openshift team owner" to include pweil-, kargakis, jim-minter.

It would be handy for openshift team owners to be able to easily see the queue of PRs that need their review, e.g. via the GH reviewer or assignee mechanisms.

**Comment by jim-minter** [comment]
@jackfrancis @CecileRobertMichon @pweil- @kargakis thoughts on the above rough idea?

**Comment by pweil-** [comment]
+1, a team to tag into PRs would be nice in addition to using the assignment mechanism just for making sure the OpenShift folks who aren't specifically assigned are aware of changes.

**Comment by CecileRobertMichon** [comment]
+1. You should also use the orchestrator/openshift label on openshift PRs + issues to identify them in the queue (in addition to tagging the relevant people/team).

**Comment by jim-minter** [comment]
> "touches code under /pkg/openshift..."

And parts/openshift if/when we break out the master.sh & node.sh there

**Comment by jim-minter** [comment]
@CecileRobertMichon I don't have the ability to add labels to existing PRs.

**Comment by kargakis** [comment]
Btw github already supports a form of our OWNERS file process, albeit it's slightly different in that the CODEOWNERS file needs to exist in certain places inside a repo and it's only used for requesting reviews and not for gating PR merges.

https://help.github.com/articles/about-codeowners/

**Comment by jim-minter** [comment]
cf https://github.com/Azure/acs-engine/issues/2690

**Comment by kargakis** [comment]
OWNERS files are in place: https://github.com/Azure/acs-engine/pull/2791

Prow CI setup in https://github.com/Azure/acs-engine/pull/2923

**Comment by kargakis** [comment]
Done :tada: 

/assign
/close
