### ISSUE TITLE
3 master cluster with internal load balancer timeout issues

### ISSUE THREAD

**Issue by rakidu** [Azure/acs-engine#2715]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
ACS-Engine 15.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.5

**What happened**:
we deployed kubernetes 3 master private cluster. The deployment is successful.
The challenge is the kubectl commands are not working as expected.
We are getting Timeout errors with internal load balancer IP  that sits between the master & node.
This Issue is intermittent. The commands works for a while and then throws timeout error.
This issue is same from all 3 masters.
The cluster definition is shared below for reference 

**What you expected to happen**:
The kubectl commands should work without any timeout errors

**How to reproduce it** (as minimally and precisely as possible):
Cluster definition file is shared below
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.9.5",
          "kubernetesConfig": {
        "networkPolicy": "azure",
        "privateCluster": {
         "enabled": true
        },
        "maxPods": 30
      }
       },
    "masterProfile": {
      "count": 3,
      "ipAddressCount": 15,
      "dnsPrefix": "xxxxxx",
      "vmSize": "Standard_DS3_v2",
      "vnetSubnetId": "/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Network/virtualNetworks/xxxxxx/subnets/xxxxxxx",
      "firstConsecutiveStaticIP": "xxxxxxxxxxx",
      "vnetCidr" : "xxxxxxxxxx",
      "storageProfile" : "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "node",
        "count": 3,
        "vmSize": "Standard_DS4_v2",
        "vnetSubnetId": "/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Network/virtualNetworks/xxxxxx/subnets/xxxxxxx",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile" : "ManagedDisks"
      }

    ],
    "linuxProfile": {
      "adminUsername": "scelocaladmin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "xxxxxxxxxxxxxxxxxxxxxxxx"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "xxxxxxxxxxxxxxxxxxxxxxxx",
      "secret": "xxxxxxxxxxxxxxxxxxxxxxxx"
    }
  }
}

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Hi @rakidu, please see https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#private-cluster.

This is expected behavior if you are running `kubectl` commands while ssh'd on the master. It is recommended to `export KUBECONFIG=_output/YOUR_CLUSTER_NAME/kubeconfig/kubeconfig.YOUR_REGION.json` and run `kubectl` commands locally (ie. from a jumpbox in the same VNET or directly on your machine if you are connected via VPN).
