### ISSUE TITLE
[Kubernetes] - Support for custom VNET outside the resource group

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#272]
Would like to reference a VNET in a different resource group from the one ACS-Engine creates.

**Comment by Camsteack** [comment]
Hi,

Just wanted to +1 that request as this is a must for us. We don't want to tied up the cluster definition the the networking configuration as it is setup on the side and needs to have VPN connection and configuration to on-prem.
Thanks a lot.

Cheers

**Comment by anhowe** [comment]
@colemickens is there an upstream reference for cloud provider to be able to have a VNET live in a different resource group

**Comment by anhowe** [comment]
Currently the workaround for this is to have a peered VNET.  See #425 as a reference

**Comment by Camsteack** [comment]
Hi @anhowe I thought that issue was supposed to be fixed with k8s 1.6 as @colemickens said in #538 ?

**Comment by itaysk** [comment]
Just created a cluster in a legacy VNET in a separate RG. We should close this issue to reflect that for the sake of future visitors

**Comment by JackQuincy** [comment]
Sounds good I will close it.

**Comment by dcieslak19973** [comment]
Super excited to see this working. Thanks all!
