### ISSUE TITLE
enableEncryptionWithExternalKms feature doesn't work with keyvaultSecretRef

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#2722]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: master (5509886618191015a477503f862e1cffec62b881)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

Deployment validation breaks if you have a cluster definition with enableEncryptionWithExternalKms and keyvaultSecretRef for the SP secret

```
INFO[0032] Finished ARM Deployment (levo-cluster-5ad820e4-59470587). Error: resources.DeploymentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The value for the template parameter 'servicePrincipalObjectId' at line '1' and column '22551' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'."
ERRO[0032] {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The value for the template parameter 'servicePrincipalObjectId' at line '1' and column '22551' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'."}}
FATA[0032] resources.DeploymentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The value for the template parameter 'servicePrincipalObjectId' at line '1' and column '22551' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'."
```

**What you expected to happen**:

Deploy using SP secret from keyvault

**How to reproduce it** (as minimally and precisely as possible): Add the following to servicePrincipalProfile

```
      "keyvaultSecretRef": {
        "vaultID": "",
        "secretName": "",
        "version": ""
      }
```

**Anything else we need to know**:

PR Feature - https://github.com/Azure/acs-engine/pull/2544

**Comment by lachie83** [comment]
I believe the issue is here - https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/engine.go#L704

**Comment by lachie83** [comment]
cc @ritazh

**Comment by ritazh** [comment]
@lachie83 To use the `enableEncryptionWithExternalKms` feature, you need to add the following to your apimodel, as shown here: https://github.com/Azure/acs-engine/blob/master/examples/kubernetes-config/kubernetes-data-encryption-at-rest-with-external-kms.json

```
"kubernetesConfig": {
        "enableEncryptionWithExternalKms": true
      }
```
and 
```
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": "",
      "objectId": ""
    }
```
`objectId` is the objectId of the service principal used to create the key vault in the same resource group as the cluster.

You can get it by using `az ad sp list --spn <YOUR SERVICE PRINCIPAL appId>`

Sorry the doc should be better. I will update this in a separate PR.

**Comment by ritazh** [comment]
>  "keyvaultSecretRef": {
        "vaultID": "",
        "secretName": "",
        "version": ""
      }

I think this snippet you referenced earlier is used if we want to tell acs-engine to retrieve the k8s deployment `servicePrincipalProfile` `secret` parameter from Azure KeyVault instead of providing the secret directly.

**Comment by lachie83** [comment]
Spoke with Rita and clarified the issue. This needs to be reoponed and a code fix made
