### ISSUE TITLE
[Kubernetes] - Custom VNet Deployment Fails

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#273]
Steps to re-create:

1. Create new resource group
2. Deploy KubernetesCustomVNET using 10.1.58.0/24 as the address space and the subnet KubernetesSubnet with an address prefix of 10.1.58.0/24
3. Change the firstConsecutitveStaticIP in kubernetesvnet.json to 10.1.58.10
3.a. I also changed the template to remove the "agentpri2" agentPoolProfile and bumped the count of "agentpri" to 4
3.b. Modify the vnetSubnetId for the appropriate Subscription and resource group values
4. Run acs-engine against the modified kubernetesvnet.json
5. Deploy the generated template

Wait until the "k8-master-internal-lb" object fails when it comes in conflict with one of the NICs for one of the VMs.

**Comment by colemickens** [comment]
Have you run `make` since updating `acs-engine`?

Can you SSH to the master VM and then paste the contents of `/etc/kubernetes/azure.json` with the `client_secret` field redacted so I can look at it?

**Comment by dcieslak19973** [comment]
From: https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md

1. cd $GOPATH
2. rm -rf src/github.com
3. go get github.com/Azure/acs-engine
4. go get all
5. cd $GOPATH/src/github.com/Azure/acs-engine
6. go build
7. vi examples/vnet/vnetarmtemplate/azuredeploy.kubernetes.json
7.a Swap in the CIDR 10.1.58.0/24 as appropriate
8. az resource group create --name="RG-NAME-OMITTED" --location="East US 2"
8.a. (Had already logged in)
9. az resource group deployment create --name=acs-vnet-deployment -g RG-NAME-OMITTED --template-file examples/vnet/vnetarmtemplate/azuredeploy.kubernetes.json
9.a. Azure Portal shows this deployment as successful, and I see the KubernetesCustomVNET object
10. vi examples/vnet/kubernetes.json
10.a. Remove agentpri2 node, change vnetSubnetId as appropriate, change firstConsecutiveStaticIP to 10.1.58.10, add SSH key, set count to 4 for agentpri
11. ./acs-engine examples/vnet/kubernetesvnet.json
12. cd _output/Kubernetes-[NUMBERHERE]
13. az resource group deployment create --name=acs-k8s-deployment -g RG-NAME-OMITTED --template-file ./azuredeploy.json --parameters @./azuredeploy.parameters.json

Looks like no conflicts this time.

As I drop and re-create this environment, I'll submit the contents of /etc/kubernetes/azure.json the next time it fails. Until then, close this ticket, I suppose

**Comment by colemickens** [comment]
Thank you for the high level of detail. Please feel free to reopen or file a new issue if you run into troubles. Best of luck.

**Comment by dcieslak19973** [comment]
Interestingly, the IP Addresses allocated:

Master went to 10.1.58.10
Agents filled 10.1.58.4-7
Internal LB went to 10.1.58.20

I don't know how IP addresses are allocated from SubNets, but there seems to be some danger in them overlapping. Suppose I had changed the count of agentpri instances to 10....

**Comment by colemickens** [comment]
cc: @raveeram ^ ?

**Comment by raveeram** [comment]
@dcieslak19973 Master IP is the FirstConsecutiveStaticIP you pass in through the API model (In the master profile). The InternalLB IP is at a default offset of 10 from the Master IP (we now support 3 and 5 master scenarios as well). I reckon you can prevent overlap by passing in the requisite starting IP for the masters.

**Comment by colemickens** [comment]
Why does it work that way? Don't the master normally get allocated from `10.240.255.x` ?

**Comment by colemickens** [comment]
cc: @anhowe  is this just an artifact of how existing vnet work? the ip allocation happens slightly differently?

**Comment by colemickens** [comment]
@dcieslak19973 So, `firstConsecutiveIP` is the first master's static private ip. The node ips are allocated from the subnet via DHCP.

That having been said, you shouldn't actually have any problems. You could deploy 10 nodes and it would just keep taking IP allocations, skipping the addresses already taken by the master(s).

Anyway, closing this again, as it's all expected and should be working.
