### ISSUE TITLE
Unable to RDP-SSH to windows machine ina hybrid kubernetes cluster

### ISSUE THREAD

**Issue by srinathnarayanan** [Azure/acs-engine#2730]
I have spun up an hybrid Kubernetes cluster with 2 windows VMs and 2 Linux VMs, with a Master Node running on Linux. I am trying to RDP SSH into the windows machines using putty and followed this walkthrough: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/windows.md#walkthrough

My Putty configurations:
Session:
   - HostName : Username@publicIP
   - Port : 22

Connection -> SSH -> Auth : 
   - Allow agent forwarding: true
   - private key for auth : Path_to_private_key

Connection -> SSH -> Tunnels :
   - Source port : 3390
   - Destination : The ip of my private machine (10.240.0.35:3389)

When I hit open, I connect to the master node. I'm unsure whether this is expected and/or what to do next to RDP into the windows machine.
Would Appreciate any help. I am trying to pull some logs from the machine.
Thanks!

**Comment by CecileRobertMichon** [comment]
@JiangtianLi can you please help @srinathnarayanan to ssh into his windows agent? I tried to help but not sure what is wrong with his config

**Comment by JiangtianLi** [comment]
@srinathnarayanan Once you have the ssh connection, next step is to RDP to localhost:3390 in your case.

**Comment by srinathnarayanan** [comment]
Hi @JiangtianLi I'm not sure how to RDP from a linux machine to the windows machine. Should I use XRDP?

**Comment by JiangtianLi** [comment]
@srinathnarayanan Are you using PUTTY on Linux?

**Comment by srinathnarayanan** [comment]
I installed PUTTY on linux, but am getting a "Gtk-Warning : cannot open display" error

**Comment by srinathnarayanan** [comment]
I enabled X11 forwarding and got putty to work on the linux master node, but am unable to connect to the windows agent. What should the new putty configs be?

**Comment by srinathnarayanan** [comment]
@JiangtianLi My local machine is windows, and I am using Putty on it

**Comment by JiangtianLi** [comment]
@srinathnarayanan To clarify, I was not referring to the master node in k8s cluster. I was referring to the client machine where you run PUTTY and ssh to master node. Is your client machine Linux or Windows?

**Comment by JiangtianLi** [comment]
@srinathnarayanan Then you use RDP on your local machine with localhost:3390

**Comment by srinathnarayanan** [comment]
Got it. Was able to login now. Thanks for your help! I will close this issue now.
