### ISSUE TITLE
Ensure failues in openshiftmasterscript are propagated back from acs-engine

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2748]
I just had a failed deployment 
```
+ docker run --rm -u 0 -v /etc/origin:/etc/origin:z -v /tmp/ansible:/opt/app-root/src:z -v /root/.kube:/opt/app-root/src/.kube:z -w /opt/app-root/src -e IMAGE_BASE=registry.reg-aws.openshift.com:443/openshift3/ose -e VERSION=3.9.11 -e HOSTNAME=ocp-master-21392639-0 --network=host registry.reg-aws.openshift.com:443/openshift3/ose-ansible:v3.9.11 /opt/app-root/src/ansible.sh
Unable to find image 'registry.reg-aws.openshift.com:443/openshift3/ose-ansible:v3.9.11' locally
Trying to pull repository registry.reg-aws.openshift.com:443/openshift3/ose-ansible ... 
/usr/bin/docker-current: Get https://registry.reg-aws.openshift.com:443/v2/openshift3/ose-ansible/manifests/v3.9.11: unauthorized: authentication required.
See '/usr/bin/docker-current run --help'.
+ exit 0
```
We need to ensure these kinds of failures are returned from acs-engine back to the user.

@jim-minter

**Comment by kargakis** [comment]
No, it's not. This specfic failure is not intermittent though, do we want to track it here?

**Comment by kwoodson** [comment]
As discussed in our standup today, I believe we can use the image from docker hub.  The code in the image is exactly the same since we are after the ansible roles.

https://hub.docker.com/r/openshift/origin-ansible/

Thoughts?

**Comment by kargakis** [comment]
@kwoodson makes sense to me after discussing more in IRC

**Comment by jim-minter** [comment]
@kargakis I believe this can be closed now we're on the new subscription and that #2759 is merged?
