### ISSUE TITLE
Default Service Account missing

### ISSUE THREAD

**Issue by rinormaloku** [Azure/acs-engine#2749]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
 v0.15.2

api model:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.8.4",
      "kubernetesConfig": {
        "enableRbac": true
      }
    },
    "aadProfile": {
      "serverAppID": "[removed]",
      "clientAppID": "[removed]",
      "tenantID": "[removed]"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "[dns-prefix]",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "[removed]"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "[removed]",
      "secret": "[removed]"
    }
  }
}
```

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.4

**What happened**:
Creating a new pod causes the following exception:

Error from server (Forbidden): error when creating "pod.yaml": pods "pod-name" is forbidden: service account default/default was not found, retry after the service account is created
Conclusion: **Default service account is missing.**

**What you expected to happen**:
Default account to be present.

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster with AAD profile and try to create a pod.

**Comment by rinormaloku** [comment]
Update: 
This issue is not present in Kubernetes version 1.8.11

**Comment by rguthriemsft** [comment]
Seems like this is still occuring on a 1.9.7 cluster deployed through ACS engine.  I see this in the logs for add-on manager.  I only see two pods running in kube-system.  Add on manager and api.  What other information would be helpful?

@dtzar  

Error from server (NotFound): serviceaccounts "default" not found
WRN: == Error getting default service account, retry in 0.5 second ==

**Comment by oriyastyle** [comment]
Also getting the same error with a 1.9.7 cluster - only the add-on manager and the API server pods are running in kube-system namespace.

**Comment by feiskyer** [comment]
Seems there's something wrong with master setup, especially for kube-controller-manager. Could you check whether there's error message in its logs?
