### ISSUE TITLE
openshift: IsOpenShift and IsKubernetes

### ISSUE THREAD

**Issue by jim-minter** [Azure/acs-engine#2750]
Under parts/k8s we appear to be using IsOpenShift and !IsKubernetes (and vice-versa) interchangeably.  Surely that doesn't make sense?  Can we decide on one and use it?  My leaning is that OpenShift customisations/modifications of parts/k8s should be flagged by IsOpenShift rather than !IsKubernetes?

**Comment by kargakis** [comment]
Agreed, let's stick with IsOpenShift
