### ISSUE TITLE
journald options

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#2757]
Currently we statically define journald config:

```
    echo "Storage=persistent" >> /etc/systemd/journald.conf
    echo "SystemMaxUse=1G" >> /etc/systemd/journald.conf
    echo "RuntimeMaxUse=1G" >> /etc/systemd/journald.conf
    echo "ForwardToSyslog=no" >> /etc/systemd/journald.conf
```

Let's expose a configuration interface for these (and future) settings.

**Comment by ewok2030** [comment]
I'd be willing to give this a shot, but I don't know where to get started. 

I can see the need to parameterized the journald configuration in  `parts/k8s/kubernetescustomscript.sh`, but am unsure of:

* Where is the right place to define the config items in `apimoel.json`?
* What kind of config validation is required and where is that done?
* How to get those configuration items into environment variables that can be referenced from?
