### ISSUE TITLE
Support --set flag for deploy command

### ISSUE THREAD

**Issue by jcorioland** [Azure/acs-engine#2796]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature Request

As describe in issue #733 it would be nice to support the --set flag for the deploy command as well, to be able to override api model json values directly in the CLI:

acs-engine deploy --set \
"masterProfile.count=3,\
agentPoolProfile.count=4,\
windowsProfile.adminPassword=${SOME_ENV_VAR_FETCHED_FROM_VAULT}" \
-g groupname -s subscription examples/kubernetes.json

Right now, generate and deploy command use some duplicated code. Working on this issue is also a good opportunity to mutualize apimodel.json file manipulations.

**Comment by kichristensen** [comment]
Should this be closed after #2787 was merged?

**Comment by jcorioland** [comment]
@kichristensen no, the set flag is just available for the generate command right now, I need to refactor some code to make it available to the deploy command, so I opened this issue to track this work.
