### ISSUE TITLE
[k8s] Managed Disk example

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#280]
DC/OS and Docker both have examples of managed disks; if k8s can utilize Managed Disks, an example to build a cluster would be nice.

**Comment by colemickens** [comment]
Kubernetes does not yet support Managed Disks.

There is work in progress to support Managed Disks in Kubernetes.... and there is already a PR adding support for Managed Disks in ACS-Engine. I think for K8s 1.6, Managed Disks should be fully usable, at least with ACS-Engine + K8s.

[Kubernetes managed disks support with examples #144](https://github.com/Azure/acs-engine/pull/144)

cc: @khenidak for more info potentially

**Comment by JackQuincy** [comment]
PR has merged
