### ISSUE TITLE
de-dupe examples and testdata

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#281]
Seems like the clusterdefinitions in testdata are extra. Might be nice to just have testdata contain expected output of our example clusterdefinitions.

**Comment by anhowe** [comment]
For this, I recommend dividing up tests into 2 buckets:
1. expected for the examples (and delete the duplicate tests under the tests folder).  You will have to adjust the test code to inject pre-assigned values for dns and secrets.
2. tests useful for catching regressions, but not useful for customer examples.  These can stay the same as they are today.

**Comment by colemickens** [comment]
Why wouldn't these be the same things? The testdata we have now is already virtually same as the examples.

**Comment by anhowe** [comment]
Examples should be crisp and clean and help the customers achieve success.  There are some tests that don't lend them to this, such as v20160930 tests.  Whoever proceeds to do this, divide into the buckets as recommended above, and we can see what is left over.

**Comment by anhowe** [comment]
With removal of expected, this feels like less overhead now.  The examples are missing values that the customer needs to set, that we don't want to have to set in test.  These do still seem like two distinct functions, so closing.
