### ISSUE TITLE
acs-engine upgrade fails - Error upgrading Cluster Code="DeploymentFailed"  Azure error: Write AvailabilitySets Failed

### ISSUE THREAD

**Issue by dd-cedric** [Azure/acs-engine#2815]
**Is this a request for help?**: Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**:
Version: v0.15.2
GitCommit: 2e2fd9a7
GitTreeState: clean

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.6.9

**What happened**:
While running an acs-engine kubernetes upgrade from 1.6.9 to 1.7.16 the upgrade process quits with the following error:

INFO[0042] Finished ARM Deployment (master-18-04-30T20.35.12-371451020). Error: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."

INFO[0042] Error creating upgraded master VM with index: 0

FATA[0042] Error upgrading cluster: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."

Looking at the Activity Log of the master-availabilityset of the master-node on Azure the following error is visible:
Operation name
Write AvailabilitySets
Time stamp
Mon Apr 30 2018 22:35:20 GMT+0200 (W. Europe Daylight Time)
Event initiated by
AzureContainerService_Kubernetes_Prod
Error code
PropertyChangeNotAllowed
Message
Changing property 'platformUpdateDomainCount' is not allowed.

**What you expected to happen**:
In November/December last year we did the same upgrade of our ACC environment from Kubernetes 1.6.9 to 1.8.3 without any issues. So this error message is new to us and we have no clue on how to fix this.

**How to reproduce it** (as minimally and precisely as possible):
We can easily reproduce the error in our environment / Azure Setup. 
Not sure how this effects others yet.

**Anything else we need to know**:
We are running a 3-node cluster with 1 master.

**Comment by CecileRobertMichon** [comment]
@dd-cedric what version of acs-engine was this cluster deployed with? Could you please share your cluster config (apimodel.json) please? Make sure you remove all secrets before sharing.

**Comment by dd-cedric** [comment]
Hi!

I think it was version 0.7.0 or 0.8.0 of acs-engine.

[apimodel.txt](https://github.com/Azure/acs-engine/files/1962544/apimodel.txt)
