### ISSUE TITLE
error validating generateCmd: specified api model does not exist

### ISSUE THREAD

**Issue by gaurav218** [Azure/acs-engine#2823]
Can anyone help with following issue while creating k8 acs cluster using acs engine

module.k8s_cluster.null_resource.deploy_acs: Error running command 'acs-engine generate k8s-rendered.json': exit status 1. Output: time="2018-05-01T18:28:54+05:30" level=fatal msg="error validating generateCmd: specified api model does not exist (k8s-rendered.json)"

I debugged and analyzed that error is thrown from validate method from below go file
https://github.com/Azure/acs-engine/blob/master/cmd/generate.go

any help will be greatly appreciated since I am stuck on this issue since yesterday

**Comment by CecileRobertMichon** [comment]
Hi @gaurav218, are you running `acs-engine generate --api-model <PATH_TO_YOUR_APIMODEL>` ?

**Comment by gaurav218** [comment]
I am executing it with Terraform with following main.tf file and k8s.json. It fails at line 
    command = "acs-engine generate k8s-rendered.json"
Any help will be appreciated. 
main.tf
# ACS Engine Config
data "template_file" "acs_engine_config" {
  template = "${file(var.acs_engine_config_file)}"

  vars {
    // general settings
    k8s_version                     = "${var.k8s_version}"
    dns_prefix                      = "${var.dns_prefix}"
    vm_admin_username               = "${var.vm_admin_username}"
    vm_admin_ssh_key                = "${var.vm_admin_ssh_key}"
    // master config
    master_vm_count                 = "${var.master_vm_count}"
    master_vm_size                  = "${var.master_vm_size}"
    master_subnet_id                = "${var.master_subnet_id}"
    master_subnet_cidr              = "${var.master_subnet_cidr}"
    first_master_ip                 = "${var.first_master_ip}"
    // agent config
    agent_vm_count                  = "${var.agent_vm_count}"
    agent_vm_size                   = "${var.agent_vm_size}"
    agent_subnet_id                 = "${var.agent_subnet_id}"
    // azure access
    service_principal_client_id     = "${var.azure_client_id}"
    service_principal_client_secret = "${var.azure_client_secret}"
  }
}

# Locally, run the Azure 2.0 CLI to create the resource deployment
resource "null_resource" "deploy_acs" {
  # generate acs config from template file
  provisioner "local-exec" {
    command = "echo '${data.template_file.acs_engine_config.rendered}' > k8s-rendered.json"
  }

  depends_on = ["data.template_file.acs_engine_config"]

  # run acs-engine to generate ARM template from input configuration
  provisioner "local-exec" {
    command = "acs-engine generate k8s-rendered.json"
  }

  # perform az login
  provisioner "local-exec" {
    command = "az login --service-principal -u \"${var.azure_client_id}\" -p \"${var.azure_client_secret}\" --tenant \"${var.azure_tenant_id}\""
  }

  # make sure to select the correct subscription
  provisioner "local-exec" {
    command = "az account set --subscription \"${var.azure_subscription_id}\""
  }

  # create k8s deployment in resource group
  provisioner "local-exec" {
    command = "az group deployment create --name ${var.env_config["env"]}_${var.env_config["mmc_region"]}_${var.env_config["region_short"]}_${var.cluster_name} --resource-group ${var.resource_group_name} --template-file ./$(find _output -name 'azuredeploy.json') --parameters @./$(find _output -name 'azuredeploy.parameters.json')"
  }

  # store kubeconfig into Azure Key Vault
  # This is not done via the keyvault resource provider, since this only works during initial deployment (getting the kubeconfig file content via a local_file data source),
  # but fails on each update when the local file is validated and does not exist.
  provisioner "local-exec" {
    command = "az keyvault secret set --vault-name ${var.azure_keyvault_name} --name ${var.env_config["env"]}-${var.env_config["mmc_region"]}-${var.env_config["region_short"]}-${replace(var.cluster_name, "_", "-")}-kubeconfig --value \"`cat _output/${var.dns_prefix}/kubeconfig/kubeconfig.${var.env_config["region"]}.json`\""
  }

  # following provisioners are for destroy time handling

  # Login to az cli to delete the deployment.
  provisioner "local-exec" {
    when    = "destroy"
    command = "az login --service-principal -u \"${var.azure_client_id}\" -p \"${var.azure_client_secret}\" --tenant \"${var.azure_tenant_id}\""
  }

  # make sure to select the correct subscription
  provisioner "local-exec" {
    when    = "destroy"
    command = "az account set --subscription \"${var.azure_subscription_id}\""
  }

  # Since we used an ARM template based ACS deployment, we have to delete it using the CLI during terraform destroy.
  provisioner "local-exec" {
    when    = "destroy"
    command = "az group deployment delete --name ${var.env_config["env"]}_${var.env_config["mmc_region"]}_${var.env_config["region_short"]}_${var.cluster_name} --resource-group ${var.resource_group_name}"
  }

  # delete kubeconfig secret
  provisioner "local-exec" {
    when    = "destroy"
    command = "az keyvault secret delete --vault-name ${var.azure_keyvault_name} --name ${var.env_config["env"]}-${var.env_config["mmc_region"]}-${var.env_config["region_short"]}-${replace(var.cluster_name, "_", "-")}-kubeconfig || true"
  }
}

k8s.json file

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "${k8s_version}"
    },
    "masterProfile": {
      "count": ${master_vm_count},
      "dnsPrefix": "${dns_prefix}",
      "vmSize": "${master_vm_size}",
      "vnetSubnetId": "${master_subnet_id}",
      "firstConsecutiveStaticIP": "${first_master_ip}"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": ${agent_vm_count},
        "vmSize": "${agent_vm_size}",
        "vnetSubnetId": "${agent_subnet_id}",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "${vm_admin_username}",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "${vm_admin_ssh_key}"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientID": "${service_principal_client_id}",
      "secret": "${service_principal_client_secret}"
    }
  }
}

**Comment by CecileRobertMichon** [comment]
Did you check that ` k8s-rendered.json` exists? Looks like it's not being created properly and acs-engine can't find the file...

**Comment by gaurav218** [comment]
Yes it is not generated, it fails at line 
acs-engine generate k8s-rendered.json

**Comment by CecileRobertMichon** [comment]
@gaurav218 the generate command takes an existing apimodel json (your cluster config) and outputs an ARM template. The json that you pass in, in this case `k8s-rendered.json` should exist prior to running the `generate` command.

**Comment by gaurav218** [comment]
Now i added blank file at folder location where k8s.json is present and it gives below error
![image](https://user-images.githubusercontent.com/26568744/39485766-6c9022ee-4d97-11e8-99d1-21f48c4b455e.png)

should i fill this json with start and end tags ?

**Comment by gaurav218** [comment]
below command is executed and outputs as shown in screenshot
provisioner "local-exec" {
    command = "echo '${data.template_file.acs_engine_config.rendered}' > k8s-rendered.json"
  }
  depends_on = ["data.template_file.acs_engine_config"]

![image](https://user-images.githubusercontent.com/26568744/39487342-815adf2a-4d9c-11e8-854a-27b581337d2e.png)

fails with same error

**Comment by CecileRobertMichon** [comment]
@gaurav218 please check that `k8s-rendered.json` exists and contains your apimodel definition after running `command = "echo '${data.template_file.acs_engine_config.rendered}' > k8s-rendered.json"`, before running `acs-engine generate`. My guess is that ` k8s-rendered.json` isn't created properly.

**Comment by gaurav218** [comment]
thanks, i did a workaround and save k8s-rendered.json file. this step worked fine but failed at later step with following error
![image](https://user-images.githubusercontent.com/26568744/39507682-b4943368-4dfc-11e8-9342-e580f578a8c1.png)

step where it failed
resource "null_resource" "deploy_acs" {
  provisioner "local-exec" {
    command = "az group deployment create --name ${var.cluster_name} --resource-group ${var.resource_group_name} --template-file ./$(find _output -name 'azuredeploy.json') --parameters @./$(find _output -name 'azuredeploy.parameters.json')"
   }

   depends_on = ["null_resource.run_acs_engine"]
  }

pl. suggest how to proceed.
