### ISSUE TITLE
Pods not get assigned evenly

### ISSUE THREAD

**Issue by sunnydoll** [Azure/acs-engine#2827]
**Is this a request for help?**:
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
Version: v0.12.3
GitCommit: 030e5dcc

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.9

**What happened**:
We are using ACS Engine to host one of our services. We had the issue that on 3/30/18 from 12:00am to 2:00pm we experienced the CPU usage, load, and memory usage centralizing on one node instead of being evenly distributed across our 3 nodes.
 
At 12:00am the CPU usage of one of nodes started increasing while the other two started decreasing towards 0%.
At 12:30am logs show there was a large uptick in nginx-ingress errors like "(Connection refused) while connecting to upstream client" and "upstream prematurely closed connection while reading response header from upstream" errors when sending requests to API endpoints
At 9:00am the CPU usage of the busy node was at 80% while the other two were at or close to 0%.
From 1:00pm - 1:30pm the busy node peaked at over 92% CPU usage. Load average and memory peaked as well.
 
We noticed in Kubernetes that most of the pods were localized in that busy node. We were not able to identify the root cause of this issue since VMs do not have any events that would indicate why the issue happened (such as a restart) and we were not able to track anything down in K8S either. Finally we fixed this issue by manually restarting VMs through the Azure portal.

**What you expected to happen**:
Same issue happened again on 4/27/2018. We think this issue will happen sometime in the future.

**How to reproduce it** (as minimally and precisely as possible):
We are not able to reproduce it.

**Comment by rite2nikhil** [comment]
We need to understand what is taking high cpu 
Also Please share the following info on the busy node 
1> Is docker responsive - docker ps 
2> see there are zombie processes running - ps -eo pid,ppid,stat | grep  Z | wc -l

**Comment by sunnydoll** [comment]
Thank you @rite2nikhil for following up.
1> Docker is still responsive
2> We did not check the zombie processes

We wonder if there are any other people had same issue before. We have not had same issue while using ACS or AKS. And we did not make any deployment before or after the issue
