### ISSUE TITLE
./test/user.env should either be sourced manually or should allow overrides

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#283]
Right now, if I want to quickly deploy a cluster to two regions, I have to edit `user.env` manually in between runs.

I'd prefer to be able to set `LOCATION` manually, and have my env set override what's in `user.env`. So `user.env` would look like this:
```
#export LOCATION="westus"
export LOCATION="${LOCATION:-westus}"
```

Or maybe it'd be better if `./test/deploy.sh` didn't automatically source `user.env`. This forces the user to be slightly more conscious about what settings are being used... and then I would be able to just do:
```
source ./test/user.env
export LOCATION=westus
```

**Comment by anhowe** [comment]
This is low priority, but feel free to re-open.
