### ISSUE TITLE
NetworkPlugin CNI: Failed to allocate address: No available addresses

### ISSUE THREAD

**Issue by MirzaSikander** [Azure/acs-engine#2845]
**Is this a request for help?**:

---Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---Issue

**What version of acs-engine?**:

--- 0.15.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
After 30 pods are assigned to a node, creating additional pods fail since the IP addresses assigned to a node are exhausted
```
Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "arena-dqn-linux_default" network: Failed to allocate address: Failed to delegate: Failed to allocate address: No available addresses
```
```
Pod sandbox changed, it will be killed and re-created.
```
```
Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "arena-dqn-linux_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
```

This is a linux only cluster, and there are limited number of IP addresses assigned to one node. See image below. The capacity on the other hand is 110 pods which is misleading since only 30 pods can deployed on one node.

![image](https://user-images.githubusercontent.com/2823474/39559781-aa428e72-4e4d-11e8-9d2b-58d0086efd8f.png)

**What you expected to happen**:
Either limit the capacity when the node is created to 30 or allow more ip addresses per node.

In a hybrid cluster the networking is completely different, and a route table is used to forward traffic to a node. Based on the rules I have seen in previous clusters, there are 256 possible IP addresses with /24 subnet. It is baffling to see why its different for linux only cluster.

**How to reproduce it** (as minimally and precisely as possible):
Create 33 pods for one node on a linux only cluster with one node.

**Comment by xwrs** [comment]
+1. Facing the same issue

**Comment by IvanKirianov** [comment]
+ 1 
Is it possible to found some workaround of this ?

**Comment by sharmasushant** [comment]
You can add more ipconfigs to your interface in the VM provided subnet has more free ips. This can be done via portal or powershell.

**Comment by IvanKirianov** [comment]
"allocatable": {
                    "cpu": "2",
                    "ephemeral-storage": "28043041951",
                    "hugepages-1Gi": "0",
                    "hugepages-2Mi": "0",
                    "memory": "7011884Ki",
                    "pods": "110"

The capacity by default is 110 with new version of acs. But it's limited in 30.

**Comment by jt55401** [comment]
This was happening to me as well and adding ip-configs seems to have helped so far.
Is there an easier way to add lots of ip-configs to a nic?

I ended up just calling this over and over again, increment my name by one each time, but it was slow...

```az network nic ip-config create -g XXX --nic-name YYY --name ipconfig37```

**Comment by advishnuprasad** [comment]
Facing the same issue. However, I don't have 30 pods in my node.

**Comment by jt55401** [comment]
@advishnuprasad - I opened a support ticket with Microsoft, and was advised to upgrade the CNI plugin to a new version - you might want to try the same. 

https://github.com/Azure/azure-container-networking/releases/tag/v1.0.11

The install instructions work for an upgrade too - however, it's advised that after install, you fully restart the node (not just restart kubelet, as the instructions seem to indicate)

**Comment by apeschel** [comment]
Having only 30 IPs per node is really bad. It's worse than a 30 pods per node limit.

Job pods stick around for a while and hold onto their IPs. By default, a Job resource keeps around 3 job pods, for a total of around 4 IPs in use per job resource by default. This means you are limited to 7 job resources per node for your Kubernetes cluster. This design decision effectively makes Job resources unusable with the Azure Networking plugin.

The Azure Networking plugin appears to be buggy, and doesn't seem to always release IPs when pods are done with them. The exact cause is unclear here, but I've had nodes with less than 30 IPs in use by pods giving me this error of no free IPs remaining. Only rebooting the node seems to free the IPs back up. I suspect having job pods greatly aggravates the IP freeing issue, further preventing their practical use on Azure.

The Azure Networking Plugin is responsible for so many stability issues. From the history of problems with the Azure Networking Plugin, I believe acs-engine needs to drop support for the Azure Networking plugin as the default and use a different networking plugin by default.

**Comment by apeschel** [comment]
@sharmasushant I've upgraded to 1.0.12 and it seems more stable, thank you.

**Comment by rocketraman** [comment]
@sharmasushant I recently encountered this issue on a cluster with 1.0.12. It seems to have resolved itself for now, but I'd like to understand what happened.

Logs from one node: 
[azure-vnet-logs.zip](https://github.com/Azure/acs-engine/files/2577849/azure-vnet-logs.zip)

**Comment by rocketraman** [comment]
@sharmasushant I'm getting the IP addresses exhausted error again.

**Comment by jackfrancis** [comment]
@tamilmani1989 ping as well

**Comment by rocketraman** [comment]
@tamilmani1989 I raised the limit recently to 100, so that shouldn't be a problem. I was getting a different error when I was hitting the pod limit.

**Comment by rocketraman** [comment]
@tamilmani1989 I believe acs engine 0.24.2

**Comment by jackfrancis** [comment]
That would be Azure CNI 1.0.12

**Comment by tamilmani1989** [comment]
@rocketraman can you send me /var/run/azure-vnet.json and /var/run/azure-vnet-ipam.json?

**Comment by rocketraman** [comment]
> That would be Azure CNI 1.0.12

Yes it was but I used the manual update procedure after I ran into this issue to update all the nodes to 1.0.13.

**Comment by rocketraman** [comment]
@tamilmani1989 Here it is: 
[varrunjson.zip](https://github.com/Azure/acs-engine/files/2584364/varrunjson.zip)

**Comment by rocketraman** [comment]
@tamilmani1989 Is it significant that every node in the cluster seems to have exactly 30 "Addr" entries in `/var/run/azure-vnet-ipam.json`?

```
~$ kubectl get nodes -o name | cut -d / -f 2 | xargs -I{}  -n1 ssh {} 'grep -c "\"Addr\"" /var/run/azure-vnet-ipam.json'
30
30
30
30
30
30
```

**Comment by rocketraman** [comment]
And looking at `InUse` in `/var/run/azure-vnet.json`, definitely at least one of these nodes is very close to the limit, and that is also the node showing the "No available addresses" error:

```
~$ kubectl get nodes -o name | cut -d / -f 2 | xargs -I{}  -n1 ssh {} 'echo 'node ' {}; grep InUse /var/run/azure-vnet-ipam.json | sort | uniq -c'
node k8s-agentpool1-36147952-vmss000000
     14                                                                 "InUse": false
     16                                                                 "InUse": true
node k8s-agentpool1-36147952-vmss000001
     17                                                                 "InUse": false
     13                                                                 "InUse": true
node k8s-agentpool1-36147952-vmss000002
     13                                                                 "InUse": false
     17                                                                 "InUse": true
node k8s-agentpool1-36147952-vmss000003
     17                                                                 "InUse": false
     13                                                                 "InUse": true
node k8s-agentpool2-36147952-vmss000000
      1                                                                 "InUse": false
     29                                                                 "InUse": true
node k8s-agentpool2-36147952-vmss000001
      4                                                                 "InUse": false
     26                                                                 "InUse": true
```

**Comment by rocketraman** [comment]
@tamilmani1989 When this cluster was originally created, it had MaxPods set to the default of 30. I increased that value to 100 as per some instructions provided by @jackfrancis in Slack. But perhaps Azure CNI pre-allocates 30 addresses per that setting as well?

**Comment by tamilmani1989** [comment]
From the state file it looks like, IPs are not get updated to 100. Have you checked in portal if you got 100 ipconfigs for that nic?

**Comment by tamilmani1989** [comment]
Also I'm not sure  "by modifying --max-pods in /etc/default/kubelet"  if this adds ipconfigs to nic. We usually recommend adding ipconfigs in portal.

**Comment by rocketraman** [comment]
@tamilmani1989 Just add them manually in the portal? How do I know which IPs I can allocate? I'm concerned about breaking future acs-engine scale or update operations by allocating IPs in a manner that isn't consistent with acs-engine.

**Comment by tamilmani1989** [comment]
can you please verify in portal if the nic got 100 ipconfigs? 
you don't need to know about IPs if you select dynamic but anyway lets check why cni doesn't get the update.

**Comment by tamilmani1989** [comment]
Also @jackfrancis Does acs-engine support scaling ipaddresses on the fly (i.e) does it add ipconfigs to nic?
Can you please confirm if specifying  this -> "-max-pods in /etc/default/kubelet " adds ipconfig to nics?

**Comment by rocketraman** [comment]
> can you please verify in portal if the nic got 100 ipconfigs?

No, they have not. Each node currently has 30 ipconfigs according to the "Connected devices" page of the portal.

It appears in the portal I cannot add ipconfigs manually to the agent nodes even if I wanted to -- they are using VMSS and don't appear to have any option to add ipconfigs, unlike regular VMs.

**Comment by tamilmani1989** [comment]
@rocketraman ok this explains why CNI doesn''t get update. i'm not sure whether acs-engine supports scaling of ip addresses. @jackfrancis has to help here

Can't you access Network interface resource directly and add ipconfigs?

**Comment by jackfrancis** [comment]
@rocketraman how did you raise the limit from 30 to 100? Did you manually update the runtime configuration on each node? Or did you update the value in an api model and then pass that updated input to `acs-engine upgrade`?

**Comment by rocketraman** [comment]
@jackfrancis Manually based on a discussion with yourself in slack. I guess I should apply the upgrade method here, then?

**Comment by rocketraman** [comment]
@jackfrancis Attempted the upgrade... not working because pods aren't moving around the cluster properly due to IP address exhaustion. And because of the drain timeout being too low. And because Azure ARM deployment fails because it says a volume is duplicated or attached to multiple VMs when the portal shows it is not attached anywhere  Goddamn frustrating. And now I don't even have an easy way to revert to a working state, AFAICT.

**Comment by flow0787** [comment]
Pinging @rocketraman and @apeschel..  Does anyone know the permanent fix for this? I am experiencing the issue with IP exhaustion with a self-managed cluster on azure.

Despite not having 30 pods running at one time, (limit is 30) and more than sufficient IP addresses being allocated, K8S cannot spawn new pods due to this:

```
2019/12/17 09:48:51 [cni-ipam] Plugin azure-vnet-ipam version v1.0.7.
2019/12/17 09:48:51 [cni-ipam] Running on Linux version 4.15.0-1055-azure (buildd@lcy01-amd64-026) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #60-Ubuntu SMP Thu Aug 8 18:29:07 UTC 2019
2019/12/17 09:48:51 [ipam] reboot time 2019-08-20 04:26:51 +0000 UTC store mod time 2019-12-17 09:48:37.885566345 +0000 UTC
2019/12/17 09:48:51 [ipam] Restored state, &{Version:v1.0.7 TimeStamp:2019-12-17 09:48:37.889826956 +0000 UTC AddrSpaces:map[local:0xc420095140] store:0xc420094e10 source:<nil> netApi:<nil> Mutex:{state:0 sema:0}}
2019/12/17 09:48:51 [cni-ipam] Plugin started.
2019/12/17 09:48:51 [cni-ipam] Processing ADD command with args {ContainerID:c425d454b2d24d2e66b10c4374573c76a0f125ab6928835a565c490b4447187f Netns:/proc/20956/ns/net IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=iotaccelerator;K8S_POD_NAME=iam-keycloak-0;K8S_POD_INFRA_CONTAINER_ID=c425d454b2d24d2e66b10c4374573c76a0f125ab6928835a565c490b4447187f Path:/opt/azure-vnet/bin:/opt/cni/bin}.
2019/12/17 09:48:51 [cni-ipam] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.0.10.0/24 Address: QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} AdditionalArgs:[]}.
2019/12/17 09:48:51 [ipam] Starting source azure.
2019/12/17 09:48:51 [ipam] Refreshing address source.
+2019/12/17 09:48:51 [ipam] Source refresh failed, err:expected element type <Interfaces> but have <html>.
2019/12/17 09:48:51 [ipam] Requesting address with address: options:map[].
2019/12/17 09:48:51 [ipam] Address request completed with address:<nil> err:<nil>.
2019/12/17 09:48:51 [azure-vnet-ipam] Failed to allocate address: No available addresses.+
2019/12/17 09:48:51 [cni-ipam] ADD command completed with result:<nil> err:Failed to allocate address: No available addresses.
2019/12/17 09:48:51 [cni-ipam] Plugin stopped.
```

The pod is stuck in ContainerCreating on the agent node, and the logs above are from azure-cni on the node where the pod tries to start. We are running v1.0.7.

**Comment by rocketraman** [comment]
@flow0787 You're on a really old version of azure-cni. I think the fix was in 1.0.13 or something like that. I'm currently on 1.0.18.

**Comment by flow0787** [comment]
@rocketraman i know its a long shot, but do you by any chance remember which instructions you used for the CNI upgrade?

**Comment by rocketraman** [comment]
@flow0787 Yup, its actually documented: https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md#upgrading-cni-on-existing-kubernetes-cluster-deployed-using-acs-engine
