### ISSUE TITLE
kubernetes provisioning state succeeded but kubernetes is not installed either.

### ISSUE THREAD

**Issue by gaurav218** [Azure/acs-engine#2847]
Facing this issue where provisioning state is successful but kubernetes is not installed. version tried is 1.8.11.
acs engine version is 0.16.0.  

![image](https://user-images.githubusercontent.com/26568744/39591197-a97dffb6-4f20-11e8-90a5-5a64df23e0aa.png)

deleted resource group multiple times and redeployed kubernetes with different versions as well but same result. Recreated Service principal and tried access to subscription it works
Debugged master node for logs
Kubectl command give below error
The connection to the server 172.18.X.X:8001 was refused - did you specify the right host or port?

Had a look at /var/log/azure/cluster-provision.log and i have copied content below

+ echo 'Install complete successfully'
Install complete successfully
+ false
++ date
++ hostname
+ echo Thu May 3 15:10:06 UTC 2018,k8s-master-26527143-0, endscript
+ mkdir -p /opt/azure/containers
+ touch /opt/azure/containers/provision.complete
+ ps auxfww
root@k8s-master-26527143-0:/var/log/azure# ~docker ps
No command '~docker' found, did you mean:
 Command 'kdocker' from package 'kdocker' (universe)
 Command 'docker' from package 'docker.io' (universe)
~docker: command not found
root@k8s-master-26527143-0:/var/log/azure# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@k8s-master-26527143-0:/var/log/azure# ^C
root@k8s-master-26527143-0:/var/log/azure# kubectl cluster-info dump
The connection to the server 172.18.X.X:8001 was refused - did you specify the right host or port?
root@k8s-master-26527143-0:/var/log/azure# ^C
root@k8s-master-26527143-0:/var/log/azure#

Any help is appreciated.

**Comment by jackfrancis** [comment]
Hi @gaurav218, can you share the original api model json (excluding credentials) that you used to build the cluster?
