### ISSUE TITLE
acs-engine scale: Error: <nil>

### ISSUE THREAD

**Issue by saromba** [Azure/acs-engine#2858]
**Is this a request for help?**:yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):ISSUE

---

**What version of acs-engine?**:0.13.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:
I tried to scale up a k8s cluster but I get the following error:

INFO[0000] validating...                                
INFO[0003] Name suffix: 21147453                        
INFO[0003] Found no resources with type Microsoft.Network/routeTables in the template.  source="scaling command line"
INFO[0003] Starting ARM Deployment. This will take some time... 
INFO[0382] Finished ARM Deployment. Error: \<nil\>

**What you expected to happen**:
Scaling up the cluster

**How to reproduce it** (as minimally and precisely as possible):
acs-engine scale --subscription-id ${ID} --resource-group $AZURE_RESOURCEGROUP --location westeurope --deployment-dir foo --new-node-count 5 --master-FQDN $AZURE_RESOURCEGROUP.westeurope.cloudapp.azure.com

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@saromba are you seeing the same error with the latest version of acs-engine (v0.16.0)? It looks like your trying to scale a Windows node which isn't supported yet (see #1972), but in any case agreed that the error shouldn't be `nil`. @danigian is working on it though so stay put.

**Comment by saromba** [comment]
@CecileRobertMichon: With version 0.16.0 the error didn't occur.
INFO[0000] validating...                                
INFO[0003] Name suffix: 75658474                        
INFO[0003] Found no resources with type Microsoft.Network/routeTables in the template.  source="scaling command line"
INFO[0003] Starting ARM Deployment. This will take some time... 
INFO[0276] Finished ARM Deployment. Succeeded

Thanks for the quick reply.
