### ISSUE TITLE
Windows pods fail - netplugin failed

### ISSUE THREAD

**Issue by PatrickLang** [Azure/acs-engine#2868]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
Built from master, commit 057b045162a4b9911bf38857e829ae427c820078

with cherry picks from #2822 
commit f7959c6ecdb1cc7dba37da451723f114683d9d46
Author: Yongli Chen <yongli.chen@microsoft.com>
Date:   Mon Apr 30 22:23:23 2018 -0700

    Set Windows Azure CNI config

    (cherry picked from commit 36eb9d110d6ca538a68c0271fabcf7c442a21e7d)

commit 2dd9ada09d5134b4be17feae7c6505a7a7828dc6
Author: Jack Francis <jack.francis@microsoft.com>
Date:   Fri May 4 11:51:11 2018 -0700

    update Azure CNI ver

    (cherry picked from commit 0c0434414fc7085e8f106987f3db19cbd74b1efa)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.10.1

**What happened**:

Windows pods are failing to schedule with "netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input"

```
Events:
  Type     Reason                  Age                  From                   Message
  ----     ------                  ----                 ----                   -------
  Normal   SandboxChanged          15m (x1276 over 2h)  kubelet, 13192k8s9000  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  24s (x1400 over 2h)  kubelet, 13192k8s9000  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cn
i failed to set up pod "fabrikamfiber.web-5b796445f8-5ncgs_plang1" network: netplugin failed but error parsing its diagnostic message "": unexpected end of
 JSON input
```

**What you expected to happen**:
Pod should start

**How to reproduce it** (as minimally and precisely as possible):
kubectl apply -f https://raw.githubusercontent.com/PatrickLang/fabrikamfiber/ocpdemo/k8s/db-deployment.yaml

**Anything else we need to know**:

Here's the orchestrator version & pool properties I used

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.10.1"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "...",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "windowspool2",
        "count": 2,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows",
        "osDiskSizeGB": 127
      }
    ],
...
```

**Comment by sharmasushant** [comment]
Let us take a look. @saiyan86

**Comment by saiyan86** [comment]
@PatrickLang After k8s fixes https://github.com/kubernetes/kubernetes/issues/60884, #2884 should fix this issue.

**Comment by sharmasushant** [comment]
Thanks @saiyan86 
@PatrickLang please try to use k8s 1.8.12 that we have tested and works.
