### ISSUE TITLE
Cilium daemon set etcd access is not configured correctly

### ISSUE THREAD

**Issue by khenidak** [Azure/acs-engine#2872]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
*all*
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
When using `cilium` as CNI, The cilium daemonset is configured use one etcd server instead of all the etcds (in multi master scenario).

@jessfraz @jackfrancis

**Comment by jessfraz** [comment]
hmm i must not have known the right env variable, is there one that holds them all

**Comment by jessfraz** [comment]
it just needs to go here: https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesmastercustomdata.yml#L286
