### ISSUE TITLE
dockerEngineVersion validation - enable newer versions

### ISSUE THREAD

**Issue by mwieczorek** [Azure/acs-engine#2876]
**Is this a request for help?**:

---
no
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---
FEATURE REQUEST
**What version of acs-engine?**:

---
all

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

The newset version of docker we can use is 17.05.*
https://github.com/jackfrancis/acs-engine/blob/master/parts/k8s/kubernetesparams.t#L572

Today I hit an issue:
https://github.com/docker/for-linux/issues/214
And in one of the comments there's suggestion to upgrade docker at least to 17.09.

I know that it's not validated version (https://kubernetes.io/docs/imported/release/notes/#external-dependencies) but it's also not the default, so it's users choice to use not validated version.

**Comment by mwieczorek** [comment]
@jackfrancis @CecileRobertMichon What do you think? 
Today I hit another issue: https://github.com/docker/for-linux/issues/1 which is fixed in v18.03

Let me know if you consider to accept such pull request (adding additional versions). I can contribute, do some tests, changes in scripts, etc

**Comment by dtzar** [comment]
@mwieczorek I would LOVE to see the docker engine upgraded to the latest version.  @jackfrancis @CecileRobertMichon do we have more information on what breaks when we jump to the latest version or someone tackling this?
I remember @khenidak asking this question awhile back...

**Comment by khenidak** [comment]
There is a push to standardize on containerd due to licenses issues. Stay tuned.
