### ISSUE TITLE
k8s failure while processing extension 'cse1'

### ISSUE THREAD

**Issue by rncwnd79** [Azure/acs-engine#2882]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.16.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.7

**What happened**:
Cannot provision cluster with 3 masters, 3 agents.
Deployment failed while processing cse1 (master 1).

**What you expected to happen**:
Cluster being deployed without failure.

**How to reproduce it** (as minimally and precisely as possible):
Deploy kubernetes cluster consisting of 3 masters, 3 agents using acs-engine v0.16.2.

**Anything else we need to know**:

**Comment by rncwnd79** [comment]
Hi @CecileRobertMichon,
please see the output:
```
Deployment failed. Correlation ID: 487d0ed0-57dc-4f4c-b704-e5241268e3c6. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse1'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=30\n[stdout]\n\n[stderr]\n\"."
      }
    ]
  }
}
```

status = 30

**Comment by CecileRobertMichon** [comment]
Status 30 means that the script timed out waiting for nodes : see https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetescustomscript.sh. cse1 indicates that master-1 is the one that failed, you'll need to ssh to it and pull the same script there (assuming the one you pasted above was from master-0 as it finished successfully). What is the output of `kubectl get nodes `?

**Comment by CecileRobertMichon** [comment]
you should be able to enable agent forwarding by using `ssh -A` or follow [these instructions](https://github.com/Azure/acs-engine/blob/master/docs/ssh.md#key-management-and-agent-forwarding-with-windows-pageant) if you're using putty. Then you can simply type `ssh k8s-master-73186041-1` once you're on master 0 to jump to master 1 and pull the logs from the same place in master 1.
