### ISSUE TITLE
Routing setup intermittently failing

### ISSUE THREAD

**Issue by carlpett** [Azure/acs-engine#2887]
**Is this a request for help?**: Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

**What version of acs-engine?**: 0.12.4

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes 1.9.2

**What happened**: We're seeing pods intermittently not being able to communicate with anything. Other pods, services, the Kubernetes API, the internet. The connections time out.
Best guess so far is that something is failing in the iptables setup, since the routing is what seems to be broken.

**What you expected to happen**: Communication working.

**How to reproduce it** (as minimally and precisely as possible): Not sure. This happens seemingly at random. 

**Anything else we need to know**: We have a particular workload where a container is started, does a few network operations and then finishes, with quite high frequency (5-10 pods/minute) which gets hit by this quite a lot. 
But it has also happened to other pods in normal deployments. Being restarted by a crash-loop does not help, but deleting the pod or otherwise getting it scheduled on another node has helped there a few times.

Here's a list of cases I've tested on a pod in this state, and if it works:
- Ping/curl other pod on same node: NO
- Ping/curl other pod on other node: NO
- Ping/curl LoadBalancer service: NO
- Ping/curl api, or DNS-lookups to kube-dns: NO
- Ping/curl internet hosts: NO
- Ping node running the pod: YES!
- Ping other nodes: NO

Anything else I should test? Some specific routing I should look at?

**Comment by oivindoh** [comment]
Is there any difference using IP instead of DNS names?

**Comment by carlpett** [comment]
Nope, and sorry for not mentioning that. DNS fails (since we can't reach 10.0.0.10...) so all tests were on IP addresses.

**Comment by jackfrancis** [comment]
@carlpett Are you able to deploy a test cluster using k8s 1.9.7 and repro? In particular there were several ILB issues on Azure w/ the early patch releases of 1.9.

**Comment by carlpett** [comment]
@jackfrancis I don't have a reliable way of triggering this myself, unfortunately. Are there any details about those issues that I can use to try to determine if they are behind this? (Also, what is ILB? :) )

**Comment by jackfrancis** [comment]
ILB == Internal Load Balancer

**Comment by carlpett** [comment]
Ah, right. Thanks!
I'm probably missing something, but how is a load balancer involved here, this seems to affect pod egress traffic, mainly? And were there some good issues for me to check if they were the same?

**Comment by carlpett** [comment]
@jackfrancis this just happened again on 1.10.3.
I spoke with @khenidak yesterday about there being a recent fix for Azure CNI that could be relevant?

**Comment by sharmasushant** [comment]
@carlpett Can you please paste the output of following from one of the nodes from where pods cannot reach anywhere

ebtables -t nat -L
iptables -t filter -L
iptables -t nat -L

**Comment by sharmasushant** [comment]
Also, can you please verify if you are using Azure CNI or not. You can list the files in /opt/cni/bin/ and also check if there are logs from azure cni in the /var/log/azure-vnet.log This log will also have the version of azure cni in the very beginning

**Comment by carlpett** [comment]
@sharmasushant Yes, we're using the Azure CNI. Here's the first row of /var/log/azure-vnet.log:
>Plugin azure-vnet version v1.0.4-1-gf0f090e

Here's the requested output: https://gist.github.com/carlpett/33939f883a096609fd44f55d6fc64634

**Comment by carlpett** [comment]
This just happened once more (on another 1.10.3 cluster). Opened a support case about it, let me know if you need the log output and can't get it via support.

**Comment by jackfrancis** [comment]
@carlpett Could you try installing this daemonset, it has been proven to stabilize ebtables on an Azure CNI-based cluster:

Ref:

https://hub.docker.com/r/containernetworking/networkmonitor/

Do this to install the monitor:

`$ kubectl create -f https://raw.githubusercontent.com/Azure/acs-engine/master/parts/k8s/addons/azure-cni-networkmonitor.yaml`

And then, edit the daemonset to point to the actual image:

`$ kubectl edit daemonset azure-cni-networkmonitor -n kube-system`

Replace `<azureCNINetworkMonitorImage>` with `containernetworking/networkmonitor:v0.0.4`.

**Comment by sharmasushant** [comment]
@carlpett I looked at your output of ebtables. I see the rules are there for the PODS created on the nodes. The cni network monitor was created in response to an incident where ebtables were getting completely flushed on the node (kernel logs will usually tell you if that is the case). 

Is it possible to have access to the machine where the POD is in the state that you have describe in original issue?
