### ISSUE TITLE
openshift: no easy way to tell cluster web ui URL after deploy

### ISSUE THREAD

**Issue by jim-minter** [Azure/acs-engine#2891]
should probably be an output from the arm template, and perhaps acs-engine should print this to the console too.

**Comment by jim-minter** [comment]
@kwoodson low hanging fruit :)

**Comment by kwoodson** [comment]
@jim-minter,

I see that the variable that is required here is `ExternalMasterHostname`.  Where is the best place to print to the console?

**Comment by kwoodson** [comment]
This is where the hostname is passed and the template is parsed.  https://github.com/kwoodson/acs-engine/blob/master/pkg/acsengine/engine.go#L1948

**Comment by jim-minter** [comment]
@kwoodson the "masterFQDN" ARM template output is already correctly populated.  Right at the end of cmd/deploy.go, inspect the first return value of dc.client.DeployTemplate() to dig out the value.  If the orchestrator is OpenShift, print it in the form `https://%s:8443/`.

**Comment by kwoodson** [comment]
@jim-minter, thanks.  I was looking here: https://github.com/Azure/acs-engine/blob/master/pkg/armhelpers/deployments.go

I'll see what I can come up with.

**Comment by kwoodson** [comment]
@jim-minter,

The `res` variable from the `dc.client.DeployTemplate()` looks like this:
```
&{Response:{Response:0xc4200a6870} ID:<nil> Name:<nil> Properties:<nil>}
```

The response looks like this:
```
&{Status:200 OK StatusCode:200 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Pragma:[no-cache] X-Ms-Correlation-Request-Id:[8e2e4c71-6e6c-4f2f-8c29-e5c35131af0f] Date:[Tue, 05 Jun 2018 15:34:27 GMT] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Content-Type-Options:[nosniff] Content-Type:[application/json; charset=utf-8] Vary:[Accept-Encoding] X-Ms-Request-Id:[8e2e4c71-6e6c-4f2f-8c29-e5c35131af0f] X-Ms-Routing-Request-Id:[WESTUS:20180605T153428Z:8e2e4c71-6e6c-4f2f-8c29-e5c35131af0f] Cache-Control:[no-cache] Expires:[-1] X-Ms-Ratelimit-Remaining-Subscription-Reads:[14960]] Body:{Reader:} ContentLength:-1 TransferEncoding:[] Close:false Uncompressed:true Trailer:map[] Request:0xc4200da600 TLS:0xc4206060b0}
```

The templateJSON holds the `masterFQDN` and it looks like this:
```
  masterFQDN:map[type:string value:[reference(concat('Microsoft.Network/publicIPAddresses/', variables('masterPublicIPAddressName'))).dnsSettings.fqdn]]]
```

I believe this is interpreted by the ARM template processor on Azure's side.

I do not think that the returned results have the desired information.  Any ideas?

**Comment by jim-minter** [comment]
Agreed.  Wow, nothing is easy :(

As far as I can see, this must be because the version of the Azure client library we're using is ancient.

Let's do this the stupid way:
```
if dc.containerService.Properties.OrchestratorProfile.OrchestratorType == api.OpenShift {
	// TODO: when the Azure client library is updated, read this from the template `masterFQDN` output
	fmt.Printf("OpenShift web UI available at https://%s.%s.cloudapp.azure.com:8443/\n", dc.containerService.Properties.MasterProfile.DNSPrefix, dc.location)
}
```

**Comment by kwoodson** [comment]
@jim-minter please review: 

https://github.com/Azure/acs-engine/pull/3193/files
