### ISSUE TITLE
ReadinessProbe / LivenessProbe critically failing in the entire cluster

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#2892]
**Is this a request for help?**:

Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

---

**What version of acs-engine?**:

0.13.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

1.6.6

**What happened**:

I have 6 clusters created the past year, recently we updated (in January) the version of acs-engine from 0.5.0 to 0.13.1 and the cluster was working properly. Suddenly all my 6 clusters are down because Readiness/Liveness probes are failing everywhere, from kube-system pods to the entire pods causing Termination on all the rest of pods. This is very very critical issue. It seems to be solved after restarting nodes, but after a few minutes the chaos starts again.

**What you expected to happen**:

Keep working.

**How to reproduce it** (as minimally and precisely as possible):

Deploy a 1.6.x latest version with acs-engine 0.13.1.

**Anything else we need to know**:

I have seen many issues related to this. My pods now:

> tiller-deploy-3575610951-ggk0x k8s-agentpool1-15972647-0
> Readiness probe failed: Get http://10.244.1.92:44135/readiness: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> Error syncing pod, skipping: rpc error: code = 4 desc = context deadline exceeded

 

> kube-dns-v20-2135026167-9hds5 k8s-agentpool1-15972647-0
> Liveness probe failed: Get http://10.244.1.91:8080/healthz-dnsmasq: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> Failed to create container with error: rpc error: code = 4 desc = context deadline exceeded
> Error syncing pod, skipping: failed to "StartContainer" for "healthz" with rpc error: code = 4 desc = context deadline exceeded: "Create Container Failed"

**Comment by jackfrancis** [comment]
@hmarcelodn What do kube-dns pod logs say in the kube-system namespace?

**Comment by hmarcelodn** [comment]
Hi @jackfrancis 

This is the only thing I can see from the dashboard right now.

>  Liveness probe failed: Get http://10.244.1.18:8080/healthz-kubedns: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> Failed to create container with error: rpc error: code = 4 desc = context deadline exceeded
> Error syncing pod, skipping: failed to "StartContainer" for "healthz" with rpc error: code = 4 desc = context deadline exceeded: "Create Container Failed"

Also, I must mention that I see node lost because of this.

**Comment by jackfrancis** [comment]
FYI I have a PR that I'm using to add environmental DNS sanity checks for our E2E cluster deployments:

https://github.com/Azure/acs-engine/pull/2921

Please add any high level wishlist items or concrete coverage requests there to get ahead of these issues going forward. Thanks!

**Comment by hmarcelodn** [comment]
Thanks @jackfrancis ,

We are still experiencing Termination of _Pods_, _Node Losts_ so some downtime is happening from time to time during the day. The donwtime then is recovered by the K8S auto-healthing.

We rolled-back the cluster and generated this with 0.5.0 (the latests which worked well for us the latest year) but same thing happens.

**Comment by PatrickLang** [comment]
Is this happening on newer releases? This seems stale
