### ISSUE TITLE
Deploying ACS Engine K8s Cluster with jumpbox will fail with SubnetIsFull Error

### ISSUE THREAD

**Issue by gcarrarom** [Azure/acs-engine#2897]
**Is this a request for help?**:
No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
0.16.2

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.7

**What happened**:
When deploying a Kubernetes cluster in a custom Subnet, trying to specify the CIDR of the subnet will fill up the subnet with IPConfigurations. 
If Adding a Jumpbox to the cluster, this will result in a deployment of a NIC before the creation of the cluster and there will be one less Private IP available, making the deployment fail when trying to create the cluster.

**What you expected to happen**:
ACS-Engine should reserve 1 less ip address from the subnet when a jumpbox is present in the APIModel.

**How to reproduce it** (as minimally and precisely as possible):
Create a VNET with limited number of ip addresses (/27), create a cluster with a JumpBox in the API Model.

**Anything else we need to know**:
--

**Comment by Navlesh** [comment]
I am also facing similar bug that SubnetIsFull even we have total of 27 IPs available and without provisioning Jubpbox using ACS engine v0.16.2 and Kubernetes 1.9.7.
I to have updated ACS engine generated templates not to reserve any IP, however it is getting failed.

**Comment by CecileRobertMichon** [comment]
@Navlesh are you also trying to deploy a private cluster?

**Comment by Navlesh** [comment]
Yes @CecileRobertMichon, that happens when we have /27 IPs, to avoid this bug, I did increase IPs range to /26 and it's resolved the bug.
I am also facing error when extension is being installed in the VMs, any suggestion? do you have to avoid error during extension installation in the VMs

**Comment by CecileRobertMichon** [comment]
@Navlesh can you please clarify what you mean by: 

> do you have to avoid error during extension installation in the VMs

What error are you seeing? What's exact status code?

**Comment by Navlesh** [comment]
@CecileRobertMichon, I see following error.
"code": "VMExtensionProvisioningError"
"message": "VM has reported a failure when processing extension 'cse1'. Error message: \"Enable failed: failed to 
execute command: command terminated with exit status=20\n[stdout]\n\n[stderr]\n\"."

**Comment by CecileRobertMichon** [comment]
Ah this is a different issue. Exit status 20 means that Docker failed to install (see https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetescustomscript.sh#L6). This is most likely due to a transient networking failure. Can you please try deploying again? If you still see the error, please open a new issue for this specific deployment error. I would like to keep this one to track the `SubnetIsFull` error.

**Comment by CecileRobertMichon** [comment]
@Navlesh were you able to repro?

**Comment by Navlesh** [comment]
@CecileRobertMichon Yes I am able to reproduce SubnetIsFull error only when the IPs range is less /27 or lesser.

**Comment by CecileRobertMichon** [comment]
@Navlesh I meant the `VMExtensionProvisioningError`. I'll have a PR to fix `SubnetIsFull` shortly.

**Comment by Navlesh** [comment]
@CecileRobertMichon I thought, You wanted to maintain this thread just for SubnetIsFull error.
VMExtensionProvisioningError is not consistence, I also felt that it occurs mostly when we have IPs range is less. However i am not able reproduce when I use a IPs range /26.
