### ISSUE TITLE
K8s 1.6 - windows - set timeout flag

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#290]
Noting this so that we don't forget since we're just patching private binaries for 1.5.x...

**Comment by anhowe** [comment]
@JiangtianLi completed this

**Comment by JiangtianLi** [comment]
@colemickens  Thanks for reminding. We set timeout as parameter --image-pull-progress-deadline=20m passed to kubelet in kuberneteswindowssetup.ps1 for 1.6.0 and up.
