### ISSUE TITLE
openshift: prometheus: Unexpected templating type error 

### ISSUE THREAD

**Issue by jim-minter** [Azure/acs-engine#2900]
See https://ci.openshift.redhat.com/jenkins/view/All/job/test_pull_request_origin_extended_conformance_azure_39/22/consoleFull

Unexpected templating type error occurred on ({{  __schedulable_nodes_matching_selector['results']['results'][0]['items'] | default([]) | length != 0 }}): object of type 'builtin_function_or_method' has no len()

**Comment by jim-minter** [comment]
@maxamillion I think you were looking into this before - I think it's still occurring as a flake - please can you investigate?

**Comment by jim-minter** [comment]
Also https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_origin_extended_conformance_azure_39/12

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_azure_39/15

**Comment by jim-minter** [comment]
@maxamillion re https://github.com/maxamillion/openshift-ansible/commit/fa3cf33900c7ccfe73b11591ce60a5281a0737cb somewhat belatedly I realised that this change needs to be in the ansible container that's running on the master - so I think what's needed is to do something really quite nasty in pkg/openshift/certgen/release39/templates/master/tmp/ansible/ansible.sh and just get that checked in here.

**Comment by maxamillion** [comment]
@jim-minter ah, well that's unfortunate
