### ISSUE TITLE
networkPlugin deploy validation error

### ISSUE THREAD

**Issue by DaveNW16HD** [Azure/acs-engine#2909]
**Is this a request for help?**:
YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
BUG
---

**What version of acs-engine?**:
Version: v0.16.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8S 1.10

**What happened**:

I'm trying to deploy a k8s cluster with networkPlugin set to kubenet
I have a very simple json deployment api model below
`

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10",
	  "kubernetesConfig": {
            "networkPlugin": "kubenet",			
		    "kubeletConfig": {
				"--hairpin-mode": "hairpin-veth"
			  },
			  "addons": [
				  {
					"name": "tiller",
					"enabled" : true
				  },
				  {
					"name": "kubernetes-dashboard",
					"enabled" : true
				  }
				]
		}
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 4,
        "vmSize": "Standard_E2_v3",
        "availabilityProfile": "AvailabilitySet",        
        "customNodeLabels": {
          "seidoenv": "staging"
        }
      }
    ],
    "linuxProfile": {
      "adminUsername": "balh",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
`

This is the error message I get

`
INFO[0000] Error returned by LoadContainerService: Unknown JSON tag networkPlugin
FATA[0000] error validating deployCmd: error parsing the api model: Unknown JSON tag networkPlugin
`

**What you expected to happen**:

Deploy the cluster

**How to reproduce it** (as minimally and precisely as possible):

Run a simple deploy command with the above json

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@DaveNW16HD I believe the PR that introduced networkPlugin is not included in v0.16.2 (which only added a new k8s version). It is in master though, and will be in the upcoming v0.17.0.

**Comment by CecileRobertMichon** [comment]
If you still want to build from v0.16.2 you can use `"networkPolicy": "none"` as an equivalent to setting networkPlugin to kubenet.

**Comment by DaveNW16HD** [comment]
Thanks, that worked !
