### ISSUE TITLE
Unable to get logs or port-forward with Windows nodes

### ISSUE THREAD

**Issue by sam-cogan** [Azure/acs-engine#2912]
**Is this a request for help?**:
Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

---

**What version of acs-engine?**:

0.16.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
1.8.11

**What happened**:
Multiple freshly deploy clusters all have timeouts when attempting to run kubeclt logs or kubectl port-forward against Windows containers (linux containers seem to be OK). Other Kubectl services are working fine, no system pods are stopped or erroring but any request to get logs or port forward results in this error:

Error from server: Get https://18430k8s9010:10250/containerLogs/default/rafting-termite-app-5f97c8b4f4-bml9s/rafting-termite-app: dial tcp 10.240.0.65:10250: getsockopt: connection timed out

**What you expected to happen**:
To be able to get logs and port forward

**How to reproduce it** (as minimally and precisely as possible):
Deploy an Cluster with Windows nodes, deploy pods and attempt to  get logs

**Anything else we need to know**:

**Comment by sam-cogan** [comment]
As is always the case I fixed this 5 minutes after posting. The issue was the firewall on the Windows node was blocking port 10250, allowing this worked.

This begs the question, should the deployment do this?

**Comment by CecileRobertMichon** [comment]
@JiangtianLi

**Comment by JiangtianLi** [comment]
@sam-cogan what does `netsh advf show allprofiles` output on windows node?

**Comment by JiangtianLi** [comment]
@sam-cogan Also can you check if you are using Azure CNI?

**Comment by sam-cogan** [comment]
I've recently recreated the environment from scratch with K8 1.10 and can confirm the issue is still present here. This is using CNI and the output of the all profiles command is below.
```

Domain Profile Settings:
----------------------------------------------------------------------
State                                 ON
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/A (GPO-store only)
InboundUserNotification               Disable
RemoteManagement                      Disable
UnicastResponseToMulticast            Enable

Logging:
LogAllowedConnections                 Disable
LogDroppedConnections                 Disable
FileName                              %systemroot%\system32\LogFiles\Firewall\pfirewall.log
MaxFileSize                           4096


Private Profile Settings:
----------------------------------------------------------------------
State                                 ON
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/A (GPO-store only)
InboundUserNotification               Disable
RemoteManagement                      Disable
UnicastResponseToMulticast            Enable

Logging:
LogAllowedConnections                 Disable
LogDroppedConnections                 Disable
FileName                              %systemroot%\system32\LogFiles\Firewall\pfirewall.log
MaxFileSize                           4096


Public Profile Settings:
----------------------------------------------------------------------
State                                 ON
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/A (GPO-store only)
InboundUserNotification               Disable
RemoteManagement                      Disable
UnicastResponseToMulticast            Enable

Logging:
LogAllowedConnections                 Disable
LogDroppedConnections                 Disable
FileName                              %systemroot%\system32\LogFiles\Firewall\pfirewall.log
MaxFileSize                           4096


```
