### ISSUE TITLE
External LB created, even though `privateCluster` option specified

### ISSUE THREAD

**Issue by bigmyx** [Azure/acs-engine#2917]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**What version of acs-engine?**:
---
v0.16.2

**Input Configuration**

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.8.12",
      "kubernetesConfig": {
        "clusterSubnet": "...",
        "networkPolicy": "none",
        "kubeletConfig": {
          "--max-pods": "110"
        },
        "privateCluster": {
          "enabled": true
        },
        "enableRbac": false
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "test-cluster",
      "vmSize": "Standard_B2ms",
      "vnetSubnetId": "...",
      "firstConsecutiveStaticIP": "...",
      "ipAddressCount": 5,
      "vnetCidr": "..."
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 1,
        "vmSize": "Standard_B4ms",
        "vnetSubnetId": "...",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "mic",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa ..."
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "ClientID": "...",
      "Secret": "..."
    }
  }
}


```

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
External LB created, even though `privateCluster` option specified

**What you expected to happen**:
The cluster should be completely internal, with no Internet exposure

**How to reproduce it** (as minimally and precisely as possible):
Use provided config for deployment

**Comment by CecileRobertMichon** [comment]
Hi @bigmyx, thanks for reporting! That sounds like a bug. Let me try to repro. I only get an internal load balancer when I deploy a vanilla private cluster but I'll try using a custom vnet and see if that is causing what you're seeing.

**Comment by CecileRobertMichon** [comment]
Could you check in the _output directory under the folder with your cluster name, there will be an azuredeploy.json file: how many resources are there of type `"type": "Microsoft.Network/loadBalancers"`? Can you send me the definition of those resource(s)?

**Comment by bigmyx** [comment]
@CecileRobertMichon, there is no such resource in `azuredeploy.json` file or any other generated files.

**Comment by bigmyx** [comment]
Apparently, one of our deployments created an external service resulted in creation of external LB and IP.
Closing this issue.
