### ISSUE TITLE
Error provisioning Masters: extensions CSEx always failing

### ISSUE THREAD

**Issue by hensilva** [Azure/acs-engine#2922]
## **ISSUE**
ACS-ENGINE version: 0.16.1
Kubernetes version: 1.9
Azure Region: Brazil South
Number of Masters: **1 or 3**

Description: when deploying I'm invariably getting CSE extension errors on Master nodes and cluster is failing to deploy. Tested with 3 Masters and 1 Masters, similar problem.

Last message from /var/log/azure/cluster-provision.log:

**k8s cluster is not healthy after 600 seconds
 exit 30**

Error from Azure Portal (applies to all Masters, extensions CSE0, CSE1, etc.)
**{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse2'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=30\n[stdout]\n\n[stderr]\n\"."
      }
    ]
  }
}**

My JSON (removing sensitive data) is below:
_{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.9",
        "kubernetesConfig": {
          "networkPolicy": "azure",
          "useInstanceMetadata": false,
          "privateCluster": {
            "enabled": false
          }
        }
      },
      "masterProfile": {
        "count": 3,
        "dnsPrefix": "hensilvae7819cd00a89",
        "vmSize": "Standard_B2ms",
        "storageProfile": "ManagedDisks",
        "vnetSubnetId": "/subscriptions//resourceGroups/PRD-Network/providers/Microsoft.Network/virtualNetworks//subnets/",
        "firstConsecutiveStaticIP": "172.16.7.200",
        "vnetCidr": "172.16.0.0/16"
      },
      "agentPoolProfiles": [
        {
          "name": "agentpool1",
          "count": 5,
          "vmSize": "Standard_B2ms",
          "vnetSubnetId": "/subscriptions//resourceGroups/PRD-Network/providers/Microsoft.Network/virtualNetworks//subnets/",
          "availabilityProfile": "AvailabilitySet",
          "storageProfile" : "ManagedDisks"
        }
      ],
      "linuxProfile": {
        "adminUsername": "hensilva",
        "ssh": {
          "publicKeys": [
            {
              "keyData": ""
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId": "",
        "secret": ""
      }
    }
}_

**Comment by CecileRobertMichon** [comment]
@hensilva could you please try deploying with a bigger VM size? Preferably not B series or A0. We've seen those kinds of errors when VMs had insufficient CPU/memory.

**Comment by hensilva** [comment]
I also tried with D2_v2 and D2_v3. Should I aim even higher?

**Comment by CecileRobertMichon** [comment]
@hensilva D2_v2 and v3 should be enough. If it is still failing, could you check that you can build a simple VM in your vnet and run `apt-get update` or `curl -fsSL https://aptdocker.azureedge.net/gpg` ? My guess is that your vnet either a) has an NSG rule that prevents outbound access or b) there is a firewall in place preventing your from accessing dependencies such as ubuntu.com... In order the deploy a cluster in a custom vnet the vnet needs sufficient, flexible outbound connection to install dependencies such as Docker, kubectl, CNI and others.

**Comment by CecileRobertMichon** [comment]
@hensilva any update here? Did you end up solving your issue?

**Comment by Navlesh** [comment]
@CecileRobertMichon It is failing in Master for me as well
I am using Standard_DS3_v2 VM size for Master (1) and Standard_DS2_v2 for worker (1).
ACS engine v0.19.0 and Kubernetes version 1.10.

2nd (clarification)
What service acs engine use in Azure to deploy cluster, is it Kubernetes services (AKS) or Azure container Service (ACS)?

**Comment by CecileRobertMichon** [comment]
@Navlesh what's the exit code you are seeing? Please take a look at https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/troubleshooting.md#vmextensionprovisioningerror-or-vmextensionprovisioningtimeout. 

> What service acs engine use in Azure to deploy cluster, is it Kubernetes services (AKS) or Azure container Service (ACS)?  

Answer: Neither, acs-engine generates Azure Resource Manager templates (ARM) and uses those to create Azure resources. In fact, ACS and AKS use acs-engine for some tasks (an not the other way around).
