### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by kichristensen** [Azure/acs-engine#2926]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.16.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Running the extension examples provided doesn't work

**What you expected to happen**:
It worked

**How to reproduce it** (as minimally and precisely as possible):
Add the prometheus-grafana-k8s extension to deployment

**Anything else we need to know**:
After some fiddling I got the extension to be accepted in the ARM template, but then I instead got the error below during deployment:

```
{
  "error": {
    "code": "BadRequest",
    "message": "Multiple VMExtensions per handler not supported for OS type 'Linux'. VMExtension 'cse0' with handler 'Microsoft.Azure.Extensions.CustomScript' already added or specified in input."
  }
}
```

**Comment by ritazh** [comment]
@kichristensen can you please share how you are adding the extension to your cluster definition? thanks!

**Comment by kichristensen** [comment]
This is my config with extensions:

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes", 
      "orchestratorRelease": "1.9",
      "kubernetesConfig": {
        "apiServerConfig": {
          "--admission-control":  "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DenyEscalatingExec,Initializers,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota",
          "--runtime-config": "admissionregistration.k8s.io/v1alpha1"
        },
        "useInstanceMetadata": true,
        "networkPolicy": "azure",
        "enableRbac": true
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "$ACS_DNS_PREFIX",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool",
        "count": 2,
        "vmSize": "Standard_DS11_v2",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Linux",
        "extensions": [
          {
            "name": "prometheus-grafana-k8s"
          }
        ]},
      {
        "name": "windowspool",
        "count": 1,
        "vmSize": "Standard_DS11_v2",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      }
    ],
    "windowsProfile": {
      "adminUsername": "$ACS_VM_ADMIN_USER_WINDOWS",
      "adminPassword": "$ACS_VM_ADMIN_PWD_WINDOWS"
    },
    "linuxProfile": {
      "adminUsername": "$ACS_VM_ADMIN_USER_LINUX",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "$ACS_VM_ADMIN_PWD_LINUX"
          }
        ]
      }
    },
    "extensionProfiles": [
      {
        "name": "prometheus-grafana-k8s",
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": "$ACS_SERVICEPRINCIPAL",
      "secret": "$ACS_SERVICEPRINCIPAL_SECRET"
    },
    "aadProfile": {
      "tenantID": "$ACS_SERVICEPRINCIPAL_TENANT",
      "serverAppID": "$ACS_SERVICEPRINCIPAL_API_SERVER",
      "clientAppID": "$ACS_SERVICEPRINCIPAL_API_CLIENT",
      "adminGroupID": "$ACS_ADMIN_GROUP_RBAC"
    }
  }
}
```
In the end I get this error:

```
ERROR: Deployment template validation failed: 'The resource 'Microsoft.Compute/virtualMachines/k8s-linuxpool-58091530-0/extensions/cse0' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.
```

**Comment by CecileRobertMichon** [comment]
@kichristensen @ritazh I think this issue is due to https://github.com/Azure/acs-engine/pull/2713... Is there a dependency on the custom script extension or something that refers the custom script extension in the extension template? If so should be `cse-master-$index` or `cse-agent-$index` instead of `cse-$index`

**Comment by kichristensen** [comment]
@CecileRobertMichon it is correct that the first error:

```
ERROR: Deployment template validation failed: 'The resource 'Microsoft.Compute/virtualMachines/k8s-linuxpool-58091530-0/extensions/cse0' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.
```

Disappears if I change the ```dependsOn``` section to match ```cse-agent-$index``` instead of ```cse-$index```. But then I get the next error during deployment on Azure:

```
{
  "error": {
    "code": "BadRequest",
    "message": "Multiple VMExtensions per handler not supported for OS type 'Linux'. VMExtension 'cse0' with handler 'Microsoft.Azure.Extensions.CustomScript' already added or specified in input."
  }
}
```

**Comment by neurot1cal** [comment]
do we have a timeline on when we think this fix will be rolled into acs-engine? do we have a good understanding of where things are breaking down? i'm about to deploy another cluster, and i'll be avoiding VMSS again if theres no workaround for these extensions

**Comment by hmarcelodn** [comment]
@neurot1cal  how do you avoid VMSS ? Is there a way to do this in the apimode.json ? Thanks

**Comment by neurot1cal** [comment]
@hmarcelodn You define this in each of the agentPoolProfiles in the cluster definition (availabilityProfile). For example;

```
      {
        "name": "linuxpool2",
        "count": 5,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "extensions": [
          {
            "name": "prometheus-grafana-k8s"
          }
        ]
      },
```

**Comment by ritazh** [comment]
Thanks @CecileRobertMichon I think that might be it. I will take a look at this today in few hours. Sorry for the delay.

**Comment by CecileRobertMichon** [comment]
@neurot1cal #3031 is merged. I'm in the process of releasing a patch including both @ritazh 's PR and this latest one. Good news is that extensions are fixed. Bad news is that they still don't work with VMSS.... which was never the case. I have ideas on how to make them work but it will require some re-design so I didn't want to hold this PR for it since it's an important bugfix.
