### ISSUE TITLE
acs-engine docker images not being published

### ISSUE THREAD

**Issue by apeschel** [Azure/acs-engine#2930]
Docker images for acs-engine should be getting published to https://hub.docker.com/r/microsoft/acs-engine/ but this is not happening. There is only a single image tagged "latest" from 9 months ago, which corresponds to acs-engine 0.8.0.

Please push a 0.16.X image, and ideally set up CI to automatically push images when releases happen.

Thank you

**Comment by apeschel** [comment]
@CecileRobertMichon 

It's been almost two months on this, and it's seriously a 5-10 minute fix. Can someone please upload a newer version of this container?

**Comment by CecileRobertMichon** [comment]
@apeschel I'll make sure this gets done sometime this week. The issue got lost in the pile of new issues, sorry about that!

**Comment by CecileRobertMichon** [comment]
@apeschel just pushed the image for v0.19.1, let me know if you run into any issues. I'll work on setting up an automated build.

**Comment by apeschel** [comment]
@CecileRobertMichon I appreciate it very much, thank you!

**Comment by apeschel** [comment]
@CecileRobertMichon Unfortunately, the Docker image doesn't seem to be correctly formed: it's has a windows binary on a Linux base, and doesn't seem to use the Dockerfile in the repo.

There are instructions on how to build the image in the `releases` directory:

https://github.com/Azure/acs-engine/blob/master/releases/README.Dockerfile.md

Is seems like you're using Windows, based on the Docker image that was published, so the commands to run would be as follows:

```
PS> cd releases
PS> $VERSION="0.19.1"
PS> docker build --no-cache --build-arg BUILD_DATE=$(Get-Date((Get-Date).ToUniversalTime()) -UFormat "%Y-%m-%dT%H:%M:%SZ") --build-arg ACSENGINE_VERSION="$VERSION" -t microsoft/acs-engine:$VERSION --file .\Dockerfile.linux .
```

**Comment by CecileRobertMichon** [comment]
@apeschel sorry for the delay I was off, I'll fix it today
