### ISSUE TITLE
Deploy using client-id and client-secret command line switches throws an error

### ISSUE THREAD

**Issue by maniSbindra** [Azure/acs-engine#2933]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: Building against current commit
./bin/acs-engine version. Realised this when trying to fix issue 2728
```sh
(Version: canary
GitCommit: 5e0ff5b
GitTreeState: dirty)
```

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**: same as #2657, I have added comments against PR #2771 which may have caused the issue to reoccur.

**What you expected to happen**: same as #2657, I have added comments against PR #2771 which may have caused the issue to reoccur.

**How to reproduce it** (as minimally and precisely as possible): same as #2657, I have added comments against PR #2771 which may have caused the issue to reoccur.

**Anything else we need to know**: same as #2657, I have added comments against PR #2771 which may have caused the issue to reoccur.

**Comment by CecileRobertMichon** [comment]
@maniSbindra good catch! We will need to change the change the logic to either a) allow empty client id/secret in validation, b) fill in the apimodel with the values before we validate it or c) load the CS without validation and run a validation later after filling in values from the command line. I personally prefer option c) if we can get it work.
