### ISSUE TITLE
IsKubernetesVersionGe does not work for prerelease version

### ISSUE THREAD

**Issue by karataliu** [Azure/acs-engine#2936]
**Is this a request for help?**:
When deploying a cluster with 1.11.0-alpha.1, the taint on master does not appear.

This is due to IsKubernetesVersionGe uses 'semver' to determine the version, and it assumes '1.11.0-alpha.1 >= 1.6.0' to be false, which is not intended behaviour.

https://github.com/Azure/acs-engine/blame/ad8c1da9b944760c8f9da209aac8c7d0d93eb816/parts/k8s/kubernetesmastercustomdata.yml#L182

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

**What version of acs-engine?**:
2a0766f0337b9d466a429763a36c15cb8267ebe5

apimode.json:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.11",
...
```

**Comment by karataliu** [comment]
This is a requirement for running CI on pre-release version. Since for CI testing, we might want a cluster to have same behavior of a production cluster (user pods running on agents)

**Comment by CecileRobertMichon** [comment]
@karataliu I validated that isKubernetesVersionGe works as expected via #2950. If the taint issue is still happening, please reopen the issue and change the title, it might be caused by something else.

**Comment by karataliu** [comment]
@CecileRobertMichon 
Thanks for taking a look.

The unittest calls common.IsKubernetesVersionGe, which handles prerelease case.
https://github.com/Azure/acs-engine/blob/f48137d77a6b258396cad13d3768858dc4cef2ca/pkg/api/common/versions.go#L319


But for template generation, it calls the 'IsKubernetesVersionGe' in engine.go, which does not handle prerelease.
https://github.com/Azure/acs-engine/blob/v0.16.2/pkg/acsengine/engine.go#L908

That's why the taint won't appear. Could you please recheck. Thanks.

**Comment by karataliu** [comment]
Seems I didn't find the 'reopen' button...

Suppose the fix should be forwarding 'IsKubernetesVersionGe' in engine.go calls the one in versions.go?

**Comment by CecileRobertMichon** [comment]
Ah that makes more sense thanks. Reopened the issue.

**Comment by CecileRobertMichon** [comment]
@karataliu this should fix it ^

**Comment by karataliu** [comment]
Verified the fix works. Thanks!
