### ISSUE TITLE
acs-engine 'login'

### ISSUE THREAD

**Issue by saromba** [Azure/acs-engine#2937]
**Is this a request for help?**: YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.16.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:
I've a jenkins pipeline to scale up/down. It works almost as expected.

`az login --service-principal -u $SP_APPID -p $SP_PASSWORD --tenant $SP_TENANTID`
`az account set --subscription $SUBSCRIPTION_ID`
`acs-engine scale --subscription-id $SUB_ID --resource-group $RG ...`

The problem is, that I've to **sign in every jenkins build**.

`[360000] validating...`
`[330000] To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code RTZR7HWB to authenticate.`

How can I fix/skip that? 

**What you expected to happen**:
No microsoft device login 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by croeck** [comment]
I do not think that this is an issue here. Did you try this:

https://docs.microsoft.com/en-us/azure/jenkins/execute-cli-jenkins-pipeline

**Comment by neurot1cal** [comment]
@saromba even with the `az login` and `az account set` you'll need to pass values into `acs-engine scale`. I used to do it this way as well, and it started defaulting to client auth (The login message you're seeing) instead of using my SP. 

Try to append these to your `acs-engine scale` command;

```
--auth-method client_secret --client-id <SP_ID> --client-secret <SP_SECRET>
```

**Comment by saromba** [comment]
@neurot1cal: Thx. That's the solution for me.
@croeck: Thx for the article. I installed the azure plugin. I didn't know that.
