### ISSUE TITLE
Can you run Kubernetes on RHEL with acs-engine?

### ISSUE THREAD

**Issue by shayansarkar** [Azure/acs-engine#2941]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Request
---

**What version of acs-engine?**:
0.16.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
RHEL is not a supported distro when creating a cluster

**What you expected to happen**:
I was hoping that I could create a cluster running on RHEL instead of Ubuntu

**How to reproduce it** (as minimally and precisely as possible):
This json config is what I used to try to create the cluster.  When I ran acs-engine against it I received the following error

```Orchestrator type Kubernetes not suported on RHEL Master```

```
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorVersion": "1.10.2"
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "bgk8scluster-vmss",
            "vmSize": "Standard_D2s_v3",
            "distro": "rhel"
        },
        "agentPoolProfiles": [{
            "name": "agentpool1",
            "count": 2,
            "vmSize": "Standard_D2s_v3",
            "availabilityProfile": "VirtualMachineScaleSets",
            "storageProfile": "ManagedDisks",
            "distro": "rhel"
        }],
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": {
                "publicKeys": [{
                    "keyData": ""
                }]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "",
            "secret": ""
        }
    }
}
```

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@shayansarkar currently RHEL is only supported with orchestrators SwarmMode and Openshift.

**Comment by shayansarkar** [comment]
Thanks.  Is there a technical restriction for that?  Or if I made the updates to acs-engine, could it theoretically work?

**Comment by CecileRobertMichon** [comment]
@shayansarkar I am not aware of such restrictions. We would definitely allow a PR that introduces RHEL support for K8s. The first step would be to change the validation at https://github.com/Azure/acs-engine/blob/74e1ee146dafcb0f309e49a7a1d38148160300d9/pkg/acsengine/engine.go#L477
to allow RHEL with k8s and test if it works straight out of the box. If not, there might be a few changes required to get to a functional RHEL + Kubernetes cluster deployment.

**Comment by shayansarkar** [comment]
Thanks for the info.  I'll close out this request and hopefully get back to you all with a PR later.
