### ISSUE TITLE
Deploying CoreOS cluster on Azure

### ISSUE THREAD

**Issue by fair18** [Azure/acs-engine#2943]
**Is this a request for help?**:
YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

---

**What version of acs-engine?**: 
Version: v0.16.2
GitCommit: f75f600fa
GitTreeState: clean

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I have tried to deploy an example of kubernetes cluster using distribution OS: CoreOS. I took example from https://github.com/Azure/acs-engine/tree/master/examples/coreos. After 40 mins of waiting I recieved an error from Azure:

```json
{
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"VMExtensionProvisioningError\",\"message\":\"VM has reported a failure when processing extension 'cse2'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=20\\n[stdout]\\n\\n[stderr]\\n\\\".\"}]}}",
        "statusCode": "Conflict"
}
```

**What you expected to happen**:
I expected to have complete cluster that I can test with CoreOS.  How avoid this issue?

**How to reproduce it** (as minimally and precisely as possible):

```bash
acs-engine deploy --subscription-id $(ID) \
		   --resource-group K8sCoreOSResourceGroup --location eastus2 \
		   --dns-prefix sandbox-coreos \
		   --api-model coreos.cluster.json
```

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2",
      "distro": "coreos"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        "distro": "coreos"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
````

**Anything else we need to know**:
I removed  ("networkPlugin": "kubenet") due to issue that I had "**Error returned by LoadContainerService: Unknown JSON tag networkPlugin** "

**Comment by sozercan** [comment]
Related to #2340?

**Comment by fair18** [comment]
@sozercan  Yes, I think so.
