### ISSUE TITLE
Design doc: Kubernetes provisioning in CSE

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#2944]
This will briefly outline the pros/cons of moving all retry-able application layer provisioning into CSE, i.e., `"type": "CustomScript"` Azure resource attached to the vm resource. At present, the implementation is a hybrid, with some of the provisioning being implemented as serial shell commands in cloud-init, and some of it as serial shell commands in CSE, with cross-interface communication via the filesystem.

Pros/Cons of change to CSE:

Cons:

- Observation suggests cloud-init begins between 0-60s earlier than CSE (i.e., not *always* earlier, but often earlier, and not often later); by moving application layer provisioning out of cloud-init, we delay the start time of this deployment phase, resulting in (1) a longer theoretical kubernetes node deployment

Pros:

- cloud-init does not bubble up error codes to ARM, and thus we (1) our node deployment success/fail result is non-deterministic (or we have to report via the filesystem to CSE that a particular command has failed), and (2) we don't have historical ARM records of cloud-init success/fail; tl;dr, cloud-init is implemented in such a way that it accommodates pre-requisite paving, but it is not a validation interface. By doing everything in CSE we have a nice, clean, uncomplicated story of success/fail for each phase in the application layer provisioning process
- CSE supports general shebang executable usage patterns, accommodating a variety of runtime shells; cloud-init is `/bin/sh`
- CSE takes as its input an executable string, which can point to any number of files; cloud-init uses the cloud-init runcmd interface, which is appropriate only for maintaining simple, one-line shell-interpretable scripts
- CSE enables secure context (parameter `"type": "securestring"`)

**Comment by CecileRobertMichon** [comment]
Also to consider: 

- cloud init and CSE both have size limits (although we've proven in the past that the CSE limit is quite large, at least 64K)
- Secrets must be transferred in custom data
