### ISSUE TITLE
openshift: "503 Service Unavailable" flake

### ISSUE THREAD

**Issue by jim-minter** [Azure/acs-engine#2952]
```
$ oc get route/nginx-example -n default -o jsonpath={.spec.host}
2018/05/14 17:44:00 got status "503 Service Unavailable" while trying to access nginx-example-default.40.114.111.175.nip.io
```

**Comment by jim-minter** [comment]
https://circleci.com/gh/Azure/acs-engine/26335

**Comment by jim-minter** [comment]
@kargakis can you take a look?

**Comment by jim-minter** [comment]
Seems improbable that it was DNS if it got as far as receiving a 503 response?

**Comment by kargakis** [comment]
Need to check whether the pod uses a readiness check and also whether the deployment config waits for it to turn ready.

**Comment by kargakis** [comment]
> Need to check whether the pod uses a readiness check and also whether the deployment config waits for it to turn ready.

Both readiness probe is used and the DC has sane rolling parameter defaults.

**Comment by kargakis** [comment]
ugh, retries were using microseconds for intervals instead of the intended milliseconds - opened https://github.com/Azure/acs-engine/pull/3202
