### ISSUE TITLE
Example for ClusterAutoScale with multiple node pools

### ISSUE THREAD

**Issue by beaudryj** [Azure/acs-engine#2963]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature Request

---

**What version of acs-engine?**: Latest

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** 1.10.X

In regards to the documentation for - https://github.com/Azure/acs-engine/tree/master/examples/addons/cluster-autoscaler could we please have an example for multiple node pools so that when I stand up my cluster I dont need to manually configure a second cluster for autoscale

**Comment by ewok2030** [comment]
This functionality was added in PR #2637 but at this time it only supports autoscaling the first nodePool. 

Per this [comment](https://github.com/Azure/acs-engine/pull/2637#issuecomment-386400035), you'll have to SSH into each master node and manually modify the addon file to add the config for additional node pools.

I was going to suggest that the documentation is updated to make this limitation clearer
