### ISSUE TITLE
404 in link on https://github.com/Azure/acs-engine/blob/master/docs/swarmmode.md

### ISSUE THREAD

**Issue by NightFantomJ2** [Azure/acs-engine#2981]
**Is this a request for help?**:

Yes, I think?

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue.

---

**What version of acs-engine?**:

The documentation on github, at the point of this commit: https://github.com/Azure/acs-engine/commit/bfc9c7eea789970aa87287183d7123ee5bc69ad9

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

N/A

**What happened**:

I clicked a link and it gave me a 404 error.
( point 5 in https://github.com/Azure/acs-engine/blob/master/docs/swarmmode.md : "deploy the output azuredeploy.json and azuredeploy.parameters.json" , linking here: https://github.com/Azure/acs-engine/blob/master/acsengine.md#deployment-usage )

**What you expected to happen**:

To see the correct information linked.

**How to reproduce it** (as minimally and precisely as possible):

Go to the linked page and click the link.

**Anything else we need to know**:

N/A

**Comment by NightFantomJ2** [comment]
from a different (working) link I noticed that it should be:
https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md#deployment-usage

(notice the added /docs/ in the middle)

if someone could fix this (and search the repo for references before changing links like that) that would be great, thanks!

**Comment by CecileRobertMichon** [comment]
@NightFantomJ2 feel free to open a PR to fix it if you're interested in contributing!
