### ISSUE TITLE
ERROR: The template deployment 'openshift-eastus-47708' is not valid according to the validation procedure.

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#2982]
Not sure where this issue comes from. Not sure whether we can expose more information from azure.

https://circleci.com/gh/Azure/acs-engine/26767?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by CecileRobertMichon** [comment]
AKAIK this is a symptom of a syntax error in azuredeploy.json... Very annoying to debug since ARM doesn't return more info. Since it's not happening 100% of the time it could be due to a specific Go template flow. For example something like : 
```
"osDisk": {
            "createOption": "FromImage"
          {{if ne .OSDiskSizeGB 0}}
            "diskSizeGB": {{.OSDiskSizeGB}}
          {{end}}
          }
```  
In this case the template validation will fail if ` ne .OSDiskSizeGB 0` because there will be a missing comma, should be: `  ,"diskSizeGB": {{.OSDiskSizeGB}}`

Not saying that it's a missing comma but it's a common pattern that I've seen when debugging ARM validation errors.

**Comment by jim-minter** [comment]
```
$ az group deployment create --name openshift-eastus-93914 --resource-group openshift-eastus-93914 --template-file /go/src/github.com/Azure/acs-engine/_output/openshift-eastus-93914/azuredeploy.json --parameters /go/src/github.com/Azure/acs-engine/_output/openshift-eastus-93914/azuredeploy.parameters.json
2018/05/14 21:24:38 
Error from deployment for openshift-eastus-93914 in resource group openshift-eastus-93914:exit status 1
2018/05/14 21:24:38 Command Output: ERROR: The template deployment 'openshift-eastus-93914' is not valid according to the validation procedure. The tracking id is 'ac84e721-51e5-4363-a9c9-8693a7a8e158'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
```

**Comment by jim-minter** [comment]
I'm not convinced it's a syntax error - I've been able to download the produced assets and the JSON parsed and was acceptable to ARM in our subscription (i.e. parameters and variables all matched up, etc).  I think this might be an image marketplace related error.

**Comment by jim-minter** [comment]
Possibly some az equivalent of Get-AzureRMLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DetailedOutput may get the required additional debug info

**Comment by jim-minter** [comment]
@ritazh fyi

**Comment by jim-minter** [comment]
`az monitor activity-log` ?

**Comment by kargakis** [comment]
Even though fetching the activity log has been helpful in debugging other issues, it hasn't helped every time this flake occurs.

**Comment by kargakis** [comment]
@ritazh @sozercan any idea on debugging this further? What other info would we need out of Azure?
