### ISSUE TITLE
Kubernetes: Managed Disk vs Storage Account

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#2993]
Thread to discuss pros/cons of ManagedDisk vs StorageAccount

**Comment by jackfrancis** [comment]
@DonMartin76 said:

> FWIW, we have run on ManagedDisks now for two weeks, and I can't say I am happier with it than with the StorageAccount clusters. Provisioning dynamic disks takes longer (3+ minutes instead of 1-2 minutes), and is also less calculatable in time (variance is higher). As our initial problem (the disk mounter checks all resource groups, not just the current ones, for blobs, #2768) is not appearing in 1.10.x, we will most probably go back to StorageAccount to see whether our clusters are more stable and consistent that way. In addition, smaller vhd disks seem to be faster than small managed disks. And we tend to have many smaller disks than a few large ones.

**Comment by andyzhangx** [comment]
FYI @karataliu
