### ISSUE TITLE
VM has reported a failure when processing extension 'cse0' / Generating cluster CNI

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#3013]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.13.1 & 0.16.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
1.6.6

**What happened**:
I want to create a regular cluster using CNI since Kubenet is not working fine either but after the deployment finished I received the error message:

> VM has reported a failure when processing extension 'cse0' 

**What you expected to happen**:
To properly generate de cluster

**How to reproduce it** (as minimally and precisely as possible):
Try to create a cluster using **_networkPolicy: "azure"_** using acs-engine 0.13.1 up to 0.16.2

**Anything else we need to know**:
-

**Comment by CecileRobertMichon** [comment]
Hi @hmarcelodn, are you running into the same issue with version 0.17.0?

**Comment by hmarcelodn** [comment]
Yes @CecileRobertMichon  even 0.17.1

**Comment by CecileRobertMichon** [comment]
@hmarcelodn please see https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/troubleshooting.md#vmextensionprovisioningerror-or-vmextensionprovisioningtimeout
