### ISSUE TITLE
Nodes are getting Lost everytime with High Disk IO usage. Cant ssh is available either.

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#3025]
**Is this a request for help?**:

YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.5.0, 0.16.2, 0.17.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Nodes are getting lost from 3 weeks ago. I deployed the cluster several times with different acs-engine versions and its not fixed. I can see that my nodes are getting a high read disk usage, almost 100% and I cannot even ssh into the agent nodes when they are lost. It obviously produce downtimes. Sometimes more than one node is lost. It happens in my production environments. Machines Standard D4s v3

**What you expected to happen**:
Avoid losing nodes.

**How to reproduce it** (as minimally and precisely as possible):
I generated several clusters in my prod environment and same thing happen.

**Anything else we need to know**:
-

**Comment by hmarcelodn** [comment]
https://github.com/Azure/acs-engine/issues/906

**Comment by hmarcelodn** [comment]
@jackfrancis Hey could you help me on that ?? We are experiencing this every moment and again losing nodes in Production. Is there a way we can RAID system disks so we can increse IOPS ? Kubelet seems to be reading quite a lot.

I appreaciate if I can a feedback on that from you may be you can indicate us how to proceed with this?

**Comment by jackfrancis** [comment]
@hmarcelodn What is the current IOPS limit of the disks you're seeing this on?

**Comment by hmarcelodn** [comment]
@jackfrancis  I had 500 IOPS from an Standard_D2_v2 with 30 GB. I just deployed a Standard_DS2_V2 (which uses Premium Disks by default) with Premium Disks with 250 GB + 1100 IOPS. It is in production now running after I regenerated the cluster. I am going to monitor this and see what happens. Is there a best practice for a production ready cluster in terms of recommended IOPS ? Thanks !!

**Comment by hmarcelodn** [comment]
![image](https://user-images.githubusercontent.com/5897525/40400079-eefb0732-5e16-11e8-8d66-5aa12cf77089.png)

After the change I can see a lot of activity again @jackfrancis

**Comment by hmarcelodn** [comment]
https://github.com/kubernetes/kubernetes/issues/64108 Related

**Comment by tammert** [comment]
@hmarcelodn: I had a similar (or perhaps the same) issue, which ultimately turned out to be sssd. Is that installed on your VM? If so, 0.17.0 uses a new Ubuntu image which fixes the issue -> see https://bugs.launchpad.net/cloud-images/+bug/1746806

**Comment by hmarcelodn** [comment]
Thanks @tammert I am going to try this! Good finding. Thanks!
