### ISSUE TITLE
Increase log level in the openshift control plane

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#3026]
@pweil- @jim-minter opening for discussion since I am torn.

We are setting up and starting the control plane ourselves (no ansible) as part of the master script. Once we switch to static pods there won't be any big difference. I see two possible actions for increasing the loglevel in the e2e tests:

1. update log level in the config (sysconfig or pod manifests) after a deployment is done but before tests start + restart services (ugly plus we miss debug logs during post-install tasks)
2. expose loglevel in openshift.json - as I was writting this I realized we cannot configure this today at all so I think it makes sense to do it here and now.

I think we should do 2. but wanted to discuss before I move forward with opening a PR, maybe there is something else? Thoughts? Objections?

/label orchestrator/openshift
/kind feature

**Comment by jim-minter** [comment]
I'm tempted to do nothing for now.  Would it help to express more clearly /why/ we think it would be necessary to do this?

**Comment by kargakis** [comment]
The control plane currently runs on loglevel=2 which is too low for debugging. In Origin, e2e tests run with 4.

**Comment by pweil-** [comment]
we really need the ability to change loglevel at runtime.  

2 seems like the best option but it seems less useful if it cannot be used on an existing cluster.  That would be the bar for me.   Not sure how easy that is.

**Comment by jim-minter** [comment]
@kargakis can we table this for the architecture call?  I feel there's way more to talk about here than meets the eye.  I've added a topic to the arch topics doc.
