### ISSUE TITLE
Services not working with Windows 1803 Containers

### ISSUE THREAD

**Issue by sam-cogan** [Azure/acs-engine#3037]
**Is this a request for help?**: 
No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue

---

**What version of acs-engine?**:
Master
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10

**What happened**:
When using Windows 1803 Images (with recent fixes in master) it is not possible to access cluster internal resources via services. A simple http based service times out when trying to access via the service name or IP. Directly accessing the pod IP does work

**What you expected to happen**:

Services to work to display http data

**How to reproduce it** (as minimally and precisely as possible):

Deploy a http service running on a Windows 1803 container, attempt to access internal to the cluster using a service.

**Anything else we need to know**:

**Comment by PatrickLang** [comment]
Can you try changing the CNI config to "bridge" and see if that changes anything?

https://github.com/Azure/acs-engine/pull/3045 has more info on service VIP problems. It's still a work in progress trying to doc things that are currently needing extra workarounds.

**Comment by sam-cogan** [comment]
I've changed to using bridge on teh Windows node, rebooted it and recreated the pods, and still seeing the same issue. Anything else I should be doing?

**Comment by PatrickLang** [comment]
my mistake - `bridge` isn't implemented yet so its not a valid workaround. we're working on a hotfix, and I'll use this issue to track it.

**Comment by PatrickLang** [comment]
cc @dineshgovindasamy

**Comment by sam-cogan** [comment]
Any update on this patch? I am now seeing the same issue with 1709 as well, pods cannot communicate with services.

**Comment by sharmasushant** [comment]
@sam-cogan We have made changes to both azure-cni and acs-engine. Let us release the new version of azure-cni and update acs-engine with that version. It seems to be working for us with 1709. We will take a look at 1803 one more time. I will provide an update here.
cc @saiyan86

**Comment by PatrickLang** [comment]
@sharmasushant is there a tracking issue for the pulling the new azure-cni into acs-engine deployments? 

cc @beaudryj

**Comment by jbiel** [comment]
@sharmasushant - will there be a new release of wincni.exe with these fixes? We are using k8s outside of Azure and continue to experience lots of networking issues. Thanks.

**Comment by PatrickLang** [comment]
@sam-cogan are you still having a problem? There was a DNS change merged in https://github.com/Azure/acs-engine/pull/3180 that resolved most issues for me. Here's my status using v0.18.3 https://github.com/Azure/acs-engine/pull/3216

**Comment by sam-cogan** [comment]
I haven't tried 1803 recently, I'll give it a go shortly and see

**Comment by sam-cogan** [comment]
I have just tested and yes this is still an issue with 1803, even when using the 0.18.8 release. No communication can occur between services on Windows Nodes. This includes taking to the cluster DNS, so pods cannot resolve any external resources either.
I'm struggling to see how anyone can be running a cluster using 1803 at this point, as there is no communication outside of pods.

**Comment by PatrickLang** [comment]
@daschott - does this match what you're seeing on 0.18.8? I haven't tried that build yet, but since 0.18.7 reverted to azure-cni 1.0.4 I think DNS server settings could be broken again

**Comment by daschott** [comment]
@PatrickLang I just tried acs-engine 0.18.8 and can confirm that there seems to be at least one DNS-related regression that was introduced. My observations for a vanilla deployment are:
  1. The first pod that is scheduled on a node won't have any network connectivity as @sam-cogan suggested. This was already an issue previously (endpoint is created prematurely before network is created correctly.)
  2. Inside pods the DNS suffix is missing the namespace again (ie it just has `svc.cluster.local` when it should be `<namespace>.svc.cluster.local`), so kube-DNS will only work with FQDN.
  3. External DNS and service access works for pods, (except if it is the first one scheduled on a node as described in 1.)

**Comment by sam-cogan** [comment]
It does look like an issue with the first pod scheduled on a node, when I schedule subsequent pods they do seem to be able to resolve.

**Comment by PatrickLang** [comment]
We have a Windows hotfix available for this available now, and it will be included by default in a future cumulative update for Windows. If you need to work around it near term, ask Windows support to give you the fix and reference this. Unfortunately I can't redistribute it publicly.

**Comment by daschott** [comment]
@PatrickLang I believe this is in reference to an older issue
@sam-cogan Can you confirm that your issue is resolved on recent acs-engine versions? It should be fixed on 0.19.3+.

**Comment by campbelldgunn** [comment]
@PatrickLang Have we confirmed that this issue has been resolved in a recent acs-engine. If so, can we confirm what version of acs-engine? thanks.

**Comment by rcarmo** [comment]
I'm also tracking this in a recent deployment. Can we have more info on whether updated Windows images already include a fix, or any mitigation approaches we can use to (for instance) tailor ACS-engine to pick out stable OS images?
