### ISSUE TITLE
deal with backtick (`) chars in sp keys

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#3038]
Exact details TBD, but from a high level we should either fail validation or escape backticks. Observation suggests that currently we're not dealing with it at all which yields non-deterministic side-effects during deployment.

**Comment by CecileRobertMichon** [comment]
Right now we have single quotes around it to allow special characters https://github.com/Azure/acs-engine/pull/2255 but not sure how we can deal with ` characters
