### ISSUE TITLE
Calico not working in v0.17.0

### ISSUE THREAD

**Issue by JunSun17** [Azure/acs-engine#3044]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

v0.17.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

default

**What happened**:

Calico network policy is not enforced.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

Tested v0.16.2 and it works, also noticed Calico template has been upgrade recently, which likely causes this issue.

**Comment by ozdanborne** [comment]
@jackfrancis I think there was some confusion during the NetworkPolicy / NetworkPlugin split. Calico requires the cluster be set to `--networking=cni`, not `--networking=kubenet`. I believe the recent changes are launching it with kubenet, which causes the behavior that OP is seeing.
