### ISSUE TITLE
Following kubernetes deploy guide fails on 0.17.1

### ISSUE THREAD

**Issue by jwilander** [Azure/acs-engine#3051]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.17.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes 1.9

**What happened**:

I followed the [kubernetes deploy guide](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md) and ran

```
acs-engine deploy --subscription-id <my-id> --dns-prefix <some-dns> --location eastus --api-model /path/to/my/kubes.json
```

I used the default `examples/kubernetes.json` api model with some minor changes, e.g. different machine counts/sizes and added an SSH public key.

I received the following errors

```
INFO[0000] Error returned by LoadContainerService: missing Properties.MasterProfile.DNSPrefix 
FATA[0000] failed to load apimodel: %s error parsing the api model: missing Properties.MasterProfile.DNSPrefix 
```
Filling in the DNSPrefix field then resulted in another error

```
INFO[0000] Error returned by LoadContainerService: the service principal client ID must be specified with Orchestrator Kubernetes 
FATA[0000] failed to load apimodel: %s error parsing the api model: the service principal client ID must be specified with Orchestrator Kubernetes 
```

I downgraded acs-engine to 0.16.2 and it worked correctly.

**What you expected to happen**:

Following the guide worked with the latest version.

**How to reproduce it** (as minimally and precisely as possible):

Follow the guide to deploy Kubernetes with acs-engine 0.17.1.

**Anything else we need to know**:

Don't think so.

**Comment by mikey-** [comment]
Seems to be the same or 0.17.1 but not for 0.16.1.

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/pull/2771 added validation in acs-engine deploy. It wasn't failing before because no validation was done. We need to update the docs to reflect that and make sure that the validation makes sense.

**Comment by CecileRobertMichon** [comment]
Also https://github.com/Azure/acs-engine/issues/2933 needs to be fixed to address the client id/secret issue
