### ISSUE TITLE
openshift: mysterious kubelet failure

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#3054]
I run a deployment of 3.9 to test https://github.com/Azure/acs-engine/pull/3053 and the master node never came up until I restarted `origin-node`.

I was seeing the following error in its journal:
```
May 23 15:43:23 ocp-master-98543699-0 origin-node[2431]: I0523 15:43:23.325055    2431 kubelet.go:1779] skipping pod synchronization - [Kubelet failed to get node info: failed to get zone from cloud provider: invalid character '<' looking for beginning of value]
```
I had a look at the node config and azure.conf but both seemed fine (and the process came up fine once I restarted it).

Another thing to note here is that because it took some time for the master node to come up, ansible eventually failed to install the webconsole and of course subsequently didn't install any other component. We probably need a separate issue about this in openshift-ansible, similar to https://github.com/openshift/openshift-ansible/issues/8028

@jim-minter @pweil- @kwoodson @mjudeikis

**Comment by jim-minter** [comment]
@kargakis agreed - open issues upstream + a tracking issue here?

**Comment by pweil-** [comment]
that error message is suspiciously like when you get an html 404 page (or something similar) for something we're expecting to return a json response.  I suspect config error or a down api.

**Comment by kargakis** [comment]
> @kargakis agreed - open issues upstream + a tracking issue here?

Opened https://github.com/openshift/openshift-ansible/issues/8507
