### ISSUE TITLE
Add go fmt check to checkin validation

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#306]
When looking at #152, some changes appear to just be a result of having run `go fmt` meaning we're not all running it before sending PRs. We should add a check for it.

**Comment by raveeram** [comment]
Should we run go fmt and do a diff or run the go linter?

**Comment by colemickens** [comment]
We should steal inspiration from : https://github.com/Azure/go-autorest/blob/master/.travis.yml#L13

Basically, run the `go fmt` in the mode where it outputs a diff and make sure there is no diff.

We should also run `golint`, but we have stuff to cleanup first before we can do tha.

**Comment by raveeram** [comment]
Ah I see, makes sense. I do see a few linter errors, vscode-go plugin has it by default from the looks of it.

**Comment by dmitsh** [comment]
addressed in:
https://github.com/Azure/acs-engine/pull/377

commit:
https://github.com/Azure/acs-engine/commit/badeb8dd469ee228cb39cec0f3f32ed038b25d2c
