### ISSUE TITLE
Sku not available error

### ISSUE THREAD

**Issue by ptrstpp950** [Azure/acs-engine#3060]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.17.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I tried to follow a basic tutorial, and whatever size of the machines I set I end up with following error:

**What you expected to happen**:

>The requested size for resource '/subscriptions/[GUID]/resourceGroups/my-name/providers/Microsoft.Compute/virtualMachines/k8s-agentpool1-13078356-0' is currently not available in location 'northeurope' zones '' for subscription '[GUID]'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details. (Code: SkuNotAvailable)

**How to reproduce it** (as minimally and precisely as possible):
Use examples (applying fixes to avoid #3051 )
- https://github.com/Azure/acs-engine/tree/master/examples/kubernetes-vmss
- below one
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.9",
      "kubernetesConfig": {
        "useManagedIdentity": true
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "something-abc",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
        {
          "name": "agentpool1",
          "count": 3,
          "vmSize": "Standard_D2_v2",
          "availabilityProfile": "AvailabilitySet"
        }
      ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "my public key"
          }
        ]
      }
    }
  }
}
```

**Anything else we need to know**:
I tried 3 zones (2 in Europe, 1 in USA), diffrent sizes (including NVIDIA), and still no luck

**Comment by srinathnarayanan** [comment]
I am also encountering this issue when I try to deploy to East US 2. I ran 
Get-AzureRmComputeResourceSku | where {$_.Locations -icontains "eastus2"} to see which VM types were available, and it looked like none of them were available in that region for my subscription.
How can I enable these VM types in this region for my subscription?

**Comment by CecileRobertMichon** [comment]
https://docs.microsoft.com/en-us/azure/azure-supportability/sku-series-unavailable

**Comment by CecileRobertMichon** [comment]
@ptrstpp950 @srinathnarayanan were you able to deploy in those regions before?

**Comment by ptrstpp950** [comment]
I never tried to deploy ACS anywhere. I tried this even on 2 different subscriptions, and still no luck. If you need I can post generated ARM template.

**Comment by CecileRobertMichon** [comment]
@ptrstpp950 you need to make a capacity request. See the link I posted above.
