### ISSUE TITLE
Where to find cluster-name generated by acs-engine

### ISSUE THREAD

**Issue by SeanTurner026** [Azure/acs-engine#3061]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
Version: canary
GitCommit: 3482257e
GitTreeState: clean
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Unable to get cluster-name. This is used when running azure cli commands such as `az acs kubernetes browse -g <resource-group-name> -n <cluster name>`

**What you expected to happen**:
I expect to be able to run azure cli commands that are dependant on the cluster name.

**How to reproduce it** (as minimally and precisely as possible):
Create a kubernetes cluster with acs-engine.

**Anything else we need to know**:
I believe I saw somewhere in this repo that the cluster name is not configurable. This is fine, but I would like to know where to find it. I have looked in `apimodel.json` and on the azure portal, but have been unable to find the cluster name.

**Comment by CecileRobertMichon** [comment]
@SeanTurner026 your cluster name would be your dns prefix provided in either the apimodel or as a flag when running `acs-engine deploy`. However `az acs kubernetes browse -g <resource-group-name> -n <cluster name>` is an ACS command (not acs-engine)...

**Comment by CecileRobertMichon** [comment]
To be clear, there is no acs-engine command in the az cli...

**Comment by SeanTurner026** [comment]
Thank you for the response.

Yeah I realise that acs-engine is separate from the az cli, I only asked because I saw on https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md that the "--cluster-name" was auto generated. That said, I've tried the passing in the value for my DNS-prefix before and haven't had any luck.

**Comment by CecileRobertMichon** [comment]
Please see https://github.com/Azure/acs-engine/blob/6a0221787a5f2e1cd0f601639b4ee32a8a59adff/pkg/acsengine/defaults-controller-manager.go#L28 

The controller-manager  `--cluster-name` flag is "auto-generated" as in is derived from the DNS prefix. Note that this is different from the `--cluster-name` flag in az cli commands.
