### ISSUE TITLE
VMSS is broken on 0.17.1

### ISSUE THREAD

**Issue by omartin2010** [Azure/acs-engine#3062]
**Is this a request for help?**:yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):ISSUE

---

**What version of acs-engine?**:0.17.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** : Kubernetes

**What happened**:Can't deploy following the instructions [here](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md) and following the template included in examples/kubernetes-vmss-low-priority/kubernetes.json

**What you expected to happen**:cluster to deploy

**How to reproduce it** (as minimally and precisely as possible):run the deployment using this command:
acs-engine deploy --subscription-id _<my_sub>_ --location eastus --api-model kubernetes-vmss-low-priority/kubernetes.json
I modified kubernetes.json to put the dns name in there, and didn't put the dns name in the deploy command line because it creates a bug as I've seen in [issue 3051](https://github.com/Azure/acs-engine/issues/3051).

**Anything else we need to know**:
I'm was able to repro one time. Happy to try again, now I'm using the "longer" version of the process which creates the actual template.

**Comment by omartin2010** [comment]
i fount out this also seems to be broken with the ["long way"](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md#acs-engine-the-long-way) version of the process. A missing parameter in the generated parameter file (azuredeploy.parameters.json) seems to be the source of the problem. Here's an output of the error message I forgot to put above : 
{
  "error": {
    "code": "InvalidTemplate",
    "message": "Unable to process template language expressions for resource '/subscriptions/321cae6f-e4d3-40bf-824f-c07493a62af5/resourceGroups/acs-cluster-1/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-agentpool1-24266323-vmss' at line '1' and column '56819'. 'The template variable 'agentpool1Offset' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'"
  }
Tried adding manually the parameter (agentpool1Offset) in the parameter file, but I get an error message because that's not part of the allowed parameters.

**Comment by CecileRobertMichon** [comment]
@omartin2010 please see #3064. Please use version v0.17.0 in the meantime.

**Comment by omartin2010** [comment]
I did try using v0.17.0 and experimented another issue : 
➜ az group deployment create --name acs-cluster-1-deployment -g acs-cluster-1 --template-file ./azuredeploy.json --parameters ./azuredeploy.parameters.json
Deployment failed. Correlation ID: 365b4205-2ac2-4a54-841b-086d7b7c2706. {
  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "customData",
    "message": "Changing property 'customData' is not allowed."

So now I'm trying version 0.16.2

**Comment by CecileRobertMichon** [comment]
@omartin2010 try using a different dns prefix

**Comment by navicore** [comment]
same here, `The template variable 'agentpool1Offset' is not found.` with vmss and pre-existing vnet and v0.17.1 but works with v0.17.0.

**Comment by LaurentLesle** [comment]
I managed to get it working by using ACS-engine version 0.17.0 and kubernetes 1.10.2. I deployed the VMSS into existing vnet.
Any version greater than 0.17.0 fails with same errors as described above

**Comment by mwieczorek** [comment]
I also got this bug today when trying to deploy k8s on vmss with cluster autoscaler addon.
Unfortunately I need autoscaler addon in v1.2.2 (https://github.com/kubernetes/autoscaler/issues/881), which is in 0.17.1...so I can wait only for 0.17.2 :)

**Comment by feiskyer** [comment]
The issue has been fixed in master branch, it needs a while for next v0.17.2 release

**Comment by CecileRobertMichon** [comment]
@mwieczorek https://github.com/Azure/acs-engine/commit/893c2c090c687c235764875bd6f3e96c71fd10fc is in master, not in [0.17.1](https://github.com/Azure/acs-engine/releases/tag/v0.17.1), which only added a new k8s version and fixed a bug with extensions.

**Comment by CecileRobertMichon** [comment]
This is fixed in 0.18.x

**Comment by sshepel** [comment]
@CecileRobertMichon  not working in 0.19.2

**Comment by CecileRobertMichon** [comment]
@sshepel our tests suggest that VMSS is working on the latest acs-engine version, can you give more details regarding what exactly is not working / what error message you are getting / with what apimodel?

**Comment by CecileRobertMichon** [comment]
@sshepel this is a separate issue, you are trying to modify an existing cluster using a different  template than it was created with. You should either a) create a new cluster using a dns prefix / name b) use `acs-engine upgrade` or `scale`  if you are trying to change an existing cluster or c) re-deploy using the `az group deployment create` command but without re-generating the template file or modifying it.

**Comment by sshepel** [comment]
@CecileRobertMichon I'm sorry, I just want to provide the log error (because it was the same for me) not the command.

I faced with this problem duding executing `az group deployment create` command for updating the cluster... And looks like when cluster was deployed with `"useManagedIdentity": true` and you wan to re-deploy some node pool (for example without `"scaleSetPriority": "Low"`) the role assignment for the pool can not be updated...
