### ISSUE TITLE
openshift: failing to install insights-client on centos

### ISSUE THREAD

**Issue by jim-minter** [Azure/acs-engine#3063]
failed: [137.117.85.228] (item=insights-client) => {"attempts": 3, "changed": false, "item": "insights-client", "msg": "No package matching 'insights-client' found available, installed or updated", "rc": 126, "results": ["No package matching 'insights-client' found available, installed or updated"]}

**Comment by jim-minter** [comment]
@kwoodson please can you handle

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_azure/2

**Comment by kwoodson** [comment]
@jim-minter sure. Need to track down a repository that has this rpm.

**Comment by kwoodson** [comment]
@jim-minter,

https://github.com/openshift/openshift-ansible/pull/8504

**Comment by jim-minter** [comment]
great - please close this when it merges - thanks!

**Comment by pweil-** [comment]
@kwoodson reference PR is merged

/close
