### ISSUE TITLE
Kubernetes - Stateful Sets are not honouring Persistent Volume on Window Nodes resulting in data loss 

### ISSUE THREAD

**Issue by uday31in** [Azure/acs-engine#307]
This issue can be reproduced by adding/remove node and when pods get rescheduled on other nodes in cluster.

**Comment by anhowe** [comment]
Windows is still in preview, but thanks for reporting this and we will look at this.

**Comment by colemickens** [comment]
More importantly, no volume plugins are going to work on Windows at all. This is an upstream issue, not an ACS-Engine issue.

**Comment by colemickens** [comment]
You likely need to add OS constraints to make sure your Linux workloads land on Linux machines.

**Comment by anhowe** [comment]
you can use node selector:

nodeSelector:
  beta.kubernetes.io/os: linux
