### ISSUE TITLE
Deploy to Kubernetes does not create service principal like docs state

### ISSUE THREAD

**Issue by billpratt** [Azure/acs-engine#3076]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: HEAD

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

Service Principal is not created when running ```acs-engine deploy``` and not specifying a SP. 

```
INFO[0000] Error returned by LoadContainerService: ServicePrincipalProfile must be specified with Orchestrator Kubernetes 
FATA[0000] failed to load apimodel: %s error parsing the api model: ServicePrincipalProfile must be specified with Orchestrator Kubernetes
```

**What you expected to happen**:

According to [Deploy a Kubernetes Cluster](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md) docs it states:

```
The acs-engine deploy command automates creation of a Service Principal, Resource Group and SSH key for your cluster.
```

- Is this by designed or a bug?
- Should docs be updated?

**How to reproduce it** (as minimally and precisely as possible):

Do not fill in ```servicePrincipalProfile``` in clusterDefinition.json

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Hi @billpratt this is a known issue, please see https://github.com/Azure/acs-engine/issues/2933

**Comment by CecileRobertMichon** [comment]
Closing this issue since it's a duplicate and we are already tracking in #2933
