### ISSUE TITLE
[k8s] Question: How to set a custom DNS server

### ISSUE THREAD

**Issue by siamak-haschemi** [Azure/acs-engine#308]
Hi all,

using a custom VNET-deployment, what is the preferred way add an own DNS server for master-0 and the agents in a k8s deployment?

We could set the DNS on the VNET. But this _removes_ the provided Azure DNS server, which results in the problem that the hostnames of the master and the minions is not possible.

So we need a solution to:

* Set the DNS server during the acs template deployment
* Be able to leverage on the existing Azure DNS to be able to resolv the master/minion hostnames

Thanks.

**Comment by anhowe** [comment]
Why do you need to resolve master or node names?

**Comment by siamak-haschemi** [comment]
Hi, thanks for answering.

We have an existing HAProxy Setup in an Azure Classical Environment on a different Vnet than the k8s cluster. From within the containers running on k8s, we have to access the classical environment. This is why we need to add our own DNS server to all nodes.

To be able to resolve k8s nodes (master is not needed, right) is needed, since we want to route traffic from the classical environment to the k8s cluster. We currently work with a ngninx-based edge k8s service which is bound to a host port (>30000). We don't see any alternative. For this reason, we need to resolve the k8s nodes, since on all of them the kube-proxy will forward the call to the nginx service.

Maybe someone else has experiences on Azure with having both a classical environment, and a new acs-engine supported k8s environment. With bi-directional traffic.

**Comment by anhowe** [comment]
Close, let's reopen, if someone submits a PR, or there is more interest in customizing /etc/resolv.conf including preservation / fallback to azure dns.
