### ISSUE TITLE
[unstable] should be running the expected version

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#3086]
The aforementioned test fails in `unstable` version and we should ignore it in this case.

/label orchestrator/openshift

**Comment by kargakis** [comment]
```
• Failure [0.715 seconds]
Azure Container Cluster using the OpenShift Orchestrator
/go/src/github.com/Azure/acs-engine/test/e2e/openshift/openshift_test.go:78
  should be running the expected version [It]
  /go/src/github.com/Azure/acs-engine/test/e2e/openshift/openshift_test.go:117

  Expected
      <string>: v3.10.0
  to equal
      <string>: vunstable
```

**Comment by kargakis** [comment]
@kwoodson mind taking a look into this one? Should be an easy fix.

**Comment by kwoodson** [comment]
@kargakis, sure.  /assign

**Comment by kargakis** [comment]
@jackfrancis can @kwoodson also be added in the openshift team? Thanks

**Comment by kwoodson** [comment]
@kargakis, 

> The aforementioned test fails in unstable version and we should ignore it in this case.

Did you want to skip the test when branch is `unstable`?

**Comment by kargakis** [comment]
Yeah, when expectedVersionRationalized is `unstable` there is no reason to do the version check.

**Comment by jackfrancis** [comment]
@kargakis done
