### ISSUE TITLE
Option for tainting all nodes in an agent pool

### ISSUE THREAD

**Issue by blacksails** [Azure/acs-engine#3088]
**Is this a request for help?**:
Unsure. If this is possible already yes, otherwise no.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Depends if it is possible already

---

**What version of acs-engine?**:
0.16.2

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10.2

**Option for tainting nodes in agent pool upon creation**
My use case is this. We run a k8s cluster with a pool of worker nodes (quite small vms). I now need some bigger nodes for a resource hungry piece of software. I would like to avoid that anything but the new software gets deployed onto these new bigger nodes. Hence it would be awesome to be able to specify a node taint for an agent pool.

I am aware that it currently is possible to label nodes, but that doesn't prohibit pods from getting scheduled to the node. That is what taints are for.

I am all up for implementing this if someone could give me a quick intro to what code to look into.

**Comment by jackfrancis** [comment]
@blacksails Can you describe how you would do this manually, and we can work towards a general solution to incorporate into acs-engine at cluster creation time?

**Comment by blacksails** [comment]
@jackfrancis currently I created a new agent pool and when the nodes came up I tainted them with the taint kubectl command: `kubectl taint nodes node1 key=value:NoSchedule`

**Comment by jackfrancis** [comment]
There must be an idiomatic way to do that during runtime bootstrapping (i.e., with runtime config) so that we don't have to make a manual call against the API w/ kubectl. (Right??)

**Comment by blacksails** [comment]
Actually it might already be possible to do this by setting the `--register-with-taints` kubelet flag.

I see that the flag is on the list of non-user-configurable options here: https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md#kubeletconfig

however it says "master nodes only" in parentheses which could be interpreted as "it should work with agent pools". I will have to test in order to confirm.

**Comment by CecileRobertMichon** [comment]
@blacksails you might want to try:

```
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
         "kubernetesConfig": {
                 "kubeletConfig" : {
          "--register-with-taints": "<Insert here>"
        },
      }
]
```

That _might_ work. Right now the master nodes have a hardcoded `--register-with-taints=node-role.kubernetes.io/master=true:NoSchedule` but agents don't have any.

**Comment by blacksails** [comment]
Thanks. Closing the issue.
