### ISSUE TITLE
Write a documentation/wiki about how to create log-files and other information about the cluster for debugging

### ISSUE THREAD

**Issue by siamak-haschemi** [Azure/acs-engine#310]
Creating a cluster involves naturally many moving parts and a lot of sources for problems. I observed that the maintainers here asked on several tickets the users for log-data from their clusters.

For example, in a kubernetes setup the maintainer typically needs log files from master and minion nodes, bus also kubelet logs (and more).

What I would like to have is a wiki-page, which shows for each cluster-type how to produce/copy those log files.

In first step this can be a simple list of copy/paste commands for the console, as it hopefully helps the maintainers for > 80 % of the cases. Ideally, the maintainer can point to that wiki-page in order to get the log-data from the user. 

I am not experienced enough with github, but maybe you also can create a default template to be filled out for bugs. I remember using googlecode which had this feature.

**Comment by anhowe** [comment]
@siamak-haschemi thanks for the suggestion.  We will look deeper into this.

**Comment by anhowe** [comment]
@squillace this is a request for documentation on collecting logs.  Flagging to you to add material around this.

**Comment by jackfrancis** [comment]
I think this is a good landing place for cluster debugging information:

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/monitoring.md

It's not 100% of the way there, but it's good enough that we can start pointing people to it for basic cluster troubleshooting, and as we encounter common debugging patterns that aren't reflected in the doc, we'll add to it.
