### ISSUE TITLE
acs-engine scale creates invalid ARM Template for different storage account types

### ISSUE THREAD

**Issue by arwkmd** [Azure/acs-engine#3102]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**:

* 0.15.0
* 0.17.0
* 0.17.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

* Kubernetes 1.9.6

**What happened**:

After executing `acs-engine scale` for scaling up I get error:

```shell
validating...
Resolving tenantID for subscriptionID: XXX-YYY
Already registered for "Microsoft.Compute"
Already registered for "Microsoft.Storage"
Already registered for "Microsoft.Network"
Name suffix: %s 66686873
Starting ARM Deployment (_RESOURCE_GROUP_NAME_). This will take some time...
Finished ARM Deployment (_RESOURCE_GROUP_NAME_). Error: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code=\"DeploymentFailed\" Message=\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code=\"DeploymentFailed\" Message=\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
```

In Azure Portal in Deployments section in resource Operation Details:

```json
{
  "error": {
    "code": "StorageAccountTypeConversionNotAllowed",
    "message": "Storage account type cannot be changed to Standard_LRS."
  }
}
Resource: 00bbkzqrfgx7l2gagnt0
```

**What you expected to happen**:

Scaling up

**How to reproduce it** (as minimally and precisely as possible):

There are two agent pool profiles:

| Pool name | VM Size               | Storage account type |
|-------------|--------------------|-------------------------|
| frontend    | Standard_E4s_v3  | Premium_LRS             |
| backend    | Standard_D4_v3   | Standard_LRS              |

**azuredeploy.json** generated by `acs-engine generate` contains:

```json
"frontendAccountName": "[concat(variables('storageAccountBaseName'), 'agnt0')]",
"backendAccountName": "[concat(variables('storageAccountBaseName'), 'agnt1')]"
```

ARM Template sent to Azure by `acs-engine scale` for backend contains only (there is no information about frontend)

```json
"backendAccountName": "[concat(variables('storageAccountBaseName'), 'agnt0')]"
```

Please pay attention to end of the storage account. It should be `agnt1` not `agnt0`. For this reason Azure tries to create in **Premium** fronted storage account for **Standard** vhd osdisks for backend agent pool.

**Comment by ralbon** [comment]
Exact same issue with : 
- Acs-engine 16.2
- Kubernetes 1.9.6
- VmSize : Standard_E4s_v3 (Premium_LRS) and Standard_D2_v2 (Standard_LRS)

Hopefully, we can still scale up vertically our nodes (for the moment :) )

Please let me know if you need more information.
@d-matt @ yastij

**Comment by BrendanThompson** [comment]
I am getting something similar:

```
{
  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "dataDisk.createOption",
    "message": "Changing property 'dataDisk.createOption' is not allowed."
  }
}
```

Its preventing us from scaling the cluster. Upgrading `k8s` worked perfectly though `acs-engine` though I must say!

**Comment by okke-formsma** [comment]
We are unfortunately running into the same problem. Any workarounds/solutions? 

I'm considering deploying a new agentpool when we have to scale up, as that does not run into this issue

**Comment by arwkmd** [comment]
Almost six months have passed since the issue. Are there any plans related to this error?
