### ISSUE TITLE
Enable cgroups memory and swap accounting 

### ISSUE THREAD

**Issue by tomconte** [Azure/acs-engine#3107]
**Is this a request for help?**: No

**Is this an ISSUE or FEATURE REQUEST?** FEATURE REQUEST

**What version of acs-engine?**: canary

Docker recommends [enabling cgroups memory and swap accounting](https://docs.docker.com/install/linux/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities) in the kernel to allow Docker to fully manage memory constraints. This is not the case on Ubuntu by default.

These settings are required by some Kubernetes-based platforms, for example SUSE Cloud Application Platform (CAP).

The steps needed to enable memory and swap accounting are:

1. Modify the kernel boot parameters, adding `cgroup_enable=memory swapaccount=1`

e.g. in the file `/etc/default/grub.d/50-cloudimg-settings.cfg`, the following line:

`GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 earlyprintk=ttyS0 rootdelay=300"`

becomes:

`GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 earlyprintk=ttyS0 rootdelay=300 cgroup_enable=memory swapaccount=1"`

2. Run `sudo update-grub`

3. reboot the Virtual Machine
    
It would be great to have an option for `acs-engine` to automatically apply this configuration.

**Comment by tomconte** [comment]
Note: the steps above don't seem to work anymore. See https://github.com/Azure/AKS/issues/412.

**Comment by svollath** [comment]
As noted [here](https://github.com/Azure/AKS/issues/412), it works for me again in AKS with Kubernetes 1.9.9.
JFYI, here's a more safe way to add "swapaccount=1":

```
> az vm run-command invoke -g <RGNAME> -n <VMNAME> --command-id RunShellScript --scripts "sudo sed -i -r 's|^(GRUB_CMDLINE_LINUX_DEFAULT=)\"(.*.)\"|\1\"\2 swapaccount=1\"|' /etc/default/grub.d/50-cloudimg-settings.cfg"

> az vm run-command invoke -g <RGNAME> -n <VMNAME> --command-id RunShellScript --scripts "sudo update-grub"

> az vm restart -g <RGNAME> -n <VMNAME>
```
