### ISSUE TITLE
Stamp git information into the binary

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#311]
We already prescribe that people should be building in Docker. I think we should go all-in on requiring this to be built under Linux, using the Makefile.

In the Makefile, we can stamp information about the current git state into the binary. Then `acs-engine --version` can return the git revision it was built with.

Further, once this PR is in (https://github.com/Azure/acs-engine/pull/253) git workspaces won't get dirty from just regenerating (unless there are real changes) so we can just trust the dirty/clean bit to know if they had local changes.

This is probably preferrable to having to guess: "What version are you on? Are you absolutely sure you rebuilt? Did you also re-generate?" etc...

**Comment by colemickens** [comment]
See #356 for an example of the wrapper script. It might be time to introduce a `build/` or `hack/` directory and put such a script there. And then maybe the Makefile just shells out for everything, and we keep the Makefile as an easy entry point and for tab completion.

**Comment by anhowe** [comment]
@raveeram fixed this in #412
