### ISSUE TITLE
VNET peering docs: overlapping IP CIDR blocks not allowed

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#3139]
This is a general Azure networking gotcha, but worth adding to docs: if you're building a cluster in a VNET that is peered with other VNETs, ensure that all VNET IP address space CIDR blocks are distinct, and have no overlapping IP ranges.

**Comment by diwakar-s-maurya** [comment]
Azure portal starts giving the warning for overlapping subnets even before vnet creation or doing actual peering.
Example: We already have a k8s cluster with vnet address space 10.0.0.0/8. If I just try to create a vnet using portal, it starts giving the warning for overlap.

![image](https://user-images.githubusercontent.com/10303889/40872519-84fdea90-6675-11e8-96fb-6aa6ebd0a00b.png)

The following screenshot shows vnet of our dev k8s cluster showing warning of overlap from qa k8s cluster even though they are not peered. I think its harmless and its a problem in azure portal.

![image](https://user-images.githubusercontent.com/10303889/40872562-5ef48c7c-6676-11e8-9b93-7733cf903e98.png)

The accepted answer at https://stackoverflow.com/questions/45836574/the-address-space-10-0-0-0-16-overlaps-with-10-0-0-0-16-in-virtual-network also says the same thing.

**Comment by VipinAgarwal** [comment]
I have the same scenario, I have overlapped CIDR from two VNets which are in two different subscriptions. Now I cannot peer this VNET's..
