### ISSUE TITLE
KubeDNS internal on windows nodes is not resolving correctly 

### ISSUE THREAD

**Issue by beaudryj** [Azure/acs-engine#3143]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: 28eb1d106e17281eab2753464a60ceafa1b85ea1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes 1.10.2

**What happened**: My windows nodes are not able to DNS resolve the Service they need to access

**What you expected to happen**: I expect my IIS node to be able to resolve the Service of my MSSql Deployment

**How to reproduce it** (as minimally and precisely as possible): Run a cluster with an IIS node and have it try to DNS resolve a Kube Service

**Anything else we need to know**:
```json
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.10",
        "kubernetesConfig": {
          "enableRbac": true,
          "apiServerConfig" : {
            "--feature-gates": "HyperVContainer=true"
          },
          "kubeletConfig" : {
            "--feature-gates": "HyperVContainer=true"
           }
        }
      },
      "aadProfile": {
        "serverAppID":  "",
        "clientAppID":  "",
        "tenantID":  "",
        "adminGroupID":  ""
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "ebk8s",
        "vmSize": "Standard_F2s_v2"
      },
      "agentPoolProfiles": [
        {
          "name": "linuxpool1",
          "count": 2,
          "vmSize": "Standard_F4s_v2",
          "availabilityProfile": "VirtualMachineScaleSets",
          "storageProfile": "ManagedDisks",
          "OSDiskSizeGB": 256
        },
        {
          "name": "windowspool2",
          "count": 2,
          "vmSize": "Standard_F4s_v2",
          "availabilityProfile": "VirtualMachineScaleSets",
          "storageProfile": "ManagedDisks",
          "OSDiskSizeGB": 256,
          "osType": "Windows"
        }
      ],
      "windowsProfile": {
        "adminUsername": "",
        "adminPassword": ""      },
      "linuxProfile": {
        "adminUsername": "",
        "ssh": {
          "publicKeys": [
            {
              "keyData":  ""
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId":  "",
        "secret":  ""
      }
    }
  }
```

![image](https://user-images.githubusercontent.com/2633564/40861494-46291092-65b7-11e8-8c96-3ca7c87edac1.png)

I did notice that it resolves however when your force NS lookup to use the kube-dns ip

I also spent some time with @khenidak to validate that the Kube-DNS was working as Intended

**Comment by ariellapinin** [comment]
+1
I'm getting the exact same issue using windows version 1709

any resolution for this??

**Comment by sharmasushant** [comment]
@beaudryj @ariellapinin This is happening because windows DNS is not falling back to the secondary DNS for name resolution. While it is getting investigated/fixed by windows team, we have made kube dns as the primary dns server in Azure CNI. We plan to release the new version tomorrow and update ACS engine with the new version of CNI. We have tested that the above behavior does not repro with the newer version. Here is the PR that fixed this: https://github.com/Azure/azure-container-networking/pull/155

**Comment by liorchen** [comment]
Hi

I see that there was a new RC a few hours ago but the CNI version is still 1.0.4. the fix is at 1.06..
can someone plz create a new release with the new CNI?

Thanks

**Comment by PatrickLang** [comment]
I think 2 fixes are needed. https://github.com/Azure/acs-engine/pull/3104 is the first one which was merged and is in https://github.com/Azure/acs-engine/tree/v0.18.0

Looking for the 2nd PR

**Comment by CecileRobertMichon** [comment]
#3180 is open to update the CNI version

**Comment by beaudryj** [comment]
❤

**Comment by PatrickLang** [comment]
We reverted to Azure CNI 1.0.4, so reopening.

**Comment by daschott** [comment]
@beaudryj With acs-engine v0.19.2 onwards, this should work (at least for the default namespace). For non-default namespace, you need to continue to use FQDN.
