### ISSUE TITLE
package socat and ebtables not found

### ISSUE THREAD

**Issue by aminebizid** [Azure/acs-engine#3149]
I think sudo apt-get update is missing :

Reading package lists...
Building dependency tree...
Reading state information...
Package ebtables is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package socat is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'socat' has no installation candidate
E: Package 'ebtables' has no installation candidate

**Comment by CecileRobertMichon** [comment]
@aminebizid is this output from cluster deployment logs?

**Comment by aminebizid** [comment]
Yes
To resolve this I ssh master before extensions deploy and run apt-get update

Cordialement,
Amine BIZID

**Comment by andyzhangx** [comment]
@aminebizid PR: https://github.com/Azure/acs-engine/pull/3179 fixed this issue

**Comment by malachma** [comment]
Just a comment: the update operation should actually always be the first operation if a new package needs to be added/installed. As only the update task ensure a resynchronization of the package index files from their sources.
