### ISSUE TITLE
CSE error: exit code 30

### ISSUE THREAD

**Issue by flyboarder** [Azure/acs-engine#3151]
**Is this a request for help?**:
---
YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**What version of acs-engine?**:
---
0.17.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Master CSE 0 fails to deploy

**What you expected to happen**:
Master CSE 0 is successful

**How to reproduce it** (as minimally and precisely as possible):
Deploy fresh cluster with v0.17.0 using kubernetes sample.

**My ApiModel**
Using the following apimodel, with prefix and sshkey removed.
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "...",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "count": 1,
        "name": "pool1",
        "vmSize": "Standard_D2_v2"
      }
    ],
    "linuxProfile": {
      "adminUsername": "admin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "..."
          }
        ]
      }
    }
  }
}

```
**My Logs**
end of `/var/log/azure/cluster-provision.log`
```
+ retrycmd_if_failure 100 1 20 /usr/local/bin/kubectl cluster-info
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Executed "/usr/local/bin/kubectl cluster-info" 100 times
+ exit 30
```

end of `/var/log/cloud-init-output.log`
```
Processing triggers for libc-bin (2.23-0ubuntu10) ...
+ timeout 10 apt-mark hold walinuxagent
walinuxagent set on hold.
+ timeout 10 apt-mark unhold walinuxagent
Canceled hold on walinuxagent.
+ mkdir -p /var/log/azure
+ touch /var/log/azure/cloud-init.complete
Cloud-init v. 18.2 running 'modules:final' at Sun, 03 Jun 2018 03:43:24 +0000. Up 36.41 seconds.
Cloud-init v. 18.2 finished at Sun, 03 Jun 2018 03:43:45 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 57.30 seconds
```

**Comment by flyboarder** [comment]
Additionally there is the [error code](https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetescustomscript.sh#L23) doc.

**Comment by CecileRobertMichon** [comment]
@flyboarder were you able to repro this issue? I'm able to deploy a cluster with the same apimodel as you...

**Comment by flyboarder** [comment]
@CecileRobertMichon just attempted another deployment, still fails with the same error, this is using the canadacentral azure region. Our build ran 17 times over the weekend attempting to pass, same error every time.

**Comment by CecileRobertMichon** [comment]
Ok something is going on then... I'll try to repro / debug this today

**Comment by flyboarder** [comment]
@CecileRobertMichon I just attempted with canadaeast region as well, same issue. Looks like acs-engine doesn't like canada :/

**Comment by CecileRobertMichon** [comment]
@flyboarder what do you see when you run `kubectl get nodes`? Did the other two master extensions deploy successfully?

**Comment by flyboarder** [comment]
@CecileRobertMichon once I ssh into the master, any kubectl commands hang.

**Comment by CecileRobertMichon** [comment]
Also did you actually use `adminUsername` "admin"? When I deploy with your apimodel I get ```  "error": {
    "code": "InvalidParameter",
    "target": "adminUsername",
    "message": "The Admin Username specified is not allowed."
  }```

**Comment by flyboarder** [comment]
@CecileRobertMichon no, my admin user is the company name all lowercase, here are my resources from azure:
<img width="915" alt="screen shot 2018-06-04 at 11 58 21 am" src="https://user-images.githubusercontent.com/147004/40933484-d1ce2b6c-67ee-11e8-9b2a-ca8b3c484e85.png">

**Comment by flyboarder** [comment]
@CecileRobertMichon `kubectl get nodes`, eventually resulted in `Unable to connect to the server: dial tcp 13.71.184.45:443: i/o timeout`

**Comment by flyboarder** [comment]
@CecileRobertMichon seems I posted our prod apimodel, I have updated it to reflect the node count of the dev apimodel, which is 1 master and 1 pool-node

**Comment by CecileRobertMichon** [comment]
So my deployment in canadacentral just succeeded... Using acs-engine v0.17.0, exact same apimodel as you except `azureuser` as `adminUsername`

**Comment by CecileRobertMichon** [comment]
> @CecileRobertMichon seems I posted our prod apimodel, I have updated it to reflect the node count of the dev apimodel, which is 1 master and 1 pool-node

aah let me try with 1 master then. Did you change anything at all in the generated azuredeploy json?

**Comment by flyboarder** [comment]
@CecileRobertMichon no changes to `azuredeploy.json`, we are using an acs-engine image built from the dockerfile in releases folder with version pinned to `0.17.0`, then deploying via azure cli on VSTS from our cluster config repo.

**Comment by CecileRobertMichon** [comment]
@flyboarder any reason you're setting the agentpool count to 1? It looks like that might be the issue

**Comment by flyboarder** [comment]
@CecileRobertMichon the low agentpool count was to reduce costs for the dev environment, I will reattempt with 1 master and 3 nodes

**Comment by flyboarder** [comment]
@CecileRobertMichon I believe this is being caused by the master cse timing out before the vmss is deployed.

**Comment by flyboarder** [comment]
Now getting an `error code 9` on vmssCSE
```
VM has reported a failure when processing extension 'vmssCSE'. Error message: "Enable failed: failed to execute command: command terminated with exit status=9 [stdout] [stderr] ".
```

**Comment by flyboarder** [comment]
@CecileRobertMichon I did a manual deployment using acs-engine built from master branch, this deployed without issue. I will have to wait for `0.17.2` before turning CD back on.

**Comment by flyboarder** [comment]
I don't know if this is relevant, however using `0.18.0` I can almost always deploy from my laptop, using VSTS the deployment fails every time.

**Comment by CecileRobertMichon** [comment]
@flyboarder definitely relevant, thanks for the update... We are investigating

**Comment by CecileRobertMichon** [comment]
@flyboarder I just noticed that the `ServicePrincipalProfile` is missing from you apimodel, are passing that in somehow? could you double check that it is correct and has the right permissions?

**Comment by flyboarder** [comment]
Yes, we are passing that in via BUILD ARGS:
```
SERVICE_PRINCIPAL_CLIENT_ID=$SERVICE_PRINCIPAL_CLIENT_ID
SERVICE_PRINCIPAL_SECRET=$SERVICE_PRINCIPAL_SECRET
ACS_SSH_PUBLIC=$ACS_SSH_PUBLIC
ACS_CLUSTER_ENV=dev
```

To this docker file (using the SSH PublicKey fails in VSTS when passed as an argument, so it's apart of our api model file, this is also not an issue when deployed from my laptop):
```
# ...blah blah prep image blah...
# Generate Cluster Definitions
RUN acs-engine generate \
 --api-model $ACS_API_MODEL \
 --set servicePrincipalProfile.clientID=${SERVICE_PRINCIPAL_CLIENT_ID} \
 --set servicePrincipalProfile.secret=${SERVICE_PRINCIPAL_SECRET} \
 --output-directory ${ACS_CLUSTER_ENV}
```

Then we deploy with `az` command (with company data replaced):
```
az group create \
     --name "example-dev" \
     --location "canadacentral"

az group deployment create \
    --name "example-dev" \
    --resource-group "example-dev" \
    --template-file "./output/dev/azuredeploy.json" \
    --parameters "./output/dev/azuredeploy.parameters.json"
```

**Comment by flyboarder** [comment]
@CecileRobertMichon to summarize the issues experience:
- Setting `linuxProfile.ssh.publicKeys[0].keyData` via RUN command in Dockerfile fails on VSTS, passes when used locally
- Using the `az group deployment create` command above fails on VSTS, passes when used locally

**Comment by flyboarder** [comment]
This has effectively prevented us from using VSTS Build/Release workflow for our acs-engine based cluster. Have had to do manual deployments this week. This is all with a fresh cluster, nothing customized outside of api model file and nothing changed within auredeploy files.

**Comment by CecileRobertMichon** [comment]
The `--set` command was only recently added to acs-engine... what were you using before?

Are you saying that ```RUN acs-engine generate \
 --api-model $ACS_API_MODEL \
 --set servicePrincipalProfile.clientID=${SERVICE_PRINCIPAL_CLIENT_ID} \
 --set servicePrincipalProfile.secret=${SERVICE_PRINCIPAL_SECRET} \
 --output-directory ${ACS_CLUSTER_ENV}```

works locally but not on VSTS? what is the resulting output apimodel on VSTS?

**Comment by CecileRobertMichon** [comment]
@jcorioland could you please confirm that the above command is valid?

**Comment by jcorioland** [comment]
@CecileRobertMichon @flyboarder the command above looks valid, yes - and especially if it works locally but not on VSTS. Let me try to repro the issue using Dockerfile/VSTS...

**Comment by jcorioland** [comment]
@flyboarder @CecileRobertMichon OK, I think I was able to repro. 

*Summary: it's not an ACS-Engine issue, but the way you are using variable in VSTS.*

*Full explanation:*

I assume that you are using VSTS variables to pass the environment variable to the Docker container, and that you also use "VST secret variables" for ssh-key, client id and secret. When using secret variable, I received this:

```
Error returned by LoadContainerService: json: cannot unmarshal number into Go struct field PublicKey.keyData of type string 
```

It is not an acs-engine issue, it is just that secret variable are not shared with tasks and scripts (see: https://github.com/Microsoft/vsts-agent/issues/145)

If you do not use secret variables without changing anything to your build definition, I think it would work. But it's not the best solution, as you may want to continue to use secret variable, obviously.

I think you need to use a custom shell script to run the acs-engine command, instead of using it in a RUN Dockerfile instruction at build time. Doing that, you will be able to pass secret variables to your script as explained in the issue linked above.

I wrote a [basic sample here](https://github.com/jcorioland/vsts-acsengine) to repro / understand your issue, maybe it will help you to fix your build problem.
You just need two vsts tasks to run it:
- one to build the Dockerfile
- one to run the `docker-run.sh` script (that need to be updated to takes arguments instead of using env vars directly)

Hope this helps

**Comment by flyboarder** [comment]
@jcorioland we are getting the same error as you without using secret variables, however that only solves one issue. We are currently using this method for the clientID and Secret without problems, only affects the SSH variable. (screenshot attached)

<img width="829" alt="screen shot 2018-06-07 at 10 09 10 am" src="https://user-images.githubusercontent.com/147004/41112009-e9094660-6a3a-11e8-888f-9c32de57918d.png">

However this doesn't touch on the primary issue of any deployments submitted via VSTS agent failing, when they work locally, it still seems like whenever VSTS deploys the masterCSE0 times out before the vmss has completed.

@CecileRobertMichon I will attempt to pull out the apimodel from the build image and compare it to the successful apimodel we used for the manual deployment.

**Comment by CecileRobertMichon** [comment]
Thank you for investigating @jcorioland! @flyboarder please let me know what you find out.

**Comment by jcorioland** [comment]
@flyboarder did you try to hardcode the ssh key in the apimodel file? At first, I only had the error for the SSH key and once corrected, it comes to the client id, then client secret. The validation breaks at the first unmarshalling error (this is maybe something we can improve @CecileRobertMichon, btw).

Using only non-secret variables, I was able to generate the ARM template during a VSTS build. I will try to develop from inside the containers during the build to see if I repro the masterCSE0 timeout.

**Comment by jcorioland** [comment]
@flyboarder weird. Can you try to surround the environment variable with double quote in your build arguments, like:
```
ACS_SSH_PUBLIC="${ACS_SSH_PUBLIC}"
``` 
Does this change? I remember had to do that in [this script](https://github.com/jcorioland/vsts-acsengine/blob/f7fe62ea933fefb6fa8a81779f2d7e4b2ea7096d/docker-run.sh#L9) to solve the issue.

**Comment by flyboarder** [comment]
@CecileRobertMichon I believe I found the culprit! Thanks to @jcorioland once I got into the VSTS docker container I found the clientID and Secret are not set correctly. I believe this is causing the vmss to fail deployment and therefore causing masterCSE to timeout. This could be solved by checking the format of clientID and Secret instead of just type checking them, allowing any string doesn't really help. I will post the results of my testing using the suggestion from @jcorioland above.

**Comment by CecileRobertMichon** [comment]
Glad to hear you found the problem! I agree that there is a lack of validation for the Service Principal right now, there is an issue to enforce stricter validation open at https://github.com/Azure/acs-engine/issues/3039, it's a just a matter of someone taking the time to implement it and we haven't been able to get to it yet because of other higher priority tasks.

**Comment by flyboarder** [comment]
@jcorioland no I am using the az cli VSTS task. Here are some screen shots of my build/release tasks.
Build:
<img width="567" alt="screen shot 2018-06-07 at 11 25 57 am" src="https://user-images.githubusercontent.com/147004/41115727-9c37356c-6a45-11e8-91b3-122b68b35386.png">
Release:
<img width="571" alt="screen shot 2018-06-07 at 11 27 48 am" src="https://user-images.githubusercontent.com/147004/41115810-d73229ec-6a45-11e8-9200-25cb13c56de9.png">

**Comment by jcorioland** [comment]
@flyboarder ok, makes sense! This is why you can start the deployment. Let us know if it works when you manage to deal with the service principal inside the container.

**Comment by diwakar-s-maurya** [comment]
I am trying to create v1.10.1 kubernetes cluster in southeastasia region with acs-engine v0.18.3. I am providing servicePrincipalProfile variables directly from .json file. It has failed continuously 3 times back to back with same logs and exit code except this line.

```bash
Executed "/usr/local/bin/kubectl cluster-info" 600 times
```

This is my template.json file for cluster creation
```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10",
      "orchestratorVersion": "1.10.1",
      "kubernetesConfig": {
        "maxPods": 110,
        "enableRbac": true,
        "networkPlugin": "flannel",
        "enableAggregatedAPIs": true,
        "controllerManagerConfig": {
          "--horizontal-pod-autoscaler-use-rest-clients": "true"
        },
        "apiServerConfig": {
          "--enable-aggregator-routing": "true",
          "--admission-control": "NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,ResourceQuota,DenyEscalatingExec,AlwaysPullImages"
        },
        "addons": [
          {
            "name": "tiller",
            "enabled": false
          },
          {
            "name": "kubernetes-dashboard",
            "enabled": false
          }
        ],
        "kubeletConfig": {
          "--cadvisor-port": "4194",
          "--max-pods": "110"
        }
      }
    },
    "masterProfile": {
      "count": 3,
      "vmSize": "Standard_B4ms"
    },
    "agentPoolProfiles": [
      {
        "name": "worker",
        "count": 1,
        "vmSize": "Standard_B4ms"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "---"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "---",
      "secret": "---"
    },
    "aadProfile": {
      "serverAppID": "---",
      "clientAppID": "---",
      "tenantID": "---"
    }
  }
}
```

**Comment by diwakar-s-maurya** [comment]
The cluster got created in 9th or 10th try 😞

**Comment by CecileRobertMichon** [comment]
@diwakar-s-maurya sorry to hear that, did you change anything to get it to work?

**Comment by diwakar-s-maurya** [comment]
No

**Comment by CecileRobertMichon** [comment]
Ok, I'll try to repro

**Comment by CecileRobertMichon** [comment]
I'm wondering if this because you're using B series VMs @diwakar-s-maurya, haven't been able to repro this with D2_v2. I'll try with B4ms (we've seen issues with acs-engine and B series where the VM ran out of memory during the installation but that was mostly B1s and B2s)

**Comment by CecileRobertMichon** [comment]
@diwakar-s-maurya I get `time="2018-06-12T21:27:17Z" level=info msg="Error returned by LoadContainerService: VirtualMachineScaleSets with instance metadata is supported for Kubernetes version 1.10.2 or greater. Please set \"useInstanceMetadata\": false in \"kubernetesConfig\" or set \"orchestratorVersion\" to 1.10.2 or above"` when I try to deploy your apimodel on 0.18.3, can you please share the exact apimodel you used?

**Comment by flyboarder** [comment]
@CecileRobertMichon I was able to confirm the env vars are passed to the generate command correctly, however the ssh key breaks at the end just before the email and drops a few characters, this is again deployed from VSTS

**Comment by flyboarder** [comment]
@jcorioland Do you have any suggestion for fixing the truncating of the ssh env var?
I have a line in my Dockerfile that prints the env vars, so I know that it is passed to the build correctly. However the ending `== email@example.com` part is being removed from the generated apimodel.
