### ISSUE TITLE
Can not scale down Kubernetes VM

### ISSUE THREAD

**Issue by Novitoll** [Azure/acs-engine#3158]
**Is this a request for help?**:
Yes, no documentation provided.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST maybe?

---

**What version of acs-engine?**:
0.13.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compil
er:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compil
er:"gc", Platform:"linux/amd64"}
```

**What happened**:
Can scale-up VM, but can not scale-down.

**What you expected to happen**:
VM counts of specific agentpool should be decreased (VMs should be deleted)

**How to reproduce it** (as minimally and precisely as possible):
According to this README, https://github.com/Azure/acs-engine/tree/master/examples/scale-up, I can scale up by adding in params, so that I will scale agent pool from 1 to 2 VMs. 
```
  "parameters": {
    "agentpool1Count": {
      "value": 2
    },
    "agentpool1Offset": {
      "value": 1
    },
```

Logically, if I want to scale down back to 1 VM from 2, when I do this

```
  "parameters": {
    "agentpool1Count": {
      "value": 1
    },
    "agentpool1Offset": {
      "value": 2
    },
```
it gives the error 

> Deployment template validation failed: 'The template 'copy' definition at line '1' and column '121455' has an invalid copy count. The copy count must be a postive integer value and cannot exceed '800'. Please see https://aka.ms/arm-copy for usage details.'.

I checked ARM template, we do `"count": "[sub(variables('agentpool1Count'), variables('agentpool1Offset'))]",`,
Thus, I tried to set **count = 1** and **offset = 1** OR *offset = 0* -- it didnt help as well.

**Comment by CecileRobertMichon** [comment]
@Novitoll have you tried using `acs-engine scale`? https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/scale.md

**Comment by Novitoll** [comment]
Thanks! setting the desired count of VMs in `acs-engine scale` scaled down the agentpool. Closing this issue.
