### ISSUE TITLE
When ginkgo timeouts, artifacts are not gathered

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#3171]
Observed this in a couple of different suites (both k8s and openshift)

https://circleci.com/gh/Azure/acs-engine/30298?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
test.mk:26: recipe for target 'test-kubernetes' failed
make: *** [test-kubernetes] Terminated
Too long with no output (exceeded 30m0s)
```

@jackfrancis @CecileRobertMichon @mjudeikis if you want to have a look

**Comment by kargakis** [comment]
https://circleci.com/gh/Azure/acs-engine/30340?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by CecileRobertMichon** [comment]
I've seen quite a few of those. My assumption was that circle was getting stuck...
