### ISSUE TITLE
Don't create data disk for etcd

### ISSUE THREAD

**Issue by heltondd** [Azure/acs-engine#3178]
**Is this a request for help?**:
help
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.18.0
---

JSON parameters 
...
    "masterProfile": {
      "count": 1,
      "imageReference": {
        "name": "ubuntu-16-04-custom",
        "resourceGroup": "my-images"
      },
      "dnsPrefix": "k8s-acs",
      "vmSize": "Standard_D2s_v3",
      "vnetSubnetId": "xxxx",
      "firstConsecutiveStaticIP": "xxxx"
    },
...

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes 1.10.2

**What happened**:
acs-engine does not generate azuredeploy.json with data disk information on master storageprofile for etcd when using custom image.

**What you expected to happen**:
Create data disk on master storageprofile for etcd when using custom image.

azuredeploy.json
"storageProfile": {
         "dataDisks": [
           {
             "createOption": "Empty",
             "diskSizeGB": "[variables('etcdDiskSizeGB')]",
             "lun": 0,
             "name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'-etcddisk')]"
           }
         ],

**How to reproduce it** (as minimally and precisely as possible):
generate ARM template using custom image
...
    "masterProfile": {
      "count": 1,
      "imageReference": {
        "name": "custom_image",
        "resourceGroup": "rg_custom_image"
      },
      "dnsPrefix": "k8s-acs",
      "vmSize": "Standard_D2s_v3",
      "vnetSubnetId": "xxxx",
      "firstConsecutiveStaticIP": "xxxx"
    },

**Anything else we need to know**:

**Comment by kargakis** [comment]
I don't think it's possible to attach disks to custom images.
