### ISSUE TITLE
enableEncryptionWithExternalKms needs to set permissions on the KeyVault created 

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/acs-engine#3182]
The following flag(s) need to be set when creating a KeyVault to enable ARM to retrieve the secrets:

--enabled-for-template-deployment
--enabled-for-deployment (?)

**Comment by CecileRobertMichon** [comment]
FYI @seanknox @ritazh

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/blob/2012c1c12919cb5baf4585cd861baddbfe68c54a/parts/k8s/kubernetesmasterresources.t#L810

**Comment by ritazh** [comment]
Permission set for SP on the created key vault has been implemented in acs-engine. I was not able to repro this... @seanknox will try again and let us know 😄

**Comment by CecileRobertMichon** [comment]
@seanknox do we still need this?

**Comment by seanknox** [comment]
No we can close. Turned out to be a red herring.
