### ISSUE TITLE
Cannot access provisioned Kubernetes Cluster

### ISSUE THREAD

**Issue by DonMartin76** [Azure/acs-engine#320]
## Problem description

I am starting to believe I am a little stupid here, but I have the same effect as described in #175, e.g. after the cluster has been provisioned, I cannot connect to it:

```
$ kubectl --kubeconfig=./kubeconfig get nodes
Unable to connect to the server: dial tcp: i/o timeout
```

## How to reproduce

This is the script I am currently writing to provision a Kubernetes cluster from a Jenkins pipeline (for automatic performance testing):

```bash
#!/bin/bash

set -e

if [ -z "$SUBSCRIPTION_ID" ]; then
    echo "ERROR: The env var SUBSCRIPTION_ID must be set."
    exit 1
fi

if [ -z "$SP_APPID" ] || [ -z "$SP_PASSWORD" ] || [ -z "$SP_TENANTID" ]; then
    echo "ERROR: Environment variables SP_APPID, SP_PASSWORD and SP_TENANTID"
    echo "must be set prior to calling this script. Exiting."
    # Using an owner on an account, create a service principal with this:
    # az ad sp create-for-rbac --role="Owner" --scopes="/subscriptions/$SUBSCRIPTION_ID"
    exit 1
fi

if [ -z "$LOCATION" ]; then
    export LOCATION=northeurope
    echo "Using default location $LOCATION."
fi
if [ -z "$K8S_NAME" ]; then
    export K8S_NAME=$RESOURCE_GROUP
    echo "Using default cluster name $K8S_NAME."
fi
if [ -z "$K8S_DNSPREFIX" ]; then
    export K8S_DNSPREFIX=$RESOURCE_GROUP
    echo "Using default DNS prefix $K8S_DNSPREFIX"
fi
if [ -z "$SSH_KEY_FILE" ]; then
    export SSH_KEY_FILE="~/.ssh/id_rsa.pub"
    echo "Using default SSH key file $SSH_KEY_FILE"
fi
if [ -z "$K8S_MASTER_COUNT" ]; then
    export K8S_MASTER_COUNT=1
    echo "Using default Master count $K8S_MASTER_COUNT."
fi
if [ -z "$K8S_AGENT_COUNT" ]; then
    export K8S_AGENT_COUNT=1
    echo "Using default Agent count $K8S_AGENT_COUNT."
fi
if [ -z "$K8S_AGENT_VMSIZE" ]; then
    export K8S_AGENT_VMSIZE="Standard_D2_v2"
    echo "Using default Agent VM Size $K8S_AGENT_VMSIZE"
fi
if [ -z "$K8S_ADMIN_USERNAME" ]; then
    export K8S_ADMIN_USERNAME=azureuser
    echo "Using default Kubernetes Admin username $K8S_ADMIN_USERNAME"
fi

echo "Using location: $LOCATION"

echo "Logging in using the service principal..."
# Comment this line to use the current login context:
az login --service-principal -u $SP_APPID -p $SP_PASSWORD --tenant $SP_TENANTID

echo "Creating Resource Group..."
az group create --name "$RESOURCE_GROUP" --location "$LOCATION"

echo "Provisioning Kubernetes Cluster..."

az acs create \
    --orchestrator-type Kubernetes \
    --location $LOCATION \
    --name $RESOURCE_GROUP \
    --resource-group $RESOURCE_GROUP \
    --admin-username $K8S_ADMIN_USERNAME \
    --ssh-key-value $SSH_KEY_FILE \
    --agent-count $K8S_AGENT_COUNT \
    --master-count $K8S_MASTER_COUNT \
    --agent-vm-size $K8S_AGENT_VMSIZE \
    --service-principal $SP_APPID \
    --client-secret $SP_PASSWORD
# comment last two lines to let az acs create its own service principal

if [ -f "./kubeconfig" ]; then
    echo "Removing old kubeconfig"
    rm -rf ./kubeconfig
fi
echo "Retrieve kubeconfig..."

az acs kubernetes get-credentials \
    --name $RESOURCE_GROUP \
    --resource-group $RESOURCE_GROUP \
    --ssh-key-file $SSH_KEY_FILE \
    --file ./kubeconfig

echo "Checking k8s connectivity..."

kubectl --kubeconfig=./kubeconfig get nodes
```

You will need to set a service principal `appId` in `SP_APPID`, the corresponding password in `SP_PASSWORD`, and the tenant id in `SP_TENANTID`. You will also need to specify a `SUBSCRIPTION_ID` and a `RESOURCE_GROUP` name, and then you should be good to go.

What I also tried was interactively issuing the commands to get the cluster up and running, after having logged in as my own user (on a subscription for my MSDN account). I get the same behaviour there, even if I let `az acs create` provision its own service principal:

```
Provisioning Kubernetes Cluster...
creating service principal.........done
waiting for AAD role to propagate.done
```

This can be done by commenting the `az login --service-principal` line after you have logged in as your own user (not being logged in as a service principal). It still doesn't work.

I checked with this section: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md#misconfigured-service-principal, but that does not render any error messages (empty result). What am I doing wrong? I know I had this problem before, but managed to resolve it (with the help of an MS supporter). But I can't recall what he did to fix it (and it was two months ago).

## Environment

* `az acs`: 0.1.2rc2 (seems to be current)
* Using my MSDN account
* macOS 10.12 (should totally not matter, I would think)

**Comment by DonMartin76** [comment]
Now I feel even more stupid: I just tried it again, and now it effing works. No changes. With the Service Principal I created using `az ad sp create-for-rbac`. What can have gone wrong here?

**Comment by colemickens** [comment]
@DonMartin76 Two ideas:

1. You were using cached SP creds before that were for some reason bad (the CLI tries to cache them whenever it creates them automatically). But it sounds unlikely since I can see your script also was written to manually do the sp creation...

2. You were unlucky with timing. The deployment doesn't technically wait for the Kubernetes control plane to come up. Depending on lots of factors, the Kubernetes apiserver may not be reachable for another minute or two after the deployment completes.

**Comment by DonMartin76** [comment]
@colemickens Thanks! I have a third thing I need to check: Which ports does `kubectl` use for communicating with the cluster? I was assuming it only needs 443 (`https`), is this correct? Otherwise traffic might be blocked by our corporate firewall. It worked from home, need to test again with a known working cluster whether the problem is reproducible from within the corporate network.

**Comment by colemickens** [comment]
Yes, all communication is over HTTPS on port 443.

**Comment by colemickens** [comment]
Hey @DonMartin76. Hope your tests are going more smoothly. Feel free to close out, or I will in a couple days. Thanks!

**Comment by DonMartin76** [comment]
Will do as soon as I have found the root cause for this. Will be able to tell tomorrow, I hope. Either it's a timing issue, or it's our IT dept which has borked something. I will come back here with either an explanation or a solution (e.g. waiting for connectivity using some suitable means or similar). Thanks, @colemickens.

**Comment by DonMartin76** [comment]
Closing this. It works from work today as well. Will revisit if it reoccurs. Puzzled. Thanks for your support, @colemickens
