### ISSUE TITLE
No release notes for v0.18.1

### ISSUE THREAD

**Issue by neurot1cal** [Azure/acs-engine#3203]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

v0.18.1

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

No release notes

**What you expected to happen**:

Release notes ;)

**How to reproduce it** (as minimally and precisely as possible):

Open acs-engine Repo > Releases

**Anything else we need to know**:

@jackfrancis Do we know when we'll get release notes for this lastest version? :)

**Comment by CecileRobertMichon** [comment]
@neurot1cal Jack is working on it, they should be up soon

**Comment by jackfrancis** [comment]
Thanks for your patience!

**Comment by neurot1cal** [comment]
👍
