### ISSUE TITLE
[kubernetes] Host >30 LoadBalancer services in Azure?

### ISSUE THREAD

**Issue by tekmaven** [Azure/acs-engine#321]
Hey acs-engine maintainers!  Thanks for all the hard work with Kubernetes and ACS!  

I am testing moving a large amount of infrastructure to ACS/Kubernetes.  I've provisioned very capable node VMs and can successfully have 100 active pods in the cluster.  

According to https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits - the default "Public front end IP per load balancer" is 10.  This means by default you can only have 10 LoadBalancer services.  I contacted support, and they can only increase this number to 30 - making the maximum number of LoadBalancer services you can host on ACS 30.  

How can we host more then 30 LoadBalancer services in ACS?

**Comment by rgardler** [comment]
This is an interesting limitation.

If you deploy multiple agent pools each one can have a load balancer. You will then need to ensure that you

**Comment by colemickens** [comment]
The only workaround is to manually configure additional load balancers. You would have to create new load balancer objects in the Azure APIs, one each with a backend pool corresponding to an availability set. Then create new ip configurations for each service you want exposed. Then you'd have to go back to the Service objects in Kubernetes and update them with the Ingress IP for the corresponding ip configuration on the load balancer. It could be done, just requires some work.

(One nice thing is, due to how `kube-proxy` works, you don't need to worry about making sure the workloads run on the corresponding pools.)

**Comment by DonMartin76** [comment]
Related side question: Need I worry about overloading the (single) external load balancer with heavy traffic to the cluster?

**Comment by tekmaven** [comment]
_"If you deploy multiple agent pools each one can have a load balancer. You will then need to ensure that you deploy services to appropriate agent pools."_

_"The only workaround is to manually configure additional load balancers. You would have to create new load balancer objects in the Azure APIs, one each with a backend pool corresponding to an availability set."_

It seems very difficult to achieve scale with external services.  Could work be done in Kubernetes or ACS Engine to create the correct load balancers?  

I am investigating moving my organization's infrastructure to a k8 cluster.  Would a better strategy be size a cluster to hold 30 web apps and create several clusters?

**Comment by colemickens** [comment]
>It seems very difficult to achieve scale with external services. Could work be done in Kubernetes or ACS Engine to create the correct load balancers?

There could be, but it would be non-trivial, somewhat tedious work, and there are open questions in my head as I imagine how it would even look.

>Would a better strategy be size a cluster to hold 30 web apps and create several clusters?

This is much simpler and accessible today without needing to write code or manually configure all of this. I'm also asking internally if there are any other options here...

**Comment by colemickens** [comment]
@tekmaven How many do you need per cluster?

**Comment by colemickens** [comment]
We're going to close this. For exceptional cases, you can contact support and they can increase the limit (possibly higher than otherwise advertised).

Please ping me with more details (how many you need per cluster) etc, if you are unable to reach a good resolution with Support. Thanks.
