### ISSUE TITLE
Make Docker CE a user-configurable container runtime

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#3213]
- manually move all current versions of docker CE into acsmirror (currently we have a few versions up to 17.05)
- enable those new versions in template allowed list:
  - https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesparams.t#L614
- ensure that Docker CE is never installed by default (to avoid violating distribution license), but is a documented user-configurable option

**Comment by CecileRobertMichon** [comment]
Closing for now because implementing this would be a violation of our Docker license.
