### ISSUE TITLE
staticWindowsAPIServerConfig is missing some flags

### ISSUE THREAD

**Issue by ritazh** [Azure/acs-engine#3219]
**Is this a request for help?**:

---
No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**What version of acs-engine?**:
---
Issue can be reproduced with v0.18.1 and head

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes
**What happened**:
When provisioning a Kubernetes cluster with Windows agents, we noticed some flags are missing from the apiserver config. For example, when `"enableEncryptionWithExternalKms": true` is added to the apimodel.

**What you expected to happen**:
Expected to see `--experimental-encryption-provider-config` flag in kube-apisever.yaml 

**How to reproduce it** (as minimally and precisely as possible):
Provision a Kubernetes cluster with Windows agents and `"enableEncryptionWithExternalKms": true` in the apimodel.

apimodel:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10",
      "kubernetesConfig": {
        "enableEncryptionWithExternalKms": true
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "blahblahblah",
      "vmSize": "Standard_DS2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet"
      },
      {
        "name": "windowspool2",
        "count": 2,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows",
        "osDiskSizeGB": 127
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "blah"
          }
        ]
      }
    },
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": "blah"
    },
    "servicePrincipalProfile": {
      "clientId": "blah",
      "keyvaultSecretRef": {
        "vaultID": "blah",
        "secretName": "blah",
        "version": "blah"
      },
      "objectId": "blah"
    }
  }
}
```

**Anything else we need to know**:

cc @bnookala

**Comment by ritazh** [comment]
will provide a PR for this soon

**Comment by CecileRobertMichon** [comment]
@PatrickLang FYI this looks like it might result in broken Windows clusters

**Comment by ritazh** [comment]
Just to add more data: 

The current behavior here https://github.com/Azure/acs-engine/blob/v0.18.1/pkg/acsengine/defaults-apiserver.go#L76-L77 will result in flags like `--cloud-provider` and `--cloud-config` missing from kube-apiserver.yaml when it's a hybrid cluster. But I'm still able to create resources on azure via kubernetes....why is that?
