### ISSUE TITLE
Windows containers examples please

### ISSUE THREAD

**Issue by artisticcheese** [Azure/acs-engine#322]
Bearing in mind that part of announcement is support for Windows containers. Are there any examples/walk through specifically targeting Windows containers?

**Comment by amanohar** [comment]
@artisticcheese K8s Windows walkthrough check out here: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.windows.md

**Comment by anhowe** [comment]
closing since Anubhuti provided answer
