### ISSUE TITLE
Windows DNS stops working after some amount of time

### ISSUE THREAD

**Issue by sam-cogan** [Azure/acs-engine#3225]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
0.18.3
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10

**What happened**:
Ever since release 0.18.1 DNS on windows containers seems to be working well when initally deploying a cluster. However I am finding that after an indeterminate amount of time (can be a few days, can be less than an hour) pods then start to be unable to resolve external DNS again. Deleting and recreating the cluster will make it work again.
Linux containers are still able to resolve fine, it is only Windows ones.

Windows containers do have DNS set to point to cluster DNS servers

**What you expected to happen**:

Windows containers to be able to resolve external DNS consitently

**How to reproduce it** (as minimally and precisely as possible):
Deploy windows containers, wait some time, try and resolve DNS names

**Anything else we need to know**:

**Comment by SteveCurran** [comment]
Same issue.

**Comment by PatrickLang** [comment]
@daschott - seen this?

**Comment by daschott** [comment]
@sam-cogan @SteveCurran Does accessing by IP work for you?

**Comment by SteveCurran** [comment]
@daschott Unable to test because I am currently having to recreate the cluster from issue #3153.

**Comment by jsturtevant** [comment]
@sam-cogan  What Windows Server version is this on? 1709/1803?

**Comment by sam-cogan** [comment]
1709 is where I have seen it, but that's mainly because I gave up on 1803 due to other DNS issues.

**Comment by kisadam** [comment]
same here with acs-engine v0.17.1, after few days pods unable to resolve DNS
I've got the following error:
Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "........" network: runtime error: invalid memory address or nil pointer dereference; goroutine 1 [running]: github.com/Azure/azure-container-networking/cni.(*Plugin).Execute.func1(0xc042077ec0) /go/src/github.com/Azure/azure-container-networking/cni/plugin.go:94 +0xc3 panic(0x6ab420, 0x84f790) /usr/local/go/src/runtime/panic.go:489 +0x2dd github.com/Azure/azure-container-networking/cni/network.(*netPlugin).Add.func1(0xc042077910, 0xc0420e0850, 0xc0420778d0, 0xc0420778f0, 0xc0420b1460) /go/src/github.com/Azure/azure-container-networking/cni/network/network.go:150 +0xa6 github.com/Azure/azure-container-networking/cni/network.(*netPlugin).Add(0xc0420b1460, 0xc0420e0850, 0x829be0, 0xc04217cc90) /go/src/github.com/Azure/azure-container-networking/cni/network/network.go:285 +0x138d github.com/Azure/azure-container-networking/cni.(PluginApi).Add-fm(0xc0420e0850, 0xc042170ba0, 0x5) /go/src/github.com/Azure/azure-container-networking/cni/plugin.go:112 +0x40 github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc04203f840, 0xc0420e0850, 0x82be20, 0xc0420dd950, 0xc042077e80, 0x0, 0xc04200c1c0) /go/src/github.com/containernetworking/cni/pkg/skel/skel.go:168 +0x1a6 github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc04203f840, 0xc042077e80, 0xc042077e68, 0x82be20, 0xc0420dd950, 0xc042077e38) /go/src/github.com/containernetworking/cni/pkg/skel/skel.go:199 +0x38b github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0xc042077e80, 0xc042077e68, 0x82be20, 0xc0420dd950, 0xc0420dd950) /go/src/github.com/containernetworking/cni/pkg/skel/skel.go:236 +0xf4 github.com/Azure/azure-container-networking/cni.(*Plugin).Execute(0xc042050070, 0x82bde0, 0xc0420b1460, 0x0, 0x0) /go/src/github.com/Azure/azure-container-networking/cni/plugin.go:112 +0x12e main.main() /go/src/github.com/Azure/azure-container-networking/cni/network/plugin/main.go:93 +0x4db

**Comment by jsturtevant** [comment]
@PatrickLang looks like a bug in the cni plugin

**Comment by sharmasushant** [comment]
@kisadam @jsturtevant This looks unrelated to DNS issue reported here. Can you please share logs from CNI located at C:\K\azure*.*

**Comment by croemmich** [comment]
This issue has been around for months. Most of the recent conversation in #2027 is in reference. We've had to inmplement several workarounds to get something that resembles stability. The most extreme is a DNS liveness probe we wrote that gets run in every container so they get re-scheduled when DNS fails. We also have alerting with kube-state-metrics and Prometheus to let us know when pods are failing for an extended period of time, which does happen fairly frequently. We are running on-prem and thus using wincni and not azurecni, but the issue seems to be the same.

**Comment by daschott** [comment]
@croemmich Next time you hit this issue, can you check whether all the kube-dns pods are running on your master? What is number of restarts for the kube-dns pods, if any?

**Comment by jbiel** [comment]
@daschott - I work with @croemmich and am the primary maintainer of our Windows Kubernetes cluster.

The kube-dns pods are running on 3 separate Linux nodes (we have a hybrid cluster) and have not experienced issues/restarts. Jobs that get scheduled on the Linux nodes do not experience any DNS/service IP issues. Also this does not just affect DNS, it's all service IP traffic in general (we have other TCP services routable via service IPs that are sometimes inaccessible in Windows.) Please see my comments in #2027 for more details.

```
➜  ~ kubectl -n kube-system get pods
NAME                                              READY     STATUS    RESTARTS   AGE
kube-dns-7cbffd9dc9-2hwhw                         3/3       Running   0          97d
kube-dns-7cbffd9dc9-rc5dh                         3/3       Running   0          85d
kube-dns-7cbffd9dc9-zlm77                         3/3       Running   0          85d
```

**Comment by daschott** [comment]
@jbiel @sam-cogan Do you still see this on recent acs-engine deployments? I cannot reproduce this. 
Here is what I tried:
acs-engine 0.19.2 on Windows Server, version 1803 and Kubernetes version 1.9.9
Ran two pods for 5 days (and counting) with DNS resolutions every 3 minutes. No errors.

DIY Kubernetes deployment on Windows Server 2019 (Insider) build 17682 and Flannel (host-gw) CNI. Kubernetes version 1.10.4
Ran two pods for 9 days with DNS resolution every 3 minutes. No errors.

I also ran some other tests that sent consistent traffic using kube DNS. No errors again. Which builds were you using and do you continue hitting this issue?

**Comment by sam-cogan** [comment]
I have not seen it at all since moving to using 0.19, Kubernetes 1.11 and 1803.

**Comment by PatrickLang** [comment]
Closing, seems to be ok for last few weeks. If you hit this again, please open a new issue
