### ISSUE TITLE
acs-engine / kubernetes upgrade "getsockopt: connection timed out"

### ISSUE THREAD

**Issue by pcj** [Azure/acs-engine#3249]
We are currently using acs-engine 0.10.0 to deploy kubernetes 1.8.4. 

Under this setup the `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` does not appear to work correctly.  When I upgraded a cluster on AKS from kubernetes 1.8.10 to 1.9.6, that annotation does work.

Therefore, I am now upgrading our acs-engine setup.  Using acs-engine v0.18.3 and changing to `"orchestratorVersion": "1.9.6"`, the cluster is created as expected.

However, I'm unable to get azure-vote working in this new cluster as the frontend cannot seem to connect to the redis backend despite a normal azure-vote-back service configuration.  Also, I cannot connect to the kubernetes web ui, which fails with `Error: 'dial tcp 10.244.2.3:8443: getsockopt: connection timed out'
Trying to reach: 'https://10.244.2.3:8443/'`.

Any pointers on how to debug this further or tips for upgrading from 1.8.x to 1.9.x?

**Comment by dennis-benzinger-hybris** [comment]
What exactly "does not appear to work correctly" ? Do you have any error messages or log files?

**Comment by dennis-benzinger-hybris** [comment]
FWIW I am able to create a working internal LB with Kubernetes version 1.8.4.

**Comment by pcj** [comment]
How did you test it?  From within the kubernetes cluster or from the vnet/subnet?  In my observations, attempting to curl a service exposed to the vnet via an internal lb fails.

Here are general steps to reproduce:

1. Create a typical aks cluster `az aks create --kubernetes-version 1.8.10`. 
3. Install azure-vote application as normal.  Port-forward azure-vote-front and curl from localhost to confirm it's working.
4. Change the service type to LoadBalancer, add the annotation `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`.  External IP from `kubectl get svc -o wide` is `10.1.0.7`.
5. Curl again via `kubectl port-forward`, still working.  So far, so good.
2. Add a "regular" ubuntu vm to the same vnet as the aks cluster (using portal.azure.com).
3. SSH to the ubuntu machine and try to `curl -v 10.1.0.7` the service from (3) using the subnet private IP.  Curl will hang, does not work.
5. Upgrade kubernetes to 1.9.6
6. SSH back into the ubuntu machine, `curl -v 10.1.0.7` again, now works as expected.

**Comment by dennis-benzinger-hybris** [comment]
How exactly did you perform step 3 ?

I didn't change the service type but tested with a new one.

**Comment by pcj** [comment]
Step 3 was to say, "Deploy azure-vote in standard fashion (without internal lb), santiy check it works, then update the service to use internal lb".

If you just skipped over the "standard fashion" part and went directly to internal lb, that's fine.  So you're saying you *could* SSH and curl the internal IP?
