### ISSUE TITLE
Update ACS Engine to read location from ContainerService model instead of using resourceGroup().location function

### ISSUE THREAD

**Issue by amanohar** [Azure/acs-engine#325]
Update ACS Engine to read location from Container Service model instead of resourceGroup().location function in the template. 

This is because user could create resource group in region A but could specify resource region B (in container service API model). In this case the generated template will result in resources being created in region A instead of B,

**Comment by rjtsdl** [comment]
Well i am working on a fix on this.

**Comment by rjtsdl** [comment]
#379 Please review this PR

**Comment by rjtsdl** [comment]
Close it, it is resolved by the #379
