### ISSUE TITLE
Kubernetes Dashboard Auth

### ISSUE THREAD

**Issue by Netdoc41** [Azure/acs-engine#3253]
**Is this a request for help?**:
Maybe
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
18
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Finished all steps, went to open the dashboard. It prompts for either config file or token. The config file does not work but upon research it may not be able to. So i followed some instructions on creating a new admin user but then when i use that token it does not have any permissions.

**What you expected to happen**:
From reading the instruction i expected with the proxy up and working that it would not prompt me for anything rather it would use that connection.

**How to reproduce it** (as minimally and precisely as possible):
create new cluster. Open proxy. Try to open dashboard

http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/role?namespace=default

**Anything else we need to know**:
no

**Comment by Netdoc41** [comment]
Also went to get the default token via this command (kubectl -n kube-systedescribe secret $(kubectl -n kube-system get secret | grep default | awk '{print $1}')

Same message
![image](https://user-images.githubusercontent.com/9805053/41315793-90d574f0-6e5e-11e8-8fa9-52d92d5b0385.png)

**Comment by kichristensen** [comment]
@Netdoc41 Have you applied the ClusterRoleBinding described here: https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges

**Comment by Netdoc41** [comment]
That did it. Did i miss that in the doc? is setting it up that way the preferred method?

**Comment by kichristensen** [comment]
I don't think it is the preferred way, that why the link also contains an note indicating it is a security risk. The preferred way would be probably be to actually login to the the dashboard with a user having access to what's needed
