### ISSUE TITLE
acs-engine not attaching agentpool to public load balancer

### ISSUE THREAD

**Issue by sanjinp** [Azure/acs-engine#3256]
Is this a request for help?:
Its manually resolved, rather info for everyone having the same issue, I am using predefined subnets for masters and agents.
---

Is this an ISSUE or FEATURE REQUEST?
Issue
---

What version of acs-engine?
0.18.3
---
 I have deployed kubernetes cluster using this template:
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "--",
      "vmSize": "Standard_D1_v2",
      "vnetSubnetId": "/subscriptions/--/resourceGroups/vnet/providers/Microsoft.Network/virtualNetworks/--/subnets/k8-master",
      "firstConsecutiveStaticIP": "10.239.255.239",
      "vnetCidr": "10.239.0.0/16"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "vnetSubnetId": "/subscriptions/--/resourceGroups/vnet/providers/Microsoft.Network/virtualNetworks/--/subnets/k8-agent"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.10.4

**What happened**:
Service LoadBalancer public IPs assigned but not reachable from internet

**What you expected to happen**:
Service/ingress Public IPs reachable

**How to reproduce it** (as minimally and precisely as possible):
Location: North Europe
Use the same template provided above, I noticed that Public load balancer is not associated with agentpool vmss, so to resolve it I had to manually associate it through portal.

**Comment by CecileRobertMichon** [comment]
@sanjinp could please provide more details? Is this a something that should go in docs?
