### ISSUE TITLE
Add a pool

### ISSUE THREAD

**Issue by aminebizid** [Azure/acs-engine#3260]
**A request for help**:
Guys,
What is the easiest way to add a new pool to my Kub cluster without recreating it?

---

**What version of acs-engine**:

Version: canary
GitCommit: f2a70d9
GitTreeState: dirty

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.11.2

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/blob/master/docs/kubernetes-day2-operations.md

**Comment by aminebizid** [comment]
Thanks @CecileRobertMichon 

It will be great if we can do this:

```bash
kubectl get pools
kubectl describe pool staging
kubectl delete pool staging
kubectl create pool test --count 3  --vmSize Standard_D2_v3 \
--osDiskSizeGB 200GB --osType linux --vnetSubnetId subnet \
--availabilityProfile VirtualMachineScaleSets
```

**Comment by CecileRobertMichon** [comment]
@aminebizid looks like what you are asking for is a new kubectl command, that would be an ask for Kubernetes, not acs-engine
