### ISSUE TITLE
Overprovisioning with the autoscaler extension

### ISSUE THREAD

**Issue by shayansarkar** [Azure/acs-engine#3267]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Request
---

**What version of acs-engine?**:
Version: canary
GitCommit: 658c2c28
GitTreeState: clean
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.10.3

**What happened**:

I created a new cluster with the autoscaler extension and everything worked as expected.  The cluster scaled up and down based on the parameters I provided.  However, I wanted to overprovision the cluster by 1 VM so that spare capacity would alway be available.  Is there some way to enable overprovisioning via the extension.  The previous autoscaler I used ```https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler``` supported overprovisioning, but it does not support VMSS.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@sozercan thoughts?

**Comment by feiskyer** [comment]
Overprovisioning can be configured using deployment running pause pods with very low assigned priority which keeps resources that can be used by other pods. If there is not enough resources then pause pods are premmpted and new pods take their place. Next pause pods become unschedulable and force CA to scale up the cluster.

See https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler for detailed steps.
