### ISSUE TITLE
System load peaks on kubernetes master node on azure

### ISSUE THREAD

**Issue by kris-dehaudt** [Azure/acs-engine#329]
Does anyone know why we are experiencing on our kubernetes master node some system load peaks. I thought that the master node is not doing anything except monitoring our agent nodes.

Each time we have a system load peak of 1.8-2 on our dual-core machine, I see in the kube-controller-manager log that the master tries to start 3 things:

 - controllermanager.go:373] Attempting to start disruption controller
 - controllermanager.go:385] Attempting to start petset
 - controllermanager.go:460] Attempting to start certificates

Our kubernetes version is 1.4.6 and is created via the azure portal with a container service. The system peaks can we see via datadog monitoring.

**Comment by colemickens** [comment]
Those events in the log seem like misnomers probably. Those are part of the typical controller loop and shouldn't be impactful.

The cluster is very old, would you be able to reproduce this on a newer cluster? Does datadog tell you what exactly is spiking?

I'm going to close this for now. Please re-open an upstream issue against Kubernetes with further information about what is actually spiking, as this is unrelated to ACS-Engine - we only run the standard k8s components. Thanks.
