### ISSUE TITLE
Autoscaler plugin wrong image

### ISSUE THREAD

**Issue by aminebizid** [Azure/acs-engine#3309]
In autoscaler deployment the container image is set to 
k8s-gcrio.azureedge.net
instead of 
k8s-gcrio.azureedge.net/cluster-autoscaler:v1.2.2

I had to update myself the deployment after cluster install.

**Comment by CecileRobertMichon** [comment]
@aminebizid which k8s version did you deploy with?

@sozercan fyi

**Comment by sozercan** [comment]
@aminebizid cluster-autoscaler does not officially supports v1.11 yet: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases

**Comment by CecileRobertMichon** [comment]
We should add a check at https://github.com/Azure/acs-engine/blob/master/pkg/api/vlabs/validate.go#L411 to make sure that the k8s version is supported

**Comment by sozercan** [comment]
@CecileRobertMichon agreed 👍

**Comment by CecileRobertMichon** [comment]
@sozercan can you take that on?

**Comment by aminebizid** [comment]
It just works great on 1.11

**Comment by sozercan** [comment]
thanks @aminebizid, looks like CA v1.3 was released yesterday that should support k8s v1.11
