### ISSUE TITLE
Add China Cloud CI Tests

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#331]
cc: @dmitsh

**Comment by colemickens** [comment]
cc: @wangtt03

**Comment by wangtt03** [comment]
Oops, sorry about that. I saw you have already created a PR. Does that PR fix the issue?

**Comment by colemickens** [comment]
I'm hopeful the PR will resolve the CI test being broken, but I filed this for adding CI tests to our Jenkins configurations to enable China Cloud.

I don't think it's documented yet, but Jenkins runs scripts contained in the test/ directory to ensure that `make ci` executes successfully and that the entire e2e process works for the templates under `examples/`.

The scripts would need to be extended, something akin to:
* add new cluster definition examples under `examples/` with the China location(s)
* set `AZURE_CLOUD` based on the location in cluster definition`
* call the right `az` command to point to `AZURE_CLOUD`

Then jobs could be setup for it in Jenkins.

**Comment by jackfrancis** [comment]
@anhowe is this still a regional coverage gap that we want to track?

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
