### ISSUE TITLE
Support for NC and NV Series VMS on Kubernetes Cluster 

### ISSUE THREAD

**Issue by GONZALORUIZ** [Azure/acs-engine#333]
I have tried to create a Kubernetes cluster and use NC VMS (Standard_NC6) for the Agents, however I got the following error :
error": {
    "code": "InvalidParameter",
    "message": "**The value 'Standard_NC6' of parameter 'agentProfile.vmSize'** is not allowed. Allowed values are 'Standard_A0, Standard_A1, Standard_A2, Standard_A3, Standard_A4, Standard_A5, Standard_A6, Standard_A7, Standard_A8, Standard_A9, Standard_A10, Standard_A11, Standard_D1, Standard_D2, Standard_D3, Standard_D4, Standard_D11, Standard_D12, Standard_D13, Standard_D14, Standard_D1_v2, Standard_D2_v2, Standard_D3_v2, Standard_D4_v2, Standard_D5_v2, Standard_D11_v2, Standard_D12_v2, Standard_D13_v2, Standard_D14_v2, Standard_G1, Standard_G2, Standard_G3, Standard_G4, Standard_G5, Standard_A1_v2, Standard_A2_v2, Standard_A2m_v2, Standard_A4_v2, Standard_A4m_v2, Standard_A8_v2, Standard_A8m_v2, Standard_D15_v2, Standard_F1, Standard_F16, Standard_F2, Standard_F4, Standard_F8, Standard_H16, Standard_H16m, Standard_H16mr, Standard_H16r, Standard_H8, Standard_H8m, Standard_DS1, Standard_DS2, Standard_DS3, Standard_DS4, Standard_DS11, Standard_DS12, Standard_DS13, Standard_DS14, Standard_GS1, Standard_GS2, Standard_GS3, Standard_GS4, Standard_GS5, Standard_DS1_v2, Standard_DS2_v2, Standard_DS3_v2, Standard_DS4_v2, Standard_DS5_v2, Standard_DS11_v2, Standard_DS12_v2, Standard_DS13_v2, Standard_DS14_v2, Standard_DS15_v2, Standard_F16s, Standard_F1s, Standard_F2s, Standard_F4s, Standard_F8s'."
  }
}
I have tried to create the ACS cluster in South Central US (NC Series are available there), I have used the latest version of the Python CLI 
az acs create --orchestrator-type=kubernetes --resource-group $RESOURCE_GROUP --name=$CLUSTER_NAME --dns-prefix=$DNS_PREFIX --master-count $MASTER_COUNT --agent-vm-size $AGENT_SIZE --agent-count $AGENT_COUNT  --location $LOCATION

Are the NC and NV Series supported ? What about NC_r (RDMA)
Adding support for NC will enable a broad set of scenarios like deep learning with TensorFlow.

**Comment by colemickens** [comment]
This is how the list of allowed VM sizes is generated: https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/Get-AzureConstants.ps1

Maybe there's something missing? I'm not familiar with the N skus though.

@anhowe Maybe we need to get your subscription access to the GPU skus so that they are present in your generated constants file.

**Comment by theobolo** [comment]
@GONZALORUIZ You need to ask to the Azure Support to unlock cores to be able to use NV or NC series. Did you do that, single VM deployment is working ?

**Comment by GONZALORUIZ** [comment]
@theobolo yes, I have used NC and NV both as standard VMS and with Azure batch. I will open a support ticket and check whether I have to request it again for ACS, but I would be surprised if that is the case.

**Comment by theobolo** [comment]
@GONZALORUIZ Yep you right it should be surprising that you need to ask twice, it should be an issue related to ACS, as Cole said maybe that they need to modify how ACS retrieve the NC and NV series.

**Comment by GONZALORUIZ** [comment]
@colemickens @anhowe I just double checked this with Azure support, I can NOT yet create Kubernetes clusters using N-Series , is this supported?

**Comment by colemickens** [comment]
Is this an issue about ACS or about ACS-Engine? ACS is not supported via this repo. If this is about ACS, please close this Issue and open an Issue named "GPU SKU support in ACS" on the https://github.com/Azure/ACS repo.

If this is about ACS-Engine, I previously linked to the location that needs to be updated to accommodate the N* serises SKUs.

**Comment by anhowe** [comment]
This is not supported in the RP, but is supported in ACS-Engine per constants: https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/azureconst.go#L209-L215.  Closing.
