### ISSUE TITLE
cluster deploymennt issues using acsengine 0.16.0 & 0.18.0

### ISSUE THREAD

**Issue by addycluri** [Azure/acs-engine#3334]
**Is this a request for help?**:

--- Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

--- ISSUE

**What version of acs-engine?**:

--- 0.16.0 & 0.18.0 

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes,

**What happened**:
Deployment ERROR using acsengine verisons (0.16.0 & 0.18.0):
PS | C:\\Temp\\acs-engine-v0.18.8-1 | 06-20-2018 12:26:27 > az group deployment create --name 'user2acswin3-depl' --resource-group 'user2-acswin3' --template-file './_output/user2-acswin3/azur
edeploy.json' --parameters './_output/user2-acswin3/azuredeploy.parameters.json'
Deployment failed. Correlation ID: 3d688f3b-8990-4f37-bb2b-b77b88719c62. {
'status': 'Failed',
'error': {
'code': 'ResourceDeploymentFailure',
'message': 'The resource operation completed with terminal provisioning state 'Failed'.',
'details': [
{
'code': 'VMExtensionProvisioningError',
'message': 'VM has reported a failure when processing extension 'cse-master-0'. Error message: \\'Enable failed: failed to execute command: command terminated with exit status=30\\n[st

Kube issues:
even if the cluster gets sucessfully deployed, we see the following issues with the master node and deployments are failing
- ALL Default kube pods are NOT getting deployed. I just see kube-addon-manager & kube-apiserver deployed
- on an earlier working instance using acs 0.16.0 we see ALL the default pods (heapster / controller /DNS / proxy/scheduler /dashboard / etc )

**What you expected to happen**:
all default K8S PODS to get deployed correctly
default service accounts be created.
service deployment does NOT throw errors with service accounts & tokens

**How to reproduce it** (as minimally and precisely as possible):
1)be able to successfully deploy the K8S cluster using acsengine ---- .\acs-engine.exe deploy --api-model C:\kube\kubernetes.json --location westus --subscription-id "guid"
2)log onto the master node and kubectl get pods -n=kube-system should show ALL default kube pods
3)finally running a deployment should NOT throw ereors with default service  accounts and no tokens available.

**Anything else we need to know**:
will shoow/repro using screenshare if posssible

**Comment by CecileRobertMichon** [comment]
Could this be similar to https://github.com/Azure/acs-engine/issues/3151?

**Comment by adichin** [comment]
@CecileRobertMichon thanks I will take a look at all the details of #3151 and update.
