### ISSUE TITLE
ssh key should not be required for a hosted master deployment

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#3339]
In general, I think the LinuxProfile [requirement](https://github.com/Azure/acs-engine/blob/d70808a7f888c79e9f23601df46db3577223deed/pkg/api/agentPoolOnlyApi/vlabs/types.go#L37) is redundant since no ssh access is granted in CCP machines.

**Comment by CecileRobertMichon** [comment]
This was done in https://github.com/Azure/acs-engine/pull/2582 for some api versions, not sure why the change wasn't applied to vlabs… @zqingqing1 @weinong ?
