### ISSUE TITLE
Enable encryption for disks by default

### ISSUE THREAD

**Issue by sheerun** [Azure/acs-engine#334]
The security advisor on Azure tells me none of the disks created by ACS are encrypted, why so?

**Comment by colemickens** [comment]
Good suggestion, I don't think it was intentionally omitted, we just haven't done it yet. Labeled so that it will be in our backlog, and pull requests are always welcome.

**Comment by anhowe** [comment]
@sheerun do you know why the creation of a regular VM on Azure doesn't have this on by default?  For example, why don't we have customers have to go out of their way to disable encrypted disks?

**Comment by clementnero** [comment]
PR #406: enable storage account encryption (for data disks)

**Comment by anhowe** [comment]
closing, please answer these questions before re-opening: https://github.com/Azure/acs-engine/pull/406#issuecomment-289954501.
