### ISSUE TITLE
Enable failed: failed to execute command: command terminated with exit status=80

### ISSUE THREAD

**Issue by aasier** [Azure/acs-engine#3350]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.18.8
---

If this is a ISSUE, please:

We are trying to deploy new fresh infrastructure of Kubernetes cluster with VMSS machines, and every time we are getting the following error: (check the logs attached)

"timestampUTC": "2018-06-20T10:50:19Z",
"status": {
"operation": "Enable",
"status": "error",
"formattedMessage": {
"lang": "en",
"message": "Enable failed: failed to execute command: command terminated with exit status=80\n[stdout]\n\n[stderr]\n"

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Yes, always when we try to deploy a new cluster with VMSS machines.
[waagent.zip](https://github.com/Azure/acs-engine/files/2131868/waagent.zip)

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Are you using a `customSearchDomain`? this error means that setting up a custom search domain failed.

**Comment by aasier** [comment]
Thanks! @CecileRobertMichon for your update.
Tested it again and it works with this extension register-dns.sh 
Please, you can close this issue,

Cheers,
