### ISSUE TITLE
Windows init container results in no DNS reslution

### ISSUE THREAD

**Issue by sam-cogan** [Azure/acs-engine#3352]
**Is this a request for help?**: no

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**:
0.18.9
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10

**What happened**:
When using an init container with a Windows pod it seems that the main container spawned once init is complete, is unable to resolve any DNS queries.

The init container is able to resolve fine, and if I remove the requirement for the init container, the main container is also able to resolve, but using both causes this issue. 

**What you expected to happen**:

Main container to be able to resolve DNS queries.

**How to reproduce it** (as minimally and precisely as possible):

Deploy a Pod with a windows container that has an init container (also windows) configured.

**Anything else we need to know**:

**Comment by PatrickLang** [comment]
What OS were you using? This should be feasible on Windows Server 1803 but I don't know for sure about 2016 or 1709. There may still be bugs here so if you have a deployment spec you can share that would be helpful

**Comment by sam-cogan** [comment]
This is using 1709, I've not been able to try with 1803 due to the ongoing DNS issues with that build
