### ISSUE TITLE
Kubernetes: Cluster IPs are not accessible on new deployments

### ISSUE THREAD

**Issue by bclau** [Azure/acs-engine#3368]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: v0.18.9

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes 1.11

**What happened**:

On a newly created Kubernetes deployments, the spawned Windows pods cannot access Cluster IPs. Since the Windows pods are configured to use the Kubernetes DNS server (10.0.0.10), DNS name lookups always fail, and the pods cannot access the Kubernetes API (10.0.0.1).

Restarting the Windows nodes solves this issue.

**What you expected to happen**:

The Kubernetes Cluster IPs should be accessible, and thus, DNS lookups should be resolvable.

**How to reproduce it** (as minimally and precisely as possible):

1. Create a Kubernetes deployment via acs-engine ( kubernetes.json: https://paste.ubuntu.com/p/8VrYhYkwvd/ )
2. After the deployment finishes, run:

    kubectl create namespace test-windows-containers
    kubectl create -f windows_pod.yaml ( https://paste.ubuntu.com/p/SrXDw92bqq/ )

3. Wait for the pod to start. Then run:

    \# DNS server should be set to 10.0.0.10
    kubectl exec -n test-windows-containers pod_name -- ipconfig /all
    \# this will timeout: https://paste.ubuntu.com/p/M2fzM4QVZq/
    kubectl exec -n test-windows-containers pod_name -- nslookup kubernetes.default.svc.cluster.local
    
4. Restart the Windows nodes.

5. Run Step 3. again. This time, nslookup will succeed: https://paste.ubuntu.com/p/4SDXQkdHVg/

**Anything else we need to know**:

**Comment by PatrickLang** [comment]
@dineshgovindasamy @daschott - how are the DNS fixes coming? have you synced with azure cni team on this yet?

**Comment by bclau** [comment]
The main issue here is the fact that the Kubernetes Cluster IPs are not accessible from the Windows pods. The DNS server not being accessible is a secondary effect of this problem.

**Comment by daschott** [comment]
@bclau My observations are: 
Only the first pod scheduled for a given node has no connectivity to cluster IPs. Every subsequent pod that you schedule on the node will have service VIP and outbound connectivity, even without reboot (do you also see this?) A root cause has been identified by @dineshgovindasamy for this. I agree that this is separate from the issue where the DNS suffix isn't being set correctly.

**Comment by bclau** [comment]
I've created a new deployment to test this out. As expected, the 1st pod didn't have cluster IP connectivity. The 2nd one had. The subsequent 8-10 pods did not.

**Comment by daschott** [comment]
@bclau For me, subsequent pods do have cluster IP connectivity. Only the first one scheduled on a node doesn't. Which acs-engine version did you use to create your cluster?

I tested using https://github.com/Microsoft/SDN/blob/master/Kubernetes/WebServer.yaml

**Comment by daschott** [comment]
I used acs-engine 0.18.9. This issue with the first pod having no connectivity should be resolved once [this workaround](https://github.com/Azure/azure-container-networking/pull/174/commits) makes its way up to Azure-CNI.

**Comment by daschott** [comment]
#3037

**Comment by adelina-t** [comment]
@bclau Can you confirm the workaround @daschott is using works for you?

**Comment by daschott** [comment]
@bclau are you still seeing this issue?
