### ISSUE TITLE
Support for attaching extra ssd data drives

### ISSUE THREAD

**Issue by sheerun** [Azure/acs-engine#338]
I wanted to attach extra (ideally managed) SSD data drive, to one of the nodes for Azure ACS on Kubernetes (default setup), but it seems I'm only able to attach slow HDD (60MB/s)..

I think it might be because of what master/agent machines are created. (FYI I need extra disks to vendor glusterfs cluster, but it really doesn't matter).

Could you allow to configure master/agent node types so I can attach fast drives to them?

**Comment by anhowe** [comment]
@sheerun Can you clarify the problem?  Are you saying we can't attach SSD's to premium SKUs or can't attach SSD's to standard SKUs?

**Comment by anhowe** [comment]
Closing since you can attach SSDs to premium skus (sizes with S in the name)
