### ISSUE TITLE
Add Kubernetes ExternalDNS to Addons

### ISSUE THREAD

**Issue by flyboarder** [Azure/acs-engine#3380]
**Is this a request for help?**:
---
No, although direction on how to create an addon would allow me to get a PR started

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Feature Request

**What version of acs-engine?**:
---
master branch

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes

**What happened**:
There is no asc-engine based deployment of external DNS services

**What you expected to happen**:
Deploy K8s ExternalDNS as an addon with the cluster

**How to reproduce it** (as minimally and precisely as possible):
n/a

**Anything else we need to know**:
n/a

**Comment by CecileRobertMichon** [comment]
You could look at https://github.com/Azure/acs-engine/pull/3198 for an example PR for adding an addon
