### ISSUE TITLE
Openshift template fails with "The marketplace resource plan is missing required "name" property."

### ISSUE THREAD

**Issue by ccuz** [Azure/acs-engine#3381]
**Is this a request for help?**:
no. a call for fix.
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
Version: canary
GitCommit: 91cdfe96
GitTreeState: clean

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Openshift 3.9

**What happened**:
Try to use the template using following step, from a newly created Azure Account.
1. docker pull ams0/acs-engine-light-autobuild
2. edit the https://github.com/Azure/acs-engine/blob/master/examples/openshift.json into C:\Users\xxx\Openshift\openshift.json
3. docker run -it --rm -v /c/Users/xxx/Openshift:/acs -w /acs ams0/acs-engine-light-autobuild:latest /acs-engine generate /acs/openshift.json
4. Create the Openshift cluster on Azure using the generated template:
i.	docker run -it -v /c/Users/xxx/Openshift:/home microsoft/azure-cli
ii.	az login
iii.	az account set --subscription "${SUBSCRIPTION_ID}"
iv.	az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/${SUBSCRIPTION_ID}"
v.	az group create --name testOS39us --location eastus
vi.	az group deployment create --name testOS39deploy --resource-group testOS39us --template-file /home/_output/camp18/azuredeploy.json --parameters @/home/_output/camp18/azuredeploy.parameters.json

Deployment fails using the anonymized file 
[openshift.json.txt](https://github.com/Azure/acs-engine/files/2144177/openshift.json.txt)
with : 
Azure Error: MissingMarketplacePlanName
Message: The marketplace resource plan is missing required "name" property.

**What you expected to happen**:
According to the documentation, it should create the resources, thus the cluster within the next 20 minutues.

**How to reproduce it** (as minimally and precisely as possible):
As documented

**Anything else we need to know**:
I suspect the imageReference is expected, but the Template documentation makes no mention of it. Could you try the documented steps and fix the documentaton in order to have at least one simple Openshift-cluster deployment on Azure (i.e. one master, one node, one infra) working, as the error message from the validation is of no help, even using google ;-).
Ideally, have a CI regression-test that the generated template are deployable ;-)

1. Small bash script that run through the 6 steps to create a cluster
2. Assert that https://camp18.eastus.cloudapp.azure.com:8443/ is reachable
3. Calls "az group delete --name testOS39" to delete the test cluster.

**Comment by CecileRobertMichon** [comment]
@jim-minter @pweil- @kargakis @kwoodson
