### ISSUE TITLE
coredns for k8s 1.11

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#3385]
https://kubernetes.io/docs/tasks/administer-cluster/coredns/

**Comment by jackfrancis** [comment]
@lachie83 @khenidak @feiskyer FYI, tracking issue to implement coredns in 1.11 (if we wanna be idiomatic I think we work toward making it the default for 1.11)

**Comment by feiskyer** [comment]
+1

**Comment by khenidak** [comment]
I wouldn't make it the default until we get some milage on it. (I know it sounds the great new thing, but before it make its way to our "default")

**Comment by CecileRobertMichon** [comment]
coredns is now default for 1.12+
