### ISSUE TITLE
CSE exit code 15

### ISSUE THREAD

**Issue by gitphill** [Azure/acs-engine#3395]
**Is this a request for help?**: YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE 

---

**What version of acs-engine?**: 0.19.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Exit code 15: https://github.com/Azure/acs-engine/blob/v0.19.0/parts/k8s/kubernetescustomscript.sh#L153

**What you expected to happen**:
Exit code 0

**How to reproduce it** (as minimally and precisely as possible):
`acs-engine generate ...` and `az group deployment create ...` using Azure CNI VNET configuration
https://github.com/Azure/acs-engine/blob/master/examples/vnet/kubernetesvnet-azure-cni.json

**Anything else we need to know**:
Looks like an issue with `sudo` - nothing to do with etcdctl.
I can see in logs: `sudo: unable to resolve host <hostname>: Connection timed out`.
Root user cannot resolve hostname?

**Comment by CecileRobertMichon** [comment]
@gitphill could you please share the full `/var/log/azure/cluster-provision.log` log?

**Comment by gitphill** [comment]
@CecileRobertMichon [cluster-provision.log](https://github.com/Azure/acs-engine/files/2162321/cluster-provision.log) thanks

**Comment by CecileRobertMichon** [comment]
Do you have any special vnet configs that would be relevant? Maybe NSG rules, a firewall or custom DNS? I'm not able to repro the error...

**Comment by gitphill** [comment]
Yes looks like we do have a custom DNS configuration.

https://github.com/Azure/acs-engine/blob/master/examples/vnet/kubernetesvnet-customnodesdns.json 

Is this the best way to use acs-engine to configure DNS?

**Comment by gitphill** [comment]
Can I use an Azure DNS zone
