### ISSUE TITLE
Acs-engine latest version 0.19.0 fails with kubenet plugin default install

### ISSUE THREAD

**Issue by digeler** [Azure/acs-engine#3396]
https://github.com/digeler/scripts/blob/master/acs-engineissue
full error log is here

**Comment by PatrickLang** [comment]
Looking

/assign

**Comment by PatrickLang** [comment]
Can you try:
- Switch to Kubernetes v1.10.5
- Switch to availabilitysets from VMSS

And see if either of those resolve it for you?

**Comment by digeler** [comment]
Thanks Patrick
Looks like issue is fixed with cni 1.0.7
Ill give it a try.

**Comment by PatrickLang** [comment]
Can you close issue if it's working for you?

I also added internal tests with kubenet and they're passing. You can use that as an option if you prefer that instead of azure-cni
