### ISSUE TITLE
Kubernetes cluster cannot be deployed successfully in Mooncake after merging AzureChinaCloud PR.

### ISSUE THREAD

**Issue by wangtt03** [Azure/acs-engine#340]
Also affects the Azure public cloud.

**Comment by wangtt03** [comment]
I already submit another PR: https://github.com/Azure/acs-engine/pull/339 to fix this issue.

**Comment by wangtt03** [comment]
to: @colemickens @amanohar

**Comment by colemickens** [comment]
@wangtt03 Does this actually fully block deployment of clusters? In public cloud at least it seems like everything should've worked except setting up `kubectl` ?

**Comment by wangtt03** [comment]
@colemickens for the public cloud the apiserver cannot be started correctly because of the wrong version of the yaml.

**Comment by wangtt03** [comment]
@colemickens @anhowe could you please assign the issue to me because i am fixing the issue. Thanks!

**Comment by wangtt03** [comment]
This bug should be fixed by PR:https://github.com/Azure/acs-engine/pull/339
