### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by adelina-t** [Azure/acs-engine#3405]
**ISSUE** :
---
**What version of acs-engine?**:

Tested with: v0.18.3 trough v0.18.9

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes v1.11.0-beta.1
azure-vnet-cni-windows: v1.0.4 

**Pods fail to spawn with the following error*:

https://paste.ubuntu.com/p/pc3FmMzrhS/

**Anything else we need to know**:

This issue can appear on both creation and deletion of a pod. Because this also appears when deleting the pod, the containers will remain on the Windows nodes (``kubeletwin/pause`` containers), even if the pod is no longer registered in Kubernetes.

Full logs: https://www.dropbox.com/sh/27pjfzcr4ebv0xw/AAAvUYauIuDFDlzt1darN2oVa?dl=0

**Comment by jchauncey** [comment]
@JunSun17 have you seen this error before?

**Comment by sharmasushant** [comment]
@jchauncey It might be related to the issue we are discussing with kubernetes cni: https://github.com/containernetworking/cni/issues/571

Can you share logs from C:\K\azure-vnet* to confirm.

**Comment by PatrickLang** [comment]
The last issue I'm aware of for this error is https://github.com/Azure/azure-container-networking/issues/232
