### ISSUE TITLE
Unable to view keys via etcdctl

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/acs-engine#3412]
After discussing with @CecileRobertMichon, I am opening this ticket.  The issue is that I'm unable to use `etcdctl` to view the etcd keys from inside the ACS-engine cluster.

```
➜   acs-engine version
Version: v0.18.3
GitCommit: 77dafcb43
GitTreeState: clean
```

When I run: `sudo etcdctl ls` on an acs-master node, it only shows one directory.
```
thfalgou@k8s-master-46893216-0:~$ sudo etcdctl ls / --recursive
/proxycerts
/proxycerts/requestheader-client-ca-file
/proxycerts/proxy-client-key-file
/proxycerts/proxy-client-cert-file
thfalgou@k8s-master-46893216-0:~$
```

I have proven that `generate-proxy-certs.sh` exists:
```
thfalgou@k8s-master-46893216-0:~$ ls -lart /etc/kubernetes/generate-proxy-certs.sh
-rwxr--r-- 1 root root 2787 Jun 11 19:36 /etc/kubernetes/generate-proxy-certs.sh
```

When I try running the curl request raw, I get the same list:
```
thfalgou@k8s-master-46893216-0:~$ sudo curl --cacert /etc/kubernetes/certs/ca.crt --cert /etc/kubernetes/certs/etcdclient.crt --key /etc/kubernetes/certs/etcdclient.key https://127.0.0.1:2379/v2/keys
{“action”:“get”,“node”:{“dir”:true,“nodes”:[{“key”:“/proxycerts”,“dir”:true,“modifiedIndex”:5,“createdIndex”:5}]}}
```

My acs-engine JSON file is below.  The only thing that is different is that I'm using NetworkPolicy of Calico, but I have a client that is also reporting it w/o Calico:

```
cat kubernetes-calico.json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10",
      "kubernetesConfig": {
        "networkPolicy": "calico"
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "acs-engine-19-calico",
      "vmSize": "Standard_DS2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "thfalgou",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<NONE FOR YOU>"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "<NONE FOR YOU>",
      "secret": "<NONE FOR YOU>"
    }
  }
}
```

The cluster is functional as I have deployed pods inside of it, but I cannot determine how to view the etcd data.

Thanks in advance!
-Tommy.

**Comment by mwieczorek** [comment]
Not sure about that, but maybe try with etcd api v3? F.e.:
```
ETCDCTL_API=3 etcdctl get / --prefix
```

**Comment by dennis-benzinger-hybris** [comment]
The clusters created by acs-engine still use API version 2: #2559

**Comment by mwieczorek** [comment]
I have k8s cluster (acs-engine v0.18.9, k8s 1.10.5) with API v3 (`--storage-backend=etcd3` in apiserver args). I think #2559 is only for using v3 API in acs-engine installation scripts

**Comment by dennis-benzinger-hybris** [comment]
Ah, yes. You are right. With `ETCDCTL_API=3" I can view the contents of etcd. But only if I set all the TLS related parameters. Without them I get the not very helpful error message "Error:  context deadline exceeded".

**Comment by dennis-benzinger-hybris** [comment]
Only the proxycerts are stored via the version 2 API. The Kubernetes data is stored in v3.

**Comment by lastcoolnameleft** [comment]
Ah ha!  Thanks for the clarification.  

I hit the same "context deadline exceeded" error, so I had to pass in the cert/key/cacert options as such to get it to work:

```
sudo ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/certs/ca.crt --cert /etc/kubernetes/certs/etcdclient.crt --key /etc/kubernetes/certs/etcdclient.key --debug get / --prefix --keys-only
```

**Comment by lastcoolnameleft** [comment]
That said, this addresses my issue, so thanks!
