### ISSUE TITLE
VNET address space customization 

### ISSUE THREAD

**Issue by Dan-Wolfy** [Azure/acs-engine#3415]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
v0.19.1
---

If this is a FEATURE REQUEST, please:
Custom VNet Address Space option,

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
When creating the cluster with kubenet (similair to v8) it setups the vnet to 10.0.0.0/8, orginally through though the vnetcidr did this but according to documentation it doesn't.

**What you expected to happen**:
When creating we would like an option to setup a variable like vnet_addresspace to a build a custom CIDR to allow us to bridge vnets without updating the ARM templates.

**Comment by shayansarkar** [comment]
You should be able to create a VNet with whatever address space you like and then reference it in your acs-engine template.  Then when you generate the ARM templates, it will be using that custom VNet with your configuration.

So the steps would be

1) Create a VNet with whatever address space and subnets you want
2) In the acs-engine template add a "vnetSubnetId" reference in the master and agent sections
3) generate out the acs-engine template and deploy the cluster

This is an example of how to do it
https://github.com/Azure/acs-engine/blob/master/docs/custom-vnet.md
