### ISSUE TITLE
acs-engine deploy fails for national clouds (e.g. Azure Government) due to missing AKS.Linux.Billing extension

### ISSUE THREAD

**Issue by gsacavdm** [Azure/acs-engine#3416]
**Is this a request for help?**: No
---
**Is this an ISSUE or FEATURE REQUEST?**: Issue
---
**What version of acs-engine?**: v0.19.1
---
**Orchestrator and version**: Kubernetes v1.8

**What happened**: Attempted `acs-engine deploy` to Azure Government (with `--azure-env AzureUSGovernmentCloud`) but it failed with the following error:

 >ERRO[0357] {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"}]}}

**What you expected to happen**: Deployment should complete successfully either without the extension (which is how it worked in previous versions) or the extension should be published in national clouds. Probably the former is preferable though I'm not familiar with the extension and it's purpose.

**How to reproduce it** (as minimally and precisely as possible):
Run `acs-engine deploy --cloud-env AzureUSGovernment` with all the other required parameters for the `deploy` command.

**Anything else we need to know**: N/A

**Comment by karataliu** [comment]
Same failure with AzureChinaCloud environment

**Comment by gsacavdm** [comment]
@jackfrancis , thoughts on this? I noticed you were the one that introduced this extension. Since you are the most familiar with it, how hard would it be to make it optional? I started exploring it (see my PR), not sure how much time/effort it would take me.

**Comment by ashishkulk** [comment]
Same failure with _AzureGermanCloud_ environment.

**Comment by JeffreyGarrett** [comment]
@gsacavdm can you tell us which version of acs-engine billing extensions were added?  We are hoping to downgrade acs-engine as a work around for now.

**Comment by karataliu** [comment]
@JeffreyGarrett v0.19+ has the the extensions. You can try 0.18*

**Comment by y325A** [comment]
@JeffreyGarrett you can alter the azuredeploy.json file and remove the resources if you require the latest version.

**Comment by gsacavdm** [comment]
You can also build [my branch where I made this configurable](https://github.com/gsacavdm/acs-engine/tree/aks-extension) and add the following to your apiModel to disable the extension, then you'll be able to run `deploy`, `upgrade`, etc:

```json
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
        "useAksExtension": false
      }
    },
```
