### ISSUE TITLE
Acs-engine upgrade for a cluster in 2 VNETs

### ISSUE THREAD

**Issue by SilvioPilato** [Azure/acs-engine#3418]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
This is an issue
---

**What version of acs-engine?**:
v0.19.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.3

**What happened**:

We built our cluster 4 month ago with acs engine. The cluster is built on 2 VNETs, one for the agents and one for the masters.
On the upgrade command we got an error saying "error loading existing cluster: error parsing the api model: Multiple VNETS specified."
We thought that we could update our cluster in that way.

**What you expected to happen**:
We expected to have an 1.10.5 k8s cluster in the end.

**Anything else we need to know**:
If there is no way to update a cluster maintaining this 2 VNETs structure, is there any alternative?

**Comment by jackfrancis** [comment]
Hi @SilvioPilato, multiple VNETs is not a "blessed" model. Could you do a smoke test on v0.19.1 and try to re-deploy a new cluster using the multi-VNET model?

Let us know if this works, or if you get the same validation error as above on a new deployment.

@CecileRobertMichon FYI
