### ISSUE TITLE
CSE exit code 41

### ISSUE THREAD

**Issue by no-stupid-questions** [Azure/acs-engine#3435]
**Is this a request for help?**:

yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

no

**What version of acs-engine?**:
Version: v0.19.1
GitCommit: f50fe5fe
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes v1.10.5

**What happened**:
deployed a hybrid kubernetes cluster with existing vnet, and the one windows node spun up fin and the cse provisioning had no errors, but three linux vm extensions failed with exit code 41. ( in the logs the error was:  curl: (6) Could not resolve host: acs-mirror.azureedge.net)

**What you expected to happen**:
the cse to not fail, and the curl to be able to download from https://acs-mirror.azureedge.net/cni/azure-vnet-cni-linux-amd64-v1.0.4.tgz

**How to reproduce it** (as minimally and precisely as possible):
use this deployment model: 
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Network/virtualNetworks/<redacted>/subnets/<redacted>",
      "firstConsecutiveStaticIP": "<redacted>",
      "vnetCidr": "<redacted>"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Network/virtualNetworks/<redacted>/subnets/<redacted>"
      },
      {
        "name": "windowspool2",
        "count": 1,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows",
	"vnetSubnetId": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Network/virtualNetworks/<redacted>/subnets/<redacted>"
      }
    ],
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": "<redacted>"
    },
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<redacted>"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "<redacted>",
      "secret": "<redacted>"
    }
  }
}

generate a template and set the dnsprefix, change the azuredeploy.json and add "subnet" : "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Network/virtualNetworks/<redacted>/subnets/<redacted>",
then deploy template.
**Anything else we need to know**:
when I SSH into the linux VMs and try to sudo I get this error: (sudo: unable to resolve host k8s-linuxpool1-38945190-0: Connection timed out)

**Log Files**
[handler.txt](https://github.com/Azure/acs-engine/files/2171000/handler.txt)
[cluster-provision.txt](https://github.com/Azure/acs-engine/files/2171001/cluster-provision.txt)
[cloud-init.txt](https://github.com/Azure/acs-engine/files/2171002/cloud-init.txt)

**Comment by jackfrancis** [comment]
@no-stupid-questions Is this error reproducible? Or did you run into transient DNS service flakiness during deployment?

If reproducible, there's probably something pathological in the linuxpool1 subnet network config (or in the way it's being represented in the api model above) that your linux hosts are being created into.

**Comment by no-stupid-questions** [comment]
I have consistently received this error after every deployment, as for the apimodel i got a few shoot in the dark:
Add "osType" : "Linux" 
Change "firstConsecutiveStaticIP": "172.31.49.254"  to "firstConsecutiveStaticIP": "172.31.49.230" ?
make all "vmSize": "Standard_D2_v3"


(a side note)
I ssh into my master linux vm and was able to fix the  "sudo: unable to resolve host k8s-linuxpool1-38945190-0: Connection timed out" by adding  k8s-linuxpool1-38945190-0 to the same line as localhost in /etc/hosts:
127.0.0.1 localhost k8s-master-38945190-0

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
(end of side note)

for the failing command in cluster-provision.log:
curl -fsSL https://acs-mirror.azureedge.net/cni/azure-vnet-cni-linux-amd64-v1.0.4.tgz -o /tmp/azure_cni.tgz

I found the ip of acs-mirror.azureedge.net and reran the command now i get the error "curl: (51) SSL: certificate subject name (*.azureedge.net) does not match target host name '23.79.217.132'" :

root@k8s-master-38945190-0:/etc/ssl/certs# curl -v https://23.79.217.132/cni/azure-vnet-cni-linux-amd64-v1.0.4.tgz -o /tmp/azure_cni.tgz
*   Trying 23.79.217.132...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 23.79.217.132 (23.79.217.132) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification OK
*        server certificate status verification SKIPPED
* SSL: certificate subject name (*.azureedge.net) does not match target host name '23.79.217.132'
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (51) SSL: certificate subject name (*.azureedge.net) does not match target host name '23.79.217.132'

**Comment by jackfrancis** [comment]
Is your VNET providing DNS? What does /etc/resolv.conf say?

**Comment by no-stupid-questions** [comment]
sorry for the late reply, here is my /etc/resolv.conf : 

root@k8s-master-38945190-0:/etc# more resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.17.16.11
nameserver 172.17.16.12
search reddog.microsoft.com

**Comment by CecileRobertMichon** [comment]
@no-stupid-questions this error is due to the fact that you are using custom DNS and `acs-mirror.azureedge.net` cannot be resolved. There are a number of resources that need to be accessed during deployment in order to install kubernetes and dependencies.

**Comment by no-stupid-questions** [comment]
@CecileRobertMichon What does the default DNS have/do to resolve mirror.azureedge.net that my custom DNS doesn't?
Or how could I find the info needed to compare the two DNS?
If thats not possible, is it possible to deploy the cluster with the default DNS, and then once kubernetes and dependencies are installed change to my custom DNS? (will my cluster still work after the switch?)

sorry I'm not very well versed in networking/routing/IP so please forgive me if my questions make no sense.

**Comment by CecileRobertMichon** [comment]
@axier implemented custom search domains in https://github.com/Azure/acs-engine/pull/2590 which be the solution for what you are trying to do, I'd suggest you look into it.

**Comment by no-stupid-questions** [comment]
"customSearchDomain": {
        "name": "vlabs.local",
        "realmUser": "vlabs",
        "realmPassword": "foobar"
}

@axier  @CecileRobertMichon Would "name":  be "name": "reddog.microsoft.com"? And is realmUser and realmPassword existing credentials for the search domain (if this is the case I have no idea what they are), or are these used to create new credentials?

**Comment by CecileRobertMichon** [comment]
@no-stupid-questions I realized my previous answer might not be relevant... I'll let @axier explain how to configure search domains (maybe it'd be a good idea to add some docs?) but in the meantime can you try switching to Azure DNS?
