### ISSUE TITLE
examples/networkpolicy/kubernetes-calico.json fails to apply

### ISSUE THREAD

**Issue by ozdanborne** [Azure/acs-engine#3448]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

---

**What version of acs-engine?**:

latest master

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 

**What happened**:

I tried to create a basic Kubernetes Cluster using calico as a network plugin but the example config fails to apply with the following error:

```
bin/acs-engine deploy --location westus2 --api-model examples/networkpolicy/kubernetes-calico.json --dns-prefix turk
WARN[0001] apimodel: missing masterProfile.dnsPrefix will use "turk" 
WARN[0001] --resource-group was not specified. Using the DNS prefix from the apimodel as the resource group name: turk 
INFO[0004] Error returned by LoadContainerService: networkPolicy 'calico' is not supported with networkPlugin 'azure' 
FATA[0004] Failed to validate the apimodel after populating values: %s networkPolicy 'calico' is not supported with networkPlugin 'azure' 
```

It seems to be defaulting to azure networkplugin when the networkplugin is blank with Calico.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

Calico works as a CNI plugin for Kubernetes. Calico does not work with Kubernetes if Kubernetes is using Kubenet networking.

The available options for Calico in ACS-Engine don't represent that: https://github.com/Azure/acs-engine/blob/master/pkg/api/vlabs/validate.go#L61-L68

```
		{
			networkPlugin: "kubenet",
			networkPolicy: "calico",
		},
		{
			networkPlugin: "",
			networkPolicy: "calico",
		},
```

I think it's an error to have "kubenet" as an available networkplugin without having "cni" as well. 

I'll throw out some proposed fixes to get the ball rolling:

1. Add a "cni" as a valid option for the networkPlugin field.
2. Treat an empty string to mean "cni".

I think this PR https://github.com/Azure/acs-engine/pull/3128 Fixed it at a lower level, but it needs to be fixed on the user-facing side as well.

**Comment by ozdanborne** [comment]
ping @jackfrancis

**Comment by CecileRobertMichon** [comment]
@ozdanborne Jack is on vacation this week, he'll take a look when he gets back. In the meantime, can you try deploying with kubenet? I think there's a workaround to artificially set the k8s plugin to cni when policy is calico (granted that should be improved, but it should unblock you for now).

**Comment by jackfrancis** [comment]
@CecileRobertMichon, FYI: @ozdanborne is working on integrating calico w/ Azure CNI.

So, yes, in your implementation work, you'll need to evolve the whitelist of allowed combinations, as you describe above. In this case, we want to add a novel inclusion:

```
{
			networkPlugin: "azure",
			networkPolicy: "calico",
}
```

And then of course we'll need to implement a working model of the above. :)
