### ISSUE TITLE
acs-engine docker image broken

### ISSUE THREAD

**Issue by apeschel** [Azure/acs-engine#3451]
@CecileRobertMichon Unfortunately, the currently published Docker image doesn't seem to be correctly formed: it's has a windows binary on a Linux base, and doesn't seem to use the Dockerfile in the repo.

There are instructions on how to build the image in the releases directory:

https://github.com/Azure/acs-engine/blob/master/releases/README.Dockerfile.md

Is seems like you're using Windows, based on the Docker image that was published, so the commands to run are probably as follows (I don't have a Windows machine available at the moment to verify):

```
PS> cd releases
PS> $VERSION="0.19.1"
PS> docker build --no-cache --build-arg BUILD_DATE=$(Get-Date((Get-Date).ToUniversalTime()) -UFormat "%Y-%m-%dT%H:%M:%SZ") --build-arg ACSENGINE_VERSION="$VERSION" -t microsoft/acs-engine:$VERSION --file .\Dockerfile.linux .
PS> docker push "microsoft/acs-engine:$VERSION"
```

**Comment by PatrickLang** [comment]
Ah, I see what you mean

```
PS> docker run -it microsoft/acs-engine:v0.19.1 sh
# pwd
/gopath/src/github.com/Azure/acs-engine
# ls bin
acs-engine.exe
```

**Comment by PatrickLang** [comment]
Unfortunately I can't fix this today, hopefully we can pick it up tomorrow.

**Comment by CecileRobertMichon** [comment]
@apeschel just pushed an updated image, please let me know if it works for you. You should be able to run ```PS> $VERSION="0.19.1"
PS> docker pull "microsoft/acs-engine:$VERSION"
PS> docker run -it microsoft/acs-engine:0.19.1````

**Comment by apeschel** [comment]
@CecileRobertMichon Tried it out and can confirm it looks good, thanks for the help!

**Comment by CecileRobertMichon** [comment]
Great, I realized I used the wrong Dockerfile the first time...
