### ISSUE TITLE
Provisioning of VM extension 'cse' has timed out.

### ISSUE THREAD

**Issue by mfaizanse** [Azure/acs-engine#346]
I have followed the steps in the readme and successfully generated the template but when I am deploy the template to azure, I am getting error "Provisioning of VM extension 'cse' has timed out.".

All the other resources are created successfully but the <vm_id>/cse resource take too much time on 'Provisioning Status: Running' and then Fails giving the error description as follows:

![capture](https://cloud.githubusercontent.com/assets/9897945/23498077/c6c9a2de-ff47-11e6-8d65-b9d7f14d9561.PNG)

What could be the issue?

**Comment by colemickens** [comment]
Can you confirm which git commit of ACS-Engine you were on?

**Comment by mfaizanse** [comment]
I pulled the repository yeasterday (1st march, 2017). The latest commit I have is commit b833b0b390613475b6cdd0ce9a7a1521f73dbead

**Comment by mfaizanse** [comment]
I even tried creating the kubernetes cluster usin the azure portal but still receiving the same error.

{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningTimeout",
        "message": "Provisioning of VM extension 'cse' has timed out. Extension installation may be taking too long, or extension status could not be obtained."
      }
    ]
  }
}

**Comment by colemickens** [comment]
@mfaizanse there is an issue affecting ACS right now: https://github.com/Azure/ACS/issues/9

This issue was fixed in ACS-Engine a matter of hours ago. When you filed this, I deployed a cluster and it came up successfully and I could see the Windows nodes. I haven't had a chance to deploy to it, but I expect it to work.

**Comment by mfaizanse** [comment]
@colemickens I pulled the latest commit 2 hours ago and generated a template and deployed it but the CSE stage is still in 'PROVISIONING STATE:Running' stage. Does it take this much time or should I pull again the latest commit and try again or wait?

**Comment by colemickens** [comment]
Can you clarify what commit you're on? You say you pulled two hours ago, but you commented an hour ago and had a commit from yesterday?

If you're not on the very latest commit, you could still be seeing this. I just deployed another hybrid cluster and it also worked.

**Comment by mfaizanse** [comment]
@colemickens yes, I was on the yesterday's commit when I post the comment, but after that I pulled the latest repository and deployed again. I am going to again pull the latest commit and try again. i will let you know if the issue persists. Thank you for your support :)

**Comment by mfaizanse** [comment]
@colemickens 
I pulled the latest commit and followed the "Downloading and Building ACS Engine Locally For windows" section from this [guide](https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md#downloading-and-building-acs-engine-locally).

![1](https://cloud.githubusercontent.com/assets/9897945/23506694/5aa5d7c0-ff6b-11e6-83a4-480f1d18b4c6.PNG)

I modified the examples/windows/kubernetes.json file to enter DNSprefix and service principal details.
Then I used the "acs-engine examples/windows/kubernetes.json" command to generate the template.

After that I [deployed the template](https://github.com/Azure/acs-engine/blob/master/README.md#deploying-with-powershell) to azure using powershell.

But now its been more than 40 minutes and the CSE is still in 'PROVISIONING STATE:Running'. It means that the deployment will fail after 90 minutes.

![2](https://cloud.githubusercontent.com/assets/9897945/23506924/702cce86-ff6c-11e6-9304-7ff1cb66e80d.PNG)

![3](https://cloud.githubusercontent.com/assets/9897945/23506925/71ab2b86-ff6c-11e6-9769-08e1fdc3f2a2.PNG)

Is there any way to debug the issue on my side as you have mentioned that you have successfully created a cluster?

**Comment by colemickens** [comment]
Are you able to contact the apiserver? Try to list nodes. If that doesn't work, SSH into the master and try to see if any of the systemd units failed.

Other than that, try to ping me on Slack and we can debug together.

**Comment by mfaizanse** [comment]
@colemickens 
I did SSH into the master and tried "kubectl get nodes" and got error:
![5](https://cloud.githubusercontent.com/assets/9897945/23541067/dc550e76-0006-11e7-967a-87d048742e39.PNG)

Can you mention which script its runs in CSE stage on windows agents?

P.S. I am not invited in Slack so I cannot ping you.

**Comment by colemickens** [comment]
k8s slack is public: http://slack.k8s.io/

**Comment by colemickens** [comment]
Can you check these troubleshooting steps, it's possible that's the culprit: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md#troubleshooting

**Comment by mfaizanse** [comment]
Yes, that was the culprit. I generated new service principal and created a cluster successfully. But now on master node I am getting kubectl: command not found. I checked the systemmd failed units and got:

● cloud-final.service     loaded failed failed Execute cloud user/final scripts
● hv-fcopy-daemon.service loaded failed failed Hyper-V File Copy Protocol Daemon
● kubectl-extract.service loaded failed failed Kubectl extraction

**Comment by mfaizanse** [comment]
I think I should pull the latest commit and try as the new commit's comment says the same thing. :)

**Comment by mfaizanse** [comment]
The CSE failure issue has been resolved but currently stuck on kubectl extraction issue. Closing this thread.

**Comment by MirzaSikander** [comment]
Do you know which version of ACS-engine this is fixed in? I am running into the exact same issue.
