### ISSUE TITLE
add Kata Containers as a valid runtime

### ISSUE THREAD

**Issue by egernst** [Azure/acs-engine#3463]
**Is this a request for help?**:

No.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

This is a FEATURE REQUEST

---

**What version of acs-engine?**:

All of them

---

 
Would love to s/Clear/Kata for original Clear Containers PR, adding support for Kata Containers (kata-runtime).  Eventually we will want to consider deprecating Clear Containers (cc-runtime). 
 

**How to reproduce it** (as minimally and precisely as possible):

Grep for Kata

**Anything else we need to know**:

I'm reviewing the original PRs from @jessfraz which added Clear Container support as well as ACS-engine now, and hope to submit an initial PR to add this support.

**Comment by egernst** [comment]
thx @CecileRobertMichon  - I think I'm not part of the "organization", so could not self-assign.

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/pull/3465
