### ISSUE TITLE
kube-dns sidecar container doesn't expose metrics

### ISSUE THREAD

**Issue by kovszilard** [Azure/acs-engine#3479]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: ALL

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**: Running a kubernetes cluster

**What you expected to happen**: kube-dns should expose metrics in Prometheus format as in other cloud providers

**How to reproduce it** (as minimally and precisely as possible): Install cluster using acs engine

**Anything else we need to know**: If you check the original kube-dns addon https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube-dns/kube-dns.yaml.base you can see that the sidecar container exposes a metrics endpoint on port 10054. This metrics are very useful and monitoring tools like prometheus-operator try to scrape it by default.

Related issues:
https://github.com/Azure/AKS/issues/345

**Comment by StianOvrevage** [comment]
We're also hitting this now. It appears that kube-dns on AKS/ACS does not include the sidecar container.

Also of possible interest: https://github.com/kubernetes/dns/blob/master/docs/sidecar/README.md

**Comment by kovszilard** [comment]
https://github.com/Azure/acs-engine/pull/3373 fixed the issue
