### ISSUE TITLE
etcd tls config

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#349]
We don't configure tls for etcd. We should.

**Comment by wangtt03** [comment]
@anhowe @colemickens if you didn't start this one. I think I can take it.

**Comment by anhowe** [comment]
@wangtt03 please rebase / remove "expected" files in #397, and we will approve.

**Comment by wangtt03** [comment]
@anhowe I did a rebase and could you please review PR #397 ? Thanks!

**Comment by CecileRobertMichon** [comment]
Etcd TLS is implemented as of v0.12.0
