### ISSUE TITLE
Should setup container log retention policy on master & agent node

### ISSUE THREAD

**Issue by yangl900** [Azure/acs-engine#350]
## Problem
Master node stops working for everything and claim etcd failure or it is not configured correctly.

## Root Cause
Looking into logs we found that the master node container log has taken 27 GB and used all disk space in OS disk. The cluster has been running for ~2 months.

## Proposed Fix
Setup log retention policy so we never run out of disk space.

**Comment by colemickens** [comment]
@yangl900 Ah, were the huge files: `/var/lib/docker/containers/[CONTAINER ID]/[CONTAINER_ID]-json.log`?

We should mitigate this short term with some sort of log rotations, long term presumably we'd want to run fluentd w/ logrotate and push cluster logs to some storage system...

**Comment by yangl900** [comment]
That's correct. Note that the file is holding by the running container, we had to restart in order to remove the file completely.

@brendandburns @anhowe as FYI, I think we should take this as a high priority fix. we cannot run cluster in production without the rotation.

**Comment by brendandburns** [comment]
Yes, we should add this ASAP.  The 'logrotate' tool is a good simple tool to add.

--brendan


________________________________

**Comment by rjtsdl** [comment]
I am looking into this problem.

Currently, the reason that docker daemon created multiple `/var/lib/docker/containers/[CONTAINER ID]/[CONTAINER_ID]-json.log` files, is because, docker daemon is using the default log-driver : json-file. 

Now i have two options for the short term purpose:
1. Keep using json-file log-driver for docker, then we can leverage docker's option like `max-size` to limit the size.

2. Change log-driver to journald, in this way, we can leverage journald's log rotation strategy to manage docker along with other daemons. 

I personally prefer option 2. However, i may overlook some issues, such as backward compatibility.

**Comment by colemickens** [comment]
I like option 2 as well, and I doubt we're going to end up supporting any distros that don't use systemd anyway.

**Comment by tekmaven** [comment]
This may become a problem on Windows Agents I'm assuming, so that needs to be considered.

**Comment by rjtsdl** [comment]
#373 

@anhowe @JiangtianLi , how do you guys think about Windows Agents concern?

**Comment by colemickens** [comment]
It'd be one thing if if the Windows Service was harvesting the output of `kubelet` on windows, but instead we're writing out to a text file manually. Does NSSM take care of pumping stdout/err to Windows logs? If so, that might be easiest.

**Comment by JiangtianLi** [comment]
@rjtsdl @colemickens The issue that is solved here is docker/container logs, not kubelet logs, right? What is kubelet log retention policy on Linux? A quick look at NSSM doc and it has some rotation parameters.

**Comment by colemickens** [comment]
`kubelet` runs as a container in Linux, so it's solved by this fix as well. Otherwise it would run as a bare systemd unit, which also already has log rotation. Hence my remarks about WinService logs + NSSM. I just don't know Windows well enough to know what the convention is.

**Comment by anhowe** [comment]
In Windows, log rotation is handled in the NSSM setup here: https://github.com/Azure/acs-engine/blob/master/parts/kuberneteswindowssetup.ps1#L232-L270

**Comment by rjtsdl** [comment]
Just merged the PR. I will close the issue here. 

For existing clusters, try to do modification showed in PR #373 
After that, do 
```
sudo rm -rf /var/lib/cloud/instances
sudo cloud-init -d init
sudo cloud-init -d modules -m config
sudo cloud-init -d modules -m final
sudo systemctl restart kubelet
```

**Comment by colemickens** [comment]
This was the related PR: https://github.com/Azure/acs-engine/pull/373

For a less invasive workaround, the user can just manually cleanup `/var/lib/docker/containers` after making the systemd unit change. They'll likely also need to reboot the machine, or `systemctl daemon-reload` to activate the change as well.

**Comment by colemickens** [comment]
@anhowe AFAICT... that doesn't prevent this problem on Windows. The Windows agents just pile up 1MB files. It looks like eventually it will run out of space too. Is this not the case?

**Comment by rjtsdl** [comment]
From Anders's latest found. 
"The master log seems has been moved to syslog and kernel log, but it doesn’t get rotate. "

**Comment by colemickens** [comment]
syslog? really? It might be piling up in journald, but I wouldn't expect to see it in syslog... Is that really what the "journald" driver does?

**Comment by rjtsdl** [comment]
After take a look of Anders's cluster's master node, here is what i found.

1. The node doesn't have a /var/log/journal folder, and the default Storage=auto, that means, we don't have persistent log. This will equal to Storage=volatile, all the logs will only be stored in memory, corresponding to /run/log/journal hierarchy. So the journald's log is not consuming the disk.

2. By default, journald will forward logs to syslog, so it is syslog manage the logrotation. under folder /var/log/*.log

3. Check, /etc/logrotate.d/rsyslog, it document how the syslog and kern log get rotated. Looks syslog doesn't have all the nice features like journald. It only provides how often to do rotate, and how much time duration of data kept. So it cannot detect when disk usage > max_threshold, there is no such thing in logrotate.d. But it is available in journald.

These are options for resolution.
1. Don't forward to syslog or anything else, we keep everything under control of journald
2. Customize the /etc/logrotate.d/rsyslog config. 

@yangl900 @anhowe @colemickens ,
How do your guys think?

**Comment by colemickens** [comment]
I definitely don't know best practices or anything, but #1 seems easiest? And journald seems more of the future direction of systemd-based linux systems? But that's not a strong opinion at all.

**Comment by yangl900** [comment]
If we persist the logs in disk, seems #1 is better to me. 

Also, maybe we should separate the logs into another data disk, so even it's full, it doesn't hurt master etcd. If that's reasonable, can we track that as an issue too?

**Comment by rjtsdl** [comment]
Ok, Let me try #1. I will update when i have a PR ready.
I assume we need to have a customized journald.conf file, where we mark Storage=persist.

**Comment by rjtsdl** [comment]
#444 is the fix using #1. Please review.

**Comment by rjtsdl** [comment]
@yangl900 after this fix, all the logs, include kern.log and syslog, will be stored under /var/log/journal/ hierarchy. So for your request to save it in a separate disk. It should be as simple as mount a disk at /var/log/journal. 

And BTW, with this fix, it will not use more than 10% of the total disk space.

**Comment by rjtsdl** [comment]
@yangl900, the fix has merged. I will close this issue. Thanks!
