### ISSUE TITLE
Kubernetes: AAD + v1.11 clusters

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#3505]
We have reports that the current AAD implementation does not work w/ 1.11 clusters:

Works on v1.10.5 - 
1.	Make sure you have a MSFT user (this is because MSFT has lots of AAD groups)
2.	Create an ACS-Engine cluster using the attached template
3.	Once your cluster is ready, try to run any kubectl command, it will ask for AAD auth with a code
4.	Complete aad authentication
5.	The operation will fail because of two reasons:
1.	Since you are a member of over 200 groups, the groups claim token is cut and will look like that:
"_claim_names": {
 "groups": "src1"
},
this already has an open issue for a few months now (link)
2.	You are not a member of the admin group written in the template (but it's irrelevant)
6.	The error message will look like that:
Error from server (Forbidden): pods is forbidden: User "https://sts.windows.net/<TENANT_ID>/#<USER_ID>" cannot list pods in the namespace "default"
7.	Give your specific user permissions, using:
kubectl create clusterrolebinding aad-default-cluster-admin-binding --clusterrole=cluster-admin --user https://sts.windows.net/<TENANT_ID>/#<USER_ID>
8.	Try the kubectl command again, this time it will work

Doesn't works on v1.11.0 - 
1.	Make sure you have a MSFT user (this is because MSFT has lots of AAD groups)
2.	Edit the attached template and change the kubernetes version from v1.10 to v1.11, like that:"orchestratorRelease": "1.11"
3.	Create an ACS-Engine cluster using the edited template
4.	Once your cluster is ready, try to run any kubectl command, it will ask for AAD auth with a code
5.	Complete aad authentication
6.	The operation will fail because of two reasons:
1.	Since you are a member of over 200 groups, the groups claim token is cut and will look like that:
"_claim_names": {
 "groups": "src1"
},
this already has an open issue for a few months now (link)
2.	You are not a member of the admin group written in the template (but it's irrelevant)
7.	The error message will look like that:
error: the server doesn't have a resource type "pods" (this time it's different)
8.	Give your specific user permissions, using:
kubectl create clusterrolebinding aad-default-cluster-admin-binding --clusterrole=cluster-admin --user https://sts.windows.net/<TENANT_ID>/#<USER_ID>
9.	Try the kubectl command again, this time it will still not work, with the same error:
error: the server doesn't have a resource type "pods"
10.	The real problem is that the user is not getting authenticated (and the API returns 401)

* The kubectl client version should be v1.11.0

**Comment by idanlevin** [comment]
@jackfrancis any update on this? anyone working on it?

**Comment by jackfrancis** [comment]
Hi @idanlevin, no updates at this time, I'm not aware that this has traction atm.

Sorry for the bad news :(

**Comment by pavelsmejkal** [comment]
@idanlevin @jackfrancis  if you don't need resolve groups you can workaround it for cluster creation by

sed -e '/oidc-groups-claim/d' -i.backup _output/*/apimodel.json
sed -e 's/\\\\\\"--oidc-groups-claim=groups\\\\\\", //g' -i.backup _output/*/azuredeploy.json

not sure about cluster upgrades

**Comment by idanlevin** [comment]
We eventually ended up using Guard which works perfectly :)

**Comment by kyschouv** [comment]
Is there a fix in the works for this at any point? I'd prefer not have to manage Guard separately if possible.
