### ISSUE TITLE
Implement parallel unit tests?

### ISSUE THREAD

**Issue by tariq1890** [Azure/acs-engine#3513]
As there are many table driven unit tests, they can be easily parallelized if one were to use the subtests feature of Go 1.7.

Is this something worth working towards? It could possibly shave a few seconds (or even minutes) off of build times if we could parallelize as many as unit tests as possible. This would, however, entail mandating Go 1.7 as the minimum version.

More details in the PR #3512

**Comment by CecileRobertMichon** [comment]
If we do this it'd be worth changing the Go prereq in https://github.com/Azure/acs-engine/blob/master/docs/developers.md#prerequisites to 1.7

**Comment by tariq1890** [comment]
@CecileRobertMichon Yes. It could be a breaking (I could b wrong here) change for acs-engine users who are using Go 1.6 runtimes. I'd leave it up to you and @jackfrancis to decide on this :).
