### ISSUE TITLE
hyperkube image is not pulled while creating kuberenetes cluster using acs-engine

### ISSUE THREAD

**Issue by praneethr** [Azure/acs-engine#3538]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.20.0
---

While Creating kubernetes cluster using ACS-Engine, Got Quota Exceeded error while downloading hyperkube..
httpReaderSeeker: failed open: unexpected status code https://k8s-gcrio.azureedge.net/v2/hyperkube-amd64/blobs/sha256:7460c29cea530abb10d39c00e52718293cd0969fed8d5f581cff38fd2d6bd550: 429 Too Many Requests

Below is the error message after deploying ARM template

  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=98\n[stdout]\n\n[stderr]\n\"."
      }
    ]
  }
}

Once loggedin to Master Node VM in cluster-provisioning.log, below is the error

httpReaderSeeker: failed open: unexpected status code https://k8s-gcrio.azureedge.net/v2/hyperkube-amd64/blobs/sha256:7460c29cea530abb10d39c00e52718293cd0969fed8d5f581cff38fd2d6bd550: 429 Too Many Requests

Even existing cluster when scaled up got below error .

error parsing HTTP 429 response body: invalid character 'Q' looking for beginning of value: "Quota Exceeded."
+ '[' 1 -eq 0 ']'
+ '[' 100 -eq 100 ']'
+ echo Executed '"docker' pull 'k8s-gcrio.azureedge.net/hyperkube-amd64:v1.10.2"' 100 times
Executed "docker pull k8s-gcrio.azureedge.net/hyperkube-amd64:v1.10.2" 100 times
+ return 1
+ exit 31

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What you expected to happen**:
Cluster Creation

**How to reproduce it** (as minimally and precisely as possible):
kuberenetes cluster creation using acs-engine or pulling hyperkube using below commands
docker pull k8s-gcrio.azureedge.net/hyperkube-amd64:v1.10.2
 img pull k8s-gcrio.azureedge.net/hyperkube-amd64:v1.10.2

**Comment by jackfrancis** [comment]
Was this in eastus?

**Comment by jackfrancis** [comment]
See my explanation in #3537. If not eastus, please re-open!

**Comment by praneethr** [comment]
Thanks @jackfrancis  for the explanation
