### ISSUE TITLE
Question - custom OS image on a custom VNET

### ISSUE THREAD

**Issue by eosfor** [Azure/acs-engine#3547]
Hello colleagues, i need to use my own corporate OS image stored in the subscription image repo (azure vm image). and i need to provision all of this into custom vnet/subnets. May i ask you to point me out to a proper example template, so i can start from there?

**Comment by jackfrancis** [comment]
Hi @eosfor, this is not really a working scenario in acs-engine at this time, but you could follow this PR:

https://github.com/Azure/acs-engine/pull/3536

That aims to generalize the OS + application layer paving into a custom VHD image. Perhaps there are hints therin?

**Comment by eosfor** [comment]
Hi @jackfrancis, I've found below two options in the documentation. What are they, in this case, if you are saying that this scenario "is not really working"?

```json
"imageReference": {
      "resourceGroup": "images",
      "name": "imagesource"
}
```

**Comment by eosfor** [comment]
Hi @jackfrancis, i tested this and it seems to work. I mean if you specify resourceGroup and name it seems picking up a VM image from them. What i'd also add is another parameter, like "SubscriptionID", so an image can be picked up from the different subscription.

**Comment by jackfrancis** [comment]
Stand by @eosfor, we are working on something that may have utility for you. PR
https://github.com/Azure/acs-engine/pull/3536 is an example of the work we're doing to source from a custom OS image (pre-built w/ application binaries). That implementation could lead to future related feature that sources OS images (including from external RGs/VNETs) as a 1st class feature.
