### ISSUE TITLE
Is there a way to provide hostnames?

### ISSUE THREAD

**Issue by gitphill** [Azure/acs-engine#3549]
**Is this a request for help?**: YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST (unless there is a way to do this?)

---

**What version of acs-engine?**: 0.20.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

**What happened**: acs-engine generated hostnames for me

**What you expected to happen**: for there to be a way of customising the master and agent hostname (prefix)

**How to reproduce it** (as minimally and precisely as possible): acs-engine generate

**Comment by jackfrancis** [comment]
In the api model (cluster configuration JSON file) that you use as input to acs-engine:

The "dnsPrefix" value will help to form the hostname prefix for the master nodes:

https://github.com/Azure/acs-engine/blob/master/examples/kubernetes.json#L9

And for each agent, the agent pool "name" value will do the same:

https://github.com/Azure/acs-engine/blob/master/examples/kubernetes.json#L14
