### ISSUE TITLE
Is there a way that acs-engine can generate additional resource into azuredeploy.json?

### ISSUE THREAD

**Issue by Rickion** [Azure/acs-engine#3557]
**Is this a request for help?**:
YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

---

**What version of acs-engine?**:
v0.14.6

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Cannot generate additional resource into azuredeploy.json. 

**What you expected to happen**:
A config option as input that acs-engine can used to generate resources automatically.
Like, I want to add PS DSC extension into every node of my cluster, can the deploy file, generated by acs-engine, do it ?

**How to reproduce it** (as minimally and precisely as possible):
acs-engine generate someConfig.json

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
@Rickion Can you expand on what a PS DSC extension is?

**Comment by Rickion** [comment]
Hi @jackfrancis , it's an extension for a single VM to help users to config. ([More details here](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/dsc-overview)) 

![image](https://user-images.githubusercontent.com/13317720/43300613-b953d0fa-9192-11e8-9640-c762406b2fd7.png)

And we can use ARM template to add it to a VM like [this](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/dsc-template). I wondered if ace-engine can integrate this resource when generating cluster deploy files.

**Comment by CecileRobertMichon** [comment]
See https://github.com/Azure/acs-engine/blob/master/docs/extensions.md

**Comment by Rickion** [comment]
I have read this article before. But it seems too complicated for my scenario. So I wrote my own python script to insert resources into azuredeploy.json. Easy for me.

Closing this since having no more requests.
