### ISSUE TITLE
Executing a custom cloud-init script

### ISSUE THREAD

**Issue by palmerabollo** [Azure/acs-engine#3558]
**Is this a request for help?**:
YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

---

**What version of acs-engine?**:
0.16.2+

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I am not able to configure a custom script to be run on every new node in the cluster.

**What you expected to happen**:
I was expecting to have something like [kops "additional user-data for cloud-init"](https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#additional-user-data-for-cloud-init) where you can declare additional scripts to be executed at boot time to initialize or setup the nodes.

**How to reproduce it** (as minimally and precisely as possible):
-

**Anything else we need to know**:
-

**Comment by jackfrancis** [comment]
Hi @palmerabollo. acs-engine doesn't have a super clean interface to do this, but we do have, shall I say, a functional one. See this example for an "extension" that installs prometheus and grafana.

That example demonstrates running the extension against an agent pool; you can specify in your api model that you want to attach to your master nodes as well (`masterProfile` accepts an `extensions` child property)

**Comment by palmerabollo** [comment]
Thanks @jackfrancis, could you please add the link to the example?

**Comment by jackfrancis** [comment]
whoops!

https://github.com/Azure/acs-engine/tree/master/extensions/prometheus-grafana-k8s
