### ISSUE TITLE
How to recover from out of sequence node names

### ISSUE THREAD

**Issue by kruthe01** [Azure/acs-engine#3568]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.16.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10.2

**What happened**:
We have a cluster with two nodepools, one containing multiple cpu-only nodes, and one containing gpu nodes. The gpu nodepool had one node (named xxx-0), and for reasons that aren't important to this discussion, we needed to remove that node from the cluster and replace it with a new node.

We tried draining the node and using "acs-engine scale" to scale back to 0 nodes in the nodepool, but acs-engine didn't allow a new-node-count of 0.

Due to the issue is described in https://github.com/Azure/acs-engine/issues/2148 (which we discovered after getting ourselves into this situation), we were unable to remove the bad node (xxx-0), so we scaled out to a second node and manually removed the bad node using "kubectl delete node xxx-0".

Unfortunately, now using "acs-engine scale" to scale out/in results in incorrect behavior because the names of the nodes are no longer in sequence (there is no xxx-0 node).

Is there a reasonable way to recover from this situation so that scaling out/in will work properly, going forward, with acs-engine?

**What you expected to happen**:
At this point we just want to recover from the state where acs-engine is "out of sync" with the existing node names in the gpu nodepool.

**How to reproduce it** (as minimally and precisely as possible):
Use acs-engine to create a cluster with one node. Scale out to two nodes using "acs-engine scale". Manually remove the original node using "kubectl delete node" and update the apimodel.json file to set the node count to 1. At this point, scaling out and then scaling back in removes the wrong node, or tries to remove a node that doesn't exist.

**Anything else we need to know**:
No.

**Comment by CecileRobertMichon** [comment]
Hi @kruthe01 could you try with the latest acs-engine version? https://github.com/Azure/acs-engine/pull/3644 might help your case. You could try scaling down to the number of nodes left and then scaling up again.

**Comment by kruthe01** [comment]
Hi @CecileRobertMichon, thanks for the reply. Currently, we have one node running in our gpu agent pool, with a node name ending in -3. The apimodel.json file for the cluster currently has "count: 1" for the gpu agent pool. Is there anything I should do to the cluster or the apimodel.json file before trying this? Or should I simply download the latest acs-engine executable and scale down/up using the existing cluster configuration?

**Comment by CecileRobertMichon** [comment]
You should try scaling up to 3 nodes then scaling back down to 1. That should help with the indexes. After that, try to upgrade to make sure everything is okay. Note that this is NOT an officially supported scenario, just suggesting something that might help your situation. If this a production cluster, I would suggest building a second cluster and trying to reproduce the state you are at now and trying to fix that first so you have some kind of guarantee that it works.
