### ISSUE TITLE
[Feature Request] Script Hook

### ISSUE THREAD

**Issue by wbuchwalter** [Azure/acs-engine#357]
Hi,
There are some cases where we need to install a dependency on every node of a cluster.
For example, when setting up an ACS cluster for GPU workloads, I need to install the driver on every GPU-capable host.
 
Would you be open, on principle, to enable a “scripting hook” in acs-engine that would enable running custom scripts on the different agent pools, for example:
 
``` json
     "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        “preInstallationScript” : “something.blob.core.windows.net/scripts/myscript.sh”
      }
    ]
``` 
 
At the end of the day this script would be embedded at the top of the corresponding agent pool custom data, or as another VMExtension.
 
Since I’m not a big expert in acs-engine, I may be missing some stuff here.

**Comment by colemickens** [comment]
(Your text has smart quotes, that's why the highlighting is bad.)

cc: @RobBagby who is building this.

**Comment by smartbit** [comment]
#79 _For DCOS, there is a custom script extension that runs on the last master._ 

Seems to solve your request for DCOS, although I haven't found out where to enable this CSE.

**Comment by wbuchwalter** [comment]
@smartbit My request is orchestrator-agnostic, I would like this to work on k8s as well, and before running `mesos-agent` or `kubelet` on the nodes.
@robbagby is working on this and will submit a PR soon-ish.

**Comment by minherz** [comment]
Hello, is there any progress with the feature? I see that the built template contains entries of type CustomExtension which are configured to execute powershell command. Would it be possible to expose a variable that will setup the command for the extension?
