### ISSUE TITLE
not able to deploy ACS templates to firewalled VNET

### ISSUE THREAD

**Issue by PaulCharlton** [Azure/acs-engine#3571]
**Is this a request for help?**:

This is not a request for help.  PR https://github.com/Azure/acs-engine/pull/3570 filed concurrently

**What version of acs-engine?**:

Commits to Master from June 1 2018 to July 26, 2019

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

tried with
1.8.11 -> 1.10.5

**What happened**:

The tests with `nc -v 8.8.x.x 53` use port 53, which is blocked by common corporate firewall and network security group settings.   Subsequently, the entire deployment with an ACS provided template failed.

**What you expected to happen**:

Expected outbound networking check to use common routes through corporate firewall and network security group rules.

**How to reproduce it** (as minimally and precisely as possible):

create a custom VNET, add security rules which block outbound port 53, try to deploy an ACS template using nodes connected to the custom VNET.   will fail.

**Anything else we need to know**:

the new code is more portable -- not tied to choice of domains too much, other than chose a commonly used DNS name "www.google.com" likely to be whitelisted by most corporate firewall rules, and also "www.1688.com" which is generally available behind the "great firewall of china".   Feel free to change or add domains.

**Comment by eosfor** [comment]
+1 to this. it is better to use something else, but not DNS for outbound connectivity testing

**Comment by CecileRobertMichon** [comment]
fixed in #3570
