### ISSUE TITLE
Node auto restart issue

### ISSUE THREAD

**Issue by dani07** [Azure/acs-engine#3572]
**Is this a request for help?**:

--- This is a request for help.

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

--- This is an ISSUE

**What version of acs-engine?**:

--- Commits to Master from May 1 2018 to May 15, 2018

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

--- Kubernetes version v1.10.2 

**What happened**:

--- A Working node (VMSS) got restarted automatically causing all the pods in that node to go down.

**What you expected to happen**:

--- VMSS not unexpectedly restarting. 

**How to reproduce it** (as minimally and precisely as possible):

--- Couldn't reproduce it. Happening unexpectedly and often.
 
**Anything else we need to know**:

--- VMSS Details: 

 Kernel Version:             4.13.0-1016-azure

 OS Image:                   Ubuntu 16.04.4 LTS

 Operating System:           linux

 Architecture:               amd64

 Container Runtime Version:  docker://1.13.1

 Kubelet Version:            v1.10.2

 Kube-Proxy Version:         v1.10.2

Attached is the syslog we collected from that time. 

[syslog-k8s-tier2-26881154-vmss00000K.txt](https://github.com/Azure/acs-engine/files/2234867/syslog-k8s-tier2-26881154-vmss00000K.txt)

**Comment by tariq1890** [comment]
Hey @dani07 , How often do you face this issue? Also, if you could provide the apimodel.json, that would be extremely helpful
