### ISSUE TITLE
Question: cloud-init

### ISSUE THREAD

**Issue by eosfor** [Azure/acs-engine#3574]
Hello colleagues, is cloud-init a hard dependency? I mean, it it a strict requirement for it to exist?

**Comment by CecileRobertMichon** [comment]
Hi @eosfor, could you please clarify your question? I'm not sure I understand what you mean. Why would you not want cloud-init? We mostly use it to write files to VMs and run a few commands on boot but would definitely be open to hearing about any alternatives you might be thinking about.

**Comment by eosfor** [comment]
Sure, for example because of some corporate policies. Everything which is not corporate-based is prohibited. Say you got an image in the cloud which comes from corporate image repo and the only thing that is different in it compared to the internal image is azure agent. smth like that

**Comment by CecileRobertMichon** [comment]
@eosfor I would say that today, cloud-init is a dependency in acs-engine and is required for cluster deployments.
