### ISSUE TITLE
Which version go-bindata used

### ISSUE THREAD

**Issue by khenidak** [Azure/acs-engine#358]
https://github.com/Azure/acs-engine/commit/4b20f1a3e96488680187a48295636afcd77c72d2#diff-5bb1dcfa4b1bb0b6da310acce6053f35R3

this "-nometadaa" flag is breaking "make build". Are you using a more recent version of go-bindata?

**Comment by colemickens** [comment]
Yes, we use the latest of go-bindata. If you use the docker container, this is all automated.
