### ISSUE TITLE
Cross-compile from Linux fails

### ISSUE THREAD

**Issue by jjjordanmsft** [Azure/acs-engine#3580]
**Is this a request for help?**:
No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

**What version of acs-engine?**:
This seems to have broken in commit `b2724579cef7fcde2bfd2f123f37b9721f36dcae` (tagged `v0.20.1-rc.1`)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
N/A

**What happened**:
When cross-compiling from `devenv.sh`, I get this error, repeated several times, and a failed build:
```
vendor/golang.org/x/text/unicode/rangetable/tables9.0.0.go
gen.go:172: Could not locate package: cannot find package "golang.org/x/text" in any of:
        /usr/local/go/src/golang.org/x/text (from $GOROOT)
        /gopath/src/golang.org/x/text (from $GOPATH)
exit status 1
```

This used to work for me, but has failed since the commit above (found via a rather lengthy binary-search).

**Workarounds**
As a workaround, I can `go get golang.org/x/text` prior to the `make build-cross`, but this feels wrong to me, particularly since that package is vendored.

An alternative workaround is to rev the `GO_VERSION` in `Dockerfile` to `1.10.3`, and maybe 1.9 would work too, but this probably has other side-effects.

**What you expected to happen**:
To build `acs-engine.exe` etc out of the box.

**How to reproduce it** (as minimally and precisely as possible):
Run `make build-cross` from `devenv.sh` in a clean acs-engine sandbox.

**Comment by tariq1890** [comment]
This should be fixed once #3770 is closed
