### ISSUE TITLE
GPU Nodes are not provisioned with the nvidia.com/gpu attribute inside the westus2 region

### ISSUE THREAD

**Issue by karlmutch** [Azure/acs-engine#3603]
**Is this a request for help?**:
---
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Issue

**What version of acs-engine?**:
---
acs-engine version
Version: v0.19.5
GitCommit: c8feb6ce
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10

**What happened**:
ND6s machines in one region, westus2, do not have the nvidia.com/gpu resource on their k8s node resource. 

**What you expected to happen**:
I expected that the nvidia.com/gpu would appear in the same manner as it does inside eastus.

**How to reproduce it** (as minimally and precisely as possible):
Use acs-engine to create a cluster in the westus2 region, using the following json file as your api-model
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 1,
        "vmSize": "Standard_ND6s",
        "OSDiskSizeGB": 200,
        "availabilityProfile": "VirtualMachineScaleSets"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
     "clientId": "",
     "secret": ""
    },
    "certificateProfile": {}
  }
}
```
```
acs-engine deploy --resource-group $k8s_resource_group --subscription-id $subscription_id --dns-prefix $k8s_resource_group --location westus2 --auto-suffix --output-directory test_gpu --api-model [file above]
```
Once everything completes use the kubectl get nodes command and observe that there is no nvidia.com/gpu.

Now use  eastus as your --location value and observe that the nvidia.com/gpu can be seen when doing a kubectl describe node.

**Anything else we need to know**:
Originally logged using MSFTs internal bug tracking under support request id 118072718667355

**Comment by CecileRobertMichon** [comment]
This was fixed in [0.20.0](https://github.com/Azure/acs-engine/releases/tag/v0.20.0)
