### ISSUE TITLE
azure-cni-networkmonitor and kube-proxy getting the same ip addresses

### ISSUE THREAD

**Issue by galniv1** [Azure/acs-engine#3615]
**Is this a request for help?**:

---yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---issue

**What version of acs-engine?**:

---v0.20.2

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes

**What happened**:
azure-cni-networkmonitor got the same ip address as kube-proxy

**What you expected to happen**:
both of them having the same ip addresses eliminates the ability to communicate with them

**How to reproduce it** (as minimally and precisely as possible):
All I did was deploying Istio on the machine.
I honestly did not check if this had happened before I tried to do anything on the machine.
I don't think it makes any difference(whatever I did)
**Anything else we need to know**:
![untitled](https://user-images.githubusercontent.com/42114133/43685968-7a781522-98c6-11e8-9e71-93ba3fbda85c.png)

**Comment by sharmasushant** [comment]
This is not brewing. Both of them use host networking. There should not be any issue here. Is there an issue other than both getting same ip? Can you elaborate a bit on what communication you are trying with these pods?
