### ISSUE TITLE
Can't ensure loadbalance when using vmss

### ISSUE THREAD

**Issue by birdemily** [Azure/acs-engine#3621]
**Is this a request for help?**:yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):issue

---

**What version of acs-engine?**:V0.20.2

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes v1.10.6

**What happened**:

when I create Loadbalancer on the cluster. It will failed with below error:

Normal   EnsuringLoadBalancer        25m (x18 over 1h)   service-controller  Ensuring load balancer
  Warning  LoadBalancerUpdateFailed    48s (x22 over 36m)  service-controller  (combined from similar events): Error updating load balancer with new hosts map[20121acs000003:{} 20121acs000009:{} k8s-master-20121002-0:{} 20121acs000001:{} 20121acs000005:{} 20121acs000006:{} 20121acs000007:{} 20121acs000008:{} 20121acs000002:{} k8s-master-20121002-2:{} k8s-master-20121002-1:{} 20121acs000000:{} 20121acs000004:{}]: Scale set "k8s-windowspool1-20121002-vmss" not found

**What you expected to happen**:
create Service successfully

**How to reproduce it** (as minimally and precisely as possible):
The api model we use is as below. Create windows cluster and deploy service with LoadBalancer type.
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.10.0"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "acs0202",
      "vmSize": "Standard_D4_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "windowspool2",
        "count": 2,
        "vmSize": "Standard_D14_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "osType": "Windows",
        "OSDiskSizeGB": 300
      }
    ],
…
}

**Anything else we need to know**:
When I update the name of vmss to “primaryScaleSetName”, it works well. I suspect, it is caused by some scripts in customdata of osprofile.

**Comment by wbuchwalter** [comment]
I am seeing the same issue on a cluster with only Linux agents.

Created a cluster with acs-engine `v0.21.2`, deployed some workload on it, including a service of type `LoadBalancer`. Everything worked as expected.

I then scaled some of the pools, and I am now seeing the error mentioned above. Also creation of new services now fail as well with:
```
  Type     Reason                      Age                From                Message
  ----     ------                      ----               ----                -------
  Normal   EnsuringLoadBalancer        7m (x11 over 3d)   service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  6m (x10 over 51m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service myservice: timed out waiting for the condition
```
