### ISSUE TITLE
acs-engine should validate Windows username & password in apimodel to avoid failing a deployment later

### ISSUE THREAD

**Issue by PatrickLang** [Azure/acs-engine#3636]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature

---

**What version of acs-engine?**: v0.20.* and earlier

---

Azure has extra requirements on VM password & username. If they're not met - `acs-engine generate` will succeed, but then `az group deploy` will fail after waiting a few minutes. Fail fast!

Windows VM [username](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/faq?toc=%2fazure%2fvirtual-machines%2fwindows%2ftoc.json#what-are-the-username-requirements-when-creating-a-vm) and [password](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/faq?toc=%2fazure%2fvirtual-machines%2fwindows%2ftoc.json#what-are-the-password-requirements-when-creating-a-vm)

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: all

**Comment by CecileRobertMichon** [comment]
Where to do this: https://github.com/Azure/acs-engine/blob/master/pkg/api/vlabs/validate.go#L828

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/pull/3854 enforces password validation

**Comment by PatrickLang** [comment]
resolved in #3854
