### ISSUE TITLE
Too low idle timeout for load balancer

### ISSUE THREAD

**Issue by sheerun** [Azure/acs-engine#365]
I use kubernetes along with deis, but often get "fatal: The remote end hung up unexpectedly" error message when trying to push builds. Deis build are synchronous and can take longer than 4 minutes that seems to be the default for idle timeout for Azure Load Balancer, given this post: https://azure.microsoft.com/en-us/blog/new-configurable-idle-timeout-for-azure-load-balancer/

Could you please increase default idle timeout for Azure Load Balancer e.g. to 10-15 minutes?

At last the timeout for kubernetes services could be configured with ingress controller.

Thank you

**Comment by colemickens** [comment]
This should be filed on kubernetes, not here. Can you please move the issue?

Also, if Deis is still pushing, then it wouldn't be the idle timeout, unless I'm missing something.

**Comment by sheerun** [comment]
it happens when deis is building, long after it received the git payload

**Comment by colemickens** [comment]
1. This still needs to be filed upstream on the kubernetes repo.

2. Seems like Deis is going to have problems in a variety of environments if it's really leaving a completely idle TCP connection for that long...

**Comment by sheerun** [comment]
Sure, understood. That might be actually another issue as even if I increase the timeout to 15 minutes, the connection drops after 10 minutes.. I'll debug it little more before filling to kubernetes.
