### ISSUE TITLE
Unable to pull images from ACR: Error response from daemon: Get https://foo.azurecr.io/v2/platform/identity-user/manifests/master-07eeda3: unauthorized: authentication required

### ISSUE THREAD

**Issue by neurot1cal** [Azure/acs-engine#3654]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

v0.19.5

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.11.1

**What happened**:

When pulling images that we can successfully push in our Jenkins pipeline, we're getting the following error;

```
Failed to pull image "foo.azurecr.io/platform/identity-user:master-07eeda3": rpc error: code = Unknown desc = Error response from daemon: Get https://foo.azurecr.io/v2/platform/identity-user/manifests/master-07eeda3: unauthorized: authentication required
```

We are able to push this image from within this container without an issue. When attempting to pull down we see this error. 

Service Principal has Contributor to the ACR (Just added this about 30 minutes ago, doesnt seem to impact the issue).

**What you expected to happen**:

Image to be able to be pulled down from ACR.

**How to reproduce it** (as minimally and precisely as possible):

```+ docker tag foo.azurecr.io/platform/identity-user:master-07eeda3 foo.azurecr.io/platform/identity-user:master-07eeda3
[Pipeline] sh
[identity-user_master-] Running shell script
+ docker push foo.azurecr.io/platform/identity-user:master-07eeda3
The push refers to a repository [foo.azurecr.io/platform/identity-user]
78a7bcba4edb: Preparing
16ba574f5aac: Preparing
cdb27baf3a3c: Preparing
ff42f700136d: Preparing
9ef882f5c2ea: Preparing
9dfa40a0da3b: Preparing
9dfa40a0da3b: Waiting
ff42f700136d: Layer already exists
cdb27baf3a3c: Layer already exists
16ba574f5aac: Layer already exists
9ef882f5c2ea: Layer already exists
9dfa40a0da3b: Layer already exists
78a7bcba4edb: Pushed
master-07eeda3: digest: sha256:size: 1580
[Pipeline] sh
[identity-user_master-] Running shell script
+ docker tag foo.azurecr.io/platform/identity-user:master-07eeda3 foo.azurecr.io/platform/identity-user:latest
[Pipeline] sh
[identity-user_master-] Running shell script
+ docker push foo.azurecr.io/platform/identity-user:latest
The push refers to a repository [foo.azurecr.io/platform/identity-user]
78a7bcba4edb: Preparing
16ba574f5aac: Preparing
cdb27baf3a3c: Preparing
ff42f700136d: Preparing
9ef882f5c2ea: Preparing
9dfa40a0da3b: Preparing
9dfa40a0da3b: Waiting
9ef882f5c2ea: Layer already exists
78a7bcba4edb: Layer already exists
cdb27baf3a3c: Layer already exists
16ba574f5aac: Layer already exists
ff42f700136d: Layer already exists
9dfa40a0da3b: Layer already exists
latest: digest: size: 1580
```

Then `helm install foo`;

```
=> v1/Pod(related)
NAME                                          READY  STATUS        RESTARTS  AGE
identity-user-identity-user-6cbb9c75f8-547ls  0/1    ErrImagePull  0         4s
identity-user-identity-user-6cbb9c75f8-dnjz9  0/1    ErrImagePull  0         4s
identity-user-identity-user-6cbb9c75f8-wfgbs  0/1    ErrImagePull  0         4s
```

**Anything else we need to know**:

Pulling from this ACR is working in other clusters (Production cluster in acs-engine / Kubernetes 1.10.5)

**Comment by andyzhangx** [comment]
## pull image error after granting sp access to azure acr
**Fix**
 - PR [fix acr could not be listed in sp issue](https://github.com/kubernetes/kubernetes/pull/66429)
> Note that this PR would also enable feature: pull image from a cross subscription ACR

| k8s version | fixed version |
| ---- | ---- |
| v1.7 | no fix |
| v1.8 | no fix |
| v1.9 | in cherry-pick |
| v1.10 | 1.10.7 |
| v1.11 | 1.11.2 |
| v1.12 | 1.12.0 |

**workaround**
 - wait for at most 2 hours, let service principal token expires and pull image would succeed after a few tries automatically
 - restart `kubelet` service on the agent node

**Related issues**
 - [kubelet needs restart after granting sp access to azure acr](https://github.com/kubernetes/kubernetes/issues/65225)
 - [Kubelet requires restart after granting AKS SP access to ACR resource](https://github.com/Azure/AKS/issues/442)
 - [Unable to pull images from ACR: Error response from daemon](https://github.com/Azure/acs-engine/issues/3654)

### Tips
#### How to check whether current service principal could access ACR?

 - Use following command to check whether the target ACR is listed
```
az login --service-principal -u <aadClientId> -p <aadClientSecret> -t <tenantId>
az acr list
```

**Comment by neurot1cal** [comment]
@andyzhangx Tried to upgrade cluster from 1.11.1 > 1.11.2; https://github.com/Azure/acs-engine/issues/3669

**Comment by Roshanpkj** [comment]
what is the final solution to this problem, please 
I am still getting - the following error 
message: >-
  Failed to pull image "azcregi.azurecr.io/azuredocs/azure-vote-front:v1": [rpc
  error: code = Unknown desc = Error response from daemon: manifest for
  azcregi.azurecr.io/azuredocs/azure-vote-front:v1 not found: manifest unknown:
  manifest tagged by "v1" is not found, rpc error: code = Unknown desc = Error
  response from daemon: Get
  https://azcregi.azurecr.io/v2/azuredocs/azure-vote-front/manifests/v1:
  unauthorized: authentication required, visit https://aka.ms/acr/authorization
  for more information.]

**Comment by andyzhangx** [comment]
> what is the final solution to this problem, please
> I am still getting - the following error
> message: >-
> Failed to pull image "azcregi.azurecr.io/azuredocs/azure-vote-front:v1": [rpc
> error: code = Unknown desc = Error response from daemon: manifest for
> azcregi.azurecr.io/azuredocs/azure-vote-front:v1 not found: manifest unknown:
> manifest tagged by "v1" is not found, rpc error: code = Unknown desc = Error
> response from daemon: Get
> https://azcregi.azurecr.io/v2/azuredocs/azure-vote-front/manifests/v1:
> unauthorized: authentication required, visit https://aka.ms/acr/authorization
> for more information.]

@Roshanpkj  did pull image successfully finally? Did you cluster identity has access to the ACR?
