### ISSUE TITLE
Unable to remove heapster ,dns addson from  deployment 

### ISSUE THREAD

**Issue by SuperMarioo** [Azure/acs-engine#3662]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

16.1

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 10.2

**What happened**:
I'm trying to remove heapster and dns . 

**What you expected to happen**:

Heapster and dns should not get deployed . 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

That's my configuration 

"addons": [
          {
            "name": "kubernetes-dashboard",
            "enabled": false
          },
          {
            "name": "metrics-server",
            "enabled": false
          },
          {
            "name": "heapster",
            "enabled": false
          },
          {
            "name": "kube-dns",
            "enabled": false
          },
]

**Comment by CecileRobertMichon** [comment]
Hi @SuperMarioo, this is by design. The heapster and kube-dns are required for cluster health and functionality and cannot currently be removed. For a list of currently supported configurable addons see https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md#addons.
