### ISSUE TITLE
Missing VM tags results in failed kubernetes upgrade and scale

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/acs-engine#3663]
Upgrade and scale should not rely on VM tags to determine k8s version during upgrade as those could easily be removed or modified.

https://github.com/Azure/acs-engine/blob/master/pkg/operations/kubernetesupgrade/upgradecluster.go#L200

https://github.com/Azure/acs-engine/blob/master/cmd/scale.go#L225

**Comment by serbrech** [comment]
Any suggestion on how to identify VMs to upgrade without relying on tags? Should it rely on VM names instead?

**Comment by CecileRobertMichon** [comment]
@serbrech I think for now even a simple check to make sure those tags exist before dereferencing them would help so that we can return a meaningful error ("expected tags "..." and "..." on VM "..." but no tags were found" or something like that) instead of panicking would be better.

**Comment by mboersma** [comment]
Fixed in #4100.
