### ISSUE TITLE
acs-engine deploy is missing kube-proxy on windows node

### ISSUE THREAD

**Issue by no-stupid-questions** [Azure/acs-engine#3666]
**Is this a request for help?**:

yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

issue
**What version of acs-engine?**:

Version: v0.20.8
GitCommit: 5d847c195
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes v1.10.6

**What happened**:
Deployed a hybrid  cluster of 3 linux nodes and one windows node into a custom Vnet. The deployment proccess was pretty jenky with a few work arounds. the deployment ended up looking like this:
PS C:\WINDOWS\system32> kubectl get nodes
NAME                        STATUS    ROLES     AGE       VERSION
37463k8s9010                Ready     <none>    7h        v1.10.6
k8s-linuxpool1-37463772-0   Ready     agent     7h        v1.10.6
k8s-linuxpool1-37463772-1   Ready     agent     7h        v1.10.6
k8s-master-37463772-0       Ready     master    7h        v1.10.6

pods:
kube-system   azure-cni-networkmonitor-6sqbt                         1/1       Running            1          7h
kube-system   azure-cni-networkmonitor-cxjn8                         1/1       Running            1          7h
kube-system   heapster-75f5b5c44c-4h2wm                              2/2       Running            2          7h
kube-system   jxing-nginx-ingress-controller-5d889ff66b-5bbqc        1/1       Running            0          5h
kube-system   jxing-nginx-ingress-default-backend-84f46c65d6-l4vww   1/1       Running            0          
kube-system   kube-addon-manager-k8s-master-37463772-0               1/1       Running            1          7h
kube-system   kube-apiserver-k8s-master-37463772-0                   1/1       Running            1          7h
kube-system   kube-controller-manager-k8s-master-37463772-0          1/1       Running            1          7h
kube-system   kube-dns-5b97576b6d-449z4                              3/3       Running            4          7h
kube-system   kube-proxy-4xq2m                                       1/1       Running            1          7h
kube-system   kube-proxy-trlq2                                       1/1       Running            1          7h
kube-system   kube-proxy-znn56                                       1/1       Running            1          7h
kube-system   kube-scheduler-k8s-master-37463772-0                   1/1       Running            1          7h
kube-system   kubernetes-dashboard-654df547cd-9np52                  1/1       Running            4          7h
kube-system   metrics-server-64f6d6b47-p8dpf                         1/1       Running            2          7h
kube-system   tiller-deploy-55fdff5b45-lllts                         1/1       Running            0          5h

**What you expected to happen**:
I'm not sure. I would like to know if the network has been set up properly. I don't believe it is 100% from the fact that there are only three kube-proxies, and non on the windows node. As well there is only 2 azure cni network monitors. I would like to know what I should expect for a proper network deplyment, and how to test if the network is setup properly.

**How to reproduce it** (as minimally and precisely as possible):
create a deployment with kubernetes 1.10, 3 linux nodes and one windows and a custom vnet.

**Comment by PatrickLang** [comment]
kube-proxy is run on the host, and won't show up in `docker ps` or `kubectl get pod` output for Windows nodes.
