### ISSUE TITLE
Unable to upgrade acs-engine Kubernetes cluster from 1.11.1 > 1.11.2 using v0.20.9; Subnet GatewaySubnet is in use and cannot be deleted.

### ISSUE THREAD

**Issue by neurot1cal** [Azure/acs-engine#3670]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

master (36aa21cb)

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.11.2

**What happened**:

When attempting to `acs-engine upgrade` the upgrade errors out because of the existance of a Gateway Subnet. This subnet is required for a VPN Gateway we use to connect directly to the K8s VNet.

**What you expected to happen**:

Upgrade successfully without checking on the presence of my Gateway Subnet. The upgrade should not touch an existing VNet or Subnet configuration.

**How to reproduce it** (as minimally and precisely as possible):

```
./acs-engine upgrade --auth-method client_secret \
    --client-id "SP_ID" \
    --client-secret "SP_SECRET" \
    --deployment-dir ./_output/CLUSTER_ID \
    --subscription-id "SUB_ID" \
    --resource-group "RG_ID" \
    --upgrade-version "1.11.2" \
    --location "westus" \
    --debug
```

**Anything else we need to know**:

Removing gateway subnet resolves this issue. This should not be checked during an upgrade.

**Comment by carlsoncoder** [comment]
I am also running into this same issue when attempting to upgrade my cluster from v1.10.6 to 1.11.2, using acs-engine built from source as of commit 1ade2f387a770697ed196d1d254456cac87499b5.  I received the following error message in "acs-engine upgrade" output:

**FATAL[0314] Error upgrading cluster: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details.
Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n
\"error\": {\r\n    \"code\": \"InUseSubnetCannotBeDeleted\",\r\n    \"message\": \"Subnet GatewaySubnet is in use by /subscriptions/
subscription-id/resourceGroups/resource-group-name/providers/Microsoft.Network/applicationGateways/app-gateway-name/gatewayIPConfigurations/applicationGatewayIpConfig and cannot be deleted.\",\r\n    \"details\": []\r\n  }\r\n}"}]**

I was able to solve it in the same way @neurot1cal was, however, I had an Application Gateway tied to my GatewaySubnet so I had to delete that AND the GatewaySubnet.  That's not really a viable option for me, as that would create downtime for existing users.

**Comment by neurot1cal** [comment]
@jackfrancis Is this intended behavior?
