### ISSUE TITLE
EnableEncryptionWithExternalKms does not support sovereign cloud

### ISSUE THREAD

**Issue by karataliu** [Azure/acs-engine#3677]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
v0.20.3

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s 1.11

**What happened**:
Error reported:
failed to get vault, error: failed to get vault, error: keyvault.VaultsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '{}' could not be found."

The subscription is not in public cloud, thus it reports could not be found.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a k8s cluster in sovereign cloud, turn on EnableEncryptionWithExternalKms feature
2. Create a k8s secret

cc @ritazh  Any additional config required?

**Comment by ritazh** [comment]
@karataliu To clarify, what is the value of `"cloud":""` in your azure.json. For example, in mine it is set to `"cloud":"AzurePublicCloud"`

**Comment by karataliu** [comment]
In azure.json we have correct value set there, tested with
"cloud":"AzureChinaCloud".
The cluster functions well except for the external kms part
