### ISSUE TITLE
kube-scheduler is never created using k8s 1.12 and vmss

### ISSUE THREAD

**Issue by ritazh** [Azure/acs-engine#3681]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
master commit 1ade2f3

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s 1.12

**What happened**:
Created a new cluster with acs-engine master 1ade2f3 using k8s 1.12 and VMSS resulting in a cluster that does not have kube-scheduler. `docker ps -a` does not show kube-scheduler container even being scheduled. As a result, addon pods are shown as `pending`. New pods scheduled are shown as `pending` without any events in `kubectl describe pod` 

From the master kubelet log, we never see this expected event in the log:
```
SyncLoop (PLEG): "kube-scheduler-k8s-master-36079709-0_kube-system(4112ac0d067b2419602ce8457d86bbe4)", event: &pleg.PodLifecycleEvent{ID:"4112ac0d067b2419602ce8457d86bbe4", Type:"ContainerStarted", Data:"c8f500822117e406ef587d816de0497bce0915d05c29ad38ddb3331f12a8544c"}
```
Restarting the kubelet service on master solves this issue.

**What you expected to happen**:
A healthy cluster is created with k8s 1.12 and VMSS.

**How to reproduce it** (as minimally and precisely as possible):
With the apimodel below, a cluster will be created using VMSS and k8s 1.12.

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.12"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_DS2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool",
        "count": 2,
        "vmSize": "Standard_DS2_v2"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
    }
  }
}
```

**Anything else we need to know**:
This issue is only visible in VMSS and k8s 1.12. VMAS works as intended.

cc @feiskyer

**Comment by feiskyer** [comment]
azure cloud provider hits rate limits for instance metadata. And it seems this is not clear documented.

Filed https://github.com/kubernetes/kubernetes/pull/67478 in upstream to reduce this.
