### ISSUE TITLE
Deploy Windows Server 1803 hotfix for HNS

### ISSUE THREAD

**Issue by PatrickLang** [Azure/acs-engine#3692]
This is a tracking issue to deploy a fix for a network stability issue, Windows bug 18560834. There have been some cases where a Windows Server version 1803 node can go down if a very large number of outbound connections are made.

**Comment by PatrickLang** [comment]
https://github.com/Azure/acs-engine/pull/2957 - this is the hotfix install code that was used before

**Comment by PatrickLang** [comment]
Work is happening here https://github.com/PatrickLang/acs-engine/tree/patricklang-3692 and I'm finishing up tests on it

**Comment by y325A** [comment]
@PatrickLang Do you know where I can get this update that fixes the network stability issue? I am getting lots of compute issues when a multiple pods restart at the same time.

**Comment by PatrickLang** [comment]
@y325A Open a ticket with MS support and ask for the fix to Windows bug 18560834. It will be in a future update (estimate - late October)

**Comment by daschott** [comment]
@y325A Are you seeing problems when multiple containers in a pod are restarting, or multiple pods at the same time (belonging to a service or node.)

What compute problems are you seeing?
