### ISSUE TITLE
K8s: Investigate if Etcd should be started with "--initial-cluster-state existing" flag

### ISSUE THREAD

**Issue by raveeram** [Azure/acs-engine#370]
In a multi-master scenario, restoring a failed master seems to result in the master creating a new cluster of its own instead of joining an existing cluster. Investigate if this is due to the etcd cluster being started with the "--initial-cluster-state new" flag instead of "--initial-cluster-state existing"

**Comment by anhowe** [comment]
@colemickens @amanohar does this get covered with upgrade?
