### ISSUE TITLE
kubernetes-dashboard not running - crashloopbackoff error 

### ISSUE THREAD

**Issue by rodrigoffonseca** [Azure/acs-engine#3726]
**Is this a request for help?**:
YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
acs-engine version
Version: canary
GitCommit: unset
GitTreeState: unset
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11.2

**What happened**:
The Kubernetes-Dashboard and other pods (DNS and Metrics) are not running after deploying cluster using ACS-Engine.

PODS status:
xpiusadm@k8s-master-12913804-0:~$ kubectl get pods -n kube-system
NAME                                            READY     STATUS             RESTARTS   AGE
calico-node-6kwsf                               2/2       Running            0          1d
calico-node-kpk2s                               2/2       Running            0          1d
calico-node-lg5gx                               2/2       Running            0          1d
calico-node-nsfzp                               2/2       NodeLost           0          1d
calico-node-vl2g5                               2/2       Running            0          1d
cluster-autoscaler-7b47cf54dc-gbpzq             1/1       Running            149        1d
heapster-855c6c8b5b-zpgbb                       2/2       Unknown            0          1d
heapster-855c6c8b5b-zwtjd                       2/2       Running            0          1d
kube-addon-manager-k8s-master-12913804-0        1/1       Running            0          1d
kube-apiserver-k8s-master-12913804-0            1/1       Running            0          1d
kube-controller-manager-k8s-master-12913804-0   1/1       Running            0          1d
kube-dns-6d54b9d8b6-8hj8n                       2/3       Unknown            0          1d
kube-dns-6d54b9d8b6-8nw2t                       1/3       CrashLoopBackOff   768        1d
kube-proxy-5xmnl                                1/1       NodeLost           0          1d
kube-proxy-8z2p2                                1/1       Running            0          1d
kube-proxy-cw4zh                                1/1       Running            0          1d
kube-proxy-jlsq4                                1/1       Running            0          1d
kube-proxy-sf2dq                                1/1       Running            0          1d
kube-scheduler-k8s-master-12913804-0            1/1       Running            0          1d
kubernetes-dashboard-75b94d98b6-jzb5r           1/1       Unknown            0          1d
kubernetes-dashboard-75b94d98b6-vl4hl           0/1       CrashLoopBackOff   261        1d
metrics-server-789c47657d-bppm2                 1/1       Unknown            0          1d
metrics-server-789c47657d-k4d44                 0/1       CrashLoopBackOff   262        1d
tiller-deploy-54c57f6dc5-6g266                  1/1       Running            0          1d
tiller-deploy-54c57f6dc5-8cbn5                  0/1       Unknown            0          1d

dashboard pod log:
2018/08/22 17:09:12 Starting overwatch
2018/08/22 17:09:12 Using in-cluster config to connect to apiserver
2018/08/22 17:09:12 Using service account token for csrf signing
2018/08/22 17:09:12 No request provided. Skipping authorization
2018/08/22 17:09:42 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.21.0.1:443/version: dial tcp 10.21.0.1:443: i/o timeout
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

**What you expected to happen**:
Have all pods running and dashboard available to connect

**How to reproduce it** (as minimally and precisely as possible):
Deploy using acs-engine template below:
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.11.2",
      "kubernetesConfig": {
        "enableRbac": true,
        "networkPolicy": "calico",
        "networkPlugin" : "kubenet",       
        "maxPods": 50,
        "clusterSubnet": "10.20.64.0/20",
        "serviceCidr": "10.21.0.0/16",
        "DNSServiceIP": "10.21.0.250",
        "addons": [
        {
          "name": "tiller",
          "enabled": true
        },
        {
          "name": "kubernetes-dashboard",
          "enabled": true,
          "containers": [
            {
              "name": "kubernetes-dashboard",
              "cpuRequests": "50m",
              "memoryRequests": "512Mi",
              "cpuLimits": "50m",
              "memoryLimits": "512Mi"
            }
          ]
        },
        {
          "name": "cluster-autoscaler",
          "enabled": true,
          "containers": [
            {
              "name": "cluster-autoscaler",
              "cpuRequests": "100m",
              "memoryRequests": "300Mi",
              "cpuLimits": "100m",
              "memoryLimits": "300Mi"
            }
          ],
          "config": {
            "maxNodes": "10",
            "minNodes": "2"
          }
        }
        ]
    }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "XXXXXXXXXXXXXXXXXX",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "firstConsecutiveStaticIP": "10.20.64.10",
      "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "agent",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "dnsPrefix": "",
        "availabilityProfile": "VirtualMachineScaleSets",
        "vnetSubnetId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
       "storageProfile": "ManagedDisks"
      }
    ],
    "linuxProfile": {
      "adminUsername": "XXXXXXXXXXXXXXXXXX",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
        "clientId": "",
        "secret": ""
    }
  }
}
[ACS-Support-Log-RunningPods.txt](https://github.com/Azure/acs-engine/files/2311367/ACS-Support-Log-RunningPods.txt)
[ACS-Support-Log-DashboardLogs.txt](https://github.com/Azure/acs-engine/files/2311368/ACS-Support-Log-DashboardLogs.txt)
[ACS-Support-Log-DashboardDescribe.txt](https://github.com/Azure/acs-engine/files/2311369/ACS-Support-Log-DashboardDescribe.txt)
[logs-controller.txt](https://github.com/Azure/acs-engine/files/2311374/logs-controller.txt)
[logs-APIServer.txt](https://github.com/Azure/acs-engine/files/2311375/logs-APIServer.txt)

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@rodrigoffonseca which version of acs-engine was this with?

**Comment by CecileRobertMichon** [comment]
I was able to repro with acs-engine master and with the latest release. I am investigating which part of the cluster configuration is causing this as we are not seeing this in any of our end to end tests.

**Comment by CecileRobertMichon** [comment]
@rodrigoffonseca did you follow the post deployment instructions outlined in the [custom vnet docs](https://github.com/Azure/acs-engine/blob/master/docs/custom-vnet.md#post-deployment-attach-cluster-route-table-to-vnet)?

**Comment by CecileRobertMichon** [comment]
any updates?

**Comment by tariq1890** [comment]
Closed due to inactivity. Feel free to re-open if the issue reprises.
