### ISSUE TITLE
install health-monitor and node-problem-detector on all VMs

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/acs-engine#3729]
install as daemons on all VMs:
- https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/health-monitor.sh 
- https://github.com/kubernetes/node-problem-detector

**Comment by neurot1cal** [comment]
Ooooooo :)

**Comment by juan-lee** [comment]
Let's limit the scope of this issue to the health-monitor. node-problem-detector is easy enough for folks to install on their own.

**Comment by neurot1cal** [comment]
@juan-lee Would it make sense to have this be one of the optional extensions that can be installed at cluster provisioning?

**Comment by jackfrancis** [comment]
@neurot1cal are you suggesting you want an opt-out option?

**Comment by neurot1cal** [comment]
@jackfrancis sorry, I meant the `node-problem-detector` that is out of scope now. makes sense to not install it by default, but could be something someone selects to opt-into installing via extensions, like with prometheus, etc. just a thought ;)

**Comment by jackfrancis** [comment]
@neurot1cal Got it. Filed this:

https://github.com/Azure/acs-engine/issues/3783
