### ISSUE TITLE
Deployment fails with error Bad argument `MASQUERADE' when VnetCIDR is not present in the apimodel

### ISSUE THREAD

**Issue by ashvindeodhar** [Azure/acs-engine#3730]
**Is this a request for help?**:
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

**What version of acs-engine?**:
v0.20.6

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s

**What happened**:
I am trying to deploy a k8s Linux cluster in existing vnet subnet but I get an error 
VM has reported a failure when processing extension 'cse-master-0'

I referred https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/troubleshooting.md#vmextensionprovisioningerror-or-vmextensionprovisioningtimeout 
I am attaching cluster-provision.log which shows error -
Job for kubelet.service failed because the control process exited with error code. See "systemctl status kubelet.service" and "journalctl -xe" for details.

Attaching log files -
1. cluster-provision.log
2. systemctl status kubelet.service > log1
3. journalctl -xe > log2
4. my kubernetes-sample.json

**What you expected to happen**:
Successful deployment

**How to reproduce it** (as minimally and precisely as possible):
1. az group create --name testcluster1 --location eastus2euap
2. acs-engine generate C:\k8s-json\kubernetes-sample.json ( attached )
3. az group deployment create --name deptestcluster1 --resource-group testcluster1 --template-file _output\testCluster1\azuredeploy.json --parameters _output\testCluster1\azuredeploy.parameters.json

Error:
Deployment failed. Correlation ID: 391eaac9-2814-4d34-a127-85dd1b5f84c3. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=4\n[stdout]\n\n[stderr]\n\"."
      }
    ]
  }
}
[cluster-provision.log](https://github.com/Azure/acs-engine/files/2313211/cluster-provision.log)

[kubernetes-sample-json.log](https://github.com/Azure/acs-engine/files/2313226/kubernetes-sample-json.log)

**Comment by CecileRobertMichon** [comment]
@ashvindeodhar did you attach the kubelet journalctl log? I can only see the cluster-provision log and your apimodel json.

Are you able to reproduce the issue 100% of the time with this cluster definition? Ie. did you get several failed deployments with the same error

**Comment by ashvindeodhar** [comment]
[cluster-provision.log](https://github.com/Azure/acs-engine/files/2315802/cluster-provision.log)
[log1.log](https://github.com/Azure/acs-engine/files/2315803/log1.log)
[log2.log](https://github.com/Azure/acs-engine/files/2315804/log2.log)

@CecileRobertMichon Attaching the missing logs here. I can repro this 100% of the time and have tried multiple regions as well. No luck.

**Comment by CecileRobertMichon** [comment]
Thanks @ashvindeodhar. The error is `Bad argument `MASQUERADE'`, let me try to repro.

**Comment by ashvindeodhar** [comment]
@CecileRobertMichon Thanks!! including vNetCidr in k8s apimodel json fixed this problem.

**Comment by CecileRobertMichon** [comment]
@ashvindeodhar good to hear :) I will still follow up with this issue this seems like a bug as vnetCidr shouldn't be required

**Comment by ashvindeodhar** [comment]
sounds good. Thanks for your help and following it up further.

**Comment by tariq1890** [comment]
Reopening for further investigation.
