### ISSUE TITLE
Would orchestratorType "openshift" support in Azure China?

### ISSUE THREAD

**Issue by DanielWangZhanggui** [Azure/acs-engine#3746]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
openshift

**What happened**:
Can't set the RHEL image reference

**What you expected to happen**:
provide some options to set the image refereance & rhn user information

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by andyzhangx** [comment]
as I know, RHEL image is not available in Azure china, that's a big dependency

**Comment by DanielWangZhanggui** [comment]
Yeah, there's a partner provide a RHEL image in Azure China, then we can register rhn via using our own redhat account number. 
like we can input redhat account name in this [page](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/openshift-container-platform)

**Comment by andyzhangx** [comment]
@jackfrancis @CecileRobertMichon do you know what's status of Redhat image support on acs-engine? If it could supports global azure, I think we could enable that on azure china too.

**Comment by jackfrancis** [comment]
All OpenShift development is being moved to managed service implementation.
