### ISSUE TITLE
Unable to create Load balancer service in Azure Government

### ISSUE THREAD

**Issue by zhiweiv** [Azure/acs-engine#3754]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.21.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11.2

**What happened**:
I got below error in kubectl describe service after created a Load balancer service:

  Warning  CreatingLoadBalancerFailed  19s (x4 over 54s)  service-controller  Er
ror creating load balancer (will retry): failed to ensure load balancer for serv
ice default/my-service: network.LoadBalancersClient#List: Failure respondi
ng to request: StatusCode=404 -- Original Error: autorest/azure: Service returne
d an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '29
0a3166-xxxx-xxxx-xxxx-d22e8cf95f8b' could not be found."

**What you expected to happen**:
Load balancer service could be created successfully.

**How to reproduce it** (as minimally and precisely as possible):
1 Create a service principal and set it as Contributor of my resource group.
2 Deploy a k8s Windows cluster by acs engine to my resource group, you can find the template here:https://github.com/zhiweiv/apcs/blob/master/kubernetes.json
3 Create a service by https://github.com/zhiweiv/apcs/blob/master/service.yaml 
4 Run kubectl describe service my-service

The steps work well in Azure Global.

Thanks

**Comment by andyzhangx** [comment]
can you use provide controller manager logs on master node, you could run following command:
```
id=`docker ps -a | grep "hyperkube contro" | awk -F ' ' '{print $1}'`
docker logs $id > $id.log 2>&1
vi $id.log
```

**Comment by andyzhangx** [comment]
another point, so your resource group is under subscription `290a3166-xxxx-xxxx-xxxx-d22e8cf95f8b`? could you also paste your `/etc/kubernetes/azure.json` on master node? you may remove some secret info before pasting. If create load balancer does not work, I guess other function which requires creating azure resource will not work either, you may try create a pod with azure disk either to check: https://github.com/andyzhangx/demo/tree/master/linux/azuredisk

**Comment by zhiweiv** [comment]
Hi @andyzhangx I got same error on create pvc. The subscription id and resource group are correct and matched.
Here are some information new:
https://github.com/zhiweiv/apcs/blob/master/app.png
https://github.com/zhiweiv/apcs/blob/master/role.png
https://github.com/zhiweiv/apcs/blob/master/resgroup.png
https://github.com/zhiweiv/apcs/blob/master/azure.json
https://github.com/zhiweiv/apcs/blob/master/log.txt

Thanks

**Comment by andyzhangx** [comment]
How do you deploy acs-engine on usgov? field `cloud` in config `azure.json` is not correct , it should be `AzureUSGovernmentCloud`

**Comment by andyzhangx** [comment]
anyway, you could change that filed to `AzureUSGovernmentCloud` and restart master node to have a try

**Comment by zhiweiv** [comment]
In azure.json, it is "cloud":"AzurePublicCloud", I think it should be USGovernmentCloud. You can see the code in function EnvironmentFromName,
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/auth/azure_auth.go
https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go

But I have not found any setting to set it while generating the template, do I have to change it manually in the generated azuredeploy.parameters.json?

Thanks

**Comment by andyzhangx** [comment]
it may be a bug in acs-engine, I have tried on azure china, only location is needed to set in acs-engine template. Right now could you try edit it manually on master node, and reboot master node to check whether it works or not?

**Comment by zhiweiv** [comment]
I figured it out just now, last time I followed the steps in the walkthrough guide: acs-engine generate then az group deployment. There is not param to sepcify cloud type there.

I found a guide for government here:
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-k8
This time I use acs-engine deploy directly and set --azure-env AzureUSGovernmentCloud, it works now.

**Comment by zhiweiv** [comment]
Hi @andyzhangx 
Is it better to use acs-engine deploy instead of acs-engine generate/az group deployment?
Is it better to update the walkthrough guide and link the gov guide there?
https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/windows.md

**Comment by zhiweiv** [comment]
I found location field in your demo: https://github.com/andyzhangx/demo/blob/master/acs-engine/mooncake/kubernetes-1.7.9.json#L3
But seems it is not documented in clusterdefinition guide: https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md

**Comment by andyzhangx** [comment]
@zhiweiv back to your question, I think use "acs-engine generate/az group deployment" is better, since after  `acs-engine generate`, you could check generated config files.
