### ISSUE TITLE
Dockerfile needs to be updated

### ISSUE THREAD

**Issue by tariq1890** [Azure/acs-engine#3770]
The Dockerfile needs to be updated. Currently, we run docker environments using deis/go-dev image through Makefile. (check https://github.com/Azure/acs-engine/blob/8592e491e203bdf941a92b9383ebb35fa5de4a5b/Makefile#L44).

The Dockerfile needs to reflect the process followed here.

**Comment by tariq1890** [comment]
We are asking for the Dockerfile to be changed. Right now, we are essentially running the deis/go-dev containers with parameters to containerize acs-engine (check make dev in the Makefile)

That docker run command can be converted into an equivalent Dockerfile.

**Comment by tariq1890** [comment]
Yes. Right now, the only way to spin up a working and a good docker
container is via Makefile. Some of the acs-engine users have already
attempted to create containers from our outdated Dockerfile and are running
into issues. It would be nice to have a Dockerfile which reflects exactly
what make dev is doing. The docker run command flags used have Dockerfile
primitive equivalents. That's what I had in mind when I created this issue.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
