### ISSUE TITLE
Pods are inaccessible. Connection refused.

### ISSUE THREAD

**Issue by rushabhnagda11** [Azure/acs-engine#381]
I'm not sure if this is a duplicate, but I've deployed a k8s cluster yesterday. I've followed all the manual steps to create a k8s cluster.

kubectl create -f some_service_with_type_load_balancer

curl cluster_ip/external_ip -> connection refused

Logs of kube-proxy show that it's due to 

> clusterCIDR not specified, unable to distinguish between internal and external traffic

**Comment by rushabhnagda11** [comment]
Even after providing --cluster-cidr=10.240.0.0/16 to the proxy, it still isn't working

**Comment by rushabhnagda11** [comment]
@colemickens @dmitsh Is there some sort of quick fix/config I'm missing here? My iptables seem fine as well.

**Comment by anhowe** [comment]
Please email us your ACS api model you were using with ssh secrets and SPN secretes removed.  This will look similar to https://github.com/Azure/acs-engine/blob/master/examples/kubernetes.json.  Also please provide when you updated ACS-Engine.

Also, can you confirm you went through the troubleshooting section: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md#troubleshooting.

**Comment by rushabhnagda11** [comment]
Using the latest version of acs-engine. Last commit was 11c1633cdc794d2c3089a1440293b82c84ea209d which was on March 7th.

Also, I did go through the troubleshooting section. My service principal is fine.

Here's the file.

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "prokurekubernetesfoo",
      "vmSize": "Standard_DS2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "***"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "servicePrincipalClientID": "***",
      "servicePrincipalClientSecret": "***"
    }
  }
}

**Comment by rushabhnagda11** [comment]
I can provide the exact steps to reproduce it. It is happening in Azure Container Service (booted from azure ui) in southeastasia as well

**Comment by anhowe** [comment]
Please provide exact steps after you deployed cluster.

I have done the following and everything works:
1. create two nginx services, one named nginx, and the other nginx3
2. kubectl exec into the nginx3 pod, install curl, and successfully curl nginx.default.svc.cluster.local, and the external IP

**Comment by anhowe** [comment]
Closing as there was no repro, and our BVTs are not catching this issue.

If this is still happening, please paste an exact repro, and reopen.
