### ISSUE TITLE
acs-engine scale fails with Unknown JSON tag tillerMemoryRequests

### ISSUE THREAD

**Issue by joshua-vandenhoek** [Azure/acs-engine#3834]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.9.0, 0.10.0, 0.12.4, 0.21.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.2

**What happened**:
I am trying to use acs-enging scale to add worker nodes to an existing cluster. When I use the command with all the proper information filled in, I get the following error:

`INFO[0000] validating...                                
Error: failed to load existing container service: error parsing the api model: Unknown JSON tag tillerMemoryRequests`

Now I have seen issue https://github.com/Azure/acs-engine/issues/2060 and have used the workaround implemented there for fixing the keys mentioned, but I'm not sure what to do about this particular key. I can try removing it but I am wondering if there is a suitable workaround for this key (there may be others pop up as I go along) .

As I don't know which version of acs-engine was used to create the cluster, I tried 0.9.0, 0.10.0, 0.12.4, and 0.21.2. None of these are happy with what I am trying to do.

Here is the relevant section of the apimodel.json:

```"apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "orchestratorVersion": "1.8.2",
      "kubernetesConfig": {
        "kubernetesImageBase": "gcrio.azureedge.net/google_containers/",
        "clusterSubnet": "10.244.0.0/16",
        "dnsServiceIP": "10.0.0.10",
        "serviceCidr": "10.0.0.0/16",
        "networkPolicy": "none",
        "maxPods": 110,
        "dockerBridgeSubnet": "172.17.0.1/16",
        "cloudProviderBackoff": true,
        "cloudProviderBackoffRetries": 6,
        "cloudProviderBackoffJitter": 1,
        "cloudProviderBackoffDuration": 6,
        "cloudProviderBackoffExponent": 1.5,
        "cloudProviderRateLimit": true,
        "cloudProviderRateLimitQPS": 3,
        "cloudProviderRateLimitBucket": 10,
        "gchighthreshold": 85,
        "gclowthreshold": 80,
        "etcdVersion": "2.5.2",
        "etcdDiskSizeGB": "128",
        "tillerCPURequests": "50m",
        "tillerCPULimit": "50m",
        "tillerMemoryRequests": "150Mi",
        "tillerMemoryLimit": "150Mi",
        "disabledAddons": {},
        "kubeletConfig": {
        	"--node-status-update-frequency": "10s",
        	"--non-masquerade-cidr": "10.0.0.0/8"
        },
        "controllerManagerConfig": {
        	"--node-monitor-grace-period": "40s",
        	"--pod-eviction-timeout": "5m0s",
        	"--route-reconciliation-period": "10s"
        }
      }
```

Any direction on the matter would be much appreciated. Let me know if you need more info, thanks all!

**What you expected to happen**:
I expected to be able to add 2 new worker nodes to my cluster.

**How to reproduce it** (as minimally and precisely as possible):
Have the key "tillerMemoryRequests" present in apimodel.json and try to use acs-engine scale to add worker nodes

**Anything else we need to know**:
I realize that it would be better to move over to AKS, but acs-engine is what our cluster was built on and we really just need to add a few more nodes for the time being. Thanks and let me know if you have any suggestions!

**Comment by tariq1890** [comment]
Tiller config is now a part of addons per our latest schema.

Could you try configuring tiller like this in your apimodel.json?

```
"addons": [
            {
              "name": "tiller",
              "enabled": true,
              "containers": [
                {
                  "cpuRequests": "50m",
                  "cpuLimits": "50m",
                  "memoryRequests": "150Mi",
                  "memoryLimits": "150Mi"
                }
              ]
            }
          ],

You would also need to remove `disabledAddons`
```

**Comment by joshua-vandenhoek** [comment]
Awesome, I will give that a shot and let you know the results. Thanks!

**Comment by joshua-vandenhoek** [comment]
@CecileRobertMichon Thank you for your direction on the matter. Your workaround allowed me to scale my cluster! You can mark the issue as closed. Thank you again for your help!

**Comment by tariq1890** [comment]
Glad it worked :).
