### ISSUE TITLE
error when trying to use imageReference block for worker nodes with acs-engine scale

### ISSUE THREAD

**Issue by joshua-vandenhoek** [Azure/acs-engine#3837]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
0.21.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.2

**What happened**:
Some worker nodes in my cluster have the OS distro "Debian 8 (Jessie)". I used an "imageReference" block like so:

```
{
        "name": "nodes",
        "count": 4,
        "vmSize": "Standard_DS4_v2_Promo",
        "osDiskSizeGB": 64,
        "osType": "Linux",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "StorageAccount",
        "imageReference": {
        	"name": "jessie",
        	"resourceGroup": "debian"
        },
        "fqdn": "",
        "customNodeLabels": {
          "type": "default"
        },
        "preProvisionExtension": null,
        "extensions": []
      }
``` 
But now it tells me the following:

```
FATA[0081] Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"target\": \"vm.properties.storageProfile.imageReference.id\",\r\n    \"message\": \"Could not find member 'id' on object of type 'PlatformImageReference'. Path 'properties.storageProfile.imageReference.id', line 1, position 34772.\"\r\n  }\r\n}"}] 
```

**What you expected to happen**:
I expected new nodes in my cluster to be created in the "nodes" node pool and have the OS distro "debian" as the OS on the node.

**How to reproduce it** (as minimally and precisely as possible):
Try to use a debian jessie image in the imageReference block of agentPoolProfiles in apimodel.json

**Anything else we need to know**:
This is an older cluster that was not set up by me, and I am just trying to get it scaled up in the short term. We plan on moving to AKS at some point, but now is not the time. Please let me know if you require additional information. Thanks!

**Comment by CecileRobertMichon** [comment]
@joshua-vandenhoek what acs-engine version was your cluster created with? If you cluster is not too old you should be able to see the version in the VM tags

**Comment by joshua-vandenhoek** [comment]
Funny enough, I used that post yesterday. This is what was returned:

```
{
  "creationSource": "acsengine-k8s-nodes-86417899-0",
  "orchestrator": "Kubernetes:1.8.2",
  "poolName": "nodes",
  "resourceNameSuffix": "86417899"
}
```

Obviously, this is an older version of acs-engine, but unfortunately I was not able to discern the version from the above command....

**Comment by CecileRobertMichon** [comment]
@joshua-vandenhoek do you have anything preventing you from building a new cluster and migrating workloads? Typically, acs-engine releases after 0.12.0 are backwards compatible. Unfortunately, I cannot say the same of earlier versions. Using a newer version will also allow you to get new features and k8s versions.

**Comment by joshua-vandenhoek** [comment]
@CecileRobertMichon So moving to a new version is something that is on our roadmap, but for the time being we just need to scale this cluster up to handle some larger workloads for now. I know this is a strange case that would be solved by just using newer tech but I am kind of stuck with this for right now. Is there any way to tell the current configuration to use the same debian image that the old (functioning) node is using? 

To be clear, I was successful scaling this cluster earlier. I was able to add 2 new nodes, but their OS was ubuntu and not debian. This is causing problems as now, if pods get scheduled to these new nodes, when I try and exec/get logs from them with kubectl, I get the following error:

```
error: unable to upgrade connection: Unauthorized
```

This does not happen with pods scheduled on the old node with the debian image. This is the main impetus behind me trying to scale these nodes with a debian image. 

Thank you again for your help, let me know if you have any other suggestions. Thanks!

**Comment by CecileRobertMichon** [comment]
@joshua-vandenhoek what are you exact steps to scale with Ubuntu vs with Debian (resulting in the above error)? Are you using the `acs-engine scale` command?

**Comment by joshua-vandenhoek** [comment]
Yes, I did use the acs-engine scale command. The only difference between the two attempts was the way that I was specifying the apimodel.json. I have been unsuccessful in using a debian image thus far, but using the syntax of "distro": "ubuntu" allowed me to create the new nodes. Issue being, those nodes cause the above error if pods get scheduled to them. The command I used to scale the cluster (successfully, using "distro": "ubuntu") was:

```
acs-engine scale --subscription-id <REDACTED> --resource-group <REDACTED> --location <REDACTED> --deployment-dir ../acs_engine_output_dec_11/azure-dev --new-node-count 4 --node-pool nodes --master-FQDN <REDACTED>
```

This produced 2 new nodes, but they had the ubuntu OS and not debian like I wanted. I then tried using the "imageReference" block in apimodel.json to try and get a debian image to install, but no luck. The relevant apimodel.json section was posted above. Perhaps I am missing some fundamental piece here....

**Comment by CecileRobertMichon** [comment]
The apimodel you provide to the scale command should be the one used to deploy the cluster, not a new one that you just generated. You should not be modifying it manually at any point during scale (except for backcompat workarounds). Was imageReference present in your original apimodel?

**Comment by joshua-vandenhoek** [comment]
It was not, this was my attempt to try and shoe-horn the existing setup into scaling up the new nodes

**Comment by joshua-vandenhoek** [comment]
That is a very good question. I was provided with files from my manager from Dec 11 (the output of the acs-engine deploy/generate) when the cluster was apparently created. Looking through those files, I didn't see one mention of debian anywhere in there. The only clue I have is that debian is the OS on the only working worker node in the cluster, whereas the apimodel.json file I ws provided with had specified that the "distro" key was ubuntu. It makes total sense why they are deploying ubuntu OS images, but what doesn't make sense to me is how that node got debian on it in the first place.

I know this is a mess and I am just trying to sift through it to see if there is a way to salvage this and get us by for the next bit. I totally understand if your response is "can't help you because too much of a mess" but if you do have any suggestions I would be very appreciative. Thank you again for your time, let me know what you think.

**Comment by CecileRobertMichon** [comment]
It's possible that at some point in time the default OS distro image was set to Debian and your cluster was built during that time. In my opinion there are a few paths forward for you: 
1) build a new cluster with a newer version (I strongly recommend this)
2) try to find the version that the cluster was build with and scale from that version

That being said, I would also try to look into the error you get with new Ubuntu nodes. I don't think that is necessarily because of the Debian/Ubuntu discrepancy (in fact that shouldn't be a problem) and could very well be because of some other difference between the old and the new nodes that might solve-able.

**Comment by joshua-vandenhoek** [comment]
Hello @CecileRobertMichon ,

I believe you are correct. In working with this issue it has become apparent that the discrepancy between the OS versions shouldn't matter (in fact, kubectl describe of the node says that the OS is debian, but when you ssh to the node and look at it's OS, it lists it as Ubuntu. weird.) 

With that being said, I am going to try and find the magic version that this cluster was scaled with and try to scale it up with that specific version. 

Thank you for your investigation, insights, and attention to this matter. I very much appreciate it. I will let you know if I manage to have some success. Thanks again!

**Comment by joshua-vandenhoek** [comment]
Alright, through a series of tests I managed to determine that the version is MOST LIKELY 0.9.3. With the files in the state they were when I got them, it actually ran and got to `Starting ARM Deployment (RESOURCE GROUP). This will take some time...`. It did fail with the following message though:
```
FATA[0048] resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." 
```
I looked in the Azure portal and looked at what the specific error was, and this was the output:
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"VnetAddressSpaceCannotChangeDueToPeerings\",\r\n \"message\": \"Address space of the virtual network /subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.Network/virtualNetworks/<OUR VNET> cannot change when virtual network has peerings.\",\r\n \"details\": []\r\n }\r\n}"}]}
```

At least there is a new error. Do you know what that means? Never encountered this before. If this is outside of the scope of your support, then please let me know and I will try and direct it to the proper person/group. Thanks!

**Comment by rocketraman** [comment]
@joshua-vandenhoek While I haven't read through all the messages here, just looking at your last message, if the k8s vnet has network peerings and a non-standard address space, acs-engine sometimes craps out during scale / upgrade operations. Make note of the VNET's current address space, delete the network peerings, and try the operation again. Then, after the operation is done, reset the address space to the original value, and re-create the peerings.

See #1790.
