### ISSUE TITLE
Scaling a pool to 0 agents breaks LoadBalancer-type services

### ISSUE THREAD

**Issue by wbuchwalter** [Azure/acs-engine#3858]
**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
* acs-engine v0.21.2
* Kubernetes v1.10.7
* Deployed a cluster with 3 agent pools and 3 masters.

**What happened**:

Scaling one of the agent pools to 0 breaks all services of type `LoadBalancer` (don't know about other types of services) created or updated after the scaling operation.

For example, creating a new service with type `LoadBalancer` will fail, with following events:

```
  Type     Reason                      Age               From                Message                                                                                                                                     
  ----     ------                      ----              ----                -------                                                                                                                                     
  Normal   EnsuringLoadBalancer        3m (x5 over 10m)  service-controller  Ensuring load balancer                                                                                                                      
  Warning  CreatingLoadBalancerFailed  1m (x5 over 9m)   service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service polyaxon/polyaxon-polyaxon-ingress-backup: timed out w
aiting for the condition   
```
Looking at the `kube-controller-manager` logs I notice:

```
I0917 20:07:15.187694       1 azure_vmss.go:643] VirtualMachineScaleSetsClient.UpdateInstances for service (default/will-svc-test): scale set (k8s-k80-28106673-vmss) - updating, err=compute.VirtualMachineScaleSetsClie
nt#UpdateInstances: Failure sending request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="Required parameter 'upgradePolicies.instanceIds' is
 missing (null)."  
```

Note that `k8s-k80-28106673-vmss` is the name of the VMSS that was scaled to 0, so it seems we are not handling the case where there is no instance in the VMSS we are trying to update.
cc @feiskyer since I see he is the main contributor to `azure_vmss.go`.

**How to reproduce it** (as minimally and precisely as possible):
* Create a cluster with enough masters to support all kube-system pods, scale a pool to 0 agents.
* Create a new service, or edit an existing one. Issue described above will appear.

**Comment by feiskyer** [comment]
>  it seems we are not handling the case where there is no instance in the VMSS we are trying to update. 

Right. The case is not handled within cloud provider. Let me fix this after k8s code freeze.

**Comment by feiskyer** [comment]
Filed https://github.com/kubernetes/kubernetes/pull/68775 to fix this.
