### ISSUE TITLE
Regular crashing of Windows host nodes due to BSOD / BugCheck

### ISSUE THREAD

**Issue by ocdi** [Azure/acs-engine#3875]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: v0.20.9

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11.2

**What happened**:
It seems that Windows is restarting unexpectedly, especially when there is a lot of churn in running containers. I am unsure if this is the VM image being used by acs-engine or a general windows bug. I have captured memory.dmp's from machines that have rebooted unexpectedly and opened them to determine the crash

```BugCheck 7F, {8, ffffab01c0589ef0, ffff8a89a7024000, fffff807fafd1f17}

Probably caused by : vmswitch.sys ( vmswitch!VmsExtMpSendNetBufferLists+886 )

Followup:     MachineOwner
---------

nt!KeBugCheckEx:
fffff801`4ee4eca0 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:ffffab01`c0589db0=000000000000007f
```

The windows server version I am using is 1803 and I have stored 2 memory dumps with the same BugCheck.

**What you expected to happen**:

Not BSOD and reboot unexpectedly.

**How to reproduce it** (as minimally and precisely as possible):

This happens irregularly. I can supply `memory.dmp` files however I am unsure the best place to do so.

**Anything else we need to know**:

As it stands, I don't feel Windows containers are production grade, which is a shame. Either that or the base image of the windows containers on the version I am using is buggy and upgrading will fix, if that is the case that would be awesome.

**Comment by CecileRobertMichon** [comment]
@PatrickLang

**Comment by ocdi** [comment]
just an update, I opened a support request to Azure support and sent the crash dumps to them. They have acknowledged and engineers are investigating internally. I'm not sure if case numbers are sensitive but can share to anyone if you want to see it.

**Comment by tonyschollum** [comment]
I have had the exact same issue today. Azure support looked into it for me as the VM wouldn't come back online. Basically after the crash I ended up with two NIC's with the same mac address but different IPs. Once sorted out the node is back however pods no longer work on it. I am getting the below:

Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "a73aded9a1542c302821a11f633cb409bbdc5bf63cd1234460ba1a5dd1061b2e" network for pod "rifleman-pdf-generation-uat1-ddfbd8b6f-mxqn5": NetworkPlugin cni failed to set up pod "rifleman-pdf-generation-uat1-ddfbd8b6f-mxqn5_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input, failed to clean up sandbox container "a73aded9a1542c302821a11f633cb409bbdc5bf63cd1234460ba1a5dd1061b2e" network for pod "rifleman-pdf-generation-uat1-ddfbd8b6f-mxqn5": NetworkPlugin cni failed to teardown pod "rifleman-pdf-generation-uat1-ddfbd8b6f-mxqn5_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input]

**Comment by CecileRobertMichon** [comment]
This seems related to https://github.com/Azure/azure-container-networking/issues/242 (also https://github.com/Azure/azure-container-networking/issues/232 for the error logging problem). @ocdi do you see anything similar in the kubelet logs?

**Comment by sharmasushant** [comment]
@tonyschollum this is not related to windows crashing with BSOD. Can you please open a separate issue for this and attach c:\k\azure-vnet.log.* files

**Comment by ocdi** [comment]
@CecileRobertMichon annoyingly I killed the nodes that were affected. I have a single node left running from that cluster and am trying to trigger a BSOD by killing containers and having it restart them (that did seem to be related / trigger it). The windows containers are ASP.NET apps on full framework so I would be surprised if there was any particular traffic causing it, but it does seem with less network traffic going through there have been less crashes. I am too nervous to put production traffic on the cluster again unless we find an actual cause or definitive resolution.

I'm hoping the team looking at my support request find something looking at the crash dumps. :-)

**Comment by ocdi** [comment]
I heard back from support this morning. Apparently the fix will be in the upcoming windows release (ie the one after 1809), and the team are looking at back-porting the fix to earlier Windows releases. How and when that will end up on my cluster, I have no idea. For now I am running static windows servers and not using containers. I suspect we could close this now.
