### ISSUE TITLE
kubernetes dashboard doesn't reachable 

### ISSUE THREAD

**Issue by BarAluf** [Azure/acs-engine#3880]
**Is this a request for help?**:

yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

**What version of acs-engine?**:

**v0.21.2**

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:

Kubernetes dashboard is not reachable, using **"kubectl --namespace=kube-system port-forward svc/kubernetes-dashboard ..."** forwarding command. it happens in any browser.
In addition it works on Linux machine. thanks

**browser error:
your connection is not private
attackers might be trying to steal your information from 127.0.0.1.
Error: cert_invalid**

**What you expected to happen**:

to have an access the dashboard. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.10.7",
      "kubernetesConfig": {
        "networkPlugin": "kubenet",
        "privateCluster": {
          "enabled": true
        },
        "dockerBridgeSubnet": "172.25.0.1/16"
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "ELKTelemetryCluster",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/",
      "firstConsecutiveStaticIP": "X.Y.248.30",
      "vnetCidr": "X.Y.248.0/23"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D8s_v3",
        "OSDiskSizeGB": 200,
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/",
        "extensions": [
          {
            "name": "prometheus-grafana-k8s"
          }
        ]
      }
    ],
    "linuxProfile": {
      "adminUsername": "user",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "extensionProfiles": [
      {
        "name": "prometheus-grafana-k8s",
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

![capturek](https://user-images.githubusercontent.com/24398035/45808495-92fae080-bcce-11e8-9125-08cd042c21d1.PNG)

**Comment by jackfrancis** [comment]
Are you able to access this from a different browser?

**Comment by BarAluf** [comment]
no
