### ISSUE TITLE
Unknown JSON tag windowsVersion

### ISSUE THREAD

**Issue by davidmatson** [Azure/acs-engine#3883]
Acconding to the [docs](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/windows-details.md), windowsVersion is supported in the windowsProfile section, but when trying it with v0.22.0 (git commit 3e5ca5dde), I get the following error:
```
FATA[0000] error loading API model in generateCmd: error parsing the api model: Unknown JSON tag windowsVersion
```

apimodel snippet:
```
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": "replacepassword1234$",
      "windowsPublisher": "MicrosoftWindowsServer",
      "windowsOffer": "WindowsServerSemiAnnual",
      "windowsSku": "Datacenter-Core-1803-with-Containers-smalldisk",
      "windowsVersion": "1803.0.20180815"
    },
```

**Comment by davidmatson** [comment]
The [sample](https://github.com/Azure/acs-engine/blob/master/examples/windows/kubernetes-windows-version.json) shows using imageVersion instead. Looks like a discrepancy between docs and sample/implementation. Using the property name "imageVersion" appears to work fine currently.

**Comment by CecileRobertMichon** [comment]
@davidmatson this is a gap in the docs, would you like to open a PR to fix it?

**Comment by davidmatson** [comment]
Would updating the implementation to use windowsVersion be better? That would keep it consistent with the naming of the other related properties.

**Comment by davidmatson** [comment]
(Or change all the others to imagePublisher, imageOffer, imageSku)

**Comment by CecileRobertMichon** [comment]
I agree that it would be but it would be a more complex change because we would need to ensure backward compatibility to upgrade and scale clusters that were deployed using the current property naming.
