### ISSUE TITLE
Update Kube DNS

### ISSUE THREAD

**Issue by brendandburns** [Azure/acs-engine#389]
See:

https://github.com/kubernetes/kubernetes/commit/4fe2e82d8850db42a4e398a66bAb1dc511795710a

Assigning to Anthony for triage.

**Comment by colemickens** [comment]
That commit 404s. We also need to update heapster.

**Comment by colemickens** [comment]
Well, and k8s itself.

**Comment by anhowe** [comment]
Here's the exact pull request: https://github.com/kubernetes/kubernetes/pull/41826.

@colemickens does this mean upgrading from 1.5.3 to 1.5.4?

**Comment by colemickens** [comment]
Well that PR isn't related to 1.5.3->1.5.4 (or rather 1.5.5 now that it's out). But yes, we need to update all of these things:

* heapster
* kube-dns
* kubernetes
* check for kubernetes-dashboard updates

**Comment by JackQuincy** [comment]
Why is this high pri? Sorry I just don't understand the importantance

**Comment by anhowe** [comment]
updated in #470
