### ISSUE TITLE
Make creating a service principal and granting contributor rights a better experience

### ISSUE THREAD

**Issue by davidmatson** [Azure/acs-engine#3897]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
```
Version: v0.22.1
GitCommit: 0908e5151
GitTreeState: clean
```
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11.2

**What happened**:
kubectl create secret failed

**What you expected to happen**:
kubectl create secret should succeed

**How to reproduce it** (as minimally and precisely as possible):
tl;dr
The service principal needs to be provisioned with Owner permissions via IAM on both the key vault and storage account resources.

Details:
1. In apimodel.json, set `"enableEncryptionWithExternalKms": true` on a new resource group.
2. Run `kubectl create secret generic secret1 -n default --from-literal=mykey=mydata`.

Error message:
```
Error from server (InternalError): Internal error occurred: rpc error: code = Unknown desc = failed to get vault, error: failed to get vault, error: keyvault.VaultsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<clientId>' with object id '<objectId>' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.KeyVault/vaults/<keyVaultName>'."
```

3. Work around that error by running `az role assignment create --subscription $SubscriptionId --role Owner --assignee-object-id $servicePrincipalObjectId --scope keyVaultResourceId`.
4. Again run `kubectl create secret generic secret1 -n default --from-literal=mykey=mydata`.

Second error message:
```
Error from server (InternalError): Internal error occurred: rpc error: code = Unknown desc = failed to create key, error: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<clientId>' with object id <objectId>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Storage/storageAccounts/<keyVaultName>'."
```

5. Work around the second error by running `az role assignment create --subscription $SubscriptionId --role Owner --assignee-object-id $servicePrincipalObjectId --scope $storageAccountResourceId`.

The kubectl create secret command will now work.

**Comment by ritazh** [comment]
@davidmatson The service principal here is used by the Kubernetes Azure cloud provider to create Azure resources required by the cluster, for example, disks for volumes, loadbalancers for services, access keys from key vault, etc. 

When using acs-engine to create a new cluster on Azure, we expect the user to [create a service principal with Contributor role to the subscription or Contributor role to the resource group if the resource group is already created](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md#step-2-create-a-service-principal) then [update the cluster apimodel](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md#step-3-edit-your-cluster-definition) with the client id and client secret to be used for this purpose before using `acs-engine deploy`. 

In the case of using the`enableEncryptionWithExternalKms` feature, acs-engine will create the key vault and storage account needed for this feature and assign permissions for the service principal to the key vault and keys all via ARM. 

Hope this helps, please let us know if you have additional questions.

**Comment by davidmatson** [comment]
Sounds great. Thanks, @ritazh.

**Comment by davidmatson** [comment]
Ping to remove stale label.

**Comment by CecileRobertMichon** [comment]
I believe the new https://github.com/Azure/aks-engine/blob/master/docs/tutorials/quickstart.md and https://github.com/Azure/aks-engine/blob/master/docs/topics/service-principals.md provide enough clarity to close this issue. Let me know if you don't agree and we can transfer it to aks-engine.

**Comment by davidmatson** [comment]
If we could move to aks-engine, that would be great. I think the parts remaining are:
1. Specifying explicitly in the text that it's not just a matter of creating a service principal, but granting it Contributor rights on the entire resource group (I think this is implicit in the text today and only appears in the commands, but maybe I missed something).
2. Consider having aks-engine deploy automatically assign rights as needed (I think it already auto-creates the resource group if needed).

Thanks!
