### ISSUE TITLE
Customize Kubernetes Manifest YAML files

### ISSUE THREAD

**Issue by pidah** [Azure/acs-engine#3906]
FEATURE REQUEST

#3840 added functionality to customize Addon YAML files. We have a requirement to customize the pod security yaml which is part of kubernetesManifestSettingsInit https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/artifacts.go#L239-L272
We would like this functionality extended to kubernetesManifestSettingsInit

@tariq1890

**Comment by pidah** [comment]
Hi @tariq1890, sorry to chase, have you had cycles to look at this ? thanks o/

**Comment by tariq1890** [comment]
@pidah I haven't had the time to devote cycles for this unfortunately :(. Feel free to send in a PR (with tests if possible) our way and we'd be more than happy to review for you :)

**Comment by pidah** [comment]
Thanks @tariq1890 ! Will try and do that next week.
