### ISSUE TITLE
Use of kubectl with acs kubernetes always returns error

### ISSUE THREAD

**Issue by minherz** [Azure/acs-engine#392]
*** Problem description ***

Some `kubectl` commands (e.g. `delete`, `get`, `run`) when executed result in following error:
```
error: group map[:0xc08230bdc0 certificates.k8s.io:0xc0823b42a0 policy:0xc0823b4460 rbac.authorization.k8s.io:0xc0823b44d0 storage.k8s.io:0xc0823b4540 federation:0xc08230b8f0 authentication.k8s.io:0xc08230bea0 authorization.k8s.io:0xc0823b4000 autoscaling:0xc0823b4070 batch:0xc0823b4230 componentconfig:0xc0823b4310 extensions:0xc0823b43f0 apps:0xc08230be30] is already registered
```
More debug info when executing the command with additional flag `-v 8` shows:
```
F0312 14:42:03.668536   11612 helpers.go:119] error: group map[autoscaling:0xc0823b6070 batch:0xc0823b6230 certificates.k8s.io:0xc0823b62a0 componentconfig:0xc0823b6310 extensions:0xc0823b63f0 policy:0xc0823b6460 federation:0xc08230d8f0 authentication.k8s.io:0xc08230dea0 authorization.k8s.io:0xc0823b6000 rbac.authorization.k8s.io:0xc0823b64d0 storage.k8s.io:0xc0823b6540 :0xc08230ddc0 apps:0xc08230de30] is already registered
```

*** Environment details ***

Kubernetes ACS is created using Azure portal wizard. The commands executed after the following three comands are launched from powershell:
```
az login
az acs kubernetes install-cli
az acs kubernetes get-credentials
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

The test was done on Kubernetes ACS instance that was created with 1 master and 2 nodes (nodes running Windows)

*** Additional information ***
Executing `kubectl cluster-info dump` shows a long Json with information and ends up with
```
==== START logs for kube-system/heapster-v1.2.0-1448994189-4rln1 ====
Error from server: the server rejected our request for an unknown reason (get pods heapster-v1.2.0-1448994189-4rln1)
```

Command `kube create -f <file>` completes without errors, but the Kubernetes Web UI shows pods with errors.

**Comment by colemickens** [comment]
The two errors listed are likely misnomers. Can you please include the output for `kubectl describe pod <failed_pod_name>` for whatever pods have failed.

Please also share the command used to create the cluster.

**Comment by minherz** [comment]
@colemickens I have this error regardless there is a failed pod or not. Do you like me to create a failed node to test it or the valid node is good enough? Attempt to run the above command on valid port resulted with
```
F0313 11:47:56.718985    6096 helpers.go:119] error: group map[:0xc08230ddc0 authentication.k8s.io:0xc08230dea0 autoscaling:0xc0823b8070 batch:0xc0823b8230 componentconfig:0xc0823b8310 federation:0xc08230d8f0 authorization.k8s.io:0xc0823b8000 certificates.k8s.io:0xc0823b82a0 extensions:0xc0823b83f0 policy:0xc0823b8460 rbac.authorization.k8s.io:0xc0823b84d0 storage.k8s.io:0xc0823b8540 apps:0xc08230de30] is already registered
```

As you see this is exactly the same problem. It is either an issue related to behavior on Windows of golang or the broken assumption from integration with azure.

**Comment by colemickens** [comment]
Well, I was going to recommend upgrading `kubectl` as a naive guess... but it looks like that's probably the cause: https://github.com/kubernetes/kubernetes/issues/39494#issuecomment-271277522

Please upgrade `kubectl` and close this Issue if it worked. Thanks.

**Comment by minherz** [comment]
Is the correct location is http://storage.googleapis.com/kubernetes-release/release/v1.5.0/bin/windows/amd64/kubectl.exe ?
Matching first two numbers of the server and client version worked. I will create an issue in az cli so they will update `kubectl.exe` version.

**Comment by colemickens** [comment]
Sure, you can match all three too to whatever the apiserver is running.
