### ISSUE TITLE
Failed create pod sandbox - Azure CNI v 1.0.11 - windows vm scale sets

### ISSUE THREAD

**Issue by tonyschollum** [Azure/acs-engine#3920]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: v0.22.2 & v0.21.2

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11.3

**What happened**:
When deploying pods the following error displays (this is limited to the windows nodes)
This happens with all deployments after initial cluster setup, then after a few mins they fix themselves. However this then occurs again intermittently. Eventually one of my nodes did this for all pods and I was forced to re-deploy the whole cluster.

Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3e8c80c89964d7451e1aa6d56e3b904c98a2a00444e4dc40a2e7aebf8a4c813b" network for pod "rifleman-pdf-generation-staging-5956b7684f-2xh42": NetworkPlugin cni failed to set up pod "rifleman-pdf-generation-staging-5956b7684f-2xh42_default" network: netplugin failed but error parsing its diagnostic message "{\n \"cniVersion\": \"0.3.0\",\n \"interfaces\": [\n {\n \"name\": \"eth0\"\n }\n ],\n \"ips\": [\n {\n \"version\": \"4\",\n \"address\": \"10.240.0.85/12\",\n \"gateway\": \"10.240.0.1\"\n }\n ],\n \"routes\": [\n {\n \"dst\": \"0.0.0.0/0\",\n \"gw\": \"10.240.0.1\"\n }\n ],\n \"dns\": {\n \"nameservers\": [\n \"168.63.129.16\"\n ]\n }\n}{\n \"code\": 100,\n \"msg\": \"Failed to create endpoint: HNS failed with error : Element not found. \"\n}": invalid character '{' after top-level value

**What you expected to happen**:
The pods to deploy successfully and not have the issue above intermittently.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a cluster with 2 agent pools (windows with 2 agents, linux with 1 agent) using VMSS. Once cluster is up deploy approximately 10 pods. The red error message above displays for a few mins before self-correcting. However later the issue returns and doesn't resolve itself.

**Anything else we need to know**:
Azure CNI v 1.0.11

Below is the azure-vnet.log. These logs are from a newly deployed cluster, I was forced to re-deploy the cluster after I couldn't deploy any pods to one of the nodes (the above error kept occurring).

If one of the nodes gets stuck in this state again I will update the log file.

[azure-vnet.log](https://github.com/Azure/acs-engine/files/2427780/azure-vnet.log)

**Comment by tonyschollum** [comment]
Overnight one of the nodes has now started presenting this issue. It appears the node is crashing. Attached is the system errors log and an updated azure-vnet.log.

I will open the crashing issue with Azure but would still be good to get to the bottom of the CNI issue.

[azure-vnet2.log](https://github.com/Azure/acs-engine/files/2429787/azure-vnet2.log)
[system-error-logs.txt](https://github.com/Azure/acs-engine/files/2429788/system-error-logs.txt)

**Comment by tonyschollum** [comment]
Another update to azure-vnet log.

Unfortunately now neither of the nodes can schedule pods.
[azure-vnet3.log](https://github.com/Azure/acs-engine/files/2432112/azure-vnet3.log)

**Comment by tamilmani1989** [comment]
@tonyschollum we are looking at the issue. We will investigate and get back to you.

**Comment by zhiweiv** [comment]
I got same issue twice, restart node does not work, I have to rebuild k8s cluster.
Any update?

**Comment by tonyschollum** [comment]
Hi @zhiweiv ,

You could also try the following steps (from https://github.com/Azure/acs-engine/issues/4046):
- Remote into each windows node
- Stop the kubelet service: Stop-Service Kubelet -Force
- Delete c:\k\azure-vnet.json file: del azure-vnet.json
- Delete c:\k\azure-vnet-ipam.json file: azure-vnet-ipam.json
- Start the kubelet service: Start-Service Kubelet -Force

Whilst not a fix this should get your nodes up and running again without having to re-deploy the whole cluster.

**Comment by zhiweiv** [comment]
Thanks @tonyschollum 
The old cluster is already deleted, after a few days in new cluster, one Windows node crashed again, I added my comment on  #4046.

Seems k8s Windows is far from productin use. :(

**Comment by tonyschollum** [comment]
This seems to be resolved now with the latest hotfixes from windows.
