### ISSUE TITLE
kube-dns intermittent crashloop and pods are not able access internet

### ISSUE THREAD

**Issue by LostinCloud** [Azure/acs-engine#3930]
**Is this a request for help?**:
Help
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
0.20.9
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
"orchestratorRelease": "1.10",
"orchestratorVersion": "1.10.6",
 Ubuntu :16.04
 ACS Engine:0.20.9
**What happened**:
 Intermittent crash loop on kube-dns and pods are not talking to internet

**What you expected to happen**:
kube-dns should be running state and pods should talk to internet

**How to reproduce it** (as minimally and precisely as possible):
1)	Use below template to generate ACS k8s ARM templates by using ACS engine.
 Vnet cidr: 10.120.152.0/24
 Subnet cidr: 10.120.152.0/26
  
[devdevopsk8s_json.txt](https://github.com/Azure/acs-engine/files/2435776/devdevopsk8s_json.txt)

a.	az group create --name DEV-DevOps-ACS-NET-RG --location <location>
b.	az network vnet create --name Dev-DevOps-ACS-vnet01--resource-group DEV-DevOps-ACS-NET-RG --address-prefixes 10.120.152.0/24--subnet-name Dev-DevOps-ACS-subnet01 --subnet-prefix 10.120.152.0/26
c. ./acs-engine.exe generate devdevopsk8sjson
d. az group deployment create --resource-group DEV-DevOps-ACS-RG --template-file ./azuredeploy.json --parameters ./azuredeploy.parameters.json --verbose

**Anything else we need to know**:
  Noticed Result: kube-dns will have intermittent crashloops
  Apply kube-dns add on with a cluster domain
[kube-dns-deployment_yaml.txt](https://github.com/Azure/acs-engine/files/2435771/kube-dns-deployment_yaml.txt)
•Replace attached kube-dns addon with existing /etc/kubernetes/addons/kube-dns-deployment.yaml
•Redeploy kube-dns pod 
kubectl -n kube-system delete deployment kube-dns-v20
kubectl -n kube-system delete service kube-dns
kubectl -n kube-system delete sa kube-dns
kubectl -n kube-system delete deployment kube-dns
  This will retrigger kube-dns deployment

  Outcome: kube-dns pods are in running state however pods are not talking to internet.

**Comment by dstrebel** [comment]
Can you pull and post the logs from the kube-dns pod `kubectl logs kube-dns -n kube-system`?

**Comment by jackfrancis** [comment]
@LostinCloud did the provided cluster config ever work on a prior cluster? Lack of pod networking usually speaks to either network config pathology or service principals not having access to get NICs from Azure API.

**Comment by LostinCloud** [comment]
> Can you pull and post the logs from the kube-dns pod `kubectl logs kube-dns -n kube-system`?
@dstrebel  Please find the attached kube dns logs. I have attached kube-dns , dns configuration and jenkins pod issue(unable to talk to internet)
[kubedns.log](https://github.com/Azure/acs-engine/files/2439892/kubedns.log)

**Comment by LostinCloud** [comment]
> provided cluster config ever work on a prior cluste

@jackfrancis - No.I am building k8s cluster with this config.unfortunately, its failing now. I have seen below warnings in kube dns side car logs.Apart from logs are cleans and kube-dns has crash loops too.

 Regarding service principals - service principal is configured to network(vnet) and k8s resource groups in the Access control blade.Do i need to perform any other steps? Please let me know.

devgcpadmin@k8s-master-40240024-0:~$ kubectl logs kube-dns-b74c646c5-6vfjl -n kube-system -c sidecar
I1002 21:50:59.186777       1 main.go:51] Version v1.14.8
I1002 21:50:59.186854       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.gcpdevdevops. Interval:5s Type:33} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.gcpdevdevops. Interval:5s Type:33}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I1002 21:50:59.186883       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.gcpdevdevops. Interval:5s Type:33}
I1002 21:50:59.186933       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.gcpdevdevops. Interval:5s Type:33}
W1002 21:50:59.187567       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:50014->127.0.0.1:53: read: connection refused
W1002 21:51:04.188104       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:52306->127.0.0.1:53: read: connection refused
W1002 21:51:09.188522       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:34811->127.0.0.1:53: read: connection refused
