### ISSUE TITLE
Can not create private cluster with VMSS masters 

### ISSUE THREAD

**Issue by uzd** [Azure/acs-engine#3932]
**Is this a request for help?**:

Help

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

Version: canary
GitCommit: e89eb97
GitTreeState: dirty

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 

**What happened**:
I tried to deploy a private cluster with master's availability profile set to VirtualMachineScaleSets but it failed with:
FATA[0017] resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The template variable 'masterPublicIPAddressName' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'."

**What you expected to happen**:
To create a private cluster with master VMSS 

**How to reproduce it** (as minimally and precisely as possible):

acs-engine deploy -g my-cluster-k8s --dns-prefix my-cluster --location australiaeast --api-model kubernetes.json --subscription-id XXXXX

**Anything else we need to know**:
The kubernetes.json :
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10",
      "kubernetesConfig": {
        "enableEncryptionWithExternalKms": true,
        "privateCluster": {
          "enabled": true,
          "jumpboxProfile": {
            "name": "jumpbox",
            "vmSize": "Standard_D2s_v3",
            "osDiskSizeGB": 30,
            "username": "azureuser",
            "publicKey": "ssh-rsa XXXX"
          }
        }
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "",
      "vmSize": "Standard_D2s_v3",
      "vnetSubnetId": "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Network/virtualNetworks/vnet/subnets/XXXX",
      "agentVnetSubnetId": "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Network/virtualNetworks/vnet/subnets/XXXX",
      "availabilityProfile": "VirtualMachineScaleSets",
      "vnetCIDR": "172.16.0.0/22"
    },
    "agentPoolProfiles": [
      {
        "name": "nodes",
        "count": 2,
        "vmSize": "Standard_D4s_v3",
        "availabilityProfile": "VirtualMachineScaleSets",
        "vnetSubnetId": "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Network/virtualNetworks/vnet/subnets/XXXX"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa XXXX"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "XXXX",
      "secret": "XXXX",
      "objectId": "XXXX"
    }
  }
}

**Comment by CecileRobertMichon** [comment]
@uzd VMSS master implementation is still in progress, the private cluster feature is not yet supported.

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/pull/3936
