### ISSUE TITLE
Switch acs-engine to use CoreDNS instead of kube-DNS

### ISSUE THREAD

**Issue by daschott** [Azure/acs-engine#3935]
**Is this a request for help?**:

No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature request

---

**What version of acs-engine?**:

All current versions

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:
Kubernetes conformance tests:
[Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance]
[Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance]

are failing because we are receiving authoritative does not exist upon record lookup via test invoking kube-DNS. Since Kubernetes 1.11, Kubernetes uses coreDNS by default and we need to switch over.

**Comment by PatrickLang** [comment]
Here's the KEP recommending CoreDNS as default for v1.11
https://github.com/kubernetes/community/blob/master/keps/sig-network/0012-20180518-coredns-default-proposal.md

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/issues/3385

**Comment by neurot1cal** [comment]
I know that CoreDNS is the default now as of `0.23` - When does this become officially "Stable" / "GA"? :) Whats the criteria for that? Seems pretty solid so far, are we tracking any known issues? I'm mostly concerned about Windows nodes at this point. @CecileRobertMichon  @PatrickLang

**Comment by CecileRobertMichon** [comment]
coredns is now default for 1.12+
