### ISSUE TITLE
MySQL connectivity between pods

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/acs-engine#3958]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: Latest

---

My customer using acs-engine is facing an issue with MySQL pod connectivity. Below are details -

```
> kubectl get pods -o wide
NAME          READY     STATUS    RESTARTS   AGE       IP             NODE
cpp-mysql-0   2/2       Running   7          42m       10.244.19.14   k8s-agentpool0-43274316-4
cpp-mysql-1   2/2       Running   6          39m       10.244.13.14   k8s-agentpool0-43274316-7
```
```
> kubectl exec -it cpp-mysql-0 -- bash 
  # Now inside the pod cpp-mysql-0 i try to connect to the local mysql server.
  # This working.
  > mysqlsh --uri root:$MYSQL_ROOT_PASSWORD@10.244.19.14:13306 --json=raw --sqlc -e "SELECT 1"

```
```
> kubectl exec -it cpp-mysql-1 -- bash 
  # Now inside the pod cpp-mysql-1 i try to connect to the other mysql server.
  # This does not working 
  > mysqlsh --uri root:$MYSQL_ROOT_PASSWORD@10.244.19.14:13306 --json=raw --sqlc -e "SELECT 1"
  MySQL Error 2003 (HY000): Can't connect to MySQL server on '10.244.19.14' (110)
```

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** : Kubernetes

**What happened**:  Customer is unable to connect MySQL running on another pod.

**What you expected to happen**: Customer should be able to connect MySQL running on another pod.

**How to reproduce it** (as minimally and precisely as possible): N/A

**Anything else we need to know**: N/A

**Comment by Mahesh-MSFT** [comment]
Thanks @khenidak. Yes. It is kubenet. Anything specific to look for in controller manager logs?

**Comment by jackfrancis** [comment]
@Mahesh-MSFT any updates from the customer?

**Comment by Mahesh-MSFT** [comment]
@jackfrancis This issue is resolved after correcting NSG rules. Closing this issue now.
