### ISSUE TITLE
conformance tests fail on 1.12 clusters

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#3976]
There are some new test behaviors in 1.12 vs 1.11 for validating that all nodes are schuedulable.

Here is the 1.12 test:

https://github.com/kubernetes/kubernetes/blob/v1.12.0/test/e2e/framework/util.go#L2651

Here is the test as it was in 1.11:

https://github.com/kubernetes/kubernetes/blob/v1.11.0/test/e2e/framework/util.go#L2624

The OR condition below is new compared to 1.11:

`if !isNodeSchedulable(node) || !isNodeUntainted(node) {`

And the final argument in this function invocation is also new:

`IsNodeConditionSetAsExpectedSilent(notSchedulable[i], v1.NodeNetworkUnavailable, false), notSchedulable[i].Spec.Taints)`

**Comment by lachie83** [comment]
The code has started looking for the following node label `node-role.kubernetes.io/master: ""` on the masters before it can continue. This is new code that was introduced in 1.12.
