### ISSUE TITLE
Generate proxy certs script small issues

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/acs-engine#3984]
https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesmastergenerateproxycertscript.sh

Run by default on master nodes when `ENABLE_AGGREGATED_APIS` is True (default for k8s 1.9+).

1) Keys are sometimes generated as part of the script and I've noticed sometimes get printed in `/var/log/cluster-provision.log`. We should be redacting secrets in the logs.

Example output: 

```
Generating RSA private key, 2048 bit long modulus
.......+++
.................................................................................................+++
e is 65537 (0x10001)
Generating RSA private key, 2048 bit long modulus
....+++
...+++
e is 65537 (0x10001)
Signature ok
subject=/CN=aggregator/O=system:masters
Getting CA Private Key
member 2f72769ab698d244 is healthy: got healthy result from https://10.239.255.239:2379
member 6157595d95058788 is unreachable: no available published client urls
member 93d02c474f075436 is healthy: got healthy result from https://10.239.255.240:2379
cluster is healthy
Executed "etcdctl cluster-health" 1 times
 -----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
 -----BEGIN RSA PRIVATE KEY-----
REDACTED
-----END RSA PRIVATE KEY-----
 -----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
```

(where the `REDACTED` parts actually show in the logs).

2) Investigate why one of the members appears unhealthy in the above, is it reproducible? 100% of the time? 
```member 2f72769ab698d244 is healthy: got healthy result from https://10.239.255.239:2379
member 6157595d95058788 is unreachable: no available published client urls
member 93d02c474f075436 is healthy: got healthy result from https://10.239.255.240:2379
cluster is healthy```

**Comment by ryanhartje** [comment]
Hi,

I walked through the script to find where it would be outputting the contents of the cert, and pushed a change to stop that. 

I'm new to this project however, so I'm not sure what environment this is supposed to run in. Could you point me in the right direction for testing this change so I can see where the etcd peers are having a hiccup? 

Thanks in advance for any help.

**Comment by tariq1890** [comment]
Hi @ryanhartje . Thanks for the PR. A good way to validate would be to check the provision source log in the Artifacts tab of  CircleCI and see if they have been redacted. You can check the CircleCI build logs for other PRs for comparison. ( You would be able to see the generated etcd proxy certs in those logs)
