### ISSUE TITLE
Support specifying Tiller version just like orchestratorVersion, dockerEngineVersion

### ISSUE THREAD

**Issue by davidmatson** [Azure/acs-engine#3985]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
```
Version: v0.22.4
GitCommit: 4baf4ceb9
GitTreeState: clean
```
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11.3

**What happened**:
An older version of Helm (2.8.1) was automatically installed.

**What you expected to happen**:
A newer Helm version (ex., 2.11.0) can be specified explicitly in api-model.json, like with orchestratorVersion and dockerEngineVersion.

As far as I can tell there's no way to specify the Helm version currently:
https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md

**Comment by grenzr** [comment]
helm is a client to tiller which probably runs in your Kubernetes cluster unless you purposely chose to remove it.

Have a look again at https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md and search for tiller. 

The version of tiller needs to match the version of helm you're using, although to be fair a simple `helm init --wait --upgrade` will upgrade whatever version of tiller you have deployed to work with the helm version you're working with.

**Comment by davidmatson** [comment]
Thanks - I see the "image": "myDockerHubUser/tiller:v3.0.0-alpha" part - is there a way I can just request a different version of the official tiller without customizing anything else? A tillerVersion property would be great.

**Comment by CecileRobertMichon** [comment]
I think what you want is already possible, see: https://github.com/Azure/acs-engine/blob/api-versions/docs/clusterdefinition.md#L124. You can use the `image` field to customize the Tiller version.

**Comment by davidmatson** [comment]
For other components, there's a nice syntax for customizing just the version part without needing to know anything else like repository name. Would that be possible to do for tillerVersion as well?

**Comment by CecileRobertMichon** [comment]
Tiller is a Kubernetes addon so it's a bit different from other components like Kubernetes itself or Etcd. For those, we maintain a mirror with those binaries and a curated list of version and download the requested version during acs-engine provisioning. For addons, we include the image spec in the addon yaml that gets deployed to your cluster (https://github.com/Azure/acs-engine/blob/api-versions/parts/k8s/addons/kubernetesmasteraddons-tiller-deployment.yaml#L70) and that needs to be the full image spec. You can follow the default image format and replace the version but you would need to make sure that the image exists. For example, `gcr.io/kubernetes-helm/tiller:v${TILLER_VERSION}`.

**Comment by davidmatson** [comment]
I see. Let me see if I undestand the minimum syntax required to specify a different tiller version:

```
"kubernetesConfig": {
    "addons": [
        {
            "name": "tiller",
            "containers" : [
                {
                    "image": "gcr.io/kubernetes-helm/tiller:v2.11.0"
                }
            ]
        }
    ]
}
```

Or is that not quite sufficient? (Does the container name and/or other addon/container properties need to be specified as well even if they're not being changed?)

**Comment by davidmatson** [comment]
(and for some reason I'm getting a 404 of the GitHub blob links above)

**Comment by CecileRobertMichon** [comment]
Yes, that should be sufficient.

I've fixed the links, sorry about that.

**Comment by davidmatson** [comment]
Sounds good; thanks!

**Comment by davidmatson** [comment]
I'm trying this out in practice, and getting an error. Any ideas what's going wrong?
```
FATA[0005] error generating template z:\my\apimodel.json: runtime error: index out of range - goroutine 1 [running]:
runtime/debug.Stack(0xc000add468, 0x13ac200, 0x230e060)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/Azure/acs-engine/pkg/acsengine.(*TemplateGenerator).GenerateTemplate.func2(0xc000adfa10, 0xc000adf9f0, 0xc000adfa00)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/pkg/acsengine/template_generator.go:78 +0x75
panic(0x13ac200, 0x230e060)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
text/template.errRecover(0xc000adf7d0)
        /usr/local/go/src/text/template/exec.go:160 +0x1d7
panic(0x13ac200, 0x230e060)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
text/template.errRecover(0xc000ade270)
        /usr/local/go/src/text/template/exec.go:160 +0x1d7
panic(0x13ac200, 0x230e060)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
github.com/Azure/acs-engine/pkg/acsengine.getAddonFuncMap.func1(0xc0004740d3, 0x6, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/pkg/acsengine/engine.go:700 +0xbd
reflect.Value.call(0x1360080, 0xc0005043c0, 0x13, 0x152bc38, 0x4, 0xc0005086a0, 0x1, 0x1, 0x1525bc0, 0x1, ...)
```
(more omitted)
