### ISSUE TITLE
apiVersionCompute missing from generated templates

### ISSUE THREAD

**Issue by MarcPow** [Azure/acs-engine#4003]
**Is this a request for help?**: Yes.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.23.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

N/A

**What happened**:   

Newly Generated templates that are generated from 
https://raw.githubusercontent.com/Azure/acs-engine/master/examples/windows/kubernetes.json
are not deployable

Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template variable 'apiVersionCompute' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'.

**What you expected to happen**:
normal deployment

**How to reproduce it** (as minimally and precisely as possible):

Param(
    [Parameter(Mandatory = $false,
               HelpMessage="Temp Directory.")]
    [String] $TempDir = [System.IO.Directory]::GetCurrentDirectory() + "\tmp\",

    [Parameter(Mandatory = $true,
               HelpMessage="Name of the input directory.")]
    [ValidateNotNullOrEmpty()]
    [String] $ClusterName,
    
    [Parameter(Mandatory = $false)]
    [Int32] $NodeCount,

    [Parameter(Mandatory = $false)]
    [System.String] $ServicePrincipalGuid = $null,

    [Parameter(Mandatory = $false)]
    [String] $ServicePrincipalPassword = $null
    )

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$PSDefaultParameterValues['*:ErrorAction']='Stop'

$TempDir = [System.IO.Path]::GetFullPath($TempDir);

New-Item -Path $TempDir -ItemType directory -Force -ErrorAction SilentlyContinue
$TempDir = (Join-Path $TempDir ([System.Guid]::NewGuid().ToString()));
Remove-Item -Recurse -Path $TempDir -Force -ErrorAction SilentlyContinue
New-Item -Path $TempDir -ItemType directory -Force -ErrorAction SilentlyContinue
$dnsPrefix = $ClusterName;
$windowsUser = "azureuser"
$windowsPassword = "passwordpassword";
$groupName = $ClusterName + "RG";

$kubernetesInputFile = (Join-Path $TempDir "kubernetes-windows.json");
Invoke-WebRequest -UseBasicParsing https://raw.githubusercontent.com/Azure/acs-engine/master/examples/windows/kubernetes.json -OutFile $kubernetesInputFile;
$engineFile = (Join-Path $TempDir "acs-engine.zip");
$url = "https://github.com/Azure/acs-engine/releases/download/v0.23.0/acs-engine-v0.23.0-windows-amd64.zip";
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
try { (New-Object System.Net.WebClient).DownloadFile($url, $engineFile) } catch { Write-Error $_.Exception }
Expand-Archive -Path $engineFile -DestinationPath $TempDir -Force

az group create --location westus2 --name $groupName

$groupId = (az group show --resource-group $groupName --query id).Replace("""","")

$acrScope = az acr show -n testrepositoryname --query id --output tsv

$sp = $null;
$scopes = "$($groupId) $($acrScope)"
if ($servicePrincipalGuid -eq $null)
{
    $sp = az ad sp create-for-rbac --role="Contributor" --scopes=$scopes | ConvertFrom-JSON
}
else
{
    $readSp = az ad sp show --id $servicePrincipalGuid | ConvertFrom-JSON
    $sp = "{'appId':'$($servicePrincipalGuid)', 'password': '$($servicePrincipalPassword)'}" | ConvertFrom-JSON
    az role assignment create --role="Contributor" --assignee $readSp.appId --scope=$acrScope
    az role assignment create --role="Contributor" --assignee $readSp.appId --scope=$groupId
}

$inJson = Get-Content $kubernetesInputFile | ConvertFrom-Json
$inJson.properties.agentPoolProfiles[0].count = $NodeCount;
$inJson.properties.orchestratorProfile.orchestratorRelease = "1.12";
$inJson.properties.masterProfile.dnsPrefix = $dnsPrefix
$inJson.properties.windowsProfile.adminPassword = $windowsPassword
$inJson.properties.windowsProfile.adminUsername = $windowsUser
$inJson.properties.linuxProfile.ssh.publicKeys[0].keyData = [string](Get-Content (Join-Path $Env:UserProfile "\.ssh\id_rsa.pub"));
$inJson.properties.servicePrincipalProfile.clientId = $sp.appId
$inJson.properties.servicePrincipalProfile.secret = $sp.password
$kubernetesOutputFile = (Join-Path $TempDir "kubernetes-complete.json");
$inJson | ConvertTo-Json -Depth 5 | Out-File -Encoding ascii -FilePath $kubernetesOutputFile;
$acsExe = (Join-Path $TempDir "acs-engine-v0.23.0-windows-amd64\acs-engine.exe");
$armDirectory = (Join-Path $TempDir "arm");
& $acsExe generate $kubernetesOutputFile --output-directory $armDirectory;
$templateFile = (Join-Path $armDirectory "azuredeploy.json");
$paramFile = (Join-Path $armDirectory "azuredeploy.parameters.json");

Write-Host "Please remember to apply one of the workarounds here to acquire a kubeconfig for this cluster";
Write-Host "https://github.com/Azure/azure-cli/issues/7216#issuecomment-421226435";
az group deployment create --name $ClusterName --resource-group $groupName --template-file $templateFile --parameters $paramFile;

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@MarcPow can you try again with [v0.23.1](https://github.com/Azure/acs-engine/releases/tag/v0.23.1)?

**Comment by MarcPow** [comment]
Great!  Fixed by https://github.com/Azure/acs-engine/pull/3909.
