### ISSUE TITLE
ACS-Engine 0.23.1 deploys clusters with non-functional CoreDns

### ISSUE THREAD

**Issue by MarcPow** [Azure/acs-engine#4011]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.23.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.12.1

**What happened**:

Events:
  Type     Reason          Age                 From                   Message
  ----     ------          ----                ----                   -------
  Normal   Scheduled       55m                 default-scheduler      Successfully assigned kube-system/coredns-56684f94d6-h9btz to 35934k8s9000
  Normal   Pulling         54m (x3 over 54m)   kubelet, 35934k8s9000  pulling image "coredns/coredns:1.2.2"
  Warning  Failed          54m (x3 over 54m)   kubelet, 35934k8s9000  Failed to pull image "coredns/coredns:1.2.2": rpc error: code = Unknown desc = no matching manifest for windows/amd64 in the manifest list entries
  Normal   SandboxChanged  54m (x7 over 54m)   kubelet, 35934k8s9000  Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          4m (x225 over 54m)  kubelet, 35934k8s9000  Back-off pulling image "coredns/coredns:1.2.2"

**What you expected to happen**:

ACS-Engine deploys a DNS that works

**How to reproduce it** (as minimally and precisely as possible):

Deploy a standard cluster with ACS-Engine 0.23.1

**Anything else we need to know**:

**Comment by MarcPow** [comment]
I have a cluster with one Linux master and 3 Windows agents.

The issue is that my coredns happened to get scheduled on one of the Windows boxes (instead of the Linux master).  As such, it got stuck there temporarily.

**Comment by jackfrancis** [comment]
@MarcPow can you build from source on PR #4014?

If not, we'll test it out and report back.

**Comment by MarcPow** [comment]
To your request - 

{
    "apiVersion":  "vlabs",
    "properties":  {
                       "orchestratorProfile":  {
                                                   "orchestratorType":  "Kubernetes",
                                                   "orchestratorRelease":  "1.12"
                                               },
                       "masterProfile":  {
                                             "count":  1,
                                             "dnsPrefix":  "ClarityOrDie22",
                                             "vmSize":  "Standard_D2_v3"
                                         },
                       "agentPoolProfiles":  [
                                                 {
                                                     "name":  "windowspool2",
                                                     "count":  3,
                                                     "vmSize":  "Standard_D2_v3",
                                                     "availabilityProfile":  "AvailabilitySet",
                                                     "osType":  "Windows",
                                                     "osDiskSizeGB":  128,
                                                     "extensions":  [
                                                                        {
                                                                            "name":  "winrm"
                                                                        }
                                                                    ]
                                                 }
                                             ],
                       "windowsProfile":  {
                                              "adminUsername":  "azureuser",
                                              "adminPassword":  "6a7cd99e-93a0-4cc8-9e57-d30ba5de1cff"
                                          },
                       "linuxProfile":  {
                                            "adminUsername":  "azureuser",
                                            "ssh":  {
                                                        "publicKeys":  [
                                                                           {
                                                                               "keyData":  "keykey"
                                                                           }
                                                                       ]
                                                    }
                                        },
                       "servicePrincipalProfile":  {
                                                       "clientId":  "c503f886-5e69-4ec8-bbdb-f941949a3287",
                                                       "secret":  "secretsecret"
                                                   },
                       "extensionProfiles":  [
                                                 {
                                                     "name":  "winrm",
                                                     "version":  "v1"
                                                 }
                                             ]
                   }
}

**Comment by MarcPow** [comment]
At the moment, I don't have the ability to build from source.

So instead, I pulled down the current deployment/coredns yaml, updated it with a node-selector, and re-applied.  It seems to work like a charm:

Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-6pzrg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-6pzrg
    Optional:    false
QoS Class:       Burstable
**Node-Selectors:  beta.kubernetes.io/os=linux**
Tolerations:     CriticalAddonsOnly

**Comment by MarcPow** [comment]
Update:  My manual update isn't stable.  Something is removing my node selector, but I assume that's automation around the deployment under ACS that I don't fully understand, being a newbie and all.  But I'm reasonably convinced that when applied, the node selector works appropriately.
