### ISSUE TITLE
Feature Request: Support Docker CE 18.03

### ISSUE THREAD

**Issue by MarcPow** [Azure/acs-engine#4029]
**Is this a request for help?**:

No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature Request
---

**What version of acs-engine?**:

0.23.1
---

    "dockerEngineVersion": {
      "allowedValues": [
        "17.05.*",
        "17.04.*",
        "17.03.*",
        "1.13.*",
        "1.12.*",
        "1.11.*"
      ],
      "metadata": {
        "description": "The docker engine version to install."
      },
      "type": "string"
    },

**Comment by CecileRobertMichon** [comment]
Sadly, because of unresolved license limitations we are currently unable to move to new Docker CE versions (see https://github.com/Azure/AKS/issues/63 for context). There has been a push to move to Moby instead, you can track the effort at https://github.com/Azure/acs-engine/pull/3896

**Comment by PatrickLang** [comment]
Docker EE-basic 18.03 is available for all licensed Windows Server customers. I'm tracking this upgrade in #3852 

Linux users would need their own Docker EE license.
