### ISSUE TITLE
ManagedIdentity api version incorrect

### ISSUE THREAD

**Issue by kkmsft** [Azure/acs-engine#4034]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Bug
---

**What version of acs-engine?**:
---
HEAD of the tree.

 

The ManagedIdentity api version has been replaced with the apiVersionCompute, instead of "2015-08-31-PREVIEW". Looks like a regression.  PR has been raised #4032  for this issue to be fixed and will include the e2e test, which should catch this regression, once we able to successfully move the role assignment to ARM template.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8s

**What happened**:
When creating a user assigned identity cluster, the api version would mismatch and deployment will fail.

**What you expected to happen**:
The deployment should go through.

**How to reproduce it** (as minimally and precisely as possible):
User assigned MSI cluster creation.

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
fixed in https://github.com/Azure/acs-engine/pull/4048
