### ISSUE TITLE
Auto-scaling of agent/worker nodes in Azure Container Service [Kubernetes]

### ISSUE THREAD

**Issue by mfaizanse** [Azure/acs-engine#405]
Auto-scaling of agent/worker nodes in Azure Container Service based on the CPU/Resource usage.

I asked this [question on stackoverflow](http://stackoverflow.com/questions/42785617/auto-scaling-of-agent-worker-nodes-in-azure-container-service-kubernetes) and got the answer that currently its not supported. I want to know that whether this feature will be in any of the next releases of ACS or not?

I know about the manual scaling using the azure portal or Azure CLI 2.0.

**Comment by colemickens** [comment]
Please don't file issues for ACS here, you can ask questions on the [ACS](https://github.com/Azure/ACS) repo.
This repo is meant only for the open source component.

But no, there's no ETA for auto-scaling. Eventually we will move to VMSS where auto-scaling is already enabled, but we have no ETA for that either.
