### ISSUE TITLE
Update Windows setup to create pause container for Windows Server 2019

### ISSUE THREAD

**Issue by PatrickLang** [Azure/acs-engine#4053]
https://github.com/Azure/acs-engine/blob/17aa20ed646116e408521e667036875ef2dabd2f/parts/k8s/windowskubeletfunc.ps1#L138 needs to be updated to work with 2019 / 1809

**Comment by sylus** [comment]
Any chance to update this since 1809 sku is released?

**Comment by sylus** [comment]
They have a mention to 1809 in the readme but no tags.
