### ISSUE TITLE
ip-masq-agent daemonset does not work in AzureChinaCloud

### ISSUE THREAD

**Issue by haoxin** [Azure/acs-engine#4063]
**Is this a request for help?**:

request
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE
---

**What version of acs-engine?**:
0.23.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes
**What happened**:
can't pull ip-masq-agent image 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by andyzhangx** [comment]
would you ssh to master node, and then run following:
 - modify addon config
```
sudo vi /etc/kubernetes/addons/ip-masq-agent.yaml
```

change `gcr.io/google-containers/ip-masq-agent-amd64:v2.0.0` to `gcr.akscn.io/google-containers/ip-masq-agent-amd64:v2.0.0`, and then wait for a few minutes to take effect.

 - delete all `azure-ip-masq` pods search by `kubectl get po -n kube-system -o wide | grep masq`, e.g.
` kubectl delete po azure-ip-masq-agent-8xs56 -n kube-system`

**Comment by andyzhangx** [comment]
hi @jackfrancis, I found some addons are using `gcr.io` which is not accessable on Azure china, is there any way to replace that with `gcr.azk8s.cn` in acs-engine code level. Currently I am asking user to edit config file on master node which is not a friendly way.

https://github.com/Azure/acs-engine/blob/62f119b5f82c1037e8cd511edc676032ebf6e7cd/parts/k8s/addons/ip-masq-agent.yaml#L30
https://github.com/Azure/acs-engine/blob/62f119b5f82c1037e8cd511edc676032ebf6e7cd/parts/k8s/addons/dns-autoscaler.yaml#L21

**Comment by andyzhangx** [comment]
@haoxin already fixed by https://github.com/Azure/acs-engine/pull/4190

**Comment by shm007g** [comment]
This error makes pod can't access network for me. Cost me 2 days to find this out.
You can't even use `kubectl set image ds/azure-ip-masq-agent ...` to update this.
And this issue fixed it for me for good.
