### ISSUE TITLE
CSE error: exit code 84

### ISSUE THREAD

**Issue by MirzaSikander** [Azure/acs-engine#4064]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): issue

---

**What version of acs-engine?**:
Version: v0.23.1
GitCommit: 94d7cf6fb
GitTreeState: clean

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes v1.10.8

**What happened**:
Deployment failed.

Here is the error
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=84\\n[stdout]\\n\\n[stderr]\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}
```
The VMSS deployment had a status of `Conflict`
![image](https://user-images.githubusercontent.com/2823474/47133153-474f3e80-d25c-11e8-91e6-aa4e8036f465.png)

**What you expected to happen**:
Deployment should succeed.

**How to reproduce it** (as minimally and precisely as possible):
Here is the cluster definition:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
        "gcHighThreshold" : 60,
        "gcLowThreshold" : 40,
        "addons": [
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "config": {
              "minNodes": "1",
              "maxNodes": "10"
            }
          }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "k8s-athens-internal-01",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 1,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "OSDiskSizeGB": 100
      },
      {
        "name": "agentpool2",
        "count": 20,
        "vmSize": "Standard_NC6",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "OSDiskSizeGB": 100
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<SSH PUBLIC KEY>"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "<APPID>",
      "secret": "<PASSWORD>"
    }
  }
}
```

**Anything else we need to know**:

**Comment by MirzaSikander** [comment]
The funny thing is that I can't tell which VM failed because all of them are reporting `provisioning success` for the `vmssCSE`

**Comment by CecileRobertMichon** [comment]
Hi @MirzaSikander, it looks like the extension failed with exit code `84` which means that the NVIDIA driver failed to start for your GPU node (see https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/troubleshooting.md#vmextensionprovisioningerror-or-vmextensionprovisioningtimeout). Are you able to retry? This could be a transient error.

**Comment by MirzaSikander** [comment]
@CecileRobertMichon Yes you are right.
I have uploaded the cluster-provision.log from one of the VMs that failed.
[cluster-provision.log](https://github.com/Azure/acs-engine/files/2508414/cluster-provision.log)

How should I retry this?

**Comment by CecileRobertMichon** [comment]
@MirzaSikander thanks for the logs. We are aware of transient failures with GPU and are looking into improving stability. For now, please delete your cluster/rg and retry the deployment operation (same way you deployed the first time).

**Comment by MirzaSikander** [comment]
Oh I can't delete it as the other nodes are being used. Is there a way to manually fix these 2 nodes?

**Comment by MirzaSikander** [comment]
I removed those 2 nodes and did a scale up command but the new nodes still failed. What is the solution to this problem?

**Comment by MirzaSikander** [comment]
Just for giggles, I scaled up to twice as many nodes (previously 20 to 40) and 14 of the new nodes failed for the same reason. This does seem to be a transient issue **but** it definitely needs to be addressed as the failure rate is much higher. Is there a bug for this?

**Comment by jackfrancis** [comment]
@MirzaSikander Can you paste `/var/log/azure/cluster-provision.log` from another one of the failed nodes starting from the 1st attempt? It seems to be complaining that from dpkg's perspective the driver is already installed. I wonder if at some point there in fact was a successful driver installation, but we got a spurious non-zero exit code.

Also, the changes in this PR, run overnight, have not reproduced the symptoms, so those optimizations may be what we need:

https://github.com/Azure/acs-engine/pull/4104

**Comment by MirzaSikander** [comment]
Here is another log.
[cluster-provision.log](https://github.com/Azure/acs-engine/files/2511741/cluster-provision.log)

**Comment by amrmahdi** [comment]
@jackfrancis does this only affect clusters where nvidia-device plugin is enabled, or any clusters that have gpu pools regardless ? We are facing this issue with acs engine 2.4.2, and was wondering is disabling the nvidia device plugin would help.

**Comment by jackfrancis** [comment]
@amrmahdi Yes. If you're building non-N series clusters and getting that message with an older version of acs-engine, I recommend using the latest released version, which should not have that bug.

**Comment by amrmahdi** [comment]
We are building N series clusters, or adding new N series node pool to existing clusters. To confirm again, if we have N series agent pools but the nvidia device plugin is disabled, we shouldn't encounter this issue ?

**Comment by jackfrancis** [comment]
The drivers installation is (at present) unrelated to the enabling/disabling of the addon daemonset. The most recent version of acs-engine, however, does include add'l resilience to the shell scripts that install the drivers; so I recommend updating to the newest release.

**Comment by amrmahdi** [comment]
Thanks for the clarification.

**Comment by amrmahdi** [comment]
@jackfrancis this error just happened with me with the latest version 0.25.0. Logs attached
[acs0250.txt](https://github.com/Azure/acs-engine/files/2560282/acs0250.txt)

**Comment by amrmahdi** [comment]
Retries does not help, retried for over 5 times and still facing the same issue :(

**Comment by jackfrancis** [comment]
@amrmahdi can you confirm that `/usr/local/nvidia/nvidia-drivers-396.26` doesn't exist on the nodes that failed?

**Comment by amrmahdi** [comment]
It does not, I've verified that.

**Comment by jackfrancis** [comment]
@amrmahdi we don't really test that scenario, although I have no doubts that it works for folks.

Can you test building a new nvidia cluster and confirm that this error doesn't occur?

**Comment by amrmahdi** [comment]
@jackfrancis adding a GPU agent pool worked once for me (with the latest version), but when I tried again it failed with the attached log. It seems that if it fails once it will continue to fail regardless, since the drivers are not available on the machines. I've also tested creating a GPU cluster from scratch once and it worked, not sure if it will keep working if I tried multiple times. From my experience the driver installation is not consistent.

**Comment by jackfrancis** [comment]
Which version of acs-engine are you using?

**Comment by amrmahdi** [comment]
0.25.0

**Comment by jackfrancis** [comment]
Ah! You'll need to do the following in your new `agentPoolProfile`: add the key/val `"distro": "aks-docker-engine"`.

**Comment by jackfrancis** [comment]
☝️ is because the nvidia drivers have a hard requirement on docker-engine, and v0.25.0 deprecated docker-engine in favor of moby for the default "aks" distro.

**Comment by jackfrancis** [comment]
This distro configuration is rationalized for new cluster configurations, the appropriate distro value is chosen if the pool is an N series cluster.

**Comment by amrmahdi** [comment]
Is this something that acs generates for N series pools ?

**Comment by amrmahdi** [comment]
I see, so if I removed the distro entry and made acs-engine generate the distro, it should take care of it for me ?

**Comment by jackfrancis** [comment]
It would only take care of it for you if the distro value were empty (`""`), which it would be for most folks as they don't fiddle with this value. If the value is already `"aks"` from a prior template generation, then acs-engine won't overwrite it (and thus w/ v0.25.0 you won't have a vm that can install nvidia drivers onto).

So you'll want to manually set it to "aks-docker-engine" in this manual "add a node pool to an existing cluster" scenario.

**Comment by jackfrancis** [comment]
Fantastic, thanks for hanging with us. :)

**Comment by Plateria** [comment]
If someone stumbles accross this error you can also follow this documentation from microsoft:
https://docs.microsoft.com/de-de/azure/aks/gpu-cluster
They explain how to use/add GPUs to kubernetes service.
