### ISSUE TITLE
k8s Cluster upgrade fails with Jumpbox

### ISSUE THREAD

**Issue by keyoke** [Azure/acs-engine#4065]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.23.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11.3

**What happened**:
Upgrade to 1.12.1 fails with the following results 

> gareth@vm1:~/acs-engine-v0.23.0-linux-amd64$ ./acs-engine upgrade --deployment-dir _output/gemycluster/ --upgrade-version 1.12.1 --resource-group geacstestcluster
> --location westeurope --subscription-id [SUBID]
> INFO[0000] validating...
> INFO[0041] Name suffix: 77168057
> INFO[0041] Gathering agent pool names...
> INFO[0042] VM k8s-agentpool1-77168057-vmss_0 in VMSS k8s-agentpool1-77168057-vmss has a current tag of Kubernetes:1.11.3 and a desired tag of Kubernetes:1.12.1. Upgrading this node.
>  
> INFO[0042] No tags found for VM: jumpbox1 skipping.
>  
> INFO[0042] Master VM name: k8s-master-77168057-0, orchestrator: Kubernetes:1.11.3 (MasterVMs)
>  
> INFO[0042] Upgrading to Kubernetes version 1.12.1
>  
> INFO[0042] Master nodes StorageProfile: ManagedDisks
> INFO[0042] Prepping master nodes for upgrade...
> INFO[0042] Resource count before running NormalizeResourcesForK8sMasterUpgrade: 15
> INFO[0042] Evaluating if agent pool: <nil>, resource: [parameters('jumpboxVMName')] needs to be removed
> INFO[0042] Removing nic: [variables('jumpboxNetworkInterfaceName')] from template
> INFO[0042] Evaluating if agent pool: master, resource: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))] needs to be removed
> INFO[0042] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(), '/ManagedIdentityExtension')] needs to be removed
> INFO[0042] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', '-master-', copyIndex(variables('masterOffset')))] needs to be removed
> INFO[0042] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/computeAksLinuxBilling')] needs to be removed
> INFO[0042] Resource count after running NormalizeResourcesForK8sMasterUpgrade: 14
> INFO[0042] Total expected master count: 1
> INFO[0042] Master nodes that need to be upgraded: 1
> INFO[0042] Master nodes that have been upgraded: 0
> INFO[0042] Starting upgrade of master nodes...
> INFO[0042] masterNodesInCluster: 1
> INFO[0042] Upgrading Master VM: k8s-master-77168057-0
> INFO[0042] fetching VM: geacstestcluster/k8s-master-77168057-0
> INFO[0042] found nic name for VM (geacstestcluster/k8s-master-77168057-0): k8s-master-77168057-nic-0
> INFO[0042] deleting VM: geacstestcluster/k8s-master-77168057-0
> INFO[0042] waiting for vm deletion: geacstestcluster/k8s-master-77168057-0
> INFO[0138] deleting nic: geacstestcluster/k8s-master-77168057-nic-0
> INFO[0138] waiting for nic deletion: geacstestcluster/k8s-master-77168057-nic-0
> INFO[0138] deleting managed disk: geacstestcluster/k8s-master-77168057-0_OsDisk_1_197d60dad73249e298bfe7633e1131b1
> INFO[0199] fetching roleAssignments: /subscriptions/[SUBID]/resourceGroups/geacstestcluster with principal [PRINCIPALID]
> INFO[0199] deleting role assignment: /subscriptions/7[SUBID]/resourcegroups/geacstestcluster/providers/Microsoft.Authorization/roleAssignments/[ROLEID]
> INFO[0206] Master offset: 0
>  
> INFO[0206] Master pool set count to: 1 temporarily during upgrade...
>  
> INFO[0206] Starting ARM Deployment (master-18-10-17T17.13.30-959811628). This will take some time...
> **INFO[0209] Error creating upgraded master VM: k8s-master-77168057-0
> FATA[0209] Error upgrading cluster: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The resource 'Microsoft.Network/networkInterfaces/jumpbox1-nic' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'."**

**What you expected to happen**: Upgrade should succeed

**How to reproduce it** (as minimally and precisely as possible):
Create cluster definition with:
- Private cluster
- Custom VNET
- Jumpbox
- use managed Identity
deploy cluster and then attempt upgrade with

./acs-engine upgrade --deployment-dir _output/gemycluster/ --upgrade-version 1.12.1 --resource-group geacstestcluster --location westeurope --subscription-id [SUBID]

**Anything else we need to know**: No

**Comment by keyoke** [comment]
If I look at the resulting ARM Template which is generated by the upgrade functionality I see that its missing the jumpbox NIC definition below

 {
      "apiVersion": "[variables('apiVersionDefault')]",
      "dependsOn": [
        "[concat('Microsoft.Network/publicIpAddresses/', variables('jumpboxPublicIpAddressName'))]",
        "[concat('Microsoft.Network/networkSecurityGroups/', variables('jumpboxNetworkSecurityGroupName'))]"
      ],
      "location": "[variables('location')]",
      "name": "[variables('jumpboxNetworkInterfaceName')]",
      "properties": {
        "ipConfigurations": [
          {
            "name": "ipconfig1",
            "properties": {
              "primary": true,
              "privateIPAllocationMethod": "Dynamic",
              "publicIpAddress": {
                "id": "[resourceId('Microsoft.Network/publicIpAddresses', variables('jumpboxPublicIpAddressName'))]"
              },
              "subnet": {
                "id": "[variables('vnetSubnetID')]"
              }
            }
          }
        ],
        "networkSecurityGroup": {
          "id": "[resourceId('Microsoft.Network/networkSecurityGroups', variables('jumpboxNetworkSecurityGroupName'))]"
        }
      },
      "type": "Microsoft.Network/networkInterfaces"


but it does include the Jumpbox Compute resource definition which references the missing NIC and I ssume this is why the validation is failing?
    }

**Comment by keyoke** [comment]
Should the Jumpbox be included or excluded during the upgrade process?

**Comment by CecileRobertMichon** [comment]
@keyoke this sounds like a bug. I believe upgrade removes the NICs for the template for upgrade but does not remove the jumpbox. We might need to remove the jumpbox compute resource as well, or not remove the NIC for the jumpbox. If you want to look into opening a PR for the fix, I can provide guidance as needed.
