### ISSUE TITLE
can't deploy kubernetes 1.12

### ISSUE THREAD

**Issue by YitzchakLF** [Azure/acs-engine#4066]
**Is this a request for help?**:
Yes
---

**What version of acs-engine?**:
v0.23.0
v0.23.1
v0.24.0
---

**What happened**:
Using the above 3 versions of acs-engine, I tried to generate the necessary templates for a cluster with kubernetes version 1.12

**Template used:** 
https://github.com/Azure/acs-engine/blob/master/examples/kubernetes-releases/kubernetes1.12.json (with DNS filled in)

**command used:**
acs-engine  generate  --api-model template2.json

**What you expected to happen**:
Expected to generate the arm templates, kubeconfig, and secrets

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
**Error given**
acs-engine  generate  --api-model template2.json
INFO[0000] Error returned by LoadContainerService: the following OrchestratorProfile configuration is not supported: OrchestratorType: "Kubernetes", OrchestratorRelease: "1.12", OrchestratorVersion: "". Please use one of the following versions: [1.6.6 1.6.9 1.6.11 1.6.12 1.6.13 1.7.0 1.7.1 1.7.2 1.7.4 1.7.5 1.7.7 1.7.9 1.7.10 1.7.12 1.7.13 1.7.14 1.7.15 1.7.16 1.8.0 1.8.1 1.8.2 1.8.4 1.8.6 1.8.7 1.8.8 1.8.9 1.8.10 1.8.11 1.8.12 1.8.13 1.8.14 1.8.15 1.9.0 1.9.1 1.9.2 1.9.3 1.9.4 1.9.5 1.9.6 1.9.7 1.9.8 1.9.9 1.10.0-beta.2 1.10.0-beta.4 1.10.0-rc.1 1.10.0 1.10.1 1.10.2 1.10.3 1.10.4 1.10.5 1.11.0-alpha.1 1.11.0-alpha.2 1.11.0-beta.1 1.11.0-beta.2 1.11.0-rc.1 1.11.0-rc.2 1.11.0-rc.3 1.11.0]
FATA[0000] error loading API model in generateCmd: error parsing the api model: the following OrchestratorProfile configuration is not supported: OrchestratorType: "Kubernetes", OrchestratorRelease: "1.12", OrchestratorVersion: "". Please use one of the following versions: [1.6.6 1.6.9 1.6.11 1.6.12 1.6.13 1.7.0 1.7.1 1.7.2 1.7.4 1.7.5 1.7.7 1.7.9 1.7.10 1.7.12 1.7.13 1.7.14 1.7.15 1.7.16 1.8.0 1.8.1 1.8.2 1.8.4 1.8.6 1.8.7 1.8.8 1.8.9 1.8.10 1.8.11 1.8.12 1.8.13 1.8.14 1.8.15 1.9.0 1.9.1 1.9.2 1.9.3 1.9.4 1.9.5 1.9.6 1.9.7 1.9.8 1.9.9 1.10.0-beta.2 1.10.0-beta.4 1.10.0-rc.1 1.10.0 1.10.1 1.10.2 1.10.3 1.10.4 1.10.5 1.11.0-alpha.1 1.11.0-alpha.2 1.11.0-beta.1 1.11.0-beta.2 1.11.0-rc.1 1.11.0-rc.2 1.11.0-rc.3 1.11.0]

**Comment by CecileRobertMichon** [comment]
@YitzchakLF can you make sure you're using acs-engine version you think you're using? `acs-engine version`

Kubernetes 1.6 is deprecated in all 3 versions you mentioned and the list of available version is reduced to only 2 patches per minor version. I am also unable to repro.

**Comment by MarcPow** [comment]
Agreed - acs-engine 0.23.1 definitely works for me with 1.12.

**Comment by oivindoh** [comment]
Also unable to reproduce using acs-engine 0.24.0

**Comment by YitzchakLF** [comment]
MarcPow,
can yo post your acs-engine template?
Are you using the "deploy" command or "generate"?
