### ISSUE TITLE
keyvault-flexvolume is enabled by default although the documentation states that it is not.

### ISSUE THREAD

**Issue by amrmahdi** [Azure/acs-engine#4071]
**Is this a request for help?**:

No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

0.24

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
keyvault-flexvolume add on is enabled by default , although the [documentation](https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md#addons) says that the default is false.

**What you expected to happen**:
keyvault-flexvolume should not be run by default. 

**How to reproduce it** (as minimally and precisely as possible):

```acs-engine generate examples/kubernetes-releases/kubernetes1.10.json ```
In the generated apimodel.json you will see that the keyvault-flexvolume is enabled.

**Anything else we need to know**:

**Comment by ritazh** [comment]
Thanks for reporting this @amrmahdi! The doc needs to be updated to reflect that it should be enabled by default. Will open a PR to address this.

**Comment by amrmahdi** [comment]
> Thanks for reporting this @amrmahdi! The doc needs to be updated to reflect that it should be enabled by default. Will open a PR to address this.

Thanks! Any side effect from disabling it on a cluster ?

**Comment by ritazh** [comment]
@amrmahdi
> side effect
 
This keyvault flexvolume along with the blobfuse and the smb flexvolmes were added by default to make it easier for users to use them OOTB. But if you don't think you will ever use this feature, then disabling it in the apimodel shouldn't have any side effect. If you need them later, you can always deploy them on your own.
