### ISSUE TITLE
kubernetesDashboard  azuredeploy.parameters are not auto-generated when the template has disabled add-ons

### ISSUE THREAD

**Issue by amrmahdi** [Azure/acs-engine#4080]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
0.24
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
1.10.8

**What happened**:

acs-engine generate does not generate the kubernetesDashboard parameters in the azuredeploy.parameters.json when the acs template has disabled add-on.

**What you expected to happen**:

The kubernetesDashboard parameters are auto-generated and the ```az group deplyment validate``` command generates the template without asking for the kubernetesDashboard parameters.

**How to reproduce it** (as minimally and precisely as possible):
Use the following template 

```json
{
  "apiVersion": "vlabs", 
  "location": "westus2", 
  "properties": {
    "agentPoolProfiles": [
      {
        "availabilityProfile": "VirtualMachineScaleSets", 
        "count": 4, 
        "ipAddressCount": 128, 
        "kubernetesConfig": {
          "controllerManagerConfig": {
            "--terminated-pod-gc-threshold": "50"
          }, 
          "kubeletConfig": {
            "--image-pull-progress-deadline": "30m", 
            "--max-pods": "110"
          }
        }, 
        "name": "agentpool1", 
        "osDiskSizeGB": 0, 
        "storageProfile": "ManagedDisks", 
        "vmSize": "Standard_DS13_v2"
      }
    ], 
    "linuxProfile": {
      "adminUsername": "user", 
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    }, 
    "masterProfile": {
      "count": 1, 
      "dnsPrefix": "disableaddons", 
      "vmSize": "Standard_D3_v2"
    }, 
    "orchestratorProfile": {
      "kubernetesConfig": {
        "addons": [ 
          {
            "enabled": false, 
            "name": "smb-flexvolume"
          }
        ]
      }, 
      "orchestratorType": "Kubernetes", 
      "orchestratorVersion": "1.10.8"
    }, 
    "servicePrincipalProfile": {
      "clientId": "", 
      "secret": ""
    }
  }
}

```
Run

```acs-engine  generate template.json```

You will notice that in the produced azuredeploy.parameters, the kubernetesDashboard parameters are missing. As a result if you try to run

```bash
az group deployment validate --template-file azuredeploy.json --parameters azuredeploy.parameters.json --subscription <....> --resource-group <....> --mode Incremental
```

You will be asked:

```bash
Please provide string value for 'kubernetesDashboardCPULimit' (? for help): 
Please provide string value for 'kubernetesDashboardCPURequests' (? for help): 
Please provide string value for 'kubernetesDashboardMemoryLimit' (? for help): 
Please provide string value for 'kubernetesDashboardMemoryRequests' (? for help): 
Please provide string value for 'kubernetesDashboardSpec' (? for help):
```

**Anything else we need to know**:

UPDATE: I think it is actually isolated to disabling the smb-flexvolume. Simplified the template to remove other addons.

**Comment by tariq1890** [comment]
Thanks for reporting the issue @amrmahdi . We are currently fixing this. #4084

**Comment by amrmahdi** [comment]
@tariq1890 when is it expected to be released ?

**Comment by amrmahdi** [comment]
@tariq1890 I don't see a link to the downloadable binaries.

**Comment by tariq1890** [comment]
@amrmahdi Please check now :)

**Comment by CecileRobertMichon** [comment]
@tariq1890 can this be closed now?

**Comment by tariq1890** [comment]
Yes.
