### ISSUE TITLE
Defaults being set incorrectly

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#410]
We set defaults after we load the json file. This can result in the user specified settings being clobbered.

I think this stems from the fact that the "defaults" were "defaults" from the other side, for the parameters. They were never meant to be "defaults" for values that originated from the apimodel.json.

However, they probably should be one in the same. We should set the defaults, then load from the apimodel...

**Comment by anhowe** [comment]
Defaults are applied to the missing fields only.  It is a bug to overwrite already set values.  Do you have a list of defaults overwritten?

**Comment by colemickens** [comment]
No. But it's not  a hard bug, pretty obvious: https://github.com/Azure/acs-engine/pull/411/files#diff-8edb2653431a5da9ad1f4286097702a7R76

**Comment by anhowe** [comment]
One reason for setting the defaults after reading the json is because we do not know before we load the json which orchestrator we are loading.  Let's post PRs for the defaults that applied to already set fields.
