### ISSUE TITLE
How can I add agent pool to an existing pool?

### ISSUE THREAD

**Issue by omerlh** [Azure/acs-engine#4136]
**Is this a request for help?**:

--- Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

--- Feature Request/Question

**What version of acs-engine?**:

--- 

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.8
**What happened**:
We have a running Kubernetes cluster, and we're experiencing issues with scaling due to Azure allocation limitation. The cluster has one agent pool. We would like to add a new agent pool with a different SKU to see if it will solve the issue.

**What you expected to happen**:
Document how to add agent pool.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy a cluster with one agent pool
2. Try to add a new agent pool

**Anything else we need to know**:

**Comment by omerlh** [comment]
I find #621, I will try and update if I have further questions

**Comment by rocketraman** [comment]
There was a recent discussion about this in Slack, and the general consensus seemed to be this is not supported. I recently ran into the same issue and ended up creating a new cluster and migrating everything to it. With my new cluster, I created multiple pools with different sizes of VMs to allow for flexibility in scaling.

**Comment by omerlh** [comment]
We tried that today, it worked on a fresh new cluster but when we tried it out on our production cluster it destroyed it and the cluster becomes unusable. Writing here as another warning to potential users who might want to try it out :)
