### ISSUE TITLE
Enable AllowVolumeExpansion in default storage classes

### ISSUE THREAD

**Issue by rocketraman** [Azure/acs-engine#4138]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of acs-engine?**: 0.24.2

---

The default Azure storage classes do not set `allowVolumeExpansion` to true, as described at https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims. Is there a reason for this, and if not, can it be enabled for the relevant K8S versions?

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.12.1

**Comment by andyzhangx** [comment]
It depends on k8s version, from k8s v1.11.0, azure file & disk supports `allowVolumeExpansion`. So it's v1.10.0, it will get failure if using `allowVolumeExpansion` in azure disk storage class.

**Comment by rocketraman** [comment]
> It depends on k8s version, from k8s v1.11.0, azure file & disk supports allowVolumeExpansion. 

Yes, so my expectation would be that acsengine would definite the storage class with or without that flag, depending on the k8s version.
