### ISSUE TITLE
The dashboard add-on should be of type ClusterIP and not NodePort

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#414]
The file `acs-engine/parts/kubernetesmasteraddons-kubernetes-dashboard-service.yaml` specifies type: NodePort and not type: ClusterIP.  The dashboard is not exposed publically, so exposing on NodePort is not needed.

**Comment by colemickens** [comment]
This is done because upstream does it: https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml

**Comment by colemickens** [comment]
https://github.com/kubernetes/dashboard/issues/1744

**Comment by anhowe** [comment]
thanks, we can close based on the precedent set by upstream
