### ISSUE TITLE
Enable firewall protection on KMS KeyVault

### ISSUE THREAD

**Issue by omerlh** [Azure/acs-engine#4152]
**Is this a request for help?**: No
 
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature Request

---

**What version of acs-engine?**:
```
Version: v0.24.3
GitCommit: ad007b644
GitTreeState: clean
```
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11

**What happened**:
I deployed a new cluster and specific in the API model `"enableEncryptionWithExternalKms": true`. KeyVault created as expected, but without firewall rules.

**What you expected to happen**:
Allow creating (or create by default) a rule that allows access only from the cluster VNet, maybe limit only to the master subnet.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a cluster with `"enableEncryptionWithExternalKms": true`.

**Anything else we need to know**:

**Comment by omerlh** [comment]
Also, is the key created on KeyVault can be of type HSM?

**Comment by ritazh** [comment]
@omerlh thanks for the feedback.

> Allow creating (or create by default) a rule that allows access only from the cluster VNet, maybe limit only to the master subnet.

This makes sense. I will add this as a default to acs-engine.

> is the key created on KeyVault can be of type HSM?

Currently we only support creation of a standard sku key vault for this feature. To create HSM-protected keys, you will need to use the Premium service tier: https://docs.microsoft.com/en-us/azure/key-vault/key-vault-get-started#HSM 

I will create an issue to track this issue on https://github.com/Azure/kubernetes-kms

**Comment by omerlh** [comment]
Thanks :) Should I as a customer should worry about key rolling? What do you recommend?

**Comment by ritazh** [comment]
@omerlh 
From https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers
[KMS is]
> The recommended choice for using a third party tool for key management. Simplifies key rotation, with a new DEK generated for each encryption, and KEK rotation controlled by the user. 

From https://github.com/Azure/kubernetes-kms
> Currently KMS plugin for Kubernetes does not support KMS KEK rotation scenarios. This means if you choose to create a new key version in KMS, the cluster will fail to decrypt as it won't match the KEK used for encryption at the time the cluster was created. 

You can also follow this issue: https://github.com/Azure/kubernetes-kms/issues/8

**Comment by omerlh** [comment]
Thank you!
