### ISSUE TITLE
Validate pre-pulled image effects on VHD-backed clusters.

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#4160]
We are pre-pulling k8s component images (e.g., kube-proxy), let's validate that when we bring up the k8s runtime that those pre-pulled images aren't being re-downloaded by k8s.

**Comment by CecileRobertMichon** [comment]
On a VM built from VHD image:

**Comment by CecileRobertMichon** [comment]
Related fixes #4174 #4195 #4194 #4201 #4212
