### ISSUE TITLE
Rationalize fault domains implementation for managed disk

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#4161]

**Comment by jackfrancis** [comment]
@mboersma can we summarize this work as:

- ensure that if a region supports 3 FDs that we implement managed disk w/ 3 FDs?

@seanmck FYI

**Comment by mboersma** [comment]
@jackfrancis that's most of it, but another driver for this change was that users can't create acs-engine clusters in canary regions at all, since they support only 1 FD and we're currently hard-coded at 2.

**Comment by khenidak** [comment]
@jackfrancis exactly what are you looking for? spreading the VMS over 3+ FDs?
