### ISSUE TITLE
does acs-engine support azure stack in adfs scenario?

### ISSUE THREAD

**Issue by DanielWangZhanggui** [Azure/acs-engine#4179]
**Is this a request for help?**:
- yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
- issue
---

**What version of acs-engine?**:
- 0.21.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
- kubernetes

**What happened**:
- Seems like acs-engine just supports aad service principle,  in adfs scenario, service principle doesn't provide "secret" instead providing certificates. 

**What you expected to happen**:
- Support configuration options for adfs in acs-engine

**How to reproduce it** (as minimally and precisely as possible):
- azure stack 
- adfs

**Anything else we need to know**:

**Comment by andyzhangx** [comment]
Cert is supported in upstream kubernetes. To use it, aadClientCertPath and aadClientCertPassword should be set in cloud provider config. (See https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-provider-config.md#auth-config).

But it is not supported yet in acs-engine. @jackfrancis  Do you have plans to support this?

**Comment by jackfrancis** [comment]
@andyzhangx No plans. @khenidak Is this on our near-term feature roadmap?
