### ISSUE TITLE
Update ACS Engine to use Kubernetes 1.11 client

### ISSUE THREAD

**Issue by amanohar** [Azure/acs-engine#4186]
**Is this a request for help?**: 
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): 
Feature request
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What you expected to happen**:
Update ACS Engine to use Kubernetes 1.11 client

**Comment by tariq1890** [comment]
acs-engine will support api interactions with k8s 1.11. This has been fulfilled with the introduction of this PR, https://github.com/Azure/acs-engine/pull/4157 .

The support matrix can be seen here https://github.com/kubernetes/client-go/
