### ISSUE TITLE
Question: Revoke/Rotate Kubernetes Certificates

### ISSUE THREAD

**Issue by ashishkulk** [Azure/acs-engine#4192]
Hi all,
I was wondering if anyone can guide me to documentation/steps on how to rotate/revoke kubernetes certificates?
Lets say a team member who created the acs-engine cluster leaves company. He/She would have had previously access to the certs below. How do I rotate them?

```
"ca.crt", "ca.key", "apiserver.crt", "apiserver.key", "client.crt", "client.key", "etcdclient.key", "etcdclient.crt", "etcdserver.crt", "etcdserver.key", "etcdpeer0.crt", "etcdpeer0.key", "kubectlClient.crt", "kubectlClient.key"
```

**Comment by jackfrancis** [comment]
Hi @ashishkulk, we don't have a feature that could do this without downtime. How much operational downtime are you able to tolerate?

**Comment by ashishkulk** [comment]
@jackfrancis  Thanks for getting back to me. We can tolerate downtime of couple of hours if customers are notified beforehand.

We plan to do a Maintenance window and rebuild the whole cluster ground up and restore the pv using heptio ark. Is there a better/recommended way? 

I tried to do `openssl revoke certificate` without success.

**Comment by jackfrancis** [comment]
Creating a new cluster and migrating over workloads is definitely the preferred way to do this work. I recommend lots of process testing in a staging environment, but it will be safer than spending time trying to wrench a pre-existing cluster into the desired state given the changes you want to perform.

**Comment by ashishkulk** [comment]
@jackfrancis Ah. Thanks for your recommendation. Appreciate it  :)

Out of curiousity, what would be the manual way. I was playing around on staging environment. I did `openssl revoke certificate` but it did not work.

**Comment by jackfrancis** [comment]
I've never done it manually, so I don't have steps for you, unfortunately. :)
