### ISSUE TITLE
K8S Default Template does not work upon start

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/acs-engine#420]
### Issue Details

I am following the instructions here:
https://github.com/Azure/azure-quickstart-templates/tree/master/101-acs-kubernetes

### Repro steps (*if necessary, delete otherwise*)
1. Go to https://github.com/Azure/azure-quickstart-templates/tree/master/101-acs-kubernetes
1. Click "Deploy to Azure"
1. Select A0 for Agent VM Size
1. Default for everything else.
1. Once the service is started, ssh to the master
1. Run `kubectl version`
1. Get the following error: (even after waiting 15 minutes, still same problem)

`azureuser@k8s-master-C2172990-0:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 13.65.149.62:443: i/o timeout`

Looking at the logs
`sudo journalctl -f -n 100 -u kubelet`

`Mar 21 17:33:00 k8s-master-C2172990-0 docker[5514]: I0321 17:33:00.998473    5935 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 21 17:33:00 k8s-master-C2172990-0 docker[5514]: I0321 17:33:00.998493    5935 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Mar 21 17:33:01 k8s-master-C2172990-0 docker[5514]: E0321 17:33:01.016314    5935 eviction_manager.go:202] eviction manager: unexpected err: failed GetNode: node 'k8s-master-c2172990-0' not found
Mar 21 17:33:01 k8s-master-C2172990-0 docker[5514]: E0321 17:33:01.109211    5935 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://10.240.255.5:443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8s-master-c2172990-0&resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused
Mar 21 17:33:01 k8s-master-C2172990-0 docker[5514]: E0321 17:33:01.109378    5935 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://10.240.255.5:443/api/v1/services?resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused
Mar 21 17:33:01 k8s-master-C2172990-0 docker[5514]: E0321 17:33:01.110317    5935 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://10.240.255.5:443/api/v1/nodes?fieldSelector=metadata.name%3Dk8s-master-c2172990-0&resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused`

**Comment by colemickens** [comment]
Please follow the troubleshooting steps here. The logs you've posted are not relevant.

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md#troubleshooting

**Comment by lastcoolnameleft** [comment]
After looking at the troubleshooting guide, it does appear that the Service Principal is not setup correctly.  That now leads to two questions:
1. The troubleshooting document states that there is a problem, but doesn't provide guidance on how/where to fix.
1. I'm using the default k8s template from the Azure quick start templates with no deviation.  If the public templates are failing, there might be a bigger issue.

**Comment by JackQuincy** [comment]
I will make a PR to add the link. But please see our documentation on how to create the service principal
https://github.com/Azure/acs-engine/blob/master/docs/serviceprincipal.md 
please note It needs to have at least Contributor privileges and the resource group for the cluster should be in the scope of the service principal.

**Comment by JackQuincy** [comment]
https://github.com/Azure/acs-engine/pull/436

**Comment by colemickens** [comment]
There is nothing wrong with the template. Your SP creds were bad and @JackQuincy  has fixed the documentation gap.

Closing this.

**Comment by lastcoolnameleft** [comment]
FYI, I believe this issue was related to the AAD outage happening on the same day.  I used the quick-start template, so the credentials should have been taken care of from that.

**Comment by colemickens** [comment]
@lastcoolnameleft The quickstart template still needs a service principal: (from your link above) https://github.com/Azure/azure-quickstart-templates/blob/master/101-acs-kubernetes/azuredeploy.parameters.json#L26
