### ISSUE TITLE
Usage Guide

### ISSUE THREAD

**Issue by daniel-rhoades** [Azure/acs-engine#421]
I've written up a detailed guide on how to set this up with Terraform, which might be useful:

* [daniel-rhoades/acs-engine-terraform](https://github.com/daniel-rhoades/acs-engine-terraform);
* [danielrhoades.com detailed article](http://danielrhoades.com/2017/03/20/docker-azure-terra/).

I still want to enhance it a bit, but it's still complete right now.

Feel free to reference it if you think it's useful.

**Comment by anhowe** [comment]
Thanks Daniel for the link to your detailed guide.  This is really cool.  Your github account is quite discoverable by customers, so we will close this for now.  If you wanted this referenced, this may be a good candidate to reference under https://github.com/Azure/acs-demos.
