### ISSUE TITLE
Kube-DNS Failing in some Node Pools

### ISSUE THREAD

**Issue by dhselman** [Azure/acs-engine#4234]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.24.3
---

Kube-DNS is failing to resolve in two out of five node pools in the ACS-Engine 1.10.0 k8s cluster. The DNS failures began after upgrading to 1.10.0 from 1.9.6. In three of the node pools, there are no issues with dns resolution, however there are consistent failures in two of the node pools. 

There are many related issues in the Kubernetes repo regarding DNS timeouts/latency, however several fixes have failed to resolve the time out. This includes applying the 4.15.0-1030-azure kernel patch as well as configuring the single-request-reopen configuration in resolv.conf for the pods. 

We have confirmed that the kernel patch did not resolve the issue in both busybox and CoreOS containers in this instance. 

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10.0

**What happened**:
Attempting to ping external sites (e.g. bing.com) from inside a pod in the affected node pools result in a long wait (~5-10 seconds) or a timeout altogether intermittently. Curl consistently times out across the pods in the affected node pools. 

**What you expected to happen**:
DNS to resolve in a timely manner for pods across all node pools// a consistent behavior for DNS across all node pools. 

**How to reproduce it** (as minimally and precisely as possible):
Create an ACS-Engine 1.9.6 cluster with five node pools, upgrade it to ACS-Engine 1.10.0, and test resolution to external domains across all node pools. 

**Anything else we need to know**:
Kube-DNS is deployed with 2 replicas, both on the affected node pools (one on the first affected node pool, the other on the second affected node pool).

**Comment by khenidak** [comment]
In order for us to understand. I will name failing pools `f1` an `f2`. Can you confirm 
1. Pods on `f1` and `f2` fail to resolve DNS via `kube-dns`? Do they fail with `default` policy as well? https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/?
2. Pods anywhere fail to resolve dns via `kube-dns`? Do they work with `default` policy as well? https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

@jackfrancis

**Comment by dhselman** [comment]
1. Pods on f1 and f2 succeed in resolving external addresses when set to default policy. However, when using the default policy, we are unable to access internal k8s services.
2. Pods in non failing pools when set to default dnsPolicy also succeed (as with ClusterFirst setting)
