### ISSUE TITLE
Moby ipv6 support 

### ISSUE THREAD

**Issue by amrmahdi** [Azure/acs-engine#4241]
**Is this a request for help?**:

Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

0.25.2

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.10.8

**What happened**:

Moby container runtime does not seem to have ipv6 support. When upgrading acs-engine from 0.24.2 to 0.25.2 we noticed that container on the new pods does not have ipv6 support. Looking at the change log, it seems related to moby runtime change ? 

**What you expected to happen**:

Containers have ipv6 support.

**Comment by amrmahdi** [comment]
@jackfrancis ideas ?

**Comment by jackfrancis** [comment]
@cpuguy83 @khenidak Does this ring a bell?

@amrmahdi in the meantime, you may still use docker-engine on new clusters in v0.25.2 by specifying the "aks-docker-engine" distro thusly:

(In all of your master and/or agent pools that need docker-engine)

```
    "masterProfile": {
      <etc...>
      "distro": "aks-docker-engine",
      <etc...>
```

```
},
    "agentPoolProfiles": [
      {
        <etc...>
        "distro": "aks-docker-engine",
        <etc...>
```

**Comment by cpuguy83** [comment]
Probably related to https://github.com/moby/moby/issues/33099

I think if you run docker with --ipv6=true it will enable ipv6 in the container.

**Comment by jackfrancis** [comment]
Any reason not to add `--ipv6=true` to our bootstrap implementation for all clusters?

@amrmahdi Please let us know if that option unblocks your ipv6 workloads on moby-backed clusters, thanks!

**Comment by amrmahdi** [comment]
I’ve already tried modifing  /etc/docker/daemon.json on individual nodes to add  ‘’’"ipv6": true’’’ but it didn’t help.

**Comment by cpuguy83** [comment]
Oh that makes sense, I guess this flag is specifically for docker networks created with `docker network` and not anything to do with the default networking that k8s uses... will do some more digging  to see how others have solved this.
The issue is that docker does not disable the `disable_ipv6` the option in the container (`/proc/sys/net/ipv6/conf/default/disable_ipv6`)

**Comment by cpuguy83** [comment]
What version of CNI are we using?

https://github.com/containernetworking/cni/issues/531#issuecomment-367343292

> CNI Plugins v0.7.0 includes the [disable_ipv6 sysctl workaround](
https://github.com/containernetworking/plugins/pull/113) so hopefully Kubernetes IPv6 will be easier to get up and running now on newer Docker releases. Thanks for the swift response from the CNI maintainers!

**Comment by jackfrancis** [comment]
@cpuguy83 we're using `v0.7.1`

**Comment by amrmahdi** [comment]
@jackfrancis setting 'aks-docker-engine' resolved the ipv6 issue. But adding a new agent pool on this distro not does not work :(

```json
Deployment failed. Correlation ID: 0158fb67-4811-46cd-8b47-b58e07fb738a. {
   "error": {
     "code": "PropertyChangeNotAllowed",
     "message": "Changing property 'customData' is not allowed.",
     "target": "customData"
   }
}
``` 

Any workarounds for this one ?

**Comment by jackfrancis** [comment]
Can you paste your process for adding an agent pool?

**Comment by amrmahdi** [comment]
1. Get the original apimodel.son generated by acs-engine.
2. Copy agentPoolProfiles[0] into the end of the array.
3. Update ```name```, ```vmSize```, ```count``` of the new pool appropriately to the new values.
4. Set distro of the new pool to 'aks-docker-engine'
5. Run acs-engine generate
6. Deploy the new generated template with incremental mode. 

P.S. We also update ```ipAddressCount``` for all pools to match the original since acs-engine strips it out in the generated apimodel.json (possibly a bug)

**Comment by jackfrancis** [comment]
Is the distro of the original pool (step 1) "aks-docker-engine"?

**Comment by amrmahdi** [comment]
Yes.

**Comment by jackfrancis** [comment]
Then step 4 is "verify" not "set", right?

As this is not core-acs-engine functionality, we don't have any tests that validate that it works, just wanna make sure I understand what's not working.

**Comment by amrmahdi** [comment]
Well it does not matter in this case since we have made everything to use 'aks-docker-engine' to resolve this issue, and the other GPU issue we reported few days ago.

**Comment by jackfrancis** [comment]
So I suppose we can conclude (for reasons unknown) that for non-moby scenarios, manually editing the agent pool member array after cluster creation is broken.

**Comment by amrmahdi** [comment]
Yes it is. I'd say it is on the 'aks-docker-engine' distro. It could be related to the recent image version updates ?
