### ISSUE TITLE
Cannot deploy k8s Cluster with ACS Engine in Azure North Central Region

### ISSUE THREAD

**Issue by mobeus1** [Azure/acs-engine#4242]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: acs-engine: 0.20.7

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** - Kubernetes v 1.10.6

**What happened**: Cannot deploy cluster using ACS Engine

**What you expected to happen**: ACS Engine should build cluster as usual but getting an error only in Azure North Central Region.

**How to reproduce it** (as minimally and precisely as possible): Try to build another cluster happens every time now

**Anything else we need to know**: more details below

I tried this failed deployment in West US and it runs without a problem.
 

 
I am constantly getting the following error for consecutive ACS deployments. I am using the same ACS template every time. It sometimes works but fails mostly. The same works in West US without a glitch. I have attached the obfuscated ACS template for reference.

 
Deployment failed. Correlation ID: ae54b098-72a0-4b0f-9c96-4e59f62608b8. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse-master-1'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=15\n[stdout]\n\n[stderr]\n\"."
      }
    ]
  }
}

 

Referring to https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesprovisionsource.sh, this seems to be related to ETCD but not sure why it failed. The last few lines in /var/log/azure/cluster-provision.log on the Master node has this:

 
+ '[' 9 -eq 10 ']'
+ sleep 1
+ for i in '$(seq 1 $retries)'
+ timeout 5 sudo etcdctl member update c63bd84e308e9829 https://10.217.84.25:2380
+ '[' 124 -eq 0 ']'
+ '[' 10 -eq 10 ']'
+ echo Executed '"sudo' etcdctl member update c63bd84e308e9829 'https://10.217.84.25:2380"' 10 times
Executed "sudo etcdctl member update c63bd84e308e9829 https://10.217.84.25:2380" 10 times
+ return 1
+ exit 15

 
Environment Details:

acs-engine: 0.20.7
K8s: 1.10.6
Region: North Central US
Custom DNS: Yes
NSG: Nil
Network Policy: Calico

Regards
Jayanth

**Comment by CecileRobertMichon** [comment]
@mobeus1 I believe there was an Azure incident going on in north central US yesterday which is now resolved, have tried deploying today?

**Comment by mobeus1** [comment]
Cecile,

We have tried several times in the past. can you elaborate what the issue was in North Central ?? 

Gus

**Comment by CecileRobertMichon** [comment]
I was referring to an issue with Azure storage on Monday. I thought it might be related since it seemed odd that you were having issues in that specific region but if this has happened in the past it is most likely not related. I just tried and I was able to deploy a cluster in north central us just fine. Is there anything different you're doing in that region with custom DNS or custom VNET? Could you try to ssh into a failed master and run the command that failed in the logs? `sudo etcdctl member update c63bd84e308e9829 https://10.217.84.25:2380` in the case you pasted above. Also please check that etcd is running `systemctl status etcd` and see if you see anything suspicious in etcd logs `sudo journalctl -u etcd`.

**Comment by mobeus1** [comment]
We area able to deploy now but getting nodes in "not ready" state and have created a ticket with MS Premier Support .. Also found this on the ACS site so this may be our problem... 

Known Issues

Node "NotReady" due to lost TCP connection

Nodes might appear in the "NotReady" state for approx. 15 minutes if master stops receiving updates from agents. This is a known upstream kubernetes issue #41916. This fixing PR is currently under review.

ACS-Engine partially mitigates this issue on Linux by detecting dead TCP connections more quickly via net.ipv4.tcp_retries2=8.
