### ISSUE TITLE
container localhost networking issues on moby 

### ISSUE THREAD

**Issue by amrmahdi** [Azure/acs-engine#4243]
**Is this a request for help?**:

No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

0.25.2

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

1.10.8

**What happened**:

Containers running on the same pod are not able to communicate using "localhost".  It seems like the network namespace is not shared between the containers.

Quoting [kubernetes docs](https://kubernetes.io/docs/concepts/cluster-administration/networking/#kubernetes-model)

> _In reality, Kubernetes applies IP addresses at the Pod scope - containers within a Pod share their network namespaces - including their IP address. This means that containers within a Pod can all reach each other’s ports on localhost. This does imply that containers within a Pod must coordinate port usage, but this is no different than processes in a VM. This is called the “IP-per-pod” model. This is implemented, using Docker, as a “pod container” which holds the network namespace open while “app containers” (the things the user specified) join that namespace with Docker’s --net=container:<id> function._

**What you expected to happen**:

A container can establish a tcp connection to another container within the same pod.

**How to reproduce it** (as minimally and precisely as possible):

1.Setup a pod with 2 containers
2. Set-up container A to listen on 0.0.0.0:40041
3. On container B ```telnet localhost:40041``` 

Expected: ```Connected to localhost.```
Current behavior: 
```bash
telnet localhost 40041
Trying 127.0.0.1...
command terminated with exit code 137
```

**Anything else we need to know**:

**Comment by amrmahdi** [comment]
@jackfrancis another issue related to moby.

**Comment by jackfrancis** [comment]
@cpuguy83 does this look familiar?

**Comment by amrmahdi** [comment]
I've updated the original issue with the correct output of the telnet command
```bash
telnet localhost 40041
Trying 127.0.0.1...
command terminated with exit code 137
```
The command just hangs until the pod is restarted. 

@cpuguy83 

```bash 
nslookup localhost
Server:		10.0.0.10
Address:	10.0.0.10#53

Name:	localhost
Address: 127.0.0.1
```

**Comment by cpuguy83** [comment]
Are you certain the other container is up and running?

What happens if you drop to just using the docker cli directly and `docker run --net=container:<id>`?

**Comment by amrmahdi** [comment]
@cpuguy83 The container is up and running. I've tried running 2 netcat container (server/client) using the ```--net``` option they can can connect.

**Comment by technicianted** [comment]
@amrmahdi can you do a `netstat -atn` on both containers (server and client)? This will be a clear indication of socket state and network ns sharing.

**Comment by amrmahdi** [comment]
@technicianted @cpuguy83 
### Server side netstat:

```
# netstat -atnp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:40041           0.0.0.0:*               LISTEN      10/MediaTransformSe
```

### Client side netstat:
```
# netstat -atnp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:40041           0.0.0.0:*               LISTEN      -
```

So the namespace is actually properly shared between the pods containers.

But localhost networking is not working even on the server. 

### telnet on server using localhost times out.

### telnet on server using the pod ip:
```
# telnet 10.240.0.103 40041
Trying 10.240.0.103...
Connected to 10.240.0.103.
```
