### ISSUE TITLE
Allow custom data injection for master and agent VMs

### ISSUE THREAD

**Issue by sepiroth887** [Azure/acs-engine#427]
We do have a few requirements in addition to vanilla DC/OS (mostly around CA injection and some management tooling) that we would like to automate into the provisioning cycle. 

I have seen the /parts folder having the dcoscustomdata{n}.t files which I think could be a great point to inject things. 

Is there any plan to make this available via acs-engine and template-ise this further? 

If so, here would be my suggestion: 

- add {{ .customRunCommand }} into the runcmd section 
- add {{ .customFiles }} into the write_files section
- add a -customRunCommand and -customFiles arg to acs-engine expecting correctly formatted files 
- merge the files together on generation
- profit

Thoughts? I need this soon so might be able to get a PR going for this

**Comment by anhowe** [comment]
https://github.com/Azure/acs-engine/pull/415 is attempting to solve this.  Can this work?

**Comment by sepiroth887** [comment]
This is pretty close 👍  

However I'm a bit worried about reboots since from my understanding extensions are on-shot executions that will not be run after the ARM template was deployed. Hence any type of persistent scripts would need to ensure they are done in a way to survive a reboot. 

Possible to work around and maybe even a better model since any customData has a risk of breaking the deploy due to bad formatting or syntax, whereas the extension approach would still leave you with a working ACS cluster.... hmm 

Need to dig into that a bit and test it. I get back to you :)

**Comment by colemickens** [comment]
customData/cloud-init does not reexecute either though...

**Comment by sepiroth887** [comment]
oh. I only used cloud-config via CoreOS where that's actually the case. 

Well in that case extensions are the way to handle this. Thank you! 🥇
