### ISSUE TITLE
Creating a cluster with singlePlacementGroup set to false

### ISSUE THREAD

**Issue by vijaygos** [Azure/acs-engine#4303]
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

0.24.2

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.10.8

**What happened**:
Trying to create a cluster with the following agentPoolProfile gives me an error
**FATA[0000] error loading API model in generateCmd: error parsing the api model: AgentPoolProfile count needs to be in the range [1,100]** 

"agentPoolProfiles": [
      {
        "OSDiskSizeGB": 128, 
        "availabilityProfile": "VirtualMachineScaleSets", 
        **"count": 101,** 
        "ipAddressCount": 128, 
        "kubernetesConfig": {
          "controllerManagerConfig": {
            "--terminated-pod-gc-threshold": "50"
          }, 
          "kubeletConfig": {
            "--image-pull-progress-deadline": "30m", 
            "--max-pods": "110"
          }
        }, 
        "name": "agentpool1", 
        **"singlePlacementGroup": false,** 
        "storageProfile": "ManagedDisks", 
        "vmSize": "Standard_DS13_v2"
      }
    ], 

**What you expected to happen**:
With singlePlacementGroup set to false, I would expect to be able to **create a cluster with a node count of 101**

**Comment by tariq1890** [comment]
This is a bug that we need to fix . Thanks for reporting this @vijaygos
