### ISSUE TITLE
Missing kubletwin/pause image on Windows Server 2019 deployments

### ISSUE THREAD

**Issue by bclau** [Azure/acs-engine#4310]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: v0.26.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes v1.13.0-alpha.2

**What happened**:

After deploying a Kubernetes cluster, pods cannot be spawned on the Windows Server 2019 nodes because they do not have the ``kubletwin/pause`` image.

Creating the image manually solves the issue.

**What you expected to happen**:

The ``kubletwin/pause`` image should be present on the compute nodes, and the pods should be able to run on the Windows nodes.

**How to reproduce it** (as minimally and precisely as possible):

Deploy a Kubernetes Cluster with Windows Server 2019 nodes, and try to create a pod on one of the Windows compute nodes. Observe that the pod fails to enter a ``Running`` state.

**Anything else we need to know**:

**Comment by AIEg0r0v** [comment]
We experience the same issue with Kubernetes v1.12.2 and Windows Server 2019 nodes created bu acs-engine v0.26.2
