### ISSUE TITLE
Load Balancers for a Multi Placement Group Agent Pool Profile cannot be associated with any backend pool.

### ISSUE THREAD

**Issue by vijaygos** [Azure/acs-engine#4318]
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

0.24.2

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.10.8

**What happened**:

Frontend deployments to a cluster with multi placement groups are not reachable because the Load Balancer is not associated with any backend node pools when created. The load balancer is however associated with a Public IP for the service.

Trying to manually associate a vmss to the backend nodepool of the load balancer also errors out.

**What you expected to happen**:

Frontend deployments for multi placement groups should create a STANDARD load balancer and associate all nodes with the load balancer with a Virtual Network.

**How to reproduce it** (as minimally and precisely as possible):

1. Create a cluster with the following agent pool profile and deploy a frontend service with an external Load Balancer

"agentPoolProfiles": [
{
"OSDiskSizeGB": 128,
"availabilityProfile": "VirtualMachineScaleSets",
"count": 101,
"ipAddressCount": 128,
"kubernetesConfig": {
"controllerManagerConfig": {
"--terminated-pod-gc-threshold": "50"
},
"kubeletConfig": {
"--image-pull-progress-deadline": "30m",
"--max-pods": "110"
}
},
"name": "agentpool1",
"singlePlacementGroup": false,
"storageProfile": "ManagedDisks",
"vmSize": "Standard_DS13_v2"
}
],

**Comment by tariq1890** [comment]
@vijaygos We haven't documented the k8s 1.11 as a pre-req for Azure Standard LB and I apologize for that.

So yes, you do need to deploy a k8s 1.11.x for Azure Standard LBs
