### ISSUE TITLE
Add the option to add a public IP to a node

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/acs-engine#4321]
Add the option to add a public IP to a node (including VMSS).

**Comment by CecileRobertMichon** [comment]
closing, duplicate of #3413

**Comment by javierprovecho** [comment]
@CecileRobertMichon should this issue be mirrored to https://github.com/Azure/aks-engine ?

**Comment by CecileRobertMichon** [comment]
@javierprovecho just transferred #3413 to aks-engine.
