### ISSUE TITLE
apiVersionLinkDefault still shows in some examples

### ISSUE THREAD

**Issue by davidmatson** [Azure/acs-engine#4326]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.26.0
---

**Anything else we need to know**:

In #3909, apiVersionLinkDefault was removed. (I had an extension that used it and wasn't sure what to use as the replacement; I eventually figured it out by searching code history for this parameter.)

While I was searching, I found a few files that still use this now-removed parameter:
https://github.com/Azure/acs-engine/search?q=apiversionlinkdefault&unscoped_q=apiversionlinkdefault

Probably worth minor cleanup here.

**Comment by CecileRobertMichon** [comment]
these are all DCOS template extensions and are self-sufficient (the apiVersionLinkDefault var is defined in the extension template) and were left on purpose to avoid touching DCOS code paths.
