### ISSUE TITLE
Kubernetes : Add setting to set pod cidr "--cluster-cidr "

### ISSUE THREAD

**Issue by ivanthelad** [Azure/acs-engine#434]
The cluster-cidr is currently not configurable. Iin the event a conflict exists on the network it would be a good idea to allow this pod network setting to be configurable

**Comment by colemickens** [comment]
https://github.com/Azure/acs-engine/pull/191

**Comment by colemickens** [comment]
I guess we can leave this open until the PR is finished/merged.
