### ISSUE TITLE
Day 2 operations increasing max pods, upgrading k8s version

### ISSUE THREAD

**Issue by sylus** [Azure/acs-engine#4340]
**Is this a request for help?**: Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

**What version of acs-engine?**: v0.24.2

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes v1.12.2

**What happened**: There is no clear instructions on how to change an existing cluster and increase the max pods definition or even upgrade the Kubernetes version. 

Can we have clear docs stating whether is possible and how-to:

- [ ] Adjust max-pods
- [ ] Increment Kubernetes version

WRT to max-pods As quoted by @jackfrancis 

> "As of now, as folks have painfully discovered, the safest thing is to consider that that particular configuration is not “changeable” after cluster creation time. Ymmv, of course, as there are many different configurations your cluster could be built with. If you don’t mind spending R&D cycles, you could replay the cluster creation scenario that produced your current 30 pod cluster (same acs-engine version and api model you used originally), and then monkey around with various upgrade scenarios on that test cluster.
> 
> I think the tl;dr that folks have discovered is that changing the apimodel.json and upgrading clusters will superficially update the control plane configuration w/ the new `--max-pods` setting, but the required Azure IaaS scaffolding won’t be in place.
> 

**What you expected to happen**: Ability for the end user to increase max pods and / or increment the kubernetes version.

**How to reproduce it** (as minimally and precisely as possible): N/A

**Anything else we need to know**: N/A

**Comment by sylus** [comment]
I was wondering if it would be acceptable and okay to just simply add a new pool to my existing cluster and deploy my acs-engine apimodel with:

```sh
az group deployment create --name "k8s-ndm" \                                                                                                                            
                           --resource-group "k8s-ndm" \
                           --template-file "./_output/k8s-ndm/azuredeploy.json" \
                           --parameters "./_output/k8s-ndm/azuredeploy.parameters.json"
```

**Comment by CecileRobertMichon** [comment]
@sylus we have the `acs-engine upgrade` command for incrementing k8s version. See  https://github.com/Azure/acs-engine/blob/master/examples/k8s-upgrade/README.md. For changing something in the configuration such as max-pods we don't yet have an officially supported way to do that, but that's definitely something we'd like to have in the future (see https://github.com/Azure/acs-engine/issues/4170)
