### ISSUE TITLE
CustomScript "exit status=98"- ERR_APT_DAILY_TIMEOUT

### ISSUE THREAD

**Issue by axelgMS** [Azure/acs-engine#4343]
**Is this a request for help?**:

--- YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

--- ISSUE

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

k8S

**What happened**:

Error with CustomScriptExtension on the Agents:

time=2018-11-29T13:19:29Z version=v2.0.6/git@1008306-clean operation=enable seq=0 event="created output directory"
time=2018-11-29T13:19:29Z version=v2.0.6/git@1008306-clean operation=enable seq=0 files=0
time=2018-11-29T13:19:29Z version=v2.0.6/git@1008306-clean operation=enable seq=0 event="executing command" output=/var/lib/waagent/custom-script/download/0
time=2018-11-29T13:19:29Z version=v2.0.6/git@1008306-clean operation=enable seq=0 event="executing protected commandToExecute" output=/var/lib/waagent/custom-script/download/0
time=2018-11-29T13:49:37Z version=v2.0.6/git@1008306-clean operation=enable seq=0 event="failed to execute command" error="command terminated with exit status=98" output=/var/lib/waagent/custom-script/download/0
time=2018-11-29T13:49:37Z version=v2.0.6/git@1008306-clean operation=enable seq=0 event="enable failed"
time=2018-11-29T13:49:37Z version=v2.0.6/git@1008306-clean operation=enable seq=0 event="failed to handle" error="failed to execute command: command terminated with **exit status=98"**

and

Cluster provision logs:
+ for i in '$(seq 1 $retries)'
+ timeout 60 /usr/lib/apt/apt.systemd.daily
+ '[' 124 -eq 0 ']'
+ '[' 20 -eq 20 ']'
+ echo Executed '"/usr/lib/apt/apt.systemd.daily"' 20 times
Executed "/usr/lib/apt/apt.systemd.daily" 20 times
+ return 1
**+ exit 98**

the error code 98 is ERR_APT_DAILY_TIMEOUT=98 # Timeout waiting for apt daily updates (cf https://github.com/Azure/acs-engine/blob/8840e3d6978a0fbb8f0fbdebcc24b96f87a9600e/parts/k8s/kubernetesprovisionsource.sh)

**What you expected to happen**:

no error from CustomScriptExtension on the Agents.
Manually running **sudo /usr/lib/apt/apt.systemd.daily** is ok

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@axelgMS which version of acs-engine are you using? This error should not occur in recent versions

**Comment by mdpradeep** [comment]
The version is `v0.17.1`

**Comment by CecileRobertMichon** [comment]
Please use a more recent version (latest is 0.26.1). This error has been removed entirely since June (https://github.com/Azure/acs-engine/pull/3304).

**Comment by axelgMS** [comment]
thanks Cecile
