### ISSUE TITLE
Latest release is missing the usual assets (v0.26.3)

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Azure/acs-engine#4363]
![image](https://user-images.githubusercontent.com/2286713/50978934-5b1de000-14ed-11e9-9b37-9acdc8d53648.png)

**Comment by mboersma** [comment]
@ElvenSpellmaker I uploaded the correct archive files to the [v0.26.3 release](https://github.com/Azure/acs-engine/releases/tag/v0.26.3). Thanks for catching that!

**Comment by ElvenSpellmaker** [comment]
@mboersma Excellent, thanks!
