### ISSUE TITLE
Doc update: distinguish between custom VNET *within* 10.0.0.0/8 and otherwise

### ISSUE THREAD

**Issue by rocketraman** [Azure/acs-engine#437]
Based on the docs, I was under the impression that one had to go through a lot of manual work or use code in out-of-date pull request [1] to deploy Kubernetes to *any* VNET other than 10.0.0.0/8. However, after trying this for myself, I now realize deploying with a custom VNET that uses some subset of the 10.0.0.0/8 address space e.g. 10.1.0.0/16 works quite well already, by following the "Custom VNET" instructions (and tempory workaround [2]) to preconfigure the VNET and associated address space.

It would be useful to clearly distinguish in the docs between the second simple case using a subnet of 10.0.0.0/8, and the first currently not-so-simple case of using an entirely different address space.

[1] https://github.com/Azure/acs-engine/issues/180, https://github.com/Azure/acs-engine/issues/303, https://github.com/Azure/acs-engine/pull/191

[2] Step 7 @ https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md

**Comment by colemickens** [comment]
Can you show your changes? We hardcode the master ips to something that I don't believe falls in 10.1.0.0/16, so I'm not sure how it would be working.

I'm not really sure I understand how/why the docs are confusing, could you possibly suggest the change with a PR?

**Comment by rocketraman** [comment]
> Can you show your changes?

I followed the instructions on ACS-Engine for a custom VNET. 

1. Create a vnet in a resource group -- I used 10.2.0.0/16 for this install.

2. Update `kubernetes.json` as per the instructions in the CustomVNET directory of ACS-Engine:
2a. Include the path to the vnet created above in `properties.masterProfile.vnetSubnetId`
2b. Set `properties.masterProfile.firstConsecutiveStaticIP` to `10.2.255.239` (an IP inside the 10.2.0.0/16 subnet -- this is probably the key step to avoid the master IP hard-coding)
2c. Set `agentPoolProfiles[*].vnetSubnetId`

3. Deploy the templates generated by ACS-Engine to the same resource group as the custom vnet was originally created in

4. Finally, update the created routetable with the subnet information as instructed in temporary step 7.

Result: the master IP is set to the `10.2.255.239` address specified in kubernetes.json via `firstConsecutiveStaticIP`, and all other node IPs are also in the same 10.2.0.0/16 subnet. The internal Kubernetes service IPs are 10.0.0.0/16, and I believe internal pod IPs are 10.244.0.0/16, but I don't think that should impact gateway access to the vnet.

A remaining question, though, is what is the best way to expose some of my cluster services to traffic from a peered VNET (other non-Kubernetes services running inside a different Azure RG)? I considered service type of NodeIP, which I suspect would work, but that seems rather messy. Ideally, I'd like to use a service type of `LoadBalancer` with some appropriate params that causes it to listen on a 10.2.0.0/16 IP address, and sets up a NSG rule allowing source=VirtualNetwork.

> I'm not really sure I understand how/why the docs are confusing, could you possibly suggest the change with a PR?

Once I have understood what is happening here, I'd be happy to submit a doc-related PR if still applicable.

**Comment by colemickens** [comment]
There are upstream issues (and a PR in progress) for an annotation that will create an internal load balancer.

Which part do you not understand? You seem to have it working?

**Comment by rocketraman** [comment]
Thanks for the quick reply...

> There are upstream issues (and a PR in progress) for an annotation that will create an internal load balancer.

Great. In the meantime, what do you suggest as the best workaround?

> Which part do you not understand? You seem to have it working?

I guess I do understand it :-) I was going by your earlier comment "I'm not sure how it would be working."

**Comment by colemickens** [comment]
>Great. In the meantime, what do you suggest as the best workaround?

Use NodePort (and/or use NodePort + wire up the ILB yourself). Unfortunately, I don't know of a better solution right now.

>I guess I do understand it :-) I was going by your earlier comment "I'm not sure how it would be working."

I didn't realized you'd found all the things that needed to be changed 😄 .

**Comment by rocketraman** [comment]
> There are upstream issues (and a PR in progress) for an annotation that will create an internal load balancer.

BTW, for future reference to others, I believe these are the relevant links:

https://github.com/kubernetes/kubernetes/issues/38901
https://github.com/kubernetes/kubernetes/pull/43510

> Use NodePort (and/or use NodePort + wire up the ILB yourself). Unfortunately, I don't know of a better solution right now.

Using NodePort with a manually wired ILB worked, thanks.

I may still submit a minor docs PR, so I'll leave this open for now.

**Comment by siamak-haschemi** [comment]
As faar as I understood, the Azure networking solution for k8s is based on the cloud native ip-routes, instead of an overlay network. So my assumption is that the POD network segment can interfer with an existing network segment.

In our setup I separated all, master, node, and POD network segment to be different from our existing 10.0.0.0/12 network (our classical production environment where our product runs currently). For that, I had still places in the scs-engine code where I had to replace hardcoded values (merged with master yesterday).

**Comment by colemickens** [comment]
Presumably the peered vnet won't overlap with the k8s vnet space...

Service IPs are virtual (think like overlay) and only have meaning on the kube nodes, so shouldn't be a problem.

I am unsure about the Pod traffic though. Traffic should get out fine, but it won't be masqueraded if the peered vnet is 10.x.x.x/x.... You'd likely have to adjust the flag that controls masquerading or mirror the route table into the peered vnet. The only thing is, I don't know how mirroring that route table is going to work out if the nextHop addresses fall within the range of the peered vnet.

Generally speaking, I'd agree with @siamak-haschemi and try to keep them all distinct. There are other private ip ranges beside 10.0.0.0/8 that might alleeviate problems as well.

**Comment by rocketraman** [comment]
> Generally speaking, I'd agree with @siamak-haschemi and try to keep them all distinct. There are other private ip ranges beside 10.0.0.0/8 that might alleeviate problems as well.

Ok, so indeed there was something I didn't understand earlier. Thank you @siamak-haschemi and @colemickens for clarifying. The pod-to-pod networking is covered [here](https://kubernetes.io/docs/concepts/cluster-administration/networking/) and based on this doc, indeed Kubernetes assumes that all containers can communicate with all other containers without NAT, and that all nodes can communicate with all containers (and vice-versa) without NAT.

So if we already have other VNETs using addresses in the 10.0.0.0/8 space that we want to peer with, the only "provably correct" solution we are left with is to modify the Azure Kubernetes setup as described by @siamak-haschemi to use a different address space entirely. If only this were easier to do -- @siamak-haschemi 's pull request seems out of date and didn't seem ready to be accepted in any case...

**Comment by colemickens** [comment]
Those ranges are just variables in the output template, it shouldn't be hard to make the modifications, you seemed comfortable diving in for the other fields you changed, should just be a few more to touch.

This has been asked for a lot. If you or @siamak-haschemi or someone else were to rebase that PR, I will set aside some time to review it, make sure the api (in the apimodel.json) is agreeable with the team so we can move forward on this.

**Comment by rocketraman** [comment]
> Those ranges are just variables in the output template, it shouldn't be hard to make the modifications, you seemed comfortable diving in for the other fields you changed, should just be a few more to touch.

Here is what I come up with in the generated templates when searching for "10.":

```
grep -R "10\." _output/Kubernetes-18117938/*
_output/Kubernetes-18117938/apimodel.json:      "firstConsecutiveStaticIP": "10.2.255.239"
_output/Kubernetes-18117938/azuredeploy.json:      "defaultValue": "10.2.255.239",
_output/Kubernetes-18117938/azuredeploy.json:    "kubeDnsServiceIp": "10.0.0.10",
_output/Kubernetes-18117938/azuredeploy.json:    "kubeServiceCidr": "10.0.0.0/16",
_output/Kubernetes-18117938/azuredeploy.parameters.json:    "value": "10.2.255.239"
```

So the only 2 that seem to require change that cannot already be modified via the input json are `kubeDnsServiceIp` and `kubeServiceCidr`. Does that seem correct to you @colemickens ?

**Comment by siamak-haschemi** [comment]
In our case, we have an existing `10.0.0.0/12` network, which means

```
HostMin:   10.0.0.1             
HostMax:   10.15.255.254 
```

I planned our kubernetes cluster network like that:

```
private vnet 10.16.0.0/14 
HostMin: 10.16.0.1 
HostMax: 10.19.255.254

  DefaultKubernetesMasterSubnet 10.16.0.0/16
  HostMin:   10.16.0.1
  HostMax:   10.16.255.254

    DefaultFirstConsecutiveKubernetesStaticIP = 10.16.255.5

  AgentSubnet = 10.17.0.0/16
  HostMin:   10.17.0.1
  HostMax:   10.17.255.254

  kubeServiceCidr 10.18.0.0/16
  HostMin:   10.18.0.1
  HostMax:   10.18.255.254

    kubeDnsServiceIp 10.18.0.10

  kubeClusterCidr = 10.19.0.0/16
  HostMin:   10.19.0.1
  HostMax:   10.19.255.254

    [
      podCIDR1 = 10.19.1.0/24
      HostMin:   10.19.1.1
      HostMax:   10.19.1.254

      podCIDR2 = 10.19.2.0/24
      HostMin:   10.19.2.1
      HostMax:   10.19.2.254

      ...
    ]
```

And to achieve that, I have this patch

[acs-engine-modify-subnet.txt](https://github.com/Azure/acs-engine/files/877088/acs-engine-modify-subnet.txt) based on commit 1c322cd9469d6cdf25575e3c22d7806af0cf07f6

@colemickens Unfortunately, I don't see having time to contribute code-wise.

**Comment by rocketraman** [comment]
I did the primary grunt work of rebasing pull https://github.com/Azure/acs-engine/pull/191 BUT my rebased branch is definitely broken -- the tests don't work. Unfortunately, I don't have time to dig deeper and understand why... but hopefully someone can build on it:

https://github.com/rocketraman/acs-engine/tree/rg/customVnet

cc: @colemickens

**Comment by rocketraman** [comment]
This discussion doesn't seem relevant any more with @ashb 's previous changes are merged in to master again: https://github.com/Azure/acs-engine/pull/546. Closing this issue.
