### ISSUE TITLE
Met an issue when scale up my agent pool 

### ISSUE THREAD

**Issue by jiaxaiol** [Azure/acs-engine#4372]
The error message as following:
malformed node or string: <_ast.BinOp object at 0x7fdfd51409b0>

**Comment by jiaxaiol** [comment]
I have uploaded the auzredeploy.json : https://leostorageaccount.blob.core.chinacloudapi.cn/acsticket/azuredeploy.json
azuredeploy.parameters.json:
https://leostorageaccount.blob.core.chinacloudapi.cn/acsticket/azuredeploy.parameters.json

**Comment by CecileRobertMichon** [comment]
this repo is not actively monitored, please open issues at https://github.com/Azure/aks-engine
