### ISSUE TITLE
Kubernetes Pods unable to access external hosts using networkPolicy Calico

### ISSUE THREAD

**Issue by ivan-section-io** [Azure/acs-engine#439]
I've just done a very default acs-engine Kubernetes cluster install using `"networkPolicy": { "value": "calico"  }.` From commit 1c322cd9469d6cdf25575e3c22d7806af0cf07f6
Pods on the resulting nodes cannot access external resources (e.g. DNS/http).

`tcpdump` reveals that traffic from pods exit the host's interface with pod source IP addresses.

I worked around this by adding an ipPool using `calicoctl` matching the pod addresses with `nat-outgoing: true`.
```
apiVersion: v1
kind: ipPool
metadata:
  cidr: 10.244.0.0/16
spec:
  nat-outgoing: true
```
This resulted in a change to `iptables -t nat ` on the host:
```
@@ -16,6 +16,7 @@
 Chain POSTROUTING (policy ACCEPT)
 target     prot opt source               destination
 felix-POSTROUTING  all  --  0.0.0.0/0            0.0.0.0/0
+MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            match-set felix-masq-ipam-pools src ! match-set felix-all-ipam-pools dst
 KUBE-POSTROUTING  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
 MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0
```
and `ipset`
```
Name: felix-masq-ipam-pools
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 448
References: 1
Members:
10.244.0.0/16
```
Pods can now access external systems. I'm no expert in these areas, so this is likely a crazy hack - but it's my work-around for the moment. (Of course it's also very possible this is the intended functionality, and I'm waaay off-track)

**Comment by colemickens** [comment]
I don't know enough about Calico's policy plugin to know what is expected here, or what the resolution should be.

cc: @simonswine (the contributor who added the Calico integration)

**Comment by colemickens** [comment]
Actually, ideally an e2e test should be added for Calico...

**Comment by simonswine** [comment]
This is a valid bug you raise and it hasn't come up using my manual testing approach. @colemickens it would be good to get e2e tests for that. 

@ivan-section-io what your "hack"  is doing is the way to go. I think it has been done on the etcdless yamls for calico, but we did not port that back to the kube-addons-manager ones we are using:
- https://github.com/projectcalico/calico/blob/master/v2.0/getting-started/kubernetes/installation/hosted/k8s-backend/calico.yaml#L32
- https://github.com/projectcalico/calico/blob/master/v2.0/getting-started/kubernetes/installation/hosted/k8s-backend-addon-manager/calico-configmap.yaml#L30

**Comment by caseydavenport** [comment]
Calico developer here. 

Can confirm that the correct solution is, as you describe above, to configure an IP Pool without outgoing NAT enabled.

**Comment by colemickens** [comment]
Thank you both for the quick responses! @simonswine mentioned on Slack that he would update the yamls that acs-engine pulls down, but that it might take a day or two.

Another option might be to actually bake those into acs-engine as we do with other addon-type yamls... it also aligns with an effort to reduce our dependencies on external hosts.

**Comment by ashb** [comment]
The IP range should not be hard-coded either, especially not once/if #473 is merged.

**Comment by ashb** [comment]
I took a look at bundling in the calico addon YAML files like we do with heapster/kubedns etc and it's not that straight foward sadly -- as we only want to include those files if the network policy is calico, but the customdata.yaml currently isn't templated so we can't put a conditional it in.

Do we want to convert customdata.yaml (and perhaps all the other bundles resources)? into a go text/template? That might mean we'd have to do fewer tricks and use `sed` less often at the cost of more processing at template generation time.

**Comment by lachie83** [comment]
Let me have a crack at getting this implemented

**Comment by lachie83** [comment]
This change is depended on #632 which supersedes #473

**Comment by lachie83** [comment]
This should do the trick. Build and test off this PR. LMK
