### ISSUE TITLE
Fix Apiserver HA config

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#440]
We need to remove the `--apiserver-count` flag and add --advertise-address to be the DNS LB endpoint.

I can add more details later, but this may fix or help address the TCP connection problem we've been seeing when an apiserver goes down...

cc: @raveeram

**Comment by raveeram** [comment]
Thanks Cole, that sounds intriguing. I'll try it out. Although I have some questions based on this: https://github.com/kubernetes/kubeadm/issues/37. Let's discuss when you're back

**Comment by colemickens** [comment]
Yes, this came up in a sig-cluster-lifecycle meeting around kubeadm.

What happens is this: without the flag, the 'kubernetes' service will flap, multiple times a second even, between the three apiservers as they try to claim ownership and update the `default/kubernetes` endpoints list.

As for the certs concerns, we would just make the api advertised address be the FQDN that we use everywhere else.

WITH the flag though, they're basically static. The apiserver updates a record for itself... and then if the apiserver dies... the record is still there, just getting stale. Also bad. Could possibly be somewhat related to the connection being held open. (Though, I talked with some folks from CoreOS and they seem to think it's just a flaw with Azure LB that it doesn't terminate the TCP conns).

Even if it doesn't fix the other issue... still good to do.

**Comment by JackQuincy** [comment]
Is this still something we need to look at? I'm reducing priority as it doesn't seem to be causing issues.

**Comment by anhowe** [comment]
duplicate
