### ISSUE TITLE
China Cloud clusterdefinition example

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#448]
Is there an example of the location parameter in the cluster definition? I thought one was added, but I don't see it...

**Comment by colemickens** [comment]
Maybe we don't need a full separate example, but we should add the location field to the apimodel and start requiring it in ACS-Engine.

**Comment by colemickens** [comment]
cc: @raulfiru

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
