### ISSUE TITLE
How to configure `allow-privileged=true`

### ISSUE THREAD

**Issue by holiman** [Azure/acs-engine#449]
In my pods, I'd like to run docker with `--privileged=true`. 

My yaml-files contain 

        securityContext:
          privileged: true

But it appears that the underlying infra does not allow this. So how/where do i set the flag to enable it? 

Thanks

**Comment by colemickens** [comment]
What makes you think the underlying infra does not allow this? Can you please share more information, like any error messages? Thanks!

**Comment by colemickens** [comment]
Hi @holiman! This is the relevant line: https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmaster-kube-apiserver.yaml#L19

It is enabled. I was just easily able to deploy nginx with privileged=true. Please feel free to add more details, but I'm closing this for now. Thanks.

**Comment by holiman** [comment]
The reason I thought `privileged` was not enabled was that my image is spitting out the following message: 
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
CRIT[04-04|08:11:19] failed to retrieve docker version        error="cannot connect to Docker endpoint"
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

It'a docker-in-docker image.

**Comment by colemickens** [comment]
That sounds like you didn't mount the docker socket in the Pod spec then. Either way, it sounds like an application/k8s-specs level problem.
