### ISSUE TITLE
German Cloud has different Ubuntu images

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#451]
So the deployments fail because the specific image version isn't in German Cloud. I think this should be fixed in the platform rather than making every single piece of software and vendor in Azure handle different images for different clouds.

**Comment by colemickens** [comment]
```
$ az group deployment create     --name="kubetest"    --resource-group="kube_test"   --template-file="/Users/firur/acs/src/github.com/Azure/acs-engine/_output/Kubernetes-12051246/azuredeploy.json" --parameters "@/Users/firur/acs/src/github.com/Azure/acs-engine/_output/Kubernetes-12051246/azuredeploy.parameters.json"
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "ImageNotFound",
    "target": "imageReference",
    "message": "The platform image 'Canonical:UbuntuServer:16.04-LTS:16.04.20170307' is not available. Verify that all fields in the storage profile are correct."
  }
}  Correlation ID: a655ce1d-64cf-489b-8775-2c9bb2073013
```

**Comment by colemickens** [comment]
Presumably distribution of the Ubuntu images is far from our control so we'll need to be able to handle different image URNs for the different locations/clouds.

**Comment by colemickens** [comment]
cc: @raulfiru

**Comment by colemickens** [comment]
@raulfiru Actually, for us to fix this, I think we'll need you to tell us what Ubuntu 16.04 images are available... Can you let us know which one you ended up using? `az vm list-images` or something similar should be a starting point for getting a list of the Ubuntu images... Thanks.

**Comment by raulfiru** [comment]
i don't fully get it.. since i get multiple results...

az vm image list --all give me this:
>"urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201701130",
>    "urn": "Canonical:UbuntuServer:16.04.0-LTS:16.04.201604203",
>    "urn": "Canonical:UbuntuServer:16.04.0-LTS:16.04.201605161",
>    "urn": "Canonical:UbuntuServer:16.04.0-LTS:16.04.201609071",
>    "urn": "Canonical:UbuntuServer:16.04.0-LTS:16.04.201610200",

az vm image list (cached)
>"urn": "Canonical:UbuntuServer:16.04-LTS:latest",

and the portal has this comment:

>Ubuntu Server 16.04 LTS amd64 20170330 Public Azure, 20170330 Azure China, 20170113 Azure >Germany, 20161221 Azure Gov. 

the one i used and worked was:  16.04.201701130 (the one in the portal)

**Comment by colemickens** [comment]
This isn't the most fun. @anhowe do you have any suggestions? Otherwise we're going to have to make these sorts of things part of the internal model as well... and as I'm looking at doing this, I realize we never fixed where the defaults are set... we need time to look into this and fix it correctly...

**Comment by colemickens** [comment]
As a shorter-term solution, @szarkos may be able to publish the image we use today into GermanCloud. I'll update more as I hear about this.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
