### ISSUE TITLE
NetworkUnavailable ->  RouteController failed to create a route

### ISSUE THREAD

**Issue by zachariahyoung** [Azure/acs-engine#461]
After a recent install we are getting the following error on each of our nodes.  We used the default install for kubernetes in our azure environment. 

In the log for the controller pod we a seeing this issue.

I0403 16:51:16.586553       1 routecontroller.go:154] Creating route for node k8s-agent-708c8d27-1 10.244.1.0/24 with hint ba6ca9b0-09ac-11e7-8248-000d3a726930, throttled 579ns
I0403 16:51:16.586581       1 azure_routes.go:65] create: creating route. clusterName="jbh-kubernetesmgmt" instance="k8s-agent-708c8d27-1" cidr="10.244.1.0/24"
I0403 16:51:16.586568       1 routecontroller.go:154] Creating route for node k8s-master-708c8d27-0 10.244.0.0/24 with hint 7bd59890-09ac-11e7-8248-000d3a726930, throttled 1.158µs
I0403 16:51:16.586709       1 azure_routes.go:65] create: creating route. clusterName="jbh-kubernetesmgmt" instance="k8s-master-708c8d27-0" cidr="10.244.0.0/24"
I0403 16:51:16.586829       1 routecontroller.go:154] Creating route for node k8s-agent-708c8d27-0 10.244.3.0/24 with hint e6014f2f-09ac-11e7-8248-000d3a726930, throttled 675ns
I0403 16:51:16.586849       1 azure_routes.go:65] create: creating route. clusterName="jbh-kubernetesmgmt" instance="k8s-agent-708c8d27-0" cidr="10.244.3.0/24"
I0403 16:51:16.586978       1 routecontroller.go:154] Creating route for node k8s-agent-708c8d27-2 10.244.2.0/24 with hint c7861bc4-09ac-11e7-8248-000d3a726930, throttled 386ns
I0403 16:51:16.587029       1 azure_routes.go:65] create: creating route. clusterName="jbh-kubernetesmgmt" instance="k8s-agent-708c8d27-2" cidr="10.244.2.0/24"
E0403 16:51:16.798590       1 routecontroller.go:160] Could not create route e6014f2f-09ac-11e7-8248-000d3a726930 10.244.3.0/24 for node k8s-agent-708c8d27-0 after 211.767883ms: network.RoutesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'f02cbf8c-c4cc-406f-9e2b-21d8c7b728ec' with object id 'f02cbf8c-c4cc-406f-9e2b-21d8c7b728ec' does not have authorization to perform action 'Microsoft.Network/routeTables/routes/write' over scope '/subscriptions/2bb0d855-54c8-40a4-8014-f4b28235be9c/resourceGroups/JBH_PROD_PLATFORM-APPSRV-ACS_RG/providers/Microsoft.Network/routeTables/k8s-master-708C8D27-routetable/routes/k8s-agent-708c8d27-0'."
I0403 16:51:16.798663       1 routecontroller.go:154] Creating route for node k8s-agent-708c8d27-0 10.244.3.0/24 with hint e6014f2f-09ac-11e7-8248-000d3a726930, throttled 675ns
I0403 16:51:16.798672       1 azure_routes.go:65] create: creating route. clusterName="jbh-kubernetesmgmt" instance="k8s-agent-708c8d27-0" cidr="10.244.3.0/24"
E0403 16:51:16.830856       1 routecontroller.go:160] Could not create route c7861bc4-09ac-11e7-8248-000d3a726930 10.244.2.0/24 for node k8s-agent-708c8d27-2 after 243.885936ms: network.RoutesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'f02cbf8c-c4cc-406f-9e2b-21d8c7b728ec' with object id 'f02cbf8c-c4cc-406f-9e2b-21d8c7b728ec' does not have authorization to perform action 'Microsoft.Network/routeTables/routes/write' over scope '/subscriptions/2bb0d855-54c8-40a4-8014-f4b28235be9c/resourceGroups/JBH_PROD_PLATFORM-APPSRV-ACS_RG/providers/Microsoft.Network/routeTables/k8s-master-708C8D27-routetable/routes/k8s-agent-708c8d27-2'."
I0403 16:51:16.830957       1 routecontroller.go:154] Creating route for node k8s-agent-708c8d27-2 10.244.2.0/24 with hint c7861bc4-09ac-11e7-8248-000d3a726930, throttled 868ns
I0403 16:51:16.831011       1 azure_routes.go:65] create: creating route. clusterName="jbh-kubernetesmgmt" instance="k8s-agent-708c8d27-2" cidr="10.244.2.0/24"
E0403 16:51:16.961588       1 routecontroller.go:160] Could not create route ba6ca9b0-09ac-11e7-8248-000d3a726930 10.244.1.0/24 for node k8s-agent-708c8d27-1 after 375.044715ms: network.RoutesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'f02cbf8c-c4cc-406f-9e2b-21d8c7b728ec' with object id 'f02cbf8c-c4cc-406f-9e2b-21d8c7b728ec'

What client do we need to change to fix the AuthorizationFailed error?

Zach

**Comment by anhowe** [comment]
@zachariahyoung This is pointing at a service principal error.  Here is the troubleshooting guide for this: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md#troubleshooting.

How did you create your service principal?

**Comment by zachariahyoung** [comment]
We don't have the service principal setup correctly I believe.  We will try again.  

Please close this issue.
