### ISSUE TITLE
What are the plans for upgrading clusters on day 365 for k8s clusters

### ISSUE THREAD

**Issue by jkurz** [Azure/acs-engine#464]
I love the idea of making k8s installations easier for my team. The issue I am trying to wrap my head around is, what happens on day 365 when kubelet needs to be upgraded. What happens if etcd needs to be updated or flannel needs to be updated? Are you planning on creating a guide to do updates, that we can follow or am I on my own, once I deploy my application to production and I need maintain the clusters.

Is the solution to just reprovision a new cluster and migrate all of the containers over? Sometimes that seems like it could be troublesome and possibly cause issues, especially if etcd nodes are running on the same vms that my kubelets are running on. Which is a whole nother issue. 

Thanks
Josh Kurz

**Comment by JackQuincy** [comment]
Upgrade is on our radar. It is also a priority, but we don't have a ETA yet. I'll update here as more info comes.

**Comment by jkurz** [comment]
@JackQuincy awesome. If there is anything you could make public, so the community could help work on the issue together, that would be great. I am willing to pitch in some elbow grease to possibly come up with a solution to make this a real thing. Would be awesome to come up with an automated solution that upgrades clusters based on some type of scripted method. That way all clusters get upgraded in the same way and it can be tested and proven out for each release.

**Comment by JackQuincy** [comment]
Last thinking I heard was an API to trigger upgrade so that enterprise customers wouldn't be forced to upgrade before they could test compatibility from our RP perspective. That will use some scripts or some other code/magic in ACS Engine to trigger/carryout the upgrade. 
This [PR](https://github.com/Azure/acs-engine/pull/467) is our team changing our setup of the Kubernetes clusters to try to make them easier to upgrade. But the plan is to start moving more of our discussion/progress into github.

**Comment by amanohar** [comment]
@jkurz, regarding:
_Would be awesome to come up with an automated solution that upgrades clusters based on some type of scripted method. That way all clusters get upgraded in the same way and it can be tested and proven out for each release._

Yes, that is the plan. It will be an automated solution based in input from the user and scripts so that all clusters follow the same upgrade model.

**Comment by Karnich** [comment]
Any news on this one? :)

**Comment by dtzar** [comment]
I've started to work on a guide which shows how to manually upgrade nodes and migrate workloads using ACS engine - utilizing new resource pools.  I'll share what I have soon.

**Comment by JackQuincy** [comment]
As for our plans. This is probably the best representation #707 . I believe it is in a workable state though in some failure cases it could get the cluster into a bad state. Let me know if you need more than that.

**Comment by dtzar** [comment]
Jack - thanks for the quick reply.  I took a quick peek through the code and it would take awhile to try and figure out how to actually utilize the functionality in that PR.  Could you perhaps spell out at least a little bit the flow of how I might try to utilize the functionality present there?

**Comment by JackQuincy** [comment]
I honestly haven't had time to go over it in depth. There is a command on acs-engine it adds. That is defined in file cmd/upgrade.go  that should show how to use it.

**Comment by dtzar** [comment]
On a fresh pull & build of acs-engine I'm not seeing the upgrade command come back as valid:
```
root@809413628b6d:/gopath/src/github.com/Azure/acs-engine# ./acs-engine upgrade
Error: unknown command "upgrade" for "acs-engine"
```

**Comment by amanohar** [comment]
@dtzar 

1) In Dockerfile at: github.com\Azure\acs-engine\Dockerfile add the following line:
    ENV ACSENGINE_EXPERIMENTAL_FEATURES 1
2) Build ACS Engine
3) Make sure orchestrator version in the input API model is:
```
 "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.5.3"
    }
```
4) Run the following command to deploy a v1.5.3 cluster:
./acs-engine deploy --subscription-id <_SubscriptionId_> --location "West US" --resource-group <_ResourceGroup_> --api-model  <_PathToYourAPIModelFile_>

5) Once step 4 is complete, run the upgrade command to upgrade to v1.6.2:
./acs-engine upgrade --subscription-id <_SubscriptionId_> --deployment-dir <_PathToDirectoryThatContainsTheTemplate_> --resource-group <_ResourceGroup_> --upgrademodel-file  <_UpgradeModelFile_>

Sample <_UpgradeModelFile_> attached (rename of .json)
[kubernetesUpgrade.txt](https://github.com/Azure/acs-engine/files/1043188/kubernetesUpgrade.txt)

**NOTE:**
**This is an experimental feature and still in the works so please try it on your test clusters only.** 

Upgrade operation is idempotent meaning that if it fails you can rerun it again using the same command and it should pick up where it left off. 
_Except in one case (The update to fix this is coming soon):_  the operation does not yet delete orphaned OS disks so if upgrade operation failed during VM deletion. In that case you might have to delete the OS disk of the deleted VM yourself and if you rerun the operation again it should pick up where it left off and continue with the upgrade.

**Comment by dtzar** [comment]
Awesome, thanks @amanohar! Would this method exclude any sort of upgrades starting from 1.6.2?  I.e. if I just want to patch my nodes, create a new sized node pool, deploy slightly newer commit from ACS-engine build, --> 1.6.4 ...

**Comment by amanohar** [comment]
@dtzar, 
- Only v1.5.3->1.6.2 is supported for now but more will come soon. Right now ACS Engine does not support creating a v1.6.4 cluster.
- When you scale up it will still create nodes of v1.5.3 because it going to use template from your existing location which is a v1.5.3 template. But after scale up you can run upgrade operation again and it should upgrade that node to the new version.

**Comment by dtzar** [comment]
when I run your deploy command it throws this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5d989a]

goroutine 1 [running]:
github.com/Azure/acs-engine/pkg/api/vlabs.(*Properties).Validate(0x0, 0x92, 0x292)
        /gopath/src/github.com/Azure/acs-engine/pkg/api/vlabs/validate.go:197 +0x3a
github.com/Azure/acs-engine/pkg/api.LoadContainerService(0xc42008c580, 0x92, 0x292, 0xc42011a948, 0x5, 0x0, 0x0,
0x292)
        /gopath/src/github.com/Azure/acs-engine/pkg/api/apiloader.go:73 +0x398
github.com/Azure/acs-engine/pkg/api.DeserializeContainerService(0xc42008c580, 0x92, 0x292, 0x92, 0x292, 0x0, 0x0,
 0x0)
        /gopath/src/github.com/Azure/acs-engine/pkg/api/apiloader.go:30 +0x13a
github.com/Azure/acs-engine/pkg/api.LoadContainerServiceFromFile(0x7fff5edd9924, 0x13, 0xc0dd00, 0xc4200136c0, 0x
0, 0x0, 0xc4201064e0)
        /gopath/src/github.com/Azure/acs-engine/pkg/api/apiloader.go:20 +0x1bd
github.com/Azure/acs-engine/cmd.(*deployCmd).validate(0xc42009c640, 0xc42011c000, 0xc42006a880, 0x0, 0x8)
        /gopath/src/github.com/Azure/acs-engine/cmd/deploy.go:97 +0x101
github.com/Azure/acs-engine/cmd.newDeployCmd.func1(0xc42011c000, 0xc42006a880, 0x0, 0x8, 0x0, 0x0)
        /gopath/src/github.com/Azure/acs-engine/cmd/deploy.go:57 +0x57
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc42011c000, 0xc42006a800, 0x8, 0x8
, 0xc42011c000, 0xc42006a800)
        /gopath/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200ad680, 0xc4200add40, 0xc4200
adb00, 0xc4200ad8c0)
        /gopath/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200ad680, 0xc420117f68, 0x893d13
)
        /gopath/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
        /gopath/src/github.com/Azure/acs-engine/main.go:9 +0x2f
```

**Comment by Karnich** [comment]
@amanohar how can i know if etcd is on a seperate data disk? When looking at the storage accounts for my cluster i only see OS disks for the nodes and master?

**Comment by amanohar** [comment]
@dtzar without looking at your input API model file my best guess is that OrchestratorProfile is null, i.e. its not present in the file?

@Karnich, if you created a K8s cluster using ACS Engine in the last 3 weeks or so you should have an etcddisk. 

The etcddisk is in the same storage account as the OS disk for the corresponding master VM and the name of the etcddisk disk ends with '-etcddisk'. You can also confirm by looking at datadisk in storageProfile of the master VM properties/definition.

**Comment by Karnich** [comment]
@amanohar Unfortunely all my clusters are older. Some even date back to the "preview" times ;)
Will updating clusters throught the CLI be supported in the future where the etcd disk is not seperate? Or is the best way just to create a new one? :)

**Comment by amanohar** [comment]
Upgrades using cli will be supported at some point. But as of right now there are no plans to support upgrades on clusters that don't have etcd on a separate disk.
