### ISSUE TITLE
Not able to pull image for kubelet

### ISSUE THREAD

**Issue by vmakhaev** [Azure/acs-engine#476]
Sometimes when I create clusters with acs-engine kubelet service not able to start. What I see from systemd logs is docker can not pull hyperkube image (gcr.io/google_containers/hyperkube-amd64:v1.5.3) 

```
Apr 07 14:19:07 k8s-agentpool1-35482160-1 systemd[1]: Started Kubelet.
Apr 07 14:19:07 k8s-agentpool1-35482160-1 docker[5274]: Unable to find image 'gcr.io/google_containers/hyperkube-amd64:v1.5.3' locally
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: v1.5.3: Pulling from google_containers/hyperkube-amd64
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 5040bd298390: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 6b1b1be60d9d: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: f163e8430603: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: e3a2e612099f: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: ae1cc9eb5881: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: e3592413a73f: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: a6576fd6cbda: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 4426b151b520: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 5c17a00e67cd: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 3ad0a968bece: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: b5975036b156: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 3579abf9ff23: Pulling fs layer
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 3579abf9ff23: Waiting
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: ae1cc9eb5881: Waiting
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: e3592413a73f: Waiting
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: a6576fd6cbda: Waiting
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 4426b151b520: Waiting
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 5c17a00e67cd: Waiting
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: 3ad0a968bece: Waiting
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: b5975036b156: Waiting
Apr 07 14:19:08 k8s-agentpool1-35482160-1 docker[5274]: e3a2e612099f: Waiting
Apr 07 14:19:39 k8s-agentpool1-35482160-1 docker[5274]: /usr/bin/docker: error pulling image configuration: Get https://storage.googleapis.com/artifacts.google-containers.appspot.com/containers/images/sha256:08fdc47202632891dbd15c1a1d25c2ff97afcc87a08e296cd43045619f0863e1: dial tcp 172.217.7.240:443: i/o timeout.
Apr 07 14:19:39 k8s-agentpool1-35482160-1 docker[5274]: See '/usr/bin/docker run --help'.
Apr 07 14:19:39 k8s-agentpool1-35482160-1 systemd[1]: kubelet.service: Main process exited, code=exited, status=125/n/a
Apr 07 14:19:39 k8s-agentpool1-35482160-1 systemd[1]: kubelet.service: Unit entered failed state.
Apr 07 14:19:39 k8s-agentpool1-35482160-1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

and I do not see agent nodes in cluster (there should be 10 agents, all of them have same issue):
```
kubectl get nodes
NAME                    STATUS                     AGE
k8s-master-30197476-0   Ready,SchedulingDisabled   9m
k8s-master-30197476-1   Ready,SchedulingDisabled   8m
k8s-master-30197476-2   Ready,SchedulingDisabled   8m
```

I'm able to connect to google.com:443 from this node:
```
nc -v google.com 443
Connection to google.com 443 port [tcp/https] succeeded!
```
but not able to connect to 172.217.7.240:443:
```
nc -v 172.217.7.240 443
nc: connect to 172.217.7.240 port 443 (tcp) failed: Connection timed out
```
so this does not look like network issue. And the only my guess, assuming that sometimes clusters work fine, is that maybe some azure's public ips are blocked by public docker repositories (could it be?).
anyway, here is public ip of this particular node: 40.71.196.227. Hope it will help.

**Comment by JackQuincy** [comment]
Thanks for reporting this. We are also looking at this internally. I don't have latest info on status though. @anhowe @amanohar Can you guys update here when you make progress?

**Comment by amanohar** [comment]
Hi @vmakhaev , can you run "curl ifconfig.co" to get external IP of the VM where you are seeing the repro and let us the know the IP.

**Comment by amanohar** [comment]
@vmakhaev, can you try again? The issue has been resolved now.

**Comment by vmakhaev** [comment]
@amanohar external IP of the VM was 40.71.196.227. I will return to this in few days and let you know if some thing goes wrong. Btw, what was the problem?

**Comment by amanohar** [comment]
A live site incident last week impacted a subset of customers resulting in the symptoms described in this issue. The problem has been identified and was resolved Friday April 7 afternoon PDT

**Comment by robbiezhang** [comment]
I hit the same issue today. some nodes fails to pull image for hours.

Apr 14 22:31:52 k8s-agentpool2-62235045-4 docker[5090]: Unable to find image 'gcr.io/google_containers/hyperkube-amd64:v1.5.3' locally
Apr 14 22:31:54 k8s-agentpool2-62235045-4 systemd[1]: Time has been changed
Apr 14 22:31:54 k8s-agentpool2-62235045-4 systemd[1]: apt-daily.timer: Adding 9h 17min 45.323201s random time.
Apr 14 22:31:54 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 4h 2min 6.451293s random time.
Apr 14 22:31:54 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 50min 9.283398s random time.
Apr 14 22:31:59 k8s-agentpool2-62235045-4 systemd[1]: Time has been changed
Apr 14 22:31:59 k8s-agentpool2-62235045-4 systemd[1]: apt-daily.timer: Adding 8h 36min 53.343869s random time.
Apr 14 22:31:59 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 3h 23min 56.086923s random time.
Apr 14 22:31:59 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 4h 13min 715.593ms random time.
Apr 14 22:32:04 k8s-agentpool2-62235045-4 systemd[1]: Time has been changed
Apr 14 22:32:04 k8s-agentpool2-62235045-4 systemd[1]: apt-daily.timer: Adding 11h 12min 53.892521s random time.
Apr 14 22:32:04 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 1h 29min 25.093203s random time.
Apr 14 22:32:04 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 3h 49min 5.841404s random time.
Apr 14 22:32:09 k8s-agentpool2-62235045-4 systemd[1]: Time has been changed
Apr 14 22:32:09 k8s-agentpool2-62235045-4 systemd[1]: apt-daily.timer: Adding 1h 13min 35.363241s random time.
Apr 14 22:32:09 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 1h 24min 3.335082s random time.
Apr 14 22:32:09 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 5h 14min 13.203605s random time.
Apr 14 22:32:14 k8s-agentpool2-62235045-4 systemd[1]: Time has been changed
Apr 14 22:32:14 k8s-agentpool2-62235045-4 systemd[1]: apt-daily.timer: Adding 3h 1min 52.329893s random time.
Apr 14 22:32:14 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 5h 10min 26.933088s random time.
Apr 14 22:32:14 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 4h 23min 49.798948s random time.
Apr 14 22:32:19 k8s-agentpool2-62235045-4 systemd[1]: Time has been changed
Apr 14 22:32:19 k8s-agentpool2-62235045-4 systemd[1]: apt-daily.timer: Adding 2h 40min 44.149317s random time.
Apr 14 22:32:19 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 1h 57min 41.599536s random time.
Apr 14 22:32:19 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 3h 22min 49.898867s random time.
Apr 14 22:32:23 k8s-agentpool2-62235045-4 docker[4994]: time="2017-04-14T22:32:23.117122719Z" level=error msg="Error trying v2 registry: Get https://gcr.io/v2/google_containers/hyperkube-amd64/manifests/v1.5
Apr 14 22:32:23 k8s-agentpool2-62235045-4 docker[4994]: time="2017-04-14T22:32:23.117184550Z" level=error msg="Attempting next endpoint for pull after error: Get https://gcr.io/v2/google_containers/hyperkube
Apr 14 22:32:23 k8s-agentpool2-62235045-4 docker[4994]: time="2017-04-14T22:32:23.117221868Z" level=error msg="Handler for POST /v1.24/images/create returned error: Get https://gcr.io/v2/google_containers/hy
Apr 14 22:32:23 k8s-agentpool2-62235045-4 docker[5090]: /usr/bin/docker: Error response from daemon: Get https://gcr.io/v2/google_containers/hyperkube-amd64/manifests/v1.5.3: dial tcp 64.233.171.82:443: i/o
Apr 14 22:32:23 k8s-agentpool2-62235045-4 docker[5090]: See '/usr/bin/docker run --help'.
Apr 14 22:32:23 k8s-agentpool2-62235045-4 systemd[1]: kubelet.service: Main process exited, code=exited, status=125/n/a
Apr 14 22:32:23 k8s-agentpool2-62235045-4 systemd[1]: kubelet.service: Unit entered failed state.
Apr 14 22:32:23 k8s-agentpool2-62235045-4 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Apr 14 22:32:23 k8s-agentpool2-62235045-4 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Apr 14 22:32:23 k8s-agentpool2-62235045-4 systemd[1]: Stopped Kubelet.
Apr 14 22:32:23 k8s-agentpool2-62235045-4 systemd[1]: Starting Kubelet...
Apr 14 22:32:23 k8s-agentpool2-62235045-4 ebtables[5119]: Bridge table: nat
Apr 14 22:32:23 k8s-agentpool2-62235045-4 ebtables[5119]: Bridge chain: PREROUTING, entries: 0, policy: ACCEPT
Apr 14 22:32:23 k8s-agentpool2-62235045-4 ebtables[5119]: Bridge chain: OUTPUT, entries: 0, policy: ACCEPT
Apr 14 22:32:23 k8s-agentpool2-62235045-4 ebtables[5119]: Bridge chain: POSTROUTING, entries: 0, policy: ACCEPT
Apr 14 22:32:23 k8s-agentpool2-62235045-4 iptables[5123]: Chain PREROUTING (policy ACCEPT)
Apr 14 22:32:23 k8s-agentpool2-62235045-4 iptables[5123]: target     prot opt source               destination
Apr 14 22:32:23 k8s-agentpool2-62235045-4 iptables[5123]: Chain INPUT (policy ACCEPT)
Apr 14 22:32:23 k8s-agentpool2-62235045-4 iptables[5123]: target     prot opt source               destination
Apr 14 22:32:23 k8s-agentpool2-62235045-4 iptables[5123]: Chain OUTPUT (policy ACCEPT)
Apr 14 22:32:23 k8s-agentpool2-62235045-4 iptables[5123]: target     prot opt source               destination
Apr 14 22:32:23 k8s-agentpool2-62235045-4 iptables[5123]: Chain POSTROUTING (policy ACCEPT)
Apr 14 22:32:23 k8s-agentpool2-62235045-4 iptables[5123]: target     prot opt source               destination
Apr 14 22:32:23 k8s-agentpool2-62235045-4 systemd[1]: Started Kubelet.
Apr 14 22:32:23 k8s-agentpool2-62235045-4 docker[4994]: time="2017-04-14T22:32:23.460190467Z" level=error msg="Handler for POST /v1.24/containers/create returned error: No such image: gcr.io/google_container
Apr 14 22:32:23 k8s-agentpool2-62235045-4 docker[5127]: Unable to find image 'gcr.io/google_containers/hyperkube-amd64:v1.5.3' locally

**Comment by colemickens** [comment]
(If you use triple backticks, newline, paste, newline, triple backticks, then you will get slightly nicer formatting there)

We're working on fixing this (cc: @dmitsh), but in the meantime... we should look to see if this is the same root cause as last time and raise alarms as needed (cc:  @amanohar).

**Comment by robbiezhang** [comment]
Thanks for the tips. Update the formatting. I still have one machine failed to pull the hyperkube image.

```
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: Time has been changed
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: apt-daily.timer: Adding 3h 27min 7.979891s random time.
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: snapd.refresh.timer: Adding 4h 46min 55.952799s random time.
Apr 15 00:39:51 k8s-agentpool2-62235045-4 docker[4994]: time="2017-04-15T00:39:51.264921872Z" level=error msg="Not continuing with pull after error: Error pulling image (v1.5.3) from gcr.io/google_containers/hyp
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: kubelet.service: Main process exited, code=exited, status=125/n/a
Apr 15 00:39:51 k8s-agentpool2-62235045-4 docker[8870]: 5b1f17435ed5: Error pulling layer metadata
Apr 15 00:39:51 k8s-agentpool2-62235045-4 docker[8870]: eb0c136b8d12: Error pulling image (v1.5.3) from gcr.io/google_containers/hyperkube-amd64, endpoint: https://gcr.io/v1/, Failed to download json: Get https:
Apr 15 00:39:51 k8s-agentpool2-62235045-4 docker[8870]: eb0c136b8d12: Error pulling image (v1.5.3) from gcr.io/google_containers/hyperkube-amd64, Failed to download json: Get https://gcr.io/v1/images/5b1f17435ed
Apr 15 00:39:51 k8s-agentpool2-62235045-4 docker[8870]: /usr/bin/docker: Error pulling image (v1.5.3) from gcr.io/google_containers/hyperkube-amd64, Failed to download json: Get https://gcr.io/v1/images/5b1f1743
Apr 15 00:39:51 k8s-agentpool2-62235045-4 docker[8870]: See '/usr/bin/docker run --help'.
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: kubelet.service: Unit entered failed state.
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: Stopped Kubelet.
Apr 15 00:39:51 k8s-agentpool2-62235045-4 systemd[1]: Starting Kubelet...
```

**Comment by colemickens** [comment]
Can you get me the whole log? `sudo journalctl -u kubelet | nc termbin.com 9999` will spit out a URL with the contents of the kubelet log. I need to see why the gcr pulls are failing. I'm wondering if the same livesite thing as last week is occurring now (sporadically) ?

**Comment by robbiezhang** [comment]
I cannot repo the issue these days. All the nodes reported to the master after the Azure template is deployed..

**Comment by seanknox** [comment]
Sounds like this can no longer be reproduced. Feel free to reopen @vmakhaev.
