### ISSUE TITLE
ACS engine should support CoreOS

### ISSUE THREAD

**Issue by wangtt03** [Azure/acs-engine#484]

**Comment by wangtt03** [comment]
https://github.com/Azure/acs-engine/issues/83

**Comment by wangtt03** [comment]
#83

**Comment by wangtt03** [comment]
#466

**Comment by wangtt03** [comment]
I am working on this issue. #83

**Comment by amanohar** [comment]
Linking to issue tracking CoreOS support for DC/OS: https://github.com/Azure/acs-engine/issues/83

**Comment by colemickens** [comment]
Can you please discuss how you plan to achieve this @wangtt03 ? For example, I don't want to have to maintain 2x copies of customData for different distros...

**Comment by wangtt03** [comment]
Currently I made two copies of customData because I found there are too much difference between them. CoreOS doesn't support bootcmd/runcmd and there are also some modifications in `write_files` section. I tried to merge them into one file but it is unreadable.

The modifications I made:
1.  Make a new copy of customData and make it workable for CoreOS
2. Add a parameter `osImageOffer` in `masterparams.t` with allowedValues: `UbuntuServer/CoreOS`
3. Modifications to `dcosmastervars.t` to add variables based on the selection of OSImageOffer.
4. Update `engine.go` adding new customData files and select correct customData using orchestratorType and OSImageOffer.
5. Changes to `dcosmasterresources.t` because OSTCExtensions doesn't work in CoreOS. Using `Microsoft.Azure.Extensions` instead.
6. Modifications to `dcos-setup.service` to replace the `/usr/bin/curl` to `/opt/mesosphere/bin/curl` in `dcos-adminRouter.service` because default curl of CoreOS reports error when starting it.

**Comment by amanohar** [comment]
Some questions/feedback:
- osImageOffer - is an a overused term since its used in Azure internally to define different skus of the 
same OS as well.  Can we call it OSDistribution or better yet LinuxDistribution?
Also, where do you plan to add this in the API so that the user can specify it?
- Making 2 copies of customData might make it difficult to manage. Would it be possible to parameterize custom data so that common parts stay in once place?
- Does Microsoft.Azure.Extensions work on Ubuntu? 
- For #6 in your list above, can you ask this question on Mesosphere slack channel and/or their GitHub repo to confirm.

In general DC/OS templates are written in collaboration with Mesosphere so it would be useful to get their input as well.

**Comment by colemickens** [comment]
If we're going multi OS, it may be time to ditch cloud init and either
write a shell script or use Ansible (even if we only ever run the playbook
once, immutable style.)

**Comment by anhowe** [comment]
We are closing as won't fix, since the multi-os scenario is out of currently scope for ACS-Engine.

@wangtt03 We do need some help with Sovereign cloud infrastructure building on what you have added, and @colemickens is filing an update.

**Comment by wangtt03** [comment]
@amanohar I use both `OSTCExtension` and `AzureExtension` in the resource template and use OSImageOffer to switch between two extensions. The root cause is that `OSTCExtension` in CoreOS cannot download its dependencies which made customescript.py timeout.

And for the mesosphere issue, I guess the DCOS setup will overwrite the /usr/bin/curl however the /usr volume of CoreOS is ready-only, then it fails.

@anhowe @colemickens could you please share me more info about the sovereign cloud infra and please feel free to let me know what I can do.

**Comment by colemickens** [comment]
@wangtt03 there's internal mail on that subject, but basically it's:
 * https://github.com/Azure/acs-engine/issues/492
 * https://github.com/Azure/acs-engine/issues/451
 * https://github.com/Azure/acs-engine/issues/450
