### ISSUE TITLE
Cleanup handling of different sovereign clouds

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#492]
There are a lot of places in the code where we have specialized branching off for different suffixes, etc. I think it would be better/cleaner if we had a struct like this declared, and passed around everywhere. Additionally, this could be done at the same time as #450, #451... in fact that's how I wanted to implement #451/#450 but I realize there is no good precedent for it.

Also, it's very awkward that the DNS suffix calculation is done inside of the const file that is generated by PowerShell...

We need a proper struct that contains all of the things for a given cloud - the download prefix, the FQDN suffix, etc... and then we need to use a const instance of the struct to pass around everywhere to let specific decisions be made. The go-autorest project even has these things already for us to use. For example: https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L122

Another field of this struct would be the Image to use.

```
type AcsEngineEnvironment struct {
    ImageOffer string
    ImageSku string
    DockerPrefix string
    FQDNSuffix string
}
```

**Comment by wangtt03** [comment]
I think I can take this job but I don't have test accounts for these sovereign clouds. How can we collaborate on this issue?

**Comment by colemickens** [comment]
I think we will have some willing counterparts in Germany to test, albeit asynchronously.

Additionally, the template outputs should be the same (other than where the GermanCloud FQDN suffix gets fixed... so you can always just diff the current output against the future output after your changes. I think this will be an okay strategy because the changes detailed here will be almost exclusively inside the engine.

**Comment by benkoller** [comment]
If you still need access to the GermanCloud let me know, we can help.

**Comment by wangtt03** [comment]
@benkoller Thanks a lot! Once I finished my coding work, I will work with you to test it:)

**Comment by wangtt03** [comment]
This PR #499 should fix the problem. @benkoller Could you please help me test it on GermanCloud? Thanks!

**Comment by benkoller** [comment]
I will take a peek in the following days and give you an update asap afterwards. Thx for the efforts.
