### ISSUE TITLE
Docker-Engine is not installed on some node

### ISSUE THREAD

**Issue by robbiezhang** [Azure/acs-engine#497]
I use the ACS engine to provision a cluster today. I have 4 machines in an agent pool, but only 2 nodes shows up in the kubectl.

One of the failed nodes shows up after ~25 minutes. The journalctl log shows that it failed to download hyperkube image, but it's auto-recovered by retries.
The other node didn't show up because the docker-engine is not installed. It gets timeout when fetching the gpg keys from apt.dockerproject.org.

`for i in 1 2 3 4 5; do curl --max-time 60 -fsSL https://apt.dockerproject.org/gpg | apt-key add -; [ $? -eq 0 ] && break || sleep 5; done`

https://github.com/yangl900/acs-engine/blob/master/parts/kubernetesagentcustomdata.yml#L145

There is no retry logic to install the docker-engine again. So, the node is dead, won't recover automatically. 

I have to ssh to the machine and run the scripts manually. After ~15 minutes, the node shows up in the kubectl.

**Comment by colemickens** [comment]
Did it timeout on GPG key or on the package installing? Can you please provide logs?

Also, what commit was this on? Is it that `master` branch from @yangl900's repo?

**Comment by robbiezhang** [comment]
It timeouted in both places, basically, the apt.dockerproject.org website has not response. However, the other node, which is health, can communicate with it.

`Apr 14 22:06:02 k8s-agentpool2-62235045-3 cloud-init[1739]: curl: (28) Connection timed out after 60000 milliseconds
Apr 14 22:06:02 k8s-agentpool2-62235045-3 cloud-init[1739]: gpg: no valid OpenPGP data found.
Apr 14 22:06:05 k8s-agentpool2-62235045-3 systemd[1]: Time has been changed
Apr 14 22:06:05 k8s-agentpool2-62235045-3 systemd[1]: apt-daily.timer: Adding 6h 20min 9.963208s random time.
Apr 14 22:06:05 k8s-agentpool2-62235045-3 systemd[1]: snapd.refresh.timer: Adding 2h 56min 25.018608s random time.
Apr 14 22:06:05 k8s-agentpool2-62235045-3 systemd[1]: snapd.refresh.timer: Adding 2h 56min 53.528231s random time.
Apr 14 22:06:07 k8s-agentpool2-62235045-3 sudo[3186]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/tee /etc/apt/sources.list.d/docker.list
Apr 14 22:06:07 k8s-agentpool2-62235045-3 sudo[3186]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 14 22:06:07 k8s-agentpool2-62235045-3 cloud-init[1739]: deb https://apt.dockerproject.org/repo ubuntu-xenial main
Apr 14 22:06:07 k8s-agentpool2-62235045-3 sudo[3186]: pam_unix(sudo:session): session closed for user root
Apr 14 22:06:07 k8s-agentpool2-62235045-3 cloud-init[1739]: Hit:1 http://azure.archive.ubuntu.com/ubuntu xenial InRelease
Apr 14 22:06:07 k8s-agentpool2-62235045-3 cloud-init[1739]: Hit:2 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease
Apr 14 22:06:07 k8s-agentpool2-62235045-3 cloud-init[1739]: Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Apr 14 22:06:07 k8s-agentpool2-62235045-3 cloud-init[1739]: Hit:4 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease`

`Apr 14 22:08:07 k8s-agentpool2-62235045-3 cloud-init[1739]: Err:5 https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Apr 14 22:08:07 k8s-agentpool2-62235045-3 cloud-init[1739]:   Connection timed out after 120001 milliseconds
Apr 14 22:08:09 k8s-agentpool2-62235045-3 cloud-init[1739]: Fetched 102 kB in 2min 0s (850 B/s)
Apr 14 22:08:10 k8s-agentpool2-62235045-3 cloud-init[1739]: Reading package lists...
Apr 14 22:08:10 k8s-agentpool2-62235045-3 cloud-init[1739]: W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/InRelease  Connection timed out after 120001 milliseconds
Apr 14 22:08:10 k8s-agentpool2-62235045-3 cloud-init[1739]: W: Some index files failed to download. They have been ignored, or old ones used instead.
Apr 14 22:08:10 k8s-agentpool2-62235045-3 cloud-init[1739]: Reading package lists...
Apr 14 22:08:10 k8s-agentpool2-62235045-3 systemd[1]: Time has been changed
Apr 14 22:08:10 k8s-agentpool2-62235045-3 systemd[1]: apt-daily.timer: Adding 58min 42.411246s random time.
Apr 14 22:08:10 k8s-agentpool2-62235045-3 systemd[1]: snapd.refresh.timer: Adding 51min 38.481857s random time.
Apr 14 22:08:10 k8s-agentpool2-62235045-3 systemd[1]: snapd.refresh.timer: Adding 4h 24min 23.771386s random time.`

It's from yangl900. I merged from the Azure\acs-engine, and created the release branch with other changes: https://github.com/yangl900/acs-engine/tree/rel-20170412

**Comment by anhowe** [comment]
Our pgp issues have been resolved by referencing the azure cdn now.  Please open if you see this again.
