### ISSUE TITLE
NodePort support ?

### ISSUE THREAD

**Issue by jaydp17** [Azure/acs-engine#500]
Does ACS running k8s support NodePort?
I tried with a simple `nginx` pod as well as k8s dashboard.

I wasn't able to access it outside the cluster.

BTW, I'm using a cluster with linux nodes

**Comment by colemickens** [comment]
We support type=LoadBalancer which is probably better for your scenario. `NodePort` is also "supported" but you'd need to poke holes in the NSG manually. If you just do `LoadBalancer` type then this will all be done for you automatically.

**Comment by colemickens** [comment]
Closing this in favor of the discussion on GitHub. https://stackoverflow.com/questions/43423906/does-nodeport-work-on-azure-container-service-kubernetes

Please see the SO post where there is better information than I provided in my last reply (which I'm removing now).
