### ISSUE TITLE
InvalidParameter: platformFaultDomainCount when using agent disks

### ISSUE THREAD

**Issue by jaydp17** [Azure/acs-engine#502]
Trying to create a cluster with managed disks, it throws the below error
```sh
$ az group deployment create --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP --template-file "./_output/Kubernetes-30677023/azuredeploy.json" --parameters "@./_output/Kubernetes-30677023/azuredeploy.parameters.json"

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "InvalidParameter",
    "target": "platformFaultDomainCount",
    "message": "The specified fault domain count 3 must fall in the range 1 to 2."
  }
}  Correlation ID: a6c81eec-0020-49b3-9599-221147081ebe
```

Here's the JSON file I'm using
```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "kube101",
      "vmSize": "Standard_DS3_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "storageProfile": "ManagedDisks",
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "diskSizesGB": [128]
      }
    ],
    "linuxProfile": {
      "adminUsername": "ubuntu",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "REDACTED"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "servicePrincipalClientID": "REDACTED",
      "servicePrincipalClientSecret": "REDACTED"
    }
  }
}
```

BTW, it works perfectly fine without the agent disks 😕

**Comment by dmitsh** [comment]
Which region are you deploying in?

**Comment by jaydp17** [comment]
I'm deploying to `southindia`.
Let me try and deploy to some other region.

**Comment by dmitsh** [comment]
Could you try westus?

**Comment by jaydp17** [comment]
sure

**Comment by jaydp17** [comment]
It works in `westus`

BTW, this could be a noob question (but I'm fairly new to Azure & k8s)
Where is the disk mounted? Here's the output from one of the agent nodes.
```sh
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% /dev
tmpfs           697M  1.1M  696M   1% /run
/dev/sda1        30G  2.4G   27G   9% /
tmpfs           3.5G     0  3.5G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.5G     0  3.5G   0% /sys/fs/cgroup
/dev/sdb1        14G   35M   13G   1% /mnt
tmpfs           697M     0  697M   0% /run/user/1000
```

**Comment by JackQuincy** [comment]
This does appear to be an issue/bug where we are always setting the fault domain to 3 and not all regions allow that many fault domains. 

I'm currently deploying a managed disk cluster to try to find the disk.

**Comment by JackQuincy** [comment]
I can't ssh into my cluster for some reason... You should be able to use fdisk, makefs, and mount to mount your disk sdc disk. I'm suprised that didn't happen by default though. @anhowe are there manual steps to take on a machine to be able to use the managed data disks?

**Comment by JackQuincy** [comment]
We should move the 3 to parameter and set that parameters value from the azureconsts.go file and vary it based on destination region. Issue is there isn't a table of which regions only allow 2 fault domains that I have heard of. So it might just take manual testing.

**Comment by jmspring** [comment]
I'm running into this in WestUS2.

**Comment by pheuter** [comment]
Running into this in WestUS2 when trying to deploy kubernetes: https://github.com/coreos/terraform-azurerm-kubernetes

**Comment by mliyanagamage** [comment]
Hey guys, stumbled onto this issue while looking at the same error for something unrelated, but found this table and thought you guys might find it useful

https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/managed-disks-common-fault-domain-region-list.md

**Comment by ashutoshishere04** [comment]
how can one specify this range, my current range is 1-1 in centraluseuap region
