### ISSUE TITLE
Make '/etc/kubernetes/azure.json' more secure

### ISSUE THREAD

**Issue by karataliu** [Azure/acs-engine#504]
'/etc/kubernetes/azure.json' contains field 'aadClientSecret', thus it would be better to make it more secure.
1. For now file '/etc/kubernetes/azure.json' has a permission of 0644, it could better be 0600.
  Related: https://github.com/Azure/acs-engine/blob/4151596be9f8c3292e4b2650840b2c088ae8fb69/parts/kubernetesmastercustomscript.sh#L52

2. The secret field appears also on agent nodes. Will agent nodes need permission to operate with Azure resources? If not seems we could also hide such field for agent nodes.

**Comment by colemickens** [comment]
@karataliu 

1. Agreed.

2. This PR effectively removes it: https://github.com/Azure/acs-engine/pull/483
