### ISSUE TITLE
Adding a new node to existing k8s cluster

### ISSUE THREAD

**Issue by rushabhnagda11** [Azure/acs-engine#505]
Hi,

I have a running kubernetes cluster with 3 nodes. I modified the agentpool1Count from 3 to 4, in azuredeploy.parameters.json.

What I've observed is, the new node was added successfully, however there was a 5 minute downtime where the entire cluster (including all services) became unresponsive. Any idea why this is happening?

Also, what's the best way to add a new node to a cluster deployed using acs-engine?

**Comment by colemickens** [comment]
This is because when you re-PUT the template, it removes the rules from the NetworkSecurityGroup. Currently, we recommend you remove the NSG from the output template before PUTing it to avoid breaking external service access for that interim period.

**Comment by JackQuincy** [comment]
please see https://github.com/Azure/acs-engine/tree/master/examples/scale-up for details on how to scale up reliably without down time.
