### ISSUE TITLE
Image GC not running

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#510]
This is almost surely because we run `kubelet` from a container. It might be time to consider not doing that.

From a `kubectl describe node ...`:
```
 4m            4m              1       {kubelet k8s-agentpri-24696100-0}                       Warning         ImageGCFailed           unable to find data for container /
```

**Comment by nancyxue** [comment]
Has been happening to us in k8s v1.6.1.  How to run kubelet not from a container?

**Comment by wenwu449** [comment]
Almost all Windows nodes are reporting "ImageGCFailed" warning, here is the event:
4m         2d          763       13472acs90216                                            Node                                    Warning   ImageGCFailed         {kubelet 13472acs90216}   invalid capacity 0 on device "" at mount point ""

**Comment by colemickens** [comment]
@wenwu449 that's a different issue. There are a lot of things misisng for Windows, and I'm pretty sure that's one of them. Can you open a new issue in ACS-Engine, and then file one upstream against Kubernetes and link them together?

Thanks.

As an update on this bug: apparently it only occurs sporadically, possibly only right after kubelet comes up, and then it gets back to a steady state.

**Comment by CecileRobertMichon** [comment]
Closing as we are no longer running kubelet inside a container.
