### ISSUE TITLE
Ping to 10.0.x.x from Pod not working.

### ISSUE THREAD

**Issue by karthik-ir** [Azure/acs-engine#514]
I have pods with CIDR `17.244.0.0/24`. 
I have a external machine (Outside of k8 cluster) with ip 10.0.1.23. 
I ping the machine from the master node or agent node to check if it is reachable. And it is successfully pingable from master/agent. 
But then when trying to access the machine from within the pod, I see that it is not reachable. 

My assumption is 10.0.0.0/8 should be assigned to some of the k8 cluster thing and is not being redirected outside of the cluster. 
I do a `iptables-save | grep 10.0` and i Find `-A POSTROUTING ! -d 10.0.0.0/8 -m comment --comment "kubenet: SNAT for outbound traffic from cluster" -m addrtype ! --dst-type LOCAL -j MASQUERADE` This is weird. 

Output of `ip route` 
` default via 17.244.0.1 dev eth0 
17.244.0.0/24 dev eth0  src 17.244.0.8 `

What could be wrong here ? Please let me know if any other info is required.

**Comment by anhowe** [comment]
Service IPs cannot be pinged.  This is by design, and more information here: https://github.com/kubernetes/kubernetes/issues/7996#issuecomment-100413276

**Comment by karthik-ir** [comment]
@anhowe Nope! I think I have not explained the issue well. 
I have another machine which has IP 13.4.5.6, This is ping-able from within the pod. 
But then The machine with IP 10.0.x.x will not be ping-able. 
I'm talking about a machine which is outside of the k8s cluster.

**Comment by karthik-ir** [comment]
@JackQuincy @anhowe Is this definitely not an issue? Can we reopen this?

**Comment by andrewstevenson** [comment]
@JackQuincy @anhowe I have the same issue. I'm aware you can not ping a service from a pod but in this case I'm not trying to do that.  I'm trying to ping a set of Kafka vms outside of the k8 cluster in a separate subnet (10.0.0.0) . K8 is deployed to 10.0.2.0 in the same vnet.

**Comment by JackQuincy** [comment]
This appears to be overlapping subnets or something of the sort. I'm not the expert on networking in general and definitely not on k8s networking. Can you tell if the containers subnet and the other services subnet are overlapping? if so K8s runs its networking largely via ip tables on the nodes + route tables in the vnet. If the subnets overlap k8s might be looking for a container with that address and not finding it.

**Comment by andrewstevenson** [comment]
@JackQunicy I believe they are. The default kubednsserviceip is 10.0.0.10 which I think is the issue. I'm not sure what the various ips configurations should be if I need to change this?

**Comment by karthik-ir** [comment]
@andrewstevenson @JackQuincy To my observation, The subnet change for the Pods doesn't change the subnet of the kube-dns. And it still runs on the 10.x.x.x/8 subnet. And so the the ip get routed back to the kubernetes cluster. I believe there should be some external configuration on setting it as a parameter to the kube-dns. Correct me if im wrong.
