### ISSUE TITLE
Zombie processes exceeding ulimits

### ISSUE THREAD

**Issue by rushabhnagda11** [Azure/acs-engine#521]
I have a k8s cluster running for about a month. One of the nodes became very unresponsive, on sshing into this node (which worked after a few attempts).

ps -ef | grep defunct | wc -l gives 18622 processes.

Here is a sample of ps -ef | grep defunct

root     63412 16414  0 Mar31 ?        00:00:00 [wc] \<defunct>
root     63451 16414  0 Mar31 ?        00:00:00 [wc] \<defunct>
root     63588 16414  0 Mar31 ?        00:00:00 [wc] \<defunct>
root     63679 16414  0 Mar31 ?        00:00:00 [wc] \<defunct>
root     63686 16414  0 Mar31 ?        00:00:00 [wc] \<defunct>

where 16414 is the kubelet process. Any idea why they're not getting killed properly?

**Comment by rushabhnagda11** [comment]
After restarting the kubelet process on these nodes. Things seem to be fine. It's been around 4 days and not observing any such process on ps -aux.

Something very specific to my setup might have triggered this?

**Comment by seanknox** [comment]
Hi @rushabhnagda11. Take a look at the Kubernetes cluster troubleshooting guide: https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/

I'm closing this issue for now, but feel free to re-open if you gather more information.

**Comment by rushabhnagda11** [comment]
not reopening since I cant find a way to reproduce
