### ISSUE TITLE
Kubelet errors out when /var/lib/docker point to an external drive

### ISSUE THREAD

**Issue by jaydp17** [Azure/acs-engine#522]
Using the solutions given over https://github.com/moby/moby/issues/3127

I moved the `/var/lib/docker` directory to `/datadrive/.docker-files`.
The origininal path is sym linked `ln -s /datadrive/.docker-files /var/lib/docker`

After that no pod is starting on that node, here's the error
```sh
Error syncing pod 00fc5316-2766-11e7-a086-000d3a3047d2, skipping: failed to "StartContainer" for "POD" with RunContainerError: "addNDotsOption: ResolvConfPath \"/datadrive/.docker-files/containers/b56a2b54d8829f500854e759db7277675fccc3623f6927406d022f5afe37817c/resolv.conf\" does not exist"
```

The path given in the error does exist, I checked.

Any clues, what going wrong?

**Comment by JackQuincy** [comment]
I'm pretty sure docker runs as super user, but can you check permissions on the file. It might be possible docker can't list or read it.

**Comment by jaydp17** [comment]
Docker is able to access the files as I can pull images and run them directly through docker.
Something's wrong with Kubelet container.

**Comment by seanknox** [comment]
Hi @jaydp17. I believe this is a Docker/Linux issue and not an acs-engine one. Closing, but if you believe acs-engine to specifically be involved, feel free to re-open.
