### ISSUE TITLE
Understanding managed disks template in Kubernetes

### ISSUE THREAD

**Issue by ams0** [Azure/acs-engine#523]
I deployed a cluster using [this template](https://github.com/Azure/acs-engine/blob/master/examples/disks-managed/kubernetes-vmas.json), since #144 has been merged. After successful deployment, I have:

- a master with the OS disk in storage account (unmanaged) and a 128GB data disk (managed); however, the latter, reported as /dev/sdc, is not formatted and not mounted
- agents have one OS disk, managed, of 30GB

I fail to see the purpose of this setup; etcd is still running on the master with  _--data-dir /var/lib/etcddisk_ and the agents have no extra disks to present to Kubernetes (specifically, my goal is to automate GlusterFS setup in ACS).

thanks

**Comment by JackQuincy** [comment]
> is not formatted and not mounted
This is a bug. That disk is supposed to be mounted and have etcd on it. 

The Managed disk support is not for adding more disks to give to the containers. In Kubernetes you should use a PVC and Azure disks or Azure files for that(Kubernetes will dynamically allocate them for you, there are issues here about this which you can look at to try to find a good setup). The point of the Managed disks in the api model is to get your disks storage accounts spread out across fault domains.

**Comment by khenidak** [comment]
There are two things to consider:

1. A cluster running on managed disks (OS and/or data disks).
2. PVCs using managed disks (which will require having the machine running OS (and any pre attached data disk ) as managed disks . 

Currently acs- engine supports both managed and unmanaged disks. But K8S supports only unmanaged PVC (support for managed PVC will come in 1.7) . If you are planning to run something such as ClusterFS then you probably looking for pre-attached data disks (using managed or un managed). The trick is, if you created managed VMs you will only be able to add managed disks (and accordingly managed PVC).

**Comment by seanknox** [comment]
Closing due as I believe this has been answered; feel free to re-open if needed.
