### ISSUE TITLE
Swarm Mode configuration fails

### ISSUE THREAD

**Issue by benformosa** [Azure/acs-engine#524]
I seem to have an issue when deploying swarm mode with a custom VNET.

The VM extension deployment times out because the `configure-swarmmode-cluster.sh` fails at the command `hostname -i`.

**Comment by amanohar** [comment]
@benformosa , I just tried deploying a Swarm Mode cluster in a custom VNET and it worked as expected. I used subnets: 11.0.0.0/16 and 172.15.0.0/24 for agent and master respectively.

Can you provide more details on the error you were running into and the API model you used to generate your template?

**Comment by benformosa** [comment]
Hi, thanks for looking at this, and apologies if I've wasted your time.

I modified the generated template to set custom DNS servers. This may have worked for me previously when deploying with a single master, instead of 3.

Removing this modification allows the swarm to be configured correctly.

You can call this a duplicate of #308. You can probably delete PR #525 as well.

Thanks again,
Ben
