### ISSUE TITLE
Official docker image please?

### ISSUE THREAD

**Issue by ppanyukov** [Azure/acs-engine#526]
Hello, wouldn't it be nice to have an official docker image of this on docker hub, rather than requiring people to clone repo and invoke some scripts to build image, and *then* invoke `make` in the container.

Would be so nice if we could just `docker pull azure/acs-engine`.

**Comment by avaranovich** [comment]
it is not a single docker image. In fact, if you don't need to customize acs engine, just go into your Azure portal, and search for Azure Container Service. This way you don't need to build anything custom yourself, and can just provision a cluster.

**Comment by rjtsdl** [comment]
@ppanyukov , just add some info.

Not sure if you are aware, you can do `make devenv` at the root after you cloned the repo.
It created the needed dev environment as a docker image, and then attach your repo as volume. 
To access to the acs-engine binary, you need another `make build`.

Just want to make sure, you don't miss this.
Thx

**Comment by seanknox** [comment]
👍 to what everyone has said here. Official releases of acs-engine are in the works.

**Comment by kaskavalci** [comment]
On Azure portal I cannot specify the Kubernetes version. From what I see online, only way to create 1.6.2 cluster is to clone this repository and follow https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md guide. Is that right?

**Comment by amanohar** [comment]
ACS RP (service) does not allow user to choose orchestrator version. This is a newly added field (within the last month) and is supported in ACS Engine only. Right now the only way to create K8s 1.6.2 is using ACS Engine.
