### ISSUE TITLE
Unable to mount the CIFS share in the ACS/DCOS cluster

### ISSUE THREAD

**Issue by mmisztal1980** [Azure/acs-engine#527]
I'm trying to follow the documentation outlined [here (DCOS/ACR)](https://docs.microsoft.com/en-us/azure/container-service/container-service-dcos-acr) and [here (CIFS share)](https://docs.microsoft.com/en-us/azure/container-service/container-service-dcos-fileshare).

While iterating over the mesos cluster nodes, I'm supposed to mount the CIFS share using the scripts provided in the documentation.

The failing line is: ```ssh `whoami`@$line -o StrictHostKeyChecking=no -i yourPrivateKeyFile < ./cifsMount.sh```

Each time I'm getting a:

```mount error(13): Permission denied```

Please advise, it's a blocking issue for me.

**Comment by amanohar** [comment]
Can you try running the command as a super user/in sudo mode?

**Comment by mmisztal1980** [comment]
if I run it in sudo mode, it's all good, however the documentation implies that I'm ssh'ing into an array of machines and launching a local script remotely - can I ensure that sudo is propagated somehow?

**Comment by JackQuincy** [comment]
I'd say if it works then it propagated. If not I'd switch your command to include sudo, `ssh `whoami`@$line -o StrictHostKeyChecking=no -i yourPrivateKeyFile < sudo ./cifsMount.sh`

**Comment by anhowe** [comment]
closing since Jack presents solution above.  Please re-open if you still have outstanding questions
