### ISSUE TITLE
After deploy using acs-engine az acs not recognize the cluster

### ISSUE THREAD

**Issue by lshahar** [Azure/acs-engine#528]
After deploy Kubernetes I have try to use az cli to manage the cluster and scale up, but the cluster not found under 'acs list' command.
$ az acs list
[]

**Comment by amanohar** [comment]
az acs command works for a cluster created by Azure Container Service: https://azure.microsoft.com/en-us/services/container-service/ and will not work with a cluster created with ACS Engine since there is no ACS resource in this case.
