### ISSUE TITLE
k8s: Routing via Express Route

### ISSUE THREAD

**Issue by avaranovich** [Azure/acs-engine#530]
I have a k8s cluster set up in Azure environment that has Express Route in place. I need to be able to communicate with the internal system via Express Route.

Kubernetes is deployed by using a default VNet template.

My POD can't reach the IP _192.87.126.210_. 
If I try to reach just from normal VM, it works of course.

Is there some configuration required on the **route table** to facilitate the communication between PODs and "on-prem" resources?

**Comment by JackQuincy** [comment]
@colemickens Have we got this working with express route. I know we have done things with VNET peering, but I don't know about express route.

**Comment by colemickens** [comment]
Yes, per numerous other issues, the route table needs to be mirror, the non-masquerade-cidr flag needs to be updated, or there needs to be an iptable rule added. There are other issues about this.

**Comment by colemickens** [comment]
We should document this.

**Comment by avaranovich** [comment]
Indeed would be good to have this documented.
Meanwhile, do you have any pointers on where this **an iptable rule added** should be done?
Do I need to configure kube-proxy on each node? Or there is a more straightforward way to do this on the running cluster?

**Comment by shawnmost** [comment]
Any Update on this. with what steps are needed. I have been looking at the same thing.

**Comment by avaranovich** [comment]
@colemickens would you advise us on the particular steps?
