### ISSUE TITLE
Containers do not talk to each other on same host via service IP

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#539]
#486 introduced flags --iptables=false --ip-masq=false to docker, and this resulted in a case where pods on the same node, do not talk to each other via the service IP.  They talk via their pod ips, but not through the service IP.

To repro:
1.	Deploy a Kubernetes cluster with 1 agent
2.	Deploy an nginx service with 2 pods.
3.	Exec into the pod and try to curl to service, and you will notice it will hang 50% of the time.

**Comment by rocketraman** [comment]
I'm pretty sure this is the same issue I described here: https://github.com/Azure/acs-engine/issues/493#issuecomment-296732825.

As per that comment, I believe this can be fixed by ensuring that the `br_netfilter` is loaded on the master and agent nodes -- loading it on my nodes fixed this problem, without removing `--iptables=false --ip-masq=false` from the docker daemon.

**Comment by JackQuincy** [comment]
I have confirmation that this was fixed with my PR from different sources.[#540](https://github.com/Azure/acs-engine/pull/540)

**Comment by rocketraman** [comment]
@JackQuincy But did you see my note? Is the "better" fix to add the `--iptables=false --ip-masq=false` arguments back to the Docker daemon, OR to modify the system to ensure the `br_netfilter` module is loaded and leave those arguments off?

**Comment by JackQuincy** [comment]
I'm not sure I wasn't investigating. @anhowe did you see the `br_netfilter` suggestion in your investigation?

**Comment by rocketraman** [comment]
@JackQuincy @anhowe I'm reasonably certain that adding those two parameters to the docker daemon is only *indirectly* fixing the problem by causing docker to load the `br_netfilter` module.

**Comment by anhowe** [comment]
@rocketraman - Jack's change is to mitigate the issue.  I have filed #573 for the longer term fix.  PR's are welcome.
