### ISSUE TITLE
Document the Storage Account Level for Attached Disks

### ISSUE THREAD

**Issue by bearrito** [Azure/acs-engine#542]
It is not obvious from the examples how to declare the disks level for a agent pool.

In particular how to indicate whether the disks are premium or standard

https://docs.microsoft.com/en-us/azure/storage/storage-premium-storage

**Comment by JackQuincy** [comment]
I believe this comes down to the VM Size. Here is a chart the chart of all sizes. https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general 
And from the page you linked it states:

> Premium Storage supports VM disks that can be attached to specific size-series VMs. Premium Storage supports DS-series, DSv2-series, GS-series, and Fs-series VMs

So if you want premium disks use the sizes that support it. I did have to link two pages though so we could update the documentation to state that. 

In code you can find the definitive list at 
%repo root%\src\github.com\Azure\acs-engine\pkg\acsengine\azureconst.go.GetSizeMap()

**Comment by seanknox** [comment]
@bearrito Closing as I believe your question has been answered. Feel free to re-open if needed.
