### ISSUE TITLE
Access to pod from external system in same VNET of Kubernetes cluster

### ISSUE THREAD

**Issue by carlosmkb** [Azure/acs-engine#549]
Hi,
I have a Kubernetes cluster with calico and created an ippool with pods address CIDR as mentioned in #439  
With this configuration I can access to external systems from the pods, but cannot access directly to pods (10.244.x.x) from an external system in the same vnet.
There is any solution for this requirement?

**Comment by JackQuincy** [comment]
@simonswine @colemickens Do either of you know the solution to this?

**Comment by radu-matei** [comment]
Currently dealing with the same (as in trying to access cluster services from other service in the same VNET) situation. Is there any answer for this?
