### ISSUE TITLE
CNI downloads aren't versioned?

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#556]
I'm trying to understand this:

```
# Mirror from https://github.com/Azure/azure-container-networking/releases/tag/$AZURE_PLUGIN_VER/azure-vnet-cni-linux-amd64-$AZURE_PLUGIN_VER.tgz
downloadUrl https://acs-mirror.azureedge.net/cni/azure-vnet-cni-linux-amd64-latest.tgz | tar -xz -C $CNI_BIN_DIR
```

`acs-mirror` looks like a CDN over storage rather than a passthrough like `acs-docker`.

Does GitHub not allow Azure CDN to sit on top like gcr.io/apt.dockerproject.org does?

**Comment by colemickens** [comment]
@dmitsh

**Comment by dmitsh** [comment]
@colemickens @seanknox Indeed acs-mirror is a storage-based CDN. We will be keeping all available CNI versions there. By default the latest version is used, unless the version is explicitly specified.

**Comment by seanknox** [comment]
Hey Dmitry, that's wonderful. What is the URL structure to specify a specific version from the CDN?

**Comment by dmitsh** [comment]
Currently we would need to change URL itself in acs-engine. I will take an action item to make it a parameter.

**Comment by seanknox** [comment]
Can we take this off your plate to implement?

**Comment by dmitsh** [comment]
certainly

**Comment by colemickens** [comment]
Bump on this, given this issue/comment: https://github.com/Azure/azure-container-networking/issues/76#issuecomment-339123049

**Comment by mrosterm** [comment]
Can this be closed?
