### ISSUE TITLE
Master VMSize A V2

### ISSUE THREAD

**Issue by itaysk** [Azure/acs-engine#559]
It seems that the entire A v2 series is not whitelisted for Master VMSize, but it is for agent pools. Old A series if available for both.
Is this on purpose?

**Comment by JackQuincy** [comment]
@shrutir25 @anhowe

**Comment by anhowe** [comment]
this is by design.  Master's need more cores and memory.  Documented in code here: https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/Get-AzureConstants.ps1#L44-L45.
