### ISSUE TITLE
No "role" label on Windows nodes

### ISSUE THREAD

**Issue by wenwu449** [Azure/acs-engine#563]
Get nodes fomr a cluster with both Linux nodes and Windows nodes:
`kubectl get nodes --show-labels
NAME                        STATUS                     AGE       LABELS
35970acs9020                Ready                      5d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=windows,kubernetes.io/hostname=35970acs9020
35970acs9021                Ready                      5d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=windows,kubernetes.io/hostname=35970acs9021
35970acs9022                Ready                      5d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=windows,kubernetes.io/hostname=35970acs9022
35970acs9023                Ready                      5d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=windows,kubernetes.io/hostname=35970acs9023
35970acs9024                Ready                      5d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=windows,kubernetes.io/hostname=35970acs9024
35970acs9025                Ready                      5d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=windows,kubernetes.io/hostname=35970acs9025
k8s-agentpool1-35970643-0   Ready                      5d        agentpool=agentpool1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=1,kubernetes.io/hostname=k8s-agentpool1-35970643-0,reserved=gateway,role=agent
k8s-agentpool1-35970643-1   Ready                      5d        agentpool=agentpool1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=0,kubernetes.io/hostname=k8s-agentpool1-35970643-1,reserved=gateway,role=agent
k8s-master-35970643-0       Ready,SchedulingDisabled   5d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=0,kubernetes.io/hostname=k8s-master-35970643-0,role=master
`

All Linux nodes have "role" label but Windows nodes do not have it.

**Comment by JackQuincy** [comment]
@JiangtianLi

**Comment by JiangtianLi** [comment]
It looks like --node-labels is not passed to Windows kubelet. Will come up with a fix.

**Comment by CecileRobertMichon** [comment]
@JiangtianLi any update on this?

**Comment by JiangtianLi** [comment]
@CecileRobertMichon Not yet. Will revisit. Please assign to me.

**Comment by JiangtianLi** [comment]
@JamesEarle Haven't got chance to work on it. Feel free to chime in.
