### ISSUE TITLE
Ability to set sourceAddressPrefix and sourcePortRange for incoming SSH and TLS connections

### ISSUE THREAD

**Issue by marc-sensenich** [Azure/acs-engine#566]
I have a use case to limit the sourceAddressPrefix and sourcePortRange for incoming connections to the created NSG. For this case, I would like to be able to define this in the cluster configuration file to parameterize these changes.

@bearrito

**Comment by bearrito** [comment]
Our need for this is driven by NETSEC requirements.

We would like to limit 22 access to our bastion box and/or limit 443 access to our set of static corporate ips

**Comment by JackQuincy** [comment]
I'm guessing this isn't high on the ACS team radar today. So if you want the feature we would need to have a design discussion here and if we can agree then you or someone else in the community could pick up the work to push this into ACS Engine

**Comment by marc-sensenich** [comment]
That works out for me. The initial design I propose would be adding additional properties to the cluster definitions for configuring  sourceAddressPrefix and sourcePortRange in the masterProfile for the available protocols in DC/OS and Kubernetes. Where sourceAddressPrefix and sourcePortRange would be valid values per the constraints set for these in NSGs. 

```json
{
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2",
      "securityRules": {
          "ssh": {
               "sourceAddressPrefix": "",
               "sourcePortRange": ""
          },
          "tls": {
               "sourceAddressPrefix": "",
               "sourcePortRange": ""
          },
          "rdp": {
               "sourceAddressPrefix": "",
               "sourcePortRange": ""
          }
      }
    }
}
```

**Comment by JackQuincy** [comment]
For where we are today this feels to niche to make it into our API model. So we won't be taking this change at this time. The way I would do this would be to add the rules myself after deployment. then to remove the NSG from the template anytime I was updating the cluster.

**Comment by bearrito** [comment]
That is the approach we took.  It's unfortunate because it adds to operator overhead.

I'm quite sure others work in audited environments were exposing important parts of the management api to the Internet isn't allowed and so everyone will have to replicate the above steps.
