### ISSUE TITLE
k8s: Remote client IP when using Azure Load Balancer is incorrect

### ISSUE THREAD

**Issue by dbarentine** [Azure/acs-engine#570]
I'm getting the wrong client IP in services that use an Azure LoadBalancer for incoming traffic.

Current setup:
Kubernetes (Linux nodes) deployed through Azure Portal. Currently k8s v1.5.3
Deployed echoheader app and add service of Type: LoadBalancer

With that setup once I have a public IP from the LB I can hit the application but I end up with a private IP address on the k8s network instead of the remote client IP address.

This is the results from the echoheader app:
CLIENT VALUES:
client_address=10.244.1.1
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://104.45.232.229:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding=gzip, deflate, sdch
accept-language=en-US,en;q=0.8
connection=keep-alive
host=104.45.232.229
upgrade-insecure-requests=1
user-agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
BODY:
-no body in request-

**Comment by JackQuincy** [comment]
This is a dup to this issue, https://github.com/Azure/ACS/issues/8 You need to add an annotation to the service to get the source IP. See this link for details https://kubernetes.io/docs/tutorials/services/source-ip/

**Comment by dbarentine** [comment]
@JackQuincy Thanks that was it. Once the annotation was added everything works as expected.
