### ISSUE TITLE
Why does --iptables=false --ip-masq=false break interpod connectivity on same host?

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#573]
#486 introduced a regression where interpod connectivity on the same host is broken.  #539 and #540 reverted this change as an immediate mitigation.

This Issue is to find a longer term fix where we can add `--iptables=false --ip-masq=false` back to /etc/systemd/system/docker.service.d/exec_start.conf.

@rocketraman has suggested the longer term fix for this issue in the discussion of #539.

**Comment by seanknox** [comment]
Disabling iptables for Docker causes lots of issues (flannel breaks for example) so my hunch is this probably not the way forward. We'll need to revisit this.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
