### ISSUE TITLE
Protect docker daemon using TLS for Swarm and Swarmmode.

### ISSUE THREAD

**Issue by iphilpot** [Azure/acs-engine#575]
This change would allow customers to connect from client to ACS instance of swarm/swarmmode using TLS, which is a published best practice. Currently customers have to create an SSH tunnel to execute Docker commands on the remote host. The following are proposed changes to ACS-Engine to enable this functionality.

Current Customer/Partner example: [CodeShip CI/CD](https://github.com/codeship-library/azure-deployment/blob/acs-swarm/sshtunnel/ssh-tunnel.sh)

I may have missed a couple of things during my investigation, but this should be the highlights. 

### Proposed Changes to engine:
| Pkg	| File	| Method/Struct	| Change |
|-------|-------|---------------|--------|
|Acsengine	|Defaults.go	|certGenerationRequired	|Swarm/SwarmMode return true|
|Api/vlabs	|Types.go	|CertificateProfile	|Change cert struct to allow for both K8 and swarm certs|
|Acsengine	|Pki.go	|CreatePki	|extraFQDNs if k8|
|Acsengine	|Pki.go	|CreatePki	|If K8 gen certs per struct/if swarm gen certs per struct|

### Proposed Changes to provision scripts (swarm/swarmmode):
Script locations: /opt/azure/containers/

| Template name | Script name | Changes |
|------------------|---------------|----------|
| agentCustomScript | configure-swarm-cluster.sh & configure-swarmmode-cluster.sh | Save cert/keys & configure TLS startup |

### Proposed Changes to example ClusterDefinitionFiles for Swarm/Swarmmode:
https://github.com/Azure/acs-engine/tree/master/examples

  - Add TLS port: 2376

### Proposed changes to documentation: 
These docs will need to be updated:
  1. https://github.com/Azure/acs-engine/blob/master/docs/swarm.md
  2. https://github.com/Azure/acs-engine/blob/master/docs/swarmmode.md

  - Update Architecture image to reflect TLS port
  - Step 2 remove ssh tunnel 
  - Add client TLS setup:
		$ mkdir -pv ~/.docker
        $ cp -v {ca,cert,key}.pem ~/.docker
        $ export DOCKER_HOST=tcp://$HOST:2376 DOCKER_TLS_VERIFY=1

**Comment by amanohar** [comment]
Ack @tripdubroot. I will review this soon.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
