### ISSUE TITLE
devenv.sh fails to mount Docker bin on OS X

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#577]
Howdy folks. `scripts/devenv.sh` now fails trying to mount `/usr/local/bin/docker` in the container. 

```
++ which docker
++ pwd
+ docker run -it --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /usr/local/bin/docker:/usr/bin/docker:ro -v /Users/seknox/src/go/src/github.com/azure/acs-engine:/gopath/src/github.com/Azure/acs-engine -w /gopath/src/github.com/Azure/acs-engine acs-engine /bin/bash
docker: Error response from daemon: Mounts denied:
The path /usr/local/bin/docker
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

This happens if `/usr/local/bin/docker` is a symlink, which is the case if the docker client is installed via `homebrew` or via Docker for Mac. A temporary workaround is to copy an actual binary to `/usr/local/bin/docker`. This isn't a very good (or lasting) solutions because:
- It breaks management of the docker client via Homebrew, if installed that way
- The Docker for Mac client overwrites `/usr/local/bin/docker` every time it starts up, so any binary tweezing will need to be repeated.

@lachie83 cc'ing you in case you have any ideas on this...

**Comment by rjtsdl** [comment]
@seanknox , can you try with the latest? What i noticed is, this line `-v /usr/local/bin/docker:/usr/bin/docker:ro ` doesn't exist in the scripts/devenv.sh file.

**Comment by seanknox** [comment]
Fixed in HEAD. Thanks @rjtsdl!
