### ISSUE TITLE
Scaling-up SwarmMode cluster - nodes won't show up on master server

### ISSUE THREAD

**Issue by srigi** [Azure/acs-engine#578]
I created small cluster using `acs-engine` in `SwarmMode`. Everything gets created correctly and I can see all initial agent nodes by running `docker node ls` on master node.
Then I scaled *virtual-machine-scale-set* instances up. No errors too.

How are the new node added to the swarm? I cannot see them on master nodes list.

**Comment by amanohar** [comment]
@srigi , can you share the following logs from the node that does not show up when you list:
- /var/log/azure/cluster-bootstrap-postinstall.log
- /var/log/azure/cluster-bootstrap.log

Also, does Portal show that the new VMSS instance was provisioned successfully?

**Comment by srigi** [comment]
Hello @amanohar, thanks for reply.
I must apologize, nodes indeed showed up, I just have to wait little longer. I cannot express how awesome this is, I was thinking that after scaling *virtual-machine-scale-set* there is some provisioning work to do from my side. But this automation of including new nodes into the swarm is great.

Once again sorry for false warning.

**Comment by rjtsdl** [comment]
Remove bug label, and close it, as it is false alarm.
