### ISSUE TITLE
Using kubernetes-hybrid only one Windows node is created

### ISSUE THREAD

**Issue by SitoCH** [Azure/acs-engine#586]
Hello,
I'm trying to deploy an hybrid cluster with Kubernetes but, even if all the VMs are created correctly only the last Windows node join the cluster. Can you help me troubleshooting the issue?

My JSON file is the following:
```
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes"
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "dns-prefix",
            "vmSize": "Standard_A2"
        },
        "agentPoolProfiles": [{
                "name": "linuxpool",
                "count": 3,
                "vmSize": "Standard_A2",
                "availabilityProfile": "AvailabilitySet"
            },
            {
                "name": "windowspool",
                "count": 3,
                "vmSize": "Standard_A2",
                "availabilityProfile": "AvailabilitySet",
                "osType": "Windows"
            }
        ],
        "windowsProfile": {
            "adminUsername": "azureuser",
            "adminPassword": "complexpwd"
        },
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": {
                "publicKeys": [{
                    "keyData": "ssh-key"
                }]
            }
        },
        "servicePrincipalProfile": {
            "servicePrincipalClientID": "id",
            "servicePrincipalClientSecret": "secret"
        }
    }
}
```

As you can see there should be 6 nodes (3 linux and 3 windows) and a master but on kubectl two Windows nodes are missing. The strange thing is that if a deploy 2 Windows nodes instead of 3 I can see only 1 node too.

Thank you

Sito

**Comment by JackQuincy** [comment]
This is very strange I haven't heard of others running into this that are running hybrid clusters. If you go to resources.azure.com you should be able to find the resource group you deployed into then go into Microsoft.Compute/virtualMachines. In there you hsould see 1 master node, your linux nodes and then some nodes that have #####acs9#### or something close to that, and those will be your windows nodes. Is there only one or are there more?  I'm just trying to figure out if the bug is in the resources part of the template or the custom script.

**Comment by SitoCH** [comment]
Hi,
thank you for your help. I can see the 3 windows VM and all the three with:

```
"provisioningState": "Succeeded"
```
I found an anomaly under *Microsoft.Network* -> *routeTables*, there I can see the master, 3 linux VM and only one Windows VM...

**Comment by SitoCH** [comment]
There seem to be some kind of a racing condition or something like that. I just deleted everything and deployed the same template again and this is the new situation: 1 master, 3 linux nodes, 1 windows node ok, 1 missing and 1 not ready...

![schermata 2017-05-10 alle 07 34 42](https://cloud.githubusercontent.com/assets/498887/25884524/4becba64-3553-11e7-8e61-3d6ad05893d1.png)

**Comment by SitoCH** [comment]
I noticed that sometimes the Docker service is stopped on the node, manually starting it seems to fix everything. I'm closing the issue since I no longer have to problem.
