### ISSUE TITLE
processing extension 'cse0' provisioning fails on Kubernetes master

### ISSUE THREAD

**Issue by janus-christensen** [Azure/acs-engine#587]
Hello,

I am attempting to create a Container Service on Azure with a Kubernetes Orchestrator using acs-engine. I have created a JSON (kubernetes.json) that I run through _acs-engine_, which produces the attached azuredeploy.json and azuredeploy.paramters.json files. These I deploy in PowerShell with

```
.\Deploy-Template.ps1 -TemplateFile 'azuredeploy.json' -TemplateParametersFile 'azuredeploy.parameters.json' -ResourceGroupName 'op-container-test'
```

The deployment fails with the following error:
```
Template deployment returned the following errors:
12:11:52 - Resource Microsoft.Compute/virtualMachines/extensions 'k8s-master-41889334-0/cse0' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\"."
      }
    ]
  }
}'
12:11:52 - VM has reported a failure when processing extension 'cse0'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1".
```
When I ssh to the master VM and have a look in at the CommandExecution.log in /var/log//azure/Microsoft.Azure.Extensions.CustomScript/2.0.3/ and this is what it looks like:

```
azureuser@k8s-master-41889334-0:~$ ll /var/log/azure/Microsoft.Azure.Extensions.CustomScript/2.0.3
ls: cannot access '/var/log/azure/Microsoft.Azure.Extensions.CustomScript/2.0.3/..': Permission denied
ls: cannot access '/var/log/azure/Microsoft.Azure.Extensions.CustomScript/2.0.3/CommandExecution.log': Permission denied
ls: cannot access '/var/log/azure/Microsoft.Azure.Extensions.CustomScript/2.0.3/.': Permission denied
total 0
d????????? ? ? ? ?            ? ./
d????????? ? ? ? ?            ? ../
-????????? ? ? ? ?            ? CommandExecution.log
```
Obviously, I can't see what is in the log:
```
azureuser@k8s-master-41889334-0:~$ tail /var/log/azure/Microsoft.Azure.Extensions.CustomScript/2.0.3/CommandExecution.log
tail: cannot open '/var/log/azure/Microsoft.Azure.Extensions.CustomScript/2.0.3/CommandExecution.log' for reading: Permission denied
```

Does anybody have a clue as to might be wrong?

Thank you!

[kubernetes.json.txt](https://github.com/Azure/acs-engine/files/986214/kubernetes.json.txt)
[azuredeploy.json.txt](https://github.com/Azure/acs-engine/files/986224/azuredeploy.json.txt)
[azuredeploy.parameters.json.txt](https://github.com/Azure/acs-engine/files/986223/azuredeploy.parameters.json.txt)

**Comment by Camsteack** [comment]
As far as I know you might have an issue with your service principal.
Can you verify that your `servicePrincipalClientID` and `servicePrincipalClientSecret` are correct and that it has the proper permissions on your subscription ?

**Comment by SitoCH** [comment]
I had the same issue yesterday and, as @Camsteack said, it was related to a badly configured *servicePrincipalClientID* and *servicePrincipalClientSecret*.

**Comment by janus-christensen** [comment]
Yes, I have just confirmed it is the case here too. I fixed the servicePrincalClientID and servicePrincipalClientSecret values and now it deploys without errors.

Thank you for the help!
