### ISSUE TITLE
Support for docker 1.13 swarm-mode?

### ISSUE THREAD

**Issue by ivanthelad** [Azure/acs-engine#589]
Currently docker engine  in SwarmMode is pinned to 1.12.x 
is there plans to have 1.13 supported for acs-engine swarm mode. 
https://github.com/Azure/acs-engine/blob/master/parts/configure-swarmmode-cluster.sh#L19 

or is acs-engine waiting on support 1.13 support in kubernetes first?
https://github.com/Azure/acs-engine/pull/327

**Comment by JackQuincy** [comment]
It is running latest version of docker engine. It is pinned to 1.12 for docker compose. Which supports all of the swarm mode functionality. And will happily accept pull requests to use new versions once they are blessed as stable.

**Comment by amanohar** [comment]
Adding to Jack's point. ACS Engine used the latest version of docker engine. Here is an example of version being used on a cluster created last month:

Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
