### ISSUE TITLE
K8s Agent Cannot Use Standard_F1

### ISSUE THREAD

**Issue by robbiezhang** [Azure/acs-engine#591]
Standard_F1 is defined in GetKubernetesAgentAllowedSizes,
https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/azureconst.go#L324
but it doesn't exist in GetSizeMap:
[https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/azureconst.go#L560](url)

The ARM template is generated successfully, but it failed to process.

> The language expression property 'Standard_F1' doesn't exist. available properties are ...

**Comment by JackQuincy** [comment]
@shrutir25 was this something we meant to do?

**Comment by anhowe** [comment]
@robbiezhang Standard_F1 is supported for Agents but not for Masters.  Masters require >= 2 cores.

**Comment by anhowe** [comment]
replace https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/Get-AzureConstants.ps1#L264-L276, with all sizes

**Comment by anhowe** [comment]
@shrutir25 - please note the above

**Comment by robbiezhang** [comment]
This issue is for agent pool. I use Standard_F1 in the agent pool, and generate the ARM template. The error happens when executing the template.

**Comment by SaaldjorMike** [comment]
I believe this one can be closed.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
