### ISSUE TITLE
Unable to resize cluster after creation

### ISSUE THREAD

**Issue by dsemarketer** [Azure/acs-engine#597]
In the latest acs-engine pull that I did yesterday, I have a fully functional cluster. But when I resize the master from a Standard_D2_v2 to a Standard_D1_v2, Kubelet will not start with the following message all over the place:

dial tcp 10.254.31.5:443: getsockopt: connection refused

Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig.  This is most likely due to lack of PodCIDR

I noticed, that now for some reason the VM size is being pushed as a label and coded in in /opt/azure/containers/kubelet.sh. Even changing the label in the kubelet.sh doesnt fix this (although it does change the flag on kubelet to the right size.

The code change looks like its from this commit - https://github.com/Azure/acs-engine/pull/581

Is there somewhere else that's hardcoding the VM size causing the master to be functional only with the size the vm was when initially created?

**Comment by JackQuincy** [comment]
If you revert #581 in a fork it might work.  And I would be curious as to what it would take to get this working, but today resizing the master vm is a none goal for acs engine clusters. 

A little background #581 was about mitigating throttling from ARM that was happening in large clusters/subscriptions with lots of clusters in the subscription.

**Comment by anhowe** [comment]
#626 has fixed this
