### ISSUE TITLE
Windows Server 2016 Nano

### ISSUE THREAD

**Issue by SitoCH** [Azure/acs-engine#598]
Hello,
is it possibile to use the Nano edition instead of the full one on a Windows node?
It would really decrease the overhead on the node but I don't know if there are other limitations...

Thanks

Sito

**Comment by rjtsdl** [comment]
@JiangtianLi

**Comment by JackQuincy** [comment]
@anhowe  might also know. I do know getting k8s running on the Windows image working properly was nontrivial and required quite a bit of coordination with the windows team and currently we are patching a bug in windows at run time that hasn't made it into their official images. So I'm guessing that switching to Nano edition wouldn't be trivial. Though it definitely would be nice.

**Comment by PatrickLang** [comment]
Running containers based on microsoft/windowsservercore will require --isolation=hyperv. This means nested virtualization is required and I can't speak to how that will be supported on Azure.

**Comment by anhowe** [comment]
Per @PatrickLang we will required nested hyper-v which is not currently support on Azure.  Closing issue, and we can re-open once nested hyper-v is supported.

**Comment by sebgod** [comment]
D-Series v3 VMs supported nested Hyper-V
