### ISSUE TITLE
Selecting Kubernetes version - 1.5.7 planned?

### ISSUE THREAD

**Issue by DonMartin76** [Azure/acs-engine#601]
Hello,

We are just running into some trouble with our 1.5.3 cluster (currently provisioned by `az acs create`, but we'll probably move to `acs-engine` soon to get more flexibility) in that we tend to get a lot of `wc` zombie processes on the Kubernetes agents. This seems to be related to https://github.com/kubernetes/kubernetes/issues/38894 which is fixed in 1.5.6.

I tried creating a template with `orchestratorVersion` set to 1.5.7, but apparently only a few (checked: 1.5.3, 1.6.0 and 1.6.2) are supported.

Seeing the changes in RBAC with 1.6.x, I am reluctant to move to 1.6 just yet (haven't tried it yet), but would love to have the most recent 1.5 release. Is this something you are planning to do, or will all new releases only be 1.6 and upwards?

Best regards,
Martin

**Comment by JackQuincy** [comment]
We don't have any immediate plans to add support for 1.5.6.  But PRs are welcome.

**Comment by DonMartin76** [comment]
OK, tried out to just bump some versions to suitable images, seems to work. Got a 1.5.7 cluster up and running. Will create a PR, hopefully.

**Comment by DonMartin76** [comment]
See https://github.com/Azure/acs-engine/pull/602

**Comment by JackQuincy** [comment]
Thanks I've reached out to @JiangtianLi  to answer your question about windows then after that we should be able to merge it.

**Comment by DonMartin76** [comment]
Thanks a lot for your support on this, the PR has been merged, it's now possible to spin up a 1.5.7 cluster. Awesome! Thanks!

Closing.
