### ISSUE TITLE
How to spin up K8s version 1.6.2  ?

### ISSUE THREAD

**Issue by writeameer** [Azure/acs-engine#606]
Hello there,

I've been following the Kubernetes [walkthrough](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md) and was just curious if version 1.6.2 worked ? The sample at https://github.com/Azure/acs-engine/blob/master/examples/kubernetes.json seems to specify 1.6.2:

```
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.6.2"
    },
```

However, the generated artefacts under the "_output" folder appear to be a different version. The generated azuredeploy.parameters.json file has the following:

```
  "kubernetesHyperkubeSpec": {
    "value": "gcr.io/google_containers/hyperkube-amd64:v1.5.3"
  },
```

It's also what ends up being spun up - a cluster with server version 1.5.3.  Can someone please help ? Thank you.

**Comment by amanohar** [comment]
I just tried this scenario from the build on ACS Engine latest and I get the expected output:
  "kubernetesHyperkubeSpec": {
    "value": "gcrio.azureedge.net/google_containers/hyperkube-amd64:v1.6.2"
  }

Was the output folder that contains all the generated files already present and you changed the version to 1.6.2 and reran ACS Engine? Can you try deleting the output folder and try again?

**Comment by writeameer** [comment]
Thanks @amanohar . I was definitely using an older version of the code. The older version seemed to create an output folder with subfolders called "Kubernetes-<number>", whereas the newer version creates an output folder with the a sub folder named after the "dns-prefix".

Kubernetes 1.6.2 is up and running and workes like a charm. 

Thank you so much
