### ISSUE TITLE
HA Master lose connection on ILB restart due to kubernetes issue 41184

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#608]
The agents may report NodeNot Ready due to single master restart, or HA Masters on ILB restart. 

This is to track the following kubernetes issue: https://github.com/kubernetes/kubernetes/issues/41185.

Per @colemickens, this is a related issue: https://github.com/kubernetes/kubernetes/issues/41916#issuecomment-299177721.

To avoid this, an alternative solution is multi-host client: https://github.com/kubernetes/kubernetes/pull/40674.

**Comment by seanknox** [comment]
To add more color on this, one person's research indicates the delay is due to the way the Linux kernel handles dead TCP connections: https://github.com/kubernetes/kubernetes/issues/41916#issuecomment-312428731
