### ISSUE TITLE
Missing Azure Container Service Item

### ISSUE THREAD

**Issue by sprgn** [Azure/acs-engine#610]
We've built a kubernetes cluster with our vnet using acs-engine/examples/vnet/kubernetesvnet.json template.  However, after everything got spun up (vm's, availability sets, nic's, etc.), there was no Azure Container Service object created.  What did we miss?

**Comment by amanohar** [comment]
This is expected. If a cluster is created using ACS Engine then compute, storage, networking resources are deployed but an ACS resource is not created. ACS resource will only be created if you used https://azure.microsoft.com/en-us/services/container-service/ APIs to create the cluster.

**Comment by sprgn** [comment]
Thank you.
