### ISSUE TITLE
Pre-built docker image with just acs-engine?

### ISSUE THREAD

**Issue by DonMartin76** [Azure/acs-engine#619]
Hi there,

Is there/will there be a pre-built docker image which can be used e.g. in build pipelines, which just contains the acs-engine executable?

Asking before I create such a thing myself for our Jenkins pipelines.

Would you accept a PR which contains scripting and/or guidelines on how to build such an image? Or is this nothing you would want to have inside this repo?

**Comment by DonMartin76** [comment]
In the meantime:
https://github.com/Haufe-Lexware/acs-engine-runtime

**Comment by anhowe** [comment]
Great feature @DonMartin76 .  This is related to the work of #55

**Comment by rgardler** [comment]
Hey @DonMartin76 any chance you could

**Comment by DonMartin76** [comment]
I could...?

**Comment by DonMartin76** [comment]
... dance? Sing loudly? Break a leg?
