### ISSUE TITLE
How do I specific multiple users, ssh keys when initiating DC/OS cluster

### ISSUE THREAD

**Issue by skasturi** [Azure/acs-engine#620]
Hello,

When creating the cluster I would like to specify multiple administrator user name and their ssh public keys. How do I do that in the template? 

I see the following in linux profile. Though "ssh" is a list, I am afraid the user name is azureuser and I don't see a way to map one username to one specific sshkey. 

 "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    }

Thanks,
Sasidhar.

**Comment by anhowe** [comment]
Only one username is allowed.  This is passed directly to the underlying virtual machine definition: https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-create-or-update.
