### ISSUE TITLE
Is it possible to add agent pools at a later point of time? 

### ISSUE THREAD

**Issue by skasturi** [Azure/acs-engine#621]
Hello,
      I would like to know how we can add agent pools to an existing cluster DC/OS created using acs-engine. 

Thanks,
Sasidhar.

**Comment by anhowe** [comment]
@skasturi yes, this is supported.  Using the apimodel.json from the output folder, add the extra agent pool and redeploy the template.  Ensure you are using the same ACS-Engine you created the original cluster with, otherwise you will have to trim out the other VM resources.
