### ISSUE TITLE
How do I set mesos configurations when creating a cluster?

### ISSUE THREAD

**Issue by skasturi** [Azure/acs-engine#622]
Hello,
     I am trying to change mesos configurations. Specifically some of the ones defined here: http://mesos.apache.org/documentation/latest/configuration/

Is it possible to define these when creating the cluster using acs-engine? 

Thanks,
Sasidhar.

**Comment by anhowe** [comment]
@skasturi Changing options on DCOS is currently not supported.  PR's are welcome.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.
