### ISSUE TITLE
Kubernetes masters and agents can use up all of ARM's QPS for subscription

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#635]
notes from @yangl900

I think we probably want to solve the problem generically in azure driver, as anyone runs a 200 node cluster can potentially hit this badly at any time. Some ideas:
 
1.	If we can control how frequent we poll the VM status, I think we should make that less frequent. I couldn’t think of a scenario where we want to know master node property change in seconds.
2.	If we cannot control how frequent we poll the VM, can we do VM list instead of individual VM GET? In a 200 node cluster, this is 1 request v.s. 200 requests.
3.	It’s not easy to identify if an request is coming from controller, or kubelet itself, or somewhere else. All request simply have UA “Azure-SDK-for-Go/7.0.1-beta arm-compute/2016-03-30”. We should probably add user agent for different component, it’s much easier on a Livesite analysis. (potentially, x-ms-client-command-name header as well for grouping the actual tasks)
4.	We should really do generic back off on 429s. At least, don’t make things worse.

**Comment by seanknox** [comment]
Hey @anhowe, @jackfrancis and I have been trying to reproduce the ARM throttling symptoms in large clusters with no luck. How/where are you seeing this behavior?

**Comment by anhowe** [comment]
@dmitsh hit this and can say, but you should just be able to deploy a few hundred machines, run containers on everything and a few services, and I believe ARM starts throttling.  If you are not seeing it, try dropping to k8s v1.5.3 (which is what @dmitsh was using).  Perhaps it was fixed in 1.6?  Also, let me show you Kusto, so you can see your IOPs.

**Comment by jdumars** [comment]
An update on this:  we're able to replicate the 429 response codes from ARM at scale.  We're also using Kusto now to help diagnose the issues.  There's no specific work plan initiated yet, but once we have PRs ready to go, I'll link them here so everyone has visibility.

**Comment by seanknox** [comment]
FYI we have upstream improvements to the Azure cloud provider that will help here: https://github.com/Azure/acs-engine/issues/635

**Comment by seanknox** [comment]
Upstream fixes have been committed to Kubernetes HEAD and cherry-picked for v1.6.6. Next step is to enable cloud provider backoff in acs-engine. cc @jackfrancis

**Comment by seanknox** [comment]
Closed via https://github.com/Azure/acs-engine/issues/922. We'll re-open if necessary.
