### ISSUE TITLE
Kubernetes UDP support for Service

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#645]
@colemickens made the following change.  This is to track back porting into 1.6x.  Once this is available, update Dan Lepow for documentation.

 https://github.com/kubernetes/kubernetes/pull/45523.

**Comment by jdumars** [comment]
This will most likely ship in 1.6.5 in approximately 2 weeks.  I will update if I get a specific release time.

**Comment by jompu** [comment]
So this means there would be support for load-balancing UDP traffic? 

Is there currently any way to expose UDP port to public IP address?

**Comment by jdumars** [comment]
FYI this has been merged and should be in 1.6.5.  https://github.com/kubernetes/kubernetes/pull/46174

**Comment by jpoon** [comment]
Awesome. Thanks @jdumars for all the help.

**Comment by jpoon** [comment]
The change was successfully back-ported and included in 1.6.5. This issue can be closed.
