### ISSUE TITLE
Master count limited to 5

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#654]
Hey all, I was curious for the decision to limit masters to a max of 5. I got this when running `make ci`:

`FATA[0000] error parsing the api model: MasterProfile count needs to be 1, 3, or 5`

**Comment by seanknox** [comment]
My guess is this is related to masters and etcd 1) both running on the same VMs and 2) both masters and etcd need odd numbers to reach quorum.

**Comment by anhowe** [comment]
Correct, odd numbers are necessary for the quorum in the consensus ring.  The limit of 5 was chosen because this was sufficient, to handle a multi-thousand node cluster.  We can reconsider 7 or 9, but this has not been an ask so far.
