### ISSUE TITLE
Swarmmode puts master in Pause mode.  Should be a configurable option

### ISSUE THREAD

**Issue by larryms** [Azure/acs-engine#665]
When creating a swarm mode cluster, acs-engine making the assumption that the master should be paused such that when  containers are deployed, none will run on the master.   Ideally, this should be an option in the configuration template.

The setting comes from https://github.com/Azure/acs-engine/blob/master/parts/configure-swarmmode-cluster.sh in this section of code:
```
if ismaster ; then
  echo "Setting availability of master node: '$VMNAME' to pause"
  docker node update --availability pause $VMNAME
fi
```

**Comment by JackQuincy** [comment]
@amanohar can speak more to the reasoning for this, but my understanding is that we did it as the masters aren't behind the agent load balancer

**Comment by larryms** [comment]
Yes, I did see that the masters are not behind the agent load balancer, but if the master is made active, the [swarm ingress routing mesh](https://docs.docker.com/engine/swarm/ingress/) should be able to route to it.

My specific use case:  I'm trying to run [Docker Visualizer](https://github.com/dockersamples/docker-swarm-visualizer), which can only be run on the master.

**Comment by amanohar** [comment]
General design and guiding principle for all ACS RP and ACS Engine clusters is that masters are not set up by default to allow running containers. This is enable separation between manager and worker for manageability, There is no current plan to make this a configurable option but this is an easy change after the cluster is deployed.
