### ISSUE TITLE
[Kubernetes - Windows Worker] Subscription Not Authorized For Image 

### ISSUE THREAD

**Issue by uday31in** [Azure/acs-engine#666]
I am getting following error on Kubernetes (Hybrid) deployment for Windows Worker. Linux Worker and Masters are deploying fine in the Resource Group in West Europe Region:

{
  "error": {
    "code": "SubscriptionNotAuthorizedForImage",
    "target": "imageReference",
    "message": "The subscription is not authorized."
  }
}

I have following in ARM template:

"agentWindowsOffer": "WindowsServer",
"agentWindowsPublisher": "MicrosoftWindowsServer",
"agentWindowsSku": "2016-Datacenter-with-Containers",
"agentWindowsVersion": "2016.0.20170127",

Uday

**Comment by JackQuincy** [comment]
Please see pr #664. The image was vulnerable to wanna cry so the windows team depublished it. We are working with them on improving our channels of communication with them so that we don't have down time like this.

**Comment by JackQuincy** [comment]
Users with older clusters should be okay,  as windows update was turned on and would of been patched it was just the time after deployment until the patching happened that would of been an issue

**Comment by JackQuincy** [comment]
This should be resolved. I'm closing reopen if you can reproduce at head
