### ISSUE TITLE
[Kubernetes - Windows Worker] default 2016-Datacenter-with-Containers image does not work with k8s 1.6

### ISSUE THREAD

**Issue by andyzhangx** [Azure/acs-engine#670]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
deploy Kubernetes 1.6.2 with CLI
(Hybrid) deployment for Windows: master is Linux and agent is Windows

**What happened**:
I have deployed a Kubernetes (Hybrid) deployment for Windows with 1.6.2 with default 2016-Datacenter-with-Containers image in ARM template:
    "agentWindowsPublisher": "MicrosoftWindowsServer",
    "agentWindowsOffer": "WindowsServer",
    "agentWindowsSku": "2016-Datacenter-with-Containers",
    "agentWindowsVersion": "2016.127.20170411",

And then I am getting following error when deploy microsoft/aspnet on k8s cluster with "kubectl run aspnet --image microsoft/aspnet"

kubectl describe pod aspnet-xxx
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  1m            1m              1       default-scheduler                       Normal          Scheduled       Successfully assigned iis-3512527085-gd346 to 29884acs9000
  1m            1s              6       kubelet, 29884acs9000                   Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: docker: failed to parse docker version \"17.03.1-ee-3\": illegal zero-prefixed version component \"03\" in \"17.03.1-ee-3\""

**What you expected to happen**:
aspnet should work well on Windows agent

**How to reproduce it** (as minimally and precisely as possible):
1. deploy a Kubernetes (Hybrid) deployment for Windows with 1.6.2 with default 2016-Datacenter-with-Containers image in ARM template:
    "agentWindowsPublisher": "MicrosoftWindowsServer",
    "agentWindowsOffer": "WindowsServer",
    "agentWindowsSku": "2016-Datacenter-with-Containers",
    "agentWindowsVersion": "2016.127.20170411",
2. kubectl run aspnet --image microsoft/aspnet
3. kubectl describe pod aspnet-xxx

**Anything else we need to know**:
I have tested, 2016-Datacenter-with-Containers image version "2016.127.20170406" works well.

**Comment by JackQuincy** [comment]
Please update to latest acs-engine. We have merged a fix for this. Though 1.6.2 is still having some issues.

**Comment by JackQuincy** [comment]
Okay we patched our k8s zip file for windows and the latest acs-engine should work with 1.6.2 as well. Can you test and verify it is fixed @andyzhangx ?

**Comment by andyzhangx** [comment]
@JackQuincy It's working now, thanks. I will close this issue.
