### ISSUE TITLE
Switch to using recently added udev symlinks for mounting etcd disks

### ISSUE THREAD

**Issue by amanohar** [Azure/acs-engine#676]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Use the recently added udev symlinks instead of /dev/sdc for mounting etcddisk in Kubernetes clusters.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:
Current implementation does explicit mount of  /dev/sdc1 to /var/lib/etcddisk instead of using symlinks which might be error prone and not stable as it takes explicit dependency on /dev/sdc1.

**What you expected to happen**:

Use the recently added udev symlinks instead of /dev/sdc. The kernel device names are not guaranteed to be stable. Use /dev/disk/azure/scsi1/lun0 for the disk attached on lun 0 and /dev/disk/azure/scsi1/lun0-part1 for the first partition on the disk.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
If someone picks this up during cse sync week we might have to revisit to make sure it is still needed and relevant.

**Comment by aheumaier** [comment]
Since a device name (/dev/sdc or /dev/nvme) has to be known cloud-init run time - udev doesnt help here
