### ISSUE TITLE
Identify good Kubernetes functional test candidate to try out w/Ginkgo

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#678]
Functional tests are a mixture of Go and shell scripts. We want to try out using [Ginkgo](https://github.com/onsi/ginkgo) as the test runner for both unit and integration/functional/regression tests, which will make tests easier to write, refactor, and reuse.

acceptance criteria:
- Identify an existing Kubernetes functional test that would be a good candidate to quickly spike on with Ginkgo.
- Lay down Ginkgo boilerplate/setup.

**Comment by jchauncey** [comment]
Acceptance Criteria:

* [ ] Can run the kubernetes suite of tests using ginkgo
* [ ] Add make target for running tests specific to the suite - `make test-kubernetes`
* [ ] Build boilerplate functions for creating cluster from a template
* [ ] Use current json descriptor for provisioning clusters (location and cluster definition)
* [ ] Ability to run suites in parallel (this may just be multiple jobs that call the make target with a given descriptor)
* [ ] Create job that runs these tests in parallel with current bash suite
