### ISSUE TITLE
acs-engine moved to journald from json-file for logs - how to forward to logger?

### ISSUE THREAD

**Issue by DonMartin76** [Azure/acs-engine#689]
**Is this a request for help?**:

yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

hard to tell

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes v1.5.7

**What happened**:

As of fairly recently (at least currently the `az acs create` command line doesn't yet do it), end of March or so, `acs-engine` Kubernetes deployments were changed from using the `json-file` logging plugin to the `journald` Docker logging.

This means that we cannot use e.g. `fluentd` to tail the docker logs anymore, as the `journald` format is binary. Most "solutions" we have found on this topic have been very hacky or clunky at best, or they simply do not work.

Ultimately, we need to be able to ship our logs to Graylog (GELF format), which until now the `fluentd` agent did.

**What you expected to happen**:

Some guidance on how to make log shipping work, using other means than the `oms-agent` (which kinda works, actually!), which is not the desired log sink for us.

**How to reproduce it** (as minimally and precisely as possible):

See above, it's the standard configuration.

**Anything else we need to know**:

Are there plans on extending the documentation on how to ship logs using e.g. `fluentd`, or a similar shipper? To other targets than OMS, that is?

---

Possibly and probably related: https://github.com/kubernetes/kubernetes/issues/24677
This also does not really help: https://kubernetes.io/docs/concepts/cluster-administration/logging/
Maybe the same thing: https://github.com/Azure/acs-engine/issues/574

**Comment by DonMartin76** [comment]
Somewhat related, as this could solve the issue: https://github.com/fluent/fluent-bit/issues/217

**Comment by JackQuincy** [comment]
We are working with the OMS team to get the journal logs into fluentd in the default OMS settings. In the interm you can definitely use json-file. You might want to add a max log size so that you don't run out of hard drive space

**Comment by rjtsdl** [comment]
Closed by #766
