### ISSUE TITLE
headless azure public IP addresses associated to the LB for services

### ISSUE THREAD

**Issue by ferantivero** [Azure/acs-engine#690]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
"very often" after I delete K8s services using kubectl, the allocated Azure Public IP Addresses are not getting dissociated. 

**What you expected to happen**:
If I delete a k8s resource service kind, the Azure Public IP Address associated with gets deleted. So I don't easily reach the max limit allowed. 

**How to reproduce it** (as minimally and precisely as possible):

1. Create a new K8s namespace named prod
2. Create another K8s namespace named dev
3. Create a 2 new K8s services within the new ns prod 
4. Create a 2 new K8s services within the new ns dev (same names as in prod)
5. Delete the services from ns prod and check if the IP Addresses associated with have been deleted. if Yes, repeat the same for dev

P.S.: I'm creating deploy(s), so they get exposed through the services. But not sure if this is required to get this reprod. 

**Anything else we need to know**:
couldn't find any other workaround rather than just delete the whole lb and then proceed with the IP Addresses.  

Thanks,

**Comment by ferantivero** [comment]
most probably the same as in kubernetes/kubernetes/issues/43730

**Comment by JackQuincy** [comment]
@seanknox @colemickens  can either of you confirm above

**Comment by seanknox** [comment]
I believe this is the same upstream kubernetes bug mentioned. Will double-check.

**Comment by seanknox** [comment]
Yep, looks to be the same issue AFAIK.

**Comment by ferantivero** [comment]
1.7 just released http://blog.kubernetes.io/2017/06/kubernetes-1.7-security-hardening-stateful-application-extensibility-updates.html?m=1

**Comment by ferantivero** [comment]
it seems to be solved in kubernetes/kubernetes#50539 and was included as part of the [K8s 1.8 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v180).

Also from kubernetes/kubernetes/issues/43730: all tags associated to Azure have been removed in favor of a more general problem. 

Please feel free to close this whenever you guys are ready!
