### ISSUE TITLE
e2e core test scenario: Kubernetes

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#699]
**acceptance criteria**:
For [this walkthrough](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md), the following are true:
- Automated e2e testing for walkthrough items
- e2e is reliable

**Comment by dmitsh** [comment]
The following issues have been occasionally observed in k8s validation:
1. nodes are in "Not ready" state within 2 minutes
2. dashboard is in "Not running" state  
3. curl occasionally throws "Connection refused" error when accessing node's dashboards from the master.
