### ISSUE TITLE
e2e core test scenario: DC/OS

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#700]
**acceptance criteria**:
For [this walkthrough](https://github.com/Azure/acs-engine/blob/master/docs/dcos.md), the following are true:
- Automated e2e testing for walkthrough items
- e2e is reliable

**Comment by dmitsh** [comment]
The following issues have been occasionally observed in dc/os validation:
1. marathon app does not have expected 3 running tasks
2. "dcos marathon app add marathon.json" failed
