### ISSUE TITLE
Tracking failures over releases

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#703]
We want an app that can collect data from Jenkins and stores in a database so we can track failures of different types (Azure deployment, acs-engine validations, etc.) across releases. This will help shed light on non-deterministic behavior in both tests themselves and on infrastructure.

**Comment by jchauncey** [comment]
Having done this several times we want to probably build this as a generic engine because once other teams see it they will also want to use it =).

As long as the input into the system is something like a junit xml file or some common testing format we can ingest data from anywhere.
