### ISSUE TITLE
Accessing cluster with public IP returns Unauthorized

### ISSUE THREAD

**Issue by kaskavalci** [Azure/acs-engine#704]
**Is this a request for help?**: Yes

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:
get cluster public fqdn by `kubectl cluster-info`
access `kubernetes-dashboard` by public url:
```
curl -k https://mycluster.westeurope.cloudapp.azure.com/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Unauthorized
```

**What you expected to happen**:
I should be able to access open via http or https

**How to reproduce it** (as minimally and precisely as possible):
Setup a cluster
Access https of public fqdn

**Anything else we need to know**:

**Comment by JackQuincy** [comment]
Don't you need to specify the certs to call with in the curl command? I'm not super familiar with how to use the kubectl proxy command.

**Comment by anhowe** [comment]
Closing since no answer to Jack's question and we are guessing you have solved this.

**Comment by rbitia** [comment]
Hi, I'm hitting a similar issue when I try and access the bashboard

**Comment by chribsen** [comment]
You can't access the URLs from `kubectl cluster-info` directly as you'll need to specify the certificates (as pointed out by @JackQuincy)

Setting up these certificates can be a bit tedious, so you should be able to start a local proxy through `kubectl`:

1. Create a local proxy:
```
kubectl proxy
$ Starting to serve on 127.0.0.1:8001
```

2. Get the URLs from `cluster-info`:
```
kubectl cluster-info
```
Swap the domain (e.g. `foo.com/version`) with the proxy IP and port (e.g. `127.0.0.1:8001/version`)
