### ISSUE TITLE
Copy/steal from Draft release process

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#713]
Mostly an expnasion upon the release process we're already using.

https://github.com/Azure/draft/blob/master/docs/contributing/release-checklist.md

**Comment by CecileRobertMichon** [comment]
@jackfrancis we should maybe formalize the release process and include it in the docs like draft does + update https://github.com/Azure/acs-engine/tree/master/docs/roadmap because it doesn't seem very up-to-date.
