### ISSUE TITLE
install nsenter on k8s nodes

### ISSUE THREAD

**Issue by dmitsh** [Azure/acs-engine#718]
nsenter is not installed but expected by docker, accoding to these error messages:

NetworkPlugin kubenet failed on the status hook for pod "kube-dns-v19-2cb5w_kube-system": Unexpected command output nsenter: cannot open : No such file or directory

**Comment by CecileRobertMichon** [comment]
@jackfrancis any idea if this is still an issue?

**Comment by jackfrancis** [comment]
Let's assume no based on age and lack of thread count
