### ISSUE TITLE
Build errors and version (unset)

### ISSUE THREAD

**Issue by ams0** [Azure/acs-engine#721]
**Is this a request for help?**:

Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

acs-engine build steps

**What happened**:
Building acs-engine (tried on linux and mac, latest commit  4c64999), gives error on the `go get all` phase:

```
[root@cloud gopath]# go get all
# github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers
src/github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers/helpers.go:23: undefined: azure.ServicePrincipalToken
src/github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers/helpers.go:24: azure.PublicCloud.OAuthConfigForTenant undefined (type azure.Environment has no field or method OAuthConfigForTenant)
src/github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers/helpers.go:28: undefined: azure.NewServicePrincipalToken
# github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus/examples/hook
src/github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus/examples/hook/hook.go:12: cannot use airbrake.NewHook(123, "xyz", "development") (type *airbrake.airbrakeHook) as type "github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus".Hook in argument to log.Hooks.Add:
	*airbrake.airbrakeHook does not implement "github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus".Hook (wrong type for Fire method)
		have Fire(*"github.com/sirupsen/logrus".Entry) error
		want Fire(*"github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus".Entry) error
# github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/cobra/cmd
src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/cobra/cmd/root.go:52: cannot use rootCmd.PersistentFlags().Lookup("author") (type *"github.com/Azure/acs-engine/vendor/github.com/spf13/pflag".Flag) as type *"github.com/spf13/pflag".Flag in argument to viper.BindPFlag
src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/cobra/cmd/root.go:53: cannot use rootCmd.PersistentFlags().Lookup("projectbase") (type *"github.com/Azure/acs-engine/vendor/github.com/spf13/pflag".Flag) as type *"github.com/spf13/pflag".Flag in argument to viper.BindPFlag
src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/cobra/cmd/root.go:54: cannot use rootCmd.PersistentFlags().Lookup("viper") (type *"github.com/Azure/acs-engine/vendor/github.com/spf13/pflag".Flag) as type *"github.com/spf13/pflag".Flag in argument to viper.BindPFlag
```
Compilation with `go build` then proceeds without problems. However, the version of acs-engine is unset:

```
[root@cloud acs-engine]# ./acs-engine version
INFO[0000] ACS-Engine Version: unset (unset)
```

**What you expected to happen**:

Compile with errors and correctly set the version to the commit.

**How to reproduce it** (as minimally and precisely as possible):

Clone the git repo of acs-engine on a regular CentOS7 box, follow the steps [here](https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md).

**Anything else we need to know**:

I want to setup automatic builds in TravisCI, and automatic publishing of acs-engine binaries, I'm not sure how to tell TravisCI to continue regardless of the error of the `go get all` command. My .travis.yml is like this:

```
os:
  - linux
  - osx
language: go
install: go get all
script: go build
```

**Comment by jamesbannan** [comment]
I can confirm this behaviour on Mac OS X Sierra:

go get all
# github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers
../gopath/src/github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers/helpers.go:23: undefined: azure.ServicePrincipalToken
../gopath/src/github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers/helpers.go:24: azure.PublicCloud.OAuthConfigForTenant undefined (type azure.Environment has no field or method OAuthConfigForTenant)
../gopath/src/github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/examples/helpers/helpers.go:28: undefined: azure.NewServicePrincipalToken
# github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus/examples/hook
../gopath/src/github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus/examples/hook/hook.go:12: cannot use airbrake.NewHook(123, "xyz", "development") (type *airbrake.airbrakeHook) as type "github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus".Hook in argument to log.Hooks.Add:
	*airbrake.airbrakeHook does not implement "github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus".Hook (wrong type for Fire method)
		have Fire(*"github.com/sirupsen/logrus".Entry) error
		want Fire(*"github.com/Azure/acs-engine/vendor/github.com/Sirupsen/logrus".Entry) error
# github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/cobra/cmd
../gopath/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/cobra/cmd/root.go:52: cannot use rootCmd.PersistentFlags().Lookup("author") (type *"github.com/Azure/acs-engine/vendor/github.com/spf13/pflag".Flag) as type *"github.com/spf13/pflag".Flag in argument to viper.BindPFlag
../gopath/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/cobra/cmd/root.go:53: cannot use rootCmd.PersistentFlags().Lookup("projectbase") (type *"github.com/Azure/acs-engine/vendor/github.com/spf13/pflag".Flag) as type *"github.com/spf13/pflag".Flag in argument to viper.BindPFlag
../gopath/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/cobra/cmd/root.go:54: cannot use rootCmd.PersistentFlags().Lookup("viper") (type *"github.com/Azure/acs-engine/vendor/github.com/spf13/pflag".Flag) as type *"github.com/spf13/pflag".Flag in argument to viper.BindPFlag
# gopkg.in/godo.v1
../gopath/src/gopkg.in/godo.v1/exec.go:243: multiple-value gopass.GetPasswd() in single-value context

After go build:

./acs-engine version
INFO[0000] ACS-Engine Version: unset (unset)

**Comment by ams0** [comment]
I think I'm making progress, see https://github.com/Azure/acs-engine/pull/253#issuecomment-307589924

Basically, remove _-nometadata_ from _pkg/acsengine/fileloader.go_ and the build should succeed (and binary correctly showing the version and the commit).

**Comment by anhowe** [comment]
Please confirm this is still happening on latest acs-engine

**Comment by olafmol** [comment]
i can confirm, Mac OS X, both Yosemite and Sierra. The same errors as reported above

**Comment by mfaizanse** [comment]
#1068 Facing similar issue on windows

**Comment by hmarcelodn** [comment]
I am getting on go build

```
c:\gopath\src\github.com\Azure\acs-engine>go build
# github.com/Azure/acs-engine/pkg/acsengine
pkg\acsengine\engine.go:185: undefined: Asset
```

Any ideas?

**Comment by CecileRobertMichon** [comment]
`make build` should work.
