### ISSUE TITLE
Service Principal key expired - getting 401 errors

### ISSUE THREAD

**Issue by otaviosoares** [Azure/acs-engine#722]
**Is this a request for help?**: Yes

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.6.2

**What happened**:
I started getting 401 Unauthorized errors out of nowhere whenever my cluster tried to access azure. I checked my service principal and realized that the key expired. I generated another key and modified /etc/kubenetes/azure.json in all my nodes and in the master. I restarted kubelet, apiserver and controller. However, I'm still getting 401 errors like:

`E0604 21:22:51.641173       1 routecontroller.go:94] Couldn't reconcile node routes: error listing routes: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/8788e101-fa00-4b62-8a29-74b7c82f051b/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401
`

`E0604 21:22:23.475149       1 servicecontroller.go:703] External error while checking if load balancer "ae9f0ec692c9811e78e07000d3ac07e8" exists: name, autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/8788e101-fa00-4b62-8a29-74b7c82f051b/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401
`

`E0604 21:22:23.475231       1 servicecontroller.go:679] External error while updating load balancer: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/8788e101-fa00-4b62-8a29-74b7c82f051b/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401.
`

**What you expected to happen**:
I'd like to know what's the proper way of replacing the azure client secret.

Thanks

**Comment by otaviosoares** [comment]
I restarted the container and it worked.

**Comment by vydd** [comment]
For anyone having the same issue, it's not one container that needs to be restarted after changing `azure.json`, but all of them, as in `service docker restart`.

**Comment by annegi** [comment]
hi I used a new service principal client id and key. Although, my acs-engine k8s cluster nodes show in ready state now after doing these steps but I still see route errors like 'Couldn't reconcile node routes: error listing routes'

**Comment by dbalaouras** [comment]
I had the exact issue and managed to restore the nodes by updating `/etc/kubenetes/azure.json`.
Still, I am getting similar errors as @annegi :-(

Any luck with this anyone?

```
E0303 21:23:38.847899       1 nodecontroller.go:504] Error determining if node k8s-agent-6ba3291a-7 exists in cloud: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxx/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401
E0303 21:23:38.931390       1 nodecontroller.go:504] Error determining if node k8s-agent-6ba3291a-6 exists in cloud: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxx/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401
E0303 21:23:44.007969       1 nodecontroller.go:504] Error determining if node k8s-agent-6ba3291a-7 exists in cloud: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxx/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401
E0303 21:23:44.082413       1 nodecontroller.go:504] Error determining if node k8s-agent-6ba3291a-6 exists in cloud: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxx/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401
E0303 21:23:46.890022       1 routecontroller.go:99] Couldn't reconcile node routes: error listing routes: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxx/oauth2/token?api-version=1.0 failed with 401 Unauthorized: StatusCode=401
```
