### ISSUE TITLE
Very little Docker daemon logging in swarmmode swarms

### ISSUE THREAD

**Issue by carlfischer1** [Azure/acs-engine#726]
BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Swarmmode

**What happened**:
Swarmmode is based on Ubuntu Xenial. https://success.docker.com/KBase/Where_are_the_Docker_daemon_logs%3F suggests /var/log/upstart/docker.log, but that file is not present. Minimal daemon logging is present in /var/log/syslog.

Are logs aggregated somewhere else?

Repro steps
1 - Create a swarmmode swarm via https://github.com/Azure/azure-quickstart-templates/tree/master/101-acsengine-swarmmode
2 - ssh to a master node
3 - docker run hello-world
4 - cat /var/log/syslog | grep docker

Observed
Very minimal logging:
```
Jun  4 22:45:48 swarmm-master-13957614-0 kernel: [95788.866420] aufs au_opts_verify:1597:dockerd[1419]: dirperm1 breaks the protection by the permission bits on the lower branch
Jun  4 22:45:48 swarmm-master-13957614-0 kernel: [95788.999546] aufs au_opts_verify:1597:dockerd[1419]: dirperm1 breaks the protection by the permission bits on the lower branch
Jun  4 22:45:48 swarmm-master-13957614-0 kernel: [95789.111759] aufs au_opts_verify:1597:dockerd[1251]: dirperm1 breaks the protection by the permission bits on the lower branch
Jun  4 22:45:48 swarmm-master-13957614-0 kernel: [95789.113368] docker0: port 1(veth8adaf75) entered forwarding state
Jun  4 22:45:48 swarmm-master-13957614-0 kernel: [95789.113372] docker0: port 1(veth8adaf75) entered forwarding state
Jun  4 22:45:48 swarmm-master-13957614-0 kernel: [95789.114397] docker0: port 1(veth8adaf75) entered disabled state
Jun  4 22:45:48 swarmm-master-13957614-0 kernel: [95789.640328] docker0: port 1(veth8adaf75) entered forwarding state
Jun  4 22:45:48 swarmm-master-13957614-0 kernel: [95789.640334] docker0: port 1(veth8adaf75) entered forwarding state
Jun  4 22:45:49 swarmm-master-13957614-0 kernel: [95789.826485] docker0: port 1(veth8adaf75) entered disabled state
Jun  4 22:45:49 swarmm-master-13957614-0 kernel: [95789.919501] docker0: port 1(veth8adaf75) entered disabled state
Jun  4 22:45:49 swarmm-master-13957614-0 kernel: [95789.921390] docker0: port 1(veth8adaf75) entered disabled state

```

**What you expected to happen**:
docker daemon logging related to running hello-world container

As a reference, see the logging available in a Docker EE Basic for Azure swarm: /var/log/docker.log contains lots of runtime info

**How to reproduce it** (as minimally and precisely as possible):
Above

**Anything else we need to know**:

**Comment by ams0** [comment]
Could be related to https://github.com/Azure/acs-engine/issues/689 ?

**Comment by carlfischer1** [comment]
@ams0 json-file is the configured logging method, so not sure #689 is relevant
`[swarmacs] ~ $ docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: 
Swarm: active
 NodeID: xgujzxv1bb7n3d5ih5zl7um69
 Is Manager: true
 ClusterID: vd58o0p532y9qpbijvm4i1581
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 172.16.0.5
 Manager Addresses:
  172.16.0.5:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.804GiB
Name: swarmm-master-13957614-0
ID: W4QP:VM2B:4LPC:3WBL:5C6H:IBT3:S3YK:7TKV:IN5L:DDGS:VU25:YSFX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support`

**Comment by carlfischer1** [comment]
Creating /etc/docker/daemon.json with
```
{
     "debug": true
}
```
allows the expected level of logging to be available via `journalctl -u docker.service`

Setting this by default (as is the case in other Docker Editions) will enable usable `dockerd` logs without requiring configuration.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
