### ISSUE TITLE
Building a k8s cluster fails as az acs is attempting to use an outdated base image

### ISSUE THREAD

**Issue by stimms** [Azure/acs-engine#729]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:
Attempting to build a new windows cluster with 

``` az acs create --orchestrator-type=kubernetes --resource-group $RESOURCE_GROUP --name=$CLUSTER_NAME --dns-prefix=$DNS_PREFIX --generate-ssh-keys --windows --admin-password $DOCKER_PASSWORD```

Error returned is 

```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ProvisioningFailed",
        "message": "Provisioning of resource(s) for container service 'prdc2017' in resource group 'kubernetes' failed with errors: Resource type: Microsoft.Compute/virtualMachines, name: DB8BBacs9000, id: /subscriptions/000000/resourceGroups/kubernetes/providers/Microsoft.Compute/virtualMachines/DB8BBacs9000, StatusCode: NotFound, StatusMessage: \\n {\r\n  \"error\": {\r\n    \"code\": \"ImageNotFound\",\r\n    \"target\": \"imageReference\",\r\n    \"message\": \"The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available. Verify that all fields in the storage profile are correct.\"\r\n  }\r\n}\r\nResource type: Microsoft.Compute/virtualMachines, name: DB8BBacs9001, id: /subscriptions/000000/resourceGroups/kubernetes/providers/Microsoft.Compute/virtualMachines/DB8BBacs9001, StatusCode: NotFound, StatusMessage: \\n {\r\n  \"error\": {\r\n    \"code\": \"ImageNotFound\",\r\n    \"target\": \"imageReference\",\r\n    \"message\": \"The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available. Verify that all fields in the storage profile are correct.\"\r\n  }\r\n}\r\nResource type: Microsoft.Compute/virtualMachines, name: DB8BBacs9002, id: /subscriptions/00000000000/resourceGroups/kubernetes/providers/Microsoft.Compute/virtualMachines/DB8BBacs9002, StatusCode: NotFound, StatusMessage: \\n {\r\n  \"error\": {\r\n    \"code\": \"ImageNotFound\",\r\n    \"target\": \"imageReference\",\r\n    \"message\": \"The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available. Verify that all fields in the storage profile are correct.\"\r\n  }\r\n}\r\n"
      }
    ]
  }
}
```

Notice the version of windows image is incorrect.

**What you expected to happen**:

Cluster to be created.

**How to reproduce it** (as minimally and precisely as possible):

Using the latest azure cli attempt to build a cluster targeting k8s on windows

**Anything else we need to know**:

There seems to be an update in git but it is not apparent how to select the correct image. It should be the default anyway.

**Comment by JackQuincy** [comment]
This is known and being tracked in https://github.com/Azure/ACS/issues/25 . We have a deployment currently rolling out and it should be working currently in the austrilia South east region. We are following internal procedures so it will take a few days to roll out the deployment globally

**Comment by stimms** [comment]
Thanks @JackQuincy I have a talk on container services tomorrow in North America. Is there any workaround to use a closer region or manually flag the image to use?

**Comment by JackQuincy** [comment]
You could use acs-engine, but if you want to do it in the portal you'll need to use the regions we have deployed the fix to.  Which currently is just Australia southeast. We should be doing the next phase tomorrow but none of those regions are in North America.

**Comment by stimms** [comment]
Thanks, I tried Australia SE and it works great. I'll just do my whole talk with my patented terrible Australian accent.  Dingo, didgeridoo.
