### ISSUE TITLE
Option to configure data disks as RAID

### ISSUE THREAD

**Issue by jt55401** [Azure/acs-engine#731]
Modify the initialization scripts to configure RAID if more than 1 data disk is specified.

Example steps to include in script: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/configure-raid

Generally:
1. Install mdamd
2. Create a partition
3. Create the RAID array
4. Add it to fstab

I would think most folks would want RAID 0, but it would be good to also have an option for which RAID level to use with mdadm (or, at a minimum, RAID 0 or 1)

Noob suggestion:
> I'm new to your project, so I don't think I can do this on my own, but I did dig around a bit, and it looks like for Kubernetes, this would involve specifying a new script in parts/kubernetesmastercustomdata.yml, and running in down in the "runcmd" section? (and, it looks like the mountetcd.sh script near line 265 might have some of the building blocks for doing this?

**Comment by anhowe** [comment]
Thanks for the feature request.  This is currently out of scope, and why I'm assigning p2, but we will accept PRs.
