### ISSUE TITLE
Create a --set flag for generate

### ISSUE THREAD

**Issue by jchauncey** [Azure/acs-engine#733]
#**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

It would be nice if you could pass in the custom values for an acs cluster via the command line instead of having to edit a file on disk. This would help facilitate more automation around the creation of clusters. It would work just like the helm `--set` flag does now which takes a comma separated list of key/value pairs. So an example could look like the following:

```
acs-engine generate --set \
"masterProfile.count=3,\
agentPoolProfile.count=4,\
windowsProfile.adminPassword=${SOME_ENV_VAR_FETCHED_FROM_VAULT}" \
examples/kubernetes.json

**Comment by colemickens** [comment]
This ties into stuff I've wanted to do to make `acs-engine deploy ...` more robust and not requiring editting the apimodel as well. For my case, I want to also be able to have `acs-engine` generate an SP and inject it as well.

**Comment by serbrech** [comment]
If the goal is to solve the configuration in a generic way, and potentially extend it with other sources later (env, yaml, toml, ...) I would suggest looking at existing libraries managing configuration sources.
one pretty extensive implementation is was built by Containous, to manage Traefik configuration from toml, or commandline.

see [containous/staert](http://github.com/containous/staert)

However, this is an intrusive change that might cause breaking changes if not carefuly introduces, and it makes acs-engine rely on 2 external libraries. ([containous/staert](http://github.com/containous/staert), [containous/flaeg](http://github.com/containous/flaeg)).

**Comment by jcorioland** [comment]
Right now working on implementing the feature by replacing the values directly in json using json query like library but yes, it makes sense to make it more generic to be able to handle different kind of source.
