### ISSUE TITLE
Kubernetes Service creates NSG with port set to ANY

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#740]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

If you create a service with only a single protocol the corresponding NSG gets set to procotol of any. It should evaluate the port protocol and correctly configure the NSG.

```
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    name: test
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
   name: test
---


**What you expected to happen**:

Create the service above and the NSG configures the NSG to only support TCP

**How to reproduce it** (as minimally and precisely as possible):

See above


**Anything else we need to know**:

**Comment by itowlson** [comment]
When I try this, it creates the LB rule and the NSG rule with UDP.  The commit is https://github.com/kubernetes/kubernetes/commit/355c2be7a016fe470657741895486ec0ac9686c3.  I haven't tested end to end though (there is a comment in the code that it doesn't work for services that need health checks, but that _shouldn't_ be an issue as the LB/NSG rules should not be created in that case).
