### ISSUE TITLE
Kubernetes in non 10.0.0.0 subnet - services with wrong cluster IP 

### ISSUE THREAD

**Issue by itaysk** [Azure/acs-engine#742]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes latest

**What happened**: created a cluster using an existing subnet with custom subnet CIDR (not the 10.0.0.0 that ACS assumes). everything basically works, but services are still created under 10.0.0.0 range.

**What you expected to happen**: services be created under the cluster's range, or allow me to specify a custom 'kubeServiceCidr'.

**How to reproduce it** (as minimally and precisely as possible): 
1. Create a VNET and subnet 192.168.1.0/16.
2. Create Kube cluster in that VNET including 'kubernetesConfig.clusterSubnet' and 'firstConsecutiveStaticIP'. cluster nodes are created correctly under the correct IPs.
3. Once done, create a new deployment, pods get a correct IP in the range.
4. expose the deployment using a kubernetes service with type 'cluster-ip'. service ip is created under 10.0.0.0/16 and therefore are non-routable, and might conflict with existing subnets.

**Anything else we need to know**:
This was apparently fixed in GH-473 which added `serviceCidr` to cluster definition but was then reverted back in GH-508 which was partially fixed again in GH-632 (serviceCidr is still hardcoded). 
GH-632 says that "This PR is complementary to #473" and that "this PR can be applied in any order to re-enable that functionality." 
So should now that GH-632 was applied - should we merge GH-473 again on top of it?

**Comment by itaysk** [comment]
BTW, as a workaround, I guess I can modify this: https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastervars.t#L87 ?
anything else I need to do for this workaround to work?

**Comment by SaaldjorMike** [comment]
Assume this one can be closed due to the merge of #546
