### ISSUE TITLE
Kubernetes Deployment failing with CNI "networkPolicy": "azure"

### ISSUE THREAD

**Issue by uday31in** [Azure/acs-engine#752]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes
https://github.com/Azure/acs-engine/blob/master/examples/cni/kubernetes-azure.json

**What happened**:

Error: 
Resource: k8s-master-41119652-0/cse0
Type: Microsoft.Compute/virtualMachines/extensions
StatusMessage: 
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\"."
      }
    ]
  }
}

**Azure Script Extension log:**
```
+ /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/bin/custom-script-extension install
time=2017-06-12T11:40:14Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 event=start
time=2017-06-12T11:40:14Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 status="not reported for operation (by design)"
time=2017-06-12T11:40:14Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 event="created data dir" path=/var/lib/waagent/custom-script
time=2017-06-12T11:40:14Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 event=installed
time=2017-06-12T11:40:14Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 status="not reported for operation (by design)"
time=2017-06-12T11:40:14Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 event=end
Writing a placeholder status file indicating progress before forking: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/status/0.status
+ nohup /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/bin/custom-script-extension enable
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=start
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=pre-check
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="checking for state migration"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="no old state found to migrate"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="comparing seqnum" path=/var/lib/waagent/custom-script/seqnum
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="seqnum saved" path=/var/lib/waagent/custom-script/seqnum
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="reading configuration"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="read configuration"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="validating json schema"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="json schema valid"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="parsing configuration json"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="parsed configuration json"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="validating configuration logically"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="validated configuration"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="creating output directory" path=/var/lib/waagent/custom-script/download/0
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="created output directory"
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 files=0
time=2017-06-12T11:40:15Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="executing command" output=/var/lib/waagent/custom-script/download/0
time=2017-06-12T11:52:53Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="failed to execute command" error="command terminated with exit status=1" output=/var/lib/waagent/custom-script/download/0
time=2017-06-12T11:52:53Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="enable failed"
time=2017-06-12T11:52:53Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="failed to handle" error="failed to execute command: command terminated with exit status=1"

```

**What you expected to happen**:

Deployment to succeed

**How to reproduce it** (as minimally and precisely as possible):

Following values used to generate template: 
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
        "networkPolicy": "azure"
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "udayk8sazure",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      },
      {
        "name": "agentpool2",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],

**Anything else we need to know**:

**Comment by itaysk** [comment]
Same here..

**Comment by yaron2** [comment]
+ 1

Can someone take a look at this?
Its currently a show stopper for many deployments..

**Comment by anhowe** [comment]
@brendanburns - correct this is a duplicate of #561 - Outbound internet does not work with CNI plugin

**Comment by yaron2** [comment]
Up until several days ago I was able to successfully deploy azure cni clusters. The deployment completed successfully along with the cse..

The outgoing internet issue happens without relation to the cluster deployment process.
The deployment should succeed.

**Comment by itaysk** [comment]
Sorry but how does outbout internet connectivity has to do with this issue? Im unable to create a cni cluster at all, meaning the template development fail. this effectively means kube-cni is broken.

**Comment by yaron2** [comment]
@anhowe look at what you wrote in #561  - 

"To repro:

1. deploy a cluster with CNI
2. kubectl exec to the container, and try to access the internet from a container"

In this issue you can't even get past step 1.. the cluster itself doesn't deploy.
Seems like this isn't a dup..

**Comment by itaysk** [comment]
Trying to debug this, I looked at the azure agent logs (since the error comes from the script extension) I couldn't find anything meaningful but I this I can guess that the agent is unable to download he script or one of its resources before executing, so it be related (still needs confirmation). BUT if it's indeed because of cni outbound internet issue, how did we expect the deployment to ever succeed? Also - this worked just couple of days ago

**Comment by ofiliz** [comment]
I just deployed a new cluster with CNI plugin and latest acs-engine. It works fine.

**Comment by uday31in** [comment]
I can also confirm updating acs engine from 5/22 to latest works fine.

**Comment by uday31in** [comment]
Spoke too soon :-( 

Although deployment is not failing; Kubernetes is not getting installed either.

root@k8s-master-41119652-0:/var/lib/waagent/custom-script/download/0# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?


root@k8s-master-41119652-0:/var/lib/waagent/custom-script/download/0# ls -alh
total 8.0K
drwx------ 2 root root 4.0K Jun 13 17:43 .
drwx------ 3 root root 4.0K Jun 13 17:43 ..
-rw------- 1 root root    0 Jun 13 17:43 stderr
-rw------- 1 root root    0 Jun 13 17:43 stdout

**Comment by brendandburns** [comment]
We need the logs for the waagent run, something went wrong, but it's hard to know what...



________________________________

**Comment by uday31in** [comment]
I have deleted resource group but redeployment worked fine. Thanks for the help everyone!

**Comment by gaurav218** [comment]
i am facing this issue where provisioning state is successful but kubernetes is not installed 

![image](https://user-images.githubusercontent.com/26568744/39591197-a97dffb6-4f20-11e8-90a5-5a64df23e0aa.png)

deleted resource group multple times and redeployed kubernetes with different versions as well but same result. Any help is appreciated.
