### ISSUE TITLE
run vlab api-version on Azure resource manager REST API

### ISSUE THREAD

**Issue by chartotu19** [Azure/acs-engine#756]
**Is this a request for help?**: Yes
---

**Is this an ISSUE or FEATURE REQUEST?** :
ISSUE

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
v1.6.2

**What happened**:
I am trying to handcraft an azure deployment template of [acs kubernetes + custom VNET](https://github.com/Azure/acs-engine/tree/master/examples/vnet). "vlab" api-version doesn't exist in the  [REST API](https://docs.microsoft.com/en-us/rest/api/resources/deployments#Deployments_CreateOrUpdate), I get an error agentPoolProfiles[0].vnetSubnetId is not supported and few other fields.
When I follow the tutorial using acs-engine, it works. The generated azuredeploy.json has an api version "2016-03-30". My understanding is that the Azure resource manager API [resolves does resolve agentPoolProfiles](https://github.com/Azure/azure-quickstart-templates/blob/master/101-acs-kubernetes/azuredeploy.json#L128) object, but doesnt support new fields such as vnetSubnetId. 

Is there way to bypass acs-engine and run "vlab" version on azure RM API directly?

**Comment by anhowe** [comment]
The vlab is exclusive to ACS-Engine only.  It is a header we use for experimental features.  Let us know what features you like on https://github.com/Azure/acs.  Also, periodically watch https://azure.microsoft.com/en-us/services/container-service/ for updates and releases.

**Comment by argoLein** [comment]
hi,

i'm need nearly the same. the custom VNet for Master/Agent profiles. We use westeurope as location, but there is only ACS RP 1 available. I think the change with the custom vnet is in ACS RP2. Do know a Roadmap when ACS RP 2 is available in other regions?
