### ISSUE TITLE
Support AAD authentication to the Kubernetes API

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#771]
AAD authentication support just landed in Kubernetes upstream. We should support using AAD to authenticate to the Kubernetes API. This is a meta issue to track this feature work.

- [x] AAD authentication support in Kubernetes upstream and scheduled Kubernetes v1.7 release
- [x] Kubernetes v1.7.0 release
- [ ] acs-engine provisions Azure authentication apps, one for client (kubectl) and one for server (apiserver itself)
- [ ] acs-engine configures apiserver with options required for AAD
- [ ] acs-engine configures kubeconfig to use Azure authentication provider

Step by step details located here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure/README.md

**Comment by colemickens** [comment]
If it's helpful, here's some code that can do the Application creation: https://github.com/colemickens/azkube/blob/master/util/ad.go.

ACS-Engine will need to generate two Apps and then configure them appropriately for the client/server behaviors (I don't have code for that latter part but @lachie83 has done it manually and the manifest update should be straightforward.)

One of these also have to be round-tripped into the VM similar to the SP creds that are plumbed in today. This may require extending the ServicePrincipalProfile section even further, or it may be the push to start having ACS-Engine stage everything in KeyVault and then have a bootstrap service on the VM that can use MSI to pull down all of the assets it thinks it needs to pull down.

**Comment by seanknox** [comment]
Awesome, and thanks for calling out the AAD app creation step. Added that work to our internal tracker.
