### ISSUE TITLE
Allow custom script execution when provisioning nodes

### ISSUE THREAD

**Issue by vlesierse** [Azure/acs-engine#79]
For my use case I would like to create a single ARM template which deploys an ACS cluster (DC/OS orchestrator) and some additional services directly provisioned on top of Marathon.

I've tried to add an Custom Script Extension to the Mesos master. This works although there is no way to resolve the VM's resource name due to generated 8 HEX string to make the resources unique.
Issue #53 would solve this particular problem, but I think it would be cleaner if it's somehow possible  to provide an reference to a script.

**Comment by anhowe** [comment]
Will it solve your case, if you writing your code in parts/dcosprovision.sh?  This runs on both Master and Agent.

**Comment by vlesierse** [comment]
That will work for sure. Any guidance of how to determine if it's currently running on a master or agent? In my case I would like to only run it once on the first master node (curl a Marathon app in json format)

**Comment by anhowe** [comment]
For DCOS, there is a custom script extension that runs on the last master.  If this doesn't complete, it will fail the deployment.  You can wire in your changes to that master custom script extension to confirm it has successfully run.

**Comment by anhowe** [comment]
Closing since this was a question.  Please re-open if this is not fully answered.  I've tagged with wontfix, since I'll leave this as a customer enhancement.
