### ISSUE TITLE
Deleting Container Service leaves provisioned resources around

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/acs-engine#792]
Ciao!

When provisioning an Azure Container Service instance through the API - lots of resources are created for things like Storage Accounts, VMSS etc, through what appears to be an ARM Template. When deleting the Container Service instance through the API these resources aren't cleared up - which we've had come through as issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/79

Would it be possible to fix this? Thanks! :)

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
I tried DC/OS, [using the top example on this page](https://www.terraform.io/docs/providers/azurerm/r/container_service.html), but I'm assuming this is applicable to all.

**What happened**:
The Container Service got deleted, but all the provisioned resources got left behind.

**What you expected to happen**:
The resources provisioned by Azure Container Service would be cleaned up when deleting the Container Service instance.

**How to reproduce it** (as minimally and precisely as possible):
Delete the Container Service instance through the Azure API (we do this via `terraform destroy --target=azurerm_container_service.test`, but just a regular API call will work)

**Anything else we need to know**:

This bug was originally https://github.com/hashicorp/terraform/issues/14128 before migrating to the new location: https://github.com/terraform-providers/terraform-provider-azurerm/issues/79

**Comment by rgardler** [comment]
Thanks for the report. This is indeed an issue, although it is an ACS-Engine issue since Engine itself does not create an ACS Resources.

WORKAROUND
Deleting the ResourceGroup that the container service was a part of will delete all resources. However, be aware that this will delete other resources created outside of ACS.

**Comment by tombuildsstuff** [comment]
Hey @rgardler

Thanks for confirming that - apologies I wasn’t sure of the best place to file this issue, I’d normally place this kind of thing in the Rest API Specs repository - but that didn’t feel like the right place :( where’s the best place to reopen this issue?

Thanks for the workaround, that’ll work in the short-term until this is fixed :)

Thanks!

**Comment by JackQuincy** [comment]
github.com/Azure/acs

**Comment by tombuildsstuff** [comment]
Migrated to https://github.com/Azure/ACS/issues/31 - thanks @JackQuincy / @rgardler
