### ISSUE TITLE
Kubernetes Tracking - Attach/Detach Disk api calls do not correctly monitor status

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#793]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

Tracking issue for https://github.com/kubernetes/kubernetes/issues/47623 - Attach/Detach Disk api calls do not correctly monitor status

**Comment by khenidak** [comment]
This behavior has been fixed in the new plugin. The plug-in is available in v 1.7.2++ . The new plugin check if there is a lease on the disk before attempting to attach it. 

@jdumars do you own issues on Kubernetes repo? Can you close it?

**Comment by khenidak** [comment]
Can we please close this one?
