### ISSUE TITLE
test scripts don't work with recent versions of azure-cli

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#811]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

**What happened**:

After upgrading my `azure-cli` (to `2.0.8`) for an unrelated task, I am no longer able to use any of the test scripts (e.g., `test/deploy.sh`). This is due to the following lines in `test/common.sh`, which use the now-deprecated `@` prefix syntax when passing in group deployment parameters:

https://github.com/Azure/acs-engine/blob/master/test/common.sh#L118
https://github.com/Azure/acs-engine/blob/master/test/common.sh#L145

I've verified locally that removing the `@` prefix restores functionality of the test scripts with newer versions of `azure-cli` that include this change. We don't want to blindly update `acs-engine` without thinking about how to best communicate to users how to best pair its use with particular versions of `azure-cli`.

**Comment by seanknox** [comment]
@dmitsh is this still an issue?

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
