### ISSUE TITLE
Ensure Ubuntu auto-updates for 16.04

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#814]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** all

**What happened**: daily auto-updates not applying, and the following mitigation will make them apply:

echo 2dd1ce17-079e-403c-b352-a1921ee207ee > /sys/bus/vmbus/drivers/hv_util/unbind
sed -i "13i\echo 2dd1ce17-079e-403c-b352-a1921ee207ee > /sys/bus/vmbus/drivers/hv_util/unbind\n" /etc/rc.local

**Comment by DonMartin76** [comment]
We have seen nodes dropping out of the cluster, and we have currently no clue what it can be caused by. This cannot be related, can it?
