### ISSUE TITLE
dcosprovision.sh Needs newer version of Docker

### ISSUE THREAD

**Issue by jsilberm** [Azure/acs-engine#816]
**Is this a request for help?**:
No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DCOS

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by JackQuincy** [comment]
Can you describe why we need the newer version of docker?

**Comment by jsilberm** [comment]
In docker 1.11, the docker.service file is deployed by default with MountFlags=slave.
For Portworx to run, this needs to be disabled (on all nodes running Portworx).
In docker 1.12 and above, MountFlags=slave is no longer set by default.

We have the absolute simplest/easiest way of deploying Portworx on DCOS, as documented here:https://docs.portworx.com/scheduler/mesosphere-dcos/install.html
But with an older (1.11) version of Docker, we would need to 'ssh' in to each agent node first in order to suppress MountFlags=slave --- which is unmanageable.

In addition, I'm certain there are many other features supported and bugs fixed since docker version 1.11

Thanks,   -Jeff

**Comment by JackQuincy** [comment]
Seems dcos has moved to 1.13.1

https://github.com/dcos/dcos/blob/master/gen/azure/cloud-config.yaml
> https://mesosphere.blob.core.windows.net/dcos-deps/docker-engine_1.13.1-0-ubuntu-xenial_amd64.deb

**Comment by jsilberm** [comment]
But it does not appear that acs-engine has picked this up.
If 1.13.1 was referenced by acs-engine, then https://github.com/Azure/acs-engine/blob/master/examples/dcos-attributes/dcos.json would pick up 1.13.1.
And I can verify that is not the case.   The acs-engine dcos.json file deploys 1.11, which coincidentally corresponds to the version in dcosprovision.sh

**Comment by JackQuincy** [comment]
Agreed. We are definitely still on 1.11. DCOS moved to 1.13 in may and I don't think we've taken an update since then.
If you want to submit a PR for moving to 1.13.1 that would help get this in sooner.
file to change would be https://github.com/Azure/acs-engine/blob/master/parts/dcosprovision.sh 
and we would want to also verify that the china mirror has the new binaries @wangtt03 .

**Comment by jsilberm** [comment]
Understood.  And I'll be happy to file the PR.   But I do need some help from you first please.  

Here's the line that needs fixing:
DOCKER_ENGINE_DOWNLOAD_URL=https://az837203.vo.msecnd.net/dcos-deps/docker-engine_1.11.2-0~xenial_amd64.deb

I could not find a newer package under "https://az837203.vo.msecnd.net/dcos-deps".
So I simply used an official repo at : "apt.dockerproject.org/repo/pool/main/d/docker-engine"

Do you want me to submit using 1.13.1 against dockerproject.org?   Or if not, then can you please point me to a 1.13.1 package under msecnd.net.

Thanks.

**Comment by JackQuincy** [comment]
I'd actually prefer we use the url from mesosphere
https://mesosphere.blob.core.windows.net/dcos-deps/docker-engine_1.13.1-0-ubuntu-xenial_amd64.deb
as that is a mirror hosted in azure maintained by mesosphere. 
Unless @dmitsh  wants to add  1.13.1 to our cdn

**Comment by jsilberm** [comment]
Gladly.   Thanks.

**Comment by JackQuincy** [comment]
@ritazh @wangtt03 @Azure/ccg-data-sln-admin can someone help me get the new docker build into the china cloud mirror?

**Comment by wangtt03** [comment]
@JackQuincy Sure!
