### ISSUE TITLE
Documentation for "acs-engine deploy"

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/acs-engine#822]
**Is this a request for help?**:
Documentation change request
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

FEATURE REQUEST - include examples of how to use `acs-engine deploy` instead of using `az resource group deployment create ...` commands to deploy the templates generated by `acs-engine generate`

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

All

**What happened**:

Command help is not sufficient. Documentation references deployments using CLI and not the tool

**What you expected to happen**:

Documentation to include examples using acs-engine as well as the CLI

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by seanknox** [comment]
Thanks @dcieslak19973 for raising this issue. We're tracking this work in https://github.com/Azure/acs-engine/issues/873, closing this issue in favor of that one.
