### ISSUE TITLE
acs-engine ci is broken

### ISSUE THREAD

**Issue by JackQuincy** [Azure/acs-engine#823]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
all

**What happened**:
az cli rev'ed and the current version is broken.
**What you expected to happen**:
ci to be able to deploy a template

**How to reproduce it** (as minimally and precisely as possible):
run @acs-bot tests

**Anything else we need to know**:
We are currently working on getting a working version of the cli back so that we can restore to normal operations

**Comment by anhowe** [comment]
This is now fixed by #826
