### ISSUE TITLE
Automatically Install NVidia Drivers on provisioning

### ISSUE THREAD

**Issue by drcrook1** [Azure/acs-engine#828]
Currently I use Kubernetes and William Buchwalters branch of ACS engine located here: https://github.com/Azure/acs-engine such that I can have the scripts automatically run and install the nvidia drivers on GPU nodes in my cluster.

We do batch machine learning training on GPU nodes in Azure, we serve ML models from GPU nodes running in Kubernetes and also host and provide a variety of GPU services as a SaaS type offering using the GPU nodes.  GPU nodes are critical for us.  William's fork is starting to fall quite a bit behind this one.  It would be really great if we could just use Azure/acs-engine mainline for provisioning clusters.

Right now this is painful because your updates and other updates fix bugs in clusters that we currently run.

Thanks!

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I have to currently ssh into each node (we use an auto-scaler as well making this challenging).

**What you expected to happen**:
drivers get installed as part of provisioning

**Comment by JackQuincy** [comment]
This pr didn't help? https://github.com/Azure/acs-engine/pull/385

**Comment by drcrook1** [comment]
Notice that step two in her walk through is to ssh into each node and install the drivers.

**Comment by wbuchwalter** [comment]
@JackQuincy The PR only allows kubernetes to detect the GPU if it is present and the drivers are installed.
Installing them is still the responsibility of the user currently.

The main blocker is not technical, it's legal. Does the licence of NVIDIA drivers allow us to do this? If yes I can submit a PR, but it needs investigation.

**Comment by JackQuincy** [comment]
@rgardler can you point us in the right direction to get this question answered?

>  The main blocker is not technical, it's legal. Does the licence of NVIDIA drivers allow us to do this?

**Comment by JackQuincy** [comment]
side note to me this almost feels like a CRP bug in that you have a vm with a GPU but no driver. Though I could see the whole we pick the image thing being part of this. I wonder if we could get an image that came with them preinstalled. @anhowe  thoughts?

**Comment by wbuchwalter** [comment]
@JackQuincy Currently every GPU-VM on Azure, AWS or GCE requires the end-user to install the drivers himself.  

Quote from someone working on GCE GPU VMs (from https://news.ycombinator.com/item?id=13697666):

> SIGH. Because GPL you can't pre-install the NVIDIA driver. At that point, it sadly makes more sense to have you roll your own and then bake the image. I'll gladly hand out refunds for the X minutes this takes (don't forget that on kernel upgrades you get to do it again when the kernel headers change!), but like you I wish it weren't so.

So it seems like currently the user would have to create the image.

**Comment by ezwiefel** [comment]
@wbuchwalter and @JackQuincy The DSVM for both Windows 2016 and Ubuntu come with the GPU drivers pre-installed. (See Deep Learning section on the Doc page: https://aka.ms/Annxi7)

Perhaps that team could give us some pointers on the licensing question... I'm wondering if we have special licensing agreed upon when we bought the GPUs for Azure.

**Comment by ogrisel** [comment]
The lack of an automated way to install the nvidia drivers on ACS nodes seriously limit the usability of ACS for GPU computing clusters, especially when using an autoscaler.

I confirm that the official Ubuntu Data Science Deep Learning VM comes with the nvidia drivers installed by default. Why wouldn't it be possible to have nvidia drivers installed by default on ACS agent nodes with vmSize that have nvidia GPUs?
