### ISSUE TITLE
ACS engine on Linux installation issue

### ISSUE THREAD

**Issue by windswordsgd** [Azure/acs-engine#84]
I tried to install ACS engine on a Linux which had docker installed already with the document below,
https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md
*********************************
Linux
For Linux, ensure Docker is installed, and follow the developer instructions at https://github.com/Azure/acs-engine#development-docker to build and use the ACS Engine.
*********************************
After click the above link,  the instruction for install ACS engine on Linux is not very clear.
*********************************
Development (Docker)
The easiest way to get started developing on  acs-engine  is to use Docker. If you already have Docker or "Docker for {Windows,Mac}" then you can get started without needing to install anything extra.
•Windows (PowerShell):  .\scripts\devenv.ps1 
•Linux (bash):  ./scripts/devenv.sh 
This setup mounts the  acs-engine  source directory as a volume into the Docker container. This means that you can edit your source code normally in your favorite editor on your machine, while still being able to compile and test inside of the Docker container (the same environment used in our Continuous Integration system).
Here's a quick demo video showing the dev/build/test cycle with this setup.
********************************

Do we need to export any path or parameters on Linux?  Where is devenv.sh located at?   It would be great if there will be a step-by-step installation guide as Windows or OSX.  Current installation guide for Linux is not very clear.

**Comment by colemickens** [comment]
That script is exactly where the docs says it is after you clone the
repository. I'm just not sure what part of it is confusing.

1. clone the repo
2. Run `scripts/devenv.sh`
3. Run `make`

Please give details on where you're getting stuck or confused. Thanks.

**Comment by windswordsgd** [comment]
Hi Cole,

From the document https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md,  I find the installation guide for Linux.

Linux
For Linux, ensure Docker is installed, and follow the developer instructions at https://github.com/Azure/acs-engine#development-docker to build and use the ACS Engine.

Once I click the link https://github.com/Azure/acs-engine#development-docker,   it re-direct to the page below.
https://github.com/Azure/acs-engine#development-docker

Development (Docker)
The easiest way to get started developing on acs-engine is to use Docker. If you already have Docker or "Docker for {Windows,Mac}" then you can get started without needing to install anything extra.

  *   Windows (PowerShell): .\scripts\devenv.ps1
  *   Linux (bash): ./scripts/devenv.sh
This setup mounts the acs-engine source directory as a volume into the Docker container. This means that you can edit your source code normally in your favorite editor on your machine, while still being able to compile and test inside of the Docker container (the same environment used in our Continuous Integration system).
Here's a quick demo video showing the dev/build/test cycle with this setup.<https://www.youtube.com/watch?v=lc6UZmqxQMs>

It does not mention clone of repo and the steps below in https://github.com/Azure/acs-engine#development-docker or https://github.com/Azure/acs-engine/blob/master/docs/acsengine.md

1. clone the repo
2. Run `scripts/devenv.sh`
3. Run `make`

Once I click the link and go to Development(Docker) section,  it does not mention what to do next.   It would be great if the Linux instruction is as detailed as Windows and OSX.

Thank you for looking into this.

Best Regards,
David Gao

**Comment by colemickens** [comment]
Okay, I can update the docs to add `Clone this repo first so you can build or develop on it`.

**Comment by anhowe** [comment]
Closing as won't fix, since the instructions already request cloning the repo.
