### ISSUE TITLE
How do I get the K8S master FQDN programmatically

### ISSUE THREAD

**Issue by rajeevb2** [Azure/acs-engine#847]
I looked at client-go and kubernetes libraries and couldnt find the answer

**Comment by JackQuincy** [comment]
Is this for a k8s cluster created by a template generated from acs engine?

**Comment by rajeevb2** [comment]
I used the following to create the k8s cluster on acs. 
az acs create -n xxx -g yyy --generate-ssh-keys --location eastus --agent-vm-size Standard_DS2_v2 --orchestrator-type kubernetes

After that, I have been using client-go and kubectl:

**Comment by CecileRobertMichon** [comment]
@JackQuincy any update on this? this looks to be an ACS question. I will close the issue of no objections.

**Comment by robsonpeixoto** [comment]
I needing it too.
I'd created a private K8S cluster and I'd like to scale down the agent pool, but I got the error:
```
FATA[0013] master-FQDN is required to scale down a kubernetes cluster's agent pool
```

How to get the FQDN?

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine) and the ACS service will be deprecated on January 31, 2020.
