### ISSUE TITLE
Managed Disks are not yet supported by k8s persistent volumes

### ISSUE THREAD

**Issue by skippy** [Azure/acs-engine#849]
hi folks,

the docs don't reference the fact that managed disks for persistent volumes are not yet supported by k8s, and in fact it looks like 1.8 will be the earliest it could be added (see https://github.com/kubernetes/kubernetes/pull/46360). 

Please update the documents to note that fact.  I'm happy to attach a PR with warnings on every page that references managed disks that it is not yet supported for persistent volumes.

Thank you.

**Comment by anhowe** [comment]
Thanks @skippy, we are working to get the disk PR into 1.8.  If you could submit a PR with the warnings that would be great.  We did add managed disks for master / agents because we have some customers who want encryption at rest, but not to use PVs.

**Comment by skippy** [comment]
@anhowe will do!  I hadn't realized #844 was so recent!  I am still trying to figure this out, but so far I haven't been able to create encrypted OS disks under k8s for masters or agents.  Do you have instructions that you can point me to?  I'm glad to update the docs to include this info if needed.

**Comment by skippy** [comment]
@anhowe just to be clear, I'm using the https://github.com/Azure/acs-engine/blob/master/examples/disks-managed/kubernetes-vmas.json examples; the disks are showing up in the UI as well as `az disks list`, but the encryption settings are null on the CLI and showing up as unencrypted on the UI (select agent or master vm -> select disks -> Encryption is 'Not enabled'


so perhaps I'm all set and managed disks is working as expected?

**Comment by anhowe** [comment]
Correct, your managed disks have encryption at rest automatically.

The Disk team confirmed that Portal / CLI shows the status of ADE (https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption).  Portal and CLI do not show encryption at reset which is enabled automatically (https://azure.microsoft.com/en-us/blog/azure-managed-disks-sse/?v=17.23h).

**Comment by skippy** [comment]
@anhowe gotcha, and I really appreciate the input!!  I've been hitting a wall trying to figure that one out.  

Ok... documentation.  I'm on it!

**Comment by seanknox** [comment]
Managed disk support is now in Kubernetes v1.7.2 which should allow us to fix this.

**Comment by seanknox** [comment]
This is solved in three parts:
- [x] We've implemented managed disks on masters in https://github.com/Azure/acs-engine/issues/1027. 
- [x] Merge managed disks into upstream Kubernetes. This is available starting in Kubernetes v1.7.2.
- [ ] We also need to implement managed disks on the nodes/agents themselves (for their own filesystems)

**Comment by lachie83** [comment]
This has been release #1072
