### ISSUE TITLE
Polish `deploy` command

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#872]
Some cleanup + polish tasks for the `deploy` command before we document and promote it more:
 
- [ ] Support auto-fill for SSH key
- [ ] Support auto-fill for cluster name (derived from RG name)
- [ ] Support auto-fill for SP creds
- [ ] Cleanup UX for the output (there’s a few places where the wrong output formatter is used and looks sloppy)

**Comment by colemickens** [comment]
@seanknox Can I send this this week? I've implemented all 4 of these things in a branch. Or would you prefer I hold off for a different release?

**Comment by seanknox** [comment]
Let's do it. 👍

**Comment by colemickens** [comment]
Drat. I forgot I had to hack around the validation code because it's... oddly tied to the deserialization process. I need to refactor a bit more before this can be submitted. I'll do it tonight and get a PR out, tired of rebasing it :).

**Comment by seanknox** [comment]
No worries or rush—let's push to next release officially, merge in at your leisure.
