### ISSUE TITLE
Pin to specific versions of azure-cli

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#877]
Recently we discovered that a [newer version of azure-cli broke scripts](https://github.com/Azure/acs-engine/issues/811) we use for internal development and testing. We should pin to the latest "blessed" version of azure-cli to prevent upstream changes from breaking acs-engine.

**Comment by seanknox** [comment]
We already do this in the Dockerfile, so maybe it's enough to call out a specific version in the README.

**Comment by jackfrancis** [comment]
This is done.
