### ISSUE TITLE
"prereqs" is missing from the "build" rule in the Makefile.

### ISSUE THREAD

**Issue by jsilberm** [Azure/acs-engine#880]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:

pkg/acsengine/fileloader.go:3: running "go-bindata": **exec: "go-bindata": executable file not found** in $PATH

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by seanknox** [comment]
Addressed in #881.
