### ISSUE TITLE
Update Linux script extensions to the recommended "Microsoft.Azure.Extensions" "CustomScript"

### ISSUE THREAD

**Issue by ivanthelad** [Azure/acs-engine#890]
Feature 
The current extension used by the docker swarm(possibly used by kubenetes and mesos also) is using a extension that is not recommened 
https://github.com/Azure/azure-linux-extensions/tree/master/CustomScript

The recommendation is to use this extension instead https://github.com/Azure/custom-script-extension-linux. 

`    "properties": {
        "publisher": "Microsoft.OSTCExtensions",
        "settings": {
          "commandToExecute": "[variables('masterCustomScript')]",
          "fileUris": []
        },
        "type": "CustomScriptForLinux",
        "typeHandlerVersion": "1.4"
      }` 

New version 
``

           {
                "name": "Microsoft.Azure.Extensions.CustomScript",
                "properties": {
                  "publisher": "Microsoft.Azure.Extensions",
                  "type": "CustomScript",
                  "typeHandlerVersion": "2.0",
                  "autoUpgradeMinorVersion": true,
                  "settings": {
                    "fileUris": [ ],
                    "commandToExecute": "[variables('nodeProxySetupScript')]"
                  }
                }

              }
``

**Comment by JackQuincy** [comment]
We moved k8s over 3 months ago. I'm not sure when our team will get to this. but if you could make the change, test the change, then submit a PR for it. This is something we want to do.
