### ISSUE TITLE
Use Azure Instance Metadata service

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#896]
We should explore using the new Azure Instance Metadata service to provide instance metadata for the kubelet + cloud provider.

**Comment by seanknox** [comment]
Bumping this up for the v0.4.0 milestone. @amanohar @colemickens where could we find more information about using the AIM? Feel free to follow-up offline if you prefer.

**Comment by amanohar** [comment]
@seanknox , pinging you offline with more details.
