### ISSUE TITLE
Support Kubernetes network policies

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#897]
Users need to be able to specify of how groups of pods are allowed to communicate with each other and other network endpoints. This is enabled by three parts:

1. enable the `extensions/v1beta1/networkpolicies` runtime config in your apiserver
2. a controller that acts on Network policies
3. the actual network policies

**Comment by dcieslak19973** [comment]
Would this enable CNI on Kubernetes, such that one could install something like WeaveNet?

https://www.weave.works/docs/net/latest/kube-addon/

**Comment by seanknox** [comment]
@lachie83 is this enabled currently via calico?

**Comment by lachie83** [comment]
This will be fully working once this is merged -- https://github.com/Azure/acs-engine/pull/1013

**Comment by lachie83** [comment]
Docs here -- https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md#optional-enable-network-policy-enforcement-using-calico

**Comment by dtzar** [comment]
Linking the calico issues together here #1417 and #1197
