### ISSUE TITLE
Agent Pools Only

### ISSUE THREAD

**Issue by kris-nova** [Azure/acs-engine#900]
### Overview

We would like a way to generate the ARM templating for agent pools only. We will need to pass in a Kubernetes master API endpoint at runtime. We will also need to pass in TLS certificate information at run time as well.

### Success Criteria

 - As an ACS engine user I can generate arm templates that will deploy an arbitrary agent pool independently of a master infrastructure.
 - As an ACS engine user I can conveniently pass in TLS certificate data, as well as a publicly resolvable API endpoint for an existing master. The new agent pools will automatically be configured to work with the existing master infrastructure.
 - As an ACS engine user I can easily find documentation on how to achieve this
 - As an ACS engine developer I can easily find and run tests that ensure this functionality works

**Comment by JackQuincy** [comment]
Would this better fit under a project? instead of an issue?

**Comment by seanknox** [comment]
@JackQuincy This is placeholder issue that will be delivered in chunks. As a first step, there will be some refactoring work that makes feature work easier for contributors: https://github.com/Azure/acs-engine/issues/902

**Comment by yangl900** [comment]
It would be nice if it can generate template of single agent, but agentpool is a good start.

**Comment by jackfrancis** [comment]
AKS!

**Comment by marcelfalliere** [comment]
@jackfrancis does AKS support microsoft based docker images ?

**Comment by jackfrancis** [comment]
@marcelfalliere Not sure I understand the question. An AKS Kubernetes cluster is able to schedule any general purpose docker container image. Do you mean a Windows container image? If so, the answer is "not yet".
