### ISSUE TITLE
Kubernetes Specific API Definitions 

### ISSUE THREAD

**Issue by kris-nova** [Azure/acs-engine#902]
### Overview

Technical chore to extract kubernetes specific API definitions into aliased and concrete implementations of the existing vlabs model.

### Success Criteria 

- Existing API models continue to function as is today
- Backwards compatibility with all api models in vlabs 
- Concrete implementation of Kubernetes profiles for the following 
  - AgentPoolProfile
  - MasterProfile
  - ServicePrincipleProfile
  - LinuxProfile
 - Only Kubernetes affected by decoupling initiative (DCOS and swarm remain unchanged)

**Comment by CecileRobertMichon** [comment]
@seanknox can I close this issue?

**Comment by seanknox** [comment]
Yep!
