### ISSUE TITLE
High disk IO load with large volumes - Specifying kubelet options?

### ISSUE THREAD

**Issue by DonMartin76** [Azure/acs-engine#906]
**Is this a request for help?**:

yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature Request, I think, if it's not already implemented, but not documented.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.5.7

**What happened**:

We are experiencing intermittent slowness, which is most probably due to the cluster checking volume statistics using the `du` command (I think it's heapster who does this in the end), and as some of our volumes have really **vast** amounts of files (>500 GB of files), this eats up the IOPS on the persistence server (an NFS VM), which in turn slows down the entire cluster.

**What you expected to happen**:

I would like to be able to specify a `kubelet` option, most specifically `--volume-stats-agg-period=0` to turn off the gathering of these statistics. We have monitoring of that anyway, so it doesn't hurt at all to switch it off (we hope).

**How to reproduce it** (as minimally and precisely as possible):

This is not that simple, I fear, as you need a lot of files; a single run of `du` (as we gathered in the logs) on certain volumes ran over ten minutes(!), spiking the CPU of the NFS server.

**Anything else we need to know**:

Related Issues in Kubernetes:
https://github.com/kubernetes/kubernetes/issues/23255 (The discussion after this was closed sounds very familiar)
https://github.com/kubernetes/kubernetes/issues/47928 (This can be the same thing, but I'm not sure)

**Comment by jackzampolin** [comment]
Just to add my 2c we are running into something similar on our `acs-engine` cluster

**Comment by hmarcelodn** [comment]
Exactly the same issue here
