### ISSUE TITLE
Automatically create service principal

### ISSUE THREAD

**Issue by kris-nova** [Azure/acs-engine#912]
### Overview

Right now the Kubernetes JSON file **requires** a user to support creating and managing a service principal independently of `acs-engine`. This feature would allow users to **optionally** define an existing service principal. If no service principal is defined by the user, the new `acs-engine` feature would create one at runtime and use the newly created service principal credentials for the cluster.

### Success Criteria

 - Continue to support `ServicePrincipalProfile` as it exists today.
 - Begin supporting API models without `ServicePrinicpalProfile` defined

### Concerns/Questions
 - When/how could we generate a service principal? 
 - Would this happen at runtime during `acs-engine generate`? Or in the ACS RP?

**Comment by weinong** [comment]
IIRC, spn can only be created by user account. So this feature will probably not work in the RP.

**Comment by weinong** [comment]
likewise, if user of acs-engine uses spn with client_secret or client_certificate auth, it will probably not work.

**Comment by amanohar** [comment]
@weinong SPN should be creatable on behalf of the user by ACS RP unless I am missing something.

**Comment by amanohar** [comment]
@colemickens can you comment on this?

**Comment by weinong** [comment]
I just tried. 
az login with spn
az ad sp create --id http://test-spn.com
`Insufficient privileges to complete the operation.`

So, no, I don't think it will work.

**Comment by seanknox** [comment]
This will be really helpful for users, though appears that there's significant work needed both in acs-engine and the ACS RP to support.

**Comment by amanohar** [comment]
@weinong looks like the role didn't have the right privilege but RP can get the right privilege to do this on behalf of the user.

**Comment by weinong** [comment]
@amanohar It'd be great if that's the case.
