### ISSUE TITLE
LoadBalancerFrontendIPConfigurationCountLimitReached but total exposed microservices are 4

### ISSUE THREAD

**Issue by mfaizanse** [Azure/acs-engine#916]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes : 1.5.3

**What happened**:
I am receiving Exception "LoadBalancerFrontendIPConfigurationCountLimitReached" when exposing a kubernetes service using LoadBalancer. I deployed multiple pods and exposed them using load balancer, but then I deleted the services and currently only 4 kubernetes services are exposed using LoadBalancer. But when I try to expose a 5th service, it is saying that the limit has been reach. I know the default limit is 10 IPs but I deleted the previously exposed services. My question is that when we delete a kubernetes service, does it removes the IP address from the load balancer at the same time or it is deleted after some delay? If it deletes the IP at the same time then why in my case it failed to do so?

**What you expected to happen**:
When we delete a kubernetes service, it should remove the IP address from the load balancer at the same time.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I tried to delete the unused IP addresses using azure portal but it return an error: 
`Fail to delete public IP adresss. [name] can not be deleted since it is still allocated to resource [resource name].`

**Comment by yangl900** [comment]
It does remove the public IP (it's async process), but I do observe leaking in a few cases. Especially when you re-create the service using same name. 

To mitigate the issue, you will need find the load balancer, and remove the load balancing rules of the leaked public IP and then remove the leaked public IP from frontend IP pool. Only after these 2 step you can then delete the public IP.

**Comment by chribsen** [comment]
+1

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).

**Comment by palmerabollo** [comment]
@mboersma We still face this issue with recent versions of aks-engine. Should we reopen this issue in the new repository?

**Comment by mboersma** [comment]
@palmerabollo yes, please. It would help to have a fresh issue with current steps to reproduce to focus on.
