### ISSUE TITLE
Intent to Implement: Change how versioning is handled

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#921]
Versioning will be changed such that:
* User now specifies `orchestratorVersionHint` (examples: `1.5`, `1.6`). At deploy time, it is resolved to a concrete version (`1.6.6`).
* Upgrade API allows for same minor version to be specified. It can then either do a full upgrade, or just a patch version level upgrade, based on what it knows is the highest resolvable version at the time of upgrade being called

This will require changes to the api models for vlabs, and the 2017-07-01 API. But this is fine because we haven't really fully gone live with these fields in that api version.

**Comment by rjtsdl** [comment]
I have assigned both @JiangtianLi  and I on this issue. I will primarily work on this though.

**Comment by rjtsdl** [comment]
@seanknox , this will have api model change. Give a thumb up ?

**Comment by seanknox** [comment]
:+1: go for it.
