### ISSUE TITLE
k8s: windows agent node should install official RS1 patch for network stack instead of private bits

### ISSUE THREAD

**Issue by yangl900** [Azure/acs-engine#937]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**: 
Windows agent node contains a private patch for network module. According to windows team an official patch has been released and should use that instead.

The latest patch installed on the machine was from May. So the machine is out of date by a month.
The fix for issue 2 you mentioned below was shipped in 6C. So you can remove the private from your machine and install the official package from Windows10.0-KB4022723-x64.msu
Installing the patch above will fully update the machine with the latest patches.

**What you expected to happen**:
Install official patch, get rid of private bits.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by PatrickLang** [comment]
This fix was rolled out into the Windows Server 2016 with Containers image a long time ago. Closing
