### ISSUE TITLE
k8 dashboard does not come up for version 1.6.6

### ISSUE THREAD

**Issue by rajpolaris** [Azure/acs-engine#941]
This is a request for help.
I am having an issue similar to this issue that was reported and closed previously.
https://github.com/Azure/acs-engine/issues/560

I took the latest version of acs-engine and tried to provision a new cluster in an existing vnet.
deployment was successful.

It is in west us.

I can get into the master node.
I also downloaded the config file and can run kubectl remotely

bash-4.3# kubectl get nodes
NAME                       STATUS                     AGE       VERSION
k8s-agentpri-23283249-0    Ready                      7h        v1.6.6
k8s-agentpri-23283249-1    Ready                      7h        v1.6.6
k8s-agentpri2-23283249-0   Ready                      7h        v1.6.6
k8s-agentpri2-23283249-1   Ready                      7h        v1.6.6
k8s-master-23283249-0      Ready,SchedulingDisabled   7h        v1.6.6
k8s-master-23283249-1      Ready,SchedulingDisabled   7h        v1.6.6
k8s-master-23283249-2      Ready,SchedulingDisabled   7h        v1.6.6

**What happened**:

bash-4.3# kubectl get pods --namespace kube-system
NAME                                            READY     STATUS             RESTARTS   AGE
heapster-v1.2.0-1994216852-9wxrj                2/2       Running            0          7h
kube-addon-manager-k8s-master-23283249-0        1/1       Running            0          7h
kube-addon-manager-k8s-master-23283249-1        1/1       Running            0          7h
kube-addon-manager-k8s-master-23283249-2        1/1       Running            0          7h
kube-apiserver-k8s-master-23283249-0            1/1       Running            0          7h
kube-apiserver-k8s-master-23283249-1            1/1       Running            0          7h
kube-apiserver-k8s-master-23283249-2            1/1       Running            0          7h
kube-controller-manager-k8s-master-23283249-0   1/1       Running            1          7h
kube-controller-manager-k8s-master-23283249-1   1/1       Running            2          7h
kube-controller-manager-k8s-master-23283249-2   1/1       Running            1          7h
kube-dns-v20-5q3sc                              1/3       CrashLoopBackOff   202        7h
kube-dns-v20-8zdsn                              1/3       CrashLoopBackOff   203        7h
kube-proxy-2755x                                1/1       Running            0          7h
kube-proxy-43lg9                                1/1       Running            0          7h
kube-proxy-4f7f1                                1/1       Running            0          7h
kube-proxy-9b91k                                1/1       Running            0          7h
kube-proxy-lzlv6                                1/1       Running            0          7h
kube-proxy-t6gds                                1/1       Running            0          7h
kube-proxy-x5k01                                1/1       Running            0          7h
kube-scheduler-k8s-master-23283249-0            1/1       Running            1          7h
kube-scheduler-k8s-master-23283249-1            1/1       Running            2          7h
kube-scheduler-k8s-master-23283249-2            1/1       Running            1          7h
kubernetes-dashboard-3995387264-h089l           0/1       CrashLoopBackOff   87         7h

So DNS and dashboard did not come up.

There was no output for
sudo journalctl -u kubelet | grep --text autorest

bash-4.3# kubectl logs kubernetes-dashboard-3995387264-h089l --namespace kube-system
Using HTTP port: 8443
Creating API server client for https://10.0.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.0.0.1:443/version: dial tcp 10.0.0.1:443: i/o timeout
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

**What you expected to happen**:
I expected the cluster to come up. I expected dns and dashboard to be available

**How to reproduce it** (as minimally and precisely as possible):
Just take the latest acs engine.
Deploy the cluster to an existing VNET
VNET does not have any NSG's

**Anything else we need to know**:

Here is my input file used to generate the template
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "sentk8west",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/xxxxxxxx/resourceGroups/k8west/providers/Microsoft.Network/virtualNetworks/KubernetesCustomVNET/subnets/KubernetesSubnet",
      "firstConsecutiveStaticIP": "10.239.255.239" 
    },
    "agentPoolProfiles": [
      {
        "name": "agentpri",
        "count": 2,
        "dnsPrefix": "",
        "vmSize": "Standard_D2_v2",
        "vnetSubnetId": "/subscriptions/xxxxxxxxx/resourceGroups/k8west/providers/Microsoft.Network/virtualNetworks/KubernetesCustomVNET/subnets/KubernetesSubnet",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks"
      },
      {
        "name": "agentpri2",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "vnetSubnetId": "/subscriptions/xxxxxxxxxx/resourceGroups/k8west/providers/Microsoft.Network/virtualNetworks/KubernetesCustomVNET/subnets/KubernetesSubnet",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "xxxx"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "servicePrincipalClientID": "xxxx",
      "servicePrincipalClientSecret": "yyy"
    }
  }
}

I did not enforce network policy with calico.

My service principal should be good. I created it like this.

az login
az account set --subscription="${SUBSCRIPTION_ID}"
az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/${SUBSCRIPTION_ID}"

Let me know if you have any suggestions for me.
Error implies that my cluster is misconfigured.

**Comment by rajpolaris** [comment]
I wanted to share the logs from failed dns container

bash-4.3# kubectl logs kube-dns-v20-8zdsn --namespace kube-system -c kubedns
I0709 14:40:49.385352       1 dns.go:48] version: 1.14.3-4-gee838f6
I0709 14:40:49.386462       1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I0709 14:40:49.386517       1 server.go:113] FLAG: --alsologtostderr="false"
I0709 14:40:49.386531       1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I0709 14:40:49.386536       1 server.go:113] FLAG: --config-map=""
I0709 14:40:49.386539       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I0709 14:40:49.386547       1 server.go:113] FLAG: --config-period="10s"
I0709 14:40:49.386551       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0709 14:40:49.386554       1 server.go:113] FLAG: --dns-port="10053"
I0709 14:40:49.386578       1 server.go:113] FLAG: --domain="cluster.local."
I0709 14:40:49.386583       1 server.go:113] FLAG: --federations=""
I0709 14:40:49.386587       1 server.go:113] FLAG: --healthz-port="8081"
I0709 14:40:49.386590       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I0709 14:40:49.386599       1 server.go:113] FLAG: --kube-master-url=""
I0709 14:40:49.386603       1 server.go:113] FLAG: --kubecfg-file=""
I0709 14:40:49.386606       1 server.go:113] FLAG: --log-backtrace-at=":0"
I0709 14:40:49.386616       1 server.go:113] FLAG: --log-dir=""
I0709 14:40:49.386619       1 server.go:113] FLAG: --log-flush-frequency="5s"
I0709 14:40:49.386660       1 server.go:113] FLAG: --logtostderr="true"
I0709 14:40:49.386663       1 server.go:113] FLAG: --nameservers=""
I0709 14:40:49.386666       1 server.go:113] FLAG: --stderrthreshold="2"
I0709 14:40:49.386669       1 server.go:113] FLAG: --v="2"
I0709 14:40:49.386672       1 server.go:113] FLAG: --version="false"
I0709 14:40:49.386677       1 server.go:113] FLAG: --vmodule=""
I0709 14:40:49.386711       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I0709 14:40:49.386767       1 server.go:200] Skydns metrics not enabled
I0709 14:40:49.386775       1 dns.go:147] Starting endpointsController
I0709 14:40:49.386778       1 dns.go:150] Starting serviceController
I0709 14:40:49.386860       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0709 14:40:49.386874       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0709 14:40:49.887030       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:50.387026       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:50.887052       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:51.387001       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:51.887040       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:52.387056       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:52.886999       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:53.386965       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:53.887008       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:54.386970       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:54.887033       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:55.387014       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:55.887001       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:56.387023       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:56.886994       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:57.387040       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:57.887012       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:58.386986       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:58.886991       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:59.386966       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:40:59.887033       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:00.387023       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:00.887047       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:01.387033       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:01.887011       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:02.386974       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:02.886960       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:03.386985       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:03.887042       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:04.386974       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:04.886958       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:05.387081       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:05.886934       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:06.387012       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:06.886988       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:07.386973       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:07.886958       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:08.387075       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:08.887035       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:09.386999       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:09.886993       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:10.387018       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:10.887023       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:11.387055       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:11.887065       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:12.386971       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:12.887043       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:13.387004       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:13.887053       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:14.386996       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:14.887015       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:15.386959       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:15.887031       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:16.386959       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:16.887030       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:17.387001       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:17.887008       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:18.386970       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:18.887090       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:19.386896       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0709 14:41:19.388231       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0709 14:41:19.388569       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
I0709 14:41:19.887034       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:20.386960       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:20.887133       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:21.387013       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:21.886949       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:22.386976       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:22.887050       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:23.387071       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:23.887034       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:24.386993       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:24.887020       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:25.387017       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:25.886991       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:26.387010       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:26.887013       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:27.386980       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:27.887025       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:28.386922       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:28.886983       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:29.386981       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:29.887010       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:30.386987       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:30.887027       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:31.387029       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:31.887034       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:32.386986       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:32.887009       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:33.386967       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:33.886949       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:34.386937       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:34.886930       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:35.387014       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:35.887026       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:36.386974       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:36.887086       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:37.387051       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:37.887022       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:38.387022       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:38.887054       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:39.387038       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:39.887061       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:40.386985       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:40.887058       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:41.387051       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:41.887064       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:42.387024       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:42.887054       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:43.387050       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:43.887015       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:44.386955       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:44.887043       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:45.387003       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:45.886996       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:46.386983       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:46.887009       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:47.387000       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:47.887066       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:48.386955       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0709 14:41:48.886979       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
F0709 14:41:49.386975       1 dns.go:168] Timeout waiting for initialization

**Comment by rajpolaris** [comment]
I did not define a network policy. I was wondering if I still have to do the workaround mentioned in step 7 here https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md

It says that after cluster has been created I need to get the route table name and update the subnet property to refer to the subnet. My problem is that when I look in azure  resource explorer to get the route table name there are 7 routes ( one of each VM). So which route do I need to use to update the subnet property?
Do I need to even do workaround if I did not use network policy?

**Comment by rajpolaris** [comment]
I created a new cluster where I still used acs-engine but I did not deploy to custom vnet. So the problem is related to deploying to custom vnet.

**Comment by rajpolaris** [comment]
here is the error I get when accessing the dashboard

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

**Comment by rajpolaris** [comment]
This issue was caused by the fact that route table created by the deployment was not associated with subnet. Once I manually associated the route table with the subnet and waited a few minutes my DNS and dashboard started working. Sharing this here so others will not have to waste their time like I did.

**Comment by rossedman** [comment]
@rajpolaris Thanks a lot. I just ran into this and I am hoping this is my answer
