### ISSUE TITLE
guaranteed scheduling of critical add-ons requires a **Rescheduler** pod

### ISSUE THREAD

**Issue by pidah** [Azure/acs-engine#944]
---

**Is this an ISSUE or FEATURE REQUEST?** ISSUE
The kube-dns ( and also heapster and calico) deployment config yaml contain the following annotation:
      `annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: "[{\"key\":\"CriticalAddonsOnly\",\"operator\":\"Exists\"}]"`
According to the docs here: https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/ , guaranteed scheduling of critical add-ons requires a **Rescheduler** pod to be running. An example Rescheduler manifest is available here: https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest
 
I am unable to find a rescheduler pod in acs-engine. Is the rescheduler no longer required ?

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes 1.6.2

**Comment by brendandburns** [comment]
No rescheduled is a good idea. We should add one in.

**Comment by lachie83** [comment]
I'll pick this up.

**Comment by jackfrancis** [comment]
@CecileRobertMichon you may benefit from taking advantage of Lachie's start here: https://github.com/Azure/acs-engine/pull/1024
