### ISSUE TITLE
CI should skip docs only changes

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#952]
We don't need to CI to run on changes to docs only. The kubernetes project accomplishes this with a "retest-not-required-docs-only" label applied to PRs that are documentation only.

**Comment by seanknox** [comment]
@dmitsh FYI.

**Comment by jackfrancis** [comment]
We don't have a clean way to do this programmatically at the moment. As a pattern, project admins try to do this manually with admin merge override.
