### ISSUE TITLE
Test/CI subscription quotas are monitored

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#958]
> As a product manager,
> I want to be notified when our test subscription is at or near Azure quota limits
> so I can take action before it affects CI

## Acceptance Criteria
- Key Azure quota limits are continuously monitored and when above thresholds, are reported to the ACS Engine product team
- There is a dashboard to see current quotas

I would like to use a preexisting solution already in place at Microsoft/ACS.

TBD: 
- what metrics to monitor? `MaxStorageAccountsCountPerSubscriptionExceeded`, etc.?

**Comment by seanknox** [comment]
What's the full list of quotas we should monitor? `MaxStorageAccountsCountPerSubscriptionExceeded` for starters. cc @dmitsh @colemickens @amanohar

**Comment by seanknox** [comment]
Dmitry kicked off an email to ARM folks. Will update story once we know more.

**Comment by dmitsh** [comment]
Implemented via ActivityLog Monitors

**Comment by seanknox** [comment]
@dmitsh can you elaborate on the monitoring solution as you understand it? Specifically looking to understand:

- What metrics will be monitored
- What is the user interface/dashboard to see them
- What kind of notifications can we configure (Slack, email, etc.)

Feel free to discuss offline if better.

**Comment by mboersma** [comment]
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).
