### ISSUE TITLE
Support for AzureGerman/Custom Clouds

### ISSUE THREAD

**Issue by iMelnik** [Azure/acs-engine#96]
Hi,
Trying to run ACS on AzureGermanCloud and found some missing parts:

- [/parts/kubernetesmastercustomscript.sh#L53](https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastercustomscript.sh#L53) lacks `"cloud": "${CLOUD_NAME}"`, essential to get kubelet working
- generated certificates do not have custom domains like cloudapp.microsoftazure.de
- generated ubuntu version is no longer available, "osImageVersion": "16.04.201610200" runs fine

All of this could be done by hand, but fixing this would be nice.
Thanks!

**Comment by rgardler** [comment]
I'm sorry we did not respond to this in a timely way. Azure German Cloud is not currently supported. Though it is on the roadmap as you can imagine.

Your report is very helpful, thank you. We accept patches too if you try the above  fixes and find they work.

**Comment by anhowe** [comment]
@iMelnik - we now have support for China cloud thanks to @wangtt03.  If you are able to submit a PR, look at https://github.com/kubernetes/kubernetes/pull/41487 as an example.

**Comment by wangtt03** [comment]
@anhowe, i think i can work with @iMelnik to add German cloud support

**Comment by anhowe** [comment]
that would be great, thanks @wangtt03

**Comment by iMelnik** [comment]
@anhowe @wangtt03 thanks for your replies. I no longer have access to Azure Germany, therefore unable to test it.

**Comment by anhowe** [comment]
related to #450 and #451

**Comment by raulfiru** [comment]
i can confirm that it is still there....

met @colemickens at kubecon europe and went though installing one on azure germany. it works if i ssh on the master node and use "-s http://localhost:8080" but it's not really usable

i can help with testing

**Comment by colemickens** [comment]
Closing in favor of the more specific issues.
