### ISSUE TITLE
Windows container takes long time to start

### ISSUE THREAD

**Issue by robbiezhang** [Azure/acs-engine#960]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.3.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.6.6

**What happened**:
Windows container needs 2-10 minutes to get into the "Running" state from "ContainerCreating" state, even if the image has already been pulled to the node.
From the `kubectl describe`, it just stuck at the "Created container with docker id xxxx" state during the waiting.

```
  FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                    -------------                   --------        ------          -------
  2m            2m              1       default-scheduler                                       Normal          Scheduled       Successfully assigned cc-a65a-2a9d1a1a-1497672518-24q7m to o01wcacs9031
  2m            2m              1       kubelet, o01wcacs9031   spec.containers{console-agent}  Normal          Pulled          Container image "cloudcondfwestcentralus.azurecr.io/azconsole-agent-win:master_20170615.1" already present on machine
  2m            2m              1       kubelet, o01wcacs9031   spec.containers{console-agent}  Normal          Created         Created container with docker id eb44d51b5468
```

**What you expected to happen**:
Windows container should start immediately when the image is pulled.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by seanknox** [comment]
Same question here: which version were you using prior to v0.3.0 before you noticed this issue?

**Comment by robbiezhang** [comment]
It seems like an issue in k8s 1.6.6. Previously, we use ACS-Engine v0.1.2 with k8s 1.6.2 and 1.5.3, it works fine.

**Comment by yangl900** [comment]
Note that when it taking long time to start, I observed this error:

Error syncing pod, skipping: failed to "StartContainer" for "server" with RunContainerError: "runContainer: operation timeout: context deadline exceeded"

and the second retry of creating container succeeded quickly.

**Comment by seanknox** [comment]
> context deadline exceeded

I've seen this issue with Kubelet can't talk to the Docker daemon, usually around high CPU load. Might not be related but just noting...

**Comment by seanknox** [comment]
Follow-up here: this appears to be a Windows VM regression, connected to https://github.com/Azure/acs-engine/issues/959.

**Comment by seanknox** [comment]
Confirmed that even with https://github.com/Azure/acs-engine/pull/967 nanoserver takes 5 minutes to start, though it's only 383 MB.

**Comment by seanknox** [comment]
Possibly related, upstream issue where Windows pods are stuck in pending for a long time: https://github.com/kubernetes/kubernetes/issues/48193

**Comment by jackfrancis** [comment]
@robbiezhang Is this still an observable issue?

**Comment by jackfrancis** [comment]
Closing this with the rollout of RS3 @JiangtianLi
