### ISSUE TITLE
Windows Kubernetes binaries in upstream

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#963]
We currently build and maintain custom Kubernetes binaries for Windows  (fork here: https://github.com/JiangtianLi/kubernetes/tree/k8swin166). We should explore handling this upstream in kubernetes/kubernetes.

Question: what patches are needed in upstream?

**Comment by jsturtevant** [comment]
Is it still necessary to maintain a custom Kubernetes binaries for Windows Fork with the recent release of 1.9 which took care of the networking and volume limitations?

**Comment by JiangtianLi** [comment]
@jsturtevant From 1.9, all windows binaries are taken from upstream. For 1.7 and 1.8, we are still maintaining our Azure fork (https://github.com/Azure/kubernetes)
