### ISSUE TITLE
Add ServicePrincipalProfile.KeyvaultSecretRef for KeyVault secret reference

### ISSUE THREAD

**Issue by weinong** [Azure/acs-engine#965]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---
Issue (Bug)
**What version of acs-engine?**:
---
HEAD

**What happened**:
To enable using keyvault reference for api version 2017-07-01 in RP, RP needs to perform a linked access check on the API model to avoid privilege escalation. Currently the fact that `ServicePrincipalProfile.Secret` is overloaded with secret string as well as KeyVault ref will fail the linked access check when secret string is used. The fix is to introduce a new property `ServicePrincipalProfile.KeyvaultSecretRef` specifically for KeyVault secret reference.

## Acceptance Criteria
- Add a new property in vlabs and in 20170701 schemas: `ServicePrincipalProfile.KeyvaultSecretRef`that contains an azure resourceID for a user's KeyVault, e.g. `/subscriptions/8ecadfc9-1111-4ea4-b855-0d9999f4d7c8/resourceGroups/ww-kv/providers/Microsoft.KeyVault/vaults/ww-kv-ukwest/secrets/spn`
- There should be unit tests
- There should be regression/integration tests to confirm this works—work with Dmitry for guidance
- Update the acs-engine documentation with example `KeyvaultSecretRef`

## Sean note:
- While the coding work is relatively small, I think there's going to be a significant amount of test coverage and documentation to write, so sizing this as a medium.

**Comment by seanknox** [comment]
Closed via #1022.
