### ISSUE TITLE
Windows VM images should use tagged version

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#968]
In https://github.com/Azure/acs-engine/commit/77dc4cdb9305160f1844c16b330ed8d5687b6748#diff-f18f17bd6f84d54a111be39c8fe59d54L187 we switched to using the "latest" tag of Windows VM versions from a version tag (2016.127.20170510). I believe this was to take advantage of security patches right away, but unfortunately by using latest, we have no idea what version of the VM artifact we're actually using. This end up causing at least one [bug](https://github.com/Azure/acs-engine/issues/959) that made Windows containers unusable.

## Acceptance Criteria
- Treat Windows VM images like any other external dependency by using specific images.
- Manually test that outbound internet works on pods with Windows nodes (we lack automated tests at the moment)

**Comment by seanknox** [comment]
@JiangtianLi what is the latest Windows VM version tag?

**Comment by anhowe** [comment]
closing, please ping @anhowe @seanknox offline for further explanation.
