### ISSUE TITLE
Tag created resources for Azure consumption

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#971]
> As a product manager
> I want to know which resources are created via ACS 
> so I can track growth of the service

## Acceptance Criteria
- All resources (VMs, LBs, etc.) created via acs-engine are tagged and can be reconciled using Microsoft analytics tools

**Comment by dcieslak19973** [comment]
Would you envision this as allowing the user to specify user-defined tags that will apply to all resources acs-engine creates?

**Comment by seanknox** [comment]
Initially this will just be used to help track ACS resources into a coherent billing picture, so tags won't be configurable. Do feel free to open a new issue if you'd like additionally tag functionality.

**Comment by sylus** [comment]
I was curious if there was any progress on this, right now be leverage cloudyn for our billing which is related to tags on various infra, we are unsure how we can get an accurate billing picture for dynamic workloads on k8s. Any guidance would be greatly appreciated!

**Comment by JeffreyGarrett** [comment]
I agree with @sylus.  Azure has suggested cloudyn for all billing and financial reports.  We have a script to add tags to all existing resources, but this means that we miss the ongoing new tags. We would like to add multiple tags to all resources to the cluster.  Additional benefits of adding different tags based on poolname or other more detailed needs.
