### ISSUE TITLE
Automatically install helm CLI on Linux master

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#974]
Follow-up from https://github.com/Azure/acs-engine/pull/924, which auto-installs the server-side Tiller component into new ACS clusters. This work would download and install the `helm` CLI tool on Linux master.

## AC:
- `helm` is installed and available on Linux master

Example install steps:
```
$ curl https://storage.googleapis.com/kubernetes-helm/helm-vX.Y.Z-linux-amd64.tar.gz
$ tar -zxvf helm-vX.Y.Z-linux-amd64.tgz
$ mv linux-amd64/helm /usr/local/bin/helm
```

**Comment by technosophos** [comment]
Is this installing Helm onto the nodes? Is there a reason why we would do this? That's not really the normal way you use Helm... though I suppose there's no harm in doing it.

**Comment by seanknox** [comment]
Oops, meant autoinstall to only happen on masters. My thought is it might be useful tool to have available for Cloud Shell. Not at all imperative though.

**Comment by JackQuincy** [comment]
? for it to be available it would need to be in the container the cloud shell team stands up. It being on the master is irrelevant to my knowledge.

**Comment by jackfrancis** [comment]
Please re-open if this is change will support additional, useful functionality for cloud shell users!
