### ISSUE TITLE
Use orchestrator type to run subset of functional tests

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#978]
We can be more tactical with integration tests run on each PR by running tests specific to the orchestrator. A Docker Swarm failure due to intermittent Azure failures shouldn't hold up Kubernetes development in HEAD. Between orchestrator tests, unit tests, manual tests, and the full regression suites that run every hour I feel good about this coverage in exchange for unblocking development.

**Comment by jackfrancis** [comment]
Not feasible to optimize this any further.
