### ISSUE TITLE
Question: Kubernetes and a custom VNET

### ISSUE THREAD

**Issue by mogthesprog** [Azure/acs-engine#99]
Hi Guys,

Great to see this open sourced (and in go)! I'm looking at using this package to deploy production kubernetes clusters, however the inability to deploy to a custom VNET in another resource group is a bit of a problem for us. I was wondering why this isn't possible? is it a constraint inherited from the resources deployed by the generated template, or a feature that needs adding in code? 

If it's a feature request in acs-engine then i'm happy to muck in and add this. If you can point me at the problem.

Cheers,

Morgan

**Comment by colemickens** [comment]
There's actually an example cluster definition that enables it: https://github.com/Azure/acs-engine/blob/master/examples/vnet/kubernetesvnet.json

However, I've not tested it and I've heard there might be a problem with it. If you want to give it a shot we can troubleshoot it if the cluster's not working at the end.

**Comment by mogthesprog** [comment]
Thanks for the speedy response!

Your response made me go back and have another look - **it works!**

So the reason i'd given up so easily was going off the warning on [this](https://github.com/Azure/acs-engine/blob/master/examples/vnet/README.md) page. I got an error, complaining that the resource (VNET) couldn't be found, even thought the IDs were correct, even though looking at the IDs, they were correct.

For me the issue was that i was deploying the cluster in a different region to the original vnet - oops.

I'll issue a pull request with the updated doc in a bit.

I'll close this now, thanks for the help. Do you have a roadmap or a list of tasks that need implementing? Happy to contribute.

Thanks again

**Comment by colemickens** [comment]
Can you please run some containers and make sure they start properly and let me know?

And docs PRs are hugely appreciated. We should get some sort of roadmap up for features we want to build. I'll make a note and try to add something soon.

**Comment by mogthesprog** [comment]
Yeah sure, i'll double check and post back here. Reopening...

**Comment by mogthesprog** [comment]
Yep, all seems to work. 

I first deployed to one of our dev environments, which has a locked down vnet/subnets, that failed. I then created a temporary vnet to test this out with no custom NSG rules, all was good. :) Ran a few pods fine.

Would you guy be interested in http_proxy support? I may spend some time tomorrow looking at how to add proxy support here. Looking at the templates, some script actions are called, plus the docker config would need to include the proxy... Also depends how etcd cluster is initiated too, if that calls out to a registration service then that would need it too. I'll have a good dig in the morning.

Thanks again for your help

**Comment by colemickens** [comment]
Is `http_proxy` meaning something that `docker` knows about to be able to `pull` through a restrictive firewall?

I don't think we have any need for it, but I think it's something we would consider merging, depending on the size of the change, how much it would take to support it, etc.

In the current kubernetes configuration, there is a single master that has etcd running as a systemd unit.

**Comment by rgardler** [comment]
+1000 for docs patches :-)

---
Twitter: @rgardler

________________________________

**Comment by mogthesprog** [comment]
Yeah as in proxy support for clusters that have to run in locked down networks, the same way we run our cluster on premise today. I wouldn't be surprised if we aren't the only ones interested in that support.

Thanks for the etcd notes. I only asked since on premise we run an etcd instance on each master (3 node masters) which runs in containers managed by the kubelet, so docker on those nodes have the proxy set.  I guess in this case it's not needed :) We do this as the hyperkube instances for controller-manager/api-server/scheduler also run in containers managed by the kubelet too. I'll have a dig around this cluster in the morning to see how it's currently configured.

**Comment by mogthesprog** [comment]
Will make a PR for docs tomorrow. :)

**Comment by colemickens** [comment]
Reopening this, I've had multiple reports that things aren't actually working right. Another person reported the same issue, the cluster might appear to be okay, but containers aren't actually getting scheduled. There was also an assertion that the route table wasn't getting updated as expected.

**Comment by mogthesprog** [comment]
No worries, yeah so i had a strange issue whereby the agent VMs weren't
being created properly - complaining that the storage account didn't exist.
So i thought there may have been a `dependson` statement missing from the
VMAS but that wasn't the issue. Still not sure what is casuing it but it's
intermittent. For the moment i'm putting it down to DNS updates in
repeatedly creating/destroying storage accounts. When the VMs are created
successfully it all seems to work fine for me.

I'll repeat the test in a new empty VNET in a different RG and report back
on what i see.

**Comment by anhowe** [comment]
VNET support is being fixed in #172

**Comment by colemickens** [comment]
This is now fixed by the merging of #172.
