### ISSUE TITLE
validation: refactor how internal model and validation are handled

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#996]
Changes to apimodel/validation/etc right now is painful due to the large amount of manual conversion code, the fact that validation code is all duplicated, and the highly coupled nature of validation and conversion to internal model makes things like intelligent default setting challenging. To make matters worse, the internal model today is not guaranteed to be fully populated so consumer code has to use extensive nil/empty checks.

Things that might help:

1. Consider a more strict internal model, where all fields are populated so that downstream consumers/tooling can just count on the value to be populated. This would require/enable some functions that can consume an invalid internal model and do intelligent defaulting to possibly make it valid (validation would occur after the defaults are set). This would clean up some of the code that was contributed for auto-deployment via `deploy.go`.

2. Validation and deserialization of the model into the unversioned model is highly coupled. I hacked something in for the `feat(autodeploy)` that will ignore validation and then re-perform it again at the end, but it definitely needs to be improved upon (it serialized the internal model and then deserializes it back into the unversioned model and validates it).

3. It may be worth consider using what Kubernetes uses to maintain the versioned<->unversioned code. We used to have tests that caught these things, but while implementing the MSI PR, I noticed that it was easy to miss some conversion code and introduce subtle bugs.

This would move us from:
> versioned model -> version specific validation -> internal model -> (still possible nulls, no default values saved for historical reference)

To:
> versioned model -> (with intelligent default settings) -> internal model -> validation -> (a complete representation of our internal model)

This would be fully populated for historic reference [rather than relying on the implicit default in ACS-Engine at the time of original deployment], and downstream code doesn't have to be littered with `nil` checks). This would be better to save in the Database in the RP as well. The apimodel captures user intent, but for management scenarios, it's important to know the complete "internal state" at deployment-time.

Consider how that impacts scenarios:
* upgrade where we want to track specific version that we are driving towards, but we only allow user to specify the minor version. Apimodel only captures their intent, but we need to know how we "resolved" that intent previously.
* we change the default networking plugin being deployed. The user then scales up. Today, they're probably going to get a broken cluster as new nodes would be deployed with the new implicit default in ACS-Engine.

**Comment by seanknox** [comment]
@jackfrancis @dmitsh @kris-nova FYI

**Comment by itowlson** [comment]
While some of the validation can be moved to the internal model by selecting appropriate defaults during conversion, there also seem to be some version-specific checks.  E.g. when using early API versions, the MasterProfile.Count is required to be 1, 3 or 5; in later versions (20170701 and vlabs) this restriction is removed.  So we can ensure that the internal model is fully populated and set defaults before validation, but it seems like we still need to have version-specific validations - does that reflect your thinking @colemickens?
